### ISSUE TITLE
上传多文件卡住

### ISSUE THREAD

**Issue by sammiler** [cloudreve/Cloudreve#1003]
![微信图片_20210908124107](https://user-images.githubusercontent.com/25954458/132448161-8af3e0ed-6047-45b1-bce4-0ae0c259842c.png)
![微信图片_20210908124219](https://user-images.githubusercontent.com/25954458/132448166-0518e004-c2df-423d-910e-41bd760925b0.png)

**Comment by HFO4** [comment]
3.5.0后优化了多文件上传性能
