### ISSUE TITLE
使用Webdav时，报500

### ISSUE THREAD

**Issue by HuangTD1995** [cloudreve/Cloudreve#1004]
账号密码应该是没问题的，接口返回code码500
![image](https://user-images.githubusercontent.com/50571663/132468007-35bb7bfd-0459-4bf2-92a6-29013e270c2b.png)

**Comment by HFO4** [comment]
能否开启 Debug 模式提供更详细的日志？

**Comment by HuangTD1995** [comment]
> 能否开启 Debug 模式提供更详细的日志？

这个要怎么开debug模式，直接跑源码吗？

**Comment by HuangTD1995** [comment]
> 能否开启 Debug 模式提供更详细的日志？

![image](https://user-images.githubusercontent.com/50571663/132499307-69728bd6-7edc-449b-b05d-7d04bed1b407.png)
显示没有权限，这个是我上传的文件，我直接在页面上下载也不行，又新上传了一个测试了下webdav就可以的，权限问题我也不知道怎么回事

**Comment by HuangTD1995** [comment]
> > 能否开启 Debug 模式提供更详细的日志？
> 
> ![image](https://user-images.githubusercontent.com/50571663/132499307-69728bd6-7edc-449b-b05d-7d04bed1b407.png)
> 显示没有权限，这个是我上传的文件，我直接在页面上下载也不行，又新上传了一个测试了下webdav就可以的，权限问题我也不知道怎么回事

找到问题了，是我之前启动的时候用的管理员启动的，感谢支持！！！
