### ISSUE TITLE
邮箱功能无法使用，已确定

### ISSUE THREAD

**Issue by rygzx2060** [cloudreve/Cloudreve#1005]
邮箱功能无法使用，已确定，用的宝塔自建邮局，使用wp和第三方程序都能正常发送邮件，但用cloudreve无法正常使用，提示邮件发送队列出现异常，我能确保防火墙密码等配置准确无误，错误提示i/o timeout ,10 秒后重置，但是实际上使用服务器去ping邮件服务器端口25完全通畅，
强制使用 SSL 连接勾选或则不勾选都无法使用，，网盘版本为最新版，宝塔邮局也为最新版，在其他地方使用邮局并没有任何问题，

**Comment by Cao0220** [comment]
你的后端报错是什么？
我是
 `邮件发送队列出现异常, x509: certificate is valid for *.net, not mail.*.net ,10 秒后重置`
