### ISSUE TITLE
阿里云盘

### ISSUE THREAD

**Issue by liuluping0106** [cloudreve/Cloudreve#1006]
大佬你好，请问是否有计划添加阿里云盘的支持啊！！！

**Comment by cxplay** [comment]
@liuluping0106 https://github.com/cloudreve/Cloudreve/issues/999#issuecomment-913322691

**Comment by cxplay** [comment]
@liuluping0106 提 issue 前请先使用搜索功能谢谢

**Comment by wangxiaoerYah** [comment]
无语了@liuluping0106 为啥你提的issue，都不去好好了解下能不能实现，已经稳定性如何呢？阿里官方都没给出api，连阿里云的挂载都要靠抓包token，你觉得这种东西稳定吗？说不定用着用着数据就没了。
