### ISSUE TITLE
文件导入更新时间戳

### ISSUE THREAD

**Issue by ghost** [cloudreve/Cloudreve#1008]
你好，请问可否考虑在导入文件的时候可以更新时间戳。
我在onedrive中做了修改，想之后用webdav同步到别的地方，如果时间戳不改，无法正常同步。

**Comment by wangxiaoerYah** [comment]
不太可行，cloudreve是作为储存的中间层来实现的，你直接到onedrive里面更改，怎么可能实时检测到更改。cloudreve的数据是在你的服务器的mysql里面的，时间是根据你在cloudreve里面的操作来定义的。和你直接用云储存是不同的。如果要实时检测文件更改，那就要和onedrive长时间保持连接，而不是像目前这样只是post get。你要实时check的话，微软直接把你账号ban了，你得不偿失。

**Comment by liuluping0106** [comment]
我的意思是，点击那个导入按钮的时候更新时间戳，又不是实时更新。你想想，你新文件能导入，旧文件修改了，其实相当于新文件只是同名，你不改时间戳合理么？？？

**Comment by imrelax** [comment]
我也对这个功能有需求。  因为我 经常更新的是 onedrive里面。
然后希望文件同步到 这边来。
其实 不需要实时。我觉得可以在后台做定时。
设置时间限制。多久更新一次。可以满足这个需求。
