### ISSUE TITLE
是否可以加入用户随机分配储存区

### ISSUE THREAD

**Issue by znc15** [cloudreve/Cloudreve#1009]
每次新用户进来都不会换储存区，导致一个区的api会爆炸，是否可以加入一个新用户随机分配储存区呢

**Comment by wangxiaoerYah** [comment]
在用户管理里面，为用户组添加储存策略。很明显随机策略是很糟糕的决定。

**Comment by znc15** [comment]
> 在用户管理里面，为用户组添加储存策略。很明显随机策略是很糟糕的决定。

不是，很明显，当文件量大的时候，我们请求量大到每天都要炸一次，而新用户自动切换储存，可以减少用户在一个储存上使用下载和上传的使用量 @wangxiaoerYah
