### ISSUE TITLE
希望分享链接可以和百度网盘那样可以直接复制链接和提取码。。

### ISSUE THREAD

**Issue by DMC-cmd997** [cloudreve/Cloudreve#1011]
希望分享链接可以和百度网盘那样可以直接复制链接和提取码。
每次生成的提取码都要另外复制，有点麻烦，能不能搞成那种一键生成链接和提取码的。

**Comment by cxplay** [comment]
相似 issue: https://github.com/cloudreve/Cloudreve/issues/852
