### ISSUE TITLE
文件名魔法变量新增 "不包含扩展名的文件名" 和 "扩展名" 变量

### ISSUE THREAD

**Issue by cxplay** [cloudreve/Cloudreve#1016]
在使用随机变量用来保持文件唯一性的时候添加为 {originname} 的话就只能在前缀添加 randomkey, 否则在文件末尾只会让扩展名错误, 然而默认又是依靠文件名首字母开始排序, 如果是需要依靠文件名的排序那么这样又会破坏排序.

希望能够将新增 "不包含扩展名的文件名" 与 "文件扩展名" 两种新变量.

**Comment by wangxiaoerYah** [comment]
在cloudreve里面排序不是靠储存桶里面的文件名。是靠储存在cloudreve数据库里面的源文件名。

**Comment by cxplay** [comment]
> 在cloudreve里面排序不是靠储存桶里面的文件名。是靠储存在cloudreve数据库里面的源文件名。

排序不是首要问题, 主要的问题在于要实现的是自动重命名将 random_key 加在文件名后面, 而不是扩展名后面.

**Comment by lsCoding666** [comment]
我也希望有这个功能，因为上传文件后会在onedrive里面进行查看和管理，或许这样会显得有些奇怪，但是如果以后数据库丢了的话还能从onedrive导入。
我自己就是在很多台服务器上部署cloudreve，然后用离线下载下载到onedrive的同一账号的同一路径下，然后去oneDrive看，如果使用了 {originname}_{ randomkey}的话在线预览不了，因为oneDrive不支持重命名后缀名。
至于为啥要在多台服务器部署oneDrive，当然是下载快啦

**Comment by lsCoding666** [comment]
至于为啥不用原始文件名，是因为有些时候也可能有相同的文件在同一资源下，或者有时下载不同资源到同一路径下的时候防止文件名冲突导致失败

> 我也希望有这个功能，因为上传文件后会在onedrive里面进行查看和管理，或许这样会显得有些奇怪，但是如果以后数据库丢了的话还能从onedrive导入。 我自己就是在很多台服务器上部署cloudreve，然后用离线下载下载到onedrive的同一账号的同一路径下，然后去oneDrive看，如果使用了 {originname}_{ randomkey}的话在线预览不了，因为oneDrive不支持重命名后缀名。 至于为啥要在多台服务器部署oneDrive，当然是下载快啦

**Comment by lsCoding666** [comment]
啊 新版本有aria2从机的功能了 美滋滋

**Comment by lsCoding666** [comment]
这个问题我自己添加2行代码解决了[models/policy.go](https://github.com/cloudreve/Cloudreve/blob/056de22edbd2f321c28e94a0f8687bda2e6f2250/models/policy.go)
```
// GenerateFileName 生成存储文件名
func (policy *Policy) GenerateFileName(uid uint, origin string) string {
	// 未开启自动重命名时，直接返回原始文件名
	if !policy.AutoRename {
		return policy.getOriginNameRule(origin)
	}

	fileRule := policy.FileNameRule

	replaceTable := map[string]string{
		"{randomkey16}":    util.RandStringRunes(16),
		"{randomkey8}":     util.RandStringRunes(8),
		"{timestamp}":      strconv.FormatInt(time.Now().Unix(), 10),
		"{timestamp_nano}": strconv.FormatInt(time.Now().UnixNano(), 10),
		"{uid}":            strconv.Itoa(int(uid)),
		"{datetime}":       time.Now().Format("20060102150405"),
		"{date}":           time.Now().Format("20060102"),
		"{year}":           time.Now().Format("2006"),
		"{month}":          time.Now().Format("01"),
		"{day}":            time.Now().Format("02"),
		"{hour}":           time.Now().Format("15"),
		"{minute}":         time.Now().Format("04"),
		"{second}":         time.Now().Format("05"),
	}

	replaceTable["{originname}"] = policy.getOriginNameRule(origin)
	replaceTable["{suffix}"] = path.Ext(origin)
	replaceTable["{originname_without_extension}"] = strings.TrimSuffix(origin, replaceTable["{suffix}"])
	fileRule = util.Replace(replaceTable, fileRule)
	return fileRule
}
```

![image](https://user-images.githubusercontent.com/73888354/152806848-b6f87144-46e3-4295-99f9-b3a96b889a68.png)
![image](https://user-images.githubusercontent.com/73888354/152806971-39ad811a-59d8-4340-a529-f776cdc1739a.png)

**Comment by lsCoding666** [comment]
![image](https://user-images.githubusercontent.com/73888354/152807809-0f48d521-2879-465e-b0a2-d4a9e1afb57c.png)
对于没有扩展名的文件，就直接在文件名末尾加上_和8位随机key

**Comment by wangking873** [comment]
文件扩展名 suffix 支持了吗？ 最新版本没看到啊
