### ISSUE TITLE
使用谷歌验证码的时候提示需要网站所有者处理的错误：密钥类型无效

### ISSUE THREAD

**Issue by rsnocsi** [cloudreve/Cloudreve#1018]
使用谷歌验证码的时候提示需要网站所有者处理的错误：密钥类型无效
我现在登录都登录不了，要怎么关闭这个谷歌验证码呢

**Comment by rongwing** [comment]
同问，使用腾讯验证码，验证码过期或别的原因导致验证码无法使用，导致无法登录，这种情况下怎么关闭验证码功能或使用Cloudreve自带验证码？

**Comment by alongw** [comment]
同样的问题，腾讯云验证码过期导致无法登录

**Comment by kangmingyang123** [comment]
我也一样
