### ISSUE TITLE
在没有登录的情况下打开分享链接页面会跳转到登录

### ISSUE THREAD

**Issue by 1262917464** [cloudreve/Cloudreve#1026]
（即便是登录状态下也可能会跳转）
因为这个问题我已经接收到一大堆账号注册轰炸了

**Comment by MagmaBlock** [comment]
+1,
的确是有这个BUG，新浏览器打开分享经常会跳到登录  即使访问这个分享不需要权限
因为这个问题给人分享文件有时候会造成不必要的误会
