### ISSUE TITLE
图片上传卡处理中

### ISSUE THREAD

**Issue by znc15** [cloudreve/cloudreve#1031]
3.3.2 Pro版本在一些未知情况下，上传.png .jpg等图片文件的时候，会卡在处理中。
存储是Onedrive。
套了CDN。
电脑和手机都是这样。

文件名：
后台日记：
[GIN] 2021/10/09 - 18:36:30 | 200 |    4.812807ms |  175.167.83.119 | GET      "/api/v3/directory/"
[GIN] 2021/10/09 - 18:36:30 | 200 |     3.37906ms |  175.167.83.119 | GET      "/api/v3/user/storage"
[GIN] 2021/10/09 - 18:36:31 | 200 |    2.429015ms |  175.167.83.119 | GET      "/api/v3/user/storage"
[GIN] 2021/10/09 - 18:38:15 | 200 |    7.184225ms |    121.5.219.20 | GET      "/"
[GIN] 2021/10/09 - 18:38:18 | 200 |    1.225053ms |     59.52.64.74 | GET      "/favicon.ico"
[GIN] 2021/10/09 - 18:40:29 | 200 |     3.47187ms |  175.167.83.119 | GET      "/api/v3/file/upload/credential?path=%2F&size=1114745&name=%5D_KP%40UW%5DV_6%40LXHPS%60%7BKL)U.png&type=onedrive"

图片
![D)FR~99C%T~F7XSK75B@9%Q](https://user-images.githubusercontent.com/64775575/136654851-9bd95641-5bae-4706-a1d5-64d5e4e6453d.jpg)

**Comment by happi0** [comment]
同样的问题, 每次上传完成后最后一个文件会卡很久，甚至卡到浏览器跳出来提示
![image](https://user-images.githubusercontent.com/86256628/149964064-ae326fcd-54a7-4257-9a5d-ec910d5664b5.png)
