### ISSUE TITLE
admin账户后台管理存在bug

### ISSUE THREAD

**Issue by BaiEJi** [cloudreve/Cloudreve#1032]
使用admin账号可以在后台将admin账号的登陆邮箱改为admin@xx（不用点后缀名的形式是可以通过的）

但是由于前端强制限制了登陆的邮箱格式，导致后台改了登陆邮箱为admin@xx（无后缀名）之后无法登录，只能重新安装网盘

**Comment by MagmaBlock** [comment]
![image](https://user-images.githubusercontent.com/61128045/140028981-0782d265-85c8-4967-8b4c-ce985d48dcff.png)
[https://docs.cloudreve.org/manage/db-script](url)
既然都是管理员了，为什么要乱折腾呢（
