### ISSUE TITLE
上传中文件无法取消

### ISSUE THREAD

**Issue by ARTAvrilLavigne** [cloudreve/Cloudreve#1042]
上传队列中一个大文件，点击取消没有任何反应。只能等待上传完成，关闭上传队列弹框，再次上传其他文件显示排列中，无法查询之前上传中的那个大文件

**Comment by TsinbeiTech** [comment]
好像取消键有问题，不管上传什么点取消都不会从队列里移出，没有反应。但是点了取消之后确实不会上传该文件了。

**Comment by zhangweibo413** [comment]
> 好像取消键有问题，不管上传什么点取消都不会从队列里移出，没有反应。但是点了取消之后确实不会上传该文件了。

我的也跟你一样，虽然不能从队列里移出，但右下角的数字却是能减少，但还是不方便，不知道到底哪个被移出队列了

**Comment by ggelua-cc** [comment]
等待修复吧

从 Windows 版邮件发送

发件人: zhangweibo413
发送时间: 2021年12月18日 12:19
收件人: cloudreve/Cloudreve
抄送: ggelua-cc; Comment
主题: Re: [cloudreve/Cloudreve] 上传中文件无法取消 (Issue #1042)

好像取消键有问题，不管上传什么点取消都不会从队列里移出，没有反应。但是点了取消之后确实不会上传该文件了。
我的也跟你一样，虽然不能从队列里移出，但右下角的数字却是能减少，但还是不方便，不知道到底哪个被移出队列了
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by HFO4** [comment]
3.5.0后已修复
