### ISSUE TITLE
希望能增加文件秒传功能

### ISSUE THREAD

**Issue by ARTAvrilLavigne** [cloudreve/Cloudreve#1043]
1、上传同一文件会重新上传一次并且再次占用同样大小的空间。希望能增加秒传的功能，比如通过比对MD5值
2、同一目录下上传相同的文件，上传一直卡在处理中....    界面无任何提示
后台打印日志：
![image](https://user-images.githubusercontent.com/30069579/140003130-96493614-d61f-4fb1-9648-227e2af65f5f.png)

**Comment by 709397578** [comment]
对的，我也希望添加这个功能，比如有50个人，他们都传了相同一个文件，这样会非常占用空间，如果有MD5文件指纹功能的话，有人上传了这个文件，再上传只需要链接过去这个文件就可以了，可以极大的减小存储空间，从而节省资源。
