### ISSUE TITLE
建议充分利用用户端的Cookie能力

### ISSUE THREAD

**Issue by chunfengyao** [cloudreve/Cloudreve#1045]
比如，保存用户的排序习惯，比如，保存用户上次观看的视频的位置。
现在每次设置了排序，都只是内存里记住了，一旦杀掉重新打开就又要重新设置。比较习惯于使用按时间排序。

**Comment by MagmaBlock** [comment]
+1
我的资源库是按年代建的文件夹  现在每次用都会去按一下按名称排序

**Comment by HFO4** [comment]
排序习惯现在已经可以记录在local storage里面
