### ISSUE TITLE
cloudreve网页, 日期显示bug

### ISSUE THREAD

**Issue by letterk** [cloudreve/Cloudreve#1047]
文件显示的日期, 都是创建时的日期
而非修改后的日期

显示创建日期毫无参考性

**Comment by yrjyrj123** [comment]
web端提供了部分编辑功能，如果编辑后能把显示的时间改一下，就更好了。
非web端的文件修改，比如在服务器上改了文件，应该属于异常情况，就不需要考虑了。

**Comment by letterk** [comment]
webdav功能就是非web端
不管是什么方式改的文件, 日期显示都应该是最近修改, 没见过默认日期是创建的
除非这个网盘的设计目标只是保存归档内容的, 那样日期就不重要

**Comment by yrjyrj123** [comment]
> webdav功能就是非web端 不管是什么方式改的文件, 日期显示都应该是最近修改, 没见过默认日期是创建的 除非这个网盘的设计目标只是保存归档内容的, 那样日期就不重要

我不赞同你的说法。
通过暴露的服务对文件进行修改，时间应该同步修改。
服务器维护等情况，让绕过对外服务，直接修改文件，比如对后端存储的文件进行了移动、病毒查杀、恢复等，显然不应该影响对外服务显示的文件时间。
更进一步，网盘如果要支持秒传等功能，必然伴随后端文件的复用，难道A上传的文件时间会因为B又传了一次而改变？还是B上传的文件，时间还是A上传时的？

**Comment by letterk** [comment]
难以理解你的思路.
日期是为了让拥有者方便排序用的, 除此之外日期不起任何作用. 
秒传之类是通过文件hash来确定是那个目标文件, 而不是通过时间. 
对外服务你指的是什么, 分享有分享那一天的时间, 具体到文件有该文件最后的修改时间, 去看看别家网盘是怎么做的.
