### ISSUE TITLE
3.3.2 无法在线预览 OFFICE WORD, EXCEL 文档

### ISSUE THREAD

**Issue by harvee1981** [cloudreve/Cloudreve#1050]
**Describe the bug**
无法在线预览 OFFICE WORD, EXCEL 文档

**To Reproduce**
1. 点击我的文件
2. 双击一个excel文档
3. 提示：An error occurred

**Expected behavior**
期望能在线预览office、wps文档

**Screenshots**
![image](https://user-images.githubusercontent.com/7745160/141234292-b305e495-38f8-44d0-a680-52521b8b9d3c.png)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]win 10
 - Browser [e.g. chrome, safari]chrome
 - Version [e.g. 22]版本 95.0.4638.69（正式版本） （64 位）

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Li-xp** [comment]
原有接口挂了，等待更新

**Comment by HFO4** [comment]
> 原有接口挂了，等待更新

真的挂了吗？我自己的演示站是ok的，所以现在很迷，很多人反馈挂了

**Comment by liujinyi28** [comment]
我的也打不卡 所有office格式

**Comment by maincooss** [comment]
目前微软的几个接口都挂了，其他有私人的接口，但是从安全角度来看作者应该不会用，建议可以提供一个参数。。。
https://github.com/kekingcn/kkFileView

**Comment by useblue** [comment]
应该是看存储位置的，挂载在SharePoint上这些预览都可以正常使用

**Comment by gitcomy** [comment]
3.3.1一切正常

**Comment by v587xpt** [comment]
我的也出现了这个问题；在想可否添加onlyoffice在线编辑，部署在本地，相当于挂载了第三方的软件，是否会稳定些；就像 dzzoffice一样
