### ISSUE TITLE
建议内置Web服务器增加强制SSL功能

### ISSUE THREAD

**Issue by Steve-George** [cloudreve/Cloudreve#1052]
如题，建议内置Web服务器增加强制SSL功能，从开发角度应当不难实现，但部署使用时会方便很多。

**Comment by aojie654** [comment]
个人认为，所有的产品/应用都应该重点关注自己的功能，而不是包罗万象，CloudReve只是一个网盘应用，而不是一个web服务器，类似于Django会携带一个内置的 Web Server，但是作者在[文档](https://docs.djangoproject.com/en/3.2/intro/tutorial01/)中也很明确提出：”We’re in the business of making Web frameworks, not Web servers.“

**Comment by Steve-George** [comment]
> 个人认为，所有的产品/应用都应该重点关注自己的功能，而不是包罗万象，CloudReve只是一个网盘应用，而不是一个web服务器，类似于Django会携带一个内置的 Web Server，但是作者在[文档](https://docs.djangoproject.com/en/3.2/intro/tutorial01/)中也很明确提出：”We’re in the business of making Web frameworks, not Web servers.“

但当前已经添加了对HTTPS的支持，如果没有强制HTTPS的功能，这个功能也就基本上白开发了，因为我不可能让别人输网址的时候还在前面加上“https://”。

**Comment by KawaiiZapic** [comment]
> 



> > 个人认为，所有的产品/应用都应该重点关注自己的功能，而不是包罗万象，CloudReve只是一个网盘应用，而不是一个web服务器，类似于Django会携带一个内置的 Web Server，但是作者在[文档](https://docs.djangoproject.com/en/3.2/intro/tutorial01/)中也很明确提出：”We’re in the business of making Web frameworks, not Web servers.“
> 
> 但当前已经添加了对HTTPS的支持，如果没有强制HTTPS的功能，这个功能也就基本上白开发了，因为我不可能让别人输网址的时候还在前面加上“https://”。

强制https是使用hsts头实现的, 这要求用户必须使用https访问你的网站至少一次, 因此你必须让别人输网址的时候还在前面加上“https://”.

cloudreve提供的https仅仅是用于无反代的情况下让pwa正常工作, 如果真的需要搞些花里胡哨, 还是建议自己再在前面套一层反代, 让专业的人来做专业的事, 而不是包罗万象多少沾点.

**Comment by miyunda** [comment]
https://docs.cloudreve.org/getting-started/install#ke-xuan-bu-shu-liu-cheng
文档里面有https的办法

**Comment by aojie654** [comment]
> > 个人认为，所有的产品/应用都应该重点关注自己的功能，而不是包罗万象，CloudReve只是一个网盘应用，而不是一个web服务器，类似于Django会携带一个内置的 Web Server，但是作者在[文档](https://docs.djangoproject.com/en/3.2/intro/tutorial01/)中也很明确提出：”We’re in the business of making Web frameworks, not Web servers.“
> 
> 但当前已经添加了对HTTPS的支持，如果没有强制HTTPS的功能，这个功能也就基本上白开发了，因为我不可能让别人输网址的时候还在前面加上“https://”。

从我的客户的情况来看，HSTS不见得所有人都喜欢……如果真要做，完全可以通过web server实现
