### ISSUE TITLE
离线下载到onedrive报错

### ISSUE THREAD

**Issue by dnslin** [cloudreve/Cloudreve#1057]
版本 arm64 最新发行版
环境 debian11 服务器 arm64 迪拜

aria2下载完成开始转存 报错
报错 Resource not found for the segment https
日志不知道存放在哪 无法体现

**Comment by HFO4** [comment]
试下这个存储策略在web端能否正常上传文件呢

**Comment by dnslin** [comment]
正常上传文件

**Comment by HFO4** [comment]
版本是3.4.0 beta1吗？离线下载节点是从机吗？存储策略是onedrive还是sharepoint呢？

**Comment by dnslin** [comment]
是正式版的arm 下载节点为主机的aria2 存储策略不管是onedrive还是sharepoint都出现这样的问题 并且切换过不同全局的
如果可以的话 可以说一下是否做了日志文件的存放 这样可以更好的进行一个反馈

**Comment by Bbqbbq123** [comment]
腾讯云 2核4g8m，才198元/3年
香港机器  2核4G30M  522元/1年

https://curl.qcloud.com/lOaK729o
![输入图片说明](https://static.cnodejs.org/FlaOHQeotV-IPSFDVe17Q_xT4f7d)
