### ISSUE TITLE
potplayer挂载webdav设置？

### ISSUE THREAD

**Issue by feishi12121** [cloudreve/Cloudreve#1062]
尝试了一下还是配置不上？哪里的设置要特别注意吗？相关的#1023号issue没有了
![image](https://user-images.githubusercontent.com/31927191/143450883-f94dff5e-a521-44a9-b1a5-b6b819872126.png)
![image](https://user-images.githubusercontent.com/31927191/143450911-bb786eb7-fcb5-4fbf-a432-b29b9d2d6059.png)

**Comment by black0w0** [comment]
我也还是没搞懂   potplayer的地址栏好像还是定位不到/dav

**Comment by HFO4** [comment]
![image](https://user-images.githubusercontent.com/16058869/144739579-0cb04256-1a59-4f28-ba7d-90ae74a993cd.png)
参考配置，实测可以正常使用。

**Comment by feishi12121** [comment]
> 

谢谢，已解决

**Comment by feishi12121** [comment]
> 我也还是没搞懂 potplayer的地址栏好像还是定位不到/dav
> 
> 解决了，potplayer地址栏直接填 "域名/dav"，前面不要加http或https，即然后勾选ssl，就可以了

谢谢，已解决

**Comment by feishi12121** [comment]
> ![image](https://user-images.githubusercontent.com/16058869/144739579-0cb04256-1a59-4f28-ba7d-90ae74a993cd.png) 参考配置，实测可以正常使用。

谢谢，原来去掉http或者https就行，已解决

**Comment by wangxiaoerYah** [comment]
> > ![image](https://user-images.githubusercontent.com/16058869/144739579-0cb04256-1a59-4f28-ba7d-90ae74a993cd.png) 参考配置，实测可以正常使用。
> 
> 谢谢，原来去掉http或者https就行，已解决

那就是你的nginx没有配置preload 重定向和hsts

**Comment by GC-ZF** [comment]
> > > ![image](https://user-images.githubusercontent.com/16058869/144739579-0cb04256-1a59-4f28-ba7d-90ae74a993cd.png) 参考配置，实测可以正常使用。
> > 
> > 
> > 谢谢，原来去掉http或者https就行，已解决
> 
> 那就是你的nginx没有配置preload 重定向和hsts

请问这个界面的软件是什么？

**Comment by yjc007** [comment]
谢谢！
