### ISSUE TITLE
cloudreve可以对离线下载的文件大小做限制吗

### ISSUE THREAD

**Issue by xjc19960724** [cloudreve/Cloudreve#1063]
没找到aria2的相关参数，很容易被别人故意搞炸盘

**Comment by HFO4** [comment]
关闭aria2的预分配存储空间功能并限制存储策略最大文件大小即可

**Comment by xjc19960724** [comment]
> 关闭aria2的预分配存储空间功能并限制存储策略最大文件大小即可

对BT种子没用的，比如我限制10G的文件大小，种子里面的文件有几个5G的文件离线下载还是继续进行
