### ISSUE TITLE
离线下载 database is locked

### ISSUE THREAD

**Issue by shirakun** [cloudreve/Cloudreve#1068]
版本:3.4.1
数据库类型:sqlite
已开启redis

![image](https://user-images.githubusercontent.com/11274807/143726729-f88ed75a-1066-4989-aaac-4deb0e8f22cf.png)

此外失败的任务没有重试之类的功能,任务多的时候无法分辨失败的任务对应哪些需要下载的任务,手动管理起来很麻烦

**Comment by qitayun** [comment]
sqlite的问题
转换到mysql就行
