### ISSUE TITLE
更新后离线下载无法正常显示添加使用

### ISSUE THREAD

**Issue by qitayun** [cloudreve/Cloudreve#1069]
https://pic.rmb.bdstatic.com/bjh/2ed55498177ef1f8714920e15db8e8ea.png
https://pic.rmb.bdstatic.com/bjh/452bdf2de629408d5a100735f4d1d63e.png

**Comment by HFO4** [comment]
疑似只更新了前端没更新后端

**Comment by qitayun** [comment]
> 疑似只更新了前端没更新后端

请问后端怎么更新？？不是替换原文件吗？

**Comment by qitayun** [comment]
@HFO4 
请问怎么解决呀

**Comment by HFO4** [comment]
@qitayun 不知道

**Comment by qitayun** [comment]
@HFO4 
那我怎么办？
[Warning] 2021-12-04 08:46:48 无法恢复任务，record not found
[Warning] 2021-12-04 08:46:48 无法恢复任务，unexpected end of JSON input
[Warning] 2021-12-04 08:46:48 节点池初始化失败, Error 1146: Table 'pan_qita_link.nodes' doesn't exist
这个报错，请问是数据表的问题吗？
