### ISSUE TITLE
3.4.1版本转存失败

### ISSUE THREAD

**Issue by xwwbest** [cloudreve/Cloudreve#1070]
![微信截图_20211128183921.png](https://pic.sl.al/gdrive/pic/2021-11-28/1a604cd42321f.png)

**Comment by HFO4** [comment]
Aria2配置中的临时下载目录填写有误。

**Comment by xwwbest** [comment]
问题解决了，不好意思



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月28日(周日) 晚上6:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cloudreve/Cloudreve] 3.4.1版本转存失败 (Issue #1070)




 
Aria2配置中的临时下载目录填写有误。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by xwwbest** [comment]
谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月28日(周日) 晚上6:57
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cloudreve/Cloudreve] 3.4.1版本转存失败 (Issue #1070)




 
Aria2配置中的临时下载目录填写有误。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
