### ISSUE TITLE
希望增加手机绑定功能

### ISSUE THREAD

**Issue by mayoushang** [cloudreve/Cloudreve#1072]
注册逻辑可保持不变，用户登录后检测是否绑定手机号，如果没绑定强制提醒绑定手机号并短信验证，个人中心可修改手机号，密码找回时可选邮箱或手机验证码找回。
目前只有邮箱有三个问题
1.不符合国家规定，国内网盘类必须强制要求用户绑定手机号到达实名认证的目的；
2.通知类的消息批量通知到用户已邮箱方式发不了几封就会被当成垃圾邮件屏蔽；
3.对于上传违法违规文件的用户来说，目前注册成本很低，账号被封号随便找个邮箱又可以注册上传。

希望作者可以考虑。

**Comment by xvzhenduo** [comment]
对于第3个问题，如果你是捐助版可以设置注册邮箱域黑名单/白名单，例如只允许qq邮箱注册

**Comment by dhlun** [comment]
no

**Comment by dhlun** [comment]
打错了，，为啥要关闭。破机器人

**Comment by hatsuyuki280** [comment]
@dhlun 如你所见，这个issue已经一年没有任何讨论了，主线上也没有将会加入这个功能的计划，继续开着一个暂时根本没计划修复的功能请求的意义有很大嘛quq？
