### ISSUE TITLE
提示：ACCESS TOKEN 获取失败

### ISSUE THREAD

**Issue by cycxyit** [cloudreve/Cloudreve#1074]
你好，开发者

挂载的时候提示：ACCESS TOKEN 获取失败
我已经检查了客户端id和客户端密码（值）都没有问题，至于账号类型是e5。

请问是出了什么问题吗？

**Comment by wangxiaoerYah** [comment]
建议你截图或者提供log。

**Comment by cypicbed** [comment]
> 

![Screenshot_20211201-210824_Chrome](https://user-images.githubusercontent.com/91234043/144234927-c7dae717-37bd-45d9-bf5e-cfc5a5f5d649.jpg)

**Comment by GreenTeodoro839** [comment]
用网络更好的服务器

**Comment by zhangweibo413** [comment]
这个在上传的时候偶尔也会出现这个错误，一般重新上传就行了
