### ISSUE TITLE
 。

### ISSUE THREAD

**Issue by ilubin** [cloudreve/Cloudreve#1075]

**Comment by wangxiaoerYah** [comment]
https://github.com/cloudreve/frontend/blob/master/src/component/Admin/Node/Guide/Aria2RPC.js#L222-L222

自己去看源码，这个示例是引用配置文件里面的key来反馈给你的webui的。


一天到晚就提这种垃圾issue，瞎jb叫。自己不会去看?

**Comment by wangxiaoerYah** [comment]
@HFO4 直接关闭吧。简直丢人现眼

**Comment by HFO4** [comment]
@ilubin 给你置顶以表敬意
