### ISSUE TITLE
目标名称非法 123.flac

### ISSUE THREAD

**Issue by xdeng** [cloudreve/Cloudreve#1076]
**Describe the bug**
谷歌原版浏览器拖进去上传一个 123.flac 无损文件提示的，上传进度走完，已经改成123名称了，同目录下没有同文件名。
设置里翻了一遍也看见设置 允许文件类型 的地方。

**To Reproduce**
谷歌原版浏览器拖进去上传一个 123.flac 无损文件提示的，上传进度走完，已经改成123名称了，同目录下没有同文件名。

**Desktop (please complete the following information):**
 - OS: win10
 - Browser chrome 96.0.4664.45
 - Cloudreve 3.4.2

**Comment by HFO4** [comment]
从老版本升级的话要清空下浏览器缓存。

**Comment by xdeng** [comment]
> 从老版本升级的话要清空下浏览器缓存。

厉害了 确实可以了。另外新加的 音频预览支持列表播放和后台播放 太棒了。

**Comment by xdeng** [comment]
webdav 加 音频预览支持列表播放和后台播放 这个 可以脱离QQ音乐啥的了
