### ISSUE TITLE
验证码无法刷新，改了腾讯云验证后无法通过验证

### ISSUE THREAD

**Issue by lius1999** [cloudreve/Cloudreve#1079]
console报错
Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
Failed to load resource: the server responded with a status of 500 (Internal Server Error)

另外，现在验证不了导致没法登录了，怎么保存原数据的情况下强行登录管理员或者强行去掉验证码……

**Comment by HFO4** [comment]
去数据库里改一下`settings`表

**Comment by lius1999** [comment]
> 去数据库里改一下`settings`表

是修改cdsettings表里的captcha_type或captcha_mode吗？有没有value相关说明？我尝试了将captcha_type设为NULL或captcha_mode设为0,1都没有效果

**Comment by HFO4** [comment]
改完后重启一下cloudreve

**Comment by lius1999** [comment]
> 改完后重启一下cloudreve

无效，试过重启cloudreve, mysql, redis, 服务器，清除浏览器缓存，登录仍然提示“验证失败，请刷新网页后再次验证”

**Comment by lius1999** [comment]
已解决，nginx的缓存问题
