### ISSUE TITLE
Cloudreve 3.4.x 版本上传任何文件都显示"钩子执行失败：目标名称非法"

### ISSUE THREAD

**Issue by SirlyDreamer** [cloudreve/Cloudreve#1081]
+ 系统环境：Ubuntu 20.04 64-bit
+ 文件系统：ext4
+ 非root权限执行
+ 安装方式：解压release包，直接运行
+ 配置文件：默认配置，主机模式

当我部署完3.4.x版本后，上传任何文件都会返回“目标名称非法”
切换回3.3.2版本则没有报错

**Comment by HFO4** [comment]
清空浏览器缓存。
