### ISSUE TITLE
使用Oracle对象存储（兼容AWS S3）时难以设置web端上传

### ISSUE THREAD

**Issue by CCCAUCHY** [cloudreve/Cloudreve#1086]
我使用的是Oracle对象存储（兼容AWS S3），通过填写endpoint成功设置存储策略，能够正常访问我的存储桶了，但是不能自动设置跨域策略，也没有找到文档。对于一个开箱即用的软件来说，即使我能访问外部存储，却不能使用web上传功能（甚至可以使用webdav上传），这非常令人困惑。

最好能适配Oracle对象存储，即使需要自己填写endpoint，但至少请在专家模式里给出设置web上传的方法。

我现在使用s3fs挂载对象存储到操作系统的目录

**Comment by ThreeGold127** [comment]
Oracle对象存储 其实并不兼容s3，你搜搜minio gateway s3 模式的相关问题就知道了。oci用起来感觉挺蛋疼的
