### ISSUE TITLE
能否加一个查看离线下载完成后上传进度功能

### ISSUE THREAD

**Issue by zyt0002** [cloudreve/Cloudreve#1087]
RT，离线下载后转存到OD，但是无法判断进度到哪了，通常都是在后台宝塔看上传进度。能不能加个进度条之类的功能？

**Comment by Scomarlf** [comment]
离线下载功能的下载进度不准确，似乎无法动态更新？

![image](https://user-images.githubusercontent.com/38175557/157360631-7ed41d4d-34b2-499e-b78d-50df24fdb599.png)
