### ISSUE TITLE
成功接到从机，但是从机返回 i/o timeout

### ISSUE THREAD

**Issue by q601904795** [cloudreve/Cloudreve#1088]
版本为最新版3.4.2，系统为ubuntu20.04
aria版本为1.35

链接从机提示：
成功接到从机，但是从机返回：Post http://192.99.17.27:12388/jsonrpc: dial tcp 192.99.17.27:12388: i/o timeout

这个aria以同样配置可以在aria webui链接，应该不是aria配置问题。
求指导

**Comment by q601904795** [comment]
新发现：
在主机配置中，把在从机配置中测试链接失败的aria参数填入，能够正常链接。

**Comment by HFO4** [comment]
@q601904795 从机的aria2要运行在从机上，你填主机的rpc地址当然不通了

**Comment by q601904795** [comment]
啊  大佬你可能理解错我的意思  
就是我添加从机下载节点，填写了从机aria的信息，测试链接不通。
然后我刚刚试着用从机aria的信息填到主机离线下载那边 ，能通。

**Comment by HFO4** [comment]
那说明你主机能连到从机的aria2，从机连不到自己的aria2

q601904795 ***@***.***>于2021年12月9日 周四14:37写道：

**Comment by q601904795** [comment]
哦 明白了。
主机不参与从机aria的通讯。是让从机自己和从机的aria通讯。
我这个机器IPV4是nat转发，可能和这个有关。
将IP改为机器内网IP后链接成功了。
谢谢大佬~
