### ISSUE TITLE
上传M级别的文件要么是卡在处理中，再大一点的就直接http错误

### ISSUE THREAD

**Issue by lovelyJason** [cloudreve/Cloudreve#1089]
怎么回事， 上传策略里没有限制， 使用服务器本地存储

传了19M文件就卡在处理中了，上传70m的文件最后就是http错误

使用的是最新的3.4.x版本,  centos下部署的

![image](https://user-images.githubusercontent.com/50656459/145370167-920bedcc-5ebc-463e-8a4b-c6f76a713a4b.png)

![image](https://user-images.githubusercontent.com/50656459/145370483-aeff3dd6-045a-4668-922b-66b9d8c2598b.png)

难道是nginx配置有什么问题？nginx没有设置多余参数
-------

我刚又试了下，ip去访问服务可以传成功， nginx代理后上传大文件有上面问题

-----
解决了， 就是nginx对网络传输的默认值不够大文件上传的， 我加了这些参数就行了
    client_max_body_size     50m; # 限制请求体的大小
    client_header_timeout    1m; # 读取请求头的超时时间
    client_body_timeout      1m; # 读取请求实体的超时时间
    proxy_connect_timeout     60s; #http请求无法立即被容器(tomcat, netty等)处理，被放在nginx的待处理池中等待被处理。此参数为等待的最长时间
    proxy_read_timeout      1m; # http请求被容器(tomcat, netty等)处理后，nginx会等待处理结果，也就是容器返回的response。此参数即为服务器响应时间
    proxy_send_timeout      1m; # http请求被服务器处理完后，把数据传返回给Nginx的用时

**Comment by bs10081** [comment]
你好啊，請問設定多大的響應時間，才不會造成http錯誤？
另，新春快樂！

**Comment by zhangweibo413** [comment]
我是文件越小，越是大概率“处理中”，反而是大文件，几百M，1-2G都秒过处理，所以现在都不敢传小文件，生怕卡住

**Comment by HFO4** [comment]
3.5.0后已支持分片上传
