### ISSUE TITLE
【BUG】od储存策略上传失败

### ISSUE THREAD

**Issue by HaoShen2021** [cloudreve/Cloudreve#1092]
【Bug】
安装环境：V3.4.0  Commit #3948ee7  Win11 64
问题描述：使用onedrive储存策略时，上传大文件（>=4Mb）时会出现上传失败的问题。
比如这个： 
![图片](https://user-images.githubusercontent.com/90556839/145681354-30b07254-b3f7-4694-81c4-5301e42885fd.png)

上传时正常，完成后会出现约5-15秒的成功提示， 
![图片](https://user-images.githubusercontent.com/90556839/145681361-3ff501d7-d515-4c01-9807-83a3405af961.png)

再后来就会出现：  
![图片](https://user-images.githubusercontent.com/90556839/145681366-2b1c6911-387f-4ceb-8d8c-e8f9d186ca9e.png)
![图片](https://user-images.githubusercontent.com/90556839/145681372-f98e602e-091c-4665-a1c5-d367b14cfb95.png)

刷新页面没有该文件，但在onedrive上传路径内能找到。

**Comment by wangxiaoerYah** [comment]
前面套了cf cdn吧，限制只能100m大小
________________________________
From: HaoShen2021 ***@***.***>
Sent: Saturday, December 11, 2021 11:06:02 PM
To: cloudreve/Cloudreve ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cloudreve/Cloudreve] 【BUG】od储存策略上传失败 (Issue #1092)


【Bug】
安装环境：V3.4.0 Commit #3948ee7 Win11 64
问题描述：使用onedrive储存策略时，上传大文件时会出现上传失败的问题。
比如这个：
[图片]<https://user-images.githubusercontent.com/90556839/145681354-30b07254-b3f7-4694-81c4-5301e42885fd.png>

上传时正常，完成后会出现约5秒的成功提示，
[图片]<https://user-images.githubusercontent.com/90556839/145681361-3ff501d7-d515-4c01-9807-83a3405af961.png>

再后来就会出现：
[图片]<https://user-images.githubusercontent.com/90556839/145681366-2b1c6911-387f-4ceb-8d8c-e8f9d186ca9e.png>
[图片]<https://user-images.githubusercontent.com/90556839/145681372-f98e602e-091c-4665-a1c5-d367b14cfb95.png>

刷新页面没有该文件，但在onedrive上传路径内能找到。

―

**Comment by HaoShen2021** [comment]
但我上星期是正常的，3.4.0之上的版本都是这样的

**Comment by wangxiaoerYah** [comment]
你就回，是不是套了cloudflare cdn，别上个星期。如果你套了cdn，cf的cdn，有时候你是直连host，没有走他的cdn，你上传成功很正常 后面不成功了也正常。没什么大惊小怪。cf的cdn，就是限制100m，除非你是企业版没有限制。

**Comment by wangxiaoerYah** [comment]
有时候你们提问真的很无语。问你是不是套了cdn呢，你回上个星期不这样。。。。。你不知道cdn限制大小，我们会给你科普，能好好提问好好回答不。

**Comment by wangxiaoerYah** [comment]
本着帮你解答问题的思想，但是你们老是避实就虚。不回答我们想知道的信息，我们怎么解答，难道回你这是"玄学"吗？"它就是这样时而好时而坏"。好了，我不是开发者，帮你@ @HFO4

**Comment by HaoShen2021** [comment]
没有用cdn，现在又变这样了

**Comment by BunnySakura** [comment]
cdn有缓存，等一阵子

**Comment by JureGrinffin** [comment]
对于楼上的暴躁老哥 建议您用抓包软件抓下包再来这里一刀切+输出观点
我抓了 每次上传都是直连od不走我的cloudreve服务器中转

对于issuer `od上传路径中能找到文件`你上传到od的文件是否完整？拿你截图的视频文件举例，全部的视频是否能正确在线播放？（或者你从od下载下来 对比一下两者的hash）
+ 如果完整 则有可能是你的服务器没有收到od服务器的callback
建议你检查以下内容
  + client_id secret的正误 并考虑重新授权
  + 服务器和你的od节点的连接性
大概率是dns的问题 建议改dns服务器 比如1.1.1.1 或者手动dig来刷新dns缓存
PS: 节点地址形如xxxx-my.sharepoint.com
+ 如果不完整 可以尝试服务端开debug 然后配合本地抓包查找问题

如果不是第一种情况 您可以comment里面踹我一下或者email我 我们再看看下一步怎么办

**Comment by HaoShen2021** [comment]
https://user-images.githubusercontent.com/90556839/145715608-f1a39eb9-db04-49ec-92c2-3db6be38bbf6.mp4
