### ISSUE TITLE
webdav无法上传文件

### ISSUE THREAD

**Issue by huacong1** [cloudreve/Cloudreve#1093]
win10通过添加网络位置的方式添加设置好的webdav账号，连接成功后可以正常下载文件，上传文件提示失败，重新尝试小文件也是一样，可以新建文件夹就是不能上传文件，有添加反代。用手机端的其他app连接webdav也是一样，可以下载无法上传，均提示上传失败

**Comment by yanranxiaoxi** [comment]
同样问题，我是出现在Tabby使用tabby-cloud-sync-settings插件配置同步时，配置可以验证成功，且成功新建了文件夹，最终提示上传失败。

服务器使用的Caddy2反代

**Comment by qtxie** [comment]
估计是没权限。我之前把cloudreve放到/usr/local/bin, 也是这个问题。后来把cloudreve放到用户目录下运行，就正常了。
