### ISSUE TITLE
从机停止运行Cloudreve后文件依旧显示且无法删除

### ISSUE THREAD

**Issue by YumeGod** [cloudreve/Cloudreve#1099]
我储存策略一个从机一个注册，在从机停止运行Cloudreve之后删除从机储存策略时显示还有文件储存在从机上，由于从机已离线所以文件无法删除，有办法解决吗，可以从数据库里面强行抹掉这些死文件吗

**Comment by HFO4** [comment]
后台选中文件强制删除。
