### ISSUE TITLE
参数设置中没有离线下载选项

### ISSUE THREAD

**Issue by yefengwu** [cloudreve/Cloudreve#1100]
3.4.x版本尝试了docker和release，网页均没有离线下载的选项

**Comment by yefengwu** [comment]
![image](https://user-images.githubusercontent.com/45461486/146902192-6a5d024d-38bc-4b38-9fa7-e4d0af90d309.png)

**Comment by HFO4** [comment]
@yefengwu 离线下载节点中设置
