### ISSUE TITLE
请求添加OSS的CNAME功能选项

### ISSUE THREAD

**Issue by Orisland** [cloudreve/Cloudreve#1102]
如题，在使用OSS时，外网下载读取高昂的流量费用望而却步。
但是只需要在代码中启动OSS的CNAME即可解决，使用ECS反代理的方式访问OSS即可不消耗外网流量。
[这种方式](https://help.aliyun.com/document_detail/52931.html
)很容易添加且只需要修改一行代码,`oss.UseCname(true)`,希望考虑添加该功能或作为可选设置。
该选项默认关闭，需要手动开启。
```go
// 初始化客户端
client, err := oss.New(endpoint, handler.Policy.AccessKey, handler.Policy.SecretKey, oss.UseCname(true))
```

**Comment by topjohncian** [comment]
这样建议直接使用 ossfs 挂载为本地储存
