### ISSUE TITLE
增加和彩云存储，和彩云提供了api

### ISSUE THREAD

**Issue by decentone** [cloudreve/Cloudreve#1109]
需求：增加和彩云为底层存储策略

可行性：和彩云的容量比较大，同时限速不是很严重，提供了一系列接口，可以接入。
这是和彩云的api接口文档，http://open.yun.139.com/open/index.html#/help-document/basic-ability-word

**Comment by hbqjren** [comment]
+1，和彩云比其它网盘好的多，好在它有200G定向流量，无限速，扩容活动多。目前是我主用的网盘

**Comment by pongfcnkl** [comment]
这个api的接口需要企业申请

**Comment by Sunbangyan** [comment]
api接口只能企业用户调用（，摘自http://open.yun.139.com/#/help-document/standard-word
如果您还没有开发者账号，请在中国移动互联网能力开放平台右上角找到注册入口，选择企业用户注册（非企业认证将无法调用相关能力），填写相关资料。

**Comment by hbqjren** [comment]
> api接口只能企业用户调用（，摘自http://open.yun.139.com/#/help-document/standard-word 如果您还没有开发者账号，请在中国移动互联网能力开放平台右上角找到注册入口，选择企业用户注册（非企业认证将无法调用相关能力），填写相关资料。

我最近看到es文件管理器支持和彩云。用是官方api接口。给es的只有上传权限，没有文件管理限权。还有不走定向流量上传
