### ISSUE TITLE
WebDav上传大文件不能及时停止

### ISSUE THREAD

**Issue by lv4lv** [cloudreve/Cloudreve#1116]
使用RaiDrive挂载WebDav时，当上传一个大文件时，明明已经上传完毕，但是在进度条走到最后的时候会出现漫长的等待（有的时候需要10分钟左右），进度条窗口才会消失。
经测试发现，出现这个的原因是：虽然文件已经完全上传到中转服务器，但是从中转服务器上传到OneDrive完毕后，才会向RaiDrive发送上传完毕的信号。
期望的结果：上传到中转服务器完毕时即返回上传成功的信号，关闭进度条窗口，减少无谓的等待。

**Comment by HFO4** [comment]
目前on-the-fly式的中转上传，技术上无法实现提前返回。
