### ISSUE TITLE
阿里云OSS下载时无法获取真实文件名

### ISSUE THREAD

**Issue by z-my-cn** [cloudreve/Cloudreve#1117]
### 环境
阿里云OSS：公有读私有写
 Cloudreve：3.4.2

### 问题复现
如下，**polr.zip**为原上传文件，**uploads_2022_Ab4xwize_polr.zip**为上传后下载文件
**uploads_2022_Ab4xwize**为配置的存储路径uploads/{year}/{randomkey8}
![image](https://user-images.githubusercontent.com/51685165/150637364-7788d4fc-2ba6-4799-8d5f-71deb696abba.png)
通过外链获取如下：
https://z-my.oss-cn-hangzhou.aliyuncs.com/uploads%2F2022%2FAb4xwize%2Fpolr.zip?Expires=1642852526

### 问题对比
同配置下七牛云正常 阿里云异常

**Comment by z-my-cn** [comment]
目测应该是获取下载的时候将字符“/”转换成了“%2F”，希望可以调整一下，毕竟总不能把所有文件放在根目录下。

**Comment by lsCoding666** [comment]
试试改下file.go里面的GetDownloadURL方法，将返回的source中的%2f替换为/试试？

**Comment by z-my-cn** [comment]
> 

这应该是一个好办法，可惜我对go并不是很熟悉，还是希望可以尽快修复

**Comment by lsCoding666** [comment]
我代码做了一些调整 不知道能不能解决你的问题
/pkg/filesystem/driver/oss/handler.go
原本的代码长这样
https://github.com/cloudreve/Cloudreve/blob/96712fb0660695fa4c07bd8c5a99379418841e49/pkg/filesystem/driver/oss/handler.go#L396
改后的
```
func (handler Driver) signSourceURL(ctx context.Context, path string, ttl int64, options []oss.Option) (string, error) {
//省略
	decodedValue, err := url.QueryUnescape(finalURL.String())
	if err != nil {
		return "", nil
	}
	//return finalURL.String(), nil
	return decodedValue, nil
```
二进制文件已上传至https://pan.c34.pw/s/lbf4

**Comment by z-my-cn** [comment]
完美解决问题，非常感谢您提供解决办法


> 我代码做了一些调整 不知道能不能解决你的问题 /pkg/filesystem/driver/oss/handler.go 原本的代码长这样
> 
> https://github.com/cloudreve/Cloudreve/blob/96712fb0660695fa4c07bd8c5a99379418841e49/pkg/filesystem/driver/oss/handler.go#L396
> 
> 
> 改后的
> ```
> func (handler Driver) signSourceURL(ctx context.Context, path string, ttl int64, options []oss.Option) (string, error) {
> //省略
> 	decodedValue, err := url.QueryUnescape(finalURL.String())
> 	if err != nil {
> 		return "", nil
> 	}
> 	//return finalURL.String(), nil
> 	return decodedValue, nil
> ```
> 
> 二进制文件已上传至https://pan.c34.pw/s/lbf4
> 
> 测试的时候备份原来的二进制文件和数据库

**Comment by hatiwowo** [comment]
使用您的办法后，外链变成为[https://haticloud.oss-cn-shanghai.aliyuncs.com/2/阿里云/eye.png?Expires=1647412680](url)；
使用阿里云默认的oss browser，同一文件获取到的连接为[https://haticloud.oss-cn-shanghai.aliyuncs.com/2/%E9%98%BF%E9%87%8C%E4%BA%91/eye.png](url)。
 路径同样做一个encodeURIComponent会不会更好一点


> 

@lsCoding666

**Comment by linfun486** [comment]
@hatiwowo 试试看
```
func (handler Driver) signSourceURL(ct...
省略...

	if handler.Policy.BaseURL != "" {
		cdnURL, err := url.Parse(handler.Policy.BaseURL)
		if err != nil {
			return "", err
		}
		finalURL.Host = cdnURL.Host
		finalURL.Scheme = cdnURL.Scheme
	}

	return decodeUrl(finalURL.String())
}

//转正确的url路径
func decodeUrl(urlString string) (ret string, err error) {
	ret, err = url.QueryUnescape(urlString)
	if err != nil {
		return
	}
	ss := strings.Split(ret, "/")
	for i, item := range ss {
		ss[i] = url.QueryEscape(item)
	}
	ret = strings.Join(ss, "/")
	return
}

```

**Comment by HFO4** [comment]
oss-golang-sdk 的问题，暂时无法解决，参考 https://github.com/aliyun/aliyun-oss-go-sdk/issues/212
