### ISSUE TITLE
右键点击文件或者文件夹没有弹出对话框，无法进行操作

### ISSUE THREAD

**Issue by mysalter** [cloudreve/Cloudreve#1120]
我找不到删除文件夹的地方，只找到了删除文件的按钮，这是在哪呢
![msedge_KustbplrHR](https://user-images.githubusercontent.com/62681289/150703440-f8e4460c-40d2-4036-9639-77babfa0fd1e.png)

**Comment by mysalter** [comment]
我用的另一个电脑能够点击文件夹右键进行了删除，但为啥这个电脑点右键不出来操作呢

**Comment by topjohncian** [comment]
建议使用 **Chrome** 或 **Microsoft Edge** 等 **现代化**浏览器使用
