### ISSUE TITLE
某些http链接下载的文件没有文件名，希望加入http链接下载的文件指定文件名的功能

### ISSUE THREAD

**Issue by lsCoding666** [cloudreve/Cloudreve#1124]
有些http链接下载的文件没有文件名，比如
https://vod0041-hwyun02-vip-lixian.mypikpak.com/download/?fid=QCmqwuNRpDgR9ZOx8T6eWglhF3qSqCAaAAAAAJNcII3mn*4Pw1P9SIkkdoxlPQQp%26mid=666%26threshold=251%26tid=26BD181BE80AEA16F6F131D7A67AEF1A%26srcid=0%26verno=2%26pk=xdrive%26e=1643451298%26g=935C208DE69FEE0FC353FD488924768C653D0429%26i=4029AAC2E351A43811F593B1F13E9E5A0961177A%26ui=YfGNRbIsO7zpLNYh%26t=0%26hy=1%26ms=6300000%26th=0%26pt=1%26f=438347922%26clientver=%26spr=flow%26fileid=VMuQQNWM_NPwXchvFMwVMCvno1%26fext=mp4%26userid=YfGNRbIsO7zpLNYh%26clientid=YNxT9w7GMdWvEOKa%26projectid=2wks56c31dc80sxm5p9%26vip=PVIP%26at=69DB6B324BE3765355115282E50F2929
文件名下载后默认是index.html，这是不对的
![image](https://user-images.githubusercontent.com/73888354/151545343-de83e6f5-43cd-48fe-b95b-1436e2edf177.png)
![image](https://user-images.githubusercontent.com/73888354/151545370-313ee54c-0b11-4f41-b15b-cc615dd54be4.png)
希望在添加http离线任务的时候加一个指定文件名的功能，效果是上传到存储策略的原本的文件名就是我指定的那个，而不是存储策略是index.html，数据库中是我指定的文件名
![image](https://user-images.githubusercontent.com/73888354/151545510-93f0ce68-8c59-4aa5-b9a4-e4906d79f0f4.png)
就是在这里 正则为http链接后加一个重命名的功能

**Comment by lsCoding666** [comment]
models/download.go
```
type Download struct {
	gorm.Model
	Status         int    // 任务状态
	Type           int    // 任务类型
//添加这一行
	CustomName     string //自定义名称
	Source         string `gorm:"type:text"` // 文件下载地址
	TotalSize      uint64 // 文件大小
	DownloadedSize uint64 // 文件大小
	GID            string `gorm:"size:32,index:gid"` // 任务ID
```
pkg/cluster/master.go
![image](https://user-images.githubusercontent.com/73888354/152809839-465d5b38-0efa-4516-8dfe-92ec7d5bdd8f.png)
service/aria2/add.go
![image](https://user-images.githubusercontent.com/73888354/152809961-c4eaf874-d58c-420e-a3e3-9504a291b9c1.png)
![image](https://user-images.githubusercontent.com/73888354/152809995-3dcca609-5113-40dc-ab7b-e216452d6c1b.png)

前端
src/component/FileManager
![image](https://user-images.githubusercontent.com/73888354/152810243-afc8e5fe-0e61-45ad-b5da-3415422da168.png)
![image](https://user-images.githubusercontent.com/73888354/152810311-2db57609-7a85-4030-aaa3-e8bc4a2d1be4.png)
![image](https://user-images.githubusercontent.com/73888354/152810350-1605bd04-d91b-4461-a9c0-4f1661863c8b.png)

**Comment by HFO4** [comment]
暂时不打算引入自定义文件名的功能。
