### ISSUE TITLE
请问使用OneDrive存储，WebDAV连接的话流量要过服务器吗？

### ISSUE THREAD

**Issue by Danny-Yxzl** [cloudreve/Cloudreve#1135]
如题，没有找到相关叙述，个人无法解决此问题，还请大佬解答

**Comment by Clansty** [comment]
@Danny-Yxzl 上传要，下载不要

**Comment by Danny-Yxzl** [comment]
> @Danny-Yxzl 上传要，下载不要

感谢回复

正常的网页上传也是不需要过服务器的对吧？

**Comment by HaoShen2021** [comment]
参照这个
![储存策略](https://user-images.githubusercontent.com/90556839/154790231-c0178a1c-6690-49b3-abdf-fd07f46153e7.png)

**Comment by wicecoffeey** [comment]
我的od用web浏览不了，是不是用设置什么东西
