### ISSUE TITLE
存储策略转移目录不一致

### ISSUE THREAD

**Issue by Zynismus16** [cloudreve/Cloudreve#1137]
如题，我使用的是cloudreve pro 3.4.2

两个路径的魔法路径变量一致，文件转移后并不会与原路径一致。会丢失掉原路径中用户定义的文件路径

问题复现
设置有两个存储测量，均为SharePoint 这里代称为sp1 sp2
在sp1中新建一个文件夹名为：123（内含多个文件），将123文件夹使用存储策略转移功能转移至sp2空间
该文件夹在sp1中的路径为/time/uid/path/123/xxxx.xx,转移到sp2后路径为/time/uid/xxxx.xx

**Comment by Licsber** [comment]
同遇到 转移后路径会不一致 但文件名符合要求

**Comment by comwasemo** [comment]
同遇到，本应该在以下目录的文件却跑到了另一个盘的用户根目录，中间目录丢失。
/run/media/root/home2/uploads/2/test/test1/*
/run/media/root/home3/uploads/2/*
