### ISSUE TITLE
请帮我看看这是什么问题呢？

### ISSUE THREAD

**Issue by MuziShaoxing** [cloudreve/Cloudreve#1138]
问题描述
1. 服务器域名访问他一切正常，域名解析后报错
  -  ![riNhdx](https://cdn.jsdelivr.net/gh/muzishaoxing/picture@main/shaoxing/20220219/150557/riNhdx.png)
  - 设置生效很慢。。。。
2. 我自己测试 重开一个端口 用新的应用，问题一致
3.  测试系统
  - 宝塔linux
  - 宝塔Windows
  - 反向代理 127.0.0.1:端口
  - 域名：xinglu.xyz. 腾讯
  - 还有啥需要提供请告知

**Comment by MuziShaoxing** [comment]
我也不会 我是通过宝塔一建的 这可能是最简单的


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月22日 22:47:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [cloudreve/Cloudreve] 请帮我看看这是什么问题呢？ (Issue #1138)




 
我这里看是好的啊？
 顺便问一下，如何设置http跳转https？
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by XUZI09** [comment]
我的是这样

:( 请求时出现错误
Request failed with status code 502

**Comment by MuziShaoxing** [comment]
- 我现在正常。是因为 我重装了服务器。。。。
- 温馨提醒 也许是反代缓存惹的祸
- 反代不开缓存！！！

**Comment by XUZI09** [comment]
我的是这样

:( 请求时出现错误
Request failed with status code 502
