### ISSUE TITLE
关于站点URL的设置

### ISSUE THREAD

**Issue by XYZliang** [cloudreve/Cloudreve#1140]
站点url的设置似乎没什么意义，甚至造成了一些麻烦。
例如我部署在内网的一个服务器上，并且穿透出去。我完全可以在内网的情况下通过访问内网ip来获得更快的速度：在外网的情况下走穿透的线路确保外网也能正常使用。
但是站点url就导致这样使用的时候，下载出问题。
站点url设置为内网ip的时候，穿透访问时无法下载（下载文件走的是内网的地址）
设置为外网的时候，内网访问下载时走的还是外网的链接无法利用局域网的优势…
为何不取消站点url这个设置？反之在用户下载的时候，根据用户访问的链接来生成下载链接。

**Comment by HFO4** [comment]
有些地方还是需要指定站点url的，不止是下载链接。比如上传回掉之类的。
