### ISSUE TITLE
离线下载Aria2实例获取失败

### ISSUE THREAD

**Issue by QCXES** [cloudreve/Cloudreve#1144]
打包版，不知道有没有自带aria2c，在目录下放了一个还是不行
链接
https://do.rytsu.org/games/phigros/phigros_1.4.1.apk

**Comment by Waitung** [comment]
第一，打包版是什么东西，请不要自己生造一个东西。
第二，附带个apk链接又是什么情况。
最后，aria2c不是在目录下放一个就好了，是需要自己配置好并运行，cloudreve只是通过rpc和aria2连接。

**Comment by wangxiaoerYah** [comment]
😂😂😂😂小白好难教的哦

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
