### ISSUE TITLE
非Https下剪切板会失效复制不了任何东西

### ISSUE THREAD

**Issue by lsCoding666** [cloudreve/Cloudreve#1145]
![image](https://user-images.githubusercontent.com/73888354/155703991-d1a45b14-c892-4d35-9caa-a1f7946be102.png)
在 Chrome 的 DevTools 控制台下执行 navigator.clipboard 返回 undefined，经查找资料发现是浏览器禁用了非安全域的 navigator.clipboard 对象，哪些地址是安全的呢？

安全域包括本地访问与开启TLS安全认证的地址，如 https 协议的地址、127.0.0.1 或 localhost 。
参考https://www.cnblogs.com/hellxz/p/15192573.html

帮别人做一个批量复制外链并且复制到剪切板的时候发现的bug 在本地测试没有问题 放到服务器上就有问题，最后发现是这个原因

**Comment by HFO4** [comment]
不考虑支持非https场景
