### ISSUE TITLE
WebDav使用无法加载内容

### ISSUE THREAD

**Issue by wicecoffeey** [cloudreve/Cloudreve#1147]
安卓手机用ES文件/Reex
输入网址和用户名密码；可以进去看到各种文件目录，也可以点进目录看到里面的各种
(web的用户名/密码输入正确，如果错误应该是登录不进去的)
但是点击文件，全部加载不出来 包括PDF，MP4等各种文件（不论文件大小）
网址加了ssl；分别尝试了https和http；都是可以看到文件，但是但是点击文件，加载不出来
挂载了od，并且用自己的服务器反代了od；

猜测是不是因为用服务器反代了，所以WEBDAV读取不到文件的地址？
不知道需要提供什么文件（截图）来反应这个问题

**应该是OD的问题，但是不知道怎么处理；新建存储策略，没有反代也打不开，但是存储到本机的文件没有任何问题；**
宝塔搭建；想问下宝塔跟E5 存储策略有没有什么需要注意的设置事项

**Comment by Etr0-666** [comment]
我自己也是，文件存od上然后用winscp尝试打开文件显示“WebDAV资源被移到了'https://xxx.sharepoint.com/sites/balabala“，然后cloudreve后台显示301错误，应该是跨域调用的问题

**Comment by wicecoffeey** [comment]
> 
我的直接就打不开od里面的资源~加载失败；请问有解决办法吗

**Comment by wicecoffeey** [comment]
一样的问题，但是我电脑挂wab之后，大概30m以内视频可以打开，其他的都不行
![屏幕截图 2024-03-01 205646](https://github.com/cloudreve/Cloudreve/assets/96828708/97dcc940-74ed-44b0-8b14-9a5947e5589e)
