### ISSUE TITLE
版本3.4.2，arm版本下上传文件，提示“文件名称错误”上传失败

### ISSUE THREAD

**Issue by waves-zhangyt** [cloudreve/Cloudreve#1148]
**Describe the bug**
版本3.4.2，本地存储，32位树莓派OS下上传文件，会提示“文件名称错误”上传失败。回退到3.3.2版本没有问题

上传目录层级三级（含中文路径名）

**Desktop (please complete the following information):**
 - OS: win11
 - Browser: Chrome
 - Version 98

**Comment by Cinnamoroll-Cat-2** [comment]
这个不知道是不是bug
