### ISSUE TITLE
使用了frp，只能上传不能下载和分享

### ISSUE THREAD

**Issue by pr9dro** [cloudreve/Cloudreve#1149]
使用环境是在本地，配置的ip是本机不是127.0.0.1，然后使用了frp.104300.xyz
文件上传是可以上传的，但是下载或者分享的时候，下载跳转的ip变成了本机ip没法下载，分享显示的地址也是本机ip，这个怎么办。

**Comment by POMIN-163** [comment]
我也遇到了这样的问题，但是我是在服务器上面，点击下载按钮，跳转到localhost，它应该是服务器的域名才对，系统是Debian10，版本3.4.2.

**Comment by wangxiaoerYah** [comment]
请在设置面板设置服务器的域名。。。。。

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by vvisionnn** [comment]
This is not a Cloudreve related issue, for the usage discussion please post to the [forum](https://forum.cloudreve.org), thanks.
