### ISSUE TITLE
OneDrive 鉴权失败

### ISSUE THREAD

**Issue by xingsenfirst** [cloudreve/Cloudreve#1153]
我的 Cloudreve 使用的存储策略是 OneDrive 国际版（**已设置“允许获取永久直链”**）。

但是，通过右键文件选择“获取外链” 生成的直链**刚开始还可以用**，经过一段时间就显示：

`{"code":403,"msg":"鉴权失败"}`

必须重新生成。请问这是什么问题？该如何解决？

**Comment by Cinnamoroll-Cat-2** [comment]
重新验证试试。我是 @cinnamoroll-cat

**Comment by lsCoding666** [comment]
看看是不是服务器时间问题

**Comment by lsCoding666** [comment]
![image](https://user-images.githubusercontent.com/73888354/157806362-d0ed7bc9-857a-499b-8c1f-862c4683a3f6.png)
注意看外链格式 后面跟着一串这样的东西 1KkZpuXH4hLRw0-Eifg7uh4NHoalfDUN_AoYptOSjzs=:0 最末尾是0，我想看下你的是多少。按照cloudreve的代码，0代表永不过期，否则就是有失效时间的，比如说这个值是1646975756 代表2022-03-11 13:15:56 过期，这是一个unix时间戳
https://tool.jisuapi.com/unixtime.html

**Comment by lsCoding666** [comment]
如果你的签名末尾是0，那就代表不是时间的问题，不是过期的问题，那就是签名的问题。当没有过期的情况下，会对签名进行验证
![image](https://user-images.githubusercontent.com/73888354/157806922-0caeeac1-0f96-4952-b938-89de18928dc5.png)
expires就是unix时间戳，比如上面的说的1646975756，我这里签名末尾是0，所以我这实际上是expires=0，然后拿着expires去校验签名。
简单来说，会拿着body和expires去生成一个值，这个值就是签名，然后拿着生成的签名和你传过来的签名进行校验 1KkZpuXH4hLRw0-Eifg7uh4NHoalfDUN_AoYptOSjzs= 这个是你的签名，如果两者相同，那么就会校验通过，否则不通过，这是为了防止用户自行修改过期时间expires的验证过程

**Comment by lsCoding666** [comment]
![image](https://user-images.githubusercontent.com/73888354/157807437-1640d8ff-6b16-4ef7-a49b-eaa4aaaa8bf0.png)
这个文件是onedrive生成外链的函数，传入的参数有一个ttl，代表过期时间，然后他会拿着这个ttl，就是相当于上文的expires，和这个url去签名，然后返回给用户。我觉得大概率是因为你这里的ttl写的是两个小时，所以2小时后失效

**Comment by lsCoding666** [comment]
不过我看了下 这个外链地址默认ttl写的是0 就是不限制时间，所以我觉得应该是你服务器环境或者配置的问题 cloudreve没有问题，如果你站点套了cdn，试试不通过cdn访问试试
![image](https://user-images.githubusercontent.com/73888354/157807889-424c0009-a272-49cb-9379-cce07bae480b.png)
