### ISSUE TITLE
连接微软onedrive存储无法删除文件

### ISSUE THREAD

**Issue by Danny-Yxzl** [cloudreve/Cloudreve#1156]
如题，前两天还是正常的，现在不好用了，加载很久之后报错400

站点地址：https://cloud.yixiangzhilv.com/

测试账号：test@test.com

密码：test

**Comment by Danny-Yxzl** [comment]
能帮助解决不胜感谢 可有偿

**Comment by lsCoding666** [comment]
可能是cdn配置出现问题
![image](https://user-images.githubusercontent.com/73888354/157802381-2570e86a-ddc9-4a6e-928d-9a90f4b4f1dd.png)
试下不通过cdn访问

**Comment by Danny-Yxzl** [comment]
> 可能是cdn配置出现问题 ![image](https://user-images.githubusercontent.com/73888354/157802381-2570e86a-ddc9-4a6e-928d-9a90f4b4f1dd.png) 试下不通过cdn访问

感谢大好人

嘶这话为什么听着这么阴阳

反正给大佬磕头！！
