### ISSUE TITLE
建议：打包下载时增加校验文件大小的功能

### ISSUE THREAD

**Issue by HenMie** [cloudreve/Cloudreve#1157]
目前存在问题：但需打包的文件过大时，很容易导致错误，并且很多时候也无法正确完成打包。
建议：增加打包大小的限制，限制打包文件体积，避免上述情况发生。
附加：目前打包是流程是发送打包请求，网页转圈加载，打包完成后返回下载链接。如果打包时间较长，用户很可能误认为发生错误，从而刷新界面等。因此还可以考虑增加后台打包功能，如离线下载一样处理。

**Comment by HFO4** [comment]
后续会流式处理打包下载。
