### ISSUE TITLE
V3.4.2 对接Onedrive国际版，无法上传，无法下载

### ISSUE THREAD

**Issue by kasie-zhang** [cloudreve/Cloudreve#1158]
## 前言
截止到昨天下午四点，Cloudreve 一直运行的很好。现在对接Onedrive出现了问题（对接又拍云是正常的！）。我尝试使用 3.4.1 版本，但未起作用。

## 问题描述

1. 无法上传，报错如下

![](https://uf.zk123.top/u%2F5ECVS5XT_2022-03-12_1.png)

2. 无法预览

3. 无法下载（提示无法获取外链）

## 测试账户
[项目地址](https://drive.zk123.top/)

测试账户：test@test.com

密码: test

**Comment by lsCoding666** [comment]
先重新对接试试 最好就是重新开client id和密钥，然后不行再试试ip:5212访问试试 就是通过http访问试试

**Comment by kasie-zhang** [comment]
@lsCoding666 感谢你及时有效的回答。重新设置 Client ID 和 Client Secret 解决了问题。
