### ISSUE TITLE
当用户已经登录时，访问【域名】/login 会又出来一个登录页面

### ISSUE THREAD

**Issue by HaoShen2021** [cloudreve/Cloudreve#1160]
如题，右上角已经显示登陆了
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/90556839/158152549-37c09098-b29e-41e5-b67c-b52e07fb1634.png">

应该改为跳转到  域名/home 界面

**Comment by qitayun** [comment]
那不是废话吗，你访问/login干啥……

**Comment by unauth401** [comment]
正常情况下应该直接redirect 不是特别严重的bug吧

**Comment by HaoShen2021** [comment]
有谁知道怎么设置重定向吗？


| |
皓神官方
|
|
***@***.***
|
在2022年4月10日 ***@***.***> 写道：

正常情况下应该直接redirect 不是特别严重的bug吧

**Comment by HFO4** [comment]
不算啥严重的问题，欢迎pr

**Comment by qitayun** [comment]
小白就去百度一下 别问这么简单的问题了……




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cloudreve/Cloudreve"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 晚上6:14
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cloudreve/Cloudreve] 当用户已经登录时，访问【域名】/login 会又出来一个登录页面 (Issue #1160)





 有谁知道怎么设置重定向吗？
 
 
 | |
 皓神官方
 |
 |
 ***@***.***
 |
 在2022年4月10日 ***@***.***&gt; 写道：
 
 正常情况下应该直接redirect 不是特别严重的bug吧
