### ISSUE TITLE
ipad端点击下载按钮没有反应，那个下载按钮的长条框会直接缩回去消失掉。

### ISSUE THREAD

**Issue by DamoLiu** [cloudreve/Cloudreve#1162]
我用的是捐助版，现在很多用户都反应 ipad端 无法下载文件。。这个比较着急。 就是选中文件后，一点击右上角的黑色小云朵标志，那个长条框就回缩回去，没有任何反应，现在有的朋友无意中测试到，如果用手点就出现这样的状况，他用了一根触碰笔，用笔的笔尖，很细的地方触碰下载按钮，就可以下载，目前看来应该是IPAD端那个下载按钮可触碰的区域非常小，用手点的话，就像是点在了别的空白地方的效果，所以那个长条框会缩回去。这样，如果是不支持在线预览的文件，还可以通过双击文件直接弹出来下载框。。 要是支持在线预览的文件格式，比如PDF,DOC之类的，一双击就成了直接在线预览了，也还是下载不下来文件。。求大佬修复。。因为用IPAD端的朋友还是挺多的，下载不了文件。。

**Comment by HFO4** [comment]
在3.5.3中应该没问题了。
