### ISSUE TITLE
世纪互联图片缩略图有时候会失效

### ISSUE THREAD

**Issue by Shizuri23** [cloudreve/Cloudreve#1165]
<img width="1917" alt="image" src="https://user-images.githubusercontent.com/46082179/158520746-ef020418-db02-452d-9254-92ad0f58bf29.png">
如图片，会变成这个样子....
Cloudreve 3.4.2

**Comment by Shizuri23** [comment]
<img width="1133" alt="image" src="https://user-images.githubusercontent.com/46082179/158647327-5b9b1db9-d018-4009-87d7-9ef10719c86d.png">

**Comment by HFO4** [comment]
后期会优化OneDrive策略图Fallback的逻辑

**Comment by Shizuri23** [comment]
> 

如果onedrive缩略图能换到本地就好了
目前3.5.3版本也是这样
