### ISSUE TITLE
webdav在使用mysql做为数据库的时候阅读无法正常上传(docker版)

### ISSUE THREAD

**Issue by ggtony233** [cloudreve/Cloudreve#1166]
[Warning] 2022-03-16 19:30:46 无法插入目录记录, Error 1062: Duplicate entry 'legado-4' for key 'cd_folders.idx_only_one_name'
[GIN] 2022/03/16 - 19:30:46 | 409 |   15.079452ms |     192.168.2.1 | MKCOL    /dav/legado/
[Warning] 2022-03-16 19:30:46 无法插入目录记录, Error 1062: Duplicate entry 'bookProgress-5' for key 'cd_folders.idx_only_one_name'
[GIN] 2022/03/16 - 19:30:46 | 409 |   16.319018ms |     192.168.2.1 | MKCOL    /dav/legado/bookProgress/
[GIN] 2022/03/16 - 19:30:46 | 404 |   16.211407ms |     192.168.2.1 | GET      /dav/legado/bookProgress/鬼谷子_王诩.json
[Warning] 2022-03-16 19:30:46 无法插入目录记录, Error 1062: Duplicate entry 'legado-4' for key 'cd_folders.idx_only_one_name'
[GIN] 2022/03/16 - 19:30:46 | 409 |   17.657844ms |     192.168.2.1 | MKCOL    /dav/legado/
[Warning] 2022-03-16 19:30:46 无法插入目录记录, Error 1062: Duplicate entry 'bookProgress-5' for key 'cd_folders.idx_only_one_name'
[GIN] 2022/03/16 - 19:30:46 | 409 |   17.377589ms |     192.168.2.1 | MKCOL    /dav/legado/bookProgress/
[GIN] 2022/03/16 - 19:30:46 | 404 |   14.508801ms |     192.168.2.1 | GET      /dav/legado/bookProgress/圣墟_辰东.json
[Warning] 2022-03-16 19:30:46 无法插入目录记录, Error 1062: Duplicate entry 'legado-4' for key 'cd_folders.idx_only_one_name'
[GIN] 2022/03/16 - 19:30:46 | 409 |   18.480373ms |     192.168.2.1 | MKCOL    /dav/legado/
[Warning] 2022-03-16 19:30:46 无法插入目录记录, Error 1062: Duplicate entry 'bookProgress-5' for key 'cd_folders.idx_only_one_name'
以上为错误日志。。。。。。

**Comment by HFO4** [comment]
什么WebDAV客户端？

**Comment by ggtony233** [comment]
开源阅读发自我的华为平板-------- 原始邮件 --------发件人： AaronLiu ***@***.***>日期： 2022年3月18日周五 晚上8:07收件人： cloudreve/Cloudreve ***@***.***>抄送： ggtony233 ***@***.***>, Author ***@***.***>主    题： Re: [cloudreve/Cloudreve] webdav在使用mysql做为数据库的时候阅读无法正常上传(docker版) (Issue #1166)

什么WebDAV客户端？

**Comment by ggtony233** [comment]
开源阅读

**Comment by ggtony233** [comment]
joplin在使用mysql5.7版本时，同样出现webdav上传错误，在使用自带的sqlite时则一切正常

但这次数据库没有报错，而是在cloudreve社区版里报错，文件无法增加，这是mysql的问题还是？
以下为日志不正常的内容
```linux

[GIN] 2022/04/27 - 11:06:31 | 405 |   16.301525ms |  112.44.251.136 | PUT      "/dav/info.json"


[GIN] 2022/04/27 - 11:06:38 | 200 |    2.422965ms |   61.241.55.180 | GET      "/"


[Warning] 2022-04-27 11:06:41 钩子执行失败：同名文件或目录已存在
```

**Comment by HFO4** [comment]
> joplin在使用mysql5.7版本时，同样出现webdav上传错误，在使用自带的sqlite时则一切正常
> 
> 但这次数据库没有报错，而是在cloudreve社区版里报错，文件无法增加，这是mysql的问题还是？ 以下为日志不正常的内容
> 
> ```
> 
> [GIN] 2022/04/27 - 11:06:31 | 405 |   16.301525ms |  112.44.251.136 | PUT      "/dav/info.json"
> 
> 
> [GIN] 2022/04/27 - 11:06:38 | 200 |    2.422965ms |   61.241.55.180 | GET      "/"
> 
> 
> [Warning] 2022-04-27 11:06:41 钩子执行失败：同名文件或目录已存在
> ```

这是 3.5.2 出现的吗？

**Comment by ggtony233** [comment]
在之前的3.5.0beta貌似也能看到这个问题，我在mysql8.0时也能碰到这个问题，切到5.7时问题依旧在，mysql具体版本为5.7.22

**Comment by HFO4** [comment]
尝试升级到3.5.2看看
ggtony233 ***@***.***>于2022年4月27日 周三11:33写道：

**Comment by ggtony233** [comment]
好的，我目前使用的是3.5.1版本，确认3.5.2已经没有以上问题，感谢大佬回答

**Comment by ggtony233** [comment]
在切换到3.5.2时没有以上问题
