### ISSUE TITLE
使用OneDrive世纪互联存储策略, 上传同名文件报告错误

### ISSUE THREAD

**Issue by cxw620** [cloudreve/Cloudreve#1169]
**Describe the bug**
如题.
控制台输出
```
[Cloudreve-uploader][error] err:  {status: 402, response: '{"code":50002,"msg":"无法获取上传凭证"}\n', file: PluploadFile, message: '无法获取上传凭证', code: 402}
```
**To Reproduce**
目前百分百复现. 

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: `Windows`
 - Browser: `Chrome`
 - Version `3.4.2`

**Additional context**
文件历史记录功能或许会有用

**Comment by HFO4** [comment]
不支持覆盖物理同名文件。
