### ISSUE TITLE
访问白屏，无法上传，404

### ISSUE THREAD

**Issue by gyigi** [cloudreve/Cloudreve#1170]
**Describe the bug**
可以访问网站，但无法上传，f12报一个404，刷新（ctrl+r）/清缓存无效
![image](https://user-images.githubusercontent.com/62084226/158942639-320cc15b-f7ec-4b41-8b27-90ff0b949145.png)
使用ctrl+f5刷新显示白屏，f12报多个404，但再使用ctrl+r可以回到前面那种情况
![image](https://user-images.githubusercontent.com/62084226/158942673-16663332-b71f-4372-a9c5-b383451912de.png)

**To Reproduce**
只在特定服务端（在我树莓派上搭建），特定设备（我的电脑），特定浏览器（我电脑上的chrome）有该情况，其他设备/浏览器全部白屏
但是使用github上一人的手机客户端是可以正常加载/上传文件的

**Desktop (please complete the following information):**
 - OS: Windows 11 Insider Preview Build 22567
 - Browser Chrome
 - Version 99.0.4844.74

**Smartphone (please complete the following information):**
 - Device: Huawei Mate 30
 - OS: Harmony OS 2.0.0.216
 - Browser Chrome
 - Version 98.0.4758.101

**Additional context**
服务端：树莓派4B 8G，使用Debian 11 arm64，Nginx 1.21.4，MySQL 8.0.24，Cloudreve 3.4.2，使用Nginx进行反代，使用CloudFlare
网址：cloud.skyshi.tech，访问应该是白屏f12报404

**Comment by GreenTeodoro839** [comment]
反代是用的文档里的代码吗？

**Comment by gyigi** [comment]
> 反代是用的文档里的代码吗？

是的

**Comment by GreenTeodoro839** [comment]
> > 反代是用的文档里的代码吗？
> 
> 是的

有试过sqlite数据库吗

**Comment by gyigi** [comment]
> > > 反代是用的文档里的代码吗？
> > 
> > 
> > 是的
> 
> 有试过sqlite数据库吗

有试过，一开始用的是自带的sqlite，发现上述情况后就换了mysql
另外还使用了redis，但没有redis也是这个情况

**Comment by HFO4** [comment]
Nginx 站点配置中跟静态资源有关的配置删除即可。

**Comment by gyigi** [comment]
> Nginx 站点配置中跟静态资源有关的配置删除即可。

感谢回复。
问题成功解决（当然是没有frp的情况）

**Comment by topjohncian** [comment]
宝塔 Nginx 缓存规则也有可能造成此错误
