### ISSUE TITLE
关于从站离线下载的负载均衡权重配置

### ISSUE THREAD

**Issue by KyonCN** [cloudreve/Cloudreve#1172]
请问从站离线下载的负载均衡权重数字是越大分配到的任务越多，还是数字越小分配到的任务越多？
我从主从两个机器分别设置1和1000、1000和1进行测试。依次添加离线任务进行测试。
在后台里分配的任务都是主从各1个任务，依次分配进行。

目前版本v3.4.2主站的离线下载无法暂停使用，只要主站跑满下载，访问就会变的很慢。
翻阅了文档貌似没有相关解释，所以想请教一下，这个离线下载的负载均衡的权重数字越大还是越小分配任务越少，或者是否考虑以后的版本可以直接禁用本站的离线下载。

谢谢开发者

**Comment by topjohncian** [comment]
此版本(3.4.2)，并未实装负载均衡(及其权重)功能

**Comment by KyonCN** [comment]
> 此版本(3.4.2)，并未实装负载均衡(及其权重)功能

好的 谢谢
