### ISSUE TITLE
Office文件预览服务打不开文件

### ISSUE THREAD

**Issue by 13663316223** [cloudreve/Cloudreve#1174]
![image](https://user-images.githubusercontent.com/84111600/159839366-e01937e8-e130-464c-8693-4b314cb7cdb0.png)
看起来是缺少一个JS文件
![image](https://user-images.githubusercontent.com/84111600/159839393-13a0bc86-a48d-4be6-9848-f850d5f5f029.png)
网上说是因为IP地址的缘故，需要使用域名。但是我现在已经是域名访问了。格式是：http://域名:port，至于问为什么不用80端口，是因为运营商的公网封80端口，打开的话得需要备案

**Comment by 13663316223** [comment]
我的本地端口5212，外网映射端口是8082

**Comment by topjohncian** [comment]
必须使用 80 / 443 等标准端口
也可以自建 kkFileView 等 Office 预览服务

**Comment by wisinfun** [comment]
> 必须使用 80 / 443 等标准端口 也可以自建 kkFileView 等 Office 预览服务

老哥，具体的设置步骤可以分享下吗，不胜感激

**Comment by topjohncian** [comment]
自建 [kkFileView](https://kkfileview.keking.cn/zh-cn/index.html) 
Cloudreve 后台设置中 预览选项填入 kkFileView 的预览地址
``` http://your.kkfileview/onlinePreview?url={$srcB64} ```

**Comment by wisinfun** [comment]
> 自建 [kkFileView](https://kkfileview.keking.cn/zh-cn/index.html) Cloudreve 后台设置中 预览选项填入 kkFileView 的预览地址 `http://your.kkfileview/onlinePreview?url={$srcB64}`

感谢感谢

**Comment by Kotori-0912** [comment]
> 自建 [kkFileView](https://kkfileview.keking.cn/zh-cn/index.html) Cloudreve 后台设置中 预览选项填入 kkFileView 的预览地址 `http://your.kkfileview/onlinePreview?url={$srcB64}`

![Q1](https://user-images.githubusercontent.com/25550007/172131630-67861f7d-b167-494f-8ea0-59d5788d65a5.png)
![Q2](https://user-images.githubusercontent.com/25550007/172132858-cc063a43-b942-49b7-b2a5-db9dfae3dcb7.png)
老哥，请教一下，我在本地搭建好了kkFileView之后按照你的设置，在后台设置好之后，打开文件就提示文件类型不支持，这个问题有遇到过吗？

**Comment by 632575987** [comment]
> > 自建 [kkFileView](https://kkfileview.keking.cn/zh-cn/index.html) Cloudreve 后台设置中 预览选项填入 kkFileView 的预览地址 `http://your.kkfileview/onlinePreview?url={$srcB64}`
> 
> ![Q1](https://user-images.githubusercontent.com/25550007/172131630-67861f7d-b167-494f-8ea0-59d5788d65a5.png) ![Q2](https://user-images.githubusercontent.com/25550007/172132858-cc063a43-b942-49b7-b2a5-db9dfae3dcb7.png) 老哥，请教一下，我在本地搭建好了kkFileView之后按照你的设置，在后台设置好之后，打开文件就提示文件类型不支持，这个问题有遇到过吗？

我也遇到了这个问题。。。

**Comment by qiangweihewu** [comment]
微软的这个可以：
https://view.officeapps.live.com/op/embed.aspx?src={$src}
