### ISSUE TITLE
PC端兑换码的小BUG

### ISSUE THREAD

**Issue by DamoLiu** [cloudreve/Cloudreve#1176]
后台自动批量生成的兑换码全都是小写字母的，在移动端测试时直接复制兑换码去激活没有任何问题，但是 PC端的网页内复制兑换码粘贴过去会自动全都变成大写字母，然后点击兑换时会弹出来兑换码无效的提示，但是实际后台查询，这个兑换码是已使用掉了，实际也是兑换成功了的，但是客户那边是提示的兑换码无效。

**Comment by Licsber** [comment]
同遇到兑换积分后 积分不到账 兑换码显示已使用bug

**Comment by HFO4** [comment]
> 同遇到兑换积分后 积分不到账 兑换码显示已使用bug
> 
> 
> 
> Update:
> 
> 不明原因 现无法复现
> 
> 
> 
> Update1:
> 
> 不明原因 只针对某个用户无法兑换 但后台将其积分改为非0后又正常

是不是开源版本升级pro版没有执行升级脚本
