### ISSUE TITLE
windows版文件导入功能报错

### ISSUE THREAD

**Issue by 632575987** [cloudreve/Cloudreve#1179]
**Describe the bug**
不知道是不是windows路径（/）的问题，导入文件目录结构不成功

**To Reproduce**
1. 点击头像
2. 点击管理面板
3. 文件
4.从外部导入
![QQ截图20220328152635](https://user-images.githubusercontent.com/3284852/160347519-c7d1f7f3-2a6b-4885-98e5-0a2deaafb219.png)

**Screenshots**

![QQ截图20220328152042](https://user-images.githubusercontent.com/3284852/160346916-fd976dbd-07a4-4844-a8ea-3694e08df5e0.png)

**Desktop:**
 - OS: Windows10 1903
 - Browser: Edge
 - Version: 版本 94.0.992.50 (官方内部版本) (64 位)

**Comment by HFO4** [comment]
目的目录路径填写有误。这是用户在Cloudreve端的路径，不是物理文件系统路径。
