### ISSUE TITLE
成功接到从机，但是从机返回：签名已过期

### ISSUE THREAD

**Issue by C4a15Wh** [cloudreve/Cloudreve#1183]
版本: 3.4.2
问题: 连接到从机时出现错误，签名已过期
![image](https://user-images.githubusercontent.com/61458603/160918083-c0e495cd-0ac3-43c6-a85c-f3e37338decf.png)
已经确认从机网络状况良好且配置文件严格按照提示填写

**Comment by C4a15Wh** [comment]
主从机的时间要一样

**Comment by EvenCu** [comment]
> 主从机的时间要一样

运行一年后出现此问题，请教一下下 - -
