### ISSUE TITLE
通过连接进行匿名上传

### ISSUE THREAD

**Issue by wangxiaodong1021** [cloudreve/Cloudreve#1184]
希望能增加匿名上传功能，用户创建文件上传请求，设置密码，分享给另一个用户，他不用登录就可以通过这个链接上传文件。

**Comment by lbyxiaolizi** [comment]
感觉不大可能实现吧，不太像正常网盘的功能

**Comment by mao13820** [comment]
同求，希望能增加匿名账号功能。这样朋友之间分享文件照片，就不用登陆了，毕竟账号密码太复杂了。没有直接点开方便直接。

**Comment by qq77522980** [comment]
这个功能其实nextcloud就有，分享的文件夹支持上传文件，希望cloudreve也增加。
