### ISSUE TITLE
COS存储策略下，文件上传之后看不见

### ISSUE THREAD

**Issue by epis2048** [cloudreve/Cloudreve#1187]
**Describe the bug**
使用GitHub上面最新版代码编译之后，COS存储策略下，Web方式文件上传之后看不见，但是后台文件列表可以看见该文件。

经测试，数据库中上传的文件size列为0，将upload_session_id统一update为NULL之后可以看见了。

推测是腾讯云COS存储策略下，文件上传至COS后没有更新文件信息（计算Size，清空upload_session_id），导致前端不能正确显示文件。（可能是前端的问题，上传过程由前端与COS交互）

其他存储策略未测试，不知道是否存在此问题。

此外，右键上传文件会显示“上传组件未加载”，右下角的加号可以正常使用。

**Comment by topjohncian** [comment]
`master` 分支处于开发状态，请 checkout 到对应版本编译

**Comment by HFO4** [comment]
感谢提醒，漏了一个步骤，已经fix
