### ISSUE TITLE
build failure:sqlite3-binding.c: In function ‘sqlite3SelectNew’

### ISSUE THREAD

**Issue by lanwood** [cloudreve/Cloudreve#1190]
VERSION: 3.4.2-51-gec776ac
COMMIT_SHA : ec776ac

after typing "go build -a -o cloudreve"，
it happends:

# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:125322:10: warning: function may return address of local variable [-Wreturn-local-addr]
125322 |   return pNew;
       |          ^~~~
sqlite3-binding.c:125282:10: note: declared here
125282 |   Select standin;
       |          ^~~~~~~
# github.com/cloudreve/Cloudreve/v3/service/explorer
service/explorer/upload.go:56:19: undefined: time.UnixMilli

**Comment by lsCoding666** [comment]
I just compile the entire project at ec776ac without any failue.
complie on wsl:
```
git clone --recurse-submodules https://github.com/cloudreve/Cloudreve.git
cd assets
yarn install
yarn run build 
cd ..
go get github.com/rakyll/statik
statik -src=assets/build/  -include=*.html,*.js,*.json,*.css,*.png,*.svg,*.ico,*.ttf -f
export COMMIT_SHA=$(git rev-parse --short HEAD)
export VERSION=$(git describe --tags)
go build -a -o cloudreve -ldflags " -X 'github.com/cloudreve/Cloudreve/v3/pkg/conf.BackendVersion=$VERSION' -X 'github.com/cloudreve/Cloudreve/v3/pkg/conf.LastCommit=$COMMIT_SHA'"
```

**Comment by lanwood** [comment]
> I just compile the entire project at [ec776ac](https://github.com/cloudreve/Cloudreve/commit/ec776ac837bce68729d79f4f82e0f4c2ef81b33c) without any failue. complie on wsl:
> 
> ```
> git clone --recurse-submodules https://github.com/cloudreve/Cloudreve.git
> cd assets
> yarn install
> yarn run build 
> cd ..
> go get github.com/rakyll/statik
> statik -src=assets/build/  -include=*.html,*.js,*.json,*.css,*.png,*.svg,*.ico,*.ttf -f
> export COMMIT_SHA=$(git rev-parse --short HEAD)
> export VERSION=$(git describe --tags)
> go build -a -o cloudreve -ldflags " -X 'github.com/cloudreve/Cloudreve/v3/pkg/conf.BackendVersion=$VERSION' -X 'github.com/cloudreve/Cloudreve/v3/pkg/conf.LastCommit=$COMMIT_SHA'"
> ```




=====================

thx for help，It is uncertain whether the operating system caused the failure，this is my OS details:

LSB Version:    :core-4.1-amd64:core-4.1-noarch
Distributor ID: AlibabaCloud
Description:    Alibaba Cloud Linux release 3 (Soaring Falcon)
Release:        3
Codename:       SoaringFalcon

I Stuck in the last step as follows:

```shell
[root@lycc Cloudreve]# export COMMIT_SHA=$(git rev-parse --short HEAD)
[root@lycc Cloudreve]# echo $COMMIT_SHA
ec776ac
[root@lycc Cloudreve]# export VERSION=$(git describe --tags)
[root@lycc Cloudreve]# echo $VERSION
3.4.2-51-gec776ac
[root@lycc Cloudreve]#
[root@lycc Cloudreve]# go build -a -o cloudreve -ldflags " -X 'github.com/cloudreve/Cloudreve/v3/pkg/conf.BackendVersion=$VERSION' -X 'github.com/cloudreve/Cloudreve/v3/pkg/conf.LastCommit=$COMMIT_SHA'"
# github.com/mattn/go-sqlite3
sqlite3-binding.c: In function ‘sqlite3SelectNew’:
sqlite3-binding.c:125322:10: warning: function may return address of local variable [-Wreturn-local-addr]
125322 |   return pNew;
       |          ^~~~
sqlite3-binding.c:125282:10: note: declared here
125282 |   Select standin;
       |          ^~~~~~~
# github.com/cloudreve/Cloudreve/v3/service/explorer
service/explorer/upload.go:56:19: undefined: time.UnixMilli

```

**Comment by lsCoding666** [comment]
go version go1.18 linux/amd64
ubuntu 20.04lts wsl
npm 8.6.0
node.js v16.14.2
![image](https://user-images.githubusercontent.com/73888354/161438766-51757c90-9ca7-4689-a233-2a72cd1d31f2.png)

Hope to help you

**Comment by lsCoding666** [comment]
Or binary file：
[cloudreve.zip](https://github.com/cloudreve/Cloudreve/files/8405069/cloudreve.zip)

**Comment by topjohncian** [comment]
https://github.com/mattn/go-sqlite3/issues/822

**Comment by topjohncian** [comment]
`sqlite3-binding.c: In function ‘sqlite3SelectNew’:` is just a warning. You certainly can ignore it.

The problem to be solved is `service/explorer/upload.go:56:19: undefined: time.UnixMilli`
`time.UnixMilli` was added in go 1.17. 
So please update your go version to 1.17 or higher.
