### ISSUE TITLE
离线下载：下载出错，目标名称非法

### ISSUE THREAD

**Issue by 0123454321** [cloudreve/Cloudreve#1191]
我下的是Youtu解析出来的视频链接，会自动生成一个以视频标题为名的文件名，但是有些字符无法做为文件名，同时离线下载又不支持自定义文件名，造成无法下载此类链接，附上原视频和解析后的地址。
原视频：https://www.youtube.com/watch?v=adN9L0ktFOE
解析下载地址：https://rr1---sn-ab5sznzs.googlevideo.com/videoplayback?expire=1649044837&ei=BRlKYpyNC6GmhwahgpGoDg&ip=91.229.105.127&id=o-AHy0lM7ryJJRJt4Krh8H3QCu8Ide61qT_g3wLvlxXYw8&itag=22&source=youtube&requiressl=yes&mh=I9&mm=31%2C29&mn=sn-ab5sznzs%2Csn-ab5l6nzr&ms=au%2Crdu&mv=m&mvi=1&pl=23&initcwndbps=1431250&spc=4ocVC1dO16_k2cgtOUIYuSfRYqML&vprv=1&mime=video%2Fmp4&ns=KUQzd2udmtfmbBshXPGyIw4G&cnr=14&ratebypass=yes&dur=6862.169&lmt=1647249163711818&mt=1649022773&fvip=5&fexp=24001373%2C24007246&c=WEB&txp=5532434&n=-13dSvJIgYzaWMg2I&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Cmime%2Cns%2Ccnr%2Cratebypass%2Cdur%2Clmt&sig=AOq0QJ8wRQIgTfLM7p8nMiFYJuaaN-yZ2Y1-gr6ssCigo8T2zvfu9n8CIQDxEHwOAYm2iWfKrlgYx6AWSjae-XIhiyTrxITYqHceBw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AG3C_xAwRQIgQjzjRl2ws5DXG6bV55adM_g6_Gl14czQOAujLds5X8UCIQCuxf0IcLcraHAdQ-0DSu3G0GWTyMqKur5s366PaIyd2w%3D%3D&title=%E6%B8%A9%E9%93%81%E5%86%9B%EF%BC%9A%E5%85%A8%E7%90%83%E5%8C%96%E8%BF%9B%E7%A8%8B%E4%B8%AD%E7%9A%84%E4%B8%AD%E5%9B%BD%E5%8D%B1%E6%9C%BA%E4%B8%8E%E7%BB%8F%E9%AA%8C%E3%80%90%E6%B8%A9%E9%93%81%E5%86%9B%E8%B7%B5%E9%97%BB%E5%BD%95|%E4%B8%A4%E5%B0%8F%E6%97%B6%E6%94%B6%E8%97%8F%E5%90%91%E3%80%91

出现错误的截图：
![截屏2022-04-04 上午6 04 28](https://user-images.githubusercontent.com/97329753/161451058-1cfb3b8f-6fc1-4b52-9256-c12c8eceb378.png)

**Comment by lsCoding666** [comment]
https://github.com/cloudreve/Cloudreve/issues/1124
一样的问题

**Comment by 0123454321** [comment]
> #1124 一样的问题

这个问题很突出啊，怎么不解决一下呢，你有编译好的二进制文件吗？

**Comment by 0123454321** [comment]
> #1124 一样的问题

我也找到了一种办法，改title
![截屏2022-04-04 下午4 15 17](https://user-images.githubusercontent.com/97329753/161502775-802a66c2-faf8-4a1e-91d6-e85e57e4d746.png)


![截屏2022-04-04 下午4 12 27](https://user-images.githubusercontent.com/97329753/161502820-b33d7ae6-f6f6-4bad-87e4-483ce6823067.png)
