### ISSUE TITLE
cloudreve能否自动检查非法文件

### ISSUE THREAD

**Issue by huangdihd** [cloudreve/Cloudreve#1195]
我打算用cloudreve搭建一个网盘，但是我担心其他人会上传一些非法的文件，cloudreve有组织非法文件上传的功能吗，如果没有，能添加这个功能吗

**Comment by huangdihd** [comment]
我不小心把“阻止”打成“组织”了

**Comment by huangdihd** [comment]
额，有人回答吗

**Comment by topjohncian** [comment]
没有

**Comment by wangxiaoerYah** [comment]
还自动检查非法文件，你知道非法文件长什么样子?别人网盘可以检查，是基于人工识别加确认过的文件的md值来确定，你可以自己接腾讯或者阿里的API。但是完全没必要在这里加，这个定位是私人云盘，你是想商用。商用的话自己改源码，本身就是开源。

**Comment by lsCoding666** [comment]
答主好像是被人搞了 好像在官方群看到了，就是说自己建了个网盘，然后被人上传非法文件举报了，被请去喝茶了

**Comment by lsCoding666** [comment]
我有一计：vps用国外的 ，域名新买一个不备案，网盘ban中国ip，只给国外人用，避免审查。不可能阻止用户上传非法文件的，百度网盘和b站都解决不了的问题，更别说我么了

**Comment by huangdihd** [comment]
额，好吧

**Comment by act-m** [comment]
如果存储策略使用的是腾讯云对象存储，可以为存储桶开启万象内容审核。
此功能按使用量收费，见：https://cloud.tencent.com/document/product/436/45435

**Comment by wangxiaoerYah** [comment]
> 答主好像是被人搞了 好像在官方群看到了，就是说自己建了个网盘，然后被人上传非法文件举报了，被请去喝茶了

那就不科学了，如果没有用国内的储存，然后把普通用户分享权限关闭，能别人怎么举报，而且也没人知道这个站点到底有什么文件。如果开启分享，那别人拿去搞，就会被查了。

反正我直接就是禁止注册，只给信得过的用

**Comment by wangxiaoerYah** [comment]
> 如果存储策略使用的是腾讯云对象存储，可以为存储桶开启万象内容审核。
> 此功能按使用量收费，见：https://cloud.tencent.com/document/product/436/45435

这个的话就要去适配了

你上传一个文件到了对象储存，然后对象储存过了一会检查到非法，给你删除了，cloudreve没适配还不知道被删除，他还是会引用第一次存入的链接。所以现在还是不可用的。如果开启的话，到时候你的cloudreve各种文件不见了，有得你哭😭重装整个站点

**Comment by act-m** [comment]
@wangxiaoerYah 站点公告里写清楚就行了，谁传了非法文件谁心里清楚。

**Comment by act-m** [comment]
> > 如果存储策略使用的是腾讯云对象存储，可以为存储桶开启万象内容审核。
> > 此功能按使用量收费，见：https://cloud.tencent.com/document/product/436/45435
> 
> 这个的话就要去适配了
> 
> 你上传一个文件到了对象储存，然后对象储存过了一会检查到非法，给你删除了，cloudreve没适配还不知道被删除，他还是会引用第一次存入的链接。所以现在还是不可用的。如果开启的话，到时候你的cloudreve各种文件不见了，有得你哭😭重装整个站点

刚新建了一个存储桶做了个小实验，COS+CDN。手动从存储桶里删除文件（模拟万象审核后删除），在Cloudreve系统里，只是不显示缩略图及无法找到源文件，404错误。但站点不受影响。Cloudreve存储文件的状态信息在数据库里，文件存储位置不影响前端。因此应该是无需重装站点什么的。
![CleanShot 2022-04-09 at 02 26 03@2x](https://user-images.githubusercontent.com/87530132/162501676-5efdb779-e089-4dc6-b63b-efcaadfd84b3.jpg)

**Comment by wangxiaoerYah** [comment]
> > > 如果存储策略使用的是腾讯云对象存储，可以为存储桶开启万象内容审核。
> > > 此功能按使用量收费，见：https://cloud.tencent.com/document/product/436/45435
> > 
> > 这个的话就要去适配了
> > 
> > 你上传一个文件到了对象储存，然后对象储存过了一会检查到非法，给你删除了，cloudreve没适配还不知道被删除，他还是会引用第一次存入的链接。所以现在还是不可用的。如果开启的话，到时候你的cloudreve各种文件不见了，有得你哭😭重装整个站点
> 
> 刚新建了一个存储桶做了个小实验，COS+CDN。手动从存储桶里删除文件（模拟万象审核后删除），在Cloudreve系统里，只是不显示缩略图及无法找到源文件，404错误。但站点不受影响。Cloudreve存储文件的状态信息在数据库里，文件存储位置不影响前端。因此应该是无需重装站点什么的。
> ![CleanShot 2022-04-09 at 02 26 03@2x](https://user-images.githubusercontent.com/87530132/162501676-5efdb779-e089-4dc6-b63b-efcaadfd84b3.jpg)
> 
> 

。。。你都知道找不文件，文件还在数据库里面了。这是上传一个文件，你开启离线下载，一个种子文件几十上百。然后，如果还是多用户，打个比方，同时有4-5个用户上传，离线下载了文件，他们都是间隔几天，找到点片就丢到离线里去了。然后有一天突然想看了，然后打不开，你怎么解决?一个个查看存储桶对比数据库?然后再加点魔法变量命名，一堆字符串你去查?我估计你得头大，直接重装。

都说了，要适配下，非要杠

**Comment by wangxiaoerYah** [comment]
> > > > 如果存储策略使用的是腾讯云对象存储，可以为存储桶开启万象内容审核。
> > > > 此功能按使用量收费，见：https://cloud.tencent.com/document/product/436/45435
> > > 
> > > 这个的话就要去适配了
> > > 
> > > 你上传一个文件到了对象储存，然后对象储存过了一会检查到非法，给你删除了，cloudreve没适配还不知道被删除，他还是会引用第一次存入的链接。所以现在还是不可用的。如果开启的话，到时候你的cloudreve各种文件不见了，有得你哭😭重装整个站点
> > 
> > 刚新建了一个存储桶做了个小实验，COS+CDN。手动从存储桶里删除文件（模拟万象审核后删除），在Cloudreve系统里，只是不显示缩略图及无法找到源文件，404错误。但站点不受影响。Cloudreve存储文件的状态信息在数据库里，文件存储位置不影响前端。因此应该是无需重装站点什么的。
> > ![CleanShot 2022-04-09 at 02 26 03@2x](https://user-images.githubusercontent.com/87530132/162501676-5efdb779-e089-4dc6-b63b-efcaadfd84b3.jpg)
> > 
> > 
> 
> 。。。你都知道找不文件，文件还在数据库里面了。这是上传一个文件，你开启离线下载，一个种子文件几十上百。然后，如果还是多用户，打个比方，同时有4-5个用户上传，离线下载了文件，他们都是间隔几天，找到点片就丢到离线里去了。然后有一天突然想看了，然后打不开，你怎么解决?一个个查看存储桶对比数据库?然后再加点魔法变量命名，一堆字符串你去查?我估计你得头大，直接重装。
> 
> 都说了，要适配下，非要杠

不能保证稳定可以，那这活就是白整，还不如直接用那种zfile oneflie这种单页网盘

**Comment by act-m** [comment]
> > > > 如果存储策略使用的是腾讯云对象存储，可以为存储桶开启万象内容审核。
> > > > 此功能按使用量收费，见：https://cloud.tencent.com/document/product/436/45435
> > > 
> > > 
> > > 这个的话就要去适配了
> > > 你上传一个文件到了对象储存，然后对象储存过了一会检查到非法，给你删除了，cloudreve没适配还不知道被删除，他还是会引用第一次存入的链接。所以现在还是不可用的。如果开启的话，到时候你的cloudreve各种文件不见了，有得你哭😭重装整个站点
> > 
> > 
> > 刚新建了一个存储桶做了个小实验，COS+CDN。手动从存储桶里删除文件（模拟万象审核后删除），在Cloudreve系统里，只是不显示缩略图及无法找到源文件，404错误。但站点不受影响。Cloudreve存储文件的状态信息在数据库里，文件存储位置不影响前端。因此应该是无需重装站点什么的。
> > ![CleanShot 2022-04-09 at 02 26 03@2x](https://user-images.githubusercontent.com/87530132/162501676-5efdb779-e089-4dc6-b63b-efcaadfd84b3.jpg)
> 
> 。。。你都知道找不文件，文件还在数据库里面了。这是上传一个文件，你开启离线下载，一个种子文件几十上百。然后，如果还是多用户，打个比方，同时有4-5个用户上传，离线下载了文件，他们都是间隔几天，找到点片就丢到离线里去了。然后有一天突然想看了，然后打不开，你怎么解决?一个个查看存储桶对比数据库?然后再加点魔法变量命名，一堆字符串你去查?我估计你得头大，直接重装。
> 
> 都说了，要适配下，非要杠

是谁在杠呢？我在提供解决方案，你只说这种不可用要适配，又没说出有何适配方案。作为公共网盘，如果本身在大陆运营，那么就必须需要做审查。用户自己上传了非法文件，丢失了还要管理员来找？这是什么逻辑？

**Comment by huangdihd** [comment]
感谢大家

**Comment by huangdihd** [comment]
> > > 如果存储策略使用的是腾讯云对象存储，可以为存储桶开启万象内容审核。
> > > 此功能按使用量收费，见：https://cloud.tencent.com/document/product/436/45435
> > 
> > 
> > 这个的话就要去适配了
> > 你上传一个文件到了对象储存，然后对象储存过了一会检查到非法，给你删除了，cloudreve没适配还不知道被删除，他还是会引用第一次存入的链接。所以现在还是不可用的。如果开启的话，到时候你的cloudreve各种文件不见了，有得你哭😭重装整个站点
> 
> 刚新建了一个存储桶做了个小实验，COS+CDN。手动从存储桶里删除文件（模拟万象审核后删除），在Cloudreve系统里，只是不显示缩略图及无法找到源文件，404错误。但站点不受影响。Cloudreve存储文件的状态信息在数据库里，文件存储位置不影响前端。因此应该是无需重装站点什么的。 ![CleanShot 2022-04-09 在 02 26 03@2x](https://user-images.githubusercontent.com/87530132/162501676-5efdb779-e089-4dc6-b63b-efcaadfd84b3.jpg)

请问你这是怎么弄的

**Comment by act-m** [comment]
@huangdihd 截图测试以及前面提到腾讯万象，都只是举例说明，其实七牛、阿里云OSS、又拍云这些国内云服务商都有自己的内容审核系统。使用方式是在Cloudreve里配置存储策略为云存储，再到对应的云存储里配置内容审核。如果有开发能力，还可以做审核后结果回调，反馈信息等。另外，也不是说被审查的资源就一定会被删除，以腾讯万象为例，是可以配置二次人工审核的策略的。腾讯数据万象有一个审核体验页面，先去试试再看吧：https://cloud.tencent.com/act/pro/ciExhibition?tab=contentReview&sub=pictureReview

各大云服务商的审核服务介绍：
阿里云OSS违规检测： https://help.aliyun.com/document_detail/84448.html
又拍云内容识别： https://docs.upyun.com/cloud/audit/
七牛云内容安全： https://www.qiniu.com/products/censor
腾讯数据万象： https://cloud.tencent.com/document/product/460/47484
AWS监管内容： https://docs.aws.amazon.com/zh_cn/rekognition/latest/dg/moderation.html

其他存储策略（本机、从机、OneDrive）不是对象存储。

**Comment by lsCoding666** [comment]
如果用第三方的对象存储，确实能监测违法内容，但是抛开违法内容不谈，光是存储成本和流量成本就是个惊人的数字。
下图是对象存储的流量定价
![image](https://user-images.githubusercontent.com/73888354/162557208-843c62e4-e974-4073-80dd-d4ed9cae34c9.png)

而流量又分为好多种 文档也很长，不建议细看，直接拿价格计算器试试
https://buy.cloud.tencent.com/price/cos/calculator

如果你真的要开网盘，自动检查非法文件只是其中一个要关注的地方。最关键的还是成本和怎么盈利的问题，如果你是个人或者小团队，还是算了，这玩意烧钱。

我随便说个你要考虑的地方：大量用户注册恶意刷存储空间和容量。假如你一天新增了100个用户，每个用户10g空间，这就是1t空间的存储成本了，然后这些用户还恶意刷流量，天天下载刷流量，你钱就被烧了，你怎么办？

你真的要开网盘吗？你考虑清楚了吗？

**Comment by lsCoding666** [comment]
其实不说恶意刷流量了，就算是用户正常使用的钱，个人和小团队我觉得也烧不起

**Comment by act-m** [comment]
他既然想拿网盘挣钱，就不可能走OneDrive这种薅流量羊毛的路线了。不过我倒是领悟到了部分人为什么总是有非法文件的原因：如果都是拿来用下载某类种子文件里的图片与视频，那肯定遍地都是雷区吧。是不是个人与小团队不重要，主要看拿来做什么吧。
