### ISSUE TITLE
可以把Cloudreve像WP一样装到文件夹里吗？

### ISSUE THREAD

**Issue by xzh767** [cloudreve/Cloudreve#1196]
由于内网穿透的原因，除根域外，为CR额外建立一个域名是需要氪金的
但是新版本的的CR似乎是一个EXE可执行文件，直接占用localhost:8080
能否将CR变成文件的形式装在文件夹中？
即localhost/cloudreve这样
我应该怎么做？

**Comment by xiongzai666** [comment]
@xzh767 钝角

**Comment by topjohncian** [comment]
此版本不可以 
#1129
