### ISSUE TITLE
出现报错 websocket: close 1006 (abnormal closure): unexpected EOF

### ISSUE THREAD

**Issue by baiyuheifeng** [cloudreve/Cloudreve#1197]
cloudreve V3.4.2
突然出现close 1006的报错
（websocket: close 1006 (abnormal closure): unexpected EOF）
打开网站框架可以显示，但文件区域会出现network error
网上有说可能是nginx的反代超时了，但我用的是IIS，而且超时时间设置的是300
请问是怎么回事呢？

**Comment by HFO4** [comment]
是不是你梯子挂了...

**Comment by baiyuheifeng** [comment]
我的cloudreve是挂在腾讯云的服务器上的，一直都没有挂梯子，正常运行了两个月，今天突然就出问题了，应该不是梯子的问题吧

AaronLiu ***@***.***> 于2022年4月9日周六 20:50写道：

**Comment by ASLKRS** [comment]
刚才试着给服务器挂了个梯子，用云服务器上的浏览器可以正常访问cloudreve，但本地的电脑依旧无法访问，显示无法加载站点配置 network error

？这条消息输入到一半，服务器挂梯子也不行了，麻了
