### ISSUE TITLE
建议：希望可以增加直链功能

### ISSUE THREAD

**Issue by mattskjy** [cloudreve/Cloudreve#1199]
现在的外链功能已经可以作为图床使用了。
但是作为图床自己使用的话，如果vps到期后不打算续费。
可能会更换到其它的vps（续费太贵，买其他的vps），这种情况下，就打算把图片文件夹整个拷贝到新的vps下，保持目录结构和之前一样。然后保证域名不变（重新解析到新的vps上），来达到以往链接不失效的效果。
我试了一下，现在的外链达不到这样的效果，希望可以考虑添加获取直链url的功能。
ps：非常感谢写出cloudreve这样好用的程序。

**Comment by qitayun** [comment]
已经出了这个功能了吧
获取外链不就是直连

**Comment by xiongzai666** [comment]
@qitayun 已经有了

**Comment by qitayun** [comment]
> @qitayun 已经有了

@我干啥……

**Comment by mattskjy** [comment]
> 已经出了这个功能了吧 获取外链不就是直连
@qitayun 

现在的”获取外链“的确是可以在markdown等地方直接使用url查看图片。
 我想表达的意思的是github、七牛云等的那种直链（url就是域名+文件路径的形式）。因为考虑到作图床的话，vps到期后可能会更换。如果是github、七牛云那种直链的话，只要保证域名不变，文件搬家后保持目录结构不变的话，以往的markdown文档里引用的url就不会失效了。
现在的这个外链达不到这样的效果。我在两个vps上获取同一个照片的外链，两个外链是不同的，替换彼此的域名就不能访问照片了。
（ps：不是为难作者挑麻烦，感觉的确是有这么个需求。所以提了一下）

**Comment by mattskjy** [comment]
> 已经出了这个功能了吧 获取外链不就是直连

@qitayun

现在的”获取外链“的确是可以在markdown等地方直接使用url查看图片。
我想表达的意思的是github、七牛云等的那种直链（url就是域名+文件路径的形式）。因为考虑到作图床的话，vps到期后可能会更换。如果是github、七牛云那种直链的话，只要保证域名不变，文件搬家后保持目录结构不变的话，以往的markdown文档里引用的url就不会失效了。
现在的这个外链达不到这样的效果。我在两个vps上获取同一个照片的外链，两个外链是不同的，替换彼此的域名就不能访问照片了。
（ps：不是为难作者挑麻烦，感觉的确是有这么个需求。所以提了一下）

**Comment by lsCoding666** [comment]
cloudreve是网盘程序，我觉得用alist等目录程序好一些。

> > 已经出了这个功能了吧 获取外链不就是直连
> 
> @qitayun
> 
> 现在的”获取外链“的确是可以在markdown等地方直接使用url查看图片。 我想表达的意思的是github、七牛云等的那种直链（url就是域名+文件路径的形式）。因为考虑到作图床的话，vps到期后可能会更换。如果是github、七牛云那种直链的话，只要保证域名不变，文件搬家后保持目录结构不变的话，以往的markdown文档里引用的url就不会失效了。 现在的这个外链达不到这样的效果。我在两个vps上获取同一个照片的外链，两个外链是不同的，替换彼此的域名就不能访问照片了。 （ps：不是为难作者挑麻烦，感觉的确是有这么个需求。所以提了一下）

**Comment by mattskjy** [comment]
> cloudreve是网盘程序，我觉得用alist等目录程序好一些。

嗯嗯 的确，本身也不是专门的图床工具。 好的，我去了解一下alist。

**Comment by qitayun** [comment]
好建议
同求


ps：隔壁ifile有这个功能，叫直链分享应该不难做


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cloudreve/Cloudreve"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月10日(星期天) 晚上6:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [cloudreve/Cloudreve] 建议：希望可以增加直链功能 (Issue #1199)





  
已经出了这个功能了吧 获取外链不就是直连
  
@qitayun
 
现在的”获取外链“的确是可以在markdown等地方直接使用url查看图片。
 我想表达的意思的是github、七牛云等的那种直链（url就是域名+文件路径的形式）。因为考虑到作图床的话，vps到期后可能会更换。如果是github、七牛云那种直链的话，只要保证域名不变，文件搬家后保持目录结构不变的话，以往的markdown文档里引用的url就不会失效了。
 现在的这个外链达不到这样的效果。我在两个vps上获取同一个照片的外链，两个外链是不同的，替换彼此的域名就不能访问照片了。
 （ps：不是为难作者挑麻烦，感觉的确是有这么个需求。所以提了一下）
