### ISSUE TITLE
本机存储的mp4视频共享外链在iPhone上不能播放

### ISSUE THREAD

**Issue by haikouwang** [cloudreve/Cloudreve#1202]
开发者您好！
我发现，在 Cloudreve 3.4.2 （存储配置为本机存储的 ）共享 mp4 视频外链，在 iPhone 上打开该外链，mp4 视频不能在线播放。其中 safari 还疑似出现不能下载的问题，夸克浏览器正常。
我已反复确认，相同外链 安卓 和 windows 的在线播放和下载功能均正常。
我找了一个相关的技术文档，但是我不懂修改 cloudreve 的配置，不知道对您是否有帮助 https://www.jianshu.com/p/f69e3417a79e
盼望开发者有空的时候能帮忙处理一下，谢谢！

**Comment by haikouwang** [comment]
我的网站搭建是宝塔用 supervisor 做守护进程，然后 nginx 反代本地 5212 端口

**Comment by wangxiaoerYah** [comment]
你可以放个链接出来我们试试

**Comment by haikouwang** [comment]
> 你可以放个链接出来我们试试

https://cloudreve.hk.lnlcvv.cf/s/AqCv
