### ISSUE TITLE
新版希望融合 ffmpeg 的转码功能

### ISSUE THREAD

**Issue by haikouwang** [cloudreve/Cloudreve#1205]
尊敬的开发者：
您好！

希望您有空的时候可以考虑添加 ffmpeg 转码的功能，因为：
继 https://github.com/cloudreve/Cloudreve/issues/1202 后，我知道了视频只有 iPhone 无法播放是 库克 的问题。
我发现这种只有 iPhone 不能播放的 mp4 文件用 ffmpeg -i 转码后就可以播放了，虽然也是 mp4 转 mp4.
但是我小姐姐太多了，手动转码在上传又太累了，我想让开发者您加上这个功能，这样

1.）可以不浪费 腾讯云 没人用的 vCPU 资源；
2.）我不用重新上传啦；
3.）cloudreve 一定会更出名更受欢迎哒！！！！！！

希望 cloudreve 项目可以越来越装大（等我学会 Go 以后我也来贡献源码）

**Comment by danblaze13** [comment]
@haikouwang Ios用infuse挂载webdave可以客户端转码。filebox也可以。是最优解了。

**Comment by machao1989** [comment]
这个就专注云盘功能就可以了，ffmpeg 转码功能给你推荐个更专业的项目emby

**Comment by Licsber** [comment]
"1.）可以不浪费 腾讯云 没人用的 vCPU 资源；"
了解过转码到底多耗费CPU资源估计你就不会提了
可以用自己的电脑 非默认参数转（默认参数画质糊的没法看）试试

**Comment by vvisionnn** [comment]
Thanks for your recommendation, we have no plan for this type of feature for now.
