### ISSUE TITLE
使用 Postgres 数据库时支持 SSL 连接到数据库（Heroku需求）

### ISSUE THREAD

**Issue by sxjeru** [cloudreve/Cloudreve#1208]
众所周知，Heroku Postgres [强制要求SSL连接](https://devcenter.heroku.com/articles/connecting-heroku-postgres#heroku-postgres-ssl)。目前部署时会出现以下报错：

`panic: 连接数据库不成功, pq: no pg_hba.conf entry for host "xxx", user "xxx", database "xxx", no encryption`

希望能增加相应配置选项，感谢。

`sslmode=require`

**Comment by unauth401** [comment]
@sxjeru ssl选项可以自己在postgres配置文件改的 建议去看配置文档
况且这个错误好像是因为服务端没开ssl cloudreve本身就是用ssl连postgres的

**Comment by sxjeru** [comment]
感谢答复，不过已换用其他类型数据库。

**Comment by sxjeru** [comment]
感谢答复，已换用其他类型数据库。
