### ISSUE TITLE
请问有群晖使用者成功导入文件吗？

### ISSUE THREAD

**Issue by reonsee** [cloudreve/Cloudreve#1211]
四处找都好像没看见有教学，我自己试了很多次都是显示任务完成但没显示文件出来
![image](https://user-images.githubusercontent.com/38994513/163726256-405dc67c-0e87-41e3-aad7-c489ed379aae.png)
![image](https://user-images.githubusercontent.com/38994513/163726280-7f2dc140-7165-4946-b8e7-dd63a1bc6b60.png)
![image](https://user-images.githubusercontent.com/38994513/163726292-c0c8fa4a-0488-402f-a7aa-241808c52136.png)
我填写资料正确吗？

**Comment by vvisionnn** [comment]
For the usage discussion, please post it to the [forum](https://forum.cloudreve.org/), thanks.
