### ISSUE TITLE
Deprecation of deeplink to register applications with Microsoft Identity Platform

### ISSUE THREAD

**Issue by yuazhou** [cloudreve/Cloudreve#1212]
Dear developer, I am Yuan Zhou, a product manager in Azure identity team. We found that your app is using a deeplink to apps.dev.microsoft.com to register applications with the Microsoft Identity Platform. This is not an official API and we want to notify you that we are deprecating this method in 30 days. You can use [official Azure API to create applications](https://docs.microsoft.com/en-us/graph/api/resources/application?view=graph-rest-1.0) instead. Please don't hesitate to reach out to me if you have any questions. Thanks!

**Comment by HFO4** [comment]
I‘ve checked current codebase, no such API is used since v3.0, thanks for inform!
