### ISSUE TITLE
视频无法在Safari中mov视频

### ISSUE THREAD

**Issue by weeeeibin** [cloudreve/Cloudreve#1218]
- Browser: Safari
```
// frontend
// src\config.ts
export const videoPreviewSuffix = ["mp4", "mkv", "webm", "avi", "m3u8","mov"];
```

我大部分时间用的是mac和ios系统，但是mov默认无法在线预览，在videoPreviewSuffix增加mov后Safari加载mov视频时会加载失败但chrome可以播放，请问这样直接修改前端可以达到预览mov视频的目的么

**Comment by HFO4** [comment]
已经添加
