### ISSUE TITLE
releases发布的linux-amd64无法在alpine虚拟机使用

### ISSUE THREAD

**Issue by sundaqiang** [cloudreve/Cloudreve#1219]
从docker拷贝一份出来就可以。能否构建一份在releases以便更新？

**Comment by Ink-33** [comment]
请使用`go build -ldflags '-s -w -extldflags "-static"'`编译

**Comment by sundaqiang** [comment]
> 请使用`go build -ldflags '-s -w -extldflags "-static"'`编译

额，是知道怎么编译的，只是想问下能不能加入releases版本中。没这个计划那就自己编译了

**Comment by tom-temp** [comment]
`apk add gcompat` 安装这个运行库就可以使用了，不需要重新编译

**Comment by sundaqiang** [comment]
> `apk add gcompat` 安装这个运行库就可以使用了，不需要重新编译

非常感谢您的指导，我现在自己做了一个Actions来自动提取docker里面的二进制文件，https://github.com/sundaqiang/openwrt-packages-backup/releases。

docker里面的二进制文件不需要其他运行库

**Comment by chunfengyao** [comment]
> > `apk add gcompat` 安装这个运行库就可以使用了，不需要重新编译
> 
> 非常感谢您的指导，我现在自己做了一个Actions来自动提取docker里面的二进制文件，[https://github.com/sundaqiang/openwrt-packages-backup/releases。](https://github.com/sundaqiang/openwrt-packages-backup/releases%E3%80%82)
> 
> docker里面的二进制文件不需要其他运行库

自己封的Docker： [https://github.com/chunfengyao/cloudreve-docker](https://github.com/chunfengyao/cloudreve-docker)
吭哧吭哧地封了一个docker，今天发现，原来官方也提供了docker，官方的来的太晚了，开始用cloudreve的时候找了半天才找了一个能用的docker（上周停更了）。

官方Docker地址：[https://hub.docker.com/r/cloudreve/cloudreve](https://hub.docker.com/r/cloudreve/cloudreve)
