### ISSUE TITLE
cloudreve下操作onedrive存储删除的问题。

### ISSUE THREAD

**Issue by inpowerchiu** [cloudreve/Cloudreve#1220]
我用的版本是最新的测试版3.5.0-beta2，遇到一个onedrive存储的问题。
我在管理面板新建了一个管理账户，从外部导入文件到这个账户，然后登陆这个账户在cloudreve操作删除文件，到onedrive页面查看并没有同步删除。然后我从本地通过cloudreve页面上传文件到onedrive存储，操作删除后，再到onedrive页面下查看是会同步删除了，反复试了两三遍都这样。

**Comment by HFO4** [comment]
经测试我这边是可以删除的。
能否提供：你所导入的，不能删除的文件在OneDrive里的完整路径？

**Comment by inpowerchiu** [comment]
> 经测试我这边是可以删除的。 能否提供：你所导入的，不能删除的文件在OneDrive里的完整路径？

![_20220421135230.png](https://img.imoutomoe.net/images/2022/04/21/_20220421135230.png)
![_20220421135833.png](https://img.imoutomoe.net/images/2022/04/21/_20220421135833.png)
![_20220421135414.png](https://img.imoutomoe.net/images/2022/04/21/_20220421135414.png)
图1所示，我刚又在cloudreve端测试删除该文件，返回onedrive页面刷新几次依旧存在，路径应该是“/cloudreve/电脑软件/装机软件/”吧？不知道什么原因不会同步删掉。
图3是我在cloudreve面板设置的参数，不知道有没有弄错。

**Comment by HFO4** [comment]
我这边测试了一摸一样的目录结构，是可以正常删除的

**Comment by inpowerchiu** [comment]
> 我这边测试了一摸一样的目录结构，是可以正常删除的

我也搞不懂为何会这样，请教一下，我原来有一个默认的admin管理员用户，也是用的这个onedrive存储，而后我是在新创建的管理员用户下操作的导入外部文件的，在这之前原有admin管理员用户下也操作过导入外部文件（但因为路径有点乱的原因才考虑创建第二个管理员账户），第二个管理员账户操作删除不同步的情况会不会是两个用户拥有相同文件导致的呢？

另外，想问一下，如果在程序不出现我现在这个问题的情况下，删除用户会导致该用户下的文件在真实存储盘内被同步删除吗？

**Comment by GreenTeodoro839** [comment]
@inpowerchiu 会同步删除，而且另一个用户的文件会永远占用空间，除非通过数据库删除文件。需要相同文件在多个用户里可以用pro版分享链接转存

**Comment by inpowerchiu** [comment]
> @inpowerchiu 会同步删除，而且另一个用户的文件会永远占用空间，除非通过数据库删除文件。需要相同文件在多个用户里可以用pro版分享链接转存

并不需要多用户使用同一个文件，主要还是自己用，我的最初目的是想着把整个onedrive导入到cloudreve下（最初使用cloudreve时只是在把cloudreve路径定在onedrive下的/cloudreve处，后续使用过程中发现cloudreve的文件搜索功能比onedrive自带的好用太多了，于是想把整个onedrive盘导入到cloudreve内），请问有办法把现有cloudreve上现有的onedrive存储的文件清空再重新把我整个onedrive文件导入到cloudreve下吗？

**Comment by HaoShen2021** [comment]
直接把数据库删了，重新配置；或者把onedrive储存策略乱改一下，让cloudreve无法上传，删除，在后台删完了再改回来；再或者直接删除，把od回收站内容恢复

**Comment by inpowerchiu** [comment]
> 直接把数据库删了，重新配置；或者把onedrive储存策略乱改一下，让cloudreve无法上传，删除，在后台删完了再改回来；再或者直接删除，把od回收站内容恢复

管理面板处admin@cloudreve.org这个用户没法删除，囧啊，回头研究一下数据库吧，囧。

**Comment by HaoShen2021** [comment]
我指的是控制面板把用户文件删除


| |
皓神官方
|
|
***@***.***
|
在2022年4月22日 ***@***.***> 写道：

直接把数据库删了，重新配置；或者把onedrive储存策略乱改一下，让cloudreve无法上传，删除，在后台删完了再改回来；再或者直接删除，把od回收站内容恢复

***@***.***这个用户没法删除，囧啊，回头研究一下数据库吧，囧。

**Comment by inpowerchiu** [comment]
> 我指的是控制面板把用户文件删除 | | 皓神官方 | | ***@***.*** | 在2022年4月22日 ***@***.***> 写道： 直接把数据库删了，重新配置；或者把onedrive储存策略乱改一下，让cloudreve无法上传，删除，在后台删完了再改回来；再或者直接删除，把od回收站内容恢复 ***@***.***这个用户没法删除，囧啊，回头研究一下数据库吧，囧。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

你说的这个的确可以，可是面板管理页面，最大每页显示100文件，将近上万个文件，得翻一百页，找不到一次过全选的方法头都大了

**Comment by GreenTeodoro839** [comment]
@HaoShen2021 不行，会提示删除失败

**Comment by AnotiaWang** [comment]
我也遇到了类似的问题，不过和你的有点不一样：删除文件时，如果目录中有文件夹，其中的文件会被正常删除，但是空文件夹会留在 OneDrive 的目录中
