### ISSUE TITLE
功能建议：管理员上传的文件可共享给其他用户访问

### ISSUE THREAD

**Issue by Kyle91** [cloudreve/Cloudreve#1221]
希望管理员上传的文件，可以共享给其他用户直接访问，不需要再手动分享链接

**Comment by seeleclover** [comment]
我也认为这个功能很有必要，希望能做出这种团队盘的功能。

**Comment by Kyle91** [comment]
因为之前用过可道云Kodexplorer的共享文件，感觉这种团队共享文件的功能挺好用的

**Comment by Cinnamoroll-Rabbit** [comment]
我认为管理员和管理员认证的共享者可以添加文件到共享盘内，别人打开共享盘的域名(和CR是两个域名，但是反代的一个程序)可以直接下载，不需要手动添加分享链接。而其它人也可以组建自己的组织，在自己的组织内可以进行共享。
