### ISSUE TITLE
【功能建议】建议增加存储策略之间冗余备份功能

### ISSUE THREAD

**Issue by simon-ding** [cloudreve/Cloudreve#1229]
很多人建站使用的淘宝买来的onedrive账号，存在被封禁的风险。希望能够增加在多个存储策略之间冗余备份。这样当一个策略不能用时，无缝却换到另外一个策略。

1. 文件同事同步多个策略 
2. 获取文件时自动从可用的策略获取
3. 提示用户某个策略不可用
4. 加入新备份策略时，自动同步已有数据到上面

**Comment by marvinli001** [comment]
真要用网盘要不你考虑下更安全稳定的方法，比如正价买个onedrive，从淘宝买的号纯粹就是瞎玩玩，因为都知道不稳定

**Comment by otakisa** [comment]
你这个不是功能建议，而是滥用，还有你这个“很多人”是从哪里调查来的？还是说你自己就代表了“很多人”

**Comment by simon-ding** [comment]
既然有这种东西，为什么不能用呢？还是说这么用就犯罪了。“很多人”这个不用我来调查吧，网上随便搜一下教程就有人来推荐的

**Comment by simon-ding** [comment]
> 真要用网盘要不你考虑下更安全稳定的方法，比如正价买个onedrive，从淘宝买的号纯粹就是瞎玩玩，因为都知道不稳定

基于不稳定存储，来构建稳定存储也是挺NB的啊，类似于Hadoop就是基于每台机器存储都可能丢失，做了多次备份。不管用买来的onedrive是否道义的问题，备份存储对于高可靠性场景总是需要的。

谁能知道那个运营商的数据存储一定可靠，多个备份手段总是好的

**Comment by Oldming1** [comment]
> 既然有这种东西，为什么不能用呢？还是说这么用就犯罪了。“很多人”这个不用我来调查吧，网上随便搜一下教程就有人来推荐的



> 既然有这种东西，为什么不能用呢？还是说这么用就犯罪了。“很多人”这个不用我来调查吧，网上随便搜一下教程就有人来推荐的

没必要
1.真的需要冗余那是物理层面的事情，没有网盘听说有冗余。
2.真的要备份onedrive官方有工具mover.io你可以定期自动运行备份。
3.真的搞冗余数据需要经过服务器下载上传，如何保证上传下载不出错。
要是真的实现那是和nas有什么区别了

**Comment by vvisionnn** [comment]
Thanks for your recommendation, we have no plan for this type of feature for now.
