### ISSUE TITLE
【提案】release添加deb，rpm等打包

### ISSUE THREAD

**Issue by Ink-33** [cloudreve/Cloudreve#1230]
使用包管理器对Cloudreve进行管理，不论是升级还是移除都较为便利。
且可以内置用于`systemctl`的守护配置，便于运行维护

现有的发版工具如`goreleaser`可以经过简单配置，结合`actions`即可实现此目标
至于`deb`，`rpm`的`gpg`签名，如果不做软件源的话不搞也行

欢迎讨论

**Comment by topjohncian** [comment]
有一个 #1039 的问题

**Comment by Ink-33** [comment]
> 有一个 #1039 的问题
> 

看了一下，确实需要解决
配置文件可以用一个如`-config`的启动参数解决。
数据目录确实是需要配置，特别是引入包管理器之后，按理来说应当遵守`FHS`
