### ISSUE TITLE
PRO版的注册用户和管理里添加用户会导致数据库操作卡死

### ISSUE THREAD

**Issue by Melody** [cloudreve/Cloudreve#1234]
试了社区版和PRO版，同一个数据库在windows和liunx只有pro版卡死

日记：

[35m(/home/aaron/Backend-V3/service/admin/group.go:96)[0m 
[33m[2022-04-24 14:48:53][0m  [36;1m[0.07ms][0m  SELECT count(id) FROM "users"  WHERE "users"."deleted_at" IS NULL AND ((group_id = 3))  
[36;31m[0 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/service/admin/group.go:96)[0m 
[33m[2022-04-24 14:48:53][0m  [36;1m[0.08ms][0m  SELECT count(id) FROM "users"  WHERE "users"."deleted_at" IS NULL AND ((group_id = 2))  
[36;31m[0 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/service/admin/group.go:96)[0m 
[33m[2022-04-24 14:48:53][0m  [36;1m[0.07ms][0m  SELECT count(id) FROM "users"  WHERE "users"."deleted_at" IS NULL AND ((group_id = 1))  
[36;31m[0 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/models/policy.go:91)[0m 
[33m[2022-04-24 14:48:53][0m  [36;1m[0.18ms][0m  SELECT * FROM "policies"  WHERE "policies"."deleted_at" IS NULL AND (("policies"."id" = 2)) ORDER BY "policies"."id" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/models/policy.go:91)[0m 
[33m[2022-04-24 14:48:53][0m  [36;1m[0.39ms][0m  SELECT * FROM "policies"  WHERE "policies"."deleted_at" IS NULL AND (("policies"."id" = 4)) ORDER BY "policies"."id" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 
[GIN] 2022/04/24 - 14:48:53 | 200 |      3.0148ms |  58.248.217.228 | POST     "/api/v3/admin/group/list"

[35m(/home/aaron/Backend-V3/models/user.go:203)[0m 
[33m[2022-04-24 14:48:54][0m  [36;1m[0.38ms][0m  SELECT * FROM "users"  WHERE "users"."deleted_at" IS NULL AND ((status = 0) AND ("users"."id" = 1)) ORDER BY "users"."id" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/models/user.go:203)[0m 
[33m[2022-04-24 14:48:54][0m  [36;1m[0.20ms][0m  SELECT * FROM "groups"  WHERE "groups"."deleted_at" IS NULL AND (("id" IN (1))) ORDER BY "groups"."id" ASC  
[36;31m[1 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/service/admin/list.go:20)[0m 
[33m[2022-04-24 14:48:54][0m  [36;1m[0.23ms][0m  SELECT * FROM "groups"  WHERE "groups"."deleted_at" IS NULL  
[36;31m[5 rows affected or returned ][0m 
[GIN] 2022/04/24 - 14:48:54 | 200 |    1.249217ms |  58.248.217.228 | GET      "/api/v3/admin/groups"

[35m(/home/aaron/Backend-V3/models/user.go:203)[0m 
[33m[2022-04-24 14:48:54][0m  [36;1m[0.25ms][0m  SELECT * FROM "users"  WHERE "users"."deleted_at" IS NULL AND ((status = 0) AND ("users"."id" = 1)) ORDER BY "users"."id" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/models/user.go:203)[0m 
[33m[2022-04-24 14:48:54][0m  [36;1m[0.20ms][0m  SELECT * FROM "groups"  WHERE "groups"."deleted_at" IS NULL AND (("id" IN (1))) ORDER BY "groups"."id" ASC  
[36;31m[1 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/service/admin/user.go:161)[0m 
[33m[2022-04-24 14:48:54][0m  [36;1m[0.09ms][0m  SELECT count(*) FROM "users"  WHERE "users"."deleted_at" IS NULL  
[36;31m[0 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/service/admin/user.go:164)[0m 
[33m[2022-04-24 14:48:54][0m  [36;1m[0.32ms][0m  SELECT * FROM "users"  WHERE "users"."deleted_at" IS NULL ORDER BY id desc LIMIT 10 OFFSET 0  
[36;31m[3 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/service/admin/user.go:164)[0m 
[33m[2022-04-24 14:48:54][0m  [36;1m[0.32ms][0m  SELECT * FROM "groups"  WHERE "groups"."deleted_at" IS NULL AND (("id" IN (1,4)))  
[36;31m[2 rows affected or returned ][0m 
[GIN] 2022/04/24 - 14:48:54 | 200 |    2.194857ms |  58.248.217.228 | POST     "/api/v3/admin/user/list"

[35m(/home/aaron/Backend-V3/models/user.go:203)[0m 
[33m[2022-04-24 14:48:55][0m  [36;1m[0.41ms][0m  SELECT * FROM "users"  WHERE "users"."deleted_at" IS NULL AND ((status = 0) AND ("users"."id" = 1)) ORDER BY "users"."id" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/models/user.go:203)[0m 
[33m[2022-04-24 14:48:55][0m  [36;1m[0.22ms][0m  SELECT * FROM "groups"  WHERE "groups"."deleted_at" IS NULL AND (("id" IN (1))) ORDER BY "groups"."id" ASC  
[36;31m[1 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/service/admin/list.go:20)[0m 
[33m[2022-04-24 14:48:55][0m  [36;1m[0.27ms][0m  SELECT * FROM "groups"  WHERE "groups"."deleted_at" IS NULL  
[36;31m[5 rows affected or returned ][0m 
[GIN] 2022/04/24 - 14:48:55 | 200 |    1.663169ms |  58.248.217.228 | GET      "/api/v3/admin/groups"

[35m(/home/aaron/Backend-V3/models/user.go:203)[0m 
[33m[2022-04-24 14:49:05][0m  [36;1m[0.80ms][0m  SELECT * FROM "users"  WHERE "users"."deleted_at" IS NULL AND ((status = 0) AND ("users"."id" = 1)) ORDER BY "users"."id" ASC LIMIT 1  
[36;31m[1 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/models/user.go:203)[0m 
[33m[2022-04-24 14:49:05][0m  [36;1m[0.22ms][0m  SELECT * FROM "groups"  WHERE "groups"."deleted_at" IS NULL AND (("id" IN (1))) ORDER BY "groups"."id" ASC  
[36;31m[1 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/service/admin/user.go:129)[0m 
[33m[2022-04-24 14:49:05][0m  [36;1m[0.31ms][0m  INSERT  INTO "users" ("created_at","updated_at","deleted_at","email","nick","password","status","group_id","storage","open_id","two_factor","avatar","options","authn","score","previous_group_id","group_expires","notify_date","phone") VALUES ('2022-04-24 14:49:05','2022-04-24 14:49:05',NULL,'DB@moe-y.com','DB','BMRHmXCN6lmDTprp:a295ebca19c2c69cef59f8cc560ccb1d4ac220d3',0,2,0,'','','','{}','',0,0,NULL,NULL,'')  
[36;31m[1 rows affected or returned ][0m 

[35m(/home/aaron/Backend-V3/models/user.go:249)[0m 
[33m[2022-04-24 14:49:05][0m  [36;1m[0.17ms][0m  INSERT  INTO "folders" ("created_at","updated_at","deleted_at","name","parent_id","owner_id","policy_id") VALUES ('2022-04-24 14:49:05','2022-04-24 14:49:05',NULL,'/',NULL,6,0)  
[36;31m[1 rows affected or returned ][0m 
[GIN] 2022/04/24 - 14:49:47 | 200 |      32.895µs |  58.248.217.228 | GET      "/api/v3/file/thumb/xaYcg"
[GIN] 2022/04/24 - 14:49:53 | 200 |      34.005µs |  58.248.217.228 | GET      "/api/v3/file/thumb/xaYcg"
[GIN] 2022/04/24 - 14:50:10 | 200 |     416.564µs |  58.248.217.228 | GET      "/admin/user/add"
[GIN] 2022/04/24 - 14:50:10 | 200 |     316.258µs |  58.248.217.228 | GET      "/static/css/6.bca9ac5e.chunk.css"
[GIN] 2022/04/24 - 14:50:10 | 200 |   39.241197ms |  58.248.217.228 | GET      "/static/js/6.333486e2.chunk.js"
[GIN] 2022/04/24 - 14:50:10 | 200 |   13.222725ms |  58.248.217.228 | GET      "/static/js/main.a85a2277.chunk.js"
[GIN] 2022/04/24 - 14:50:10 | 200 |     326.464µs |  58.248.217.228 | GET      "/static/css/6.bca9ac5e.chunk.css.map"
[GIN] 2022/04/24 - 14:50:11 | 200 |   106.64382ms |  58.248.217.228 | GET      "/static/js/main.a85a2277.chunk.js.map"
[GIN] 2022/04/24 - 14:50:11 | 200 |    41.84828ms |  58.248.217.228 | GET      "/static/js/7.e6fef6a9.chunk.js"
[GIN] 2022/04/24 - 14:50:11 | 200 |    8.538715ms |  58.248.217.228 | GET      "/static/js/10.b91cfce7.chunk.js"
[GIN] 2022/04/24 - 14:50:11 | 200 |   303.88881ms |  58.248.217.228 | GET      "/static/js/6.333486e2.chunk.js.map"
[GIN] 2022/04/24 - 14:50:11 | 200 |    27.70384ms |  58.248.217.228 | GET      "/static/js/10.b91cfce7.chunk.js.map"
[GIN] 2022/04/24 - 14:50:11 | 200 |    1.159864ms |  58.248.217.228 | GET      "/static/img/favicon.ico"
[GIN] 2022/04/24 - 14:50:11 | 200 |  147.644617ms |  58.248.217.228 | GET      "/static/js/7.e6fef6a9.chunk.js.map"
[GIN] 2022/04/24 - 14:50:14 | 200 |     427.676µs |  58.248.217.228 | GET      "/home"
[GIN] 2022/04/24 - 14:50:14 | 200 |     299.387µs |  58.248.217.228 | GET      "/static/css/6.bca9ac5e.chunk.css"
[GIN] 2022/04/24 - 14:50:14 | 200 |     350.646µs |  58.248.217.228 | GET      "/static/css/6.bca9ac5e.chunk.css.map"
[GIN] 2022/04/24 - 14:50:14 | 200 |   15.246804ms |  58.248.217.228 | GET      "/static/js/main.a85a2277.chunk.js"
[GIN] 2022/04/24 - 14:50:14 | 200 |   142.89299ms |  58.248.217.228 | GET      "/static/js/6.333486e2.chunk.js"
[GIN] 2022/04/24 - 14:50:14 | 200 |  107.048231ms |  58.248.217.228 | GET      "/static/js/main.a85a2277.chunk.js.map"
[GIN] 2022/04/24 - 14:50:14 | 200 |  329.828387ms |  58.248.217.228 | GET      "/static/js/6.333486e2.chunk.js.map"
[GIN] 2022/04/24 - 14:50:14 | 200 |     488.866µs |  58.248.217.228 | GET      "/static/js/11.6b13b722.chunk.js"
[GIN] 2022/04/24 - 14:50:15 | 200 |      27.701µs |  58.248.217.228 | GET      "/api/v3/bg"
[GIN] 2022/04/24 - 14:50:15 | 200 |     1.07609ms |  58.248.217.228 | GET      "/static/js/11.6b13b722.chunk.js.map"

**Comment by HFO4** [comment]
已在 3.5.1 修复
