### ISSUE TITLE
分享页无法预览文件

### ISSUE THREAD

**Issue by baiguke** [cloudreve/Cloudreve#1236]
升级到3.5.1版本后 分享页无法预览文件

**Comment by HFO4** [comment]
文件分享还是目录分享？具体是哪种文件类型？具体是如何不能预览的？报错/没反应？

**Comment by baiguke** [comment]
> 文件分享还是目录分享？具体是哪种文件类型？具体是如何不能预览的？报错/没反应？

文件分享，预览文档和视频文件没反应 没有报错

**Comment by 4thrun** [comment]
同此问题，页面不报错

**Comment by wangwuxuan2011** [comment]
同此问题，可参考分享链接https://drive.im-a.top/s/76i4，版本Cloudreve 3.5.1，CentOS7.9

**Comment by HFO4** [comment]
acked, 会在3.5.2中修复

**Comment by HFO4** [comment]
fixed in https://github.com/cloudreve/frontend/commit/3131a0d557a21a51a454cdd42a6e5df6c3d33389
