### ISSUE TITLE
上传出现的问题

### ISSUE THREAD

**Issue by sunosv** [cloudreve/Cloudreve#1237]
win服务器平台

上传很多小文件的时候  会出现**“无法创建上传会话”:failed to create folder: Error1062**
可是那不是目录folder 是文件呀  然后再点重新上传 才能成功。
本来想着清空已完成的 剩下不成功的再一一点上传，可是点清空已完成的 那个没有成功的也被清空了列表

**Comment by HFO4** [comment]
fixed in https://github.com/cloudreve/Cloudreve/commit/853bd4c280cd8018d78ef424a060b3e73d5072f0
