### ISSUE TITLE
复制文件后，未能正确生成副本

### ISSUE THREAD

**Issue by ericarena** [cloudreve/Cloudreve#1238]
错误描述：
在local存储策略下，关闭自动命名，拷贝文件到folder目录，分别编辑folder目录下A文件，在folder目录没有生成文件副本，两个文件在数据库中指向同一物理文件，在folder目录下编辑保存，造成原文件内容被覆盖。

复现步骤：
1. 在根目录下新建文本文件A.txt，输入信息保存。
2. 在根目录下新建文件夹folder，复制A.txt到folder下。
3. 编辑folder下A.txt，输入信息保存。
4. 根目录下A.txt，被folder下A.txt 覆盖。物理磁盘下仅一份A.txt。

版本：3.5.1
平台： windows 10
数据库：sqite3

**Comment by HFO4** [comment]
本质上还是因为没开启重命名，导致物理文件冲突。3.5.2 后会修复此问题，如果物理文件重名则直接抛出错误。

**Comment by HFO4** [comment]
fixed in https://github.com/cloudreve/Cloudreve/commit/d845824bd8998dd4c7e3327e06f3573c916320ff
