### ISSUE TITLE
【离线下载】离线多个相同文件直接报错

### ISSUE THREAD

**Issue by qitayun** [cloudreve/Cloudreve#1241]
如果别的用户也离线的这个文件
相同的永久就无法离线

磁力反正是这样

如果要复现，就离线同一个磁力两次即可
![image](https://user-images.githubusercontent.com/79431985/165105018-ef5e55ac-316c-4965-beab-e466b1ec5e69.png)

**Comment by HFO4** [comment]
known issue, BT 协议本身的限制。

**Comment by qitayun** [comment]
> known issue, BT 协议本身的限制。

离线下载限制能做吗，快疯了
