### ISSUE TITLE
Fatal Bug: {uuid}不生效

### ISSUE THREAD

**Issue by Licsber** [cloudreve/Cloudreve#1243]
**Describe the bug**
严重错误。。 配置{uuid}仍会以原始字符串显示
复现过程略 在路径和文件重命名两个地方均测试无法生效
最新3.5.1 Pro版

**Comment by Licsber** [comment]
路径中因为没有写uuid的替换策略 不生效我能理解
https://github.com/cloudreve/Cloudreve/blob/c6130ab078fc7f5a669ac46b777a943e90a9aa42/models/policy.go#L144

但是文件名的{ext}和{uuid}实测也不生效就是让人费解了

**Comment by Licsber** [comment]
破案了 下载了最新（2022-04-24 16:10:42）的pro版源码
发现和社区版的modules/policy.go文件不一致
应该是作者两边维护忘改了 此issue只影响pro版
求重新打包发布pro版 顺带修复社区版路径不能用{uuid}的bug

**Comment by HFO4** [comment]
会在 3.5.2 中修复。
