### ISSUE TITLE
控制面板 - 离线下载节点-编辑本机界面打不开，提示错误

### ISSUE THREAD

**Issue by HaoShen2021** [cloudreve/Cloudreve#1245]
如题，提示Cannot read properties of undefined (reading 'toString')

<img width="939" alt="image" src="https://user-images.githubusercontent.com/90556839/165309162-acc743e3-378d-4372-8bc2-b60744852753.png">
 有人知道怎么解决吗？感谢！

**Comment by HaoShen2021** [comment]
有一定概率复现 可手动操作数据库解决

**Comment by GJPFWJ** [comment]
> 有一定概率复现 可手动操作数据库解决

怎么操作？我也遇到了
