### ISSUE TITLE
epub preview feature request

### ISSUE THREAD

**Issue by qndydyhm** [cloudreve/Cloudreve#1250]
**Is your feature request related to a problem? Please describe.**
can not exit the preview mode, the only way is go back to the root directory

**Describe the solution you'd like**
press esc or add a back button to go back to present working directory

**Describe alternatives you've considered**
Make the preview smaller that can exit by clicking the space around the preview

**Additional context**
N/A

**Comment by xb2016** [comment]
Use your web browser's back button (Alt + ←)
