### ISSUE TITLE
mysql连接支持ssl/tls

### ISSUE THREAD

**Issue by lsCoding666** [cloudreve/Cloudreve#1253]
希望增加mysql配置支持ssl/tls的功能，在conf.ini中添加一些字段。

```
mysql -h e51qu8igdpnf.ap-northeast-2.psdb.cloud -u 1v52wqgzm4t8 -p************ --ssl-mode=VERIFY_IDENTITY --ssl-ca=/etc/ssl/certs/ca-certificates.crt
```
```
DSN=1v52wqgzm4t8:************@tcp(e51qu8igdpnf.ap-northeast-2.psdb.cloud)/cloudreve?tls=true
```
上面两行意思相同，都是连接同一个数据库的命令

就是支持开启ssl连接

https://github.com/cloudreve/Cloudreve/blob/4a4375a796183d3cbd85daf7cfb2d36230892757/models/init.go#L45-L52

**Comment by lsCoding666** [comment]
https://github.com/cloudreve/Cloudreve/pull/1255

**Comment by cxplay** [comment]
同样的问题, 希望对 PostgreSQL 和 Redis 添加 SSL/TLS 连接支持.
