### ISSUE TITLE
failed to upload chunk

### ISSUE THREAD

**Issue by feishi12121** [cloudreve/Cloudreve#1254]
![image](https://user-images.githubusercontent.com/31927191/165730465-c6925465-b9a8-493c-b70c-e55abfb10e07.png)
![image](https://user-images.githubusercontent.com/31927191/165730520-18281d03-d020-4ed6-b896-edcb0111cdce.png)
按照文档中提供的覆盖从机配置项配置上传参数，离线上传出现上述问题，是因为中转分片上传失败次数超过配置规定次数上限还是其他问题？

**Comment by HFO4** [comment]
超出重试次数，应该是网络问题，具体要看下从机debug日志。

feishi ***@***.***>于2022年4月28日 周四18:14写道：

**Comment by lsCoding666** [comment]
是世纪互联吗 最近世纪互联上传很容易失败 基本上没成功过，只有小文件比如几百kb的小文件才能离线下载上传。
文件转存失败：Put "https://aowu.sharepoint.cn/sites/BAcb/_api/v2.0/drive/items/01VPM4KPOH3VGPIZHA2BH22NG6BBEXMGPZ/uploadSession?guid='674e8ee6-1154-46c0-b4b6-247bcf130775'&overwrite=False&rename=False&dc=0&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvYW93dS5zaGFyZXBvaW50LmNuQDE3MGE2Y2M3LWJkZTctNGJjNy04N2IwLWMxZjFkZDA0NDg4ZCIsImlzcyI6IjAwMDAwMDAzLTAwMDAtMGZmMS1jZTAwLTAwMDAwMDAwMDAwMCIsIm5iZiI6IjE2NTEwNjI3OTYiLCJleHAiOiIxNjUxMTQ5MTk2IiwiZW5kcG9pbnR1cmwiOiJWbHFXZjBla2tVM1VUSWl3QmdXTHNnTWt6SnhLc2NKcFVyajVUSGpGb1JBPSIsImVuZHBvaW50dXJsTGVuZ3RoIjoiMTg2IiwiaXNsb29wYmFjayI6IlRydWUiLCJjaWQiOiJOR1prWkdGa016TXRNak5pWkMwME1qWmxMV0psWW1ZdFkyWXlaR001WVdZMk9XRXciLCJ2ZXIiOiJoYXNoZWRwcm9vZnRva2VuIiwic2l0ZWlkIjoiWXpneE16Z3paV1F0T0RreU9DMDBOekZoTFdGaFpqRXRPVEJtTXpVME5HRmtOamc1IiwiYXBwX2Rpc3BsYXluYW1lIjoiYmI0ZV_lj6rmnInmiJHkuIDkuKrkurrnlKjnmoRjbG91ZHJldmUiLCJhcHBpZCI6ImQwMzM0YWQyLWFmN2EtNDdiZi05NzBmLWQ1MWM3OWNmNjg4NCIsInRpZCI6IjE3MGE2Y2M3LWJkZTctNGJjNy04N2IwLWMxZjFkZDA0NDg4ZCIsInVwbiI6ImJiNGVAcGFvbHUuc2l0ZSIsInB1aWQiOiIxMDAzMzIzMEM2NTU5NzJFIiwiY2FjaGVrZXkiOiIwaC5mfG1lbWJlcnNoaXB8MTAwMzMyMzBjNjU1OTcyZUBsaXZlLmNvbSIsInNjcCI6Im15ZmlsZXMucmVhZCBhbGxmaWxlcy5yZWFkIG15ZmlsZXMud3JpdGUgYWxsZmlsZXMud3JpdGUgYWxsc2l0ZXMucmVhZCIsInR0IjoiMiIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGwsImlwYWRkciI6IjUyLjEzMC4xMC4xNjEifQ.UTJ0V283Z1VGRXlZSWUybXdJSytoQm9MWk5UQklycDI5ZGJLT0V1bmNrbz0": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by GreenTeodoro839** [comment]
经过测试发现，onedrive存储策略，分片256M一定失败，分片128M就成功
