### ISSUE TITLE
在小图标文件模式下，文件排版异常

### ISSUE THREAD

**Issue by 7lsu** [cloudreve/Cloudreve#126]
请看图片外链：http://wx3.sinaimg.cn/mw690/0060lm7Tly1fzdem85khqj318a0citbq.jpg

**Comment by HFO4** [comment]
是OneDrive的存储策略吗?

**Comment by 7lsu** [comment]
是的 知道问题了吗

**Comment by HFO4** [comment]
原因是OneDrive的缩略图API没法严格限制尺寸，后面会从css样式上优化
