### ISSUE TITLE
docker版使用unix监听后无法重启容器

### ISSUE THREAD

**Issue by 97xiami** [cloudreve/Cloudreve#1262]
重启容器报错unix文件已存在

**Comment by vvisionnn** [comment]
Please follow the issue template, attach the step to reproduce or the log file behind, Thanks.

**Comment by GreenTeodoro839** [comment]
@97xiami docker不要使用unix监听，容器无法操作宿主机相关目录

**Comment by 97xiami** [comment]
> @97xiami docker不要使用unix监听，容器无法操作宿主机相关目录

好吧，nginx能用unix监听
