### ISSUE TITLE
存储策略添加rclone 挂载的gd盘后，无反应，文件无法导入？

### ISSUE THREAD

**Issue by sky8801** [cloudreve/Cloudreve#1263]
请教一个问题，甲骨文arm gd共享盘挂载后，在存储策略添加/root/gd（gd 盘），应用到管理员组，理论添加文件是这样吗？
宝塔可以正看查阅文件，但是Cloudreve，添加存储策略后无反应

**Comment by Cinnamoroll-Rabbit** [comment]
这应该是一个webdav的bug。
