### ISSUE TITLE
希望出个可以修改分享出去url的功能

### ISSUE THREAD

**Issue by haikouwang** [cloudreve/Cloudreve#1264]
数据库是sqlite的不是mysql我也不懂用phpmyadmin修改数据库里面共享出去的外链。
我想修改共享出去的外链地址。。。。

**Comment by topjohncian** [comment]
暂无计划
分享链接并没有存在数据库中，是由分享ID通过固定算法计算出来的

**Comment by Cinnamoroll-Rabbit** [comment]
修改分享链接这种功能很麻烦，而且如果开启修改，别人打开分享链接也会打不开。但是可以在分享的时候自定义分享链接，查询重复的，这样倒是可以应该。

**Comment by haikouwang** [comment]
我觉得还是要做，这个功能有用。

**Comment by haikouwang** [comment]
> 暂无计划 分享链接并没有存在数据库中，是由分享ID通过固定算法计算出来的

我就说我用 sqllite developer 看了数据库没找到分享链接的。。。share 文件夹只能看到分享链接的密码

**Comment by haikouwang** [comment]
> 

也行。
