### ISSUE TITLE
After upgrading to 3.5, there is an error when logging in with "Cannot read properties of undefined (reading 'saveType')"

### ISSUE THREAD

**Issue by lemontea66** [cloudreve/Cloudreve#1265]
**Describe the bug**

**To Reproduce**
1. Go to login
2. Click on login
3. See error on top right

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows11
 - Browser chrome
 - Version 3.5.5

**Additional context**
Cannot read properties of undefined (reading 'saveType')

**Comment by AnotiaWang** [comment]
As the [release note of v3.5.0](https://github.com/cloudreve/Cloudreve/releases/tag/3.5.0) said, after upgrading you need to force refresh the page once on all of your devices which was using an older version of Cloudreve. You can do that by pressing <button>Ctrl</button> + <button>F5</button> or <button>Ctrl</button> + <button>Shift</button> + <button>R</button>.

**Comment by topjohncian** [comment]
Unregister service worker in Chrome DevTools Application panel.
