### ISSUE TITLE
{$src} - 文件 URL 未包含文件扩展名

### ISSUE THREAD

**Issue by 2broear-xty** [cloudreve/Cloudreve#1266]
后台管理中的文档预览接口{src}参数不存在文件名，如何获取该sign的文件及扩展名呢？用于 cos 的文档预览及 onlyoffice 接口。

**Comment by 2broear-xty** [comment]
目前是直接访问返回的是文件下载链接

**Comment by HFO4** [comment]
下个版本会增加单独的扩展名变量。

**Comment by Cinnamoroll-Rabbit** [comment]
> 下个版本会增加单独的扩展名变量。

这确实是个好方法

**Comment by wang-song** [comment]
怎么还没添加单独的扩展名变量啊
