### ISSUE TITLE
上传完成后 上传会话未正确结束

### ISSUE THREAD

**Issue by ghost** [cloudreve/Cloudreve#1267]
<img width="384" alt="image" src="https://user-images.githubusercontent.com/104818082/166410754-67763f40-623e-4b22-ba58-658c256240b7.png">
像这些 已经上传100%了 ，上传完毕了，但是还是显示未完成

**Comment by Cinnamoroll-Rabbit** [comment]
这应该是最后校验之类的，稍微等等试试

**Comment by GitMouse2022** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        不行刷新页面还是这样
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年5月7日 ***@***.***> 写道： 




这应该是最后校验之类的，稍微等等试试

**Comment by Cinnamoroll-Rabbit** [comment]
> font{ line-height: 1.6; } ul,ol{ padding-left: 20px; list-style-position: inside; } 不行刷新页面还是这样 ***@***.*** 在2022年5月7日 ***@***.***> 写道： 这应该是最后校验之类的，稍微等等试试 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

哦，那应该就是一个bug了，让开发者修复下
