### ISSUE TITLE
文件扩展名大小写问题

### ISSUE THREAD

**Issue by nillin** [cloudreve/Cloudreve#1268]
文件扩展名大小写问题

![图片](https://user-images.githubusercontent.com/106225/166414627-e66707bd-0e15-4ac0-93fc-348cf1207d12.png)

**Comment by Cinnamoroll-Rabbit** [comment]
软件应该不区分扩展名大小写。

**Comment by dream10201** [comment]
最新版大写JPG不是图片，小写jpg才能识别为图片...

**Comment by MoeCinnamo** [comment]
> 最新版大写JPG不是图片，小写jpg才能识别为图片...

是的，不应该区分大小写！
