### ISSUE TITLE
可利用复制操作无视空间限制达到占用网盘空间消耗资源的目的的bug

### ISSUE THREAD

**Issue by DuckBurnIncense** [cloudreve/Cloudreve#1269]
**Describe the bug**
A clear and concise description of what the bug is:
利用网盘内复制操作, 可无视空间限制, 无限复制粘贴, 达到占用网盘空间, 消耗资源的目的

**To Reproduce**
1. Go to '根目录';
2. 上传一个在限制大小内的文件 (以压缩包炸弹为例);
3. 若有解压按钮则解压, 若无, 也无伤大雅;
4. 根目录下新建一个文件夹"0"
5. 复制解压后的文件 (下称FF) 到新创建的文件夹"0"内;
6. 在文件夹"0"内将"FF"重命名为"FF1";
7. 将"FF1"复制到根目录;
8. 再将文件夹"0"内的"FF1"重命名为"FF2";
9. 再次复制到根目录, 以此类推;
10. See error.

**Expected behavior**
莫得

**Screenshots**
If applicable, add screenshots to help explain your problem:

图片1: 官方demo内: 
![图像 001](https://user-images.githubusercontent.com/87637270/166516418-6d1ef1d4-371d-410f-8200-66648862e57c.png)

图片2: 利用压缩包炸弹占用150TB的空间示意:
![图像 002](https://user-images.githubusercontent.com/87637270/166516427-98f31473-3e5f-4062-8528-aaa2b8f21041.png)

**Desktop (please complete the following information):**
莫得

**Smartphone (please complete the following information):**
莫得

**Additional context**
Add any other context about the problem here: 
没看过其后台, 也没实际下载部署过, 故不知道这是不是个bug, 但...看着挺像, 希望尽快修复...

**Comment by DuckBurnIncense** [comment]
且无法删除:

![图像 003](https://user-images.githubusercontent.com/87637270/166517976-396f7103-5da1-4aad-a1e7-9ec6e218af9b.png)
除

**Comment by HFO4** [comment]
web端的复制只是复制了数据库索引，所以没有检查空间占用，后续版本会进行优化。

**Comment by HaoShen2021** [comment]
然后我就被封号了……，论坛也被封了……
