### ISSUE TITLE
求储存策略增加Webdav

### ISSUE THREAD

**Issue by Jovines** [cloudreve/Cloudreve#1270]
**Is your feature request related to a problem? Please describe.**
希望储存策略中增加Webdav，部分不支持的网盘可以通过这种方式添加上去，例如我使用了[阿里云盘的Webdav](https://github.com/messense/aliyundrive-webdav)，这样可以添加阿里云盘上去，比较方便。

**Describe the solution you'd like**
储存策略中支持Webdav的添加

**Describe alternatives you've considered**
我本地尝试过先利用rclone等工具将阿里云盘webdav挂载到本地，然后再加到[Cloudreve](https://github.com/cloudreve/Cloudreve)中

**Additional context**
此外能否多增加一些产物，例如windows 的 arm 版本

**Comment by HaoShen2021** [comment]
论坛里提过，集中管理不是cloudreve开发的方向，定位不明确
开发者暂无计划

**Comment by HFO4** [comment]
webdav无法实现客户端直传

**Comment by Cinnamoroll-Rabbit** [comment]
webdav无法实现客户端直传，可以的话还是挂载再加最好。

**Comment by YUDONGLING** [comment]
锁定此 issue, 后续讨论请在 https://github.com/cloudreve/cloudreve/discussions/3433 继续进行。
Lock this issue and more discussion will be avaliable at https://github.com/cloudreve/cloudreve/discussions/3433.
