### ISSUE TITLE
希望添加一个新功能：从机与主机通行时可以使用另一个地址

### ISSUE THREAD

**Issue by ghost** [cloudreve/Cloudreve#1272]
如题，如果主机和从机在同一个内网下，通信时走内网地址延时低，稳定，省流量。
建议：在编辑从机页面时，增加 “从机访问主机的地址”  如http://10.0.0.1，https://192.168.0.1:5212……
感谢开发队的辛勤耕耘，cloudreve真的是越来越好了

**Comment by GreenTeodoro839** [comment]
@GitMouse2022 从机公网ip解析到一个域名，主机hosts把这个域名解析到内网ip

**Comment by Cinnamoroll-Rabbit** [comment]
> @GitMouse2022 从机公网ip解析到一个域名，主机hosts把这个域名解析到内网ip

这是个好办法，但是使用内网ip也会更稳妥一些。
