### ISSUE TITLE
希望添加一个新功能：可以限制单次用户离线下载批量链接数量

### ISSUE THREAD

**Issue by GitMouse2022** [cloudreve/Cloudreve#1273]
如题

**Comment by HFO4** [comment]
可以在用户组设置中限制。

**Comment by GitMouse2022** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    thanks！
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年5月5日 ***@***.***> 写道： 



Closed #1273.
