### ISSUE TITLE
部分情况下 界面错位

### ISSUE THREAD

**Issue by ghost** [cloudreve/Cloudreve#1274]
1.
<img width="877" alt="image" src="https://user-images.githubusercontent.com/104818082/166854742-69b1a57e-3203-47e3-ad7e-9defb2380b33.png">

文件夹过长时可以显示前几个字符，之后由省略号代替，如[Airota][Nakitai…

2.
<img width="550" alt="image" src="https://user-images.githubusercontent.com/104818082/166854913-f1bc4c87-bcd1-4b2e-a8c4-4bdcb77f96cc.png">

这样很不美观，应当全部的工具条都换行

**Comment by Cinnamoroll-Rabbit** [comment]
可以改成工具栏只显示最多40%，超过省略号。底部文件名超出框架显示省略号。

**Comment by GitMouse2022** [comment]
3. 
<img width="420" alt="image" src="https://user-images.githubusercontent.com/104818082/169429652-249a5809-b99e-455e-ab5d-45c575959908.png">
容量配额也需要优化
