### ISSUE TITLE
能否增加一个类似filebrowser的baseurl的设置

### ISSUE THREAD

**Issue by vvmzgi** [cloudreve/Cloudreve#1275]
能否增加一个类似filebrowser的baseurl的设置，这样整个应用可以不用部署在根目录上（http://x.x.x.x:5212/），而是部署在指定子路径上（如http://x.x.x.x:5212/cloud/），这样就可以只用一个域名和一个端口去反向代理到cloudreve

**Comment by GitMouse2022** [comment]
参见 https://github.com/cloudreve/Cloudreve/issues/1129

**Comment by GitMouse2022** [comment]
现在还不能

**Comment by Cinnamoroll-Rabbit** [comment]
现在确实不能，但是可以搞一个自动获取的，比如默认是获取到反代的/，就直接用/，而如果自动获取到了/cloud，那就使用/cloud
