### ISSUE TITLE
部分情况下 全站单页应用导致站点标题未正常显示

### ISSUE THREAD

**Issue by ghost** [cloudreve/Cloudreve#1276]
复现步骤：
1、打开一个文本文档
<img width="747" alt="image" src="https://user-images.githubusercontent.com/104818082/166869613-4d249401-4329-4e4d-939c-c04bf96902fa.png">
现在标题为bug.txt
2、点击左侧列表中的其他页面
<img width="803" alt="image" src="https://user-images.githubusercontent.com/104818082/166869592-2f5052a1-cdcc-4212-b21e-a7054ce22ca9.png">
但标题未正确刷新

**Comment by Cinnamoroll-Rabbit** [comment]
这确实是个bug，标题应该可以自动刷新，等待修复。
