### ISSUE TITLE
可以搞一个同一个用户在不同存储策略有不同容量的功能吗(专业版)

### ISSUE THREAD

**Issue by MoeCinnamo** [cloudreve/Cloudreve#1281]
请问可以搞一个同一个用户在不同存储策略有不同容量的功能吗<br>
比如说，用户1在用户组A1里面，A1用户组有A和B两个存储策略，可以分别设置用户1在存储策略A里面拥有50g空间，存储策略B里面拥有当前用户组的最大空间这样的功能。

**Comment by caixiaohaier** [comment]
+1，我的使用环境是od+物理从机，我是想用户A在od的存储策略能够用多点容量，物理从机少点，毕竟物理从机的带宽啥的比较贵的。od就无所谓了，另外想购买容量包功能同步增加购买哪个存储策略的容量包这样~

**Comment by Cinnamoroll-Rabbit** [comment]
> +1，我的使用环境是od+物理从机，我是想用户A在od的存储策略能够用多点容量，物理从机少点，毕竟物理从机的带宽啥的比较贵的。od就无所谓了，另外想购买容量包功能同步增加购买哪个存储策略的容量包这样~

是不是用户A在od来说，是当前用户组的最大空间，比如当前用户组有100g最大初始空间，od就可以用100g，而物理从机只能限制一个用户最大50g这样

**Comment by caixiaohaier** [comment]
对的对的，另外想购买容量包功能同步增加购买哪个存储策略的容量包这样~

**Comment by Cinnamoroll-Rabbit** [comment]
> 对的对的，另外想购买容量包功能同步增加购买哪个存储策略的容量包这样~

那就是容量包增加定向容量包和全部容量包，全部容量包除仅支持定向容量包的存储策略外，可以增加所有的存储策略容量，而定向容量包只能给单独的存储策略增加容量。管理员可以修改存储策略是仅定向还是支持全部。为了防止存储策略出现混淆，可以在用户后台仅显示当前存储策略所存储的文件，更换存储策略后文件不显示，显示更换存储策略里的文件。
