### ISSUE TITLE
内存只增少减，咨询有什么情况会如此？

### ISSUE THREAD

**Issue by muzig** [cloudreve/Cloudreve#1283]
![Snipaste_2022-05-07_16-32-53](https://user-images.githubusercontent.com/93570733/167246351-1260a4a6-0616-48cd-8841-e55549f52b8a.png)

目前使用情况：

Mac 采用 WebDAV 接入
Linux 采用 WebDAV 接入
没有网页访问的情况，没有解压看视频等操作

疑问？

内存只增少减，想咨询下什么情况会导致如此。

**Comment by vvisionnn** [comment]
Please follow the bug report template, I am confused because it is just statistic picture even without Cloudreve name inside, If you mean the green light one is the memory usage, please attach the reproduce step in the report template

**Comment by muzig** [comment]
好的，谢谢；我先尝试本地跑一下源码，拉取pprof看看内存分布情况。
