### ISSUE TITLE
一主二从，从机负责离线下载的情况下，离线下载任务只有50个。

### ISSUE THREAD

**Issue by q601904795** [cloudreve/Cloudreve#1285]
版本3.5.3
一主二从，从机负责离线下载的情况下，离线下载任务只有50个。
超过50个，创建任务时会提醒创建任务失败。
这个是配置文件哪个配置错误？还是新版本bug?
之前3.4.3的时候并没有问题

**Comment by HFO4** [comment]
@q601904795 用户组设置中更改一下限制

**Comment by q601904795** [comment]
解决 感谢
