### ISSUE TITLE
文件去除功能

### ISSUE THREAD

**Issue by wangxiaoerYah** [cloudreve/Cloudreve#1286]
问题描述:
使用离线下载种子文件，有概率遇到Cloudreve上传失败,但是文件却已经上传到对象储存(Onedrive)里面。
不仅仅是离线下载，有可能是手动上传。遇到网络故障，或者数据库故障等等。都有可能造成这种问题
日积月累，这种文件会越来越多，白白占用空间。
PS:昨天我测试数据库集群，就用Cloudreve下载了权利的游戏1-5季，结果中途Cloudreve写入太繁忙，遇到了 Error 1047: WSREP has not yet prepared node for application use 错误。然后我查看下载结果，有39个上传成功10个失败。但是查看onedrive却有49个文件(权利的游戏)。

功能需求:
将这种文件删除。

实现构想:
一般默认设置的上传路径都是uploads，可以通过对象储存(onedrive)API列出uploads路径的文件列表，然后对比数据库中存在的文件名，不存在的文件就删除。
可以在后台管理添加这个功能，不用天天清理，设置定时清理或者手动清理即可。

@HFO4 

还有一点不明白，就是从机设置的redis配置，从机的redis是要连接到master主机上的redis吗？还是在从机上搭建redis?望刘大解答下🙏

**Comment by GitMouse2022** [comment]
+1
希望删除文件后空文件夹也自动删除

**Comment by Licsber** [comment]
> +1 希望删除文件后空文件夹也自动删除

这个功能不可能有吧 S3默认是这样 因为是伪文件夹
自建存储还这样就有点不可理解了

**Comment by wangxiaoerYah** [comment]
> > +1 希望删除文件后空文件夹也自动删除
> 
> 这个功能不可能有吧 S3默认是这样 因为是伪文件夹
> 自建存储还这样就有点不可理解了

文件夹无所谓，主要是文件需要清理。
