### ISSUE TITLE
部分情况下 默认排序方式会出现 sorted ascending

### ISSUE THREAD

**Issue by GitMouse2022** [cloudreve/Cloudreve#1287]
<img width="485" alt="image" src="https://user-images.githubusercontent.com/104818082/167356227-ea977646-47c3-4902-ae42-2af250ddfea0.png">

**Comment by HFO4** [comment]
Fixed at https://github.com/cloudreve/frontend/commit/f2f8d7c43a64d51761cca2533f2a342412d23c3c#diff-09ec4ce2cd245f6569e87a1462ce938d8e85695f3b1ef943fe1f0b71672a12e3L332

**Comment by GitMouse2022** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        thanks!
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年5月9日 ***@***.***> 写道： 



Fixed at ***@***.***#diff-09ec4ce2cd245f6569e87a1462ce938d8e85695f3b1ef943fe1f0b71672a12e3L332
