### ISSUE TITLE
[Pro版] 希望增加一个新功能：可添加流量包，用户组内可以设置默认最大流量为多少，用户可以购买流量包

### ISSUE THREAD

**Issue by GitMouse2022** [cloudreve/Cloudreve#1288]
如题，开发的算法参考如下
流量的计算：
1.对于本机，从机等后端可以识别download访问次数（直链也可以吧），流量为次数x文件大小。
2.对于生成链接有效期为1h的，如onedrive，流量为次数x文件大小，在一小时内重复下载同一文件，不消耗流量。
3.对于其他储存策略，应该也可以实现。
流量的选项：后台用户组内可以设置该用户组内默认最大流量，如1TB/月，增值服务中可以添加，前台可以购买。
更高级的设置：参见 https://github.com/cloudreve/Cloudreve/issues/1281

**Comment by HFO4** [comment]
对于第三方存储策略，下载链接一单生成就无法控制用户的多次下载行为。

**Comment by GitMouse2022** [comment]
但是我想用户不会每天一直下载同一文件吧

**Comment by unauth401** [comment]
@GitMouse2022 请记住 在任何时候 都不要相信你的用户
永远
