### ISSUE TITLE
希望添加一个新功能：文件重命名后物理文件名变量中的{originname}部分也应当重命名

### ISSUE THREAD

**Issue by ghost** [cloudreve/Cloudreve#1290]
如题，在网盘的文件重命名后，虽然直接下载（除了od）都是重命名后的文件，但是物理文件没有重命名。建议：如果后台不开启文件自动重命名或开启，变量包含{originname} ，在前台重命名文件，应当同步更新

**Comment by ELISHELL** [comment]
感觉你这个不符合 分布式存储规范！
