### ISSUE TITLE
上传文件数量多直接卡死死机

### ISSUE THREAD

**Issue by Galun-hu** [cloudreve/Cloudreve#1293]
**

ttl报错：

**

- root@aml:~# [  184.510870@1] BUG: soft lockup - CPU#1 stuck for 22s! [kswapd0:41]
- [  184.517902@1] Kernel panic - not syncing: softlockup: hung tasks
- [  184.523125@1] CPU: 1 PID: 41 Comm: kswapd0 Tainted: P             3.10.108-aml-s805 #3
- [  184.531064@1] [<c0014a78>] (unwind_backtrace+0x0/0xec) from [<c00118b8>] (show_stack+0x10/0x14)
- [  184.539738@1] [<c00118b8>] (show_stack+0x10/0x14) from [<c07ec20c>] (panic+0xa0/0x1f4)
- [  184.547636@1] [<c07ec20c>] (panic+0xa0/0x1f4) from [<c008df08>] (watchdog_timer_fn+0x23c/0x288)
- [  184.556324@1] [<c008df08>] (watchdog_timer_fn+0x23c/0x288) from [<c004c12c>] (__run_hrtimer.constprop.0+0x8c/0x108)
- [  184.566736@1] [<c004c12c>] (__run_hrtimer.constprop.0+0x8c/0x108) from [<c004caf4>] (hrtimer_interrupt+0x158/0x2bc)
- [  184.577159@1] [<c004caf4>] (hrtimer_interrupt+0x158/0x2bc) from [<c001c680>] (meson_timer_interrupt+0x78/0xa4)
- [  184.587145@1] [<c001c680>] (meson_timer_interrupt+0x78/0xa4) from [<c008e9c8>] (handle_irq_event_percpu+0x48/0x17c)
- [  184.597564@1] [<c008e9c8>] (handle_irq_event_percpu+0x48/0x17c) from [<c008eb38>] (handle_irq_event+0x3c/0x5c)
- [  184.607552@1] [<c008eb38>] (handle_irq_event+0x3c/0x5c) from [<c00918c8>] (handle_fasteoi_irq+0x104/0x148)
- [  184.617217@1] [<c00918c8>] (handle_fasteoi_irq+0x104/0x148) from [<c008e2a0>] (generic_handle_irq+0x28/0x38)
- [  184.627120@1] [<c008e2a0>] (generic_handle_irq+0x28/0x38) from [<c000ed68>] (handle_IRQ+0x7c/0x8c)
- [  184.636156@1] [<c000ed68>] (handle_IRQ+0x7c/0x8c) from [<c0008464>] (gic_handle_irq+0x40/0x5c)
- [  184.644884@1] [<c0008464>] (gic_handle_irq+0x40/0x5c) from [<c000da00>] (__irq_svc+0x40/0x70)
- [  184.653515@1] Exception stack(0xef453cc8 to 0xef453d10)
- [  184.659307@1] 3cc0:                   00000002 00000000 00000004 00000003 ed6d4ddc 00025bcb
- [  184.667861@1] 3ce0: 000000bf ed6d4d80 ed6d4ddc ef453d80 00000000 00000000 00000000 ef453d10
- [  184.676452@1] 3d00: c07f4584 c07f45b4 80000113 ffffffff
- [  184.682387@1] [<c000da00>] (__irq_svc+0x40/0x70) from [<c07f45b4>] (_raw_spin_lock+0x40/0x50)
- [  184.691328@1] [<c07f45b4>] (_raw_spin_lock+0x40/0x50) from [<c00c7adc>] (__swap_duplicate+0x44/0x150)
- [  184.701032@1] [<c00c7adc>] (__swap_duplicate+0x44/0x150) from [<c00a99e0>] (shmem_writepage+0x184/0x2ac)
- [  184.711063@1] [<c00a99e0>] (shmem_writepage+0x184/0x2ac) from [<c00a6c28>] (shrink_page_list+0x444/0x7dc)
- [  184.721245@1] [<c00a6c28>] (shrink_page_list+0x444/0x7dc) from [<c00a7514>] (shrink_inactive_list+0x1e4/0x2c4)
- [  184.731983@1] [<c00a7514>] (shrink_inactive_list+0x1e4/0x2c4) from [<c00a7dec>] (shrink_zone+0x518/0x578)
- [  184.742353@1] [<c00a7dec>] (shrink_zone+0x518/0x578) from [<c00a8b3c>] (kswapd+0x5ac/0x8a0)
- [  184.751519@1] [<c00a8b3c>] (kswapd+0x5ac/0x8a0) from [<c0049148>] (kthread+0xac/0xb8)
- [  184.760165@1] [<c0049148>] (kthread+0xac/0xb8) from [<c000dec0>] (ret_from_fork+0x14/0x34)
- [  184.769241@0] CPU0: stopping
- [  184.775665@0] CPU: 0 PID: 1441 Comm: cloudreve Tainted: P             3.10.108-aml-s805 #3
- [  184.784788@0] [<c0014a78>] (unwind_backtrace+0x0/0xec) from [<c00118b8>] (show_stack+0x10/0x14)
- [  184.794397@0] [<c00118b8>] (show_stack+0x10/0x14) from [<c00131d0>] (handle_IPI+0xd4/0x180)
- [  184.803711@0] [<c00131d0>] (handle_IPI+0xd4/0x180) from [<c000847c>] (gic_handle_irq+0x58/0x5c)
- [  184.813436@0] [<c000847c>] (gic_handle_irq+0x58/0x5c) from [<c000dbbc>] (__irq_usr+0x3c/0x60)
- [  184.823045@0] Exception stack(0xedb0bfb0 to 0xedb0bff8)
- [  184.829794@0] bfa0:                                     00008d62 022b23a0 00008d62 00000000
- [  184.839323@0] bfc0: 8f2fba93 0000000f 23cbeea5 00000004 00000000 00000000 01e67770 000fffff
- [  184.848877@0] bfe0: 7eea4e1a 022b2d0c 00072450 00071ac4 20050010 ffffffff
- [  184.856844@3] CPU3: stopping
- [  184.863642@3] CPU: 3 PID: 1446 Comm: cloudreve Tainted: P             3.10.108-aml-s805 #3
- [  184.873153@3] [<c0014a78>] (unwind_backtrace+0x0/0xec) from [<c00118b8>] (show_stack+0x10/0x14)
- [  184.883134@3] [<c00118b8>] (show_stack+0x10/0x14) from [<c00131d0>] (handle_IPI+0xd4/0x180)
- [  184.892797@3] [<c00131d0>] (handle_IPI+0xd4/0x180) from [<c000847c>] (gic_handle_irq+0x58/0x5c)
- [  184.902873@3] [<c000847c>] (gic_handle_irq+0x58/0x5c) from [<c000dbbc>] (__irq_usr+0x3c/0x60)
- [  184.912797@3] Exception stack(0xed73bfb0 to 0xed73bff8)
- [  184.919848@3] bfa0:                                     36750ec3 4120a754 0000aabf 00000000
- [  184.929670@3] bfc0: d9d43b0a 00000011 36750ec3 00000034 00000000 00000000 01c82ff0 000fffff
- [  184.939537@3] bfe0: f982cc99 022b4d20 00070958 009b7e50 00050010 ffffffff
- [  184.947866@2] CPU2: stopping
- [  184.955059@2] CPU: 2 PID: 0 Comm: swapper/2 Tainted: P             3.10.108-aml-s805 #3
- [  184.964727@2] [<c0014a78>] (unwind_backtrace+0x0/0xec) from [<c00118b8>] (show_stack+0x10/0x14)
- [  184.975153@2] [<c00118b8>] (show_stack+0x10/0x14) from [<c00131d0>] (handle_IPI+0xd4/0x180)
- [  184.985275@2] [<c00131d0>] (handle_IPI+0xd4/0x180) from [<c000847c>] (gic_handle_irq+0x58/0x5c)
- [  184.995774@2] [<c000847c>] (gic_handle_irq+0x58/0x5c) from [<c000da00>] (__irq_svc+0x40/0x70)
- [  185.006161@2] Exception stack(0xef2a1fa0 to 0xef2a1fe8)
- [  185.013738@2] 1fa0: 00000002 00000000 000082aa 00000000 ef2a0000 ef2a0000 c0b31490 c07f7bb4
- [  185.024125@2] 1fc0: ef2a0000 c0b817e2 c09c4670 00000000 01000000 ef2a1fe8 c000f1f0 c000f1f4
- [  185.034495@2] 1fe0: 60070013 ffffffff
- [  185.042124@2] [<c000da00>] (__irq_svc+0x40/0x70) from [<c000f1f4>] (arch_cpu_idle+0x28/0x2c)
- [  185.054825@1] SMP: failed to stop secondary CPUs
- [  185.054825@1] SMP: failed to stop secondary CPUs
- 2c) from [<c006bd18>] (cpu_startup_entry+0xfc/0x150)
- [  185.066550@2] [<c006bd18>] (cpu_startup_entry+0xfc/0x150) from [<009e9044>] (0x9e9044)
-

**

F12日志：
[
[192.168.1.28-1652199860659.log](https://github.com/cloudreve/Cloudreve/files/8663367/192.168.1.28-1652199860659.log)
](url)

**

上传策略为默认策略
[
![网页捕获_11-5-2022_02032_192 168 1 28](https://user-images.githubusercontent.com/61612946/167677848-4828a57d-b602-40c9-a7fa-1d11b3924290.jpeg)
](url)

**Comment by HFO4** [comment]
并行任务数量是多少？

**Comment by Galun-hu** [comment]
> 

并行数量1个

**Comment by HFO4** [comment]
是浏览器死机还是服务端死机？

**Comment by Galun-hu** [comment]
> 是浏览器死机还是服务端死机？

服务器死机

**Comment by MoeCinnamo** [comment]
服务器瓶颈问题，添加后台限制存储策略最大上传文件数即可解决。
