### ISSUE TITLE
有 Windows 的客户端软件吗？

### ISSUE THREAD

**Issue by MrLanYX** [cloudreve/Cloudreve#1297]
<image src='https://raw.githubusercontent.com/cloudreve/docs/master/images/homepage.png'/>
看 readme 的图片是有 pc端的软件吗？

**Comment by GitMouse2022** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    这是pwa 自己搜，是伪客户端
    
     
    
        
                    ***@***.***
        
    
 

    在2022年5月12日 ***@***.***> 写道： 






看 readme 的图片是有 pc端的软件吗？

**Comment by vvisionnn** [comment]
> For user experience, please post to the [forum](https://forum.cloudreve.org/)

currently we don't offer the windows client, but we have PWA fully supported
