### ISSUE TITLE
希望添加一个新功能！添加共享文件夹，所有用户都可以看到！

### ISSUE THREAD

**Issue by LANDH** [cloudreve/Cloudreve#1302]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by LANDH** [comment]
强强强👍

**Comment by Andy17269** [comment]
能否基础版开放？毕竟这个功能很基本，比如里面放公告，推广链接等

**Comment by marvinli001** [comment]
> 能否基础版开放？毕竟这个功能很基本，比如里面放公告，推广链接等

公告不是后台有这功能吗.....如果推广链接这些就涉及商业化了

**Comment by Andy17269** [comment]
> > 能否基础版开放？毕竟这个功能很基本，比如里面放公告，推广链接等
> 
> 公告不是后台有这功能吗.....如果推广链接这些就涉及商业化了

普通版没有吧？

**Comment by LingyeSoul** [comment]
> > > 能否基础版开放？毕竟这个功能很基本，比如里面放公告，推广链接等
> > 
> > 
> > 公告不是后台有这功能吗.....如果推广链接这些就涉及商业化了
> 
> 普通版没有吧？

这简单，页脚里面插JS解决，我就是这么干的
