### ISSUE TITLE
希望增加文件预览中有返回按钮

### ISSUE THREAD

**Issue by caixiaohaier** [cloudreve/Cloudreve#1304]
希望增加文件预览中有返回按钮，比如在看视频，或者浏览PDF，TXT等，现在点进去看完只能点我的文件进行根菜单或者用浏览器的后退按钮，这很不方便

**Comment by HFO4** [comment]
如果有返回按钮的话，你只能点击返回按钮返回。
如果用浏览器级别的返回的话，你可以通过各种手势、快捷键返回，并没觉得不方便。

**Comment by xb2016** [comment]
> 如果有返回按钮的话，你只能点击返回按钮返回。 如果用浏览器级别的返回的话，你可以通过各种手势、快捷键返回，并没觉得不方便。

这个问题今天想到了一个例外：如果我打开了一个视频预览，并且通过播放列表看了N个视频，那我需要按浏览器的返回按钮N次才可以回到目录，这就相当不方便了。我觉得可以把预览界面的标题点击改成回到文件目录而不是回到根目录。
