### ISSUE TITLE
[Pro] 希望添加一个团队共享功能

### ISSUE THREAD

**Issue by MoeCinnamo** [cloudreve/Cloudreve#1305]
希望添加一个团队共享功能
成员加入这个团队后，将会看到共享文件夹。
团队内每个成员都会有一个私有存储空间和共享存储空间，私有存储空间除本私有空间所有者外，其它成员都看不见；共享存储空间的内容都可以看见，相当于共享文件夹。
管理员可以设置团队的容量配额和团队组，也可以添加团队容量包，每个团队所使用的空间按照每个成员的私有空间+共享空间来计算。并且管理员可以指定哪些存储策略用来为团队提供存储。
管理员也可以为团队限制下载速度、限制多次下载请求等。

**Comment by GitMouse2022** [comment]
> 4.0 Pro

还有多久啊 期待☺

**Comment by MoeCinnamo** [comment]
> 4.0 Pro

感觉3.8 Pro就可能会出

**Comment by GitMouse2022** [comment]
> > 4.0 Pro
> 
> 感觉3.8 Pro就可能会出

20年说的是预计3.3  开发大队加油吧！早日实现！

**Comment by ELISHELL** [comment]
这个也是我迫切需要的。公司内部使用，多个部门多个管理员。多租户体系。

**Comment by MoeCinnamo** [comment]
> 这个也是我迫切需要的。公司内部使用，多个部门多个管理员。多租户体系。

是的，我也是需要的

**Comment by fightingbamboo** [comment]
迫切需要

**Comment by xiaopeng12138** [comment]
这个要是出了必买Pro，出了后就对nextcloud无欲望了
