### ISSUE TITLE
【Pro】希望在4.0优化离线下载

### ISSUE THREAD

**Issue by ghost** [cloudreve/Cloudreve#1307]
1.希望在管理面板内增加单次批量导入链接数量（将导入链接数量与同时进行任务数分离，目前的设置，假如设为2，那么单次只能两个链接一导入，两个任务同时下载）
2.【pro】希望用户组可以设置允许使用哪些节点，并可设置每个节点介绍（如德国高速1，us2等）以及节点负载情况
在用户界面可以自由选择节点
3.离线下载失败后自动换节点重试
4.希望离线下载后文件中转可以显示进度
5.控制面板-离线下载 链接过长显示省略号，将从机#  替换为设置的名称
6.可以将离线下载和中转合并，视为一个任务，（这样可以有效解决上下带宽不对等的服务器中转过慢导致的文件堆积，磁盘爆满）
希望以上可以实现 期待~~~

**Comment by GitMouse2022** [comment]
8.离线下载任务应当在当前进行的几个任务完成后再分配节点（发送到从机），而不是一导入链接就全部分配好

**Comment by qitayun** [comment]
期待
