### ISSUE TITLE
离线下载相关

### ISSUE THREAD

**Issue by marvinli001** [cloudreve/Cloudreve#1308]
希望增加对转存失败的离线下载任务，未成功转存的文件有重试的功能，转存OneDrive世纪互联文百G的时候容易connection reset by peer
还有就是从从机目录导入的文件转存的时候可以直接走从机上传不走本机嘛？

**Comment by wangxiaoerYah** [comment]
https://docs.cloudreve.org/getting-started/config

末尾有写，注意并行协程数，不要太大，建议根据CPU核数来定，比如我的CPU4核，并行任务我定的4，协程我是8
重试我设置了999，这样传输慢了点但是不会被突然的并发上传导致网络错误，或者被onedrive限制。

**Comment by xjc19960724** [comment]
> 
cr单方面的问题，其他上传工具比如rclone和onedriveuploader就不会出错那么频繁

**Comment by wangyijin209** [comment]
> 

离线转存失败怎么解决？只能从头开始？
