### ISSUE TITLE
3.5.3版本报Cannot read properties of undefined (reading 'saveType')错误

### ISSUE THREAD

**Issue by lemontea66** [cloudreve/Cloudreve#1311]
登录的时候报错Cannot read properties of undefined (reading 'saveType')，这个问题之前提交过issue，给出的解决方案是清空浏览器缓存。按照方法清空浏览器缓存后依然在登录时右上角报错Cannot read properties of undefined (reading 'saveType')这个问题

**Comment by lemontea66** [comment]
更新：登录是报错的并且跳转到cloudreve的404页面，但是如果进入/home目录的话是能够进行操作的，后台也可以上。出现一个新问题就是上传按钮无法显示，右键点击上传后报错，提示“上传组件还未加载完成”。更换浏览器、更换设备都无法解决此问题。

**Comment by HFO4** [comment]
清空浏览器缓存，确保前端版本为最新。

**Comment by lemontea66** [comment]
已经清空缓存，版本3.5.3 pro
