### ISSUE TITLE
请问图片的外链怎么才能直接下载而不是浏览器查看

### ISSUE THREAD

**Issue by qzmp123** [cloudreve/Cloudreve#1312]
请问图片的外链（直链）怎么才能让他直接下载而不是在浏览器查看？搜到其它的帖子说的是加响应头“Content-Disposition: attachment”，可我不会代码，有哪位大神可以告知一下在哪修改吗？

**Comment by MoeCinnamo** [comment]
图片的外链如果浏览器支持解析就默认在浏览器查看，否则则会直接下载。这是图片外链的特性，很多的程序(包括极大部分的图床)都是在浏览器查看，而不是直接下载的。加响应头对于某些情况确实可用，但是在其它情况下也是没什么作用的。

**Comment by topjohncian** [comment]
Hi! That is the expected behaviour by design.
