### ISSUE TITLE
分片上传失败: The resource could not be found.

### ISSUE THREAD

**Issue by unkoe** [cloudreve/Cloudreve#1317]
**Describe the bug**
分片上传失败。

### Browser 提供的信息：
```
文件名：
file_demo.rar
文件大小：
145.5 MB (3 个分片, 每个分片 50.0 MB)
存储策略：
quick_cloud_drive
目的路径：
[根目录](javascript:void)
上传会话：
23 小时后过期
错误信息：
分片上传失败: The resource could not be found.
```
截图：
![image](https://user-images.githubusercontent.com/47616680/170218753-f4d4a2e5-401d-4966-bb17-e1de14b815c1.png)

### 存储策略：
上传文件使用的 `onedrive` 国际版版，因为默认**50M**失败，我将它设置为 *20M*，但是更小的分片似乎仍然失败。
![image](https://user-images.githubusercontent.com/47616680/170222368-5d05b87b-c05f-420d-a1ce-a1dcb9db77cc.png)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chrome
 - Version 100.0.4896.127

**Additional context**

我不知道 `cloudreve` 生成的 `log` 存储的路径，幸运的是我是用 `docker` 部署的。我决定在容器日志中寻找原因，发现容器日志中有一次 `warn`，这应该是导致失败最为可能的原因：
```
[GIN] 2022/05/25 - 16:26:38 | 301 |  809.013657ms | 113.109.111.189 | GET      "/api/v3/file/thumb/nriG"
[Warning] 2022-05-25 16:32:24 未发送回调，删除文件
```
还有一次似乎调用用户头像相关的接口时出现的失败，可能是响应的json并不正确。
```
[GIN] 2022/05/25 - 16:22:53 | 404 |    2.377895ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/l"
unexpected end of JSON input
```
这次也许可能是 `onedrive 国际版` 接口不稳定导致的分片上传失败，我认为可以增加上传重试机制，可供用户配置失败重试的次数，以便避免这种情况。

提供相对完整的 log

```
[GIN] 2022/05/25 - 16:15:53 | 200 |    2.510859ms | 113.109.111.189 | GET      "/api/v3/file/search/doc/internal"
[GIN] 2022/05/25 - 16:15:54 | 200 |    2.337375ms | 113.109.111.189 | GET      "/api/v3/file/search/image/internal"
[GIN] 2022/05/25 - 16:15:55 | 200 |    1.861172ms | 113.109.111.189 | GET      "/api/v3/file/search/video/internal"
[GIN] 2022/05/25 - 16:15:58 | 500 |     936.839µs | 113.109.111.189 | GET      "/static/img/favicon.ico"
[GIN] 2022/05/25 - 16:15:58 | 200 |    2.048615ms | 113.109.111.189 | GET      "/api/v3/aria2/downloading"
[GIN] 2022/05/25 - 16:15:58 | 200 |    2.051503ms | 113.109.111.189 | GET      "/api/v3/aria2/finished?page=1"
[GIN] 2022/05/25 - 16:16:00 | 200 |    2.238781ms | 113.109.111.189 | GET      "/api/v3/directory/"
[GIN] 2022/05/25 - 16:16:00 | 500 |     909.961µs | 113.109.111.189 | GET      "/static/img/favicon.ico"
[GIN] 2022/05/25 - 16:16:01 | 200 |    1.964934ms | 113.109.111.189 | GET      "/api/v3/file/search/doc/internal"
[GIN] 2022/05/25 - 16:16:01 | 200 |    2.161796ms | 113.109.111.189 | GET      "/api/v3/file/search/doc/internal"
[GIN] 2022/05/25 - 16:16:02 | 200 |    1.729385ms | 113.109.111.189 | GET      "/api/v3/file/search/doc/internal"
[GIN] 2022/05/25 - 16:16:03 | 404 |     2.25731ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/l"
[GIN] 2022/05/25 - 16:16:05 | 500 |     871.996µs | 113.109.111.189 | GET      "/static/img/favicon.ico"
[GIN] 2022/05/25 - 16:16:05 | 200 |    1.742694ms | 113.109.111.189 | GET      "/api/v3/admin/summary"
[GIN] 2022/05/25 - 16:16:05 | 404 |     1.94047ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/s"
[GIN] 2022/05/25 - 16:16:06 | 200 |  665.086043ms | 113.109.111.189 | GET      "/api/v3/admin/news"
[GIN] 2022/05/25 - 16:16:36 | 500 |      807.17µs | 113.109.111.189 | GET      "/static/img/favicon.ico"
[GIN] 2022/05/25 - 16:16:36 | 200 |    7.264701ms | 113.109.111.189 | POST     "/api/v3/admin/policy/list"
[GIN] 2022/05/25 - 16:16:36 | 200 |    9.225582ms | 113.109.111.189 | POST     "/api/v3/admin/file/list"
[GIN] 2022/05/25 - 16:16:40 | 200 |  332.260166ms | 113.109.111.189 | GET      "/api/v3/admin/file/preview/4"
[GIN] 2022/05/25 - 16:16:40 | 200 |     739.392µs | 113.109.111.189 | GET      "/favicon.ico"
[GIN] 2022/05/25 - 16:16:42 | 304 |     539.234µs | 113.109.111.189 | GET      "/service-worker.js"
[GIN] 2022/05/25 - 16:16:45 | 200 |     1.77295ms | 113.109.111.189 | GET      "/api/v3/site/config"
[GIN] 2022/05/25 - 16:16:46 | 200 |    2.507606ms | 113.109.111.189 | POST     "/api/v3/admin/policy/list"
[GIN] 2022/05/25 - 16:16:46 | 200 |     2.82223ms | 113.109.111.189 | POST     "/api/v3/admin/file/list"
[GIN] 2022/05/25 - 16:16:46 | 404 |    1.097898ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/s"
[GIN] 2022/05/25 - 16:16:46 | 200 |     420.576µs | 113.109.111.189 | GET      "/manifest.json"
[GIN] 2022/05/25 - 16:16:46 | 500 |     939.555µs | 113.109.111.189 | GET      "/static/img/favicon.ico"
[GIN] 2022/05/25 - 16:16:48 | 304 |     578.506µs | 113.109.111.189 | GET      "/service-worker.js"
[GIN] 2022/05/25 - 16:16:54 | 200 |    2.402931ms | 113.109.111.189 | POST     "/api/v3/admin/file/delete"
[GIN] 2022/05/25 - 16:16:54 | 200 |    3.234847ms | 113.109.111.189 | POST     "/api/v3/admin/file/list"
[GIN] 2022/05/25 - 16:16:56 | 200 |    1.511777ms | 113.109.111.189 | GET      "/api/v3/site/config"
[GIN] 2022/05/25 - 16:16:56 | 200 |    4.304076ms | 113.109.111.189 | POST     "/api/v3/admin/file/list"
[GIN] 2022/05/25 - 16:16:56 | 200 |    4.776955ms | 113.109.111.189 | POST     "/api/v3/admin/policy/list"
[GIN] 2022/05/25 - 16:16:56 | 404 |    1.615922ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/s"
[GIN] 2022/05/25 - 16:16:57 | 500 |       1.544ms | 113.109.111.189 | GET      "/static/img/favicon.ico"
[GIN] 2022/05/25 - 16:16:57 | 200 |     266.093µs | 113.109.111.189 | GET      "/manifest.json"
[GIN] 2022/05/25 - 16:16:58 | 304 |     865.023µs | 113.109.111.189 | GET      "/service-worker.js"
[GIN] 2022/05/25 - 16:17:00 | 200 |     945.672µs | 113.109.111.189 | GET      "/api/v3/admin/summary"
[GIN] 2022/05/25 - 16:17:00 | 500 |     698.731µs | 113.109.111.189 | GET      "/static/img/favicon.ico"
[GIN] 2022/05/25 - 16:17:00 | 200 |  662.460384ms | 113.109.111.189 | GET      "/api/v3/admin/news"
[GIN] 2022/05/25 - 16:17:02 | 200 |    3.004993ms | 113.109.111.189 | GET      "/api/v3/site/config"
[GIN] 2022/05/25 - 16:17:02 | 200 |    2.766412ms | 113.109.111.189 | GET      "/api/v3/directory/"
[GIN] 2022/05/25 - 16:17:02 | 200 |    1.806608ms | 113.109.111.189 | GET      "/api/v3/user/storage"
[GIN] 2022/05/25 - 16:17:02 | 404 |    1.894457ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/s"
[GIN] 2022/05/25 - 16:17:02 | 200 |    1.380907ms | 113.109.111.189 | GET      "/api/v3/user/storage"
[GIN] 2022/05/25 - 16:17:02 | 200 |     394.055µs | 113.109.111.189 | GET      "/manifest.json"
[GIN] 2022/05/25 - 16:17:02 | 500 |     820.356µs | 113.109.111.189 | GET      "/static/img/favicon.ico"
[GIN] 2022/05/25 - 16:17:04 | 304 |     550.063µs | 113.109.111.189 | GET      "/service-worker.js"
[GIN] 2022/05/25 - 16:19:17 | 200 |    3.095189ms | 113.109.111.189 | GET      "/api/v3/user/storage"
[GIN] 2022/05/25 - 16:19:17 | 200 |    4.195397ms | 113.109.111.189 | GET      "/api/v3/directory/"
[GIN] 2022/05/25 - 16:19:17 | 200 |    1.177181ms | 113.109.111.189 | GET      "/api/v3/user/storage"
[GIN] 2022/05/25 - 16:21:32 | 200 |    3.191543ms | 113.109.111.189 | DELETE   "/api/v3/file/upload/efe1b223-bbd1-4ca9-819a-0fd73897176f"
[Warning] 2022-05-25 16:22:00 未发送回调，删除文件
[GIN] 2022/05/25 - 16:22:03 | 200 |  641.990363ms | 113.109.111.189 | PUT      "/api/v3/file/upload"
unexpected end of JSON input
[GIN] 2022/05/25 - 16:22:10 | 200 |    1.129951ms | 113.109.111.189 | GET      "/api/v3/user/setting"
[GIN] 2022/05/25 - 16:22:10 | 404 |    1.968428ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/l"
[GIN] 2022/05/25 - 16:22:10 | 500 |    2.471966ms | 113.109.111.189 | GET      "/static/img/favicon.ico"
[GIN] 2022/05/25 - 16:22:15 | 200 |    2.333287ms | 113.109.111.189 | GET      "/api/v3/directory/"
[GIN] 2022/05/25 - 16:22:15 | 500 |    1.133654ms | 113.109.111.189 | GET      "/static/img/favicon.ico"
[GIN] 2022/05/25 - 16:22:23 | 200 |    1.996987ms | 113.109.111.189 | GET      "/api/v3/site/config"
[GIN] 2022/05/25 - 16:22:23 | 200 |    1.657306ms | 113.109.111.189 | GET      "/api/v3/user/storage"
```

**Comment by GitMouse2022** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    回调地址没写好
        
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

    在2022年5月25日 ***@***.***> 写道： 




Describe the bug

分片上传失败。

Browser 提供的信息：

文件名：

file_demo.rar

文件大小：

145.5 MB (3 个分片, 每个分片 50.0 MB)

存储策略：

quick_cloud_drive

目的路径：

[根目录](javascript:void)

上传会话：

23 小时后过期

错误信息：

分片上传失败: The resource could not be found.



截图：



存储策略：

上传文件使用的 onedrive 国际版版，因为默认50M失败，我将它设置为 20M，但是更小的分片似乎仍然失败。



Desktop (please complete the following information):



OS: windows 10

Browser chrome

Version 100.0.4896.127



Additional context

我不知道 cloudreve 生成的 log 存储的路径，幸运的是我是用 docker 部署的。我决定在容器日志中寻找原因，发现容器日志中有一次 warn，这可能是导致失败最为可能的原因：

[GIN] 2022/05/25 - 16:26:38 | 301 |  809.013657ms | 113.109.111.189 | GET      "/api/v3/file/thumb/nriG"

[Warning] 2022-05-25 16:32:24 未发送回调，删除文件



还有一次似乎调用用户头像相关的接口时出现的失败，可能是响应的json并不正确。

[GIN] 2022/05/25 - 16:22:53 | 404 |    2.377895ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/l"

unexpected end of JSON input



这次也许可能是 onedrive 国际版 接口不稳定导致的分片上传失败，我认为可以增加上传重试机制，可供用户配置失败重试的次数，以便避免这种情况。

提供相对完整的 log

[GIN] 2022/05/25 - 16:15:53 | 200 |    2.510859ms | 113.109.111.189 | GET      "/api/v3/file/search/doc/internal"

[GIN] 2022/05/25 - 16:15:54 | 200 |    2.337375ms | 113.109.111.189 | GET      "/api/v3/file/search/image/internal"

[GIN] 2022/05/25 - 16:15:55 | 200 |    1.861172ms | 113.109.111.189 | GET      "/api/v3/file/search/video/internal"

[GIN] 2022/05/25 - 16:15:58 | 500 |     936.839µs | 113.109.111.189 | GET      "/static/img/favicon.ico"

[GIN] 2022/05/25 - 16:15:58 | 200 |    2.048615ms | 113.109.111.189 | GET      "/api/v3/aria2/downloading"

[GIN] 2022/05/25 - 16:15:58 | 200 |    2.051503ms | 113.109.111.189 | GET      "/api/v3/aria2/finished?page=1"

[GIN] 2022/05/25 - 16:16:00 | 200 |    2.238781ms | 113.109.111.189 | GET      "/api/v3/directory/"

[GIN] 2022/05/25 - 16:16:00 | 500 |     909.961µs | 113.109.111.189 | GET      "/static/img/favicon.ico"

[GIN] 2022/05/25 - 16:16:01 | 200 |    1.964934ms | 113.109.111.189 | GET      "/api/v3/file/search/doc/internal"

[GIN] 2022/05/25 - 16:16:01 | 200 |    2.161796ms | 113.109.111.189 | GET      "/api/v3/file/search/doc/internal"

[GIN] 2022/05/25 - 16:16:02 | 200 |    1.729385ms | 113.109.111.189 | GET      "/api/v3/file/search/doc/internal"

[GIN] 2022/05/25 - 16:16:03 | 404 |     2.25731ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/l"

[GIN] 2022/05/25 - 16:16:05 | 500 |     871.996µs | 113.109.111.189 | GET      "/static/img/favicon.ico"

[GIN] 2022/05/25 - 16:16:05 | 200 |    1.742694ms | 113.109.111.189 | GET      "/api/v3/admin/summary"

[GIN] 2022/05/25 - 16:16:05 | 404 |     1.94047ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/s"

[GIN] 2022/05/25 - 16:16:06 | 200 |  665.086043ms | 113.109.111.189 | GET      "/api/v3/admin/news"

[GIN] 2022/05/25 - 16:16:36 | 500 |      807.17µs | 113.109.111.189 | GET      "/static/img/favicon.ico"

[GIN] 2022/05/25 - 16:16:36 | 200 |    7.264701ms | 113.109.111.189 | POST     "/api/v3/admin/policy/list"

[GIN] 2022/05/25 - 16:16:36 | 200 |    9.225582ms | 113.109.111.189 | POST     "/api/v3/admin/file/list"

[GIN] 2022/05/25 - 16:16:40 | 200 |  332.260166ms | 113.109.111.189 | GET      "/api/v3/admin/file/preview/4"

[GIN] 2022/05/25 - 16:16:40 | 200 |     739.392µs | 113.109.111.189 | GET      "/favicon.ico"

[GIN] 2022/05/25 - 16:16:42 | 304 |     539.234µs | 113.109.111.189 | GET      "/service-worker.js"

[GIN] 2022/05/25 - 16:16:45 | 200 |     1.77295ms | 113.109.111.189 | GET      "/api/v3/site/config"

[GIN] 2022/05/25 - 16:16:46 | 200 |    2.507606ms | 113.109.111.189 | POST     "/api/v3/admin/policy/list"

[GIN] 2022/05/25 - 16:16:46 | 200 |     2.82223ms | 113.109.111.189 | POST     "/api/v3/admin/file/list"

[GIN] 2022/05/25 - 16:16:46 | 404 |    1.097898ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/s"

[GIN] 2022/05/25 - 16:16:46 | 200 |     420.576µs | 113.109.111.189 | GET      "/manifest.json"

[GIN] 2022/05/25 - 16:16:46 | 500 |     939.555µs | 113.109.111.189 | GET      "/static/img/favicon.ico"

[GIN] 2022/05/25 - 16:16:48 | 304 |     578.506µs | 113.109.111.189 | GET      "/service-worker.js"

[GIN] 2022/05/25 - 16:16:54 | 200 |    2.402931ms | 113.109.111.189 | POST     "/api/v3/admin/file/delete"

[GIN] 2022/05/25 - 16:16:54 | 200 |    3.234847ms | 113.109.111.189 | POST     "/api/v3/admin/file/list"

[GIN] 2022/05/25 - 16:16:56 | 200 |    1.511777ms | 113.109.111.189 | GET      "/api/v3/site/config"

[GIN] 2022/05/25 - 16:16:56 | 200 |    4.304076ms | 113.109.111.189 | POST     "/api/v3/admin/file/list"

[GIN] 2022/05/25 - 16:16:56 | 200 |    4.776955ms | 113.109.111.189 | POST     "/api/v3/admin/policy/list"

[GIN] 2022/05/25 - 16:16:56 | 404 |    1.615922ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/s"

[GIN] 2022/05/25 - 16:16:57 | 500 |       1.544ms | 113.109.111.189 | GET      "/static/img/favicon.ico"

[GIN] 2022/05/25 - 16:16:57 | 200 |     266.093µs | 113.109.111.189 | GET      "/manifest.json"

[GIN] 2022/05/25 - 16:16:58 | 304 |     865.023µs | 113.109.111.189 | GET      "/service-worker.js"

[GIN] 2022/05/25 - 16:17:00 | 200 |     945.672µs | 113.109.111.189 | GET      "/api/v3/admin/summary"

[GIN] 2022/05/25 - 16:17:00 | 500 |     698.731µs | 113.109.111.189 | GET      "/static/img/favicon.ico"

[GIN] 2022/05/25 - 16:17:00 | 200 |  662.460384ms | 113.109.111.189 | GET      "/api/v3/admin/news"

[GIN] 2022/05/25 - 16:17:02 | 200 |    3.004993ms | 113.109.111.189 | GET      "/api/v3/site/config"

[GIN] 2022/05/25 - 16:17:02 | 200 |    2.766412ms | 113.109.111.189 | GET      "/api/v3/directory/"

[GIN] 2022/05/25 - 16:17:02 | 200 |    1.806608ms | 113.109.111.189 | GET      "/api/v3/user/storage"

[GIN] 2022/05/25 - 16:17:02 | 404 |    1.894457ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/s"

[GIN] 2022/05/25 - 16:17:02 | 200 |    1.380907ms | 113.109.111.189 | GET      "/api/v3/user/storage"

[GIN] 2022/05/25 - 16:17:02 | 200 |     394.055µs | 113.109.111.189 | GET      "/manifest.json"

[GIN] 2022/05/25 - 16:17:02 | 500 |     820.356µs | 113.109.111.189 | GET      "/static/img/favicon.ico"

[GIN] 2022/05/25 - 16:17:04 | 304 |     550.063µs | 113.109.111.189 | GET      "/service-worker.js"

[GIN] 2022/05/25 - 16:19:17 | 200 |    3.095189ms | 113.109.111.189 | GET      "/api/v3/user/storage"

[GIN] 2022/05/25 - 16:19:17 | 200 |    4.195397ms | 113.109.111.189 | GET      "/api/v3/directory/"

[GIN] 2022/05/25 - 16:19:17 | 200 |    1.177181ms | 113.109.111.189 | GET      "/api/v3/user/storage"

[GIN] 2022/05/25 - 16:21:32 | 200 |    3.191543ms | 113.109.111.189 | DELETE   "/api/v3/file/upload/efe1b223-bbd1-4ca9-819a-0fd73897176f"

[Warning] 2022-05-25 16:22:00 未发送回调，删除文件

[GIN] 2022/05/25 - 16:22:03 | 200 |  641.990363ms | 113.109.111.189 | PUT      "/api/v3/file/upload"

unexpected end of JSON input

[GIN] 2022/05/25 - 16:22:10 | 200 |    1.129951ms | 113.109.111.189 | GET      "/api/v3/user/setting"

[GIN] 2022/05/25 - 16:22:10 | 404 |    1.968428ms | 113.109.111.189 | GET      "/api/v3/user/avatar/kRfO/l"

[GIN] 2022/05/25 - 16:22:10 | 500 |    2.471966ms | 113.109.111.189 | GET      "/static/img/favicon.ico"

[GIN] 2022/05/25 - 16:22:15 | 200 |    2.333287ms | 113.109.111.189 | GET      "/api/v3/directory/"

[GIN] 2022/05/25 - 16:22:15 | 500 |    1.133654ms | 113.109.111.189 | GET      "/static/img/favicon.ico"

[GIN] 2022/05/25 - 16:22:23 | 200 |    1.996987ms | 113.109.111.189 | GET      "/api/v3/site/config"

[GIN] 2022/05/25 - 16:22:23 | 200 |    1.657306ms | 113.109.111.189 | GET      "/api/v3/user/storage"

**Comment by HFO4** [comment]
这是上传中断后又虚传出现的？中间间隔了多久？

**Comment by unkoe** [comment]
> 这是上传中断后又虚传出现的？中间间隔了多久？

上传过程中没有中断行为，这次我又尝试上传一个Ubuntu镜像，发现仍存在这种情况
![ubuntu imgae](https://user-images.githubusercontent.com/47616680/170227638-51277141-3e99-438a-862c-371d7259ab92.png)

**Comment by HFO4** [comment]
多尝试几下，是否10%复现？
上传到多大的时候出现的错误？

**Comment by unkoe** [comment]
> 多尝试几下，是否100%复现？ 上传到多大的时候出现的错误？

并不是100%复现，*145MB* 的压缩包重试3次后已经成功上传了，这个Ubuntu镜像在进行第一次重试，也能成功。所以我怀疑是国内使用 onedrive 接口稳定性的原因，如果支持断点续传能否自动重试呢？
![image](https://user-images.githubusercontent.com/47616680/170231676-53684e49-3583-4a7b-8469-89a22d42bcb3.png)
