### ISSUE TITLE
显示数量和实际数量不一致

### ISSUE THREAD

**Issue by fanweiya** [cloudreve/Cloudreve#1320]
我发现我上传的图片在页面显示的时候老是显示缺几张，有几张在前台不显示，但是在后台去看的时候又是全的，mysql数据库去看也是全的，重现上传又显示那一张已存在，但是就是在前台找不到，然后单独去看那个文件夹的详细信息也是全的，请问这是什么原因呢

https://i.imgtg.com/2022/05/28/hlsgM.png
https://i.imgtg.com/2022/05/28/hlVsG.png
https://i.imgtg.com/2022/05/28/hlfo1.png

**Comment by HFO4** [comment]
有可能是上传中断的文件占位符，尝试清空上传会话试试呢？

**Comment by fanweiya** [comment]
> 有可能是上传中断的文件占位符，尝试清空上传会话试试呢？

刷新了还是不行，而且去后台看，这个文件是完整的

**Comment by HFO4** [comment]
> > 有可能是上传中断的文件占位符，尝试清空上传会话试试呢？
> 
> 刷新了还是不行，而且去后台看，这个文件是完整的

是否方便发送后台账号到 support@cloudreve.org？ 方便排查。

**Comment by fanweiya** [comment]
> > > 有可能是上传中断的文件占位符，尝试清空上传会话试试呢？
> > 
> > 
> > 刷新了还是不行，而且去后台看，这个文件是完整的
> 
> 是否方便发送后台账号到 [support@cloudreve.org](mailto:support@cloudreve.org)？ 方便排查。

我是在局域网搭建的

**Comment by HFO4** [comment]
那或者把数据库的 `files` 和 `folders` 表 dump 出来？

**Comment by fanweiya** [comment]
https://transfer.sh/%28/9L13lI/cloudreve.sql%29.tar.gz

> 那或者把数据库的 `files` 和 `folders` 表 dump 出来？

**Comment by HFO4** [comment]
从数据库里看 `C1_01_02_01.jpg` 这个文件确实没有完成上传，可以在上传任务管理器右上角清空上传会话，然后重新上传此文件。

**Comment by fanweiya** [comment]
> 从上传任务管理器里看`C1_01_02_01.jpg`这个文件确实没有完成，可以上传清空上传会话文件，然后再上传这个文件。

好的，谢谢
