### ISSUE TITLE
[Pro] Cannot read properties of undefined (reading 'saveType')

### ISSUE THREAD

**Issue by black-fruit** [cloudreve/Cloudreve#1323]
在其他设备登录时出现 Cannot read properties of undefined (reading 'saveType') 字样
![Screenshot_20220529-160127](https://user-images.githubusercontent.com/77201076/170858449-0897d239-0893-4da0-b88b-b57e8014e26a.png)

**Comment by HFO4** [comment]
创建 issue 前请先搜索。
dup: https://github.com/cloudreve/Cloudreve/issues/1265
