### ISSUE TITLE
菜单建议

### ISSUE THREAD

**Issue by setube** [cloudreve/Cloudreve#1325]
网盘左侧菜单建议能够自定义
1.离线下载菜单: 如果我没配置离线下载或者没开启离线下载,那这个菜单项是不是应该隐藏起来呢
2.容量配额菜单: 如果后台增值服务里没有配置支付相关,容量包,可购用户组兑换码这些,那这个菜单是不是应该隐藏起来呢
3.连接与挂载菜单: 用户组未勾选,那这个菜单是不是应该隐藏起来呢
4.任务队列菜单: 如果后台队列里没有任务,那这个菜单是不是应该隐藏起来呢
5.存储空间扩容按钮: 我直接引用第二条建议里的话,如果后台增值服务里没有配置支付相关,容量包,可购用户组兑换码这些,那这个菜单是不是应该隐藏起来呢
以上五条仅为建议,或者说也算bug

**Comment by MoeCinnamo** [comment]
我还有一个建议，主页应该可以自定义

**Comment by topjohncian** [comment]
> 我还有一个建议，主页应该可以自定义

无计划

**Comment by MoeCinnamo** [comment]
> > 我还有一个建议，主页应该可以自定义
> 
> 无计划

这只是一个建议，不一定会有计划，但是我认为最好在4.2出来之前可以实现它。
