### ISSUE TITLE
安卓11下使用网页端中的"用外部播放器打开"功能.选择mxplayer free 与mxplayer pro都只会打开谷歌商店

### ISSUE THREAD

**Issue by hktrace** [cloudreve/Cloudreve#1327]
2个安卓11手机都测试了.无法在网页端选择用外部播放器调起mxplayer.
PC端调起 potplayer 正常,IOS端调起 nplayer 正常.
安卓端 下载 vlc  也可以调起.
只有mxplayer无法调起.点击使用mxplayer 就会跳转到谷歌商店中

**Comment by hktrace** [comment]
我去[mxplayer api ](https://sites.google.com/site/mxvpen/api?authuser=0)
查看了对呀的调起代码.然后经过测试..发现.要调用mxplayer必须带有视频or音频文件的后缀.不然无法调起.

**Comment by topjohncian** [comment]
Also, the preview api URL should end in the raw filename of files in specific situations (for example external office preview)
