### ISSUE TITLE
问下 储存策略 里面的 私有空间 选项是什么作用?

### ISSUE THREAD

**Issue by jinwyp** [cloudreve/Cloudreve#1328]
问下 储存策略 里面的 私有空间 选项是什么作用?  是否 私有空间 什么意思?

**Comment by jinwyp** [comment]
> 就是存储策略 的选择啊，自用就私有 需要公开访问 直链 就需要公共

什么意思? 
1 私有空间就不能用外链了?  那么 允许获取外链 那个选项是干啥的? 
2 这个私有空间 会控制能否外链? 允许获取外链 选项受到 私有空间控制? 如果 私有空间 为是 才可以 允许外链吗?

**Comment by Cloudreve-Pro-Provider** [comment]
你不要用专家模式编辑，你用向导模式，你应该就明白了。在专家模式下强行打开外链会让外链不可用。

**Comment by HFO4** [comment]
专家模式仅仅把所有存储策略设置项罗列出来，“私有空间”这一项并不是所有的存储策略类型都会使用。一般情况请使用向导模式。
