### ISSUE TITLE
webdav上传的文件大小能修改吗？

### ISSUE THREAD

**Issue by biliyaworld** [cloudreve/Cloudreve#1331]
群晖用Sync绑定webdav之后。貌似超过50MB的文件都会报文件大小超上限，无法上传。
有的修改吗。不晓得是群晖的问题，还是cloudreve要修改。

**Comment by HFO4** [comment]
检查下 cloudreve 外面的web服务器的上传限制。

**Comment by biliyaworld** [comment]
> 检查下 cloudreve 外面的web服务器的上传限制。

感谢，修改了PHP的上传限制就可以了。
