### ISSUE TITLE
有一个想法，多块硬盘，如何加到一个存储策略中

### ISSUE THREAD

**Issue by yz-qc** [cloudreve/Cloudreve#1332]
家里有好几块1T的硬盘，希望能够增加一个存储策略配置多块磁盘的功能

建议一个存储策略 增加多磁盘配置，上传的时候随机存储到对应磁盘或者做智能判断，存储到剩余容量较多的磁盘

由于数据库中是记录绝对路径的，所以也不存在取不到数据的情况，这个功能应该挺实用的，特别适合家里有多块硬盘闲置的情况，能够有效的利用起来

**Comment by HFO4** [comment]
可以添加多个存储策略对应多个磁盘。
如果需要为不同目录绑定不同存储策略，可以考虑捐助版。随机存储策略负载均衡有计划要做（不一定），但肯定只会加在捐助版里。

**Comment by GreenTeodoro839** [comment]
@yz-qc 用lvm系统整合硬盘，参考这个 https://hostloc.com/forum.php?mod=viewthread&tid=971814&highlight=1.6t

**Comment by yz-qc** [comment]
> @yz-qc 用lvm系统整合硬盘，参考这个 https://hostloc.com/forum.php?mod=viewthread&tid=971814&highlight=1.6t

谢谢，我用的是windows10做的部署，一般家用，没有多余的linux机器。。。。。不过根据你给的线索，查到了windows有一个动态磁盘，好像可以做到，打算试一下。。。。。再次感谢

**Comment by yz-qc** [comment]
> 可以添加多个存储策略对应多个磁盘。 如果需要为不同目录绑定不同存储策略，可以考虑捐助版。随机存储策略负载均衡有计划要做（不一定），但肯定只会加在捐助版里。

好的，了解过捐赠版，看起来捐赠版主要功能是集中在外部服务，用于盈利相关的。目前只打算自己家里用用，没有打算做收费网盘之类的服务，暂时好像还用不到，我试试 动态磁盘吧，谢谢

**Comment by MoeCinnamo** [comment]
可以搞软raid实现。

**Comment by jooler** [comment]
> > @yz-qc 用lvm系统整合硬盘，参考这个 https://hostloc.com/forum.php?mod=viewthread&tid=971814&highlight=1.6t
> 
> 谢谢，我用的是windows10做的部署，一般家用，没有多余的linux机器。。。。。不过根据你给的线索，查到了windows有一个动态磁盘，好像可以做到，打算试一下。。。。。再次感谢

windows支持存储池

**Comment by ELISHELL** [comment]
你可以和 minio 结合起来使用。使用s3挂在上。
