### ISSUE TITLE
webdav使用问题

### ISSUE THREAD

**Issue by yintao-xu** [cloudreve/Cloudreve#1333]
**Describe the bug**
用onedriveE5作为存储，挂载webdav，对里面的文件无法进行正常操作。
可以正常读取到文件目录，txt（1kb）文件可以正常打开，视频文件（8G）无法正常打开。
用的是nginx反代，里面已经加入配置client_max_body_size 20000M;
**To Reproduce**

**Expected behavior**
请问有解决办法吗？
**Screenshots**
![](https://s3.bmp.ovh/imgs/2022/06/06/30dbe1c8f6bf7bf2.png)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by yintao-xu** [comment]
![](https://s3.bmp.ovh/imgs/2022/06/06/a03d2278d409e915.png)
webdav，200多M的文件可以上传，但是下载不了

**Comment by xb2016** [comment]
@yintao-xu 请尝试使用 RaiDrive 挂载再进行测试

**Comment by yintao-xu** [comment]
> @yintao-xu 请尝试使用 RaiDrive 挂载再进行测试

![](https://s3.bmp.ovh/imgs/2022/06/06/0b6c64a1e3ca5349.png)
![](https://s3.bmp.ovh/imgs/2022/06/06/e7242bd645497948.png)
用raidrive连txt都下载不了。。

**Comment by xb2016** [comment]
嗯，试了下新版本 RaiDrive，确实出现了很多迷惑问题，还多了不能走本地代理这种迷惑设定。
可以试试 2021.5.20 版本的 RaiDrive，我这里测试是没有问题的。
![image](https://user-images.githubusercontent.com/31783875/172093526-c1257397-d06d-4f05-8c50-b2e54d716854.png)
视频打不开是 Windows 自带 Webdav 的问题，连接别的 dav 地址也一样无法打开视频。
你也可以试试找找看别的支持 Webdav 挂载软件。

**Comment by yintao-xu** [comment]
> 
用了2021.5.20 版本的 RaiDrive后问题解决，谢谢。

**Comment by cngege** [comment]
> > 
> 
> 用了2021.5.20 版本的 RaiDrive后问题解决，谢谢。

使用最新版本也可以解决
