### ISSUE TITLE
3.5.2pro版 有时候文件夹中文件数过多或者文件过大可能会引起“无法列取子文件”的错误

### ISSUE THREAD

**Issue by AlexWanghh2022** [cloudreve/Cloudreve#1334]
复现步骤：
1、准备两个大文件夹
<img width="306" alt="image" src="https://user-images.githubusercontent.com/106942721/172090026-f778f0a6-b885-47bd-8699-fc9a36fa27c5.png">
2、两个文件夹现在详细信息是正常的
<img width="242" alt="image" src="https://user-images.githubusercontent.com/106942721/172090080-bc00c529-baf4-42a5-8e66-914d16ad3742.png">
<img width="251" alt="image" src="https://user-images.githubusercontent.com/106942721/172090093-e22a08dd-3e4f-44f7-a305-b2ad5f8bde42.png">
3、将他们移到一个目录
<img width="256" alt="image" src="https://user-images.githubusercontent.com/106942721/172090128-c4af41f5-0a58-485a-8525-dac2b86064fa.png">
4、错误复现
<img width="264" alt="image" src="https://user-images.githubusercontent.com/106942721/172090153-221b6626-afdc-4d39-88cf-5221aa919004.png">
5、进入这个目录，这两个文件夹的详细信息都是正常的。
<img width="723" alt="image" src="https://user-images.githubusercontent.com/106942721/172090313-16391778-4633-4d33-a1f2-c2adc0452ce3.png">
<img width="897" alt="image" src="https://user-images.githubusercontent.com/106942721/172092107-ca26707b-09d5-4525-8fe2-8cc6f38801d5.png">

api请求是
<img width="515" alt="image" src="https://user-images.githubusercontent.com/106942721/172101378-99a66e8c-19ec-4bef-b54c-193d624aa2fe.png">

**Comment by AlexWanghh2022** [comment]
api请求是
<img width="515" alt="image" src="https://user-images.githubusercontent.com/106942721/172101378-99a66e8c-19ec-4bef-b54c-193d624aa2fe.png">

**Comment by MoeCinnamo** [comment]
这可能是硬盘的随机读写瓶颈，最好让cr支持分批读取应该就可以解决这个问题。

**Comment by AlexWanghh2022** [comment]
还有，这样会无法删除文件
<img width="566" alt="image" src="https://user-images.githubusercontent.com/106942721/172629917-b86fc0ae-f753-4c34-b847-30fb17208160.png">
我不理解，现在已经能够展示有几个项目了，已经列取子文件了，但是删除又提示“无法列取对象记录”

**Comment by MoeCinnamo** [comment]
> 还有，这样会无法删除文件
> <img alt="image" width="566" src="https://user-images.githubusercontent.com/106942721/172629917-b86fc0ae-f753-4c34-b847-30fb17208160.png">
> 我不理解，现在已经能够展示有几个项目了，已经列取子文件了，但是删除又提示“无法列取对象记录”

文件太多了。让cr实现每300扫描一次就可以解决文件多提示“无法列取对象记录”的问题；每300执行一次删除也可以解决无法删除的问题。强烈建议cr能使用分批读写来缓解这种问题。

**Comment by HFO4** [comment]
duplicated
