### ISSUE TITLE
增加一个IPFS的存储策略功能

### ISSUE THREAD

**Issue by MoeCinnamo** [cloudreve/Cloudreve#1335]
我希望在4.0的时候增加IPFS存储策略功能，进一步降低成本，增加用户体验。

IPFS是星际文件系统，和http以及其它oss存储策略不同，它采用无中心化；使用 ‘区块链‘ 和用户共享的 ‘有余’ 空间实现分布式存储，我希望增加一个IPFS存储策略，实现使用类似 ’小龙云盘‘ 的无总存储端的分布式网盘。

**Comment by MoeCinnamo** [comment]
是的，最好在离线下载里面支持下载磁力链接以及电驴。

**Comment by MoeCinnamo** [comment]
最好放在在 ‘存储策略’ 里面可以让管理员自主添加删除ipfs

**Comment by hiCasper** [comment]
目前IPFS受众应该还不是很多，可以考虑使用本地挂载IPFS后使用本地储存策略

**Comment by hhhkkk520** [comment]
支持增加ipfs储存策略

**Comment by MoeCinnamo** [comment]
> 

目前推荐直接在网盘内增加ipfs，本地挂载后太麻烦而且不能同步。

**Comment by whitiy666** [comment]
支持增加ipfs!

**Comment by kasuganosora** [comment]
支持增加ipfs!
