### ISSUE TITLE
视频外部播放器问题

### ISSUE THREAD

**Issue by yintao-xu** [cloudreve/Cloudreve#1336]
**Describe the bug**
因为有些视频在网页中不支持解码，所以就想用外部播放器播放。
看到有好多选项，其中windows平台用potplayer，可以正常播放视频；macos平台用iina一直错误。
iina已和youtube-dl插件配合。

**To Reproduce**

**Expected behavior**
请问有解决方法吗？
**Screenshots**
![](https://s3.bmp.ovh/imgs/2022/06/06/51a098ef17cecfe8.png)
![](https://dimg04.c-ctrip.com/images/0390j120009ifilgm9036.jpg)
![](https://edu-image.nosdn.127.net/EE94B73D6E24396C8C8A4F4FD545B2D4.png)
**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ChrisKimZHT** [comment]
iOS 端 VLC 可复现同样问题

**Comment by yixinin** [comment]
/api/v3/file/download/{key} 接口返回的url 没有将域名带上，可以由前端或后端修复。
