### ISSUE TITLE
关于创建分享链接和取消分享链接的需求建议==========

### ISSUE THREAD

**Issue by hiBenzhu** [cloudreve/Cloudreve#1338]
![img](https://tencent-qn-bucket-colorfulimage-cdn.deepgaze.com.cn/2022/06/07/629f52a4ee81b.png)

如图 希望可以将自动过期优化一下

使用时可以设置为**链接永久有效**，但是**下载n次以后**链接失效

还有这个下载次数和过期天数可以**自定义**，让用户自己填写

希望能实现以上需求

其次建议取消分享按钮点击时加入二次确认，有时候手滑一点就取消分享无法恢复！！

**Comment by MoeCinnamo** [comment]
还可以两个分开。也就是有: 1、永久有效但是下载足够次数后失效，2、几天后失效但是无限次数下载。
