### ISSUE TITLE
看起来不太适合pi玩

### ISSUE THREAD

**Issue by Canees** [cloudreve/Cloudreve#1341]
用webdav传贼慢，FRP转发也有6M带宽，按理不应该几KB的速度，
![image](https://user-images.githubusercontent.com/40012261/172582895-81df2d1c-1343-46f5-88d4-ee826ae55c3d.png)

**Comment by MoeCinnamo** [comment]
> 用webdav传贼慢，FRP转发也有6M带宽，按理不应该几KB的速度，
> ![image](https://user-images.githubusercontent.com/40012261/172582895-81df2d1c-1343-46f5-88d4-ee826ae55c3d.png)

这是pi的性能瓶颈问题，更好的cpu可以实现更好的效果，你可以试试用老的安卓手机可能效果会好一些。x86服务器效果是最好的。

**Comment by Canees** [comment]
> > 传贼慢，转向也有6M，用webd理理应该不应该几KB的速度，
> > ![图片](https://user-images.githubusercontent.com/40012261/172582895-81df2d1c-1343-46f5-88d4-ee826ae55c3d.png)
> 
> 这是最好的瓶颈问题，更好的cpu可以有更好的效果，你可以试试用老的安卓手机可能效果会好一些。x86服务器效果是性能的。
 
 rk3389 6核4G 不比安卓手机？我在本地测了硬盘读写稳定在100M左右

**Comment by MoeCinnamo** [comment]
> > > 传贼慢，转向也有6M，用webd理理应该不应该几KB的速度，
> > > ![图片](https://user-images.githubusercontent.com/40012261/172582895-81df2d1c-1343-46f5-88d4-ee826ae55c3d.png)
> > 
> > 
> > 这是最好的瓶颈问题，更好的cpu可以有更好的效果，你可以试试用老的安卓手机可能效果会好一些。x86服务器效果是性能的。
> 
> rk3389 6核4G 不比安卓手机？我在本地测了硬盘读写稳定在100M左右

那我不清楚了，试试用更好的cpu。pi的性能并没有x86服务器更好。

**Comment by mritd** [comment]
@MoeCinnamo 你可以给出完整的测试环境, 例如 设备型号、系统、网络环境、软件版本、复现方式; 这样可以方便有相关设备的人进行测试和排查问题. 如果没有这些必要信息我也可以讲是因为你的显示器有问题(对的, 很无厘头).

**Comment by MoeCinnamo** [comment]
> @MoeCinnamo 你可以给出完整的测试环境, 例如 设备型号、系统、网络环境、软件版本、复现方式; 这样可以方便有相关设备的人进行测试和排查问题. 如果没有这些必要信息我也可以讲是因为你的显示器有问题(对的, 很无厘头).

我使用的是 志强1230(可能是)、Centos 7系统、1000MB光纤宽带、最新的CR、直接安装就可以，它没有问题。你应该去找 @[Canees](https://github.com/Canees)
