### ISSUE TITLE
[BUG] 从外部目录导入失败

### ISSUE THREAD

**Issue by z0z0r4** [cloudreve/Cloudreve#1343]
疑似由于文件过大，导入的文件为18G
![image](https://user-images.githubusercontent.com/78744121/172782379-d2846286-1409-446d-8491-88f59e2cbb34.png)

持久任务显示完成
![image](https://user-images.githubusercontent.com/78744121/172781937-e1455fcb-60be-43ca-be07-c2c1dd8f8c6c.png)

但无法下载该文件
![image](https://user-images.githubusercontent.com/78744121/172782461-18c79a76-1d0f-4c99-94c8-d24665b4a3b4.png)
![image](https://user-images.githubusercontent.com/78744121/172782514-947ae4e9-8a31-4295-804d-2e586d4b6c05.png)

**Comment by z0z0r4** [comment]
其他文件可以下载，导入小文件可以下载，疑似由于文件过大
世纪互联存储

**Comment by z0z0r4** [comment]
存储空间未满
![image](https://user-images.githubusercontent.com/78744121/172782894-99f1b1a3-f545-4dbd-99f9-f5096c277b30.png)

**Comment by MoeCinnamo** [comment]
确实是因为文件过大导致的虚假上传，也就是显示上传成功但是实际上并没有成功上传导致无法获取文件外链导致的无法下载。直接下载以及分享链接理论上都无法下载的。

**Comment by z0z0r4** [comment]
这个问题，未来有可能修复吗（

**Comment by HFO4** [comment]
> 确实是因为文件过大导致的虚假上传，也就是显示上传成功但是实际上并没有成功上传导致无法获取文件外链导致的无法下载。直接下载以及分享链接理论上都无法下载的。

你这说的是啥….我咋看不懂



> 这个问题，未来有可能修复吗（

不确定原因，需要开启debug模式看下错误信息

**Comment by MoeCinnamo** [comment]
> > 确实是因为文件过大导致的虚假上传，也就是显示上传成功但是实际上并没有成功上传导致无法获取文件外链导致的无法下载。直接下载以及分享链接理论上都无法下载的。
> 
> 你这说的是啥….我咋看不懂
> 
> > 这个问题，未来有可能修复吗（
> 
> 不确定原因，需要开启debug模式看下错误信息

就是实际上显示上传成功，但是目录里面根本没有这个文件。
