### ISSUE TITLE
请问离线下载是否能支持同时下载和上传呢？

### ISSUE THREAD

**Issue by AHCorn** [cloudreve/Cloudreve#1346]
目前离线下载功能是全部下载完成后才开始转存，但受限于硬盘空间，很多较大的磁力都没法下载
比如我想下载一部动画片的BD版，能否在下载完成一集以后就自动上传一集，以腾出空间来下载后面的部分呢？

**Comment by AlexWanghh2022** [comment]
你指的是包含多个文件的种子吗？
如果是一个一个链接的目前是可以的

**Comment by AHCorn** [comment]
> 你指的是包含多个文件的种子吗？ 如果是一个一个链接的目前是可以的

是的，我指的就是包含多个文件的种子，因为必须文件全部下载完成才能开始上传，所以一些较大的种子就没法下载了

**Comment by AlexWanghh2022** [comment]
嗯，这个需要优化

**Comment by MoeCinnamo** [comment]
包含多个文件的种子在本地好像也并不能拆开一个一个下载，这和aria2有关。网盘系统确实可以拆开发送给aria2。

**Comment by lsCoding666** [comment]
如果只是个人使用的话，下载美剧或者是一些电影的话，我建议使用pikpak，磁力可以直接秒传到网盘，打折的时候也不贵。如果还想转存到cloudreve的话，可以获取下载直链再在cloudeve里添加离线下载，或者用自己电脑下载好再传到cloudreve所绑定的存储策略上再导入。pikpak不限速。

**Comment by AHCorn** [comment]
感谢您的推荐，但Pikpak目前支持的客户端还是比较有限，网页端也有很多限制，而我个人是比较喜欢用电脑来看的，所以主要还是用转存到Onedrive的方式来看。
但限速方面其实还是有的，只是也算良心的了，免费用户和付费用户都是6M每秒。
![图片](https://user-images.githubusercontent.com/42889600/180361526-4b683f2b-3709-4f3e-a512-7df8943f4375.png)
