### ISSUE TITLE
如果可以的话，onedrive的缩略图搞个在本地生成缩略图的功能

### ISSUE THREAD

**Issue by Shizuri23** [cloudreve/Cloudreve#1347]
如标题，有些图片大了，看个缩略图跟看原图一样慢，这不太方便....

**Comment by MoeCinnamo** [comment]
与onedrive链接速度有关，与看缩略图原图无关。网盘本地是有缓存的，只有第一次看速度才会慢，实际上后来速度基本上会快一些。
