### ISSUE TITLE
有关webdav的问题，mac下复制东西会生成_AppleDouble文件，希望能够提供一个设置

### ISSUE THREAD

**Issue by Shizuri23** [cloudreve/Cloudreve#1348]
有关webdav的问题，mac下复制东西会生成_AppleDouble文件，希望能够提供一个设置
<img width="518" alt="image" src="https://user-images.githubusercontent.com/46082179/173050980-0b8a04aa-3d72-45d1-8d29-e6929597a667.png">

**Comment by MoeCinnamo** [comment]
这是mac系统的问题，将文件复制到U盘后将这个U盘放在win系统下也会显示_AppleDouble文件。无法提供设置，只能通过网盘内默认隐藏以 ‘ . ’ 开头的文件解决。
