### ISSUE TITLE
拖入多文件上传时，上传速度很慢

### ISSUE THREAD

**Issue by yz-qc** [cloudreve/Cloudreve#1351]
尝试过如下情况：
1、单独拖入一个文件，上传文件达到带宽条件，上传速度有10~50M挑动，均速有30M左右
2、拖入多个文件，同时上传数设置5，上传速度  几百K，偶尔有1M
3、拖入多个文件，同时上传数设置1，上传速度  几百K到1M左右
明显速度限制非常大，都是本地上传的，不知道为什么会有这么大的差距

**Comment by topjohncian** [comment]
提供一下储存策略类型

**Comment by yz-qc** [comment]
> 提供一下储存策略类型
你好，这是我的存储策略
![image](https://user-images.githubusercontent.com/25973252/173210554-aa4b32c7-26d1-4697-a02a-6363f604afb2.png)
![image](https://user-images.githubusercontent.com/25973252/173210565-05982a58-e6cb-40b6-86f3-88116dfaab9e.png)

**Comment by MoeCinnamo** [comment]
本地存储策略与磁盘速度有关。由于多个文件同时上传，导致磁盘速度可能会稍微降低，属于正常现象。

**Comment by yz-qc** [comment]
> 本地存储策略与磁盘速度有关。由于多个文件同时上传，导致磁盘速度可能会稍微降低，属于正常现象。

不不不，你可能没有仔细看我的问题，多文件上传，同时上传只能1个文件的时候，速度也是上不去的。。。。只能是单独拖一个文件的时候，速度才正常。。。。而且，速度能差几十倍，个人觉得不太可能是磁盘的问题，我硬盘拷贝文件，单文件速度能保持再60~90M，多文件也有20~30M，差个1、2倍，不可能差个几十倍的。。。

**Comment by MoeCinnamo** [comment]
> > 本地存储策略与磁盘速度有关。由于多个文件同时上传，导致磁盘速度可能会稍微降低，属于正常现象。
> 
> 不不不，你可能没有仔细看我的问题，多文件上传，同时上传只能1个文件的时候，速度也是上不去的。。。。只能是单独拖一个文件的时候，速度才正常。。。。而且，速度能差几十倍，个人觉得不太可能是磁盘的问题，我硬盘拷贝文件，单文件速度能保持再60-90M，多文件也有20-30M，差个1、2倍，不可能差个几十倍的。。。

这确实有可能是个bug，听听A大怎么说

**Comment by yz-qc** [comment]
没有人遇到相同的情况吗？

**Comment by MoeCinnamo** [comment]
> 没有人遇到相同的情况吗？

我没遇到

**Comment by yz-qc** [comment]
> 如果是几十M量级的话，没遇到过，也不应该如此。
> 
> 如果按磁盘速度测试： ![ssd](https://user-images.githubusercontent.com/31783875/174537009-f967a100-a17b-45f4-b010-6f5af2ef6791.gif) [ ](https://user-images.githubusercontent.com/31783875/174537009-f967a100-a17b-45f4-b010-6f5af2ef6791.gif) ![ssd](https://user-images.githubusercontent.com/31783875/174537009-f967a100-a17b-45f4-b010-6f5af2ef6791.gif) [ ](https://user-images.githubusercontent.com/31783875/174537009-f967a100-a17b-45f4-b010-6f5af2ef6791.gif) ![hdd](https://user-images.githubusercontent.com/31783875/174537021-e72683a2-a902-4372-a332-07e7f9322eb4.gif) [ ](https://user-images.githubusercontent.com/31783875/174537021-e72683a2-a902-4372-a332-07e7f9322eb4.gif) ![hdd](https://user-images.githubusercontent.com/31783875/174537021-e72683a2-a902-4372-a332-07e7f9322eb4.gif) [ ](https://user-images.githubusercontent.com/31783875/174537021-e72683a2-a902-4372-a332-07e7f9322eb4.gif) 上面两张图使用的 V1 V2 两个文件完全相同 第一张图是SSD，两个文件上速度相同（按GIF帧数计，Cloudreve 显示速度不准） 第二张图是HDD，明显可见第二个文件降速相当严重

两个文件可能不太好重现（有缓存），我又重现了一下，HDD，第一个文件传完后，后面的文件速度就上不来的
![1](https://user-images.githubusercontent.com/25973252/174705172-4fedb3cf-9be0-4a12-8369-b176e0d05849.gif)
![2](https://user-images.githubusercontent.com/25973252/174705193-258a93e0-69e4-4645-8e14-926c6b9de796.gif)
上面两张图，文件内容全部都一样
第一张是单文件，速度正常
第二张是9个文件，多文件上传，当第一个文件上传完之后，后面的文件速度就起不来。。。而且实际应用中我上传几十个文件，连第一个文件都是没有速度的，应该是上传的逻辑存在bug，不会提速

**Comment by xb2016** [comment]
机械盘就这样，哪怕你一个个传，第一个传完马上选第二个，速度也一样上不去。看资源管理器可以发现，一个文件传完后磁盘还是有相当高的占用，速度根本上不去。

**Comment by yz-qc** [comment]
> 机械盘就这样，哪怕你一个个传，第一个传完马上选第二个，速度也一样上不去。看资源管理器可以发现，一个文件传完后磁盘还是有相当高的占用，速度根本上不去。

我本地自己拷贝过的，第一个传完，第二个速度一会后就上去了，这里是一直上不去。。。。前后相差几十倍，为此我特意在两个磁盘中复制粘贴测试过

**Comment by hanqingwu** [comment]
试下观察下，出现降速时  磁盘的负载是不是很大

**Comment by HFO4** [comment]
> 3、拖入多个文件，同时上传数设置1，上传速度 几百K到1M左右

多文件是指多少个文件？只有两三个文件也会有这种情况吗？
