### ISSUE TITLE
希望能支持关闭外链鉴权

### ISSUE THREAD

**Issue by imouup** [cloudreve/Cloudreve#1352]
我感觉加上鉴权内容导致外链过长了，而且迁移过程中容易导致旧外链失效

**Comment by topjohncian** [comment]
回复第二点，请携带 conf.ini 迁移

**Comment by MoeCinnamo** [comment]
无鉴权内容无法确定是否为同一账号所为。迁移请携带 conf.ini 文件让网盘本身的密钥不丢失即可修复旧外链失效问题。建议降低鉴权内容文字数量，将鉴权内容移入文件类型以及文件名前，可以保证外链更加稳定。
