### ISSUE TITLE
不支持通配证书

### ISSUE THREAD

**Issue by laoxiao789** [cloudreve/Cloudreve#1353]
发现了一个问题。cloudreve 3.5.3 貌似不支持通配证书
比如说*.abc.com 证书 如果访问web.abc.com 是一个网站，pan.abc.com 是网盘！访问过pan.abc.com 无法访问web.abc.com还是显示pan.abc.com页面

**Comment by topjohncian** [comment]
建议先理解一下基础知识

**Comment by GreenTeodoro839** [comment]
@laoxiao789 只使用cloudreve一个机器只能搭建一个网盘，如果有多网站需求需要用nginx

**Comment by laoxiao789** [comment]
> @laoxiao789 只使用cloudreve一个机器只能搭建一个网盘，如果有多网站需求需要用nginx

我说的当然是cloudreve 被reverse proxy啊
