### ISSUE TITLE
上传文件一直失败,不是网络错误就是这个,确定网络是好的

### ISSUE THREAD

**Issue by JerryLiew** [cloudreve/Cloudreve#1355]
![image](https://user-images.githubusercontent.com/51161678/173243336-95f1cd89-085c-464b-8ba9-1f8a9f1c6899.png)

**Comment by hiCasper** [comment]
可以使用F12查看一下Network页面分片上传后的返回数据

**Comment by MoeCinnamo** [comment]
我这里也出现了http错误，一般只有在上传大文件时才会出现。

**Comment by HFO4** [comment]
可能被外部应用防火墙拦截了

**Comment by MoeCinnamo** [comment]
> 可能被外部应用防火墙拦截了

这确实是一方面
