### ISSUE TITLE
反应两个BUG

### ISSUE THREAD

**Issue by setube** [cloudreve/Cloudreve#1357]
我后台设置的策略是游客也可以下载文件
1.当访问网盘分享链接的时候,如果当前用户信息失效后,会跳转到登录,那我为什么还要设置游客下载
2.当访问网盘分享链接的时候,如果当前用户信息失效后,会跳转到登录,登录之后页面并没有跳转到下载页面,而是网盘目录

这俩问题,很影响用户体验

**Comment by MoeCinnamo** [comment]
这确实是bug。第一个应该通过检查游客下载是否设置来操作是下载还是跳转。而第二个登录完如果有分享链接后缀则直接跳转到分享链接。

**Comment by MoeCinnamo** [comment]
这bug可以让作者修复
