### ISSUE TITLE
在openwrt 上运行 arm64 位出错

### ISSUE THREAD

**Issue by feng-ming** [cloudreve/Cloudreve#1359]
1. 下载最新版本
2. 执行./cloudreve
3. 出现如下错误
`./cloudreve: error while loading shared libraries: libdl.so.2: cannot open shared object file: No such file or directory`

**Comment by feng-ming** [comment]
通过strace 看了，系统没有/lib64的目录出错导致。
是部署在华硕ac86u的路由中，cpu 架构是 armv7

**Comment by vvisionnn** [comment]
Please, follow the bug report template, provide what version of Cloudreve you have downloaded (full name), version number, what kind of arch you have downloaded

**Comment by vvisionnn** [comment]
I think from the title, you are using the `arm64` version, but your device is `armv7` please try download the `arm` version from the release
