### ISSUE TITLE
Add archive method for uploading a folder into Cloudreve

### ISSUE THREAD

**Issue by benpar2** [cloudreve/Cloudreve#1361]
I use Cloudreve as a storage server. When downloading a folder in the Cloudreve environment, before sending the folder to the user, Cloudreve archive the folder and then send it to the user. But it doesn't have this feature for uploading a folder. Especially when we upload a folder with small files (in KB) the uploading speed is terrible.
My idea is to add an archive feature to the Couldreve, and when the user uploads a folder to the storage, before uploading it, the archiving process should be done, then sending the archive to the server, and in the storage, the archived uploaded folder would be de-archive and then store as a folder (not archived) in the panel.
If you add this feature to the Cloudreve, it will be great!

**Comment by HFO4** [comment]
You can upload the folder archive file (.zip), then decompress it in Cloudreve.
