### ISSUE TITLE
下载报错,您要找的资源已被删除、已更名或暂时不可用

### ISSUE THREAD

**Issue by zhLoser01** [cloudreve/Cloudreve#1365]
能上传文件，上传的文件在服务器/uploads/1或 /uploads/2 目录下，下载文件失败提示您要找的资源已被删除、已更名或暂时不可用
![1655709855739](https://user-images.githubusercontent.com/23304686/174547374-75e1f5dc-958e-4c62-8548-0cea2f86bab9.png)
。

**Comment by TheresaQWQ** [comment]
@zhLoser01 请参考文档配置rewrite

**Comment by zhLoser01** [comment]
windows版本和linux版本都试过了，都是这个错
![1655710104388](https://user-images.githubusercontent.com/23304686/174549266-9f30c18f-143c-47af-93b3-a331be5db781.png)
误

**Comment by zhLoser01** [comment]
![1655713066270](https://user-images.githubusercontent.com/23304686/174557119-f4498878-151a-4930-bd69-ec52707da153.png)
是这个conf.ini配置文件吗，里面没有rewrite这个配置

**Comment by HFO4** [comment]
检查站点URL设置。
