### ISSUE TITLE
用户在登录时发生串号。

### ISSUE THREAD

**Issue by awslxm** [cloudreve/Cloudreve#1368]
部署环境:centos7.9
数据库类型:SQlite
软件版本:3.5.3pro
错误:登录系统发生异常,用户在登录时有几率发生串号。用户在登录的时候有几率登上别人的账号。可能是3.5.0的时留下来的bug,在后续运作中bug引发了问题。

**Comment by HFO4** [comment]
检查上层 CDN 或 Web 服务器缓存设置。
