### ISSUE TITLE
因 MAX_PATH 限制导致的离线下载失败

### ISSUE THREAD

**Issue by xb2016** [cloudreve/Cloudreve#1373]
Windows PATH 限制为 260 字符，一旦离线下载路径超过该限制将无法下载，提示 _Failed to open the file xxxxx, cause: The system cannot find the path specified._

我尝试将下载目录设置为根目录，将路径缩为最短，但仍无法解决此问题：
![image](https://user-images.githubusercontent.com/31783875/175525972-b3057d7f-2c94-494c-b1d6-56eacd7c540d.png)

**已尝试按微软文档修改组策略/注册表解除限制，结果为无效，从系统层面暂未找到方法。** 故期望从 Cloudreve 方面改进。

Cloudreve 在下载时会创建一个 `aria2/UUID v4` 文件夹，UUID 占用的 36 个字符对于 260 这一限制来说有点过大了。

如果只是用于区分**同时下载**中的任务，没有必要使用 UUID。同时它还会大量占用数据库空间，一个 500 个文件的 BT 任务就意味着这段 UUID 要重复 500 次。

建议使用 8 字符或更少字符的随机字符串替代 UUID。

以及下载出错的任务在 aria2 不会删除，这是否为 bug？

**Comment by xb2016** [comment]
@MoeCinnamo 什么叫 加个限制项

**Comment by MoeCinnamo** [comment]
> @MoeCinnamo 什么叫 加个限制项

就是在UUID占用的字符变得更少一些，而并不是用以前太长的UUID。
