### ISSUE TITLE
离线下载有概率出现    1 个任务创建失败：   提示

### ISSUE THREAD

**Issue by qitayun** [cloudreve/Cloudreve#1374]
离线下载的链接包含特殊字符等会出现该情况

实测直接复制到ariang里面是可以离线的

实测pro和开源版均有该bug

例
https://正常的英文域名/api/v3/file/source/1/AMVTzo1o_%28%29%

我猜是%的锅

但是据亿安云说，正常的链接也有概率复现该问题

让他来说明一下情况吧

**Comment by qitayun** [comment]
你们没有人出现相同的问题吗

**Comment by MoeCinnamo** [comment]
尝试使用正常的英文字符作为文件名，它只是因为无法进行正常的解码造成。

**Comment by qitayun** [comment]
> 尝试使用正常的英文字符作为文件名，它只是因为无法进行正常的解码造成。

并不是 以前的版本没有这个bug
高频复现

**Comment by xb2016** [comment]
能否提供一个能稳定复现的链接？

**Comment by qitayun** [comment]
> https://正常的英文域名/api/v3/file/source/1/AMVTzo1o_%28%29%

https://baidu.com/api/v3/file/source/1/AMVTzo1o_%28%29%

**Comment by qitayun** [comment]
> 能否提供一个能稳定复现的链接？

https://baidu.com/api/v3/file/source/1/AMVTzo1o_%28%29%
