### ISSUE TITLE
存储策略为onedrive的webdav错误及路径的问题

### ISSUE THREAD

**Issue by ucaec** [cloudreve/Cloudreve#1375]
1. 存储策略是onedrive，webdav能上传，能读取路径、文件名，不能打开文件，提示 WebDAV资源被移到了'https://~~~~~~~.sharepoint.com/personal/~~~~~~~，实际上这个地址是能直接在浏览器下载文件的。

2. webdav的路径问题，账号管理中设置的根目录为/webdav_linux，然后挂载为/ubuntu/web，通过webdav上传文件1.txt到/ubuntu/web/test，另外在cloudreve网页端上传文件2.txt到/webdav_linux/test。在cloudreve中，两个文件的路径分别为/webdav_linux/test/1.txt    和   /webdav_linux/test/2.txt ， 但是在onedrive中，两个文件的路径分别为~~~/test/1.txt  ~~~/webdav_linux/test/2.txt

版本：3.5.3， 挂载工具 davfs2 Winscp

**Comment by HFO4** [comment]
这俩都是预期结果。
第二个是因为 `path` 魔法变量表示的就是用户的虚拟目录。
第一个是因为你的 WebDAV 客户端不支持重定向。

**Comment by wicecoffeey** [comment]
兄弟有办法解决吗
