### ISSUE TITLE
cloudreve上传文件时发生此错误

### ISSUE THREAD

**Issue by larryxiaoyuzhe** [cloudreve/Cloudreve#1378]
错误如下：
无法解析响应: Unexpected token < in JSON at position 0 (<html> <head><title>413 Request Entity Too Large</title></head> <body> <center><h1>413 Request Entity Too Large</h1></center> <hr><center>nginx/1.20.1</center> </body> </html>       )
![Screenshot_20220629_154856_com huawei browser](https://user-images.githubusercontent.com/104183262/176381684-5604c6e0-6945-4159-af65-f642dd35191a.jpg)

**Comment by Master-ZR** [comment]
反代的问题，添加一个client_max_body_size
location / { 
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_redirect off;
                proxy_pass http://127.0.0.1:5212;
                client_max_body_size 1024G;
            }
