### ISSUE TITLE
离线下载由于Aria2的ssl证书更新导致x509报错（已解决）

### ISSUE THREAD

**Issue by kcn3388** [cloudreve/Cloudreve#1383]
**bug描述**
由于ssl证书到期，我为Aria2的ssl证书进行了更换，但是导致离线下载报错：
x509: certificate signed by unknown authority
取消Aria2的ssl配置就不会出现这个问题，请问如何解决？

**截图如下**
![image](https://user-images.githubusercontent.com/25716090/177095679-a9b4bda7-cc27-4072-9aef-7e28c1172e3c.png)

**运行设备如下**
 - OS: Ubuntu 18.04 LTS
 - Device: Vultr cloud compute
 - Browser: Microsoft Edge

**Comment by MoeCinnamo** [comment]
目前对于证书更换后需要重新进行aria2初始化，最好不要使用证书，或者尝试续签证书，而不是让它过期。

**Comment by kcn3388** [comment]
> 目前对于证书更换后需要重新进行aria2初始化，最好不要使用证书，或者尝试续签证书，而不是让它过期。

已解决，目前是通过将域名的ssl证书所属组织的根证书添加到系统内即可解决。
个人猜测：
1、我的ssl证书所属机构是TrustAsia（亚洲诚信），其证书默认情况下会被视为不安全/不可信证书；
2、ssl证书过期后无需初始化aria2，仅需在配置文件内修改证书即可
