### ISSUE TITLE
反馈个问题

### ISSUE THREAD

**Issue by SeTube** [cloudreve/Cloudreve#1384]
多文件同时上传只有等文件全部上传完毕之后文件列表才会刷新,这里逻辑是不是有点问题
按理来说应该是上传成功一个文件就刷新列表而不是等全部上传完才刷新列表,望修复

**Comment by xb2016** [comment]
@SeTube 我倒觉得这是个预期行为，如果上传的都是小文件，频繁的刷新列表体验会跟糟糕；此外上传过程中还是可以浏览其它文件夹的，刷新这一操作我觉得并不重要

**Comment by MoeCinnamo** [comment]
> @SeTube 我倒觉得这是个预期行为，如果上传的都是小文件，频繁的刷新列表体验会跟糟糕；此外上传过程中还是可以浏览其它文件夹的，刷新这一操作我觉得并不重要

是的，我认为可以尝试实时显示，无需刷新，上传完毕后自动消失。
