### ISSUE TITLE
[BUG] 文本编辑器 图片子菜单不显示

### ISSUE THREAD

**Issue by xb2016** [cloudreve/Cloudreve#1385]
预期应如下
![image](https://user-images.githubusercontent.com/31783875/177491631-5072e44a-0cd0-423d-8b25-2f5a7ca6f969.png)

**Comment by MoeCinnamo** [comment]
无计划，GitHub也并不会现实图片子菜单。

**Comment by xb2016** [comment]
@MoeCinnamo 你在说什么

**Comment by HFO4** [comment]
@MoeCinnamo 没必要定期挨个把issue轰炸一遍然后回复一大堆你的见解，更何况你这一堆评论都是错的，没有任何帮助。

**Comment by MoeCinnamo** [comment]
> @MoeCinnamo 没必要定期挨个把issue轰炸一遍然后回复一大堆你的见解，更何况你这一堆评论都是错的，没有任何帮助。

对于轰炸来说，我认为它并不是。而这一堆评论确实有可能是错的或者是不太完全的，我会进行修改的，感谢你的回复。
