### ISSUE TITLE
aria2下载磁力速度慢的问题

### ISSUE THREAD

**Issue by dfmjndm** [cloudreve/Cloudreve#1386]
希望可以增加添加外部的qbittorrent选项用来处理磁力文件，aria2的磁力下载效率太低了

**Comment by lsCoding666** [comment]
bitcomet我记得有远程下载功能的 
https://www.daxiaamu.com/6959/
![Video_20220606_112824_807](https://user-images.githubusercontent.com/73888354/177965645-8cfefde5-d35d-4a73-aef2-c1c3fe9f0d68.gif)
