### ISSUE TITLE
使用阿里云作为存储策略时报NoSuchUpload错误

### ISSUE THREAD

**Issue by ppamos** [cloudreve/Cloudreve#1388]
![企业微信截图_16572619792401](https://user-images.githubusercontent.com/48974977/177931085-6d93f3f5-c285-4501-82f3-b5fc9ea88521.png)
![企业微信截图_16572620742336](https://user-images.githubusercontent.com/48974977/177931328-a2147924-d9be-4ea0-99e8-69c92015454b.png)

**Comment by lsCoding666** [comment]
404了 上传url有问题

**Comment by lsCoding666** [comment]
试试传个50mb左右的文件并将文件分片大小设置为默认。因为阿里云的分片上传要求除了最后一片之外的每片都得大于100kb。我不清楚一个32kb的文件虽然符合这个标准，但是不知道会不会出什么问题

**Comment by HFO4** [comment]
回调失败，检查是不是套了CF，网站能不能被公网访问，站点URL对不对。

**Comment by Dragon-Fish** [comment]
Encountered the same issue

**screenshot**

![](https://user-images.githubusercontent.com/44761872/181934269-c96cdd32-4e39-4827-84de-8ee69fc0250a.png)

**server side log**

```
[Warning] 2022-07-31 01:06:45 无法取消 [Avatar.jpg] 的上传会话: oss: service returned error: StatusCode=404, ErrorCode=NoSuchUpload, ErrorMessage="The specified upload does not exist. The upload ID may be invalid, or the upload may have been aborted or completed.", RequestId=62E565251AFF6534346614FE
```

**Comment by Dragon-Fish** [comment]
Re: [https://github.com/cloudreve/Cloudreve/issues/1388#issuecomment-1200258190](https://github.com/cloudreve/Cloudreve/issues/1388#issuecomment-1200258190)

此问题已解决：若使用 Cloudflare DNS，需要关闭代理。

@HFO4 希望可以优化使用 Cloudflare 代理时遇到的此类问题，否则容易暴露源服务器地址
