### ISSUE TITLE
无法加载favicon.ico

### ISSUE THREAD

**Issue by YHYJ** [cloudreve/Cloudreve#1389]
**Describe the bug**
Nginx正确配置了静态资源加载，但是部署的Cloudreve子站还是加载不了favicon（其他子站可以），F12报错500

**Comment by xvzhenduo** [comment]
![image](https://user-images.githubusercontent.com/74353173/178763437-363e4036-41be-4f84-aafa-c3a899dd7192.png)
![image](https://user-images.githubusercontent.com/74353173/178763624-8c91b16c-ee8e-4cb8-bbc3-893b73cfae94.png)
我这里，清了一下缓存没有问题，你可以看图片都不是从磁盘缓存载入的，应该是你配置的问题，你可以截图发一下chrome开发者工具(或者其他的浏览器的开发者工具)favicon.ico的标头和响应信息

**Comment by YHYJ** [comment]
我更新了nginx已经好了，感谢
