### ISSUE TITLE
通过web删除文件后，硬盘上的文件夹还在（文件被清空）这是预期行为吗？

### ISSUE THREAD

**Issue by baloyou** [cloudreve/Cloudreve#1390]
通过内置的web管理界面。

**Comment by xvzhenduo** [comment]
应该是预期行为，有很多人提过但是一直没修(实际上也没法修因为使用魔法变量配置的路径，不一定是物理路径，在删除文件时不可能每次都检查每级父级文件夹是否为空，这样太浪费资源了，而且没什么太大用处)
