### ISSUE TITLE
通过web界面上传大量文件时（整个目录）会出现大面积上传失败的情况

### ISSUE THREAD

**Issue by baloyou** [cloudreve/Cloudreve#1391]
一次性选择了300多个GB的文件，大概有上千个文件，刚开始很不错，很快就批量报错。

但是网络一直是稳定的（内网电脑）路由器也还不错。

<img width="468" alt="image" src="https://user-images.githubusercontent.com/5190664/177975998-907b6f61-6b77-43ad-82e2-3ba968fac79e.png">

**Comment by baloyou** [comment]
居然是机械硬盘的锅，换到另一个固态硬盘上写入就正常。
有待继续测试。

**Comment by xb2016** [comment]
感觉可以和 #1351 归为同一 case
