### ISSUE TITLE
能否加入单设备同时下载数量限制（否则用户过多下载会被三方限制）

### ISSUE THREAD

**Issue by Gitcqs** [cloudreve/Cloudreve#1394]
能否加入单设备同时下载数量限制，如果多个用户，甚至只需一个用户过多下载会被三方限制，
<img width="727" alt="截屏2022-07-10 18 07 08" src="https://user-images.githubusercontent.com/12613289/178140517-49cba9c6-9e43-4914-b610-7f961bac3d11.png">
用户过多下载，会触发流量控制限制，已onedrive 为例，一定时间过多下载，会被服务终止无法正常使用（限制刚恢复忘了截图

希望能添加个单设备同时下载数量限制功能，这应该是大规模用户应用十分必要的功能

**Comment by xb2016** [comment]
@Gitcqs 同 #1288 实际不可控

**Comment by Gitcqs** [comment]
> @Gitcqs 同 #1288 实际不可控

可是用户每次下载前都进入下载页面，需要点击按钮来下载的，如果非直链应该可以在真正下载前检查和限制的

**Comment by xvzhenduo** [comment]
> > @Gitcqs 同 #1288 实际不可控
> 
> 可是用户每次下载前都进入下载页面，需要点击按钮来下载的，如果非直链应该可以在真正下载前检查和限制的

第三方的储存下载是通过跳转直链下载实现的，在浏览器的下载管理页面是可以显示直链的，在直链的有效期内用户可以使用这个链接反复下载，所以不可控

**Comment by Gitcqs** [comment]
> > > @Gitcqs 同 #1288 实际不可控
> > 
> > 
> > 可是用户每次下载前都进入下载页面，需要点击按钮来下载的，如果非直链应该可以在真正下载前检查和限制的
> 
> 第三方的储存下载是通过跳转直链下载实现的，在浏览器的下载管理页面是可以显示直链的，在直链的有效期内用户可以使用这个链接反复下载，所以不可控

我明白意思，用户获取直链后就不可控。这里意思是我一分享链接内文件夹有多个资源，用户短期时间同时获取多个文件直链并下载，能不能限制这个。我理解这里不可控是不是因为无法获取文件下载状态，无法知道用户此刻哪些任务正在下载中，如果知道下载状态应该可以限制获取新下载直链的动作？

**Comment by xvzhenduo** [comment]
> > > > @Gitcqs 同 #1288 实际不可控
> > > 
> > > 
> > > 可是用户每次下载前都进入下载页面，需要点击按钮来下载的，如果非直链应该可以在真正下载前检查和限制的
> > 
> > 
> > 第三方的储存下载是通过跳转直链下载实现的，在浏览器的下载管理页面是可以显示直链的，在直链的有效期内用户可以使用这个链接反复下载，所以不可控
> 
> 我明白意思，用户获取直链后就不可控。这里意思是我一分享链接内文件夹有多个资源，用户短期时间同时获取多个文件直链并下载，能不能限制这个。我理解这里不可控是不是因为无法获取文件下载状态，无法知道用户此刻哪些任务正在下载中，如果知道下载状态应该可以限制获取新下载直链的动作？

我不知道我没有理解你的意思，你说的应该是要限制获取文件直链的个数，也就是限制一定时间内用户可以下载文件的个数，但是这样并没有太大用处，因为第三方储存大部分都是根据流量来限制的，但没有办法可以确定用户是不是下载到一半取消了，或者是恶意下载了几十次，这样没有办法准确统计下载的流量，不能防止别人恶意消耗流量

**Comment by Gitcqs** [comment]
> 

ok，第三方储存大部分都是根据流量来限制的，但目前遇到限制大多都是短期获得过多下载链接造成的，用户不是重复刷一个下载链接而是短时间，甚至一秒点一个下载文件，有没有可能限制一定时间内获取的下载链接数，相当一个获取新下载的 rate limit（个人感觉应该有用

**Comment by Gitcqs** [comment]
> > > > > @Gitcqs 同 #1288 实际不可控
> > > > 
> > > > 
> > > > 可是用户每次下载前都进入下载页面，需要点击按钮来下载的，如果非直链应该可以在真正下载前检查和限制的
> > > 
> > > 
> > > 第三方的储存下载是通过跳转直链下载实现的，在浏览器的下载管理页面是可以显示直链的，在直链的有效期内用户可以使用这个链接反复下载，所以不可控
> > 
> > 
> > 我明白意思，用户获取直链后就不可控。这里意思是我一分享链接内文件夹有多个资源，用户短期时间同时获取多个文件直链并下载，能不能限制这个。我理解这里不可控是不是因为无法获取文件下载状态，无法知道用户此刻哪些任务正在下载中，如果知道下载状态应该可以限制获取新下载直链的动作？
> 
> 我不知道我没有理解你的意思，你说的应该是要限制获取文件直链的个数，也就是限制一定时间内用户可以下载文件的个数，但是这样并没有太大用处，因为第三方储存大部分都是根据流量来限制的，但没有办法可以确定用户是不是下载到一半取消了，或者是恶意下载了几十次，这样没有办法准确统计下载的流量，不能防止别人恶意消耗流量

ok，第三方储存大部分都是根据流量来限制的，但目前遇到限制大多都是短期获得过多下载链接造成的，用户不是重复刷一个下载链接而是短时间，甚至一秒点一个下载文件，有没有可能限制一定时间内获取的下载链接数，相当一个获取新下载的 rate limit（个人感觉应该有用
