### ISSUE TITLE
在从机设置签名有效期为6000秒,然后获取下载地址,还是1分钟左右就提示签名已过期.

### ISSUE THREAD

**Issue by hktrace** [cloudreve/Cloudreve#1395]
在从机设置签名有效期为6000秒,然后获取下载地址,还是1分钟左右就提示签名已过期.
如果开启获取直连里面的签名就不会过期...
程序都是最新的版本.

**Comment by GreenTeodoro839** [comment]
@hktrace 为什么要去存下载链接？永久链接应该通过获取直链取得

**Comment by hktrace** [comment]
> @hktrace 为什么要去存下载链接？永久链接应该通过获取直链取得

不是去存下载连接.我发现idm下载没结束的时候sign就过期了.现在我是想判断是文件下载到一半就无法下载是反代的问题还是sign到期的问题

**Comment by hktrace** [comment]
download 的签名时间这有啥法子修改时间然后并能生效的么..灰常蛋疼.看了下日志.idm 32线程跑满后过段时间就会重新请求download地址.结果因为签名过期导致无法下载..测试夸克浏览器下载也会出现这个问题.

**Comment by HFO4** [comment]
设定下载会话有效期，不是从机签名有效期。

**Comment by hktrace** [comment]
@HFO4 请问下载会话有效期的话是哪个参数.没在文档内找到.
