### ISSUE TITLE
离线下载卡100％

### ISSUE THREAD

**Issue by sail5200919** [cloudreve/Cloudreve#1396]
离线下载进度会卡100％，然后速度归零
但是如果这时点取消任务，会显示完成转存中
不知道是我的问题还是怎么，求解

**Comment by HFO4** [comment]
[文档](https://docs.cloudreve.org/use/aria2#bt-ren-wu-jin-du-100-hou-ren-wu-reng-chang-qi-chu-zai-jin-hang-zhong-de-lie-biao-zhong-bu-bei-chu-li)
