### ISSUE TITLE
是否可以增加一个秒传功能呢? 

### ISSUE THREAD

**Issue by 498110811** [cloudreve/Cloudreve#1397]
是否可以增加一个秒传功能呢? 
数据库中增加个hash值 上传的时候对比hash值实现秒传

**Comment by HFO4** [comment]
Duplicated

**Comment by 498110811** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
