### ISSUE TITLE
go编译报错

### ISSUE THREAD

**Issue by Amour-TiAmo** [cloudreve/Cloudreve#1405]
[
![image](https://user-images.githubusercontent.com/83706001/180589952-7abdc0a4-9808-4545-ba4d-260876d9297c.png)
](url)

**Comment by HFO4** [comment]
此错误与 Cloudreve 无关，请尝试Google搜索或者到 go-sqlite3 下寻求帮助。

**Comment by topjohncian** [comment]
- 可能是没有启用 CGO
尝试 `go env -w CGO_ENABLED=1`

- 或没有安装对应目标平台的 CGO

**Comment by Amour-TiAmo** [comment]
nginx代理80跳转5212时页面为空

**Comment by Amour-TiAmo** [comment]
静态资源文件访问索引页提示需要开启JavaScript，怎么解决
