### ISSUE TITLE
[Pro]从机储存无法上传

### ISSUE THREAD

**Issue by Hatsune-Miku-001** [cloudreve/Cloudreve#1407]
我使用从机储存
上传时报错network error
从机log显示200正常访问
但是我自行get上传链接显示404
从机跨域按照默认配置
![Screenshot_20220724_171737](https://user-images.githubusercontent.com/74259201/180643805-098a898d-fbe2-4fa0-bda2-15fa40206224.jpg)

**Comment by HFO4** [comment]
客户端连接不到从机或者跨域策略有误，具体错误看开发者工具。

**Comment by Rockney99** [comment]
> 我使用从机储存 上传时报错network error 从机log显示200正常访问 但是我自行get上传链接显示404 从机跨域按照默认配置 ![截图_20220724_171737](https://user-images.githubusercontent.com/74259201/180643805-098a898d-fbe2-4fa0-bda2-15fa40206224.jpg)

请问你解决了嘛？我也遇到了这个问题不知道怎么解决
