### ISSUE TITLE
nginx反代问题

### ISSUE THREAD

**Issue by kmg76** [cloudreve/Cloudreve#1408]
我把cloudreve放在/var/www/html/cloudreve下
nginx配置文件中
location ~ / {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://127.0.0.1:5212;
}
指向/时可以访问
但
location ~ /cloudreve {
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_redirect off;
    proxy_pass http://127.0.0.1:5212;
}
无法访问
在指向/cloudreve时会找不到css和js文件，并且索引页提示You need to enable JavaScript to run this app.

**Comment by vvisionnn** [comment]
Seems not a Cloudreve related issue, please head to the [docs](https://docs.cloudreve.org/), or go to [form](https://forum.cloudreve.org/)

**Comment by topjohncian** [comment]
Ref: #1129
