### ISSUE TITLE
希望作者能加一个自动刷新目录索引的功能

### ISSUE THREAD

**Issue by zhinailuoli** [cloudreve/Cloudreve#1411]
![image](https://user-images.githubusercontent.com/107562312/180794559-0ec6cfc6-177b-49a2-834b-9ee6cab473a1.png)
![image](https://user-images.githubusercontent.com/107562312/180794738-9518a0fd-c7a4-4f45-8768-92ff000799c2.png)
不要求刷新整个网盘目录，但如果能实现自动获取指定目录下的新文件就很不错了
OneDrive

**Comment by wt200655** [comment]
作为个人用户，认为这是个很实用的功能，希望作者能添加。

**Comment by topjohncian** [comment]
Dup: #896 
暂无计划
