### ISSUE TITLE
导入外部文件 + 存储策略，希望能够支持上传文件到导入的子目录

### ISSUE THREAD

**Issue by ocleo1** [cloudreve/Cloudreve#1413]
版本：cloudreve_3.5.3_linux_arm64
系统：Linux 5.10.43

### 现状

1. 创建存储策略，设置文件物理存储路径 `../../mnt/test`
2. 创建用户组，并使用该存储策略
3. 创建用户，归属该用户组
4. 导入外部目录，设置原始目录 `/mnt/test`，目的目录 `/`
5. 导入后，界面的显示和外部目录一致
6. 上传文件到其中一个子目录 Documents。成功后，界面显示的与实际存储的位置不一致。界面显示上传到了子目录 Documents，但实际在根目录

### 截图

1.
<img width="1054" alt="screenshot-1" src="https://user-images.githubusercontent.com/13135825/180898117-302b88d9-3844-45fe-9369-abcdf6287c6b.png">

2.
<img width="1102" alt="screenshot-2" src="https://user-images.githubusercontent.com/13135825/180898127-a5a95a87-9cf2-4fc9-afff-ef7c43cac5ce.png">

3.
<img width="1102" alt="screenshot-3" src="https://user-images.githubusercontent.com/13135825/180898130-46b3211a-bcdf-422c-b49d-cdb53394038b.png">

4.
<img width="1102" alt="screenshot-4" src="https://user-images.githubusercontent.com/13135825/180898131-6f16732d-3f25-41fa-8c07-a0f266de4bce.png">

5.
<img width="1102" alt="screenshot-5" src="https://user-images.githubusercontent.com/13135825/180898134-8d07eba3-d31c-4574-ab3d-3b5ef7a8d017.png">
<img width="251" alt="screenshot-6" src="https://user-images.githubusercontent.com/13135825/180898139-fb9fea10-4323-4fc0-bab5-eecbe5d3b86a.png">

6.
<img width="1102" alt="screenshot-7" src="https://user-images.githubusercontent.com/13135825/180898140-7ab5b07d-99b7-446d-8689-bd30f5004167.png">
<img width="1102" alt="screenshot-8" src="https://user-images.githubusercontent.com/13135825/180898141-19eade5a-1f67-4e38-ae80-dd6b34a58759.png">
<img width="348" alt="screenshot-9" src="https://user-images.githubusercontent.com/13135825/180898145-7a7e4579-bb8f-4941-8e41-ef8c1c373910.png">

### 建议

能否新增开关，允许上传文件到导入的子目录

**Comment by ketsurineko** [comment]
实际已经支持类似功能
存储策略中将存储路径进行修改添加魔法变量可实现类似功能
例：E:\{path}

**Comment by ketsurineko** [comment]
> 实际已经支持类似功能 存储策略中将存储路径进行修改添加魔法变量可实现类似功能 例：E:{path}
只能说曲线救国

**Comment by ocleo1** [comment]
> 实际已经支持类似功能 存储策略中将存储路径进行修改添加魔法变量可实现类似功能 例：E:{path}

魔法变量 `{path}` 可用，加上后能够上传到对应的目录

**Comment by ocleo1** [comment]
魔法变量 `{path}` 的说明，有点不太好理解。如果

1. 存储策略的路径添加魔法变量 `../../mnt/test/{path}`
2. 上传文件的本地路径 `/home/1/hello.txt`
3. 进入 `../../mnt/test/abc` 目录，上传 `hello.txt`

根据示例，路径拼接后，最终应该上传到 `../../mnt/test/home/1/`，但其实上传到 `../../mnt/test/abc/`

<img width="432" alt="image" src="https://user-images.githubusercontent.com/13135825/189620784-4f874bf3-a1d7-4d00-a6d9-2b41cbbd3ef8.png">
