### ISSUE TITLE
删除分享后还可以下载？

### ISSUE THREAD

**Issue by yjiawqgj** [cloudreve/Cloudreve#1414]
设置分享后，使用分享后的链接进行下载，下载了一点以后暂停，然后我又把网盘里的我的分享链接给删除了，在下载里继续下载，但还可以下载。那还怎么控制啊？

**Comment by marvinli001** [comment]
取决于存储策略了，除了从机别的策略下载时候获取的都是文件直接路径的下载链接，有的自带过期时间，删除分享只是删除分享的那个链接罢了，没有删除你源文件路径，况且你删除的只是那个分享链接，你的明白？

**Comment by yjiawqgj** [comment]
> 取决于存储策略了，除了从机别的策略下载时候获取的都是文件直接路径的下载链接，有的自带过期时间，删除分享只是删除分享的那个链接罢了，没有删除你源文件路径，况且你删除的只是那个分享链接，你的明白？

也就是说只能看有哪些分享了，一旦分享出去就无法控制了。那分享控制就是大残废了。不能随心所欲控制。有没有改进计划？

**Comment by marvinli001** [comment]
> > 取决于存储策略了，除了从机别的策略下载时候获取的都是文件直接路径的下载链接，有的自带过期时间，删除分享只是删除分享的那个链接罢了，没有删除你源文件路径，况且你删除的只是那个分享链接，你的明白？
> 
> 也就是说只能看有哪些分享了，一旦分享出去就无法控制了。那分享控制就是大残废了。不能随心所欲控制。有没有改进计划？

分享链接点击下载获取到的文件直链本身就取决于存储策略的过期header时间，cr怎么控制？？？？？跟cr就没关系了

**Comment by yjiawqgj** [comment]
怎么控制？你在问我吗？难道你这个不能实现吗？链接取消后就无法访问文件啊，就这么简单啊。安装 Cr 后一切都由 cr 代理全部由 cr 说了算，这不行那不行，只能说要做的还有很多，最基础的都不行

**Comment by topjohncian** [comment]
可以去了解一下其他几个程序，实在不行 pr welcome

**Comment by xb2016** [comment]
嗯，那么简单，不如辛苦您提个 PR 帮忙完善一下
