### ISSUE TITLE
储存策略无法随心控制？

### ISSUE THREAD

**Issue by yjiawqgj** [cloudreve/Cloudreve#1415]
通过本机添加储存策略并导入文件，但是不想用这个策略话，只能把文件删除才行，而且删除了以后策略你的源也会被删除，这操作？？？还有一个问题就是说添加了策略并导入的文件，在策略里面的源文件夹添加文件，竟然不能自动添加，而且必须再次导入才行，你这？？？？

**Comment by topjohncian** [comment]
两点皆为预期行为，且暂无计划支持
See #896.
