### ISSUE TITLE
社区插件支持

### ISSUE THREAD

**Issue by LFMcxixif** [cloudreve/Cloudreve#1421]
有没有可能，将来的Cloudreve社区，用户们可以自己开发插件，拓展Cloudreve的功能，而不是依赖Cloudreve的开发者更新功能？

**Comment by vvisionnn** [comment]
1. This is not an Cloudreve issue, please head to the [forum](https://forum.cloudreve.org) for discussion, for global user, you can posted on the [Github Discussions](https://github.com/cloudreve/Cloudreve/discussions)
2. Cloudreve is open source, we are very welcome for any good ideas, it is ok you can just create a Pull Request
