### ISSUE TITLE
cloudreve总是自动退出

### ISSUE THREAD

**Issue by yjiawqgj** [cloudreve/Cloudreve#1424]
安装完cloudreve一天后打不开了，后来检查状态显示
systemctl status cloudreve
● cloudreve.service - Cloudreve
   Loaded: loaded (/usr/lib/systemd/system/cloudreve.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2022-08-04 11:17:58 CST; 9min ago
     Docs: https://docs.cloudreve.org
 Main PID: 7838 (code=exited, status=203/EXEC)
这怎么弄？

**Comment by vvisionnn** [comment]
Please follow the bug report template, provide more detail

**Comment by wsndshx** [comment]
信息太少, 根据退出信息 `code=exited, status=203/EXEC` 得到如下内容

https://serverfault.com/questions/1013272/issue-running-golang-server-binary-as-a-service-with-systemd

可以考虑排查下系统或环境问题

**Comment by hanqingwu** [comment]
直接手动执行一下 cloudreve 看下是什么错误log ?
