### ISSUE TITLE
url访问的相关

### ISSUE THREAD

**Issue by ZeroHoKe** [cloudreve/Cloudreve#1425]
建议 新增 一项可以 使用访问cloudreve的url 作为下载url的头
在本地架设的时候可以在内网访问，在外网映射好的时候也可以访问，但两者都存在一个问题：如果url ip指向的是外网ip，那么内网可以访问而无法下载任何东西。这就意味着将cloudreve的站点设定为外网域名，那么将无法在内网进行下载，预览好像可行。
同样将其指向内网IP，同样发生在外网也将无法下载。这就无法做到在家和在外地同时可用。
如果可行，希望新增此项功能

**Comment by AkkiaS7** [comment]
你在内网环境不能访问自己的出口IP ，我觉得是端口回流没做好。
其实做了回流后你本地直接访问自己的出口IP效果和内网IP是一样的
可以检查一下你的路由和防火墙设备。

如果实在不支持这么操作
可以考虑通过内网DNS服务器把你自己的域名解析到内网IP，
设一个短一些的ttl让你离开局域网环境后能快速获取到外网的IP。

**Comment by ZeroHoKe** [comment]
抱歉，我的设备不支持端口回流，设备dns也不能更改解析，抱歉了
