### ISSUE TITLE
把网盘链接分享出去 即为管理员登陆中

### ISSUE THREAD

**Issue by C1en-QwQ** [cloudreve/Cloudreve#1428]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by topjohncian** [comment]
**请首先补充问题详情**
> 不补充完整信息，大家很可能没有办法准确找到你的问题，只能靠猜测
---
是否使用了 CDN ?
是否启用了类似于 `Nginx 缓存` 之类的插件 ？

**Comment by C1en-QwQ** [comment]
> **请首先补充问题详情**
> 
> > 不补充完整信息，大家很可能没有办法准确找到你的问题，只能靠猜测
> 
> 是否使用了 CDN ? 是否启用了类似于 `Nginx 缓存` 之类的插件 ？

谢谢 确实是缓存问题 解决了

**Comment by xfyNB** [comment]
> > **请首先补充问题详情**
> > > 不补充完整信息，大家很可能没有办法准确找到你的问题，只能靠猜测
> > 
> > 
> > 是否使用了 CDN ? 是否启用了类似于 `Nginx 缓存` 之类的插件 ？
> 
> 谢谢 确实是缓存问题 解决了

请问是如何解决的，我也遇到了这个问题
