### ISSUE TITLE
反馈个不知道是不是bug的问题

### ISSUE THREAD

**Issue by setube** [cloudreve/Cloudreve#1431]
我自己创建分享然后去下载是可以下载的(游客状态)
但是用户点击下载的时候却提示:"无权访问此分享"
我后台也都给了**所有用户组**下载的权限

我自己访问下载接口返回的是
`{"code":0,"data":"url", msg: ""}`

但是用户那边返回的却是
`404 page not found`

**Comment by topjohncian** [comment]
尝试提供更多的日志、截图？

**Comment by SeTube** [comment]
> 尝试提供更多的日志、截图？
用户那边反馈的截图
![1.png](https://dd-static.jd.com/ddimg/jfs/t1/65604/35/20957/41173/62f2bf09E9ab8c81c/11abfac6420a4c9d.png)
![1.png](https://dd-static.jd.com/ddimg/jfs/t1/85411/13/28545/16292/62f2bc4eE301b387e/e3dd214e12daa010.png)
