### ISSUE TITLE
谷歌浏览器前端页面白屏打不开

### ISSUE THREAD

**Issue by ConstStar** [cloudreve/Cloudreve#1435]
版本：3.5.3
![image](https://user-images.githubusercontent.com/42526758/184471447-c9a4b294-e1e3-4bbe-8047-010391baab48.png)
![image](https://user-images.githubusercontent.com/42526758/184471480-c1db45de-dac3-4ec6-8f86-b991f488b2b7.png)

**Comment by ConstStar** [comment]
谷歌浏览器版本：版本 104.0.5112.81（正式版本） （64 位）

**Comment by ConstStar** [comment]
刚刚试了 微信自带的浏览器可以 手机也能打开 就是电脑的谷歌浏览器打不开 电脑谷歌浏览器可以打开演示站

**Comment by ConstStar** [comment]
还有 Microsoft Edge  也打不开

**Comment by topjohncian** [comment]
是否更改了静态资源？

**Comment by ConstStar** [comment]
没有 正常下载下来 运行./cloudreve

**Comment by ConstStar** [comment]
> 是否更改了静态资源？

没有 正常下载下来 运行./cloudreve

**Comment by black-fruit** [comment]
我也是
