### ISSUE TITLE
[功能请求] 存储目录和网盘目录双向同步

### ISSUE THREAD

**Issue by starlight02** [cloudreve/Cloudreve#1436]
现在使用“导入”功能后，存储（硬盘）在被外部增删文件（例：aria2 下载、smb 文件传输）后，网盘目录可能出现一些无效的文件，真实文件可能已被移除，但是网盘目录下还显示着，而且硬盘新增的文件也不会显示，因此请求增加此功能。

**Comment by topjohncian** [comment]
#896 currently no plan 😃
