### ISSUE TITLE
windows下边 直接运行 exe一闪就没有了

### ISSUE THREAD

**Issue by masterchen** [cloudreve/Cloudreve#1438]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by hanqingwu** [comment]
用命令行执行下，看下错误log ？

**Comment by masterchen** [comment]
> 用命令行执行下，看下错误log ？

也没有生成log ，win10系统

**Comment by wsspsb** [comment]
顺便问下,windows用命令行启动cloudreve的话,怎么将日志写到本地文件,配置文件里没看到这样的参数

**Comment by MoeCinnamo** [comment]
win+r输入cmd，勾选用管理员身份运行，然后cd到指定的目录，输入cloudreve.exe运行后就可以在命令行运行了，这个应该不是图形界面的。
