### ISSUE TITLE
上传多个文件出现错误

### ISSUE THREAD

**Issue by reallizeyu** [cloudreve/Cloudreve#1440]
上传多个文件时会提示无法解析响应（默认策略和Onedrive都会有该提示）但在点击右边的重试后有时又可以上传.报错图片如
下
<img width="644" alt="屏幕截图 2022-08-15 194716" src="https://user-images.githubusercontent.com/111287375/184635865-0ff93e0e-2245-462a-8d31-5593d712548d.png">
<img width="506" alt="屏幕截图 2022-08-15 193927" src="https://user-images.githubusercontent.com/111287375/184635875-cfc0f7d2-b472-4bb6-9969-f85797e7470d.png">
恳请大佬帮我看看！

**Comment by topjohncian** [comment]
检查一下是否开启了类似 `Nginx 限流` 的功能或插件

**Comment by reallizeyu** [comment]
> 检查一下是否开启了类似 的功能或插件`Nginx 限流`
是这个问题，现在解决了，谢谢大佬。
