### ISSUE TITLE
同样密钥下SQLite和PostgreSQL生成的密钥不一致

### ISSUE THREAD

**Issue by yxzlwz** [cloudreve/Cloudreve#1443]
**Describe the bug**

我之前在机器A上正常使用SQLite运行Cloudreve

现在要迁移到机器B，**我已经把机器A上的HashIDSalt复制到机器B**，并尝试了如下操作：

- 直接将机器A的SQLite复制到机器B使用，正常
- 将机器A的SQLite信息导入到机器B的PostgreSQL中，再在机器B运行cloudreve，无法登录提示密码错误
- 在机器B重新初始化一个空的PostgreSQL数据库，创建一个新用户，设置了一个在机器A上使用过的密码，对比发现纵使HashID相同生成的password并不一样

**请问这是什么情况，以及如何解决？**感谢。

**Comment by topjohncian** [comment]
https://github.com/cloudreve/Cloudreve/blob/96daed26b4453093d9d1a4dfe8d9ee334a7338af/models/user.go#L242-L259

先回答3，密文中 Salt 是随机生成的，所以一定不一样

**Comment by topjohncian** [comment]
`HashIDSalt` 是用来生成 UID 等 ID 的 HashID 形式的 Salt (如 `/s/Hx6Sn` 等等)，与密码无关

SQLite 迁移至 mysql 可以看社区的帖子，但非官方方法，并不保证有效。

**Comment by yxzlwz** [comment]
> `HashIDSalt` 是用来生成 UID 等 ID 的 HashID 形式的 Salt (如 `/s/Hx6Sn` 等等)，与密码无关
> 
> SQLite 迁移至 mysql 可以看社区的帖子，但非官方方法，并不保证有效。

好的，谢谢，我再试几种情况看看规律摸索一下吧

只能说设计有一小点阴间啊……

**Comment by yxzlwz** [comment]
迁移 PostgreSQL 最后的解决方案：Navicat 导出 SQLite 为 SQL 文件，先通过 cloudreve 程序初始化 PostgreSQL 中的表，然后手动修改 SQLite 导出的 SQL 文件中的 Boolean 类型的表达方式（01 转为 true false，我对每个表分别使用正则处理的），最后再“运行SQL文件”导入。
