### ISSUE TITLE
对接OneDrive提示AssessToken获取失败

### ISSUE THREAD

**Issue by aomsir** [cloudreve/Cloudreve#1444]
使用了CDN和SSL，CDN没有对页面进行缓存。但是就是上述错误，E5和家庭版都有问题

**Comment by aomsir** [comment]
补一句，我的是捐赠版

**Comment by aomsir** [comment]
AccessToken 获取失败, AADSTS900144: The request body must contain the following parameter: 'refresh_token'. Trace ID: 32a9b11e-78c4-45e1-bd2a-7e3763de3700 Correlation ID: 39773d52-80c9-467c-9c41-909cc2090b4e Timestamp: 2022-08-19 08:58:59Z

**Comment by aomsir** [comment]
上面是今天提示的

**Comment by MoeCinnamo** [comment]
可能和网络问题有关

**Comment by aomsir** [comment]
> 可能和网络问题有关

我感觉是时间戳的问题，邮件激活和这个的提示时间都比现在的时间早8个小时

**Comment by aomsir** [comment]
解决了，使用又拍云CDN的时候未开启参数跟随导致的
