### ISSUE TITLE
Webdav返回405错误

### ISSUE THREAD

**Issue by Freddd13** [cloudreve/Cloudreve#1451]
**Describe the bug**
文献管理软件zotero, 利用cloudreve的webdav同步，ios端使用papership读写webdav。
最近zotero无法同步了，验证webdav成功，但是上传不了文件，如下：

![image](https://user-images.githubusercontent.com/50367552/185950593-5695761f-b02c-4798-8925-bfd691aceda7.png)

手动上传暂时正常

**To Reproduce**
1. zotero手动或自动webdav同步
2. 
![image](https://user-images.githubusercontent.com/50367552/185950162-44e9ae5b-9bf0-41ca-b742-9acd2d43e98b.png)
![image](https://user-images.githubusercontent.com/50367552/185950771-506a7b0c-96fe-4dc0-aca7-9d878ee78dfc.png)

win11 使用zotero自带webdav同步设置.
cloudreve策略为onedrive国际, nginx 反代：

![image](https://user-images.githubusercontent.com/50367552/185952132-c1f1fbbc-952e-4f31-95e7-7a40935c34ac.png)

**Comment by Freddd13** [comment]
手动删除了个onedrive里面残留的文件解决了

**Comment by Eunsolfs** [comment]
> 手动删除了个onedrive里面残留的文件解决了

删了啥东西啊？我也是用服务器自建了cloudreve，目前也出现了你遇到的情况，不知道怎么办呢。求教。我的微信 yuluo33826

**Comment by Freddd13** [comment]
你是用的zotero出问题吗？时间久了我记不太清了，我当时好像是从OneDrive把最新同步的那个文件夹删了重新上传同步就好了

**Comment by Eunsolfs** [comment]
是的, 连验证webdav服务器这一关都过不了

onedrive国际版 5T



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年05月14日 01:27 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [cloudreve/Cloudreve] Webdav返回405错误 (Issue #1451) |

你是用的zotero出问题吗？时间久了我记不太清了，我当时好像是从OneDrive把最新同步的那个文件夹删了重新上传同步就好了

**Comment by Freddd13** [comment]
首先保证搭建的webdav本身没问题。
然后检查下url对不对（比如https，zotero的路径），看看路径有没有搞错。
如果之前同步过可以尝试用我说的方法在电脑上将zotero 同步文件夹按时间排序，看最新那几个，然后从OneDrive 网页或者app把那几个彻底删除。不过你这似乎一开始就这样？这我没遇到过，你看看是不是webdav密码输错了，不是账号密码
