### ISSUE TITLE
启动后文件可以上传，但无法下载

### ISSUE THREAD

**Issue by zhangpanzhan** [cloudreve/Cloudreve#1452]
**Describe the bug**
./cloudreve启动后，按照文档，可以上传文件，但是无法下载文件，问题在于下载的时候，弹出的url没有port信息，手动加上5212后，就可以下载了，但是这样很傻，希望能得到解决。

**Comment by Waitung** [comment]
至少先进一次后台管理面板再来提 Issues 吧

**Comment by topjohncian** [comment]
进入后台面板会自动提示更改 `站点 URL`

**Comment by cherishh** [comment]
我使用docker安装的，请问下怎么进后台管理？

**Comment by cherishh** [comment]
> 我使用docker安装的，没有显示第一次运行时候的管理员账号密码信息，请问下要怎么查看？

找到了，`docker logs -f <DOCKER_NAME>`

**Comment by cjs520** [comment]
请熟读一下docker使用

**Comment by zhangpanzhan** [comment]
进去了的。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月24日 18:56 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [cloudreve/Cloudreve] 启动后文件可以上传，但无法下载 (Issue #1452) |

至少先进一次后台管理面板再来提 Issues 吧

**Comment by zhangpanzhan** [comment]
我这边没有提示更改，怪不得。



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年08月25日 18:55 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [cloudreve/Cloudreve] 启动后文件可以上传，但无法下载 (Issue #1452) |

进入后台面板会自动提示更改 站点 URL
