### ISSUE TITLE
V3.5.3最新版本图片直链问题

### ISSUE THREAD

**Issue by 3065176078** [cloudreve/Cloudreve#1454]
使用的是
onedrive国际策略，开启了直链获取，允许获取外链

获取图片直链正常

直链地址进去后提示

Sorry, something went wrong
The access token has expired. It's valid from '8/25/2022 5:17:46 AM' and to '8/25/2022 6:17:46 AM'.
Technical Details
Go back to site

v3.3.1老版本正常可用，升级到v3.5.3
后最新上传图片全部出现类似情况
请问是我哪个新设置没弄好吗？

**Comment by cjs520** [comment]
你刷新token过期了，重新授权一下
