### ISSUE TITLE
 管理员后台设置用户最大容量最多只能是1G

### ISSUE THREAD

**Issue by jiwufeiyang** [cloudreve/Cloudreve#146]
[你好，我这个项目我本地下载，centos7部署项目，在管理员后台设置用户组最大容量只能是1G,大于1G会自动变为负数-2147483648Bytes，我设置了php的上传文件大小也是这样，请问要怎样设置？

**Comment by HFO4** [comment]
切换到php7及以上版本试下呢

**Comment by vincenthsing** [comment]
我也是,后台改数据库完美解决,哈哈哈

**Comment by HFO4** [comment]
V3版本中已解决此问题
