### ISSUE TITLE
希望能增加手动退出登录功能

### ISSUE THREAD

**Issue by ggfvictor** [cloudreve/Cloudreve#1463]
比如在公用电脑上登陆后忘记退出，可以在登录后踢出在线登录。

**Comment by ggfvictor** [comment]
类似于hass的令牌
![image](https://user-images.githubusercontent.com/27218364/188271316-17eb1245-16ea-4bd6-87df-531075b2b199.png)

**Comment by yxzlwz** [comment]
支持，插个眼
