### ISSUE TITLE
 doc xls 无法完成文件上传: 文件信息不一致

### ISSUE THREAD

**Issue by iJayscn** [cloudreve/Cloudreve#1465]
docker版 cloudreve 3.5.3 存储策略 世纪互联 SP

文件名：202206.docx
文件大小：921.4 KB (1 个分片, 每个分片 50.0 MB)
存储策略：21VNet-SP-01
目的路径：[根目录](javascript:void)
上传会话：23 小时后过期
**错误信息：无法完成文件上传: 文件信息不一致**

**Desktop (please complete the following information):**
 - OS: Win 11 
 - Browser: EDGE
 - Version: 105

**Comment by ivmm** [comment]
复现 + 1 ，png jpg pdf 正常。word excel 文件信息不一致
