### ISSUE TITLE
赞助版的问题，望大大解惑！

### ISSUE THREAD

**Issue by a1361663667** [cloudreve/Cloudreve#1466]
你好开发组成员，我是赞助版本，但是我发现若干问题，
1.用户购买了容量后用户容量到期后之前分享的文件还能正常下载，是否有什么命令可以实时刷新语句让到期的用户无法继续下载，另外用户组也是一样的情况
2.手动解除用户组绑定后，必须要等到用户组实际到期后才能继续购买其他用户组（解绑没用）
3.删除用户账号后，对应账号下的文件无法继续删除（需先删除文件在删除账号方可）
上述的几个bug，运行环境sql3数据库和CentOS8.2国际版宝塔

**Comment by wangxiaoerYah** [comment]
这是设计问题，第一个，到期后还能下载是因为，那个下载连接是你后面的储存接出来的，你只是cloudreve容量过期了，但是cloudreve并不能阻止他人访问这个链接。除非是你可以为后面的s3或者onedrive定制访问策略或者用一个定时的token来访问。第一个就直接pass掉。本地存储会不会这样就不知道了。
第三个应该是数据库的问题，删除了用户，然后删除文件，文件是有用户的ID的，数据库找不到id就肯定报错，这个要去看你的数据库日志。

我不是开发人员，我是热心市民🤣
