### ISSUE TITLE
ios端上传有问题！

### ISSUE THREAD

**Issue by cszs1986** [cloudreve/Cloudreve#1470]
同一个文件删除后，再上传的时候无法上传
修改文件名后才可以再上传

**Comment by vvisionnn** [comment]
测试无法复现，需要提供更多信息
1. 文件删除指的是上传（未完成）时候删除还是上传完成后通过删除按钮删除？
2. 如果是上传完成后删除，文件是否已经下载为离线可用？
3. 如果问题能够复现，请提供详细复现步骤，这样能够使问题尽快解决 。

> cannot reproduce this scenario, more information needed
> 1. about the delete action, is deleting during the upload or just delete a uploaded file?
> 2. if you delete a file after done upload, is this file downloaded and marked as offline available?
> 3. if this issue can be reproduced, please follow the bug report and provide detailed reproduce steps, this can help us resolve this problem ASAP.
