### ISSUE TITLE
nginx 1.22按照文档说明反代后无法正常播放视频，会一直下载，直接访问5212端口没有这个问题

### ISSUE THREAD

**Issue by apple12358lp** [cloudreve/Cloudreve#1472]
nginx 1.22按照文档说明反向代理后无法正常播放视频，会一直下载，直接访问5212端口没有这个问题

**Comment by MiKing233** [comment]
你首先應該學會怎麽提問

無法正常播放視頻是哪種不正常? 什麽叫會一直下載? 下載是什麽意思? 創建下載任務還是一直載入??
再然後, 既然你也知道直接訪問5212沒有問題, 那麽你不把Nginx conf貼出來給別人分析?

就你這樣甩一句話描述不清就説出了問題, 放一年也不可能有人搭理你

**Comment by black-fruit** [comment]
> 你首先應該學會怎麽提問
> 
> 無法正常播放視頻是哪種不正常? 什麽叫會一直下載? 下載是什麽意思? 創建下載任務還是一直載入?? 再然後, 既然你也知道直接訪問5212沒有問題, 那麽你不把Nginx conf貼出來給別人分析?
> 
> 就你這樣甩一句話描述不清就説出了問題, 放一年也不可能有人搭理你

我觉得只有除大陆以外的人不会回复，大陆基本都用一个工具，大家都知道，就你不知道，显得你很智障

**Comment by black-fruit** [comment]
> nginx 1.22按照文档说明反向代理后无法正常播放视频，会一直下载，直接访问5212端口没有这个问题

我是直接白屏，现在cloudreve不管是论坛还是GitHub基本都没人回复了
