### ISSUE TITLE
视频封面图

### ISSUE THREAD

**Issue by LiuXIn011** [cloudreve/Cloudreve#1479]
当视频文件很多时，有封面图更有助于分辨他们
![image](https://user-images.githubusercontent.com/48080203/191466699-da029ab0-13e0-475d-901d-1c662372a7e7.png)

**Comment by DFNJKD-98** [comment]
附议

**Comment by conashin** [comment]
這是選擇的儲存策略是否支援的問題吧？我用OD是有出現的。
PS. Webdav上傳似乎都不會有縮圖

**Comment by conashin** [comment]
這是選擇的儲存策略是否支援的問題吧？可以去文檔看一下。
我用OD是有出現的。
P.S. Webdav上傳似乎都不會有縮圖（3.6.2）
