### ISSUE TITLE
cloudreve return index.hmtl when request for .css and .js file

### ISSUE THREAD

**Issue by Linnas** [cloudreve/Cloudreve#1485]
**Describe the bug**
NGINX reverse proxy under /cloud return wrong header and content

**To Reproduce**
1. build frontend assets with homepage='/cloud/'
2. rename assets to statics and place under the same dir with cloudreve

**Expected behavior**
*.css and *.js return same index.html page with response header 'text/html'

**Screenshots**
![err](https://user-images.githubusercontent.com/39158851/192580558-3c21c119-4a40-465c-8f7c-0e8c4fce403e.png)
![Screenshot from 2022-09-28 00-20-24](https://user-images.githubusercontent.com/39158851/192580945-b8a93f03-b41b-4ea3-b1c4-bace9d29796d.png)

**Desktop (please complete the following information):**
 - OS: centos7.9
 - Browser chrome
 - Version latest

**Comment by HFO4** [comment]
Currently, Cloudreve does support sub-directory.
