### ISSUE TITLE
frp内网穿透cloudreve无效的问题

### ISSUE THREAD

**Issue by VeddySama** [cloudreve/Cloudreve#1487]
我使用frp穿透5212端口  frp的服务界面上有显示5212  但是服务器上根本就无法访问到5212  这是什么问题呢  还有一个就是关于frp后nginx配置  就正常的配置就可以了吗

我用的docker部署的cloudreve:latest  服务器和内网环境均为CentOS7

**frp配置**
![image](https://user-images.githubusercontent.com/49411287/193167105-98d06cc8-23cb-4816-86d6-d756fdd556b2.png)

**frp界面正常**
![image](https://user-images.githubusercontent.com/49411287/193166836-0c4d2cd1-761c-4278-8664-6df9fa9c6a48.png)

**内网环境服务正常启动**
![image](https://user-images.githubusercontent.com/49411287/193166959-839bd318-58d6-4c01-84fe-671bd95ae6cb.png)

**服务器上无反应**
![image](https://user-images.githubusercontent.com/49411287/193167058-9a4c7ff3-6434-4823-a6e1-9e572b93642c.png)

**Comment by tapppper** [comment]
首先，信息给的太少，难以判断。
其次，frp后，nginx正常配置就行，我有成功过。
最后，建议看看穿透其他的服务有没有成功，比如ssh。

**Comment by VeddySama** [comment]
> 首先，信息给少了，其他判断有没有给太少 配置，nginx就行了，我就成功了。 最后，看看有没有成功的服务，比如ssh。

感谢回复   我这边用frp穿透ssh是可以的   内网环境防火墙也是关闭的  cloudreve是默认配置  frp配置应该只需要截图所示就行  其他的都是公共配置

**Comment by tapppper** [comment]
服务器上也没有，有没有一种可能，客户端连接的并不是这台服务器

**Comment by VeddySama** [comment]
> 服务器上也没有，有没有一种可能，客户端连接的并不是这台服务器

感谢回复  我内网服务器的22端口映射出去都没问题  并且连接至内网也是通过frp的地址端口去连接的

**Comment by VeddySama** [comment]
也有可能是我用的frp的问题

**Comment by VeddySama** [comment]
frp问题
