### ISSUE TITLE
更灵活的存储策略

### ISSUE THREAD

**Issue by Initial-heart-1** [cloudreve/Cloudreve#1489]
## 自定义存储策略

我有很多分散的文件存储服务器，今天我尝试将它们利用起来，第一个想到的就是 Cloudreve 的从机功能，但当我仔细地研究了它后，我发现对我来说它存在两个问题：

- 对于仅用于特定用途的服务器，Cloudreve 的从机机制太过臃肿。
- 对于没有主机控制权的服务器，Cloudreve 的从机机制无法实现。

故，希望有可自定义的存储策略，例如：自定义上传/下载的请求地址，协议，方式等。

对于我，存在这样的架构：

- 使用 (S)FTP 上传文件
- 使用 HTTP(S) 下载文件

相信不少的用户可以搭建相同的架构又或是有如下架构：

- 使用 HTTP(S) 上传、下载文件

考虑到 Cloudreve 是个网盘系统，除去 WebDAV 外所有操作都是通过浏览器完成，故可能只需要考虑上述两(四)种常见协议即可。

这看起来似乎并不难实现让用户自定义，苦于本人对 Go 了解甚少，未能提交 Pull request。

在我试图寻找将通过 FTP 协议通信的服务器添加为 Cloudreve 的存储策略时，我注意到了 #766 ，其中提到了一个严肃的问题：安全。

不得不承认的是，FTP 确实存在这样的问题，若要添加可能只能作为中转。但，这并不意味着这无利可图：

- 这可以有效的节省主机的存储空间（尽管代价是宝贵的带宽）。
- 这有助于使用户更快速的取回文件（若该机器可用上传带宽优于主机，又或是负载均衡）。
- 这有助于提高可靠性。

综上，希望有可自定义的存储策略。

## 并用存储策略

如题，允许并用多个存储策略。

这有助于：

- 提高可靠性。
- 给用户带来更佳体验。

可以给出选项，设定一个主用策略，用户执行上传操作时先上传至主用策略，后由服务器中转至并用的次用策略。也可选不配置，此时随机选择一个策略作为主用策略。

另给出选项，当用户执行下载操作时，将全部策略展现给用户自行选择，或是负载均衡，又或是依据地域选择......等等。

这看起来比自定义存储策略要难。同样的，苦于本人对 Go 了解甚少，未能提交 Pull request。

综上，希望允许并用多个存储策略。

**Comment by Initial-heart-1** [comment]
so，如确实没有计划实现这个 issue 所述 ，可以等待 bot 自动 close 这个 issue。

**Comment by YUDONGLING** [comment]
The idea of support (S)FTP have same problem with Webdav as storage backend.

锁定此 issue, 后续讨论请在 https://github.com/cloudreve/cloudreve/discussions/3433 继续进行。
Lock this issue and more discussion will be avaliable at https://github.com/cloudreve/cloudreve/discussions/3433.
