### ISSUE TITLE
关于添加“登陆用户分享转存至网盘”的功能的请求

### ISSUE THREAD

**Issue by reallizeyu** [cloudreve/Cloudreve#1490]
现有版本中，登录用户访问分享链接时如想将其转存至自己网盘中还需下载到本地再进行上传。希望能添加一个“登陆用户分享转存至网盘”的功能，即已登录用户可将其他用户的分享直接转存至自己账号的指定目录而无需下载再上传（此操作操作可不会额外占用存储策略物理存储空间，但仍会正常扣除用户已用容量空间），增加网盘分享体验。

**Comment by topjohncian** [comment]
Pro 版有这个功能

**Comment by reallizeyu** [comment]
知道了，谢谢

topjohncian ***@***.***> 于2022年10月3日周一 16:33写道：
