### ISSUE TITLE
希望能够增加易支付的支付接口

### ISSUE THREAD

**Issue by aac6fef** [cloudreve/Cloudreve#1493]
Payjs已停止注册，希望能提供易支付的支付接口

**Comment by gonboy** [comment]
易支付
页面好Low, 竟然还是 http.

是不是骗子啊

**Comment by gonboy** [comment]
测试了0.1元， 半个小时收不到款。

山寨的味道... ...

**Comment by AS13379** [comment]
@gonboy 您没事吧

**Comment by AS13379** [comment]
@gonboy 你当这是马支付呢。。。

**Comment by aac6fef** [comment]
> 易支付 页面好Low, 竟然还是 http.
> 
> 是不是骗子啊

易支付是一个通用的支付接口，而不是某特定商家

**Comment by dhlun** [comment]
易支付就是骗子接口，别加了，小白不懂的太多

**Comment by HFO4** [comment]
3.7.0 后可通过兼容 API 对接自定义支付接口。
