### ISSUE TITLE
二部验证的设备更换了，怎么重置？

### ISSUE THREAD

**Issue by Yumaofei** [cloudreve/Cloudreve#1495]
二部验证的设备更换了，怎么重置？

**Comment by LaochenFEIZHAI** [comment]
同好奇

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Yumaofei ***@***.***>
Sent: Friday, October 7, 2022 11:35:48 AM
To: cloudreve/Cloudreve ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [cloudreve/Cloudreve] 二部验证的设备更换了，怎么重置？ (Issue #1495)


二部验证的设备更换了，怎么重置？

―

**Comment by JaneYork** [comment]
https://www.yuque.com/docs/share/1063c5c0-b979-491c-bab7-3de857f51132?#

@LaochenFEIZHAI @Yumaofei

**Comment by DeasonHu** [comment]
@JaneYork 编辑 cloudreve.db 数据库 删除该用户的两步验证

**Comment by wzry2580** [comment]
@stale[bot] 备份好两步验证APP数据，不然，因为换了设备，你还是可以重新导入数据，如果两步验证数据没了
因为你设置两步验证登录，但是你又通不过，相当于废了，那你就登不进去，那只能重装

**Comment by topjohncian** [comment]
在后台修改该用户的双重验证信息为空，重新绑定。
