### ISSUE TITLE
【Bug】常见问题汇总-黑暗模式设置不生效

### ISSUE THREAD

**Issue by JaneYork** [cloudreve/Cloudreve#1498]
**Describe the bug**
## BUG一：黑暗模式设置不生效
Mac OS系统为深色主题。
cloudreve点击关闭黑暗模式，刷新浏览器后又恢复成黑暗模式了，不生效。无法关闭黑暗模式。
相反的，如果是亮色模式，也是无法正常切换黑暗模式。
https://github.com/cloudreve/frontend/tree/547078fa21bb5ff5109e40097103dd8090bba296
<img width="769" alt="image" src="https://user-images.githubusercontent.com/29787967/194704706-1ac6b670-6764-44a9-ab8b-0ecb01cfacf2.png">

## BUG二：多语言切换不生效
Windows server 2012下，Edge浏览器最新版访问，无法切换中英文，一直默认英文。

@HFO4 

cloudreve版本：最新
浏览器：Chrome最新版版本 105.0.5195.125（正式版本） (x86_64)

## bug3：用户组编辑显示错误
如下图，怎么显示了占位符。
<img width="657" alt="image" src="https://user-images.githubusercontent.com/29787967/194734978-01b1b186-f26f-469b-8cfb-3353b4b9b694.png">

**Comment by JaneYork** [comment]
@topjohncian

**Comment by JaneYork** [comment]
二步验证、身份验证器重新 找回 https://github.com/cloudreve/Cloudreve/issues/1495#issuecomment-1272478418

**Comment by HFO4** [comment]
Fixed in https://github.com/cloudreve/frontend/commit/d4e9d5926d18dc66108f3e8a7c008ecedd0dc220 and https://github.com/cloudreve/frontend/commit/2e9fb47f922b238592c2afedf0b5ed5fe9a30563
