### ISSUE TITLE
开发一个安卓客户端

### ISSUE THREAD

**Issue by stong12345** [cloudreve/Cloudreve#1499]
开发一个安卓客户端嘛，用来备份手机上视频，照片等信息，很多人都急需要的

**Comment by topjohncian** [comment]
欢迎贡献~
官方暂无计划开发 Android 客户端

**Comment by Six-6Chen** [comment]
我想我可以把浏览器嵌入到app中来封装web端

**Comment by dhlun** [comment]
欢迎贡献~
官方暂无计划开发 Android 客户端

**Comment by dossec** [comment]
andriod手机不配使用cloudreve吧

**Comment by liaohui5** [comment]
这个 issue 有更新吗? 现在有安卓客户端了吗?
