### ISSUE TITLE
为什么装好以后首页可以打开，但是点注册和登录就空白

### ISSUE THREAD

**Issue by exing2** [cloudreve/Cloudreve#151]
为什么装好以后首页可以打开，但是点注册和登录就空白

**Comment by exing2** [comment]
http://pan.pangx.cn/
这是我的站点

**Comment by h6fYe34KFSiH** [comment]
我的也是

**Comment by gu-chen** [comment]
你应该是直接git clone，因为这个仓库项目缺少部分vendor，所以只能访问首页。建议用composer安装
