### ISSUE TITLE
从机离线下载负载过高连接超时问题

### ISSUE THREAD

**Issue by ghost** [cloudreve/Cloudreve#1510]
配置从机离线下载后，从机持续高负载下载，主机无法连接从机，主机判断下载超时，取消任务，实际上从机仍然在下载。能否通过修改配置文件修改这个判断超时的时间呢？或者取消判断。

**Comment by dhlun** [comment]
有啊，有这个

**Comment by Canghai0823** [comment]
> 

并没有看到相关介绍啊
