### ISSUE TITLE
页面渲染出现错误，请尝试刷新此页面。

### ISSUE THREAD

**Issue by FuckUbuntu** [cloudreve/Cloudreve#1511]
**Describe the bug**
所有页面出现"页面渲染出现错误，请尝试刷新此页面"崩溃。
TypeError: Cannot read properties of undefined (reading 'palette')

    in Ni
    in t
    in t
    in t
    in l
    in i
    in Connect(i)
    in f
    in a
    in ForwardRef

**To Reproduce**
最近一次正常执行的操作为：向Onedrive上传一份iso文件。

**控制台**
   ___ _                 _                    
  / __\ | ___  _   _  __| |_ __ _____   _____ 
 / /  | |/ _ \| | | |/ _  | '__/ _ \ \ / / _ \	
/ /___| | (_) | |_| | (_| | | |  __/\ V /  __/
\____/|_|\___/ \__,_|\__,_|_|  \___| \_/ \___|

   V3.5.3  Commit #0e5683b  Pro=false
================================================

[Info]    2022-10-26 09:41:58 初始化数据库连接
[Info]    2022-10-26 09:41:58 数据库版本匹配，跳过数据库迁移
[Info]    2022-10-26 09:41:58 初始化任务队列，WorkerNum = 10
[Info]    2022-10-26 09:41:58 初始化定时任务...
[Info]    2022-10-26 09:41:58 当前运行模式：Master
[Info]    2022-10-26 09:41:58 开始监听 :5212
[GIN] 2022/10/26 - 09:42:16 | 200 |    4.238701ms |  112.94.129.221 | GET      "/favicon.ico"
[GIN] 2022/10/26 - 09:42:16 | 200 |     6.37304ms |  112.94.129.221 | GET      "/api/v3/site/config"
[GIN] 2022/10/26 - 09:42:16 | 200 |     898.129µs |  112.94.129.221 | GET      "/manifest.json"
[GIN] 2022/10/26 - 09:42:18 | 200 |    8.317195ms |  112.94.129.221 | GET      "/service-worker.js"
[GIN] 2022/10/26 - 09:42:18 | 200 |      941.42µs |  112.94.129.221 | GET      "/"
[GIN] 2022/10/26 - 09:42:18 | 200 |    2.423616ms |  112.94.129.221 | GET      "/static/css/6.d9dc5367.chunk.css"
[GIN] 2022/10/26 - 09:42:18 | 200 |   34.675018ms |  112.94.129.221 | GET      "/static/js/main.cf15fbf6.chunk.js"
[GIN] 2022/10/26 - 09:42:18 | 200 |   73.307364ms |  112.94.129.221 | GET      "/static/js/6.cad1736a.chunk.js"
[GIN] 2022/10/26 - 09:42:44 | 200 |    3.676893ms |  112.94.129.221 | GET      "/api/v3/site/config"
[GIN] 2022/10/26 - 09:42:44 | 200 |    1.290462ms |  112.94.129.221 | GET      "/manifest.json"
[GIN] 2022/10/26 - 09:42:44 | 200 |    1.676078ms |  112.94.129.221 | GET      "/favicon.ico"
[GIN] 2022/10/26 - 09:47:34 | 200 |    2.847375ms |  112.94.129.221 | GET      "/"
[GIN] 2022/10/26 - 09:47:34 | 200 |    1.728887ms |  112.94.129.221 | GET      "/static/css/6.d9dc5367.chunk.css"
[GIN] 2022/10/26 - 09:47:34 | 200 |    18.37657ms |  112.94.129.221 | GET      "/static/js/main.cf15fbf6.chunk.js"
[GIN] 2022/10/26 - 09:47:34 | 200 |    68.96771ms |  112.94.129.221 | GET      "/static/js/6.cad1736a.chunk.js"

**Desktop (please complete the following information):**

**Comment by MoeCinnamo** [comment]
重启后端试试

**Comment by HFO4** [comment]
> 重启后端试试

重启后端解决不了前端报错。

**Comment by ylsy2002** [comment]
纠正一下，最后导致错误出现的操作是在管理界面修改默认配色方案等，但是由于网络波动没成功，之后出现此错误。恢复备份的数据库后问题解决。
应该是对接到vue的bug。
