### ISSUE TITLE
迁移服务器后离线下载无法删除任务和创建新任务

### ISSUE THREAD

**Issue by AHCorn** [cloudreve/Cloudreve#1524]
想请教下各位有遇到过这种情况嘛？我这边是通过直接转移Cloudreve文件来迁移到新服务器的，然后转移的时候没有断开aria的连接，还有一个正在进行的任务，在重新配置新服务器的aria后，无法删除之前的任务，提示“无法删除任务”，创建的新任务也无法正常显示和下载

**Comment by dhlun** [comment]
直接去删数据库，简单省事
