### ISSUE TITLE
能支持个人版的onedrive吗？

### ISSUE THREAD

**Issue by fadeawaylove** [cloudreve/Cloudreve#1525]
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/38212718/201053834-7aac948f-caeb-4895-850b-bc9c2cb48204.png">

现在只支持国际版和世纪互联版

**Comment by dhlun** [comment]
no
支持不了没api

**Comment by MoeCinnamo** [comment]
个人版OneDrive没有API

**Comment by HFO4** [comment]
可以使用个人版 OneDrive，创建应用时选择允许所有租户（包括个人 Microsoft 账户）
