### ISSUE TITLE
建议新增cloudflare r2储存方式

### ISSUE THREAD

**Issue by whitiy666** [cloudreve/Cloudreve#1526]
**Is your feature request related to a problem? Please describe.**
建议新增cloudflare r2储存方式

**Describe the solution you'd like**
建议新增cloudflare r2储存方式

**Describe alternatives you've considered**
建议新增cloudflare r2储存方式

**Additional context**
建议新增cloudflare r2储存方式

**Comment by jacksunhack** [comment]
Is your feature request related to a problem? Please describe.
>建议新增cloudflare r2储存方式

Describe the solution you'd like
>建议新增cloudflare r2储存方式

Describe alternatives you've considered
>建议新增cloudflare r2储存方式

Additional context
>建议新增cloudflare r2储存方式

>我也觉得可以新增一个

**Comment by hash070** [comment]
+1，R2支持无限流量的公开存储桶，如果能接入Cloudreve的话，利用R2来分享/分发大流量的文件会方便许多。
目前的3.5.3版本直接用S3对接CloudFlare R2会出现错误，希望作者有时间的话能适配一下。

附：[CloudFlare R2官方文档](https://developers.cloudflare.com/r2/)

**Comment by MoeCinnamo** [comment]
+1，希望作者可以新增一个

**Comment by cxplay** [comment]
+1

**Comment by HFO4** [comment]
请升级到 3.6.1 后参考 https://docs.cloudreve.org/use/policy/s3。
