### ISSUE TITLE
从机存储策略无法上传文件

### ISSUE THREAD

**Issue by Rockney99** [cloudreve/Cloudreve#1527]
![image](https://user-images.githubusercontent.com/42824224/201484605-3dbded16-fcd6-432e-8f03-5d02fb4ef869.png)
内网穿透搭建好后在原站可正常上传 没有设置反向代理也没有启用ssl使用从机存储策略后无法上传 查看官方文档 也没有看到有什么解决方法 纯小白一个 花了三天内网穿透 200块自己组了一台linux装的cloudreve没有公网ip实属无奈出此下策 希望大佬看到能指导一下

**Comment by zx5qzx7tie8g** [comment]
我公网也不行
