### ISSUE TITLE
求增加一个全局默认语言切换选择

### ISSUE THREAD

**Issue by dhlun** [cloudreve/Cloudreve#1536]
我看到可以更改成英文
有没有全局更改成英文的这个选择

可以做一个全局语言
可选  中文  英文
![image](https://user-images.githubusercontent.com/68416145/203570702-ff9ce407-5f31-487b-bb37-2b3ee5d57f5e.png)

**Comment by HFO4** [comment]
默认语言会跟随用户系统语言，没有必要添加全局设定。
