### ISSUE TITLE
希望增加一个多用户访问的公共文件夹

### ISSUE THREAD

**Issue by aimiku** [cloudreve/Cloudreve#1537]
**Is your feature request related to a problem? Please describe.**
希望增加一个多用户访问的文件夹。

**Describe the solution you'd like**
根据用户组授权访问的文件夹，不同用户组区分写权限。

**Describe alternatives you've considered**
直接给全体用户一个公共文件夹，只有管理员可以写也可以。

**Comment by HFO4** [comment]
Duplicated with #773
