### ISSUE TITLE
[Pro]添加一个代理域名功能

### ISSUE THREAD

**Issue by MoeCinnamo** [cloudreve/Cloudreve#1538]
**Is your feature request related to a problem? Please describe.**
当管理员设定好代理地址后，当用户访问网盘地址(例如cloudreve.org)同时生成分享链接(或文件直链)时，将会返回站点管理员预设的随机代理地址(例如cloudreve1.org)。
当用户直接访问代理地址，而不是通过分享链接(或文件直链)访问时，将自动跳转到网盘主链接。
当用户使用网盘主链接访问分享链接(或文件直链)时，将自动跳转到随机代理地址。

**Describe the solution you'd like**
添加后台设置代理地址的功能，多个代理地址可以用英文逗号分隔，支持二级域名，代理地址设置后，代理地址根域名无需购买，仅需购买主域名，但代理地址只能提供分享和直链的下载，无法进行文件上传及webdav等服务。

**Describe alternatives you've considered**
站点配置文件(config.ini)设置代理地址，多个可用英文逗号分隔

**Additional context**
当管理员未设置代理地址时，在分享、直链中返回网盘主域名，设置后将随机调用代理域名。
作用：加速分享链接和直链的下载，同时可以让分享链接更短。

附：
![来自群友的肯定](https://user-images.githubusercontent.com/101342651/203762284-e9d1a669-4ef4-4350-be96-e2ec3516edf0.jpeg)

**Comment by dhlun** [comment]
臣附议  可以
