### ISSUE TITLE
希望支持基于 AWS S3 接口协议的 Minio 私有对象存储

### ISSUE THREAD

**Issue by dragonlhp** [cloudreve/Cloudreve#154]
希望支持基于 AWS S3 接口协议的 Minio 私有对象存储，MInio 是一个开源的私有对象存储，接口协议支持 亚马逊的 S3规范 ，为企业内部支持对象存储部署，开发基本上是对s3进行少许修改即可，https://docs.min.io/docs/how-to-use-aws-sdk-for-php-with-minio-server.html

**Comment by HFO4** [comment]
目前已经支持了，文档还在编写中

**Comment by dragonlhp** [comment]
哇 实在感谢！加油！

**Comment by Janus-Xu** [comment]
> 目前已经支持了，文档还在编写中

您好，有相关的配置介绍说明吗？文档里没找到
