### ISSUE TITLE
上传10M以上文件出现504或者分片上传失败

### ISSUE THREAD

**Issue by SherryMW** [cloudreve/Cloudreve#1540]
版本为3.6.0-beta1
使用宝塔中的Nginx配置反向代理监听5121端口，重新加载配置并启动Nginx也不行
![QS@54 `LTTJRE0J8KCU M(N](https://user-images.githubusercontent.com/118236482/204082586-e83d468e-65e8-4f09-b4d5-9d47d3bbcdd4.png)
![{YT~LQ4F~76B ~(HZ{D7ON](https://user-images.githubusercontent.com/118236482/204082588-9ef6f752-0d3c-4eb6-81fa-825b61ad5a12.png)

![image](https://user-images.githubusercontent.com/118236482/204082509-2aedd1d7-f1f9-4f25-9c94-41e36324091d.png)
![image](https://user-images.githubusercontent.com/118236482/204082518-c0e2efd8-f46f-47bf-992e-e252cfc61eca.png)

**Comment by ilisuo** [comment]
你可以监听5212试一试。

**Comment by SherryMW** [comment]
> 你可以监听5212试一试。

你好，如果不监听5212我怎么打的开cloudreve来上传文件嘛
![image](https://user-images.githubusercontent.com/118236482/204082743-dc23cb71-8a39-4e42-a6b7-7e4d7a970007.png)

**Comment by topjohncian** [comment]
指不使用反向代理 直接访问5212端口
问题很可能出现在 nginx 这一层

**Comment by SherryMW** [comment]
> 指不使用反向代理 直接访问5212端口 问题很可能出现在 nginx 这一层

明白了，刚刚试了一下，直接用服务器公网:5212访问是可以上传超过10M的文件，没有出现504或者分片上传的问题，那就奇怪了，是我反向代理的配置有问题么，这个是宝塔默认配置的

**Comment by SherryMW** [comment]
> 指不使用反向代理 直接访问5212端口 问题很可能出现在 nginx 这一层

![image](https://user-images.githubusercontent.com/118236482/204083205-62778fdf-5fd3-427c-b2d8-0be41645e049.png)

我直接用目标URL地址访问上传是没问题的
反向代理配置是
![image](https://user-images.githubusercontent.com/118236482/204083281-aec4bb37-2db9-4643-8539-f3541fcc8403.png)
红框内容是我自己加的
这是nginx配置
![image](https://user-images.githubusercontent.com/118236482/204083305-f11b6a74-2c53-4fbd-99ae-27560ba5d63b.png)

**Comment by SherryMW** [comment]
解决了，反向代理需要配置成127.0.0.1:5212
