### ISSUE TITLE
设置nginx代理后白屏

### ISSUE THREAD

**Issue by yzytmac** [cloudreve/Cloudreve#1543]
按照文档中nginx的配置进行，使用ip:5251可以正常访问，使用nginx代理就白屏，按照之前issues中说的什么nginx的默认配置冲突，但是我的默认配置已经删除了，依然白屏。

**Comment by MiKing233** [comment]
nginx config貼出來看看

**Comment by hzxie** [comment]
Works with Nginx reverse proxy on my machine. Please provide your Nginx config.

**Comment by hatsuyuki280** [comment]
@hzxie 也许你可以试试使用精简一些的配置文件比如下面这个看看会不会有问题？
这个配置文件是用于http的，他在我的环境里正常工作，如果工作正常，他应该可以在 http://localhost 上可用

server {
        listen 80;
        listen [::]:80;

        index index.html;
        server_name pan.example.com;

        location / {
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_redirect off;
                proxy_pass http://127.0.0.1:5212;
        }
}

**Comment by black-fruit** [comment]
https呢

**Comment by hatsuyuki280** [comment]
你可以简单的从 [nginx的文档](https://nginx.org/en/docs/http/configuring_https_servers.html) 复制粘贴相应的字段设置ssl。
