### ISSUE TITLE
Pro版本集成更多的支付。payjs已失效

### ISSUE THREAD

**Issue by dhlun** [cloudreve/Cloudreve#1546]
能不能集成一下易支付这种第四方接口？

只有一个个人能用的当面付太少了

payjs也用不了了。官网都关闭注册了

**Comment by MoeCinnamo** [comment]
是的，我也想搞這個彩虹易支付接口，但是一直不支持

**Comment by HFO4** [comment]
3.7.0 后可通过兼容 API 对接自定义支付接口。

**Comment by topjohncian** [comment]
推广一下 https://github.com/topjohncian/cloudreve-epay
