### ISSUE TITLE
为什么服务器无法绑定IPv4

### ISSUE THREAD

**Issue by ErrorCodesForLzx** [cloudreve/Cloudreve#1547]
我启动服务器绑定的是IPv6，服务器conf.ini里面： Listen :688 这样写的
但是启动的时候我使用netstat -natp 查看发现绑定的是IPv6如何绑定IPv4呢？
![Uploading 截屏2022-12-02 13.27.55.png…]()

**Comment by liuyuxuan0723** [comment]
你好，请问你解决了不
