### ISSUE TITLE
新增多种登录方式

### ISSUE THREAD

**Issue by nanshaobit** [cloudreve/Cloudreve#1548]
是否有考虑接入其他登录方式，比如OAuth2 标准协议、QQ等第三方平台。
下图为`wiki.js`的产品截图，希望作者可以评估一下，
附：[官方文档](https://docs.requarks.io/auth)
<img width="591" alt="image" src="https://user-images.githubusercontent.com/35527084/205305884-0227d3eb-34b1-4e69-9452-2887e58fa085.png">

**Comment by wangking873** [comment]
同求
