### ISSUE TITLE
希望支持 在线办公软件 onlyoffice 的支持

### ISSUE THREAD

**Issue by dragonlhp** [cloudreve/Cloudreve#155]
希望支持 在线办公软件 onlyoffice 的支持，Onlyoffice 是一个在线web版本的office办公套件，支持私有部署，多人协作编辑，支持 文档 表格 甚至ppt 非常实用。https://www.onlyoffice.com/

**Comment by aganlove** [comment]
目前的在线预览是国内通用的网盘的做法，onlyoffice很强大，希望能够支持，给网盘锦上添花

**Comment by CJYKK** [comment]
或者给个接口/配置文件也行，我们也可以自己改~

**Comment by HFO4** [comment]
已在 3.7.0 中可用。
