### ISSUE TITLE
我在关闭Cloudrvr后发现前端还在运行

### ISSUE THREAD

**Issue by XLHYW** [cloudreve/Cloudreve#1552]
**Describe the bug**

**To Reproduce**
无，我在将Cloudreve关闭后前端仍在运行，我不知道怎么关闭

**Expected behavior**
前端和后端一起关闭
**Screenshots**
![image](https://user-images.githubusercontent.com/116472059/206112282-60319a58-1c51-4fa6-96f6-1abd415ccd60.png)
**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Edge]
 - Version [3.5.3]

**Additional context**

**Comment by NestorRay** [comment]
ctrl+F5强制刷新

**Comment by XLHYW** [comment]
> 你这是浏览器缓存吧

不是缓存问题，刷新清除了无数遍，重启完电脑都没用

**Comment by XLHYW** [comment]
> ctrl+F5强制刷新

试了，没用，它的前端文件是内嵌在程序里面的吗？

**Comment by NestorRay** [comment]
> 

主程序内置了数据库，web服务器和静态资源
```
  -c string
        配置文件路径
  -database-script string
        运行内置数据库助手脚本
  -eject
        导出内置静态资源
```
[官方文档关于静态资源](https://docs.cloudreve.org/use/zi-ding-yi-qian-duan#:~:text=%E6%82%A8%E5%8F%AF%E4%BB%A5%E5%9C%A8%E5%90%AF%E5%8A%A8%20Cloudreve%20%E6%97%B6%E5%8A%A0%E4%B8%8Aeject%20%E5%91%BD%E4%BB%A4%E8%A1%8C%E5%8F%82%E6%95%B0%EF%BC%8C%E5%B0%86%E5%86%85%E7%BD%AE%E7%9A%84%E9%9D%99%E6%80%81%E8%B5%84%E6%BA%90%E6%8F%90%E5%8F%96%E5%88%B0statics%20%E7%9B%AE%E5%BD%95%E4%B8%8B%EF%BC%9A)

**Comment by KawaiiZapic** [comment]
你把你服务器关机, 整个连电源都给他拔掉  
你就知道到底是有缓存还是真的没关掉了

**Comment by topjohncian** [comment]
被注册成 Service Worker 以后，整个前端就由浏览器本地储存提供

**Comment by XLHYW** [comment]
> 你把你服务器关机, 整个连电源都给他拔掉 你就知道到底是有缓存还是真的没关掉了

我浏览器缓存清除过，但在服务器关闭的情况下还能访问，但无法查看数据，这应该是浏览器的问题
