### ISSUE TITLE
3.6.0-beta1,多个服务端，数据库和Config一样的情况下生成的外链不一样

### ISSUE THREAD

**Issue by HAMINAVE** [cloudreve/Cloudreve#1555]
3.5.3生成的外链全部一样,分流的时候全部正常，鉴权全都一样，一个机子生成出来的链接，其他机子也认，比如
1号机：www.xx.com/api/v3/file/source/114/514.7z?sign=aabbcc
2号机：www.xx.com/api/v3/file/source/114/514.7z?sign=aabbcc
3号机：www.xx.com/api/v3/file/source/114/514.7z?sign=aabbcc
新的beta1生成的外链变成了每个机子生成出来的都不一样，一个机子生成出来的链接，其他机子不能互认
1号机：www.xx.com/f/aaa/aa.zip
2号机：www.xx.com/f/bbb/aa.zip
3号机：www.xx.com/f/ccc/aa.zip

Config只修改了数据库链接，其他配置比如密钥全部机子都一样的
数据库只修改了对应策略的存储桶，其他全部复制，包括桶ID，登录账号密码全部都是一模一样

**Comment by HFO4** [comment]
新版本中新增了中转直链，必须共享数据库和配置文件才能保证外链一致。如果需要之前的静态外链，请在用户组设置中关闭“中转外链”。

**Comment by HAMINAVE** [comment]
> 新版本中新增了中转直链，必须共享数据库和配置文件才能保证外链一致。如果需要之前的静态外链，请在用户组设置中关闭"中转外链"。

你可能不信，关闭中转外链后，直接拿到了OneDrive的链接，对，一小时的那个链接
