### ISSUE TITLE
上传大文件时提示：无法完成文件上传 LocalUpload session file placeholder not exist

### ISSUE THREAD

**Issue by yukaidi1220** [cloudreve/Cloudreve#1558]
如题，小文件没有问题，大文件就报错
报错后查看onedrive中文件，我需要上传的文件已经完整上传且校验信息无误
[![](https://pic.imgdb.cn/item/6397ae92b1fccdcd3663583c.jpg)](https://pic.imgdb.cn/item/6397ae92b1fccdcd3663583c.jpg)
[![](https://pic.imgdb.cn/item/6397aebbb1fccdcd36637382.jpg)](https://pic.imgdb.cn/item/6397aebbb1fccdcd36637382.jpg)
[![](https://pic.imgdb.cn/item/6397aeefb1fccdcd36639126.jpg)](https://pic.imgdb.cn/item/6397aeefb1fccdcd36639126.jpg)
请问这个最有可能是什么问题，分片上传、服务端回调、或是上传占位符？

**Comment by yukaidi1220** [comment]
https://pic.imgdb.cn/item/6397aeefb1fccdcd36639126.jpg
https://pic.imgdb.cn/item/6397aebbb1fccdcd36637382.jpg
https://pic.imgdb.cn/item/6397ae92b1fccdcd3663583c.jpg
相关图片

**Comment by lhz226** [comment]
反代服务器上是否有大小限制
