### ISSUE TITLE
请求添加 WebDAV 上传策略

### ISSUE THREAD

**Issue by ghost** [cloudreve/Cloudreve#156]
现在虽然已有"远程服务器"上传策略, 但是要求在 PHP 环境下部署自定义服务端, 适用范围不太广泛. 如果可以通过 WebDAV 的方式, 把文件上传到其他存储服务器上就更好了.
同时, 也请考虑一下 FTP / SFTP 等其他标准协议的支持.

**Comment by HFO4** [comment]
其他协议较难实现客户端直传，可能短期内不会增加。

**Comment by CheChris** [comment]
> 其他协议较难实现客户端直传，可能短期内不会增加。

WebDav不是支持302重定向吗？能否尝试将其作为存储方案？这将意味着更多、更广的存储选择，会扩宽Cloudreve的发展范围，同时也能获得更多的个人用户的支持。
现在的Cloudreve的云存储更多局限于S3存储，但在目前，S3类型对象存储对于个人用户来说是昂贵的，这对个人用户来说不是一个好的选择，同时也意味着Cloudreve在个人用户群体中有着一定的局限性。相对比，WebDav协议现在很多网盘厂商支持，同时更有Openlist项目做补全，将会有很好的发展前景。
对于WebDav协议也无需有过多的适配，只需兼容标准WebDav协议加302跳转的支持即可。我认为其具有不小的价值

**Comment by YUDONGLING** [comment]
锁定此 issue, 后续讨论请在 https://github.com/cloudreve/cloudreve/discussions/3433 继续进行。
Lock this issue and more discussion will be avaliable at https://github.com/cloudreve/cloudreve/discussions/3433.
