### ISSUE TITLE
更新到3.6.0正式版后運行出現[Warning] : Static resource version mismatch [Current 3.6.0-beta1, Desired: 3.6.0]，please delete "statics" folder and rebuild it.

### ISSUE THREAD

**Issue by MiKing233** [cloudreve/Cloudreve#1563]
當前路徑中沒有名爲statics的資料夾, 并且在一個新的目錄下全新執行依然會出現此[Warning], 請問報錯中所指的資料夾statics具體路徑在哪裏, 如何rebuild

![image](https://user-images.githubusercontent.com/26044744/207747296-e1ebfcf3-f625-4a12-a01d-4a06b5ff7cb4.png)

**Comment by Moment1504** [comment]
猜测是作者打包的时候**忘记更改内置静态资源的版本号**了。
这导致程序使用内置的资源时，发现版本号不匹配，于是报错。
运行`-eject`命令后在生成的“statics”文件夹里将“version.json”内的`3.6.0-beta1`改为`3.6.0`即可。

**Comment by UkokuGemini** [comment]
> 猜测是作者打包的时候**忘记更改内置静态资源的版本号**了。
> 
> 这导致程序使用内置的资源时，发现版本号不匹配，于是报错。
> 
> 运行`-eject`命令后在生成的“statics”文件夹里将“version.json”内的`3.6.0-beta1`改为`3.6.0`即可。

可行，會變為
```Warning->
Info Folder with name statics already exists，it will be used to serve static files.
```

**Comment by HFO4** [comment]
Fixed in 3.6.1.
