### ISSUE TITLE
[Feature Request] 能否允许禁用主站的离线下载

### ISSUE THREAD

**Issue by KyonCN** [cloudreve/Cloudreve#1564]
**Is your feature request related to a problem? Please describe.**
如题，因为主站的性能和硬盘都比较拉，只要进行下载就会卡死web服务。

**Describe the solution you'd like**
目前只能配置完主站和多个从站的离线下载服务后手动杀死主站的aria2服务，让离线下载服务失效。
轮询分配离线下载服务的时候，每当分配到主站时都需要再次提交以分配到从站进行。

目前版本应该负载均衡功能还未上线，所以还是会平均概率分配到主站。
据目前观察，通过杀死aria2服务的方式将主站离线下载功能禁用应该不会对其他功能造成影响。

所以是否可以允许后台管理面板中禁用主站的离线下载功能呢

**Comment by HFO4** [comment]
你把主机节点的离线下载功能关掉就行了
