### ISSUE TITLE
 Cloudreve捐赠版3.6.0无法修改“基本信息”

### ISSUE THREAD

**Issue by aaro-n** [cloudreve/Cloudreve#1565]
## 基本信息
 Cloudreve 版本信息：捐赠版3.6.0
数据库： MariaDB，10.6.11
缓存：redis
## 遇到问题
重新安装Cloudreve捐赠版3.6.0，在修改“参数设置”-“站点信息”-“基本信息”下的“主标题“、”副标题
“、”站点描述“三项时，输入信息会变为“0”，中英文输入法斗试过，浏览器隐私模式下访问也试过，都出现相同的问题。
## 录屏

https://user-images.githubusercontent.com/45537680/208037126-4ddf80f9-00fa-4da5-9806-8a75b8f86ed8.mov

**Comment by aaro-n** [comment]
直接修改的数据库

**Comment by HFO4** [comment]
Fixed in 3.6.1.
