### ISSUE TITLE
[3.6] 忘记密码页面无法通过链接打开

### ISSUE THREAD

**Issue by xb2016** [cloudreve/Cloudreve#1569]
**Describe the bug**
如题

**To Reproduce**
直接访问 https://demo.cloudreve.org/forget

**Expected behavior**
应正常显示忘记密码页面，但现在返回 404

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: MS edge
 - Version: latest

**Comment by HFO4** [comment]
Fixed in 3.6.2.
