### ISSUE TITLE
测试从机通信提示参数有误

### ISSUE THREAD

**Issue by aomsir** [cloudreve/Cloudreve#1572]
**Describe the bug**
测试从机通信，参数有误，离线下载任务可以分流到从机，但是文件中转任务没有反应

**Expected behavior**
输入参数有误 (Successfully connected to slave node, but slave returns: invalid character '<' looking for beginning of value)

**Screenshots**
<img width="885" alt="image" src="https://user-images.githubusercontent.com/60360782/208345160-6d2824f2-e4a4-4e58-9cb6-ac36fc75aaef.png">

**Desktop (please complete the following information):**
 - OS: [macOS 13.1 (22C65)]
 - Browser [Chrome]
 - Version [ 107.0.5304.121]

**Additional context**

**Comment by HFO4** [comment]
主机无法从从机读取预期的响应，非 bug。

**Comment by aomsir** [comment]
都是按照操作来的，怎么会无法读取呢

**Comment by aomsir** [comment]
> 主机无法从从机读取预期的响应，非 bug。

都是按照操作来的，怎么会无法读取呢

**Comment by topjohncian** [comment]
从机返回了一个 html 页面，请检查是否将从机端设置为 `Slave` 模式，检查 `conf.ini`

**Comment by Mtoly** [comment]
> 

我也遇到了同样的问题
排查config.ini没有问题
全程按照教程操作

**Comment by jiasswee** [comment]
同样遇到这个问题，请问接近了嘛，如何解决的，参考一下

**Comment by aomsir** [comment]
> > 
> 
> 我也遇到了同样的问题 排查config.ini没有问题 全程按照教程操作

我是由于主机设置了CDN，然后从机调用主机的心跳检测等接口的时候访问到了缓存数据，数据不一致导致的，所以出现的这个情况，我在主机上修改host文件，直接去回源源站地址就好了。

**Comment by aomsir** [comment]
> 同样遇到这个问题，请问接近了嘛，如何解决的，参考一下

我是由于主机设置了CDN，然后从机调用主机的心跳检测等接口的时候访问到了缓存数据，数据不一致导致的，所以出现的这个情况，我在主机上修改host文件，直接去回源源站地址就好了。

**Comment by jiasswee** [comment]
解决了，我是直接在CDN内把从机ip加入白名单



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年10月13日 13:58 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [cloudreve/Cloudreve] 测试从机通信提示参数有误 (Issue #1572) |

同样遇到这个问题，请问接近了嘛，如何解决的，参考一下

我是由于主机设置了CDN，然后从机调用主机的心跳检测等接口的时候访问到了缓存数据，数据不一致导致的，所以出现的这个情况，我在主机上修改host文件，直接去回源源站地址就好了。

**Comment by sleepyjoeschool** [comment]
也遇到这个问题, 后面发现是白名单加错了。
IP白名单必须是源服务器IP和节点IP。
然后就是把TLS限制关闭, Cloudreve疑似在用低版本的TLS
