### ISSUE TITLE
为储存策略单独设置使用中转直接链接

### ISSUE THREAD

**Issue by cxplay** [cloudreve/Cloudreve#1579]
新版本加入了中转直链很好, 但只能针对用户组开启. 但实际部分储存策略完全不需要中转, 本身就已经是直接链接, 如果再套上一层中转链接, 就显得画蛇添足. 希望能够针对储存策略开启和关闭中转直链功能.

**Comment by AH-dark** [comment]
Perhaps this helps with statistics, authentication, tracking?

**Comment by cxplay** [comment]
> Perhaps this helps with analysis, authentication, tracking?

Unfortunately I don't need these at the moment, but I have to say that it makes sense for statistical analysis. 
I still think that at least the user should be given the freedom to control these features on and off as well.

**Comment by AH-dark** [comment]
> > Perhaps this helps with analysis, authentication, tracking?
> 
> Unfortunately I don't need these at the moment, but I have to say that it makes sense for statistical analysis. I still think that at least the user should be given the freedom to control these features on and off as well.

Customizability can be tedious in this part I think.
