### ISSUE TITLE
S3 储存策略无法获取非中转的直接链接.

### ISSUE THREAD

**Issue by cxplay** [cloudreve/Cloudreve#1580]
- 程序版本: 3.6.2
---
S3 储存策略无法获取非中转的直接链接. 在对应用户组关闭 "使用重定向的外链" 后获取直接链接显示 "Failed to get source link", 即使储存策略是公共访问类型, 也无法获取.  
开启了 "使用重定向的外链" 后能够正常获取, 对于公开访问的储存桶也能正常跳转到原始直接链接地址.

**Comment by r54yhe3gh34gw43** [comment]
有同样的问题，公开的存储桶可以点击 “下载”  然后再复制链接
