### ISSUE TITLE
更换头像后不生效问题

### ISSUE THREAD

**Issue by LiuNianJiang** [cloudreve/Cloudreve#1581]
新版本3.6.2更新后修改头像不会立即生效
demo站点测试问题依旧
似乎是添加了缓存？但为什么要在头像这个上面添加缓存？

**Comment by AH-dark** [comment]
@huang545 前端sw干的坏事吧

**Comment by topjohncian** [comment]
https://github.com/cloudreve/Cloudreve/blob/8dafb4f40a7c28b8ddcc4e8eff89c15d6a0cb8c1/routers/router.go#L209
50a3917a651becd9d85f71c8aa439df3321eb335

可以在后台更改此项
![image](https://user-images.githubusercontent.com/45138629/208926720-15a5300a-daa7-44b1-9869-a93f39f27f95.png)

**Comment by LiuNianJiang** [comment]
> https://github.com/cloudreve/Cloudreve/blob/8dafb4f40a7c28b8ddcc4e8eff89c15d6a0cb8c1/routers/router.go#L209
> 
> 
> [50a3917](https://github.com/cloudreve/Cloudreve/commit/50a3917a651becd9d85f71c8aa439df3321eb335)
> 可以在后台更改此项 ![image](https://user-images.githubusercontent.com/45138629/208926720-15a5300a-daa7-44b1-9869-a93f39f27f95.png)

这里的修改会影响到其他地方的缓存设置
而且头像这个东西完全没有必要去做缓存吧，不然更换头像的意义何在

**Comment by RobKing9** [comment]
这个界面是在哪里？
