### ISSUE TITLE
OneDrive储存策略直链获取存在错误

### ISSUE THREAD

**Issue by nyancatda** [cloudreve/Cloudreve#1582]
使用的是捐赠版，开源版本没有测试
在3.5.3版本中获取到的链接为https://{{host}}/api/v3/file/source/{{id}}/{{file}}，这是可以正常工作的
但是在3.6.2版本中，获取到的链接却变成了原始的直链，这将导致链接会在一定时间后过期，从而影响引用资源使用

这是新版本特性还是bug，如果是bug希望能尽快修复

**Comment by ilisuo** [comment]
进入后台 -用户组-开启 使用重定向的外链

**Comment by nyancatda** [comment]
> 进入后台 -用户组-开启 使用重定向的外链

可以使用了，十分感谢

希望下次这种破坏式更新可以写在更新日志里面

**Comment by imouup** [comment]
> > 进入后台 -用户组-开启 使用重定向的外链
> 
> 可以使用了，十分感谢
> 
> 希望下次这种破坏式更新可以写在更新日志里面

我并没有在用户组设置中找到该选项，请问可以告诉我在哪里吗

**Comment by ilisuo** [comment]
用户组最下面

![](https://pan.ilisuo.cn/f/7rsl/A921F78D-E055-4F43-8D24-AC81D6EC528A.png)

**Comment by imouup** [comment]
好的谢谢，我发现是因为我使用的不是最新的前端导致看不到这个选项
