### ISSUE TITLE
更新到3.6.2版本后访问/forget还是404状态

### ISSUE THREAD

**Issue by callng** [cloudreve/Cloudreve#1584]
**Describe the bug**
手动刷新或访问/forget密码找回页面提示404页面不存在

**To Reproduce**
先访问/login登录页，点击忘记密码切换到找回密码页面后F5刷新网页后显示HTTP404

**Expected behavior**
手动访问/forget正常显示页面

**Screenshots**
![1](https://user-images.githubusercontent.com/64207250/209147311-0fc9fb5a-7ba0-4b33-8f25-c36c7a46198b.png)

![2](https://user-images.githubusercontent.com/64207250/209147351-e0ca5e3f-5bdc-42a9-b488-82bca2b8a6e4.png)

**Desktop (please complete the following information):**
Windows10，Edge版本 108.0.1462.54 (正式版本) (64 位)

**Smartphone (please complete the following information):**
Redmi K50 G Android13 默认小米浏览器

**Additional context**
以下是我的反向代理设置

#PROXY-START/

location /
{
    proxy_pass http://127.0.0.1:5212;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header REMOTE-HOST $remote_addr;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection $connection_upgrade;
    proxy_http_version 1.1;
    proxy_hide_header Upgrade;

    add_header X-Cache $upstream_cache_status;

    #Set Nginx Cache
    
    
    set $static_file5habswgC 0;
    if ( $uri ~* "\.(gif|png|jpg|css|js|woff|woff2)$" )
    {
    	set $static_file5habswgC 1;
    	expires 1m;
        }
    if ( $static_file5habswgC = 0 )
    {
    add_header Cache-Control no-cache;
    }
}

#PROXY-END/

**Comment by topjohncian** [comment]
尝试更新 Service Worker
![image](https://user-images.githubusercontent.com/45138629/209180577-acc2a1ea-bf59-4d35-9689-23b11ef6fd72.png)
![image](https://user-images.githubusercontent.com/45138629/209180717-b2c48932-b36c-4330-bbfa-06cc6e31ba2a.png)

**Comment by callng** [comment]
> 尝试更新 Service Worker
> ![image](https://user-images.githubusercontent.com/45138629/209180577-acc2a1ea-bf59-4d35-9689-23b11ef6fd72.png)
> ![image](https://user-images.githubusercontent.com/45138629/209180717-b2c48932-b36c-4330-bbfa-06cc6e31ba2a.png)
> 
> 

稍后我回去试一试

**Comment by callng** [comment]
@topjohncian 没有效果

**Comment by callng** [comment]
@topjohncian 站点启用HTTPS后访问/forget正常了！
