### ISSUE TITLE
3.6.2版本，COS存储，通过WebDav上传的图片无法生成缩略图

### ISSUE THREAD

**Issue by lujq96** [cloudreve/Cloudreve#1589]
通过WebDav同步了一批图片，无法生成缩略图。
下载其中一张图片，在云端删除后，从网页端重新上传，能正常生成缩略图。
尝试过3.3.1版本和3.6.2版本，问题均存在。
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/34331938/209973929-0c7aa1ca-7eec-4b54-ae53-e298a03228fd.png">

**Comment by cameron-chen** [comment]
遇到了类似的问题。

情况描述：本地存储，通过 webdav 上传图片没有缩略图，同样的图片，通过网页端上传有缩略。

搜了一番 issues，没有找到解决方案。 @HFO4 请问有办法解决这个问题吗？

比如： 
- 定期为没有缩略图的照片生成缩略图
- 手动执行缩略图的生成

**Comment by HFO4** [comment]
3.8 中会试图解决这个问题。

**Comment by cameron-chen** [comment]
好的！非常感谢 HFO4 创造的这款软件，基础体验异常优秀，期待 3.8。

BTW，有同样问题的朋友，安卓上可以用 Solid Explorer 浏览图片，它会手机上自动生成缩略图。

**Comment by HFO4** [comment]
Fixed in 3.8.0-beta1.
