### ISSUE TITLE
windows捐助版3.6.2支付宝支付出错：內部错误 (Failed to initialize payment client)

### ISSUE THREAD

**Issue by KuangYeXiaoWu** [cloudreve/Cloudreve#1596]
用支付宝支付时，出现提示：內部错误 (Failed to initialize payment client)

本以为是因为是我用了内网穿透。才造成的这个错误。

但当我在阿里云用windows服务器上测试时，同现了以上同样的错误信息。

而用linux版本的程序，在linux服务器上使用就一切正常。

分析这应该是windows版本的程序有问题。不知道。有没有人遇到过和我一样的问题。

**Comment by HFO4** [comment]
https://github.com/cloudreve/Cloudreve/issues/496

**Comment by HFO4** [comment]
todo: 需要将这一信息加入到文档中。
