### ISSUE TITLE
Cloudreve conflict with other flask app running in local machine

### ISSUE THREAD

**Issue by weibaozi** [cloudreve/Cloudreve#1597]
I ran a new flask app in my machine with Nginx on it. The default URL keeps jumping to /login.
e.g. The link for the new flask app example.com. It automatically jumps to example.com/login with Cloudreve login page. Any way to solve this?
**Tested on Windows Chrome, edge, and Andriod Chrome.**

**Comment by topjohncian** [comment]
There is no solution to deploy Cloudreve on subdirectories. Another workaround is to deploy on a subdomain.

Related discussion in Chinese: #1129

**Comment by weibaozi** [comment]
Thank you for the comment. My example is a little off. Let me give another one. My cloudreve is running at couldreve.example.com. The other app is running at app.example.com. When I am trying to access app.example.com, it automatically goes to its subdirectory: app.example.com/login. Which is the default subdirectory for cloudreve.example.com when the first login.

**Comment by topjohncian** [comment]
Can you upload a screenshot or a video to show how to reproduce?

**Comment by weibaozi** [comment]
After I restart my server, it is working properly. But it is still requesting things from Clourdreve repository like shown in the picture.
![5AN}Y$( 7G)MQD$09$1`8KN](https://user-images.githubusercontent.com/58459172/211240693-379f829a-caa6-4f41-9af6-1011fdc7c621.png)

**Comment by HFO4** [comment]
> After I restart my server, it is working properly. But it is still requesting things from Clourdreve repository like shown in the picture. ![5AN}Y$( 7G)MQD$09$1`8KN](https://user-images.githubusercontent.com/58459172/211240693-379f829a-caa6-4f41-9af6-1011fdc7c621.png)

None of theses files are from Cloudreve. And I believe this issue is off topic.
