### ISSUE TITLE
版本V3.6.2试用发现的一些不足和建议

### ISSUE THREAD

**Issue by WindyWolf007** [cloudreve/Cloudreve#1601]
1. 没有文件回收站之类的防误删机制。
2. 界面响应虽然迅速，但回馈感比较诡异，UI布局容易误操作，尤其删除文件和账户的这些敏感操作，没有缓冲一碰就删（删除账户后文件一同全部消失，后果比较严重）。
3. 生成分享后，点击那个分享链接的按钮没有反应，只能手工复制，且只能链接和分享码分别复制。
4. 分享出的文件，若禁止预览，打包下载时很大几率是个空压缩包，所有文件的大小都是23B。
5. 分享若能有指定分享人就好了。

**Comment by KuangYeXiaoWu** [comment]
支持

**Comment by mydrivemall** [comment]
目前我在使用PRO版，也是发现了几个问题：
1.积分下载需要用户注册登录后账户有足够积分才可以下载，同时登录成功后跳转的并非分享文件链接，而是用户网盘主页，那么用户就需要再次复制分享链接才可以下载，也就是说下载个积分文件用户需要操作多次，希望后续更新能够解决这个问题。比如加入免登录付费下载。可以考虑直接弹窗让用户输入邮箱即可匿名付费下载。
2.对于已经注册登录的用户，能否在积分不足的情况下，提示用户积分不足，同时跳转到积分充值界面，引导用户充值积分。目前版本是直接提示当前用户组无法进行操作，无任何引导跳转动作。
3.邮箱激活问题，配置好SMTP后，进行邮箱测试没有问题，但是新用户在注册的时候，收不到激活邮件。
4.还有一个小问题就是语言问题，前端能否增加一个中文英语选项，由用户自行根据需求进行选择。
5.希望增加PayPal支付通道，如果用户群体是海外的话，目前的支付通道无法应付。
