### ISSUE TITLE
Some suggestion about upload request

### ISSUE THREAD

**Issue by ErrorCodesForLzx** [cloudreve/Cloudreve#1602]
@HFO4 
For dear cloudreve Developer:
EN:
When I use the cloudreve Server that I found cloudreve has no Android client,I got some ideas: I can develop a free and open source Cloudreve Android client , I developed very smoothly and completed most of the work. But has only one problem:The file upload by progress callback,I found your chunk upload request packet is Fixed size in response ,So it is difficult to finish it with progress callback,I wish that: Could you please modify the upload post request packet chunk size by  custom settings instead of fix size(25MB)
 Thank you to read it!
My project: https://github.com/ErrorCodesForLzx/CloudreveZX

**Comment by HFO4** [comment]
The chunk size is not fixed, it's parameterized at https://github.com/cloudreve/Cloudreve/blob/master/models/policy.go#L61 .
