### ISSUE TITLE
无法获取外链

### ISSUE THREAD

**Issue by HJZ0713** [cloudreve/Cloudreve#1612]
版本3.6.2
七牛云存储开启”允许获取外链“及”重定向的外链“
右键菜单中没有”获取文件外链“选项
版本3.4.X测试正常

**Comment by Cicini** [comment]
相同问题
存储为OneDrive

**Comment by HJZ0713** [comment]
Onedrive及其他都无法获取，且pro版正常

**Comment by HFO4** [comment]
需要用户组中批量外链数量大于0，且存储策略开启允许获取外链。

**Comment by HJZ0713** [comment]
已解决！

**Comment by Cicini** [comment]
不说都没发现那个地方是留空的(
