### ISSUE TITLE
本地存储策略导入的文件在网盘执行删除操作，直接将源文件&文件夹删除。

### ISSUE THREAD

**Issue by lt9** [cloudreve/Cloudreve#1616]
**Describe the bug**
任何一个网盘，导入的文件或者分享链接来源的文件执行删除操作期望都是解除与用户的关联关系，而非不需要二次确认的直接删除源文件，这个操作导致SSD上的文件直接无了，如果给个Lable这个肯定是紧急的线上BUG。

**To Reproduce**
1. 进入后台管理
2. 导入本地存储策略文件 | 文件夹
3. 进入用户网盘
4. 删除刚刚导入的文件夹
5. SSH登录服务器
6. 查看导入 的源文件和文件夹
7. 发现文件全部丢失

**Expected behavior**

**期望所有删除操作不会删除源文件，所有对导入文件做的删除操作不删除源文件。**

**Screenshots**

![image](https://user-images.githubusercontent.com/35452254/214785750-ce2a8fab-19a4-4041-93c8-da2b0a6c2a27.png)

**版本**
捐赠版 3.6.2 | Web端

希望完善一下。这个操作太危险了，本次仅仅是删除了我这边的一些照片，如果是重要的资料。用于生产则后果不堪设想

**Comment by bobsword** [comment]
对，可以加个解除关联而不删除源文件的选项

**Comment by lt9** [comment]
这个操作今天真实吓死我，还好我删除的文件夹本身是从另一个设备上copy来的。

暂时不敢用了，先作为学习go的demo二开吧

**Comment by HFO4** [comment]
Will track in #789.

**Comment by GreenTeodoro839** [comment]
@lt9 免费版就是这么设计的，删除文件自动删除源文件，pro版因为可以转存，所以删除文件只是解除关联

**Comment by lt9** [comment]
@GreenTeodoro839 
我是pro
1. 转移存储策略是可以建立多个存储策略。相当于在多个盘冗余
2. issue提到的是导入文件，删除。
