### ISSUE TITLE
Pro版本新增第三方支付接口的小小提议

### ISSUE THREAD

**Issue by EMCloud** [cloudreve/Cloudreve#1618]
## Pro版本新增第三方支付接口的小小提议
首先非常非常非常感谢大佬辛苦的制作的软件，本人已购买Pro，并在国外服务器上安装了CD
就是因为这个原因国内无法备案导致官方接口下不来，无法有效支付
所以非常非常非常建议加一些第三方的支付接口，这对我以及很多人非常重要
万分感谢
敬请参考，新年快乐，望管理大佬能够回复

**Comment by HFO4** [comment]
3.7.0 后可通过兼容 API 对接自定义支付接口。

**Comment by topjohncian** [comment]
推广一下 https://github.com/topjohncian/cloudreve-epay
