### ISSUE TITLE
关于CLOUDREVE PRO3.6.2使用过程中出现的几个问题及其建议，希望开发者能够改进一下。

### ISSUE THREAD

**Issue by mydrivemall** [cloudreve/Cloudreve#1619]
目前我在使用PRO版，也是发现了几个问题：
1.积分下载需要用户注册登录后账户有足够积分才可以下载，同时登录成功后跳转的并非分享文件链接，而是用户网盘主页，那么用户就需要再次复制分享链接才可以下载，也就是说下载个积分文件用户需要操作多次，希望后续更新能够解决这个问题。比如加入免登录付费下载。可以考虑直接弹窗让用户输入邮箱即可匿名付费下载。
2.对于已经注册登录的用户，能否在积分不足的情况下，提示用户积分不足，同时跳转到积分充值界面，引导用户充值积分。目前版本是直接提示当前用户组无法进行操作，无任何引导跳转动作。
3.邮箱激活问题，配置好SMTP后，进行邮箱测试没有问题，但是新用户在注册的时候，收不到激活邮件。
4.还有一个小问题就是语言问题，前端能否增加一个中文英语选项，由用户自行根据需求进行选择。
5.希望增加PayPal支付通道，如果用户群体是海外的话，目前的支付通道无法应付。

**Comment by zxcv-12345** [comment]
> 

第三个那个邮件的问题应该是被邮件服务商识别成垃圾邮件了他那个自带的激活邮件的模板不太行

**Comment by zxcv-12345** [comment]
> 目前我在使用PRO版，也是发现了几个问题： 1.积分下载需要用户注册登录后账户有足够积分才可以下载，同时登录成功后跳转的并非分享文件链接，而是用户网盘主页，那么用户就需要再次复制分享链接才可以下载，也就是说下载个积分文件用户需要操作多次，希望后续更新能够解决这个问题。比如加入免登录付费下载。可以考虑直接弹窗让用户输入邮箱即可匿名付费下载。 2.对于已经注册登录的用户，能否在积分不足的情况下，提示用户积分不足，同时跳转到积分充值界面，引导用户充值积分。目前版本是直接提示当前用户组无法进行操作，无任何引导跳转动作。 3.邮箱激活问题，配置好SMTP后，进行邮箱测试没有问题，但是新用户在注册的时候，收不到激活邮件。 4.还有一个小问题就是语言问题，前端能否增加一个中文英语选项，由用户自行根据需求进行选择。 5.希望增加PayPal支付通道，如果用户群体是海外的话，目前的支付通道无法应付。

第三个那个邮件的问题应该是被邮件服务商识别成垃圾邮件了他那个自带的激活邮件的模板不太行
