### ISSUE TITLE
请求  login.chunk.js 404

### ISSUE THREAD

**Issue by libaibuaidufu** [cloudreve/Cloudreve#162]
首页可以加载 css js
login 等 其他页面 无法加载  请求的  都是  带有chunk的 js css

**Comment by HFO4** [comment]
请参考这里的说明：
https://cloudreve.github.io/docs/#/faq?id=%e5%ae%89%e8%a3%85%e5%90%8e%e6%89%80%e6%9c%89%e9%a1%b5%e9%9d%a2%e7%a9%ba%e7%99%bd

**Comment by libaibuaidufu** [comment]
已解决

**Comment by Chairowell** [comment]
参考说明已经404了
