### ISSUE TITLE
无法连接到从机

### ISSUE THREAD

**Issue by Decem6er** [cloudreve/Cloudreve#1621]
主机测试从机通信时提示：`输入参数有误 (Failed to connect to slave node: Post "[https://【我从机的网址】/api/v3/slave/ping](https://xn--56jc027udqhs5nrjh202a8tp/api/v3/slave/ping)": x509: certificate is valid for 【我主机的网址】, not 【我从机的网址】)`

我已确认从机上部署的SSL证书与从机的网址匹配

主机系统：Ubuntu 20.04
主机部署方式：使用nginx反代本机端口，且已部署SSL，位于公网，已使用CDN
Cloudreve版本：社区版 3.6.2

从机系统：Ubuntu 20.04.3 LTS x86_64
从机部署方式：使用nginx反代本机端口，且已部署SSL，位于内网环境，无公网IP，所以使用了frp进行内网穿透
Cloudreve版本：社区版 3.6.2

**Comment by panjd123** [comment]
请问这是怎么解决的，我跟你是一样的场景

**Comment by Decem6er** [comment]
> 请问这是怎么解决的，我跟你是一样的场景

当时好像是主机和从机的 Cloudreve 的版本不一致导致的。

**Comment by Decem6er** [comment]
> 请问这是怎么解决的，我跟你是一样的场景

不好意思，太久了，我也忘了是怎么解决的，只记得确实不是 Cloudreve 的问题。可以考虑排查 CDN 和 nginx 等。
