### ISSUE TITLE
Docker版本离线下载磁力不可用

### ISSUE THREAD

**Issue by joyoner** [cloudreve/Cloudreve#1627]
**Describe the bug**
通过官方文档部署docker cloudreve+aria2，新建离线任务，点击创建任务按钮，按钮一直转圈圈。

**To Reproduce**
1、参考文档 https://docs.cloudreve.org/getting-started/install 中的Docker Compose章节部署。
2、创建目录结构。
3、创建docker-compose.yml文件，自定义rpc 密钥，docker-compose up -d成功
4、登录控制面板，在离线下载节点中，编辑离线节点，按以下内容编辑：
[不可修改] RPC 服务器地址 => http://aria2:6800
[可修改, 需保持和 docker-compose.yml 文件一致] RPC 授权令牌 => your_aria_rpc_token
[不可修改] Aria2 用作临时下载目录的 节点上的绝对路径 => /data
5、点击“测试aria2通信”，提示成功。
6、返回主页，打开离线下载导航，添加新任务。
7、新建离线任务，点击创建任务按钮，按钮一直转圈圈。

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by vvisionnn** [comment]
无法复现，aria 测试通信成功说明链接没问题，需要更多信息
如果可以请附带
- 点击下载之后的请求返回结果，chrome 控制台或者其他浏览器控制台可以查看
- 离线下载文件链接

> cannot repro this err, seems the aria2 is connected, need more info

Please attach if you could
- The response of this action, you can check this from the dev tools from chrome or other web browser
- The file download link you used in this error

**Comment by joyoner** [comment]
确认是网络问题，网络发出后一直在请求，但是无响应。属于单点问题，后续自行排查解决。
