### ISSUE TITLE
关于cloudflare开盾之后cloudreve出错的疑问

### ISSUE THREAD

**Issue by Lycorisplus** [cloudreve/Cloudreve#1630]
在cloudflare中 我们可以开启质询等来阻挡DDos攻击。但是当我开启这个功能之后，访问cloudreve并没有出现5秒的质询画面，而是出现了“Backend is not running!”
我认为原因是cloudreve在本地进行了缓存，使得访问网页时就会先加载本地缓存的程序：
![image](https://user-images.githubusercontent.com/55988289/217276891-1aee8586-bac8-4e88-91ad-260e0520d1f1.png)
但是由于盾的原因使得cloudreve无法访问后端导致出错。
我的版本为3.6.2 Pro
我该如何调整cloudreve设置 或者调整cloudflare设置 亦或者调整宝塔（nginx）设置来避免这种情况？
或者能否让cloudreve增加选项，不在浏览器进行缓存呢？
谢谢！

**Comment by wsndshx** [comment]
简单的方法：把 `/api` 加入到白名单？

**Comment by 2228515561** [comment]
> 简单的方法：把 `/api` 加入到白名单？

谢谢你的方法。但是我理解你说的是在cloudflare绕过cloudreve的缓存以达到可以实时查看更改的方法。而我想要的效果是，在本地浏览器禁用cloudreve的缓存以达到浏览器先显示cloudflare的质询页，再加载cloudreve的前端的效果。但是我不知道如何禁用浏览器缓存，甚至这只是我的猜测，我也不知道产生“Backend is not running”的真正原因。

**Comment by 2234839** [comment]
我开启 cloudflare 之后 对文件增删改的请求都不行，查询却没问题
