### ISSUE TITLE
外部云存储回退版本后，云盘无法在线打开文件

### ISSUE THREAD

**Issue by aoemon** [cloudreve/Cloudreve#1635]
cos开启版本控制后，云盘在线编辑文件并保存修改，在cos回退版本后，云盘无法在线打开文件，下载正常（内容是回退后的版本）

其他的云存储产品没有试过

请问这种有什么好的处理办法？目前我是云盘删除后重新导入回退后的文件

**Comment by Phlphat746** [comment]
ขอโทษทีครับงานมันยุ่งเหลือเกินมีเวลาก็จะแวะเข้ามาทำฃงานตลอดนะครับ.
