### ISSUE TITLE
社区版离线下载不支持种子吗

### ISSUE THREAD

**Issue by ForgetPswd** [cloudreve/Cloudreve#1649]
我看到介绍里说离线下载是支持种子的。可是我的版本里只支持ftp、http、磁力链接。
是社区版不支持磁力链接吗？
![1](https://user-images.githubusercontent.com/70511069/222095642-f72c4ae0-38a8-408e-a3ab-4c042719dd58.png)

**Comment by Syz87** [comment]
我的是上传了，但是通过种子创建离线任务显示：创建任务出错  日志只显示/api/v3/aria2/torrent/vLEhW

**Comment by Syz87** [comment]
> 我的是上传了，但是通过种子创建离线任务显示：创建任务出错 日志只显示/api/v3/aria2/torrent/vLEhW

但是aria又没显示任务，麻了
