### ISSUE TITLE
小白求助，怎么设置禁止通过ip地址访问那？

### ISSUE THREAD

**Issue by wukong999** [cloudreve/Cloudreve#1651]
Windows server环境，怎么才能设置禁止通过ip地址访问那？

**Comment by GreenTeodoro839** [comment]
@wukong999 使用防火墙拦截5212端口

**Comment by wukong999** [comment]
> @wukong999 使用防火墙拦截5212端口

拦截了之后，也不能通过域名访问了吧

**Comment by HFO4** [comment]
Out of scope.
