### ISSUE TITLE
希望接入VAPTCHA验证码

### ISSUE THREAD

**Issue by 12234254** [cloudreve/Cloudreve#1653]
google的reCAPTCHA验证码在中国大陆常常抽风，希望接入VAPTCHA验证码,大陆访问更快,最重要的是可以白嫖且延迟低
官网:https://www.vaptcha.com/

**Comment by 12234254** [comment]
文档地址:https://www.vaptcha.com/document/index.html

**Comment by 12234254** [comment]
点错了...

**Comment by cevin** [comment]
或者接入地址改成 https://www.recaptcha.net/
