### ISSUE TITLE
通过反代HTTPS访问，出现404错误

### ISSUE THREAD

**Issue by iranee** [cloudreve/Cloudreve#1654]
通过自己的域名反代访问，url连接中的%2F不可识别为/（QNAP系统自带的反向代理）
通过第三方的内网穿透可以正常通过HTTPS访问。
![Snipaste_2023-03-03_19-55-30](https://user-images.githubusercontent.com/19551701/222715176-96063581-f1f5-417f-a2b3-6ecad78149b4.jpg)
![Snipaste_2023-03-03_19-56-05](https://user-images.githubusercontent.com/19551701/222715187-10691393-238d-43e9-912b-164f82d55900.jpg)
![Snipaste_2023-03-03_19-56-43](https://user-images.githubusercontent.com/19551701/222715192-1a16b150-aa8d-4a24-b6c1-f0043e098e35.jpg)

**Comment by GreenTeodoro839** [comment]
@iranee 请根据 https://docs.cloudreve.org/getting-started/install 手动修改apache配置文件，不要使用nas自带的反向代理
