### ISSUE TITLE
登陆失败

### ISSUE THREAD

**Issue by lliioollcn** [cloudreve/Cloudreve#166]
![图片](https://user-images.githubusercontent.com/44719954/58716948-b305a680-83fc-11e9-953c-2d6a66276b8d.png)

**Comment by lliioollcn** [comment]
![图片](https://user-images.githubusercontent.com/44719954/58716882-9b2e2280-83fc-11e9-9f79-e00d7d43b661.png)
此为数据库图片

**Comment by emadons** [comment]
我也是这个问题，层主解决了吗？

**Comment by HFO4** [comment]
V3版本中已解决此问题
