### ISSUE TITLE
分片上传失败: Invalid request

### ISSUE THREAD

**Issue by RWGLQJ** [cloudreve/Cloudreve#1664]
文件名：
往期素材.z01
文件大小：
300.0 MB (1 个分片, 每个分片 2.0 GB)
存储策略
onedriver
存储路径：
[/BilBil](javascript:void)
上传会话：
23 小时后 过期
错误信息：
分片上传失败: Invalid request
![S_AP7BGQAX8QF)}AQQV(Q7B](https://user-images.githubusercontent.com/79353322/224325990-35dbb0fd-0fc8-4545-8b30-fed8408ff7eb.png)
好像是大于了300m的都会这样

**Comment by HFO4** [comment]
分片大小不要超过 200 MB。

**Comment by RWGLQJ** [comment]
> 
ok的解决了
