### ISSUE TITLE
Collabora Online在线文档编辑UI语言改进提议

### ISSUE THREAD

**Issue by baiwulin** [cloudreve/Cloudreve#1665]
在Cloudreve论坛中了解到多位用户使用Collabora Online进行在线编辑时界面语言是英文的问题，自己测试后发现也是如此，并且此问题并非是根据操作系统默认语言改变的。

我在Collabora Online官方社区中已查阅到相关问题，了解到更改UI的默认语言必须要在URL参数中设置，即启动在线编辑时还应传参lang=xxx，并且此方法目前是唯一可改变默认UI语言的。

官方社区中关于此问题的链接如下：
[UI default language](https://forum.collaboraonline.com/t/ui-default-language/1664)

希望作者能在下个版本中在后台增加一个默认语言设置的选项，并在前台适配

![1](https://user-images.githubusercontent.com/75801960/224462522-e7278543-ac30-49f8-b16d-02cf4f4e09c0.png)

![2](https://user-images.githubusercontent.com/75801960/224462536-75beb14c-33e5-41ba-bccb-cdff66bf4f57.png)

**Comment by HFO4** [comment]
Fixed in da1eaf2d1f568890676afd2099b80fdd531423b9.
