### ISSUE TITLE
添加 OneDrive/SharePoint 存储策略中，在 新建客户端密码 按钮下，截止期限现在没有 "从不"，目前最长两年

### ISSUE THREAD

**Issue by FelixTennouji** [cloudreve/Cloudreve#1668]
添加 OneDrive/SharePoint 存储策略中，在 新建客户端密码 按钮下，截止期限现在没有 "从不"，目前最长两年

**Comment by LamGC** [comment]
这个是微软的问题来着，而且这个限制是网页限制的，可以百度或 Google 一下用 Firefox 等工具抓包改数据创建“永久”密码。

**Comment by BradleyBao** [comment]
是的，你可以使用 Tamper Dev 拦截并将截至日期修改为 9999 年，也就是永久

**Comment by HFO4** [comment]
两年也是可以的，到期前记得换个新的填进去就行。
