### ISSUE TITLE
创建队里是出现错误，我的token没有问题

### ISSUE THREAD

**Issue by halfhoney2018** [cloudreve/Cloudreve#167]
Cloudreve Queue Go Version 1.0
Author: AaronLiu <abslant@foxmail.com>

2019/06/05 13:26:09 [INFO] Config information:  {FkEpi7cGEftkratZafTzYKYt5YhwGWA6wtaXrYnd8N2X8bAGaxidNrFHBmSAzSSP https://wangpan.usegoods.com/Queue 4 
1} 
2019/06/05 13:26:09 [ERROR] Auth failed, please verify your token, HTTP ERROR 403

**Comment by HFO4** [comment]
检查配置文件格式、换行符是否有异常
