### ISSUE TITLE
添加存储策略时, 为什么要求站点URL能够被外网正常访问呢?

### ISSUE THREAD

**Issue by cuixiping** [cloudreve/Cloudreve#1672]
我的理解, 只要能够读写某个云(如腾讯云)的文件(对象)和列表, 就应该可以使用Cloudreve, 我用 localhost 试了一下确实不行, 但不知道为什么会这样. 我们不是有token和key那些认证所需信息, 就可以读取云上文件了么, 并不需要云服务器来读我本地啊.

我理解不对之处, 还请指正

**Comment by xx6z8v** [comment]
或许还需要授权

**Comment by HFO4** [comment]
为保证上传可控，某些存储策略需要存储端向 Cloudreve 发送回掉。

**Comment by cuixiping** [comment]
> 为保证上传可控，某些存储策略需要存储端向 Cloudreve 发送回调。

哪些存储策略需要存储端向 Cloudreve 发送回调?
