### ISSUE TITLE
新功能:群组文件夹

### ISSUE THREAD

**Issue by nAnderYang** [cloudreve/Cloudreve#1673]
**Is your feature request related to a problem? Please describe.**
多个用户一个群组，并协作 共享文件。

**Describe the solution you'd like**
再群组文件夹内 群组管理员可以控制文件夹的访问协作，上传，删除权限？

**Describe alternatives you've considered**
最开始想通过webdav api 实现，但是只能实现文件夹的访问控制 无法控制文件访问，也无法控制删除（只读的清空下)同时影响webdav的正常使用.

**Comment by lonelyor** [comment]
同求

**Comment by sx799723** [comment]
疯狂求

**Comment by zhangwei2003** [comment]
有这个功能必开捐助版啊

**Comment by actionee** [comment]
同求！
