### ISSUE TITLE
修改Office文档预览文件大小后，WOPI 客户端无法预览office文档

### ISSUE THREAD

**Issue by wskyo129** [cloudreve/Cloudreve#1674]
**Describe the bug**
在使用docker配置了Collabora Online服务后，最大只支持4MB的文档预览。于是在管理面板调整【参数设置】-【图像与预览】-【文件预览】-【文档在线编辑最大尺寸】保存后，网盘内Office文档的【打开】按钮消失，（图片、视频、PDF的【打开】按钮仍然存在且可用）。测试了两台服务器都出现这个情况，且重启服务、重启服务器均不能恢复。

服务器1：银河麒麟高级服务器（无GUI）Kylin V10 SP1 Arm64
服务器2：银河麒麟高级服务器（带GUI）Kylin V10 Arm64
![image](https://user-images.githubusercontent.com/20489142/227419068-427d0101-921e-443d-8af8-d0ac0452639b.png)
![62eb07824990c28dde2f80771af6bd3](https://user-images.githubusercontent.com/20489142/227439956-6b292a56-fb3b-4c54-a685-314a67dc4ff6.png)

**Comment by HFO4** [comment]
你的 WOPI 服务可能挂了。每次保存这一页的设置之后，Cloudreve 会重新请求 Discovery API，如果请求出问题会有这种情况。
