### ISSUE TITLE
通过Cloudreve向S3存储策略上传的文件不包含文件类型

### ISSUE THREAD

**Issue by r54yhe3gh34gw43** [cloudreve/Cloudreve#1678]
对接CloudFlare R2存储（类S3存储）以后，通过Cloudreve上传的文件在R2控制台的“Object Details”中的“Type”没有显示，在R2控制台的上传的文件正常显示"Type"，这使得在R2控制台上传的文件直链在浏览器中是预览的，而Cloudreve复制的直链在浏览器中是随机预览和下载(取决于浏览器)
正版亚马逊S3也是如此，是Cloudreve开发中就是这样设计的还是一个Bug？

**Comment by HFO4** [comment]
和#1681是同一个问题
