### ISSUE TITLE
在线打开office出错

### ISSUE THREAD

**Issue by Mical2018** [cloudreve/Cloudreve#168]
我在本地服务器搭建好以后，用在线打开ppt文件，显示错误，内如如下：
File not found
The URL of the original file is not valid or the document is not publicly accessible.
Verify the URL is correct, then contact the document owner.
请问是不是还需要其他的配置呢？

**Comment by HFO4** [comment]
使用Office预览功能需要你的站点能够在外网被访问，且在`基础设置 `- `站点URL`中正确填写了站点的地址
