### ISSUE TITLE
第三方云存储http请求头问题 / http head error

### ISSUE THREAD

**Issue by chris000132** [cloudreve/Cloudreve#1681]
存储策略使用阿里云OSS后，部分文件下载出现问题
例：下载PDF时，浏览器不会弹出下载窗口，而是直接通过在新页面内试图打开文件
此问题出现在视频和PDF文件下载时较多。
解决方案是在oss控制台中更改http请求头即可
但不可能每个文件都手动修改。
可否在文件上传时就自动设定请求头，以避免此类问题
![Uploading image.png…]()

**Comment by chris000132** [comment]
<img width="521" alt="image" src="https://user-images.githubusercontent.com/66486908/229008086-9b29e28e-2062-4e66-8d78-1266c440240b.png">

**Comment by HFO4** [comment]
您好，经确认分片上传接口无法指定mime type。
能否检查下你的文件重命名策略，最好保留扩展名，这样OSS会尝试自动设置 mime type。

**Comment by HFO4** [comment]
> 您好，经确认分片上传接口无法指定mime type。 能否检查下你的文件重命名策略，最好保留扩展名，这样OSS会尝试自动设置 mime type。

仔细看了下文档，好像可以设定，稍后提交commit修复。

**Comment by HFO4** [comment]
Fixed in https://github.com/cloudreve/Cloudreve/commit/89ee147961623b2515e29aa8a3e1b1c912c1e337
