### ISSUE TITLE
离线下载异常 Failed to get Aria2 instance

### ISSUE THREAD

**Issue by maoxuner** [cloudreve/Cloudreve#1684]
**Describe the bug**
创建离线下载任务时报错 “1 个任务创建失败：內部错误 (Failed to get Aria2 instance)”

**To Reproduce**

```bash
docker run --name cloudreve -p 5212:5212 -d cloudreve/cloudreve:3.7.1
```
然后通过web界面添加任意离线任务，比如链接`https://www.baidu.com/index.html`

**Expected behavior**
成功添加离线任务，并下载该页面的html文件

**Screenshots**

![image](https://user-images.githubusercontent.com/104855611/229397750-925735d7-ab88-4903-96f6-4266ae7f1678.png)

**Desktop (please complete the following information):**
 - OS: Linux ideabook 6.2.9-arch1-1 SMP PREEMPT_DYNAMIC Thu, 30 Mar 2023 14:51:14 +0000 x86_64 GNU/Linux
 - Browser: Chrome 
 - Version: 版本 111.0.5563.146（正式版本） （64 位）

**Additional context**
无

**Comment by topjohncian** [comment]
官方的 Docker Image 并不包含 Aria2 组件，可以尝试使用官方的 `docker-compose` [配置文件](https://github.com/cloudreve/Cloudreve/blob/master/docker-compose.yml)

**Comment by maoxuner** [comment]
sorry. 我没看全文档。我本以为在配置文件中应该会有离线下载的配置项，结果是直接在web面板中配置
