### ISSUE TITLE
存储策略选择腾讯云COS时无法设置回调

### ISSUE THREAD

**Issue by act-m** [cloudreve/Cloudreve#1686]
**Describe the bug**
如题，选择向导模式添加存储策略进行到最后一步时，无法成果设置云函数，提示：`输入参数有误 (Failed to create SCF function)
` 。
![image](https://user-images.githubusercontent.com/87530132/229983897-7ce87c65-252c-4f3d-93f6-0f606e2ffc24.png)

但在腾讯云面板可显示已经创建了云函数，如果反复重试，会创建多个云函数。
![image](https://user-images.githubusercontent.com/87530132/229984264-eaf4865a-1633-401b-abf9-517b4fb491fb.png)

经实际使用后查看日志，这些云函数并不会被Cloudreve调用。
![image](https://user-images.githubusercontent.com/87530132/229985934-a9a09cd9-aa23-4468-a0a9-3fd60c08b963.png)

**To Reproduce**
1. 安装部署Cloudreve 3.7.1 Pro版
2. 使用向导模式添加存储策略
3. 执行到设置的最后一步，即可复现创建云函数失败的提示。
4. 登录腾讯云后台，可见创建完成的函数，查看函数调用日志，近期调用皆为空。

**Expected behavior**
成功创建函数并调用。

**Screenshots**
如上

**Desktop (please complete the following information):**
 - OS: [Windows 10 & macOS]
 - Browser [chrome, edge, safari]
 - Version [3.7.1 pro]

**Comment by topjohncian** [comment]
可以忽略，并将多余的云函数删除
此云函数会在COS上传完毕后，由COS自动调用

**Comment by act-m** [comment]
> 可以忽略，并将多余的云函数删除 此云函数会在COS上传完毕后，由COS自动调用

感谢回复，请问如何判断哪一个函数是多余的呢？还是说只要随意留一个就可以？

**Comment by topjohncian** [comment]
只留一个就可以
