### ISSUE TITLE
总管理员是否可以看到所有人的文件

### ISSUE THREAD

**Issue by Mical2018** [cloudreve/Cloudreve#169]
总管理是不是可以增加一个权限，可以看到注册用户上传的所有文件（主要是想做一个团队协同文件系统），发现这个每个账号只能看到自己的（除非分享），有没有可能一个号只能用来上传，一个号只能看所有文件

**Comment by HFO4** [comment]
目前没有向团队协作方向发展的意向，可能短时间内不会考虑

**Comment by Mical2018** [comment]
> 目前没有向团队协作方向发展的意向，可能短时间内不会考虑

好的哦，不过作为网盘来说还是挺强大的了，支持下！
