### ISSUE TITLE
Liunx启动3.7.1报错

### ISSUE THREAD

**Issue by Yummy-cookie** [cloudreve/Cloudreve#1691]
![1](https://user-images.githubusercontent.com/114837513/230697490-5df4d196-078b-4364-84b0-15579b25ecff.png)

**Comment by XiaMoHuaHuo-CN** [comment]
是不是cloudreve权限不足，试试用sudo启动?

**Comment by Yummy-cookie** [comment]
> 

我找到问题了，是数据库root and 分数据库密码的问题就是未验证密码，需要重置
