### ISSUE TITLE
网盘被刷容量，一直自动上传文件

### ISSUE THREAD

**Issue by wxilejun** [cloudreve/Cloudreve#1699]
![image](https://user-images.githubusercontent.com/43799613/231917553-2166e627-8f97-46f3-8f13-7293b7bc9a59.png)
如图，上传了上万个文件了，想知道是怎么自动刷容量占用量的，上传了几百G的文件，而且一直在上传
想问下有没有类似的反爆破功能，或者说需要开启什么才能避免这种情况的发生，版本是pro版本，域名: yun.xlj0.com
一直是做的免费产品，免费提供储存服务，宣传的时候启用的cloudreve就被一些人瞧不起说要爆破这个网盘
希望大佬能看到这个情况

**Comment by 3242692624** [comment]
这个感觉像是m3u8切片，你直接封他账号就行了

**Comment by xjc19960724** [comment]
有没有可能别人在上传原盘视频？

**Comment by Darkluna999** [comment]
看起来有点像视频切片 =-=
你实在不行，服务器设置个监控docker的日志的定时脚本什么的，然后给他注册的邮箱发警告通知，多次超频就封一段时间 =-=
是不是很好解决 =-=
另外你做这个公益虽好，你加个免责声明吧，要不谁资料被盗了你不好洗

**Comment by RobKing9** [comment]
这个仪表盘是在哪里看到的？5212端口好像没有

**Comment by 3242692624** [comment]
> 这个仪表盘是在哪里看到的？5212端口好像没有

管理员后台啊
![QQ截图20230619191507](https://github.com/cloudreve/Cloudreve/assets/62818722/1386b5c5-1baa-4f0b-afc9-1a4cf39b27b0)

**Comment by RobKing9** [comment]
你这是用的软件还是自己搭建的？

**Comment by xiaoxin3242** [comment]
> 你这是用的软件还是自己搭建的？

cloudreve啊
