### ISSUE TITLE
个人设置中的UID与个人主页中的UID不一致

### ISSUE THREAD

**Issue by ZhangYichi-ZYc** [cloudreve/Cloudreve#1700]
**Describe the bug**
个人设置中的UID与个人主页中的UID不一致

**To Reproduce**
1. 打开个人设置，找到个人资料
2. 点击头像，打开个人主页，选择个人资料
3. 上述两个个人资料中的“UID”显示不一致

**Expected behavior**
两者的UID显示一致，或UID只显示在一处

**Screenshots**
![image](https://user-images.githubusercontent.com/66503962/232058890-18448d06-d1ee-4ee8-937c-331c2436a322.png)
![image](https://user-images.githubusercontent.com/66503962/232059009-51abf406-7af5-4abe-a98d-a31117302ca1.png)

**Desktop/Smartphone (please complete the following information):**
 - OS: ALL
 - Browser : ALL
 - Version 3.7.1 on Feb 13

**Comment by timi-owo** [comment]
+1 很早的版本（3.2.0）就存在这个问题 @HFO4
