### ISSUE TITLE
难绷,不支持批量分享

### ISSUE THREAD

**Issue by SeTube** [cloudreve/Cloudreve#1707]
一个网盘程序居然不支持
![4.png](https://article.biliimg.com/bfs/article/1d51dfa18b663f2a31c0117de05106889674cd55.png)
![4.png](https://article.biliimg.com/bfs/article/190c0cacf8b68e6aa87ae1fd5d8fd69c9ab18f5e.png)

**Comment by tlze** [comment]
好奇，分享个目录不行吗？

**Comment by SeTube** [comment]
> 

我也好奇,直接批量分享的便利性难道不是大于创建文件夹然后再去实现所谓的批量分享吗?

**Comment by XiaMoHuaHuo-CN** [comment]
不建议用一种很惊讶的语气
