### ISSUE TITLE
版本升级后账号信息丢失，无法登录！！！

### ISSUE THREAD

**Issue by ALEXTANGXIAO** [cloudreve/Cloudreve#1714]
从版本3.5.0升级到3.7.1 账号信息丢失无法登录

![image](https://user-images.githubusercontent.com/45391272/236435747-83d8aa1a-a3c2-48bb-bdce-ce31b465706a.png)

![08cd01801c4e1837d46f76736db40d3](https://user-images.githubusercontent.com/45391272/236435835-18a0a949-e64c-4ed7-8fd9-cb8e218a62d9.png)

![a3265139d0c1e6b21329963ae119a4c](https://user-images.githubusercontent.com/45391272/236435852-fa2e4079-5264-4a0e-ae54-6806397c02f0.png)

**Comment by linmu1234** [comment]
赞同，我也是丢失用户，不过我没有数据，我重新建了个账号，问一下你的数据还有吗？

**Comment by HFO4** [comment]
@ALEXTANGXIAO 是否方便将`cloudreve.db` 发送到 support@cloudreve.org ？ 如果不方便的话可以自行尝试使用 SQLite 修复工具修复。

**Comment by ALEXTANGXIAO** [comment]
@HFO4 cloudreve.db 已发送到邮箱。升级后该账号在web前端没有任何数据显示。SQLite我不太会用，辛苦大佬抽空看一下，感激涕零。

**Comment by ALEXTANGXIAO** [comment]
@HFO4 大佬修好了么，db我邮箱重新发了
