### ISSUE TITLE
github.com/lib/pq@v1.10.3 导致的编译失败问题？

### ISSUE THREAD

**Issue by Yang-qwq** [cloudreve/Cloudreve#1716]
**Describe the bug**
直接检出后尝试编译不通过

**To Reproduce**
1. `git checkout 3.6.2`
2. `go build`

**Expected behavior**
```
.../opt/cloudreve_src $ go build
# github.com/lib/pq
../../../home/go/pkg/mod/github.com/lib/pq@v1.10.3/user_posix.go:13:6: userCurrent redeclared in this block
        ../../../home/go/pkg/mod/github.com/lib/pq@v1.10.3/user_other.go:8:6: other declaration of userCurrent
.../opt/cloudreve_src $
```

**Screenshots**

**Desktop (please complete the following information):**
 - OS: None
 - Browser None
 - Version None

**Smartphone (please complete the following information):**
 - Device: None
 - OS: None
 - Browser None
 - Version None

**Additional context**
我尝试了更新出问题的包后，故障解决，并且成功通过当前版本和最新版本的编译（如下）
```
go get github.com/lib/pq@latest
go: downloading github.com/lib/pq v1.10.9
go: upgraded github.com/lib/pq v1.10.3 => v1.10.9
```

**Comment by HFO4** [comment]
编译目标的CPU架构是？

**Comment by Yang-qwq** [comment]
aarch64

**Comment by Yang-qwq** [comment]
aarch64
