### ISSUE TITLE
阿里云OSS在上传的时候F12会暴露阿里默认公网Bucket 域名

### ISSUE THREAD

**Issue by 3242692624** [cloudreve/Cloudreve#1721]
阿里云OSS在上传的时候F12会暴露阿里默认公网Bucket 域名
希望能够解决这个安全问题，不然即使下载套了CDN也会被别人通过阿里默认公网Bucket 域名盗刷流量

![QQ截图20230515213500](https://github.com/cloudreve/Cloudreve/assets/62818722/230fecd3-ebab-4c4c-a3b7-00eeec7ca3b0)

**Comment by aozima** [comment]
如果不是中转模式，都会暴露存储后端的真实地址吧？
但存储后端本身会有鉴权，这个链接是有效期的，问题也不大吧。

**Comment by 3242692624** [comment]
> 如果不是中转模式，都会暴露存储后端的真实地址吧？ 但存储后端本身会有鉴权，这个链接是有效期的，问题也不大吧。

我没看到有中专模式，关键是如果公开使用肯定会被刷，只有完全隐藏存储桶才能避免，鉴权只是不能让别人一直刷，但不代表不能刷

**Comment by aozima** [comment]
尽量限制下载次数和时间呗，本身就难两全。
另外可以多分析下被盗刷的具体情况，看看能不能在OSS后台那边限制下防盗刷规则，不过这规则也是可以伪造信息的。

所以这里防的仅是通过你的加密分享链接，进而得到真实OSS地址。
然后在一定范围内可以重复下载，这时你的被盗刷途径是可以很容易查明的，不再分享给他就是了。

如果你是公开分享，或分享时间很多，又想别人只下载1次，这本身就是矛盾的啊。

**Comment by 3242692624** [comment]
> 尽管数量限制下载次数和时间嘛，本身就难两全。 另外可以多分析下被盗刷的具体情况，看不能在OSS后端那边限制下防御刷规则，不过这个规则也是可以伪造信息的。
> 
> 所以这里防范的只是通过你的加密分享链接，进入并得到真正的OSS地址。 然后在一定范围内可以重新下载，此时你的被盗刷路径是可以的很容易查明的，不再分享给他就是了。
> 
> 如果你是公开分享，或者放散分享链接很多，而且分享时间很长。。。 又想别人只下载1次，这身就是瞎眼的啊。

说这么多结果还是没办法呗

**Comment by 3242692624** [comment]
> > 尽管管数限制下载次数和时间嘛，本身就难两全。另外可以多分析下被盗刷的具体情况，看不能在OSS后端那边限制下防范御刷规则，不过这个规则也是可以伪造信息的。
> > 所以这里防范的只是通过你的加密分享链接，进入并得到真正的OSS地址。然后在一定范围内可以重新下载，此时你的被盗刷路向是可以的很容易查明的，不再分享给他就是了。
> > 如果你是公开分享，或者放散分享链接很多，而且分享时间很长。。。又想别人只下载1次，这身就是瞎眼的啊。
> 
> 说这么多结果还是没办法呀
