### ISSUE TITLE
新建一个abc.docx文件打开失败？？

### ISSUE THREAD

**Issue by yz8943** [cloudreve/Cloudreve#1724]
新建一个abc.docx文件打开失败？？
![1684826369523](https://github.com/cloudreve/Cloudreve/assets/10083920/74f041c3-5f1d-4f37-bdd6-faac7e245267)
但是自己上传的一个word文档有内容的是双击可以打开的

**Comment by hatsuyuki280** [comment]
简单来说，这是因为创建新文件的功能现阶段只能用来创建纯文本文件，
并不能通过修改扩展名，获得更多种类的不同的文件。

如果你可以阅读代码，应该可以通过 [./service/explorer/file.go#L67](https://github.com/cloudreve/Cloudreve/blob/a9bee3e6381d37b709709b9a7f158ef705612db9/service/explorer/file.go#L67) 得知，新建文件将只会创建一个0长度的空文件，而word等是具有特殊结构的文件，所以会失败是很正常的

咱也觉得这个功能确实很不错，但如果你需要这个功能，也许可以把这个issue标记为 Feature request 然后等待后续更新。
