### ISSUE TITLE
外链中存在 Signin 参数，是否安全？

### ISSUE THREAD

**Issue by KinSumLan** [cloudreve/Cloudreve#1726]
**Is your feature request related to a problem? Please describe.**

上传图片后并点击获取链接，然后我得到了以下链接：

![image](https://github.com/cloudreve/Cloudreve/assets/32812905/71cd84ad-1968-44d9-b63b-e5573c33ec14)

然后访问此链接后，链接自动变为了以下格式，重点是自动添加了一个 sign 参数：

![image](https://github.com/cloudreve/Cloudreve/assets/32812905/a088a18b-d4b0-42fe-b3cd-18918b79ae43)

暴露此参数是否存在安全风险？我应该如何加密此字符？

**Describe the solution you'd like**

新增一个“自定义密钥”功能，能够自行加密该数据并定义解密方法。或者干脆直接隐藏该参数，当然如果该参数并不会带来安全风险那也不需要有新的功能。

**Additional context**
请在文档中补充说明该功能和参数的作用。

**Comment by HFO4** [comment]
这个是安全的。
