### ISSUE TITLE
希望Cloudreve网盘可以自定义阿里云OSS上传域名

### ISSUE THREAD

**Issue by xiaoxin3242** [cloudreve/Cloudreve#1736]
希望Cloudreve网盘可以自定义阿里云OSS上传域名
![202004211028463335525](https://github.com/cloudreve/Cloudreve/assets/62818722/9bedbd69-2a75-47c8-902a-69ee4526a931)

**Comment by RobKing9** [comment]
想问一下这个页面是在哪里？

**Comment by 3242692624** [comment]
> 想问一下这个页面在哪儿？

老版本的Cloudreve php版本的
