### ISSUE TITLE
能不能让分享的文件游客可以预览但不能下载

### ISSUE THREAD

**Issue by YHXJLB** [cloudreve/Cloudreve#1738]
能不能让分享的文件游客可以预览但不能下载

**Comment by wnb6cf** [comment]
蹲

**Comment by hiCasper** [comment]
可能不太好处理，对于图片/视频等文件，可以展示缩略图的方式预览，但是文档之类的调用预览其实就等于有下载权限，更不提其他格式的文件了。

**Comment by 01101sam** [comment]
@hiCasper 拥有read权限“即浏览”即可下载，打开F12就能获取
