### ISSUE TITLE
Support onlyoffice JWT Token for security

### ISSUE THREAD

**Issue by alexshliu** [cloudreve/cloudreve#1739]
**Is your feature request related to a problem? Please describe.**

From  official guide: [Installing ONLYOFFICE Docs Community Edition for Docker on a local server](https://helpcenter.onlyoffice.com/installation/docs-community-install-docker.aspx)
> Starting from version 7.2, we added a random generation of JWT secret. If JWT secret is not specified with the environment  variable, it leads to its re-generation during every VMs or physical server reboot, so there might be problems in integrations. To avoid this issue, specify your own value in -e JWT_SECRET=my_jwt_secret.

应该如何在 cloudreve 中传递这个参数？

**Describe the solution you'd like**
最好可以直接在 cloudreve 的管理面板中进行配置。

**Comment by HFO4** [comment]
Cloudreve 使用的是 WOPI 接口，不支持 JWT 鉴权。
