### ISSUE TITLE
docker-compose部署出错

### ISSUE THREAD

**Issue by RobKing9** [cloudreve/Cloudreve#1740]
![image](https://github.com/cloudreve/Cloudreve/assets/78016475/9abdc36d-7b4e-4b8f-9f09-f260db5baa71)

**Comment by RobKing9** [comment]
一直显示重启中
![image](https://github.com/cloudreve/Cloudreve/assets/78016475/4c973ff4-9086-4316-9729-72c9ba0fed0f)

**Comment by aitay721822** [comment]
要先建立目錄結構:
[Getting Started](https://docs.cloudreve.org/v/en/getting-started/install#chuang-jian-mu-lu-jie-gou-1)

**Comment by RobKing9** [comment]
目录结构已经创建好了呢

**Comment by aitay721822** [comment]
檢查 `conf.ini` 跟 `cloudreve.db` 是被創建為文件而不是目錄

**Comment by RobKing9** [comment]
是的，按照官网复制过去的指令。

**Comment by aitay721822** [comment]
我這按照官網教學部署都是正常的。
docker-compose.yml 也是按照官網的嗎?
執行環境是?

**Comment by RobKing9** [comment]
对的，所有的都是按照官网的步骤来的。执行环境 是云服务器，已经开放了5212和8000端口了

**Comment by ggtony233** [comment]
你这就是把ini创建成目录了，建议在不带挂ini先跑一遍,然后在加上
