### ISSUE TITLE
分享链接错误

### ISSUE THREAD

**Issue by RobKing9** [cloudreve/Cloudreve#1744]
**Describe the bug**

使用docker-compose部署的cloudreve，分享的时候链接路径不对
![image](https://github.com/cloudreve/Cloudreve/assets/78016475/4e170a2e-d4dd-47da-9d2c-8cfe99169b69)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Comment by RobKing9** [comment]
还有多个文件不能创建分享链接吗
![image](https://github.com/cloudreve/Cloudreve/assets/78016475/35a33736-7c02-4a51-900f-202b43ea1342)

**Comment by RobKing9** [comment]
![image](https://github.com/cloudreve/Cloudreve/assets/78016475/a10001e8-cdab-43be-b31a-f89ae8092ef6)
主页没有显示分享的内容
![image](https://github.com/cloudreve/Cloudreve/assets/78016475/36894081-f9de-4fe9-b8ea-9d58be5bebc0)

**Comment by RobKing9** [comment]
docker-compose部署的有后台管理吗？
除了5212端口的界面？

**Comment by TY88351** [comment]
公网IP不打码吗，小心被攻击

**Comment by jyewang** [comment]
第一个问题，你需要在admin账号下进入管理面板，修改你的外网地址。

第二个问题，你可以创建一个文件夹，共享文件夹就好了。

**Comment by RobKing9** [comment]
好的感谢大佬~
