### ISSUE TITLE
建议增加Ctrl+v直接上传功能

### ISSUE THREAD

**Issue by cmssky** [cloudreve/Cloudreve#1749]
RT，
我每天大概要上传20-30个文件到不同的网盘，每个文件位于不同的盘符不同的目录下面，有的目录子目录众多，在实际使用过程中选择文件感觉很不方便，建议增加Ctrl+v直接上传功能，希望提议能得到采纳，最后感谢下作者的辛苦付出让我们能使用到这么好的网盘程序。

**Comment by hatsuyuki280** [comment]
虽然不知道未来会不会采纳这个需求，不过以现在已经实现了的功能来说，
你也许可以尝试以下几种方法来优化自己的使用体验：
* 将网盘作为webdav映射至本地后使用本地的文件管理器进行批量操作（这样就可以使用Ctrl+V操作了）
* 从本地的文件管理器批量选择需要上传的文件后使用鼠标拖放至浏览器中的网盘页面的目录视图中。
* 通过其他方式直接将文件批量上传至网盘绑定的存储策略后从管理面板扫描并添加至用户的网盘空间中。  

上述内容的具体做法可以参考网盘的文档获得更多信息，
希望以上方法可以让你在获得更进一步的回复前感觉不那么不方便
