### ISSUE TITLE
windows server 2022不兼容吗

### ISSUE THREAD

**Issue by mcmhg** [cloudreve/Cloudreve#1750]
文件对64位的windows server 2022系统不兼容
希望推出解决方案

**Comment by hatsuyuki280** [comment]
这个网盘程序是使用golang编写的，而go在一定程度上兼容性应该是可以期待的。

Windows Server属于商业软件，虽然不知道作者那边的实际情况但预设他们缺少这样的测试环境是合理的。
为了更快的解决你的问题，对于你提及的不兼容问题，可以提供更多信息嘛？
比如回答以下问题可能会有所帮助：
* 关于你的系统的更多信息，关于运行环境的更多信息，关于你下载使用的软件版本的更多信息等
* 运行过程中是否有遇到任何报错/弹窗？
* 相关配置文件是否配置正确（如数据库/反向代理/防火墙规则/端口映射等）
* 你预期程序将会如何运行，程序实际如何运行了？
* 你有没有其他对于不兼容的描述

虽然以回复以上问题不一定能让它run起来也不一定能特定到问题在哪里。
但更多的信息总是会比更少的信息对寻找问题更有利。
