### ISSUE TITLE
当更新缩略图规则时，应该将所有生成缩略图失败的图片重置为未知

### ISSUE THREAD

**Issue by xkeyC** [cloudreve/Cloudreve#1755]
**Describe the bug**
我的 Cloudreve 保存了大量 8k 图片，在本次版本更新后触发了缩略图30M大小限制，导致大量图片生成失败。
当我更新缩略图规则后，这些失败的图片依然无法展示缩略图。
请在更新缩略图规则时重置失败的图片状态，或者提供一个可以手动触发重置的按钮。

**Screenshots**
<img width="729" alt="237a01bad7e703a568a48434f37855d1" src="https://github.com/cloudreve/Cloudreve/assets/39891083/fbe411c3-ee52-413c-a723-90f50cea4bf9">

**Comment by aimiku** [comment]
数据库的文件表（cdfiles）搜索最后的字段（metadata）为 {"thumb_status":"not_available"} 的全部改成NULL。就会重新变为未知状态
 比如：UPDATE `cdfiles` SET `metadata` = NULL WHERE `metadata` LIKE '{\"thumb_status\":\"not_available\"}'
