### ISSUE TITLE
存储策略下的奇怪问题

### ISSUE THREAD

**Issue by ggtony233** [cloudreve/Cloudreve#1766]
3.6.0-3.8.0都有这个问题，更早的没测
在使用[Azure Active Directory 控制台 (国际版账号)的onedrive存储策略时，webdav会出现奇怪的现象，本地存储策略就不会出现这个问题
### floccus书签同步服务
这个客户端在第一次同步上传时不会出现任何问题，但在第二次同步时根据设置不同就会出现两个不同的错误
当未勾选允许重定向时
```log
Syncing failed with E033: Redirect detected. Please make sure the server supports the selected sync method and URL you entered is correct doesn't redirect to a different location.If the redirect is part of your setup, you can disable this check in the settings.
```
上面提到了没勾选，这是勾选后的提示
```log
E018: Couldn't authenticate with the server
```
这是onedrive的限制？还是说是bug?
### 阅读
这个是在上传的过程没有问题，但在获取备份的时候401

**Comment by Gonglja** [comment]
我也遇到了同样的问题，
解决方案：在使用 floccus 开启 `允许在服务器 URL 中重定向` 就正常了

**Comment by ggtony233** [comment]
> 我也遇到了同样的问题， 解决方案：在使用 floccus 开启 `允许在服务器 URL 中重定向` 就正常了

你仔细看，我上面说了，勾选后的提示是
```cmd
E018: Couldn't authenticate with the server
```

**Comment by Gonglja** [comment]
> > 我也遇到了同样的问题， 解决方案：在使用 floccus 开启 `允许在服务器 URL 中重定向` 就正常了
> 
> 你仔细看，我上面说了，勾选后的提示是
> 
> ```batchfile
> E018: Couldn't authenticate with the server
> ```
> 
> 而且不只floccus有这个问题，我在使用开源阅读app作为客户端的时候也碰到了这个问题上面也有讲

抱歉哈，前面没注意到

我下午使用 alist 搭建的 webdav，在使用 floccus 一次同步后再次同步就遇到了同样的问题，搜索问题时注意到这个 issue，后面 开启`允许在服务器 URL 中重定向` 后尝试成功就回复了，抱歉抱歉😅
