### ISSUE TITLE
管理员（UID:1）可以封禁自己并且无法解封

### ISSUE THREAD

**Issue by SunshineboyZj** [cloudreve/Cloudreve#1768]
三年前同样的问题：#481 #486

在后台管理用户页面的外面封禁无法封禁自己
![85853085-79ac8f80-b7e4-11ea-992f-0dc473df8b21](https://github.com/cloudreve/Cloudreve/assets/81549837/67f2de65-677b-44e7-9721-c15399b5df18)
但进入编辑页面就可以将自己的状态修改为被封禁，并且自己再也登不上这个账户了（这是个很严重的bug！！！）
![Cache_110b12a55431dcac](https://github.com/cloudreve/Cloudreve/assets/81549837/014de4e1-142e-40b5-9700-ad4a38cec834)
![image](https://github.com/cloudreve/Cloudreve/assets/81549837/1fa54422-a21f-42c9-b67f-a1b17aeaa240)

**Comment by SunshineboyZj** [comment]
查询了搜索引擎，发现这个“进入 cloudreve 数据库，修改 users 表里的 status 字段为 0”的办法能够解除封禁
![image](https://github.com/cloudreve/Cloudreve/assets/81549837/c1c6f1b7-f9cd-428a-bc02-059dbfff3926)
但还是希望能修复这个问题（让管理员无法封禁自己）

**Comment by 01101sam** [comment]
> 

之前就修了 [`service/admin/user.go`](https://github.com/cloudreve/Cloudreve/blob/master/service/admin/user.go#L114-L117)
![image](https://github.com/cloudreve/Cloudreve/assets/100821827/1286420c-3f23-4e3b-9c38-15004abff144)

**Comment by SunshineboyZj** [comment]
> > 
> 
> 之前就修了 [`service/admin/user.go`](https://github.com/cloudreve/Cloudreve/blob/master/service/admin/user.go#L114-L117) ![image](https://user-images.githubusercontent.com/100821827/259083465-1286420c-3f23-4e3b-9c38-15004abff144.png)
您好，我指的不是管理面板-用户界面（图1），而是管理面板-用户→操作→编辑界面（图2）
![图1](https://github.com/cloudreve/Cloudreve/assets/81549837/94d16597-7d08-45fc-b012-6fe134bcabc1)
![图2](https://github.com/cloudreve/Cloudreve/assets/81549837/76c42c80-d1aa-4236-b42d-3bdaade335dc)

**Comment by 01101sam** [comment]
你说的对，但是我误会了，因此给你赔了个PR

**Comment by SunshineboyZj** [comment]
> 你说的对，但是我误会了，因此给你赔了个PR

万分感谢（不用这么客气的😂）
