### ISSUE TITLE
对分享的直接批量下载、从命令行下载之功能需求和PR

### ISSUE THREAD

**Issue by myuanz** [cloudreve/Cloudreve#1772]
**Is your feature request related to a problem? Please describe.**
给出一个包含很多文件的分享时，因为默认分页机制，总是很难批量下载，必须得再创建一个目录进去才行，这样很麻烦。而分享在命令行中下载也非常麻烦。

**Describe the solution you'd like**
如果你们接受这两个功能的PR的话，我会开发以下功能。

在预览分享开启时

1. 我会添加一个`批量下载`按钮直接下载本分享下所有文件，功能等同于`取消分页-全选-右键-批量下载`
2. 我会添加一个`批量从命令行下载`按钮，点击后生成一大段使用 wget、curl、aria2 下载的命令
3. 如果可以的话，处理可能出现的超大文件断点续传的问题

**Additional context**

背景：我经常需要在局域网分享数十TB级别的数据，在公网分享数T级别的数据，也需要管理不同用户的分享和使用空间。网页上的下载功能，包括服务器打包批量下载、浏览器打包批量下载、浏览器请求文件权限单个下载在这个量级下都非常不稳定。webdav 又很慢，还需要使用额外的工具，好在大部分使用者都是 Linux 用户，如果能加强命令行就再好不过了

**Comment by HFO4** [comment]
Sounds good to me!

**Comment by myuanz** [comment]
花了很久触发大文件下载失败, 最后发现是下载很久时网络波动导致连接断开下载重试, 此时 sign 已经失效了, 调高后就不再触发了, 因此后两个功能也没什么用了
