### ISSUE TITLE
无法加载站点配置：Network Error--:( 请求时出现错误 Network Error

### ISSUE THREAD

**Issue by heiniao998** [cloudreve/Cloudreve#1773]
[https://s2.loli.net/2023/07/13/EVryPsoQpKfuWUB.png](url)
这个问题你们都没有遇见吗？
无法加载站点配置：Network Error--:( 请求时出现错误 Network Error
找半天也没有找到有人提类似问题

**Comment by XiaMoHuaHuo-CN** [comment]
字面意思啊 就是你访问不通

**Comment by XiaMoHuaHuo-CN** [comment]
这不是cloudreve问题，是你配置有问题
