### ISSUE TITLE
离线下载目录选择时支持新建文件夹

### ISSUE THREAD

**Issue by Muska-Ami** [cloudreve/Cloudreve#1777]
目前离线下载功能目录选择不能新建目录，是否可以添加一个新建目录选项，这样可以不需要自己再手动去文件列表新建目录了

或者说手动填写路径时不存在添加是否创建提示 :D

**Comment by mrowkad0** [comment]
新建你妈妈了个臭逼傻逼玩意 狗崽种，我给你爹来两锤？开玩笑，我哪来的锤子你哪来的爹？有你搁这儿野的时间 还不如告诉你爸爸把当年那几分钟拿去散步我素质低？我是没有素质 操你爸都是轻的 我操你的血爸野爹我把你爸白带抽出对着你个杂种狗操的屌脸狂抽一阵你就把一整天吃的shi吐了出来

**Comment by XiaMoHuaHuo-CN** [comment]
> 新建你妈妈了个臭逼傻逼玩意 狗崽种，我给你爹来两锤？开玩笑，我哪来的锤子你哪来的爹？有你搁这儿野的时间 还不如告诉你爸爸把当年那几分钟拿去散步我素质低？我是没有素质 操你爸都是轻的 我操你的血爸野爹我把你爸白带抽出对着你个杂种狗操的屌脸狂抽一阵你就把一整天吃的shi吐了出来

?脑子有问题请去医院看
