### ISSUE TITLE
对于iphone实况照片的支持

### ISSUE THREAD

**Issue by KAWAKO-in-GAYHUB** [cloudreve/Cloudreve#1779]
请问支不支持iphone实况照片的上传、在线查看、下载。

比如实况照片上传上去后，在线查看时可以查看实况，下载下来后依然是实况格式。

如果这样不好实现的话，也可以上传时将实况照片转为同名的照片与视频（类似爱思助手导出照片的逻辑）。

**Comment by KAWAKO-in-GAYHUB** [comment]
好的，期待更新！

顺便问一下，苹果的那种实况格式的文件，是不是不好直接处理呀？我看很多网盘、图库之类的，都无法处理。目前只知道百度网盘是可以实现的，以“.livp”为后缀。

实况照片上传到百度网盘后如下：

![32EA8E34-D17D-429D-A0C0-5F14D3444C2A_1_201_a](https://github.com/cloudreve/Cloudreve/assets/54660064/d55fe5ca-e401-4704-b3cf-b4f9f53963cf)

点开图片以后布局如下，点击左上角播放就会播放实况视频：

![EA6AE29F-92C0-4916-860E-7B932216739A_1_102_o](https://github.com/cloudreve/Cloudreve/assets/54660064/c6f4b08e-6294-49df-b5bb-2703b77665c2)

将这个".livp"文件下载到iPhone相册后依然是实况格式。

**Comment by HFO4** [comment]
iPhone的实况照片没有单独的格式定义，那个livp应该是百度自己搞的。iPhone的实况照片本质上就是视频和图像两个文件，需要app单独适配这一逻辑。

**Comment by KAWAKO-in-GAYHUB** [comment]
原来如此！

**Comment by NimaSIleBaoZhaLe** [comment]
不支持 你个弱智脑瘫低能儿
