### ISSUE TITLE
请问作者，V4版本是否有加入Azure Blob Storage的计划？

### ISSUE THREAD

**Issue by q601904795** [cloudreve/Cloudreve#1781]
如题。
目前我尝试挂载Azure Blob Storage是通过SMB到本地，再用本地储存。十分不稳定，期待原生的Azure Blob Storage支持。

**Comment by 6chetbiretlighb** [comment]
计划加入几根大鸡巴后入你亲妈屁眼

**Comment by q601904795** [comment]
你好？什么地方的罪你了？

**Comment by mrowkad0** [comment]
> 你好？什么地方的罪你了？

就想让你亲妈好好高潮高潮 爹顺手一杆子刺穿你婊子妈臭逼跟你狗爹尸体穿在一起以110迈速度将你婊子妈智障爹扔去月球以示地球人热爱和平 我烟头都刮你脸上，操你爸的。你爸像傻屌似的牵个马给他唱走马呢，操你爸的。一脚给你爸踹河沟子里了，操你爸的。给你爸画鬼脸儿你爸大屌的，操你爸的。你爸爸兜里时上借茅房搁着干你爸了个屌勒，我操你爸的。你爸跟你爸操屌时你爷偷看溅你爷一身血，操你爸的。你爸爸搁家闯红灯呢，操你爸的。给你爸月经都干失调了，操你爸的。吹口气拿刮胡刀把你爸屌毛全刮了，操你爸的。往你爸屁眼滴一下养喇叭，操你爸的。给你爸取个外号叫阳沟，操你爸的。你像傻屌似的，操你爸的。 你爸搁家是死是活屌头上一根头箍给你爸梳龟头呢，操你爸的。你像老傻屌似的，小孙子你可真jb闲。👴也很闲，于是把你的短小家伙嘎了油爆。我把它的两面炸至金黄，再裹上面包糠，给隔壁小孩。瞧把这孩给吓的，一把把你小🐔儿丢粪坑里了。不知道咋滴，你这🐔儿在管道里瞎jb转，结果转到一撤硕里。老八来吃粑粑，本来吃挺香的，结果看见你那玩意，哇哇的呕啊。你爹我举世无双的一刀以雷霆万钧不及掩耳之势给你婊子爸全身上下一共切割了七七四十九刀让你婊子爸处于极度痛苦哀嚎中致死
