### ISSUE TITLE
[Redirected Source] The sign url from redirected source should include filename if possible.

### ISSUE THREAD

**Issue by YUDONGLING** [cloudreve/Cloudreve#1783]
**Describe the bug**
The sign url like `{host}/f/RO66yguR/TEST.jpg` from redirected source should include filename if possible.
For example, the `?attname=TEST.jpg` for Qiniu KODO.

**Additional context**
Fix soon.

**Comment by YUDONGLING** [comment]
Fix in #1784.

**Comment by HFO4** [comment]
One problem is that some people expect previewing files directly via source links, (videos, audio, images), they don't want to download these files.

**Comment by YUDONGLING** [comment]
That's right. I didn t take this into consideration.
Actually, when use link as a element of a html file, no matter if link contains parameters such as `?attname` or not, the file won t be downloaded by the browser, but be displayed as a part. The situation you mentioned might be that some users want to open the link directly in the browser and preview it directly?
For this situation, I suggest use similar solution in Onedrive, that is add the parameter `download=1` at the end of the link to indicate direct download instead of preview.
