### ISSUE TITLE
关于多子域名同一个站点的支持

### ISSUE THREAD

**Issue by saga0324** [cloudreve/Cloudreve#1788]
Cloudreve很适合家用轻NAS，我目前也是这样使用
但是有一个问题，是否可以支持多子域名，一个站点的功能呢？
比如说我当前DDNS了两个域名
pan.xxxxx.cn和pan6.xxxxx.cn
我希望两个域名都能访问到cloudreeve，同时也可以处理到HTTPS

**Comment by ilisuo** [comment]
这种需求可以自己使用nginx等专业服务器应用部署，并且如果只是想两个子域都能访问，那可以部署泛域名证书即可。

**Comment by saga0324** [comment]
> 这种需求可以自己使用nginx等专业服务器应用部署，并且如果只是想两个子域都能访问，那可以部署泛域名证书即可。

主要目的就是在主机下载的时候可以自己处理链接，部署泛域名证书方法的确可以解决

**Comment by ilisuo** [comment]
你的意思是你解析了两个子域，一个解析ipv4，一个ipv6，你希望下载的时候如果客户端有ipv6就是用ipv6的子域并使用https吗

**Comment by saga0324** [comment]
是的 可以这么说 所以直接有多域名支持也许是最优解

dj4je ***@***.***>于2023年7月22日 周六21:50写道：

**Comment by ilisuo** [comment]
> 是的 可以这么说 所以直接有多域名支持也许是最优解 dj4je ***@***.***>于2023年7月22日 周六21:50写道：
> […](#)

那你直接把一个子域同时解析ipv4和ipv6呢？

**Comment by saga0324** [comment]
解析两个域名就是为了优化网络连接质量 v4好的时候用v4 v6好的时候用v6 两者QoS等级不同
如果只解析到一个域名之下，要手动再去调客户端的v4v6 还是有些过于麻烦了

dj4je ***@***.***>于2023年7月22日 周六22:13写道：
