### ISSUE TITLE
Slave cannot send callback request

### ISSUE THREAD

**Issue by misaka19465** [cloudreve/Cloudreve#1789]
**Describe the bug**
使用主从机时，长时间正常使用，但突然开始在上传时报`Slave cannot send callback request`。
下载正常

**To Reproduce**
主机使用cloudflare代理，从机裸奔；cloudreve版本均为3.8.0
在一段时间未使用上传功能后，每一次上传都会出现。

**Expected behavior**
正常上传文件

**Screenshots**
![image](https://github.com/cloudreve/Cloudreve/assets/45687121/bb86dc29-8ce2-4b16-a791-cbab4c482535)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Browser: Chrome
 - Version: 115.0.5790.102

**Comment by TomyJan** [comment]
如何解决的?
