### ISSUE TITLE
Markdown 预览功能存在漏洞，可渲染任意 HTML 内容

### ISSUE THREAD

**Issue by YanJi314** [cloudreve/Cloudreve#1793]
**问题描述**
Markdown 预览功能存在严重安全漏洞，其中写入的任何 HTML 标签及属性都可被正常渲染。
例如在分享链接中的 `readme.md` 写入  便可进行攻击，其他访客打开分享链接会自动渲染并执行攻击者的代码。

**复现步骤**
1. 用户登录后创建目录。
2. 目录中创建 `readme.md`
3. 写入 `<img src="image.png" onload="alert('请输入账号密码')">` 并保存
4. 将目录进行分享，获取分享链接
5. 其他访客打开分享链接，`readme.md` 会自动渲染，同时执行恶意代码

**期望效果**
使用 `DOMPurify` 等工具对渲染的 Markdown 内容进行净化，仅保留基础文本格式和图片等。

**问题截图**
![image](https://github.com/cloudreve/Cloudreve/assets/63778412/3e97a6ed-f56d-40e9-9a9f-7eb7c47310d4)

**系统信息**
 - 系统: Windows 10
 - 浏览器: Chrome
 - 版本: v114

**Comment by mrowkad0** [comment]
你个亲妈暴毙废物玩意 司马去吧 还报告bug呢？你爹黑了你！！！！！！！！！！
