### ISSUE TITLE
Cloudreve Pro 3.8.1创建Webdav账户失败

### ISSUE THREAD

**Issue by aaro-n** [cloudreve/Cloudreve#1794]
**Describe the bug**
更新Cloudreve Pro 3.8.1，创建Webdav账户提示“数据库操作失败 (Failed to create account record)”，数据库使用PostgreSQL

**To Reproduce**
1.打开网站，选择“链接与挂载”
2.选择下方的“创建账户”，填写“备注名”和选择“相对目录位置”
3.点击“确定”，提示“数据库操作失败 (Failed to create account record)”.
4.Cloudreve Pro 回滚3.8.0后可以正常创建webdav账户

**Expected behavior**
3.8.1版本正常创建webdav账户

**Screenshots**

**Desktop (please complete the following information):**
 - OS: macos
 - Browser chrome
 - Version 114.0.5735.198

**Smartphone (please complete the following information):**

**Additional context**

**Comment by HFO4** [comment]
感谢反馈，忘记改 required db 版本了😅

**Comment by LianZiZhou** [comment]
> 感谢反馈，忘记改 required db 版本了😅

可否增加快速修复版本，比如在出现此恶性bug后快速发布3.8.1.1。

3.8的从机缩略图问题到3.8.1修复间隔了一个月，不知道这是否是合理的版本策略。个人感觉这种小但恶性的bug影响不小。

**Comment by twobox** [comment]
> > 感谢反馈，忘记改 required db 版本了😅
> 
> 可否增加快速修复版本，比如在出现此恶性bug后快速发布3.8.1.1。
> 
> 3.8的从机缩略图问题到3.8.1修复间隔了一个月，不知道这是否是合理的版本策略。个人感觉这种小但恶性的bug影响不小。

可以先换回3.8.0版本，创建后再回到3.8.1版本。如果有必要使用3.8.1版本的话。

**Comment by 6chetbiretlighb** [comment]
> > > 感谢反馈，忘记改 required db 版本了😅
> > 
> > 
> > 可否增加快速修复版本，比如在出现此恶性bug后快速发布3.8.1.1。
> > 3.8的从机缩略图问题到3.8.1修复间隔了一个月，不知道这是否是合理的版本策略。个人感觉这种小但恶性的bug影响不小。
> 
> 可以先换回3.8.0版本，创建后再回到3.8.1版本。如果有必要使用3.8.1版本的话。

傻逼玩意你妈脑瓜子被驴踢了 你亲妈死了给你亲妈火化了换个新妈可以吗？我真是操死你个亲妈的大烂逼了！！！！！！！！ @twobox

**Comment by aaro-n** [comment]
3.8.3版本问题已修复，关闭问题。
