### ISSUE TITLE
[BUG] 使用COS存储一直卡在上传文件状态

### ISSUE THREAD

**Issue by ohto-ai** [cloudreve/Cloudreve#1807]
**Describe the bug**
配置腾讯COS存储策略，上传文件后可以在COS中查到，但是cloudreve中显示处在上传状态。

**To Reproduce**
1. 配置腾讯COS存储并设定用户存储策略
2. 上传文件
3. 进入仪表盘查看文件上传状态
4. 进入COS查看文件上传状态

**Expected behavior**
预期文件会出现在cloudreve中

**Screenshots**
1. 上传窗口：显示已上传
![image](https://github.com/cloudreve/Cloudreve/assets/46275725/605030cb-c82f-4ff5-a27d-b3a933b35c70)
2. 仪表盘：显示文件上传中，文件名可以点击打开正确的图片地址
![image](https://github.com/cloudreve/Cloudreve/assets/46275725/668b0ee6-cf05-4b66-b31d-ae3007c27c27)
3. COS存储桶：文件已上传到存储桶
![image](https://github.com/cloudreve/Cloudreve/assets/46275725/3d99ee8f-f33e-41c3-91fc-af95f5df1701)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Cloudreve-3.8.1

**Additional context**

**Comment by 6chetbiretlighb** [comment]
废物玩意我真是操死你亲妈了傻逼玩意
