### ISSUE TITLE
WOPI cannot connect to a custom port service.

### ISSUE THREAD

**Issue by wcz0** [cloudreve/Cloudreve#1809]
**Describe the bug**
WOPI cannot connect to a custom port service.

**To Reproduce**

**Expected behavior**
WOPI should be able to connect to a custom port service normally.

**Screenshots**

**Desktop (please complete the following information):**
 - Browser chrome
 - Version 3.8.1

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mrowkad0** [comment]
傻逼玩意 滚蛋 别放洋屁

**Comment by wcz0** [comment]
my error
