### ISSUE TITLE
webdav挂载到本地上传文件有限制

### ISSUE THREAD

**Issue by michaelsun123321** [cloudreve/Cloudreve#1820]
实验了2个工具，cloud drive2和raidrive
第一个上传40多兆的PDF文件无法上传始终在列表中反复尝试
第二个文件上传到一半速度突然下降到原来的10%，而且传几百k中断一下，再传几百K中断一下直到完成
都不正常
请问是什么问题，多谢

**Comment by michaelsun123321** [comment]
我是用Windows版本部署的

**Comment by leongzj** [comment]
有问题，我也是这个问题，Windows11
