### ISSUE TITLE
文件删除后再上传发生问题

### ISSUE THREAD

**Issue by sdxzwd** [cloudreve/Cloudreve#1822]
系统环境:   PHP 7.2.33,Centos7.9
cloudreve存储策略:  腾讯云对象存储(cos),设置为私有存储桶,使用了CDN服务 

我在cloudreve上传了一个文件 a.txt 
     内容是123 

然后我删除了这个文件 
     我直接去访问cos和CDN都没有这个文件 
     访问cloudreve生成的文件外链提示:
            {
            "code": 40044,
            "msg": ""
            }
     
之后我在cloudreve上传了一个同名文件 a.txt
      内容是1212

我直接去访问cos和CDN这个文件的内容都是1212

问题发生了:
我在cloudreve预览文件a.txt的内容是123
      访问a.txt生成的文件外链内容还是123
      点击下载这个文件a.txt,内容也是123

**Comment by thenamehasbeentake** [comment]
会不会是浏览器的缓存呢？
