### ISSUE TITLE
希望可以增强管理能力

### ISSUE THREAD

**Issue by hatsuyuki280** [cloudreve/Cloudreve#1825]
## 需求描述：

希望可以给管理员增加具有下列功能的管理能力
* 批量代替用户修改用户文件正在使用存储策略 (批量迁移)
* 按规则移除/移动/筛选文件
* 批量移除后端中不再可用的文件
* 新增生成sha256或CRC校验值的功能

## 需求场景：
在特定业务需求下，终端用户通常难以及时察觉存储后端的异常。
而现阶段的CR如果操作后端数据迁移，将会需要手动操作文件系统并更新数据库中的记录值。

该操作存在一定风险，且具有一定难度门槛。
尽管该操作不属于日常维护的一部分，但在使用容易翻车的存储策略时，支持批量迁移将会非常便利。

## 补充内容：
关于第三项功能，更准确的说，应该是批量检查文件在文件系统中的可用性(是否可读可写等)
第四项功能考虑到文件尺寸，太大的文件的校验可能开销会比较大（
如果同时提供具有上述功能的命令行操作方式将会更方便自动化…

**Comment by nevadax0120** [comment]
建议使用稳定的后端存储

**Comment by hatsuyuki280** [comment]
> 建议使用稳定的后端存储

你说的很有道理，只不过对于需要维护的存储策略来说，这个功能依然很有必要性。

在咱的场景下后端使用的是on-premise的本地存储，随着存储规模的扩张及旧磁盘的计划性淘汰，难免会需要涉及到原有数据的迁移，尽管直接整盘镜像也不是不行，但能在线完成迁移，实现零停机依然是很重要的需求。
