### ISSUE TITLE
直接拉取项目运行go run main.go或者go build运行报错

### ISSUE THREAD

**Issue by Albertchamberlain** [cloudreve/Cloudreve#1826]
**Describe the bug**
直接拉取项目运行go run main.go或者go build运行，无法访问登录主页，提示缺失index.html
![image](https://github.com/cloudreve/Cloudreve/assets/47343901/47efe994-f145-42cc-8085-a89cbbb27dcd)
![image](https://github.com/cloudreve/Cloudreve/assets/47343901/79385849-7a8d-4dc5-8b6a-db71fdd1d945)

![image](https://github.com/cloudreve/Cloudreve/assets/47343901/a03836e1-1fef-4bda-9bd5-0122a68b2f82)

**Comment by Albertchamberlain** [comment]
运行项目编译好的exe文件可以使用，无warring 无error
![image](https://github.com/cloudreve/Cloudreve/assets/47343901/64541e15-5671-4622-994d-71d22628f431)

**Comment by Albertchamberlain** [comment]
![image](https://github.com/cloudreve/Cloudreve/assets/47343901/80163c08-d809-456a-af2c-918e5a1562ab)

**Comment by hiCasper** [comment]
可能是前端编译时出现了问题，考虑换一下yarn/npm源，在干净的环境下重新编译试试看？

**Comment by Albertchamberlain** [comment]
嗯嗯，谢谢，更换了源，win下是没有zip命令导致的   http://stahlworks.com/dev/index.php?tool=zipunzip  将zip加入环境变量后解决了，Thanks a lot  :)
