### ISSUE TITLE
存储的大小在哪里修改呢？

### ISSUE THREAD

**Issue by SimpleTangLong** [cloudreve/Cloudreve#1836]
启动之后一直没找到修改存储大小的地方，文档也没找到。

**Comment by PercyDan54** [comment]
管理面板修改用户组容量

**Comment by vvisionnn** [comment]
登录之后主界面 -> 右上角点击头像 -> 管理面板 -> 左侧用户组 -> 选择想编辑的用户组 -> 点击右侧编辑 (铅笔图标) -> 编辑初始容量

**Comment by chuzi2923** [comment]
我在登录之后，右上角点击头像，只显示了个人主页和退出登录，默认的用户组为User，安装的是3.8.3Windows版本的，请问该如何进行设置

**Comment by chuzi2923** [comment]
> 登录之后主界面 -> 右上角点击头像 -> 管理面板 -> 左侧用户组 -> 选择想编辑的用户组 -> 点击右侧编辑（铅笔图标） -> 编辑原创财富

我在登录之后，右上点击头像，只出现了个人主页和退出登录，并没有显示管理面板，下载安装的是3.8.3Windows版本的，运行之后直接是拿邮箱注册的账号，用户组默认是User，请问这种情况该如何修改存储大小，现在默认为1GB
