### ISSUE TITLE
Cloudreve从机存储下载报错{"code":403,"msg":"expire timestamp is missing"}

### ISSUE THREAD

**Issue by xiaoxin3242** [cloudreve/Cloudreve#1838]
Cloudreve从机存储下载报错{"code":403,"msg":"expire timestamp is missing"}

**Comment by xiaoxin3242** [comment]
发现是从机存储套了cloudflare 的cdn后就会这样，cloudflare规则配置里边有让下载地址跳过所有防火墙以及自定义规则，结果还是这样

**Comment by 8ar10der** [comment]
@xiaoxin3242 请问你解决了吗最后，我也是套了cf，最近升级到v4后下载也出现同样错误
