### ISSUE TITLE
[自己的锅]用了新版本的程序，重启后原来的文件全丢了？？磁盘上也没了，这设定不科学吧？？？

### ISSUE THREAD

**Issue by linfun486** [cloudreve/Cloudreve#1840]
此前想升级下cloudreve， 没看文档
于是就直接从官网更新了cloudreve可执行文件
然后systemctl restart cloudreve 成功后发现原文件全丢了， 但是数据库记录 和配置都在

文件这么重要的东西，删之前不确认或禁止的吗？？这是不是太扯了？

**Comment by linfun486** [comment]
后台查看了下原来的存储策略也消失了， 但是部分配置又在

**Comment by ilisuo** [comment]
所以 你是夸大版本升级吗？什么也不说清楚就来diss
