### ISSUE TITLE
希望可以设置允许覆盖重名文件

### ISSUE THREAD

**Issue by achiever-C** [cloudreve/Cloudreve#1846]
设置了文件名不进行重写后，如果在同一个目录上传相同文件名的文件，会出现不允许上传的情况，希望能在存储策略中允许覆盖原文件。

我尝试注释了Cloudreve\pkg\filesystem\driver\local\handler.go文件中的，Put函数下的if判断和Token函数下的if判断，并重新构建运行，但是上传同名文件还是出现错误：无法创建上传会话，同名对象已存在。如果我哪里做的还不够好，希望能给出一些建议，万分感谢！

**Comment by CodeGather** [comment]
是呀，希望可以实现，或者名称相同时保留两者
