### ISSUE TITLE
cloudreve 3.8.2配置从机存储之后测试通讯出错

### ISSUE THREAD

**Issue by zxcv-12345** [cloudreve/Cloudreve#1847]
现象：
按照添加存储策略的默认从机配置后，测试从机通讯出现“`输入参数有误 (Successfully connected to slave node, but slave returns: invalid character '<' looking for beginning of value)`”报错。

已排查cloudreve从机程序执行权限已拥有并且目录、相关文件都有对应的可读写权限。

日志返回如下内容：
[GIN] 2023/09/23 - 01:31:19 | 200 |   61.934973ms | 主cr ip | POST     "/api/v3/slave/ping"
[GIN] 2023/09/23 - 01:31:46 | 200 |   17.683918ms | 主cr ip | POST     "/api/v3/slave/ping"
[GIN] 2023/09/23 - 01:31:55 | 200 |   15.405062ms | 主cr ip | POST     "/api/v3/slave/ping"
[GIN] 2023/09/23 - 01:44:45 | 200 |  236.689957ms | 主cr ip | PUT      "/api/v3/slave/upload"  /*这行是测试上传文件返回的日志*/
[GIN] 2023/09/23 - 01:50:22 | 200 |   72.165765ms | 主cr ip | POST     "/api/v3/slave/ping"
[GIN] 2023/09/23 - 01:53:33 | 200 |   49.527096ms | 主cr ip | POST     "/api/v3/slave/ping"
[GIN] 2023/09/23 - 01:53:41 | 200 |   14.416149ms | 主cr ip | POST     "/api/v3/slave/ping"

**Comment by zxcv-12345** [comment]
从本地部署进行复现现象：
![1695503837240](https://github.com/cloudreve/Cloudreve/assets/62590994/d7242587-0444-4685-9562-8904b65056fe)
![1695503917304](https://github.com/cloudreve/Cloudreve/assets/62590994/d750ff5b-fb86-45d6-814b-291e167d80dc)
可从图内看到在本地搭建一个主节点和一个从节点在添加存储的时候一样会出现“`输入参数有误 (Successfully connected to slave node, but slave returns: invalid character '<' looking for beginning of value)`”报错。

**Comment by zxcv-12345** [comment]
并且无法上传文件到通讯报错的从机，如果是云端配置的从机会报`network error`，如果是本机部署的从机与主机也一样无法上传至从机，他会报最后一个分片无法上传从试之后他会自动从头开始再上传但一样会在最后一个分片报错无法完成上传。

**Comment by zxcv-12345** [comment]
新增另一个测试，本地搭建一个cloudreve作为主远程连接另一个异地从机cloudreve。
![image](https://github.com/cloudreve/Cloudreve/assets/62590994/a423f841-1b50-4d38-96e2-ea760a95cde0)
从机配置 (https://send.asen.page/?2b2b889cf8666b56#XNXoqSqvEsTKbDdrxAjJa8k3qYyP4VRw5W44Zvs4e5U) 图中从机输出
 (https://send.asen.page/?fb0c2e92acd5b202#JBz9j4zp19FgBYeU9LehgsYYPAYo4g9xNho7GnmyZ2jx)主机配置 (https://send.asen.page/?c64b6ff6524e252d#2kCJ9Bb1q71w9HZrpwkgRnAkRfgNEeyhSLacv8TY9cx4) 图中主机输出
 (https://send.asen.page/?4040b644e338e5e5#3yWz93wtq4dDzqnoewQJuGZMpdXUyTThjnkgxFAKxx7u)用户名：admin@cloudreve.org
密码：IJ4x0M0M

具体问题：
cloudreve 从机 ping 操作 10 秒未响应，导致主机 ping 从机出现问题。
实际上，不止是 ping 在 10 秒内无法处理完，很多其他的请求也超时，这导致即使强行配置上 cloudreve 从机后，上传文件也无法成功。

**Comment by YUDONGLING** [comment]
直接在终端互PING一下试试。
看你主从是两个不同的本地IP，确认一下会不会是路由/交换机做了限制。

**Comment by aomsir** [comment]
检查主机是否有CDN等

**Comment by zxcv-12345** [comment]
> 检查主机是否有CDN等

额...我冒昧的想请问一下，上述复现实验都是本地局域网内做的复现，即使是后面进行异地部署进行复现都是直接ip对连进行的。

**Comment by zxcv-12345** [comment]
> 直接在终端互PING一下试试。 看你主从是两个不同的本地IP，确认一下会不会是路由/交换机做了限制。

那第一项本地局域网内部署的时候的测试就是主从本地相同局域网内做的复现测试来的，后面第二次那个异地测试ip确定可以互通。

**Comment by Muska-Ami** [comment]
3.8.3复现该问题，目前从机离线下载无法正常转存文件，会一直卡住，然后文件一直在tmp目录里不会被删除

**Comment by zyq2002** [comment]
Same issue

**Comment by way995999** [comment]
同一问题，主机从机都是us，主机和从机都套了CDN，主机从机使用域名或IP都可以正常访问，在主机配置从机向导内，使用从机https域名发送测试数据，返回错误提示和上图一样，主机从机都去除CDN，主机使用IP+端口直接登录，在配置向导内将从机也配置为IP+端口的方式，两个前端都没有了CDN，一样出现上图提示。从机主机的运行日志内都没有错误日志。
