### ISSUE TITLE
ARIA2 Docker 版: 輸入參數有誤 (Failed to connect to RPC server: Unauthorized)

### ISSUE THREAD

**Issue by Georgebobby** [cloudreve/Cloudreve#1849]
https://docs.cloudreve.org/getting-started/install
按照教程走docker版，用自設的[保持和 docker-compose.yml 文件一致] RPC 授权令牌 => justatest
可是就連不到
輸入參數有誤 (Failed to connect to RPC server: Unauthorized)

**Comment by charlieJ107** [comment]
This error should only show when the auth token of aria2 RPC is not match with the configured one. Please double check both the aria2 side and the cloudreve side token configuration.
