### ISSUE TITLE
Support upload muti photos in once

### ISSUE THREAD

**Issue by azheea** [cloudreve/Cloudreve#1850]
**Is your feature request related to a problem? Please describe.**
In my Android phone(HuaWei) I can't upload 2 or more photos in once
**Describe the solution you'd like**

**Describe alternatives you've considered**
Support upload more photos in the one time

**Additional context**
None

**Comment by 01101sam** [comment]
@azheea 遥遥领先

**Comment by LianZiZhou** [comment]
use chrome , not huawei browser.
国产手机厂商内置浏览器使用的WebView核心不符合标准。
