### ISSUE TITLE
挂载B2存储策略无法上传

### ISSUE THREAD

**Issue by reallizeyu** [cloudreve/Cloudreve#1855]
**Describe the bug**
我使用最新版本Cloudreve3.8.2 挂载Backblaze B2 存储策略 一切参数均按教程配置，但无法上传。显示Network Error 。对象存储显示有一个空文件。但使用离线下载功能可正常下载，无法删除。
**To Reproduce**
按照教程配置B2策略后上传即可看见错误
**Expected behavior**
请问有没有大佬知道解决方案，万分感谢
**Screenshots**

**Additional context**
对象存储CROS已手动设置为允许任何来源

**Comment by zxcv-12345** [comment]
他的这个s3确确实实有点小毛病，甚至你用minio自建对象存储都有这种一样的错误。还有就是跨域设置的时候你选自动让cloudreve设置显示错误还是正常？

**Comment by reallizeyu** [comment]
> 他的这个s3确确实实有点小毛病，甚至你用minio自建对象存储都有这种一样的错误。还有就是跨域设置的时候你选自动让cloudreve设置显示错误还是正常？

正常的

**Comment by zxcv-12345** [comment]
> > 他的这个s3确确实实有点小毛病，甚至你用minio自建对象存储都有这种一样的错误。还有就是跨域设置的时候你选自动让cloudreve设置显示错误还是正常？
> 
> 正常的

那就是他这个对象存储策略兼容性可能有问题，我是用minio自建对象存储后能将文件传到对象存储里面但前端页面不显示，换成cf r2就不会。
