### ISSUE TITLE
3.8.3windows无法使用FFmpeg生成本地缩略图，退回到3.8.2就可以了

### ISSUE THREAD

**Issue by yangcore** [cloudreve/Cloudreve#1857]
3.8.3windows无法使用FFmpeg生成本地缩略图，退回到3.8.2就可以了

**Comment by YUDONGLING** [comment]
尝试一下在 Cloudreve.exe 目录下建立 `"/temp/thumb"` 文件夹。

```
- Cloudreve.exe 目录
  - temp 文件夹
    - thumb 文件夹
```

**Comment by yangcore** [comment]
> 尝试一下在 Cloudreve.exe 目录下建立 文件夹。`"/temp/thumb"`
> 
> ```
> - Cloudreve.exe 目录
>   - temp 文件夹
>     - thumb 文件夹
> ```

可以了感谢
