### ISSUE TITLE
对象存储能否支持冷归档（Deep Archive）？

### ISSUE THREAD

**Issue by plmsuper8** [cloudreve/Cloudreve#1868]
目前搜不到相关讨论，不确定对冷归档的支持程度？

* 最重要是支持先解冻，再访问（[RestoreObject接口](https://help.aliyun.com/zh/oss/user-guide/restore-objects-14)）；
* 显示文件的存储类型 & 解冻进度（[ListObjectsV2](https://help.aliyun.com/zh/oss/developer-reference/listobjectsv2)）；
    * 显示\<StorageClass\>和\<RestoreInfo\>字段；

如果能用cloudreve友好的界面，管理长期数据就好了，万分感谢🤝

**Comment by HFO4** [comment]
在计划中， 会在V4加入。

**Comment by HFO4** [comment]
刚看了下，应该支持不了。解冻需要1分钟左右，现有的下载逻辑都要改。

**Comment by plmsuper8** [comment]
我想的是，右键菜单增加一个解冻可以吗？手动点击提交解冻申请（仅限云存储）。

下载逻辑**完全不用变**，如果还没完成解冻，会返回对应报错的。我试了七牛云，会返回{"error":"deep archive unrestored"}。解冻时间甚至会要1天，如果能再加个查询解冻状态菜单更好，没有也没关系。

放到pro里也可以，如果没有这个关键特性，就只能改用其他方案了。
