### ISSUE TITLE
重装数据库以后文件列表无法显示

### ISSUE THREAD

**Issue by mgz0227** [cloudreve/Cloudreve#1869]
版本：3.8.3 Pro
提示信息：
:( 请求时出现错误
Cannot read properties of undefined (reading 'parent')

Redis数据丢失
请问如何修复

**Comment by zxcv-12345** [comment]
有无对数据库进行备份？如果有备份请参考官方论坛 [https://forum.cloudreve.org/d/1460](关于sqlite3 转mysql 教程) 当中的部分思路对数据库从建生成全新的数据库表，然后将备份的数据库导入到新的建的库表当中。

注：提问者put出使用的db是什么故此用MySQL举例说明。
