### ISSUE TITLE
为什么连接不上redis?

### ISSUE THREAD

**Issue by a506488043** [cloudreve/Cloudreve#1875]
**Describe the bug**
redis 没设置密码
![image](https://github.com/cloudreve/Cloudreve/assets/16434125/1c982bc8-93b9-4c8f-bf6b-d44ab7fdfc31)

![image](https://github.com/cloudreve/Cloudreve/assets/16434125/c35112e7-8ed6-47d0-8f76-5668742933f4)

**Comment by zxcv-12345** [comment]
你是不是用的1p面版部署安装的redis？我记得1p面板的reidis是默认有密码的。

**Comment by a506488043** [comment]
> 你是不是用的1p面版部署安装的redis？我记得1p面板的reidis是默认有密码的。

问题解决了，是因为用docker安装的，IP不是 127.0.01.还有苹果的全景照片怎么上传后，列表没的。

**Comment by zxcv-12345** [comment]
> > 你是不是用的1p面版部署安装的redis？我记得1p面板的reidis是默认有密码的。
> 
> 问题解决了，是因为用docker安装的，IP不是 127.0.01.还有苹果的全景照片怎么上传后，列表没的。

存储是什么策略？

**Comment by a506488043** [comment]
> > > 你是不是用的1p面版部署安装的redis？我记得1p面板的reidis是默认有密码的。
> > 
> > 
> > 问题解决了，是因为用docker安装的，IP不是 127.0.01.还有苹果的全景照片怎么上传后，列表没的。
> 
> 存储是什么策略？

本地，现在又正常了。苹果手机app支持照片自动上传不？

**Comment by zxcv-12345** [comment]
> > > > 你是不是用的1p面版部署安装的redis？我记得1p面板的reidis是默认有密码的。
> > > 
> > > 
> > > 问题解决了，是因为用docker安装的，IP不是 127.0.01.还有苹果的全景照片怎么上传后，列表没的。
> > 
> > 存储是什么策略？
> 
> 本地，现在又正常了。苹果手机app支持照片自动上传不？

你意思是说他那个自带的图库里面自动上传？

**Comment by Ervoconite** [comment]
@zxcv-12345 文件名能不能支持 emoji 啊，现在的系统都支持 emoji 文件名了

**Comment by a506488043** [comment]
> > > > > 你是不是用的1p面版部署安装的redis？我记得1p面板的reidis是默认有密码的。
> > > > 
> > > > 
> > > > 问题解决了，是因为用docker安装的，IP不是 127.0.01.还有苹果的全景照片怎么上传后，列表没的。
> > > 
> > > 
> > > 存储是什么策略？
> > 
> > 
> > 本地，现在又正常了。苹果手机app支持照片自动上传不？
> 
> 你意思是说他那个自带的图库里面自动上传？

嗯，我手机存储小，拍不了很多照片。

**Comment by a506488043** [comment]
> > > > > 你是不是用的1p面版部署安装的redis？我记得1p面板的reidis是默认有密码的。
> > > > 
> > > > 
> > > > 问题解决了，是因为用docker安装的，IP不是 127.0.01.还有苹果的全景照片怎么上传后，列表没的。
> > > 
> > > 
> > > 存储是什么策略？
> > 
> > 
> > 本地，现在又正常了。苹果手机app支持照片自动上传不？
> 
> 你意思是说他那个自带的图库里面自动上传？

还有打开图片能增加单击打开吗，双击有点不习惯

**Comment by zxcv-12345** [comment]
> > > > > > 你是不是用的1p面版部署安装的redis？我记得1p面板的reidis是默认有密码的。
> > > > > 
> > > > > 
> > > > > 问题解决了，是因为用docker安装的，IP不是 127.0.01.还有苹果的全景照片怎么上传后，列表没的。
> > > > 
> > > > 
> > > > 存储是什么策略？
> > > 
> > > 
> > > 本地，现在又正常了。苹果手机app支持照片自动上传不？
> > 
> > 你意思是说他那个自带的图库里面自动上传？
> 
> 还有打开图片能增加单击打开吗，双击有点不习惯

他文件管理的逻辑是单击选中双击打开来的，就是依据电脑端使用逻辑。
