### ISSUE TITLE
Failed to create initial root user: Error 1062: Duplicate entry 'admin@cloudreve.org' for key 'uix_cd_users_email'

### ISSUE THREAD

**Issue by hzxie** [cloudreve/Cloudreve#1876]
**Describe the bug**

Failed to create initial root user: Error 1062: Duplicate entry 'admin@cloudreve.org' for key 'uix_cd_users_email'

**Step to reproduce**

`./cloudreve -c /path/to/conf.ini`

** Server
 - OS: Cent OS 8
 - Cloudreve Version 3.8.3

**Additional context**

Please check whether the admin account exists before creating a new one.

**Comment by vvisionnn** [comment]
think you must be in the service upgrade workflow, can you please provide the original Cloudreve version that this database file be created

**Comment by hzxie** [comment]
Before upgrading, the Cloudreve version is 3.8.0.
The database is created by Cloudreve 3.5.0.

**Comment by hzxie** [comment]
It is worth mentioning that I changed the email address of the `root` user after it was created by Cloudreve 3.5.0.
But I confirm that the user with email 'admin@cloudreve.org' indeed exists before upgrading from Cloudreve 3.8.0.
