### ISSUE TITLE
管理员账户异常，重置密码收不到邮件

### ISSUE THREAD

**Issue by yiranxiamo** [cloudreve/Cloudreve#1879]
我的管理员账户在强制删除自己的文件时，忽然弹出至登录界面。
然后，登录就提示：Wrong password or email address

我尝试重启服务器，更换低版本，找回重置密码收不到邮件。测试新注册可以收到邮件。

不知道该怎么办，我有2000多的注册用户。

**Comment by HFO4** [comment]
去数据库里编辑users表，检查下admin用户是否有异常，比如容量数字是不是负数。

**Comment by yiranxiamo** [comment]
> 去数据库里编辑users表，检查下admin用户是否有异常，比如容量数字是不是负数。

修好了，谢谢
数据库内users表，把账户下storage的值改成0就能登录了。
