### ISSUE TITLE
上传头像不生效

### ISSUE THREAD

**Issue by Tensquare9207** [cloudreve/Cloudreve#1881]
**头像上传的持续问题**
1.ctrl+f5缓存刷新无作用
2.清除缓存无作用
3.使用静态资源无作用
4.”上传校验失败时强制重置连接“开启无作用
5.重启服务器无作用
[求解决方法😭]
[版本：社区官方版，版本不知道反正从官网找到的]

**Comment by ruoyuqing** [comment]
同样问题，扩展啥的都安装了，权限也给了，都不生效

**Comment by lyidle** [comment]
一样，我重装好几次都不行，是最新版本的3.8.3；
看服务器里avatar的文件里有上传的头像，但是cloudreve获取不到
![微信截图_20231112195331](https://github.com/cloudreve/Cloudreve/assets/79448635/796cadd0-9d2b-4e74-ae99-2cb66165f450)
![2](https://github.com/cloudreve/Cloudreve/assets/79448635/a31e1c49-d61a-48f3-a927-6ce6fa7ed518)

**Comment by ruoyuqing** [comment]
> 一样，我重装好几次都不行，是最新版本的3.8.3； 看服务器里avatar的文件里有上传的头像，但是cloudreve获取不到 ![微信截图_20231112195331](https://user-images.githubusercontent.com/79448635/282296659-796cadd0-9d2b-4e74-ae99-2cb66165f450.png) ![2](https://user-images.githubusercontent.com/79448635/282296735-a31e1c49-d61a-48f3-a927-6ce6fa7ed518.png)

你开了反向代理是吗？当时用宝塔遇到过这种情况，反向代理开启缓存就解决了

**Comment by lyidle** [comment]
> 
> 你开了反向代理是吗？当时用宝塔遇到过这种情况，反向代理开启缓存就解决了

感谢解决了

**Comment by lyidle** [comment]
> 
> 你开了反向代理是吗？当时用宝塔遇到过这种情况，反向代理开启缓存就解决了
感谢解决了

**Comment by lyidle** [comment]
> 
> 你开了反向代理是吗？当时用宝塔遇到过这种情况，反向代理开启缓存就解决了
还是不得行，开了后我要请缓存才能看到换的头像，而且，切换登录还会出现登不上的情况了，还是关上算了~

**Comment by ruoyuqing** [comment]
> > 你开了反向代理是吗？当时用宝塔遇到过这种情况，反向代理开启缓存就解决了
> > 还是不得行，开了后我要请缓存才能看到换的头像，而且，切换登录还会出现登不上的情况了，还是关上算了~

反向代理里把缓存时间改为0

**Comment by lyidle** [comment]
> 反向代理里把缓存时间改为0
这样可以了，就是还是要清除缓存才能看到换的头像，登录不会出现问题
