### ISSUE TITLE
解压缩大文件失败

### ISSUE THREAD

**Issue by Para-line** [cloudreve/Cloudreve#1890]
在我的服务器上解压缩一个8G的文件时，我观察服务器的监控发现，储存空间先上升后突然下降，我怀疑是因为某种原因解压缩失败，但是客户端没有提示。

Desktop (please complete the following information):
- OS: Windows
- Browser: Chrome
- Version 119.0.6045.159

Server Information
- OS: Ubuntu 22.04
- Cloudreve Version: 3.8.3

同时也希望能够加入一个压缩任务的进度查看，因为解压大文件的时间较久，有这样一个进度心里也有一个底。

**Comment by Para-line** [comment]
我发现在后台可以看到解压缩任务，但是不知道失败的原因
![image](https://github.com/cloudreve/Cloudreve/assets/116947561/34234c68-137c-4663-a758-2f4024432489)

**Comment by Para-line** [comment]
我尝试重新上传一遍文件，并且中间没有中断，仍然出现无法解压缩的问题

**Comment by thenamehasbeentake** [comment]
存储的空间充足吗？是什么类型的压缩格式？有报错的日志吗？
