### ISSUE TITLE
希望能加入的小功能

### ISSUE THREAD

**Issue by Tonmyn** [cloudreve/Cloudreve#1938]
1、希望能直接通过粘贴文件网址链接直接上传文件，就不用在本地先转存一次再上传了；
2、希望能在文件右键后直接复制文件下载链接的按钮，目前需要先点下载按钮然后再浏览器下载器里面点击复制下载链接按钮才能得到下载链接；
3、希望能定期自动导入外部文件的功能，或者添加一个按上次配置导入的按钮，一键按上次配置导入；比如在从外部导入任务列表里面，操作列里面加入一个按钮“再次导入”，点击就可以一键按上次导入任务配置，快速再次导入文件；

**Comment by hatsuyuki280** [comment]
@Tonmyn #1 你可能想问的是：离线下载，软件有支持，自己读文档配

#2 在使用支持的存储策略，且用户组允许的情况下，现在的版本是可以右键复制直链的

#3 现在的版本确实没有这个功能，不过只是定期任务的话，完全可以自己在系统里配置，具体做法可以自己Google

**Comment by Tonmyn** [comment]
@hatsuyuki280   感谢回复

#1 我想的应该是：在当前路径下，我鼠标悬停于加号按钮上面，显示操作按钮，离线下载按钮点击后，弹出输入框，可以直接粘贴文件链接，直接创建上传到**当前目录**下的离线下载任务。个人认为这种方式的使用体验会比现在点击离线下载重新选一遍下载目录更好；
![image](https://github.com/cloudreve/Cloudreve/assets/18096197/610de30f-a87a-47d8-b365-9ac8c0441d6f)


#2 这个已经解决我现在困扰，原来需要在用户组下面设置一下才能复制直链；

#3 我在文档中没有发现关于“从外部导入文件任务”的接口，我用系统自带周期任务功能该执行什么命令才能 实现 cloudreve周期性导入外部文件呢？其实添加“再次导入”功能就已经方便很多了，周期性导入只是“再次导入”功能的扩展。
![image](https://github.com/cloudreve/Cloudreve/assets/18096197/7aa0b387-f3b5-44a6-bf3d-36b718acc1f1)

**Comment by Tonmyn** [comment]
> > @hatsuyuki280 感谢回复
> > #1 我想的应该是：在当前路径下，我鼠标悬停于加号按钮上面，显示操作按钮，离线下载按钮点击后，弹出输入框，可以直接粘贴文件链接，直接创建上传到**当前目录**下的离线下载任务。个人认为这种方式的使用体验会比现在点击离线下载重新选一遍下载目录更好； ![image](https://private-user-images.githubusercontent.com/18096197/301085917-610de30f-a87a-47d8-b365-9ac8c0441d6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDY4ODcsIm5iZiI6MTcwNjcwNjU4NywicGF0aCI6Ii8xODA5NjE5Ny8zMDEwODU5MTctNjEwZGUzMGYtYTg3YS00N2Q4LWIzNjUtOWFjOGMwNDQxZDZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEzMDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYzZjYjg3YjM0ODMzNGQyMWUxYjcyNjhlZmY2Y2M2ZTg1ZTFkYWY4MzUyMDk2NGFkMTlmNTJjN2FiMWNhMTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4N5_hz_VfPkEUqT8rzJ_WI49Y-w5MIcJQEm26mGIpdY)
> > #2 这个已经解决我现在困扰，原来需要在用户组下面设置一下才能复制直链；
> > #3 我在文档中没有发现关于“从外部导入文件任务”的接口，我用系统自带周期任务功能该执行什么命令才能 实现 cloudreve周期性导入外部文件呢？其实添加“再次导入”功能就已经方便很多了，周期性导入只是“再次导入”功能的扩展。 ![image](https://private-user-images.githubusercontent.com/18096197/301082644-7aa0b387-f3b5-44a6-bf3d-36b718acc1f1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3MDY4ODcsIm5iZiI6MTcwNjcwNjU4NywicGF0aCI6Ii8xODA5NjE5Ny8zMDEwODI2NDQtN2FhMGIzODctZjNiNS00NGE2LWJmM2QtMzZiNzE4YWNjMWYxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMzElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTMxVDEzMDk0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM1YWEwMzExZjQ2MmZiYTI1ZTExOGI5ODczMTFhZTU3MmY2Mzg2NmFlMmYyYzZmMjI2Yzg2NDIyZmQ0ZWQwYWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ASPiDRGFEl8N8qUSv6y9oVQTUHF7d8crLUXNQrUwq4E)
> 
> 第一个是这种吗？ ![image](https://private-user-images.githubusercontent.com/81206855/301170074-d5950206-643b-4ac8-b9c3-cf4a8d1857e1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTAxOTUsIm5iZiI6MTcwNjc0OTg5NSwicGF0aCI6Ii84MTIwNjg1NS8zMDExNzAwNzQtZDU5NTAyMDYtNjQzYi00YWM4LWI5YzMtY2Y0YThkMTg1N2UxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAxMTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVmMTFjMmU0NzRmNjBkY2I5ZmY0ODgwYTYwOTA1MzViNmEyOGVmMGJkN2QyNmEzY2ViZmY5OTgyN2ZjNjhhN2YmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ury9EyJDVwOVgbBUY-KWECbVhAY1v50e_J7Vsgjgr2o) ![image](https://private-user-images.githubusercontent.com/81206855/301170104-92a51bbc-2946-4396-9f3f-5c494482472e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDY3NTAxOTUsIm5iZiI6MTcwNjc0OTg5NSwicGF0aCI6Ii84MTIwNjg1NS8zMDExNzAxMDQtOTJhNTFiYmMtMjk0Ni00Mzk2LTlmM2YtNWM0OTQ0ODI0NzJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjAxVDAxMTEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliYzdjMTA3Y2I3NzEyM2NiNzA0ZTRjYmRiNzRhOGMzMjk4YzE3MWFhMTY4YWViOWFiMTQ2NDA5ODYwOGEwMzcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.md8zN7SEUNI0zbsOYQ_8_0GIkoga6VxJEFyoQoPIyFE)

@ssln5014 感谢回复，确实这个就是我想的第一个功能

目前就还剩第3的一个小功能没有实现了。

**Comment by TransparentLC** [comment]
@Tonmyn 

> 希望能定期自动导入外部文件的功能

可以自己用 crontab 定期执行命令把外部文件通过 WebDAV 上传，例如：

```sh
curl -L --output - "https://github.com/cloudreve/Cloudreve/releases/download/3.8.3/cloudreve_3.8.3_windows_amd64.zip" | curl -u user@example.com:webdavpassword -X PUT -d @- http://example.com/dav/path/to/cloudreve_3.8.3_windows_amd64.zip
```

**Comment by Tonmyn** [comment]
> @Tonmyn
> 
> > 希望能定期自动导入外部文件的功能
> 
> 可以自己用 crontab 定期执行命令把外部文件通过 WebDAV 上传，例如：
> 
> ```shell
> curl -L --output - "https://github.com/cloudreve/Cloudreve/releases/download/3.8.3/cloudreve_3.8.3_windows_amd64.zip" | curl -u user@example.com:webdavpassword -X PUT -d @- "https://example.com/dav/path/to/cloudreve_3.8.3_windows_amd64.zip"
> ```

可以使用通配符之类的操作   周期批量导入文件吗？
目前场景大概是这样的， 有一个图床会在存储桶的A文件夹下添加图片，cloudreve添加了这个存储桶，但是cloudreve不会显示从图床上传的文件，所以我想让cloudreve能够定期扫描并添加。

**Comment by TransparentLC** [comment]
我倒是没使用过这个导入文件的功能……不过想到了两个思路，也许能做到？

* F12 抓包管理员账号的 cookie 和导入文件的请求，然后重放请求（不过我没注意 cookie 的有效期是多久）
* 自己写脚本实现遍历存储桶的文件，然后忽略已经在 cloudreve 这边上传过的文件，把剩下的文件通过 WebDAV 上传
