### ISSUE TITLE
没注意安装完成后的信息，怎样才能再次看到这些信息呢，我现在没法打开admin页面

### ISSUE THREAD

**Issue by artest2016** [cloudreve/Cloudreve#194]

**Comment by HFO4** [comment]
管理邮箱 admin@cloudreve.org 密码admin

**Comment by artest2016** [comment]
你好：
我已经安装完成了，但是这块的设置不确定是否正确，麻烦指导下，谢谢


 




------------------ 原始邮件 ------------------
发件人: "AaronLiu"<notifications@github.com>;
发送时间: 2019年8月16日(星期五) 中午11:45
收件人: "cloudreve/Cloudreve"<Cloudreve@noreply.github.com>;
抄送: "zhangjd"<zhjd2010@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [cloudreve/Cloudreve] 没注意安装完成后的信息，怎样才能再次看到这些信息呢，我现在没法打开admin页面 (#194)




管理邮箱 admin@cloudreve.org 密码admin

**Comment by artest2016** [comment]
你好：
我已经安装完成了，但是这块的设置不确定是否正确，麻烦指导下，谢谢



项目我是安装在LAMP的apps下的


 




------------------ 原始邮件 ------------------
发件人: "AaronLiu"<notifications@github.com>;
发送时间: 2019年8月16日(星期五) 中午11:45
收件人: "cloudreve/Cloudreve"<Cloudreve@noreply.github.com>;
抄送: "zhangjd"<zhjd2010@qq.com>;"State change"<state_change@noreply.github.com>;
主题: Re: [cloudreve/Cloudreve] 没注意安装完成后的信息，怎样才能再次看到这些信息呢，我现在没法打开admin页面 (#194)




管理邮箱 admin@cloudreve.org 密码admin
