### ISSUE TITLE
分享链接是本地回环地址

### ISSUE THREAD

**Issue by yejianxing** [cloudreve/Cloudreve#1948]
1.cloudreve版本是3.8.3.部署在debian12云服务器上，使用nginx反向代理，可以通过域名远程连接和登录，但是文件的分享的本地地址。这个是需求还是bug?
![{~JA6EB@S}M)}0M~A4}HI2J](https://github.com/cloudreve/Cloudreve/assets/60419944/ccc0656f-eec6-428d-a141-ce3f3f29fd2c)

**Comment by hatsuyuki280** [comment]
可以先检查一下网盘后台的域名设置是否正确

**Comment by yejianxing** [comment]
请问这个后台是指网盘设置界面还是指conf.ini文件

**Comment by hatsuyuki280** [comment]
@yejianxing 网盘的设置界面

**Comment by yejianxing** [comment]
问题已经解决，谢谢你。

**Comment by hatsuyuki280** [comment]
@yejianxing 麻烦顺手close一下issue哦quq

**Comment by yejianxing** [comment]
1
