### ISSUE TITLE
cloudreve登陆问题

### ISSUE THREAD

**Issue by Pstarchen** [cloudreve/Cloudreve#1950]
3.8.3linux_amd网盘搭建后，登陆管理员之后修改管理员信息，无法跳转到登陆界面，开启验证码登陆后无法登陆。

**Comment by hatsuyuki280** [comment]
@Pstarchen 没有遇到过类似问题  
问题描述可以参考下面的内容，说的更加详细一些  

- 你的操作（复现）过程
- 你期待的行为
- 网盘实际的行为
- 前端是否有提供错误信息
- 后端log是否有错误
- 检查一下数据库里面的数据是否跟你修改后的期待值一致
- 验证码输入正确了嘛
- 其他你觉得对解决问题有帮助的信息

**Comment by Pstarchen** [comment]
@hatsuyuki280 感谢你的回复，问题已经解决了，原因是我不小心打开了反向代理中的开启缓存，导致一直在缓存中，F12关闭内存也没用，现在关闭缓存后就可以正常使用了。

**Comment by hatsuyuki280** [comment]
@Pstarchen 好的

如果解决了的话，可以手动close一下issue哦
