### ISSUE TITLE
项目很不错，只是代码质量真的有点差

### ISSUE THREAD

**Issue by wh469012917** [cloudreve/Cloudreve#197]
建议：
1. 了解一下service业务逻辑层
2. 了解一下模型的关联关系
3. 毕竟都用上tp5了，了解一下请求和响应以及参数验证

**Comment by HFO4** [comment]
感谢建议，当初我还没认真了解MVC架构时就开始写后端了。以后有空再进行下重构！

**Comment by wh469012917** [comment]
@HFO4 
建议从这散步开始：

**Comment by wh469012917** [comment]
@HFO4 
建议从这几步开始：
