### ISSUE TITLE
移动端显示问题

### ISSUE THREAD

**Issue by NoverNobida** [cloudreve/Cloudreve#199]
在手机浏览器中显示有问题，包括头像偏移，不是正中心；没有管理面板和退出等；分享页面未对齐。
![Screenshot_Magic_Browser_20190901-143026](https://user-images.githubusercontent.com/46912250/64072676-914ee080-ccc5-11e9-8f18-0ee313b97fa7.png)

![Screenshot___20190901-143055](https://user-images.githubusercontent.com/46912250/64072681-a0ce2980-ccc5-11e9-9ee5-70422fbbd1b5.png)

**Comment by HFO4** [comment]
V3版本中已解决此问题
