### ISSUE TITLE
主题配色

### ISSUE THREAD

**Issue by NoverNobida** [cloudreve/Cloudreve#200]
当使用浅色（白色）时，“添加项目”会看不清楚，它的颜色是根据主色决定的，希望可以改为独立颜色或根据“Primary colors”中的“对比文字”决定。
![Snipaste_2019-09-01_14-26-02](https://user-images.githubusercontent.com/46912250/64072712-2356e900-ccc6-11e9-8ac4-f27f55bc7b3d.png)

**Comment by HFO4** [comment]
V3版本中已解决此问题，简化了配色模式。
