### ISSUE TITLE
关于下载上传策略的疑问

### ISSUE THREAD

**Issue by yesmiley** [cloudreve/Cloudreve#201]
请问一下，**设置的对象存储/网盘，是单纯地作为存储空间来使用的吗？**（即是否是挂载到服务器，走服务器流量上传和下载文件的）
**能否像 oneindex 这类软件，直接输出官方的下载地址？**
希望能，这样就能很好地避开自建服务器网速不够的问题了。

**Comment by HFO4** [comment]
上传和下载都是直接请求对象存储的服务器的；Onedrive策略的上传则需要中转。

**Comment by Googleing** [comment]
@HFO4 那么确实是很不错的，不知有没有客户端可以配合使用，或者官方开发一个客户端呢？想利用起来搭建一个同步盘
