### ISSUE TITLE
arm 平台安装问题

### ISSUE THREAD

**Issue by ifengchao** [cloudreve/Cloudreve#203]
1）nginx、mysql、php 5.6.16
目前卡在nginx 的配置上
        location / {
                root /tmp/mnt/系统-A/cloud;

                fastcgi_pass   127.0.0.1:9000;
                fastcgi_index  index.php;
                fastcgi_param  SCRIPT_FILENAME  $document_root$fastcgi_script_name;
                include        fastcgi_params;

                if (!-e $request_filename) {
                        rewrite  ^(.*)$  /index.php?s=/$1 break;
                        #break;
                }
        }
网站推荐的可用配置：
                if (!-e $request_filename) {
                        rewrite  ^(.*)$  /index.php?s=/$1 break;
                }
这一段似乎执行不到，访问http://ip/CloudreveInstaller，提示
Access denied.
改为访问 http://ip/index.php?s=/CloudreveInstaller，提示
**控制器不存在:app\index\controller\CloudreveInstaller**

1）尝试新建了一个phpinfo.php，访问http://ip/phpinfo.php 是能正常显示信息的。
2）尝试不通过Installer安装，但缺少一些必要的配置信息，访问http://ip/Admin,
提示未选择数据库。

[10501] PDOException in Connection.php line 385
SQLSTATE[3D000]: Invalid catalog name: 1046 No database selected

**Comment by HFO4** [comment]
可参考ThinkPHP其他伪静态配置方法，你加的位置应该有问题
