### ISSUE TITLE
上传之后看不到文件

### ISSUE THREAD

**Issue by yesmiley** [cloudreve/Cloudreve#204]
又拍云能够上传，但传完之后，无论如何刷新都没有文件显示。
使用兼容 S3 的网易云对象存储则直接出现 HTTP 错误。
本地策略正常。

**Comment by HFO4** [comment]
S3策略尽在S3官方和minio下测试可用，其他的不做保证

**Comment by Googleing** [comment]
明白，但是又拍云的问题不知道怎么回事，主要是这个。 @HFO4

**Comment by HFO4** [comment]
这几天会集中排查修复这种BUG，如果可以的话，到时候可能需要您提供下额外的信息

**Comment by yutao8** [comment]
同样的问题，希望能修复，需要复现bug的话可以联系我

**Comment by ThreeGold127** [comment]
cloudreve 3.2.1 此问题复现。
文件可正常上传到minio，但是在网盘中看不到文件。
使用了2种模式都是这样，查sqlite/mysql，发现 files 库中无数据
