### ISSUE TITLE
文本文件的内容无法显示

### ISSUE THREAD

**Issue by Hansanshi** [cloudreve/Cloudreve#206]
版本号是108（076b9c436475821219e5856755add63acc92c5f1）
在线打开不能显示，显示内容为空，但该文件下载下来又有内容。
通过浏览器的网络页面查看（/File/Content?action=preview&path=/zhihu.txt），发现确实获取到正确的内容，但就是没有显示。

**Comment by jxsd1234a** [comment]
最新版110还是一样

**Comment by HFO4** [comment]
V3版本中已解决此问题
