### ISSUE TITLE
右下角上传按钮容易被浏览器广告遮挡

### ISSUE THREAD

**Issue by dufei99** [cloudreve/Cloudreve#2067]
用户浏览器千奇百怪，比如在国产浏览器中，会被浏览器广告遮挡，在360浏览器中这个按钮都看不到了。可以在界面右上角也添加一个上传的按钮不？

**Comment by dufei99** [comment]
已通过自定义前端解决这个问题，修改\src\component\FileManager\Navigator\SubActions.js文件
![PixPin_2024-04-16_12-11-01](https://github.com/cloudreve/Cloudreve/assets/76577609/32932465-d384-4246-8b7d-9b52b547539f)

**Comment by zzti** [comment]
> 已通过自定义前端解决这个问题，修改\src\component\FileManager\Navigator\SubActions.js文件 ![PixPin_2024-04-16_12-11-01](https://private-user-images.githubusercontent.com/76577609/322699725-32932465-d384-4246-8b7d-9b52b547539f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjg3OTUsIm5iZiI6MTcxNTA2ODQ5NSwicGF0aCI6Ii83NjU3NzYwOS8zMjI2OTk3MjUtMzI5MzI0NjUtZDM4NC00MjQ2LThiN2QtOWI1MmI1NDc1MzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA3NTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MjhkNjVlZDBmMmNiZDIzNzQyNmU0MDBmYjk0YjI4OWViM2YyNzE5ZmE1Y2UzMmJjZTRmODBkOGEwNGFjZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R5V2KvWJVdESoOLUS24wAxhz22bu0C9JQ5mqsCqBBs4)

请问一下这个怎么加呢?能不能分享一下代码

**Comment by dufei99** [comment]
> > 已通过自定义前端解决这个问题，修改\src\component\FileManager\Navigator\SubActions.js文件 ![PixPin_2024-04-16_12-11-01](https://private-user-images.githubusercontent.com/76577609/322699725-32932465-d384-4246-8b7d-9b52b547539f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUwNjg3OTUsIm5iZiI6MTcxNTA2ODQ5NSwicGF0aCI6Ii83NjU3NzYwOS8zMjI2OTk3MjUtMzI5MzI0NjUtZDM4NC00MjQ2LThiN2QtOWI1MmI1NDc1MzlmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA3VDA3NTQ1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTE2MjhkNjVlZDBmMmNiZDIzNzQyNmU0MDBmYjk0YjI4OWViM2YyNzE5ZmE1Y2UzMmJjZTRmODBkOGEwNGFjZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.R5V2KvWJVdESoOLUS24wAxhz22bu0C9JQ5mqsCqBBs4)
> 
> 请问一下这个怎么加呢?能不能分享一下代码
先按照https://docs.cloudreve.org/use/zi-ding-yi-qian-duan文档说明获取前端代码，然后修改代码文件：
\src\component\FileManager\Navigator\SubActions.js

头部添加
```
import { openFileSelector } from "../../../redux/viewUpdate/action";
```
在const 部分加入
```
    const UploadFile = useCallback(
        () => dispatch(openFileSelector()),
        [dispatch]
    );
```
然后在return中找到
```
            <IconButton
                title={t("batchDownload")}
```
在上面加入：
```
            <Button
                variant="contained"
                color="primary"
                onClick={UploadFile}
            >
                {t("uploadFiles")}
            </Button>
```
