### ISSUE TITLE
无法创建上传会话: placeholder file already exist

### ISSUE THREAD

**Issue by Liber1917** [cloudreve/Cloudreve#2082]
**Describe the bug**
无法创建上传会话: placeholder file already exist

**To Reproduce**
在上传各类文件时出现该报错，尝试过清空上传会话和删除temp临时文件夹，并没有成果

**Screenshots**
![屏幕截图 2024-05-10 185407](https://github.com/cloudreve/Cloudreve/assets/108458660/91ebf30e-acde-4f11-b963-51a10ef130d8)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser Edge
 - Version 3.8.3

**Additional context**

**Comment by WHL12243** [comment]
![image](https://github.com/cloudreve/Cloudreve/assets/92345071/1845e8a3-0891-43a0-a879-fa04ef4e431a)

**Comment by WHL12243** [comment]
**After the rename option is enabled, save the storage policy. Try uploading it again.**
![image](https://github.com/cloudreve/Cloudreve/assets/92345071/271b6306-ca0a-4d39-bb6c-6f19cd42bbf7)
![image](https://github.com/cloudreve/Cloudreve/assets/92345071/146aaabd-f418-4429-bfda-52b5cd991afd)
![image](https://github.com/cloudreve/Cloudreve/assets/92345071/039c7824-94d1-4f5a-9db5-6a4855b87c3b)
![image](https://github.com/cloudreve/Cloudreve/assets/92345071/8edc031a-9fe5-47ac-a42e-fac97c21b706)

**Comment by Liber1917** [comment]
感谢🙏，成功上传
