### ISSUE TITLE
请问 lastRawExts 字段在上下文中起到了什么作用？

### ISSUE THREAD

**Issue by PublicPwd** [cloudreve/Cloudreve#2105]
上下文中只被引用了一次，看起来像是用于避免二次解析 exts，但是比较差异后，没有被赋为新的值
https://github.com/cloudreve/Cloudreve/blob/3edb00a6484cef08692245cbbd41421d76ad32e5/pkg/thumb/vips.go#L20-L30
https://github.com/cloudreve/Cloudreve/blob/3edb00a6484cef08692245cbbd41421d76ad32e5/pkg/thumb/ffmpeg.go#L21-L31
https://github.com/cloudreve/Cloudreve/blob/3edb00a6484cef08692245cbbd41421d76ad32e5/pkg/thumb/libreoffice.go#L21-L31

**Comment by HFO4** [comment]
感谢反馈，是一个bug
