### ISSUE TITLE
缩略图生成器支持 LibRaw

### ISSUE THREAD

**Issue by PublicPwd** [cloudreve/Cloudreve#2108]
我已经实现了 LibRaw 生成器相关的代码，用于生成 ARW、DNG、RAF 等 RAW 图像的缩略图，不知是否能提交个 PR ？

**Comment by HFO4** [comment]
欢迎提交PR，但是V3版本不会再发布新版本，我可以手动把你的PR加到V4里面，并注释注明credit，或者您可以在V4发布后提交PR。
我挺好奇您是如何实现的，如果引入了CGO的话，跨平台交叉编译的难度会增加，所以Cloudreve一直没有引入需要CGO的外部库。

**Comment by PublicPwd** [comment]
> 欢迎提交PR，但是V3版本不会再发布新版本，我可以手动把你的PR加到V4里面，并注释注明credit，或者您可以在V4发布后提交PR。 我挺好奇您是如何实现的，如果引入了CGO的话，跨平台交叉编译的难度会增加，所以Cloudreve一直没有引入需要CGO的外部库。

和 vips 的方式一样，调用 LibRaw 工具链的方式，需要使用者下载对应平台的 [LibRaw 可执行程序](https://www.libraw.org/download) ，并在前端仪表盘中配置相关参数。

这是我的[代码实现](https://github.com/PublicPwd/Cloudreve/blob/f4aa9d2976b5add0b7595be74a7d80de2d20cf90/pkg/thumb/libraw.go#L67)

**Comment by PublicPwd** [comment]
> 欢迎提交PR，但是V3版本不会再发布新版本，我可以手动把你的PR加到V4里面，并注释注明credit，或者您可以在V4发布后提交PR。 我挺好奇您是如何实现的，如果引入了CGO的话，跨平台交叉编译的难度会增加，所以Cloudreve一直没有引入需要CGO的外部库。

我才刚看到 V4 Preview 视频，其中 ARW、mp3 已经有了  Exif 信息和封面，这块是已经有了新的处理策略了吗 😂 ，我等 V4 发布后再按需 PR 吧。

**Comment by HFO4** [comment]
V4演示视频里的RAW缩略图其实还是Libvips提取出来的，我测试了下三台设备的RAW只有一台的能被libvips识别，估计大部分RAW还是不行。

**Comment by PublicPwd** [comment]
PR #2109 [frontend#244](https://github.com/cloudreve/frontend/pull/244)

我实测了 8 台设备，包含 5 种品牌，共 ARW、DNG、RAF 三种 RAW 都能读出来。
还有更多 RAW 就只能看社区了
[LibRaw Supported Cameras](https://www.libraw.org/supported-cameras)

**Comment by ShiinaRinne** [comment]
> 欢迎提交PR，但是V3版本不会再发布新版本，我可以手动把你的PR加到V4里面，并注释注明credit，或者您可以在V4发布后提交PR。 

请问这个的意思是 v4 的后端会开源吗?
