### ISSUE TITLE
搬家之后导致所有分享地址改变了!

### ISSUE THREAD

**Issue by imrelax** [cloudreve/Cloudreve#2131]
首先我知道。这个分享地址他不是固定的。而是根据哈希值自动生成的。 分享密码是固定的。
我现在遇到的问题是。
从A主机搬迁到B主机。可能是因为主机系统不同，面板不同，环境不同等原因。
导致我搬家到B主机之后分享地址全部改了

我直接将A主机的upload文件夹压缩。然后到 B主机进行解压。
所以确保了文件夹的修改时间这些是完全没有改变的。但是可能是因为换了系统环境。结果现在就变成全部分享链接失效！！！！

**Comment by YUDONGLING** [comment]
分享地址是根据`shares`表ID，加盐后生成，具体可参考 [https://github.com/cloudreve/Cloudreve/blob/master/pkg/hashid/hash.go#L57](url)。
需要同时迁移配置文件，而不仅仅是上传到本机存储的文件。

**Comment by imrelax** [comment]
麻烦告知下。还要迁移哪些文件。除了数据库文件。 和附件的文件外。还要哪些。。
