### ISSUE TITLE
BUG:  文件名导致上传失败

### ISSUE THREAD

**Issue by anonysoul** [cloudreve/Cloudreve#2136]
**Describe the bug**
文件名为 databasetask-1.0.0.jar 时，选择文件上传后直接提示失败，但是更名为 db.jar 就可以上传成功。

**Expected behavior**
上传成功

**Screenshots**
![upload](http://router.anonysoul.com:2233/i/2024/11/15/j2mh3w.png)

**Comment by hatsuyuki280** [comment]
![image](https://github.com/user-attachments/assets/4c990f30-f2f7-43d0-9e4d-5226c8802c42)
咱的环境下你的问题不存在，建议检查一下你的存储策略的配置

**Comment by hatsuyuki280** [comment]
*补充，咱使用的是S3存储

**Comment by hatsuyuki280** [comment]
![image](https://github.com/user-attachments/assets/05d491fa-fd59-4fd4-b178-3f053ceb1e23)
![image](https://github.com/user-attachments/assets/4f9ef9f0-1f57-48d2-89e9-5f4db139e7f1)

本机存储在咱这里也是可以正常上传的
也许你可以检查下是不是你的文件系统不支持那么长的路径/文件名

**Comment by anonysoul** [comment]
经今日再次尝试，已无此问题。
