### ISSUE TITLE
上传文件失败(Upload session existed)

### ISSUE THREAD

**Issue by XokoukioX** [cloudreve/Cloudreve#2139]
[GIN] 2024/11/23 - 18:02:42 | 200 |    1.190462ms |  49.235.185.240 | POST     "/api/v3/file/upload/4a8d1167-ead2-4704-8170-39151616cc6c/0"

[GIN] 2024/11/23 - 18:02:58 | 200 |     519.802µs |   | GET      "/home?path=%2Fpandownload"

[GIN] 2024/11/23 - 18:02:58 | 200 |      807.31µs |    | GET      "/static/css/6.57254ef2.chunk.css"

[GIN] 2024/11/23 - 18:02:58 | 200 |   57.705621ms |    | GET      "/static/js/main.b93ef58f.chunk.js"

[GIN] 2024/11/23 - 18:02:58 | 200 |   107.20586ms |    | GET      "/static/js/6.df035d4b.chunk.js"

[GIN] 2024/11/23 - 18:02:58 | 200 |    2.148945ms |   | GET      "/api/v3/site/config"

[GIN] 2024/11/23 - 18:02:58 | 200 |     456.395µs |   | GET      "/static/js/12.1cabb2cf.chunk.js"

[GIN] 2024/11/23 - 18:02:58 | 200 |     888.143µs |    | GET      "/api/v3/user/storage"

[GIN] 2024/11/23 - 18:02:58 | 200 |    2.089878ms |    | GET      "/api/v3/directory/pandownload"

[GIN] 2024/11/23 - 18:02:58 | 200 |     600.493µs |    | GET      "/api/v3/user/storage"

[GIN] 2024/11/23 - 18:02:58 | 200 |    2.034687ms |    | GET      "/static/img/favicon.ico"

[GIN] 2024/11/23 - 18:03:01 | 200 |     1.24832ms |  | POST     "/api/v3/user/session"

[GIN] 2024/11/23 - 18:03:01 | 200 |    1.810003ms |  49.235.185.240 | GET      "/api/v3/directory/pandownload"

[Warning] 2024-11-23 18:03:01 Failed to execute hook：Upload session existed

**Comment by XokoukioX** [comment]
![image](https://github.com/user-attachments/assets/5e49c971-dd48-42aa-ad41-e94870acc824)
先前的中断导致传输失败，再次上传的时候提示错误
但是上传队列没有这个文件

**Comment by zxcv-12345** [comment]
> ![image](https://github.com/user-attachments/assets/5e49c971-dd48-42aa-ad41-e94870acc824)
> 先前的中断导致传输失败，再次上传的时候提示错误
> 但是上传队列没有这个文件

你看看后台文件列表里面是不是有这个文件并且显示有“上传”标签。

**Comment by XokoukioX** [comment]
> > ![image](https://private-user-images.githubusercontent.com/52972345/389190009-5e49c971-dd48-42aa-ad41-e94870acc824.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjUzMzksIm5iZiI6MTczMjM2NTAzOSwicGF0aCI6Ii81Mjk3MjM0NS8zODkxOTAwMDktNWU0OWM5NzEtZGQ0OC00MmFhLWFkNDEtZTk0ODcwYWNjODI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDEyMzAzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkODgwMmQyYjQ4MjgyY2MzNzdmYjIyOGFhZGYzOTY0YzkzMTRlODY4MDM0OTE4MGYyMDM3YzI0MjkxMmZlOTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.2NHZsSm-e853rX-ceWsr1UTHaPdJsGz1stB7ezC_KdA)
> > 先前的中断导致传输失败，再次上传的时候提示错误
> > 但是上传队列没有这个文件
> 
> 你看看后台文件列表里面是不是有这个文件并且显示有“上传”标签。

解决了，谢谢
