### ISSUE TITLE
我存了很多书在里面，但是在里面看实在是太难受了有没有什么可以和它对接的看书的软件啊

### ISSUE THREAD

**Issue by txbxxx** [cloudreve/Cloudreve#2143]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hatsuyuki280** [comment]
@txbxxx 一般来说，支持webdav的电子书阅读器都可以兼容cloudreve

具体的你搜就好，有很多

如果你习惯用的阅读器不支持，最坏的情况你可能需要自己用电脑中继一下

**Comment by txbxxx** [comment]
> @txbxxx 一般来说，支持webdav的电子书阅读器都可以兼容cloudreve
> 
> 具体的你搜就好，有很多
> 
> 如果你习惯用的阅读器不支持，最坏的情况你可能需要自己用电脑中继一下

你好我目前找到zotero,但是我链接webdav同步之后在zotero中并没有发现我的图书
