### ISSUE TITLE
希望大佬出升级包

### ISSUE THREAD

**Issue by BloveDawn** [cloudreve/Cloudreve#217]
希望大佬出commit过后的升级包啊，有些图片，文字自定义的真的不想每次都被覆盖啊...

**Comment by shellus** [comment]
就算出升级包，你的模板文件还是会被覆盖的。这个没办法

**Comment by BloveDawn** [comment]
只需要功能文件升级就可以了啊，覆盖PHP文件就够了啊

**Comment by shellus** [comment]
如果坐着要更新模板文件呢？例如页面上增加一个新功能，那就必须要更新模板

**Comment by BloveDawn** [comment]
那是没有办法的事情，但是可以声明一下更新内容
况且加功能的事情目前看来并不常见，现在还是以fix bugs为主啊

**Comment by lendy98** [comment]
这应该是diff包，可以自己保存自己使用的安装包，然后和最新的安装包最下diff，然后半自动半手动diff
