### ISSUE TITLE
启用二步验证之后，二维码扫出来是另一个二维码，第二个二维码扫描正常

### ISSUE THREAD

**Issue by BloveDawn** [cloudreve/Cloudreve#218]
启用二步验证之后，二维码扫出来是另一个二维码，第二个二维码扫描正常
直接扫描第一个二维码只会显示错误

**Comment by HFO4** [comment]
能否提供下第一个二维码的图？

**Comment by BloveDawn** [comment]
这是第一个二维码扫出来的内容
https://api.qrserver.com/v1/create-qr-code/?data=otpauth://totp/测试·网盘?secret=4KI45AAWURFASJTG&size=200x200&ecc=M

**Comment by BloveDawn** [comment]
但是实际上只需要后半部分`otpauth://totp/测试·网盘?secret=4KI45AAWURFASJTG&size=200x200&ecc=M`这一段

**Comment by HFO4** [comment]
感谢反馈

**Comment by HFO4** [comment]
V3版本中已解决此问题
