### ISSUE TITLE
使用php7.3的时候，邮件发送会报错。

### ISSUE THREAD

**Issue by myhenji** [cloudreve/Cloudreve#219]
[ error ] [8192]filter_var(): explicit use of FILTER_FLAG_SCHEME_REQUIRED and FILTER_FLAG_HOST_REQUIRED is deprecated[/extend/PHPMailer/PHPMailer/PHPMailer.php:3597]

换成7.2正常，应该是7.3抛弃了一些函数。

**Comment by Eminlin** [comment]
PHP 7.3.3 Cloudreve 2.0.0-Alpha1
无异常。

**Comment by HFO4** [comment]
V3版本中已解决此问题
