### ISSUE TITLE
七牛存储无法下载

### ISSUE THREAD

**Issue by flyou** [cloudreve/Cloudreve#223]
七牛空间域名与Cloudreve部署域名不一致导致上传的文件无法预览和下载，但是分享的外链地址是正确的。

看地址，预览和下载的地址为 Cloudreve部署的 地址+文件Id，实际地址应该是七牛空间域名+文件id

**Comment by ZL-Asica** [comment]
我也出现了同样的问题，解决了吗？

**Comment by HFO4** [comment]
存储策略中域名格式不正确。
