### ISSUE TITLE
如何连接到具体文件？

### ISSUE THREAD

**Issue by emperinter** [cloudreve/Cloudreve#224]
# 我最近想使用Keepass管理器，其中有一个Webdav使用，我电脑端只有一个连接地址，用户名和密码。请问连接地址如何填写？我自己Ipad上填写后台给的地址能进行选择，但电脑端无此功能，我就有点蒙了，尝试分享链接也不行。找了插件也不想，请问这个能否解决？谢谢！

**Comment by emperinter** [comment]
给出的错误提醒是：
> 远程服务器返回错误：（401）未经授权。

**Comment by HFO4** [comment]
V3版本中已解决此问题
