### ISSUE TITLE
上传文件超过10MB后客户端认证授权失败

### ISSUE THREAD

**Issue by Redbeanw44602** [cloudreve/Cloudreve#225]
![IMG_20191221_115134](https://user-images.githubusercontent.com/29711228/71302616-4548b880-23e8-11ea-9b78-70bf6ddc1be7.jpg)
![IMG_20191221_115122](https://user-images.githubusercontent.com/29711228/71302617-4b3e9980-23e8-11ea-9613-72ecd9f1118a.jpg)
如图所示，上传文件大小达到10MB后突然卡住，然后失败。
检查发现，Cloudreve设置的上传限制＞10MB，Cloudreve所在php限制＞10MB，远程服务器php限制＞10MB

**Comment by Redbeanw44602** [comment]
补充：Nginx的上传限制也＞10MB。另外cloudreve.org的tg链接似乎失效了

**Comment by lendy98** [comment]
设置下Nginx上传文件限制大小，这是nginx默认的10M。和Cloudreve无关

**Comment by Redbeanw44602** [comment]
nginx的限制是50M，我换本地服务器存储了，不整这个问题了。

**Comment by xiaolinenet** [comment]
要改下后台上传策略的 扩展名，扩展名要加入， 另外 发现第一次改是不行的，清理一下缓存试试 我是好用了

**Comment by xiaolinenet** [comment]
要改下后台上传策略的 扩展名，扩展名要加入， 另外 发现第一次改是不行的，清理一下缓存试试 我是好用了 Jason-张百万就是我了 欢迎大家 体验 fastnas os
