### ISSUE TITLE
PHP7.4不再支持使用大括号访问数组以及字符串的偏移

### ISSUE THREAD

**Issue by Gemo-X** [cloudreve/Cloudreve#229]
Array and string offset access syntax with curly braces is deprecated. 此处需要修正

**Comment by HFO4** [comment]
Thanks for reporting, it wil be fixed in the next refactored version.

**Comment by cary-zhou** [comment]
导致新建离线任务返回500状态码

**Comment by HFO4** [comment]
V3版本中已解决此问题
