### ISSUE TITLE
希望增加对谷歌网盘的对接

### ISSUE THREAD

**Issue by lovage** [cloudreve/Cloudreve#23]
希望增加对谷歌网盘的对接

**Comment by 1424753988** [comment]
我也希望

**Comment by madlaxcb** [comment]
作者说不会远了，期待。

**Comment by madlaxcb** [comment]
> 
> 
> 可以对接google drive，我都在用着，挂载后直接在上传策略改就可以了，百度也有现成的啊似乎
也许我和你用的不是一套源码？

**Comment by bigrain1993** [comment]
> 也许我和你用的不是一套源码？
> 
> > 可以对接google drive，我都在用着，挂载后直接在上传策略改就可以了，百度也有现成的啊似乎
大佬有没有对接的代码呀
