### ISSUE TITLE
 Local upload problem 

### ISSUE THREAD

**Issue by Gemo-X** [cloudreve/Cloudreve#230]
The disk still has a space of nearly 1t, but only 1g has been identified. Once the upload limit is reached, it cannot be uploaded.

**Comment by HFO4** [comment]
Cloudreve will follow user-group's capacity setting, rather than detecting disk space initiatively.

**Comment by Gemo-X** [comment]
Sorry, I can't find the related settings. It was found in previous issues that each user has only 1g capacity limit. Can't user groups be provided?
Administrators only have 1g of capacity?
