### ISSUE TITLE
关于名称合法性问题

### ISSUE THREAD

**Issue by jadendong** [cloudreve/Cloudreve#236]
问题描述：我上传了一个视频，名称中有+号，预览时出现视频加载不了。

经过排查，确实是名称不合法。只需修改名称即可（无需重传）即可播放视频。另外提示说只支持汉字，字母，数字及下划线和破折号。想必是考虑到了这个问题（测试空格也可以）。

所以想提个建议，能否在上传时就检查名称是否合法呢？

另外貌似目前视频预览只支持mp4格式

**Comment by HFO4** [comment]
V3版本中已解决此问题
