### ISSUE TITLE
关于分片上传及上传策略的建议

### ISSUE THREAD

**Issue by tuzi3040** [cloudreve/Cloudreve#24]
1.建议添加管理员自定义分片上传分片大小功能（建议集成在上传策略中）
2.建议支持自定义本地存储目录及分片上传缓存目录（建议支持二者能挂载不同文件系统，即互为同级或为相互独立目录。这样实现提供高速合并分片，再统一由服务器写入文件系统。会比较适合自行挂载远端存储到文件系统的用户）（希望支持路径在网站主目录外）

**Comment by tuzi3040** [comment]
建议一个用户可设置多个上传策略

**Comment by HFO4** [comment]
不错的建议，会考虑在后续更新加入

**Comment by fantastlcok** [comment]
@HFO4  希望能多线程上传，一个线程海外服务器上传有点慢。
