### ISSUE TITLE
希望可以加入google drive的支持

### ISSUE THREAD

**Issue by swjsky** [cloudreve/Cloudreve#242]
希望可以加入google drive的支持，虽然这样无法商业化，但是很多用户还是很有需求的

**Comment by ODtian** [comment]
你的想法很不错，但是其实gd的api有限制的，某一个文件访问次数过多就不给用了，要等一段时间（通常是24小时），我也是最近玩api的时候才知道的

**Comment by 742481030** [comment]
rclone 挂载

**Comment by swjsky** [comment]
> rclone挂载

如何整合到面板内？

**Comment by 742481030** [comment]
参考rclone 在linux 挂载成目录然后然后后台添加本地存储即可大陆有墙所以上传下载都从服务器中转

**Comment by swjsky** [comment]
> ux上挂载成目录然后然后后台

非常感谢大神的思路。

**Comment by HFO4** [comment]
参见#23
