### ISSUE TITLE
文件能下载，但是播放视频时，页面返回找不到文件

### ISSUE THREAD

**Issue by wadeLouis** [cloudreve/Cloudreve#244]
preview页面返回：{ "result": { "success": false, "error": "文件不存在" } }
视频是mp4文件。
其他视频文件播放正常。
经过比较，只要文件名称带有+号的，就不能正常播放。比如：BJ Goeun {레이샤고은} X BJ Boreum {레이샤보름} ~ Marian Hill Down + Gnarls Barkley Crazy sexy dance.mp4
preview的接口path参数会变成
path: /BJ Goeun {레이샤고은} X BJ Boreum {레이샤보름} ~ Marian Hill Down   Gnarls Barkley Crazy sexy dance.mp4
缺少了+号。

**Comment by wadeLouis** [comment]
好吧，经典的$_get 加号问题。
修改View.php Video方法中url赋值时对path参数进行一次encode就行

**Comment by lendy98** [comment]
Get

**Comment by lendy98** [comment]
Viewer.php Video方法
'url' => $url,
改
'url' => urldecode($url),

另外这个播放器不支持h.265怎么破？
