### ISSUE TITLE
建议捐赠版增加对腾讯云的支持

### ISSUE THREAD

**Issue by KS-OTO** [cloudreve/Cloudreve#245]
建议捐赠版增加对腾讯云的支持，相对来将腾讯云的存储和传输价格要较阿里云具有优势；

**Comment by HFO4** [comment]
V3版本会加入2020年2月28日 下午3:43，KS-OTO <notifications@github.com>写道：建议捐赠版增加对腾讯云的支持，相对来将腾讯云的存储和传输价格要较阿里云具有优势；

**Comment by HFO4** [comment]
已经加入
