### ISSUE TITLE
实在搞不懂绑定OneDrive该怎么操作。

### ISSUE THREAD

**Issue by Xuyiyang23333** [cloudreve/Cloudreve#246]
一直报错……是因为我没启用SSL所以无法使用https，导致回调地址无效吗？Azure应用的回调地址只允许设置为https协议……
![Screenshot_20200229_164126](https://user-images.githubusercontent.com/44458111/75604387-0e430180-5b13-11ea-9fb5-7db106430465.png)

**Comment by HFO4** [comment]
等待v3会优化对接指引向导2020年2月29日 下午4:47，徐艺扬 <notifications@github.com>写道：一直报错……是因为我没启用SSL所以无法使用https，导致回调地址无效吗？Azure应用的回调地址只允许设置为https协议……

**Comment by Xuyiyang23333** [comment]
> 等待v3会优化对接指引向导2020年2月29日 下午4:47，徐艺扬 <notifications@github.com>写道：一直报错……是因为我没启用SSL所以无法使用https，导致回调地址无效吗？Azure应用的回调地址只允许设置为https协议…… —You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.

谢谢，辛苦了。

**Comment by HFO4** [comment]
已经发布
