### ISSUE TITLE
手动添加本地目录下的文件

### ISSUE THREAD

**Issue by FatBoss-wang** [cloudreve/Cloudreve#248]
文件直接扔进uploads里对应文件夹没用.....
像nextcloud有一个occ files:scan --all的命令行可以用，cloudreve有类似解决办法嘛）

**Comment by YCF** [comment]
扫描功能很重要，没有的话挺难迁移过来。

**Comment by HFO4** [comment]
已在 e8a6df9 后实现，参见#304
