### ISSUE TITLE
外链下载很快没速度

### ISSUE THREAD

**Issue by lloyd18** [cloudreve/Cloudreve#250]
获取外链到玩客云下载，下载的是本地储存。大概3分钟左右 下载到300MB左右大小 就没速度了，IO飙到300MB/s,用浏览器直接下载没问题。已在参数设置增加有效期并重启也没用。

![QQ拼音截图未命名](https://user-images.githubusercontent.com/10294460/76711395-ae6f6c00-674a-11ea-81bb-177426ee003c.jpg)
![2](https://user-images.githubusercontent.com/10294460/76711421-d1018500-674a-11ea-9560-93a4c63901c9.jpg)

**Comment by qzwl** [comment]
这个问题 咋没人说呢，我也碰到了类似的问题。发现下载的人并发很大，然后造成io高。服务器卡死。
