### ISSUE TITLE
关于Cloudreve在手机端展示的问题

### ISSUE THREAD

**Issue by WumaCoder** [cloudreve/Cloudreve#251]
- 无法回到上一级文件夹
- 刷新后会跳转到首页

**Comment by mn19941219** [comment]
我的刷新会回到登陆页面

**Comment by HFO4** [comment]
> 无法回到上一级文件夹

可通过浏览器“后退”返回

> 刷新后会跳转到首页

检查 CDN 或者上层Web服务器是否缓存了`/api/*`
