### ISSUE TITLE
关于一些Bug和意见

### ISSUE THREAD

**Issue by holleworldabc** [cloudreve/Cloudreve#252]
## Bug
- 无法打开office文件
- 无法设置多个域名访问
## 意见
- 希望引入插件开发，通过开发插件可以更多的支持文件打开方式，主题更换，等其他的功能
- 插件市场，用户可以上传自己的插件到插件市场

**Comment by HFO4** [comment]
> 无法打开office文件

这个请检查下站点URL设置，并且需要是外网能否访问的。

> 无法设置多个域名访问

不明白什么意思，多个域名解析到一个 IP 不行吗

> 希望引入插件开发，通过开发插件可以更多的支持文件打开方式，主题更换，等其他的功能

静态语言实现插件功能比较难，Go 原生的插件机制也不支持 Windows 平台
