### ISSUE TITLE
本地设置conf.ini文件中Redis的Password密码含有#号,系统不能正常启动

### ISSUE THREAD

**Issue by 1990lsf** [cloudreve/Cloudreve#253]
conf.ini文件配置
`[Redis]
Server = 127.0.0.1:6379
Password = 111#31111
DB = 0`
系统启动报
无法创建Redis连接：ERR invalid password

**Comment by 1990lsf** [comment]
我知道了，需要 使用 ` 或 """ 进行包覆

**Comment by wodepig** [comment]
"""111#31111"""
