### ISSUE TITLE
Mac系统无法运行 打包能否添加Mac系统的平台~

### ISSUE THREAD

**Issue by fhefh2015** [cloudreve/Cloudreve#255]

**Comment by HFO4** [comment]
Mac 平台下需要交叉编译，我身边没有 Mac 设备。但是交叉编译需要找到对应的 GCC 工具链，目前还没找到针对 Darwin 下能用的。

**Comment by LunaGao** [comment]
Need this too

**Comment by 742481030** [comment]
https://github.com/742481030/Cloudreve/releases/download/3.0.0/cloudreve_3.0.0_macos_released_9910f8d.zip

**Comment by cjs520** [comment]
需要mac端可以找我，我qq是2930755201

**Comment by 742481030** [comment]
> GCC

移除sqllite 就能go自己交叉编译了

**Comment by mritd** [comment]
可以调整 travis ci 实现 自动打包  https://docs.travis-ci.com/user/reference/osx/

**Comment by 742481030** [comment]
> 可以调整 travis ci 实现 自动打包 https://docs.travis-ci.com/user/reference/osx/

本来go可以编译的但是sqllite必须cgo 所以要安装交叉编译,
brew install gcc
brew install mingw-w64 (win)
 brew install FiloSottile/musl-cross/musl-cross (amd64-linux)
mac arm工具链报错

**Comment by 742481030** [comment]
> 可以调整travis ci实现自动打包 https://docs.travis-ci.com/user/reference/osx/

这啥玩意?  macos版本 macos本机 编译直接go build 就行了

**Comment by 742481030** [comment]
> 可以调整travis ci实现自动打包 https://docs.travis-ci.com/user/reference/osx/

这个怎么搞?能搞个配置文件吗 
我看了不会配置,我macos 在linux 上没有交叉工具, macos 本机我可以编译win和linux 和本机的,这玩意工具挺好玩的

**Comment by 742481030** [comment]
> _没有提供描述。_
https://github.com/742481030/Cloudreve/releases/download/3.1.1.0001/cloudreve_darwin_V3.1.1-5-g40414fe_.Commit.40414fe.zip
我帮你编译了个

**Comment by mritd** [comment]
Cloudreve 项目使用了 travis ci，可以调整 travis ci 来实现多平台直接编译然后上传 release，不过目前我看一部分是通过 github workflow 完成。

**Comment by 742481030** [comment]
> Cloudreve 项目使用了 travis ci，可以调整 travis ci 来实现多平台直接编译然后上传 release，不过目前我看一部分是通过 github workflow 完成。 

编译不通过嘛  如何配置呢能给个配置文件吗,虽然我用不上哈哈
我本机macos的编译脚本是这样的
任意macos可以直接编译成功
`
REPO=$(cd $(dirname $0); pwd)

cd $REPO
command -v brew || /bin/zsh -c "$(curl -fsSL https://cdn.jsdelivr.net/gh/742481030/cnhomebrew@master/Homebrew.sh)"
command -v x86_64-linux-musl-gcc || brew install FiloSottile/musl-cross/musl-cross
command -v x86_64-w64-mingw32-gcc || brew install mingw-w64
command -v go ||brew install go
command -v node || brew install node
command -v yarn || brew install yarn 
command -v upx ||brew install uxp 




 

go build -x -v -ldflags "-s -w" -o cloudrev-macos && upx -9 cloudrev-macos ||echo "编译请检查runtime"

env CGO_ENABLED=1 CC=x86_64-w64-mingw32-gcc CXX=x86_64-w64-mingw32-g++ GOOS=windows GOARCH=amd64 go build  -v -ldflags "-s -w" -o cloudrev_x64.exe && upx -9 cloudrev_x64.exe ||echo "win64编译失败"

env CGO_ENABLED=1 CC=i686-w64-mingw32-gcc CXX=i686-w64w64-mingw32-g++ GOOS=windows GOARCH=386 go build  -v -ldflags "-s -w" -o cloudre_x86.exe && upx -9 cloudre_x86.exe ||echo "win32编译失败"

env CGO_ENABLED=1 CC=x86_64-linux-musl-gcc GOOS=linux GOARCH=amd64 go build -ldflags "-linkmode external -extldflags -static -s -w"   -o cloudreve_linux-64 && upx -9 cloudreve_linux-64 || echo "linux编译失败"`

**Comment by 742481030** [comment]
> Cloudreve 项目使用了 travis ci，可以调整 travis ci 来实现多平台直接编译然后上传 release，不过目前我看一部分是通过 github workflow 完成。

一堆的报错哈
