### ISSUE TITLE
aria2下载问题

### ISSUE THREAD

**Issue by leeyiding** [cloudreve/Cloudreve#257]
当我使用A机器反向代理B机器的cloudreve程序时，Aria2下载https资源会报错，报错内容是`SSL/TLS：handshake failure：unable to get local issure certificate`

**Comment by HFO4** [comment]
可以使用`--check-certificate=false`避免此问题，参考 https://github.com/aria2/aria2/issues/889

**Comment by leeyiding** [comment]
感谢大佬，在aria2的配置文件添加`check-certificate=false`成功解决问题
