### ISSUE TITLE
V3-RC1部分情况无法上传

### ISSUE THREAD

**Issue by Dustin-Jiang** [cloudreve/Cloudreve#259]
在Windows, macOS上传文件报错. 
![图片](https://user-images.githubusercontent.com/56217843/77143216-8a4eba80-6abd-11ea-8e98-8177fb017344.png)
拖拽上传无问题. 
在Android, iOS上测试无问题. 

服务器: Windows Server 2019 v1809
Cloudreve: 3.0.0 RC1 win amd64

**Comment by HFO4** [comment]
刷新下页面即可。目前这个错误只会在管理员从后台切回前台出现，暂时没有较好的解决办法。

**Comment by Dustin-Jiang** [comment]
非管理员用户登录后同样有此问题.
