### ISSUE TITLE
V3-RC1 一处书写错误

### ISSUE THREAD

**Issue by cattomgithub** [cloudreve/Cloudreve#262]
在首页，文件排序处有一处书写错误。
![QQ截图20200321124858](https://user-images.githubusercontent.com/16714790/77219626-9ea0bf00-6b72-11ea-9342-d28a1139aaa5.png)
![QQ截图20200321124932](https://user-images.githubusercontent.com/16714790/77219633-a6f8fa00-6b72-11ea-8b6c-fb37c12a96e5.png)
虽然不是什么大毛病，不影响正常使用，但还是希望尽快修改。

**Comment by HFO4** [comment]
已经更正，感谢反馈！
