### ISSUE TITLE
无法下载网盘中的文件

### ISSUE THREAD

**Issue by suzhigao** [cloudreve/Cloudreve#263]
如下图所示，请问为什么下载不了文件
![QQ截图20200321203641](https://user-images.githubusercontent.com/48432805/77226494-b9dfee80-6bb3-11ea-8ac7-04f74f2f95a1.png)

**Comment by suzhigao** [comment]
![QQ截图20200321204452](https://user-images.githubusercontent.com/48432805/77241657-462ff700-6c30-11ea-93ff-6b58f82f896c.png)

**Comment by HFO4** [comment]
尝试使用V3版本代替，应该没有此问题了
