### ISSUE TITLE
arm版本不能运行

### ISSUE THREAD

**Issue by eshion** [cloudreve/Cloudreve#268]
分别下载了3个arm的版本试了：
cloudreve_3.0.0-beta3_linux_arm.tar.gz
cloudreve_3.0.0-rc1_linux_arm.tar.gz
cloudreve_3.0.0-beta1_linux_arm.tar.gz 
各个分别用tar -zxf 解压后，chomd +x，再运行./cloudreve
提示：
-sh: ./cloudreve: not found
用n1盒子测试。

**Comment by lujiaxing** [comment]
斐讯 N1 盒子用的 CPU Amlogic S905D. 架构为 ARM64. 官方编译只提供了 ARM32 的版本. 必然不能用. 你需要使用 ARM64 的工具链自行编译.

**Comment by anleihn** [comment]
可以试试https://github.com/xavier-niu/cloudreve-docker 我用我家云docker成功部署

**Comment by eshion** [comment]
> 可以试试https://github.com/xavier-niu/cloudreve-docker 我用我家云docker成功部署

可以运行，非常棒！感谢感谢！

**Comment by eshion** [comment]
> 可以试试https://github.com/xavier-niu/cloudreve-docker 我用我家云docker成功部署

@anleihn 可以运行，非常棒！感谢感谢！

**Comment by HFO4** [comment]
3.0.0版本release时已带有arm64版本

**Comment by eshion** [comment]
试了下3.0.0的arm64版本，还是不行，提示：
ash: ./cloudreve: not found

@HFO4

**Comment by BioniCosmos** [comment]
> 试了下3.0.0的arm64版本，还是不行，提示：
> ash: ./cloudreve: not found
> 
> @HFO4

not found 不是写的很清楚吗？

**Comment by lujiaxing** [comment]
> > 试了下3.0.0的arm64版本，还是不行，提示：
> > ash: ./cloudreve: not found
> > @HFO4
> 
> not found 不是写的很清楚吗？
> 
> 你用 `ls` 指令看一下 `cloudreve` 文件是否在当前目录，不在的话用 `cd` 指令切换过去。

不是因为文件不存在. 而是文件存在但是编译架构与当前系统架构不一样.

**Comment by eshion** [comment]
文件是存在的。我的斐讯 N1 盒子的系统是这样的
# uname -a
Linux phicomm 4.18.14-2-amlogic #3-Alpine SMP PREEMPT Thu Nov 8 10:26:15 UTC 2018 aarch64 GNU/Linux

**Comment by adriftliu** [comment]
是不是这个不对
`interpreter /system/bin/linker`

cloudreve是这样的 `interpreter /lib/ld-linux-aarch64.so.1`

盒子、手机是没有 /lib 目录的，用的是`interpreter /system/bin/linker`

**Comment by adriftliu** [comment]
> 分别下载了3个arm的版本试了：
> cloudreve_3.0.0-beta3_linux_arm.tar.gz
> cloudreve_3.0.0-rc1_linux_arm.tar.gz
> cloudreve_3.0.0-beta1_linux_arm.tar.gz
> 各个分别用tar -zxf 解压后，chomd +x，再运行./cloudreve
> 提示：
> -sh: ./cloudreve: not found
> 用n1盒子测试。

我在termux上试了下，缺这些，但是我的N1刷了armbian是可以用的，很奇怪
libpthread.so.0
libdl.so.2
libc.so.6
ld-linux-aarch64.so.1

**Comment by expoli** [comment]
@adriftliu 试一下自己编译 设置环境 CGO_ENABLED=0

**Comment by expoli** [comment]
@adriftliu 默认编辑开启了cgo，依赖一些c库文件

**Comment by stonegr** [comment]
> @adriftliu 默认编辑开启了cgo，依赖一些c库文件

你好，官方可以不开启cgo吗？

**Comment by qian-jiahong** [comment]
我编译 ARMv5 版本，运行时，也遇到相同的问题：-sh: ./cloudreve: not found。
有办法解决了吗？

**Comment by wnpllrzodiac** [comment]
架构不一样，arm有十几个架构

**Comment by qian-jiahong** [comment]
> 架构不一样，arm有十几个架构

已经编译好了。在另外的贴有说明。
