### ISSUE TITLE
两个BUG及一个建议

### ISSUE THREAD

**Issue by yeungc** [cloudreve/Cloudreve#270]
1. 离线下载功能 - 体积比较小的档案 有时候会显示"文件转存失败" 但仍然会在在文件夹里出现 而且如果是图片档的话 也不会生成缩图 个人觉得原因可能是文件太小 系统处理太快导致步骤错乱
![图片](https://user-images.githubusercontent.com/7931068/77364106-dc7a2f00-6d8e-11ea-99e4-9cf62f3ff0db.png)

2. 压缩功能 - 压缩完成后 最后进度栏位还是显示"转存中"，改成显示"已完成 x 个文件"比较好
![图片](https://user-images.githubusercontent.com/7931068/77364515-79d56300-6d8f-11ea-914b-0c2923bbaa67.png)

3. 有文件在上传中的时候 只要离开"我的文件"页面 上传就会中断而且没提示 建议上传组件可存在于每一页 或者至少在用户离开"我的文件"时 用对话框提示上载进度会被取消

**Comment by HFO4** [comment]
1. 目前版本离线下载的文件都是没有缩略图的，日后可能会增加。
2 和3 会在未来考虑优化。
