### ISSUE TITLE
无需登录可查看用户内的文件和分享

### ISSUE THREAD

**Issue by Xiaobin2333** [cloudreve/Cloudreve#271]
宝塔反代，套了cloudflare cdn，登录账号后，用户登录信息会被cf缓存，游客无需登录可以查看被缓存用户的个人信息，用户内所有文件以及分享，但无法进行操作，存在泄露隐私问题。
附上cf页面规则：
example.com/*
浏览器缓存 TTL: 1 天, 缓存级别: 缓存所有内容, 边缘缓存 TTL: 2 小时

**Comment by HFO4** [comment]
CDN缓存时忽略`/api/*`试试呢

**Comment by Xiaobin2333** [comment]
> CDN缓存规则中，忽略`/api/*`试试呢

已解决，谢谢！
