### ISSUE TITLE
1.如何上传文件夹2.那个APP能连接WebDAV

### ISSUE THREAD

**Issue by ZiDuNet** [cloudreve/Cloudreve#273]
1.如何上传和下载文件夹
2.那个APP能连接WebDAV

**Comment by HFO4** [comment]
1. 右下角浮动按钮可上传目录
2. 客户端可参考 https://zh.wikipedia.org/wiki/WebDAV%E8%BD%AF%E4%BB%B6%E6%AF%94%E8%BE%83
