### ISSUE TITLE
建议加入自定义统计代码和公告栏

### ISSUE THREAD

**Issue by TheresaQWQ** [cloudreve/Cloudreve#275]

**Comment by IveTian** [comment]
应该是有自定义统计代码的emmmmmm
公告栏自认为可以通过侧边栏的html内容解决

**Comment by HFO4** [comment]
V3版本为单页应用，市面上统计代码无法生效，所以不会加入。公告栏暂时不在计划内，因为不是只要需求，不过未来可能会加入。
