### ISSUE TITLE
后台通过rm删除的文件主页上始终显示

### ISSUE THREAD

**Issue by molezz** [cloudreve/Cloudreve#277]
没办法清理，主页和控制面板都没法子

**Comment by syf2005** [comment]
是的哦，上传的文件记录到数据库里，只能通过cloudreve管理，自己删除数据库不能知道啊

**Comment by gtf35** [comment]
但是有的时候七牛云上传失败，他还记录了，或者删除文件，七牛删除了，他还在，就是很尴尬，删不掉
