### ISSUE TITLE
是否支持多个存储策略同时用【>3.0】

### ISSUE THREAD

**Issue by excxapp** [cloudreve/Cloudreve#279]
请问是否有计划这样做。
另外pdf预览问题，3.0以上不支持。建议pdfjs支持一下

**Comment by HFO4** [comment]
多个存储策略具体是指？
PDF预览会在未来加入。

**Comment by excxapp** [comment]
就是同时可以策略存储，比如，我选择了两个策略之后，那么，我文件同时存在两个策略里面，备份安全。

pdfjs,这个挺有用的，如果你时间不足，是否可以我改前端之后pr

**Comment by leeyiding** [comment]
> 就是同时可以策略存储，比如，我选择了两个策略之后，那么，我文件同时存在两个策略里面，备份安全。
> 
> pdfjs,这个挺有用的，如果你时间不足，是否可以我改前端之后pr

这个是高级版的功能吧

**Comment by excxapp** [comment]
为同一用户组绑定多个存储策略，用户可自由切换
官方高级版是这个。选择，但不是同时，看来还需要自己定制才行啊
