### ISSUE TITLE
OneDrive上传时出现问题

### ISSUE THREAD

**Issue by Zfusheng** [cloudreve/Cloudreve#280]
存储策略使用的OneDrive，之前使用一直没问题，但最近上传文件突然一直失败。每次文件上传到20M左右，就会出现失败提示：
The request has been throttled.
请问该如何解决。

**Comment by HFO4** [comment]
可能原因是OneDrive的API请求频繁，被限流了

**Comment by Zfusheng** [comment]
那么有什么比较好的方法避免出现这种情况或者在出现这种情况后解决呢？

**Comment by Zfusheng** [comment]
> 可能原因是OneDrive的API请求重复，被限流了

那么有什么比较好的方法避免出现这种情况或者在出现这种情况后解决呢？

**Comment by HFO4** [comment]
> > 可能原因是OneDrive的API请求重复，被限流了
> 
> 那么有什么比较好的方法避免出现这种情况或者在出现这种情况后解决呢？

暂时没有，可能会在每个文件上传前增加时间间隔。

**Comment by ODtian** [comment]
是api的限制，官方说每10分钟10000次请求，但是实测比这个小
