### ISSUE TITLE
图片能够上传，但是下载失败

### ISSUE THREAD

**Issue by webbin** [cloudreve/Cloudreve#283]
cloudreve服务搭建起来了，局域网使用，没有用第三方云盘，在web端上传了几张图片，点击图片，选择顶部提供的下载按钮，下载报错。
图片下载地址：http://localhost/api/v3/file/download/qbPQOMrmpX0BmUom?sign=PgQ1PbDLPJKHk8gNnhxWP2RGA0DARPmKMg_-xM0ZNAk%3D%3A1585751852
图片地址的域名是localhost，改成服务器的地址，也是一样报错。看后台打印的日志也没有什么特别的信息。
请问一下这个是什么问题？

服务运行环境是树莓派，系统是ubuntu mate

以下是截图：

<img width="1000" alt="屏幕快照 2020-04-01 下午10 36 21" src="https://user-images.githubusercontent.com/9608177/78150323-b9740d00-7469-11ea-864d-912976e1ff58.png">
<img width="1223" alt="屏幕快照 2020-04-01 下午10 36 41" src="https://user-images.githubusercontent.com/9608177/78150338-bf69ee00-7469-11ea-83d7-428ab5390a9a.png">

<img width="1037" alt="屏幕快照 2020-04-01 下午10 42 10" src="https://user-images.githubusercontent.com/9608177/78150632-24bddf00-746a-11ea-9921-1e6c848090bd.png">

**Comment by HFO4** [comment]
检查 后台 - 站点信息 - 站点URL

**Comment by jingkang99** [comment]
检查 后台 - 站点信息 - 站点URL???

在哪设置？

**Comment by jingkang99** [comment]
![image](https://user-images.githubusercontent.com/10793075/129518740-3dfc37c2-3928-41a4-a338-d328759151f8.png)
在 管理面板 设置
