### ISSUE TITLE
支持异步上传

### ISSUE THREAD

**Issue by RockJohnson503** [cloudreve/Cloudreve#285]
同步上传太慢了，无法把上行带宽跑满，我试了异步上传，可以把上行带宽跑满，另外就是应该像百度云盘一样，做个文件hash,加上索引,上传的时候先检查是否有这个文件的hash,有就直接加一条记录，然后修改一下其他的信息就可以了

**Comment by HFO4** [comment]
您说的 同步/异步 上传具体指的是？
文件hash计算开销较大，产生的回报比较低，暂时不会考虑增加此特性。

**Comment by RockJohnson503** [comment]
> 您说的 同步/异步 上传具体指的是？
> 文件hash计算开销较大，产生的回报比较低，暂时不会考虑增加此特性。

就是上传的时候，现在不是同步上传的吗，一个上传完成后才能上传下一个文件

**Comment by RockJohnson503** [comment]
> 您说的 同步/异步 上传具体指的是？
> 文件hash计算开销较大，产生的回报比较低，暂时不会考虑增加此特性。

异步的话就是，多个文件一起上传，就像并行上传一样

**Comment by HFO4** [comment]
并行上传需要修改大量代码逻辑，工作量较大，短期内可能不会实现

**Comment by RockJohnson503** [comment]
> 并行上传需要修改大量代码逻辑，工作量较大，短期内可能不会实现

只需要改前端呀，我弄的那个就直接用的bootstrap的fileinput,然后后端就是简单的openresty+lua存储文件

**Comment by RockJohnson503** [comment]
> 并行上传需要修改大量代码逻辑，工作量较大，短期内可能不会实现

http://www.bootstrapmb.com/item/1165/preview 我前端用的就是这个模板，你可以看看

**Comment by L1Yuu** [comment]
可以打开多个页面，同时上传。曲线救国 hahaha
