### ISSUE TITLE
Search function not functional

### ISSUE THREAD

**Issue by lujiaxing** [cloudreve/Cloudreve#288]
**What is the problem?**

- Choose an existing file
- Copy file name to "Search box" and execute query.
- Got nothing.

**what are the expected results?**
List files with search keywords in their file name

**Snapshots**
![image](https://user-images.githubusercontent.com/7188738/78638668-3de9e400-78df-11ea-9acb-4277ae89e101.png)

![image](https://user-images.githubusercontent.com/7188738/78638670-40e4d480-78df-11ea-9cd1-2161b82649ea.png)

![image](https://user-images.githubusercontent.com/7188738/78638679-43dfc500-78df-11ea-84bf-84fad7e8c0a6.png)

**Comment by HFO4** [comment]
尝试重复了操作，但是无法复现

**Comment by lujiaxing** [comment]
> 尝试重复了操作，但是无法复现

具体尝试了一下. 发现如果文件名中含有字母的情况下, 搜索关键字中具有大写字母则搜索不到内容. 哪怕文件名确实是大写字母. 转为全按小写字母则可以搜索到.
img_20200130_195136.jpg √
IMG_20200130_195136.jpg ×

注:
版本: V3.0.0 RC-1
数据库 MySQL 5.7.27. 字符集: UTF8MB4
服务器: Armbian Linux 5.3.0-aml-g12 (ARMv8)
浏览器: Chrome 81.0.4044.92



![image](https://user-images.githubusercontent.com/7188738/78963355-cbb90f80-7b29-11ea-957d-d02fda8996d6.png)
