### ISSUE TITLE
[建议]重置密码小程序

### ISSUE THREAD

**Issue by CX4A3** [cloudreve/Cloudreve#291]
今天突然忘记了我自己cloudreve的管理员密码，在无奈之下开始阅读程序代码，然后大致了解了Cloudreve的用户密码加密原力，最终用sqlite可视化工具重置了密码。
这个过程对于一般用户而言个人认为比较繁琐，能不能出一个工具来实现上述功能呢？

我个人的操作流程如下：
在查阅：https://github.com/cloudreve/Cloudreve/blob/master/models/user.go以后，得知Cloudreve存储在数据库内的密码格式为 : salt:password ， 中间由冒号分割，将明文密码采用sha1($pass.$salt)的方式加密，个人最后在cmd5重新加密了一组密码(建议另外设一组密码)，根据原来的格式填回去。然后便可正常登录。
希望开发组或者某个第三方能够编写小工具来完成这一操作。

**Comment by sky5454** [comment]
建议写成 JavaScript 代码，然后直接在浏览器控制台 (F12) 运行即可

**Comment by lujiaxing** [comment]
> 建议写成 JavaScript 代码，然后直接在浏览器控制台 (F12) 运行即可

嗯 然后我访问你的网站通过这个 javascript 代码重置了你的管理员密码

**Comment by HFO4** [comment]
暂时不会考虑增加，可通过重新初始化数据库找回密码

**Comment by NyaMisty** [comment]
@CX4A3，其实如果记得别人的密码似乎可以update set  (password = (select XXXX from )) 来用别的账号的密码hash来盖掉admin的密码

**Comment by kmahyyg** [comment]
个人建议至少在文档里写一下，忘记admin密码，又被封了25/没有提前配置好邮件发件，真的非常烦。
