### ISSUE TITLE
起用onedrive储存策略缩略图无法显示

### ISSUE THREAD

**Issue by ajian2002** [cloudreve/Cloudreve#294]
起用onedrive后图片无法缩略图查看只能一张张打开看，建议对于一些文件可以自主选择储存位置

**Comment by HFO4** [comment]
OneDrive策略的缩略图是由OneDrive生成提供的，可能有时候服务器会抽风。

**Comment by mashirozx** [comment]
> 受疫情影响目前许多国家的用户只能在家办公，这让微软提供的云服务使用率暴增并且也影响这些服务的稳定性。
>
> 为此微软此前已经调整多项产品的服务策略降低对服务器的压力，现在微软开始向OneDrive 用户进行服务限制。
>
> 这项服务限制主要针对的是OneDrive 按需下载用户的，按需下载意味着文件存储在云端而不是用户本地磁盘上。
>
> 当用户打开某些包含许多图片的文件夹时，OneDrive 需要连接服务器请求缩略图，这可能会给服务器造成压力。

似乎确实是OneDrive暂停了缩略图功能呢...
