### ISSUE TITLE
在线看不了 mp4 的视频

### ISSUE THREAD

**Issue by xiechuanyu** [cloudreve/Cloudreve#298]
上传了 mp4 的视频，在线看的话，有声音没画面
![image](https://user-images.githubusercontent.com/12131262/79301613-9ee76c80-7f1c-11ea-948e-e02a4f4754fe.png)

**Comment by lujiaxing** [comment]
视频编码格式是什么?
chrome 只支持 H.264 / MP3 / OGG 格式播放. 虽然都是 .MP4 文件但是编码方式千差万别. 需要知道具体的编码方式才能确定到底什么问题.

**Comment by xiechuanyu** [comment]
> 视频编码格式是什么?
> chrome 只支持 H.264 / MP3 / OGG 格式播放. 虽然都是 .MP4 文件但是编码方式千差万别. 需要知道具体的编码方式才能确定到底什么问题.

不知道，怎么看

**Comment by xiechuanyu** [comment]
![image](https://user-images.githubusercontent.com/12131262/79307681-e0324900-7f29-11ea-92e2-9aee99bd5779.png)
![image](https://user-images.githubusercontent.com/12131262/79307728-f17b5580-7f29-11ea-9f37-2f9c0f2a5e0a.png)
怎么没解决就关闭了呢，可以继续讨论吗？

**Comment by HFO4** [comment]
> ![image](https://user-images.githubusercontent.com/12131262/79307681-e0324900-7f29-11ea-92e2-9aee99bd5779.png)
> ![image](https://user-images.githubusercontent.com/12131262/79307728-f17b5580-7f29-11ea-9f37-2f9c0f2a5e0a.png)
> 怎么没解决就关闭了呢，可以继续讨论吗？

视频解码最终还是浏览器负责的，我们也没法通过程序层面解决此问题。

**Comment by lujiaxing** [comment]
> ![image](https://user-images.githubusercontent.com/12131262/79307681-e0324900-7f29-11ea-92e2-9aee99bd5779.png)
> ![image](https://user-images.githubusercontent.com/12131262/79307728-f17b5580-7f29-11ea-9f37-2f9c0f2a5e0a.png)
> 怎么没解决就关闭了呢，可以继续讨论吗？

可以讨论.
这个确实是播不了. 建议转换为 H.264

**Comment by xiechuanyu** [comment]
> > ![image](https://user-images.githubusercontent.com/12131262/79307681-e0324900-7f29-11ea-92e2-9aee99bd5779.png)
> > ![image](https://user-images.githubusercontent.com/12131262/79307728-f17b5580-7f29-11ea-9f37-2f9c0f2a5e0a.png)
> > 怎么没解决就关闭了呢，可以继续讨论吗？
> 
> 可以讨论.
> 这个确实是播不了. 建议转换为 H.264

好的。谢谢你
