### ISSUE TITLE
无法插入目录记录

### ISSUE THREAD

**Issue by zzd** [cloudreve/Cloudreve#302]
在webdav上传的过程中，日志会出现`无法插入目录记录, UNIQUE constraint failed: folders.name, folders.parent_id`的警告，并且无法上传成功。注：我上传的文件没有任何问题，没有重复上传

**Comment by HFO4** [comment]
使用的是哪款WebDAV客户端？

**Comment by 616620131** [comment]
使用的是笔记软件notability的自动备份，文件夹能正常创建，但是文件不能同步上去。
