### ISSUE TITLE
如何将现有磁盘文件批量导入Cloudreve中？

### ISSUE THREAD

**Issue by lifei6671** [cloudreve/Cloudreve#304]
磁盘上已经有了大量文件，请问有没有办法将这些文件批量导入到Cloudreve中呢？

**Comment by cshenxi** [comment]
我也想知道这个问题，vps上部署了Cloudreve，同时在该vps上的一个目录内也有200G的文件想要上传到Cloudreve中，现在我知道的做法就只是先通过其他手段把这200G下载到我自己本地。。再通过网页的Cloudreve上传上去。。这样太不科学了。是不是有什么方法，可以直接扫描vps的本地目录？然后把目录内的文件都自动导入？文件应该也不需要重新写一遍。。而是直接读取那个目录就可以了。。

**Comment by HFO4** [comment]
@cshenxi 会在下个版本中加入导入功能

**Comment by cshenxi** [comment]
> @cshenxi 会在下个版本中加入导入功能

感谢回复，请问这一feature，是直接读取vps本机指定的目录的文件吧？例如在/root/video下有200G的视频，导入后是否会重新转码并额外占200g空间之类的？

**Comment by HFO4** [comment]
@cshenxi 不会占用，导入的记录直接指向现有文件

**Comment by zhangguanzhang** [comment]
这个违背了项目吧，像其他这种把云盘当作本地盘的工具和产品网上有，项目是web上提供下载和上传。感觉没必要加到项目里

**Comment by lujiaxing** [comment]
> 磁盘上已经有了大量文件，请问有没有办法将这些文件批量导入到Cloudreve中呢？

FTP传. 传完了可以用程序同步数据库记录.
https://github.com/lujiaxing/cloudreve-file-synchronizer

**Comment by HFO4** [comment]
已在 https://github.com/cloudreve/Cloudreve/commit/e8a6df9a86ffc09df7385501db7c76ac8fb05b3c 后实现

**Comment by nghuyong** [comment]
有使用文档/说明了吗

**Comment by henrywu19359** [comment]
> 有使用文档/说明了吗

更新到3.1及以上版本后前往 控制面板--文件 就可以看到导入按钮了。

**Comment by nghuyong** [comment]
是的，看到了，谢谢

**Comment by mom988** [comment]
感觉可以用 rclone 同步 webdav，不过我在实际操作中感觉有点慢？是不是我这个方法不太好还是别的原因
