### ISSUE TITLE
建议添加分片以优化cdn体验

### ISSUE THREAD

**Issue by James537** [cloudreve/Cloudreve#307]
你好，
        这是个非常完美的作品，但作为一个希望将其应用于生产环境的我来说还有一点改进空间。
        希望添加一个上传分片功能（选项），如Nextcloud那样，这样对于cdn的体验就好多了。比如，Cloudflare通常只支持上传100M的文件，但进行分片就可以解决这个问题，感谢。
        祝你生活愉快!
                                                                                                                                  Best wishes
                                                                                                                                  James zhou
                                                                                                                                   2020/4/19

**Comment by YumeGod** [comment]
建议添加

**Comment by CoiaPrant** [comment]
同

**Comment by HFO4** [comment]
已经支持分片上传。

**Comment by YumeGod** [comment]
> 已经支持分片上传。

是下个版本更新添加吗

**Comment by smartcatboy** [comment]
@HFO4 请问我在存储策略给本地存储设置了cdn以后，上传显示还是使用源站进行上传，需要怎么设置才能走cdn上传吗？
