### ISSUE TITLE
建议重新设计一下UI，太难看了！

### ISSUE THREAD

**Issue by readthecodes** [cloudreve/Cloudreve#308]
建议重新设计一下UI，太难看了！严重影响使用体验。

**Comment by HFO4** [comment]
如果觉得难看，请给出具体的建议，另外 pull requests welcomed.

**Comment by HenMie** [comment]
现有UI个人认为还可以的呀，而且UI修改相对来说比较容易，不满意的话可以自己个性化一下的

**Comment by topjohncian** [comment]
在¿建议宁自己写一个呢

**Comment by hmsjy2017** [comment]
反正我是没见过UI比这个好看的

**Comment by Michael-LY** [comment]
主要是md有一整套react的框架，直接用，我觉得挺好的啊

**Comment by HFO4** [comment]
如果没有具体建议的话就先close了
