### ISSUE TITLE
是否支持映射到本地的网络磁盘？

### ISSUE THREAD

**Issue by kuzzh** [cloudreve/Cloudreve#309]
我在本机上映射了一个内网中的网络磁盘，并将存储路径设为它。我检查了文件夹都创建成功了，在上传文件的时候却提示失败，错误信息为：

`write Z:\NAS\uploads\1\1_kmbSh8rX_66ec3883-170f-4a6c-99bf-d331140c1a16.jpg: The parameter is incorrect.`

我检查了下该路径发现文件创建成功了，只是大小为 0，不知道是怎么回事呢？

**Comment by HFO4** [comment]
@kuzzh 这个错误应该是 Windows 给出的，我也没有类似的使用经验，所以不太清楚原因

**Comment by kuzzh** [comment]
@HFO4 我自己写了个程序，证实映射的网络磁盘读写都是没问题了，不清楚这里怎么就要报错。

我把 `Debug` 开关打开了，但没有任何提示信息，有没有什么更详细的错误日志记录呢？

**Comment by HFO4** [comment]
> @HFO4 我自己写了个程序，证实映射的网络磁盘读写都是没问题了，不清楚这里怎么就要报错。
> 
> 我把 `Debug` 开关打开了，但没有任何提示信息，有没有什么更详细的错误日志记录呢？

暂时能得到的错误信息只有这些

**Comment by wsndshx** [comment]
网络映射的储存可能会存在诡异的权限问题，会不会是因为cloudreve上传的时候试图设置这个文件的所有权？
