### ISSUE TITLE
建议：加一个广告位

### ISSUE THREAD

**Issue by 1362032536** [cloudreve/Cloudreve#312]
在下载文件的页面加一个或多个广告位

**Comment by HFO4** [comment]
与 #301 重复。
灵活性较大且不是广泛需求，可自行修改前端代码加入。

**Comment by ggz0638** [comment]
虽不能直接后台添加，可以自己修改前端页面，变相的增加广告或自定义内容

教程：https://fuwa365.com/showinfo-6-8-0.html
