### ISSUE TITLE
请问什么时候可以支持华为对象存储服务OBS？

### ISSUE THREAD

**Issue by tianhongce** [cloudreve/Cloudreve#313]
伟大的作者：
您好，
    因为我这边自己开发的程序使用的是华为对象存储，请问cloudreve是否有支持华为对象存储的计划？

致以崇高的敬意！

**Comment by topjohncian** [comment]
并没有多少人使用（（

**Comment by GoFly-wenxue** [comment]
并没有多少人使用（（（

**Comment by ssst0n3** [comment]
求支持

**Comment by longhuan1999** [comment]
需要+1

**Comment by hatsuyuki280** [comment]
@longhuan1999 据说同一个问题已经被问了无数遍了

答案都是同一个…

国内云没提供官方API，所以今后cloudreve都不会支持。

对于抓包自己折腾接口之类的暴力做法，考虑到国内那几个云盘的官方只要随便改一下，这种接口就作废了，谈不上稳定，所以cloudreve也不会采用这种方案。

你可以自己改或者试试第三方魔改版本，不过因为使用的不是官方接口，随时做好访问不了文件的准备。

**Comment by ssst0n3** [comment]
@hatsuyuki280 不应该都是S3的接口吗
