### ISSUE TITLE
cloudreve和盘内文件同步

### ISSUE THREAD

**Issue by Nicotinamide** [cloudreve/Cloudreve#315]
希望cloudreve可以扫描OneDrive，有时候我在OneDrive里吧文件删除后，cloudreve里显示还有文件而且没法对cloudreve里的文件进行删除。我希望可以让cloudreve同步OneDrive里文件，避免出现bug。

**Comment by HFO4** [comment]
有计划实现单向文件导入：存储端 -> Cloudreve (#304)，暂时没法实现双向同步，不过下个版本会增加强制删除无效文件的特性。

**Comment by yubanmeiqin9048** [comment]
> 希望cloudreve可以扫描OneDrive，有时候我在OneDrive里吧文件删除后，cloudreve里显示还有文件而且没法对cloudreve里的文件进行删除。我希望可以让cloudreve同步OneDrive里文件，避免出现bug。

同感，我觉得这个挺重要的

**Comment by xfap** [comment]
请问双向同步现在有办法实现了吗？可以做到类似坚果云那样的本地同步盘么

**Comment by fuxiaoiii** [comment]
> 请问双向同步现在有办法实现了吗？可以做到类似坚果云那样的本地同步盘么

老哥，请问现在实现本地同步盘的了吗
