### ISSUE TITLE
离线下载的问题

### ISSUE THREAD

**Issue by aumk** [cloudreve/Cloudreve#323]
版本3.0.0，存储策略OneDrive
离线下载之后上传会把所有文件放在指定下载目录这一个层级上，不同任务的文件，子目录里面的图片和音乐全都会在一个层级混在一起。非常难以管理。
离线下载之后上传速度比较慢，只有几M/s，转存比下载还慢。所以可不可以考虑加一个进度条？（或者改善一下速度）
离线下载完成后任务从进行中消失，但不会自动显示在完成中，需要手动刷新页面。

emmm最后还有一个问题，大佬你那个考虑了好几年的Google Drive还加不加啊（

**Comment by HFO4** [comment]
> 离线下载之后上传会把所有文件放在指定下载目录这一个层级上，不同任务的文件，子目录里面的图片和音乐全都会在一个层级混在一起。非常难以管理。

默认情况下不同任务会放在不同目录下的。

> 离线下载之后上传速度比较慢，只有几M/s，转存比下载还慢。所以可不可以考虑加一个进度条？（或者改善一下速度）

离线下载、中转的速度都要取决于你机器的带宽、网络环境。BT下载任务可通过手动执行Tracker列表加速，具体参考文档。

> 离线下载完成后任务从进行中消失，但不会自动显示在完成中，需要手动刷新页面。

自动刷新间隔可在后台调整。

> emmm最后还有一个问题，大佬你那个考虑了好几年的Google Drive还加不加啊（
因各种因素，暂时不考虑加入。

**Comment by aumk** [comment]
> > 离线下载之后上传会把所有文件放在指定下载目录这一个层级上，不同任务的文件，子目录里面的图片和音乐全都会在一个层级混在一起。非常难以管理。
> 
> 默认情况下不同任务会放在不同目录下的。
> 
默认情况下确实把不同任务的不同层级的所有文件都放在一个目录了。存储策略是OneDrive。
> > 离线下载之后上传速度比较慢，只有几M/s，转存比下载还慢。所以可不可以考虑加一个进度条？（或者改善一下速度）
> 
> 离线下载、中转的速度都要取决于你机器的带宽、网络环境。BT下载任务可通过手动执行Tracker列表加速，具体参考文档。
> 
机器是千兆对等带宽，BT下载任务没有问题（30M+），但事实上OneDrive的上传速度确实很慢。
> > 离线下载完成后任务从进行中消失，但不会自动显示在完成中，需要手动刷新页面。
> 
> 自动刷新间隔可在后台调整。
> 
哦哦，多谢解答，我尝试一下。
> > emmm最后还有一个问题，大佬你那个考虑了好几年的Google Drive还加不加啊（
> > 因各种因素，暂时不考虑加入。
嗯，多谢解答。
