### ISSUE TITLE
多选操作中shift无法使用

### ISSUE THREAD

**Issue by aumk** [cloudreve/Cloudreve#324]
如题，文件操作中无法使用shift批量多选。ctrl+a全选和ctrl多选可以正常使用
版本3.0

**Comment by SHITianhao** [comment]
苹果下应该是Command+A 但是还是Ctrl

**Comment by aumk** [comment]
> 苹果下应该是Command+A 但是还是Ctrl

我是Windows，Ctrl和Ctrl+A都可以用，但shift不能用

**Comment by SHITianhao** [comment]
@HFO4 能否考虑一下这几个前端需求？
1. Shift 连续选择
2. 苹果下改为 Command+A 全选
3. 苹果下Command+单击多选
4. 鼠标拖拽多选

如果接受我可以提供PR

**Comment by HFO4** [comment]
@SHITianhao 都可以加，感谢PR！

**Comment by zjsth92** [comment]
Shift PR: https://github.com/cloudreve/frontend/pull/16
