### ISSUE TITLE
前端自动过滤mac 的 .ds_store 文件

### ISSUE THREAD

**Issue by SHITianhao** [cloudreve/Cloudreve#325]
.ds_store 是Mac下文件夹布局文件一般没有用。是否可以上传目录时前端自动过滤这个文件？

**Comment by HFO4** [comment]
直接过滤特定文件感觉不太合适，也有可能在webdav映射或其他情境下会用到此文件，所以还是不过滤了

**Comment by SHITianhao** [comment]
我的意思只是在JS Frontend 进行目录上传时能否考虑过滤？这个并不影响webdav。希望再考虑下。我可以提供PR

**Comment by HFO4** [comment]
好的，欢迎pr
