### ISSUE TITLE
离线下载的问题（再确认）

### ISSUE THREAD

**Issue by jianfei96** [cloudreve/Cloudreve#326]
离线下载之后上传会把所有文件放在指定下载目录这一个层级上，而不会新建目录，不同任务的文件，子目录里面的图片和音乐全都会在一个层级混在一起。非常难以管理。
测试了本地存储和OneDrive，结果一致。
软件版本：3.0
OS：Arch
aria2版本：1.35
截图：
![Snipaste_2020-04-25_23-20-00](https://user-images.githubusercontent.com/18232033/80282238-55342880-874b-11ea-857f-1b9b6175b7b2.png)

**Comment by HFO4** [comment]
@aumk 噢噢，你指的是用户端的目录结构，这个确实，目前是直接铺开的

**Comment by aumk** [comment]
> @aumk 噢噢，你指的是用户端的目录结构，这个确实，目前是直接铺开的

而且好像连子目录里面的文件也会平铺到一块...
不同任务的视频歌曲特典扫图字体全都混在一起了emmm
这样根本分不清的

**Comment by KyonCN** [comment]
是的  所有文件都会丢失目录结构。。 目前来说还是不适合作为直接使用的BT仓库盘 偶尔离线点美剧 新番的等目录结构简单的种子还行
