### ISSUE TITLE
请问可以增加对.mkv视频格式的在线预览支持吗，谢谢！

### ISSUE THREAD

**Issue by declan-haojin** [cloudreve/Cloudreve#328]
如题

**Comment by aumk** [comment]
+1
很多mkv是h264编码的，浏览器其实可以直接播放

**Comment by topjohncian** [comment]
能提供解决方案吗 and pr welcome

**Comment by aumk** [comment]
> 能提供解决方案吗 and pr welcome

应该和mp4一样，浏览器原生支持？现在mkv是直接下载。或者用一些别的组件，例如dplayer？

**Comment by HFO4** [comment]
已在 https://github.com/cloudreve/frontend/commit/90c20a9c136af18b7dd34df1cdbdfb1ec6aa6b23 内实现
