### ISSUE TITLE
建议优化文件上传策略，增加可配置项。

### ISSUE THREAD

**Issue by yoyo2977** [cloudreve/Cloudreve#331]
在使用过程中，发现上传速度一直不是很理想。
文件上传的体验应该是一个web网盘十分重要的地方。
在本机和OneDrive的存储策略中，上传速度普遍达不到通过存储直接上传的水平，而且也不是很稳定。
观察发现上传时在每10m就会暂停一瞬，再开始下一个10m下载。猜测可能是分块进行上传导致请求频繁，影响上传速度。

正如下载速度可以通过本地多线程下载工具提升，上传是否也能支持并配置多线程？
**建议可增加多线程上传配置项，和分块上传分块大小的配置项，以适应不同存储的情况，提升上传速度和稳定性。**

**Comment by HFO4** [comment]
Web端实现多线程上传比较麻烦，不过下个版本中会调大Web端OneDrive上传分片大小
