### ISSUE TITLE
Cloudreve 在docker中一直无法运行

### ISSUE THREAD

**Issue by jy3344511** [cloudreve/Cloudreve#332]
执行以下命令后：
docker pull xavierniu/cloudreve:arm64v8

docker run -d \
  --name cloudreve \
  -e PUID=0 \ 
  -e PGID=0 \ 
  -e TZ="Asia/Shanghai" \ 
  -p 5212:5212 \ 
  --restart=unless-stopped \
  -v /mnt/sda1:/cloudreve/uploads \
  -v /opt/110:/cloudreve/conf.ini \
  -v /opt/120:/cloudreve/cloudreve.db \
  xavierniu/cloudreve:arm64v8

始终提示：docker run -d \
>   --name cloudreve \
>   -e PUID=0 \ 
avierniu/cloudreve:arm64v8
docker: invalid reference format.
See 'docker run --help'.
root@OpenWrt:~#   -e PGID=0 \ 
-ash: -e: not found
root@OpenWrt:~#   -e TZ="Asia/Shanghai" \ 
-ash: -e: not found
root@OpenWrt:~#   -p 5212:5212 \ 
-ash: -p: not found
root@OpenWrt:~#   --restart=unless-stopped \
>   -v /mnt/sda1:/cloudreve/uploads \
>   -v /opt/110:/cloudreve/conf.ini \
>   -v /opt/120:/cloudreve/cloudreve.db \
>   xavierniu/cloudreve:arm64v8
-ash: --restart=unless-stopped: not found

搞不明白是哪里的问题，有知道的说下，谢谢，另外在docker中跑过nextcloud，用起来不顺手，所以想试下Cloudreve，但一直无法运行，在虚拟机中跑openwrt x64上的docker，也无法运行Cloudreve，不知道是哪里的问题。

**Comment by HFO4** [comment]
Docker相关问题可以咨询镜像作者：https://github.com/xavier-niu/cloudreve-docker
