### ISSUE TITLE
bug:用户多次保存同一分享导致炸库

### ISSUE THREAD

**Issue by cha0sCat** [cloudreve/Cloudreve#336]
我分享了一个包含18w文件的文件夹。
有一个用户把分享保存到了各个文件夹
然后后端居然真的响应了，往我的数据库插入了100w条数据。
我的服务器光响应这些insert就用了一个小时。
最后这个用户整整存了21T的文件。

这个漏洞会被有心人用来炸库

连续保存100次，性能不好的数据库可能就炸掉了

***
我临时登录那个用户的账号上去看了, 是同一个分享转存到了各个不同的文件夹, 
而go没有对用户容量进行判断, 导致被成功转存.

***
我又去看了代码，然后发现，转存任务和计算大小是同时进行的，而且是在后台，所以没法在转存之前知道空间是否足够。

归根结底问题来源于文件夹没有内容大小的字段。
所以只要给文件夹增加一个size的字段，就能在用户转存之前判断容量是否足够，还能顺带右键查看文件夹内容大小
***
如果上述方法不好实现，也可以在转存之前加一个中间件来计算文件夹大小，不够的话就不用执行最终的转存任务了。
***
上述方法还是不能完全避免炸库问题
比如一个人创建了一个巨型目录树，每个目录里都有65535个子文件夹，文件夹总深度也是65535。
那就会出现一个巨型文件夹结构；而且因为文件夹里没有文件，整个炸弹还不占实际空间。
把这个炸弹分享出来，单独注册一个账号，保存这个文件夹数次，系统必定崩溃
<a href="https://ibb.co/GCnPG36"><img src="https://i.ibb.co/gtmgQF2/image.png" alt="image" border="0"></a>

**Comment by HFO4** [comment]
目前有个可行补救措施是：用户取消等待请求的同时，后台取消处理转存

**Comment by 742481030** [comment]
我也被数据库炸了,自己复制自己文件一样瞬间数据库几十万跳数据

**Comment by Creling** [comment]
这就是为什么支持类似功能的百度网盘在转存文件时限定了子目录个数及子文件个数。
一个比较简单的解决方案是，cloudreve的文件目录直接映射到物理磁盘，每个用户拥有一个独立的文件夹，不再通过数据库记录“模拟”目录分级，直接读取物理路径作为cloudreve的文件路径。

**Comment by 742481030** [comment]
> 这就是为什么支持类似功能的百度网盘在转存文件时限定了子目录个数及子文件个数。
> 一个比较简单的解决方案是，cloudreve的文件目录直接映射到物理磁盘，每个用户拥有一个独立的文件夹，不再通过数据库记录“模拟”目录分级，直接读取物理路径作为cloudreve的文件路径。

你知道百度云什么的是怎么映射的么

**Comment by 742481030** [comment]
> 这就是为什么支持类似功能的百度网盘在转存文件时限定了子目录个数及子文件个数。
> 一个比较简单的解决方案是，cloudreve的文件目录直接映射到物理磁盘，每个用户拥有一个独立的文件夹，不再通过数据库记录“模拟”目录分级，直接读取物理路径作为cloudreve的文件路径。

我的是他们自己文件管理里自己复制的

**Comment by HFO4** [comment]
> 这就是为什么支持类似功能的百度网盘在转存文件时限定了子目录个数及子文件个数。
> 一个比较简单的解决方案是，cloudreve的文件目录直接映射到物理磁盘，每个用户拥有一个独立的文件夹，不再通过数据库记录“模拟”目录分级，直接读取物理路径作为cloudreve的文件路径。

直接映射物理磁盘对于多存储策略文件统一管理不友好。

**Comment by cuixiping** [comment]
问题解决了没有? 没解决就 close 有什么意义?
