### ISSUE TITLE
【建议】增加中转直链功能

### ISSUE THREAD

**Issue by HenMie** [cloudreve/Cloudreve#337]
目前一些储存策略无法获取直链，一些是直接获取永久直链，感觉都不太好。
可以加入类似oneindex的中转直链功能，动态获取直链。

**Comment by topjohncian** [comment]
我正在写了 适用范围：aria/wget curl等

**Comment by HenMie** [comment]
> 我正在写了 适用范围：aria/wget curl等

好的，期待一下！（秒回，感动）

**Comment by topjohncian** [comment]
> > 我正在写了 适用范围：aria/wget curl等
> 
> 好的，期待一下！（秒回，感动）

TG群和GmailBot联动（（

**Comment by erow** [comment]
2022了。这个功能有实现么？期待！
