### ISSUE TITLE
能否实现存储设备中已有文件的展示?

### ISSUE THREAD

**Issue by weiyouwozuiku** [cloudreve/Cloudreve#338]
当oss或者任意一种存储设备中已经有文件时,可否实现现有文件的读取功能.现在似乎只能先从cloudreve中上传,然后才能显示出来,即使使用webdav上传的文件也没有在网页端显示,但是在所属的webdav中有显示.

**Comment by HFO4** [comment]
后续可以单向导入已有文件(#304)
