### ISSUE TITLE
加快版本迭代周期

### ISSUE THREAD

**Issue by SHITianhao** [cloudreve/Cloudreve#339]
是否可以考虑添加GitHub workflow加快小版本发布？比如3.0.1这种快速发布一些小功能和修复bug

**Comment by HFO4** [comment]
目前可以在这里(https://github.com/cloudreve/Cloudreve/actions)下载每次commit后编译的开发版。因为目前已经commit了一些未完成的特性，所以不太方便释出小版本。3.1后会尽量优先释出小版本再考虑新增特性。
