### ISSUE TITLE
【建议】1.获取外链时增加复制的按钮/2.外链增加短连接版

### ISSUE THREAD

**Issue by gurq** [cloudreve/Cloudreve#340]
基于3.0.0

1.现在的文本框不支持ctrl+a全选，建议增加按钮点击复制到剪切板

2.用onedrive作为存储时，外链太长了，可不可以支持直接转成t.cn或者其他的短连接，并且原外链仍然保留，界面上既可以选择复制原链接，也可以选择复制短连接

t.cn的接口如下：
http://service.weibo.com/share/share.php?url=链接&title=1

希望大佬增加新功能，万分感谢

**Comment by HFO4** [comment]
> 1.现在的文本框不支持ctrl+a全选，建议增加按钮点击复制到剪切板

已在 https://github.com/cloudreve/frontend/pull/5 中解决，将会在3.1版本中可用。

> 可不可以支持直接转成t.cn或者其他的短连接

感觉不是太紧迫的需求，暂时不考虑加入。
