### ISSUE TITLE
对于项目优化建议

### ISSUE THREAD

**Issue by qd201211** [cloudreve/Cloudreve#341]
1、是否可以在右键添加一个刷新按钮。每次离线或者上传都要在文件目录的地方找刷新，感觉比较麻烦
2、是否可以多加一个显示模式，感觉文件夹图标太小，文件图标太大不是很协调
3、希望可以给支持在线播放的视频，右键添加一个预览选项。。不然有时候自己也不知道上传的视频是否可以在线播放，还要双击尝试才知道。
4、txt预览是否可以添加一个关闭文档按钮来关闭当前正在查看的文档
5、希望可以在文件 和文件夹右键添加一个详细信息选项，用来查看文件信息，比如文件大小等

感谢作者~

临时加一跳不算是大问题，就是左下角的存储容量显示，貌似超过两位数就会显示不全，比如200GB就只显示20。。希望可以优化一下~~

**Comment by HFO4** [comment]
@qd201211 第二点的话已经有了啊

**Comment by qd201211** [comment]
> @ qd201211第二点的话已经有了啊

我的意思是大图标的显示情况下，文件夹图标也是大的。现在大图标下只有文件图标是变大的

**Comment by HFO4** [comment]
> 1、是否可以在右键添加一个刷新按钮‘

已在 https://github.com/cloudreve/frontend/commit/538bd95a7ba1712bf8b079375d1aa419d803273a 后实现。

> 2、是否可以多加一个显示模式，感觉文件夹图标太小，文件图标太大不是很协调

暂时不考虑变更‘

> 3. 希望可以给支持在线播放的视频，右键添加一个预览选项。。不然有时候自己也不知道上传的视频是否可以在线播放，还要双击尝试才知道。

右键后出现 `打开` 选项的都是可以预览的。

> txt预览是否可以添加一个关闭文档按钮来关闭当前正在查看的文档

目前是单页应用，可以通过浏览器后退关闭。

> 5、希望可以在文件 和文件夹右键添加一个详细信息选项，用来查看文件信息，比如文件大小等

目前不会增加，原因是：

* 数据库不会记录目录大小，计算耗费时间较大；
* 目前文件的可展示信息较少。
