### ISSUE TITLE
文件被删除 bug

### ISSUE THREAD

**Issue by wuyougan** [cloudreve/Cloudreve#342]
安装了最新的 3.0 版本，复现过程如下：

1. 修改存储策略参数，关闭**自动重命名**功能
2. 任意一传一个文件
3. 再次上传同一文件到相同目录
4. 此时提示有同名文件存在，BUG出现
5. 刷新页面，发现之前上传的文件无法打开，同时也无法删除
6. 在update目录中查看，文件实际已经不存在

**Comment by HFO4** [comment]
文件命名规则是直接使用了原始文件名吗？

**Comment by wuyougan** [comment]
是的，使用原始文件名

**Comment by ceecx** [comment]
这和我之前 Issues 的问题相同, 发生在 OneDrive 策略中.

**Comment by ceecx** [comment]
更新：
和楼主问题一样，不同的是原来还会提示同名文件存在，现在前端直接不报错误，永久显示排队中，但在控制台中可以看到提示。
![image](https://user-images.githubusercontent.com/18570103/82660442-f506a880-9c5c-11ea-9d45-5a8e2df252a6.png)
![image](https://user-images.githubusercontent.com/18570103/82660462-fe901080-9c5c-11ea-9aae-3152a7065649.png)

另外还有个问题：
挂载 Google Drive 上传几兆的小文件成功上传了，选个几百兆的文件就一直卡在那，测试自己复制大文件进去也成功上传。
![image](https://user-images.githubusercontent.com/18570103/82660735-7cecb280-9c5d-11ea-89d0-44bef04d703e.png)

发现作者好喜欢用数据库来做判断，明明可以直接读取文件目录校验，文件前端删除不了强迫症超难受。如果以上问题解决了希望能同步一下捐赠版。

**Comment by GoFly-wenxue** [comment]
> 更新：
> 和楼主问题一样，不同的是原来还会提示同名文件存在，现在前端直接不报错误，永久显示排队中，但在控制台中可以看到提示。
> ![image](https://user-images.githubusercontent.com/18570103/82660442-f506a880-9c5c-11ea-9d45-5a8e2df252a6.png)
> ![image](https://user-images.githubusercontent.com/18570103/82660462-fe901080-9c5c-11ea-9aae-3152a7065649.png)
> 
> 发现作者好喜欢用数据库来做判断，明明可以直接读取文件目录校验，文件前端删除不了强迫症超难受。如果以上问题解决了希望能同步一下捐赠版。

毕竟数据库最快啊...数据库有但是 OneDrive 没有也算是极端情况
