### ISSUE TITLE
Onedrive对接问题

### ISSUE THREAD

**Issue by cxnaive** [cloudreve/Cloudreve#343]
使用学校邮箱注册 office365
授权页面打不开
报错
AADSTS50194: Application 'fda01b3e-1cb2-4044-a320-bdb53071ab81'(cxcloud) is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant. Trace ID: 898514f6-8006-4255-8b16-0a8d65167500 Correlation ID: 2ea962b3-00e1-4499-ae0a-4e33b61a12cb Timestamp: 2020-04-30 06:34:59Z,

**Comment by 1262917464** [comment]
这题我会

受支持的帐户类型
谁能使用此应用程序或访问此 API?

选择
任何组织目录(任何 Azure AD 目录 - 多租户)中的帐户和个人 Microsoft 帐户(例如，Skype、Xbox)

**Comment by cxnaive** [comment]
特意去改了
但看样子还是学校域名不能用？
AADSTS650051: Using application 'cxcloud' is currently not supported for your organization stu.hit.edu.cn because it is in an unmanaged state. An administrator needs to claim ownership of the company by DNS validation of stu.hit.edu.cn before the application cxcloud can be provisioned. Trace ID: 698a301f-64b7-420a-98f9-a4a21af0cd00 Correlation ID: 957b8ffe-5197-4309-8ee9-6ae4aaa47e7a Timestamp: 2020-04-30 07:48:18Z,

**Comment by 1262917464** [comment]
这就是我的知识盲区了（

**Comment by Xiaohantx** [comment]
如果按楼上操作仍然不可以，可能学校管理员禁用了账户的api权限功能
