### ISSUE TITLE
关于文件上传提示同名文件或者目录

### ISSUE THREAD

**Issue by 756616071** [cloudreve/Cloudreve#345]
这个可以加一个替换吗 , 让使用者自己选择是覆盖还是不上传.

**Comment by HFO4** [comment]
因为不同存储策略对重名的处理方式不同，有的支持自定行为、有的只会覆盖。所以目前推荐将命名规则设定为避免重复的规则。

**Comment by zjsth92** [comment]
是不是应该取消前端直接上传？全部通过后端转存？
第一是更安全，第二如果后端和存储是同一供应商可以算内部流量不计费

**Comment by HFO4** [comment]
> 是不是应该取消前端直接上传？全部通过后端转存？
> 第一是更安全，第二如果后端和存储是同一供应商可以算内部流量不计费

对于第三方存储策略，中转的话对主服务器负担较大的，所以目前尽可能的都实现客户端直传了
