### ISSUE TITLE
上传组件还未加载完成

### ISSUE THREAD

**Issue by JunlinLai** [cloudreve/Cloudreve#347]
软件版本：3.0.0 released 19 days ago

问题描述：我发现在某种特定的情况下，cloudreve必定会遇到“上传组件还未加载完成”的问题。

复现步骤：
1、打开你的cloudreve主页（我的文件）
2、点击右上角的用户图标，选择“管理面板”
3、打开管理面板后，再点击右上角的用户图标，选择“个人主页”
4、打开个人主页之后，点击左上角的“我的文件”，这时候你又回到了第一步所在的页面，此时无论是通过点击右下方上传文件的加号或者通过拖拽来上传都会失败，点击右下方上传文件的加号则会显示“上传组件还未加载完成”的黄色提示

这个问题不算严重，而且必须要管理员才会遇到，只要不去打开管理面板似乎都不会遇到这个问题。但还是希望能够得到修复。谢谢！

**Comment by HuanzuoSP** [comment]
我也遇到了 刷新一下才能正常上传

**Comment by HFO4** [comment]
目前还没有可行的解决方案（#259），目前可行的方法可能是，后台跳转到前台的同时强制刷新。

**Comment by Laifang** [comment]
我用的 3.4.0-beta1  现在无法上传  一直都是未加载完成
