### ISSUE TITLE
Onedrive某些文件不能上传

### ISSUE THREAD

**Issue by 1262917464** [cloudreve/Cloudreve#350]
![image](https://user-images.githubusercontent.com/16575902/80794132-b20c6480-8bcb-11ea-861e-df9031ce522f.png)

暂时就发现这个不能传

**Comment by topjohncian** [comment]
请提供更多错误信息

**Comment by HFO4** [comment]
这个文件的大小是？

**Comment by 1262917464** [comment]
> 请提供更多错误信息

没有了

**Comment by 1262917464** [comment]
> 这个文件的大小是？

2.71M

**Comment by HFO4** [comment]
检查你服务器软件对于`post_body`的大小限制，小于4mb需要服务器中转，从报错看是请求正文太大。
