### ISSUE TITLE
怎么更新

### ISSUE THREAD

**Issue by 2276664238** [cloudreve/Cloudreve#351]
我想知道我的版本信息或者我需不需要更新

**Comment by topjohncian** [comment]
建议大脑升级 
版本信息启动时会提示 
需不需要更新打开https://github.com/cloudreve/Cloudreve/releases 
如果版本号和上面的第一条一致 说明不需要更新 
更新只需要 将cloudreve(.exe)覆盖 再次运行就可以自动更新啦 请以后不要再提这样大脑升级的issue了
