### ISSUE TITLE
Airplay播放视频会播放失败

### ISSUE THREAD

**Issue by Pigeon9092** [cloudreve/Cloudreve#352]
iPhone网页上登录以后，使用airplay在电视上播放盘里面的视频，电视上会显示播放失败。
可能是airplay推送给电视的视频没有外链的原因吗？
![批注 2020-05-02 191651](https://user-images.githubusercontent.com/59448294/80862676-8cee2380-8ca9-11ea-8c3a-269a8c7e3b81.png)

**Comment by HFO4** [comment]
不太清楚Airplay的机制以及错误原因。如果是直接由TV端拉取视频的话，那确实不行，这个URL需要登录鉴权
