### ISSUE TITLE
【建议】能否增加断点续传功能？

### ISSUE THREAD

**Issue by remychew** [cloudreve/Cloudreve#354]
国内到国际网络不好，经常会出现HTTP错误，特别是传输大文件时，一旦出现HTTP错误，上传队列窗口会显示“排队中”，前功尽弃。此时，文件就需要重新上传，并且再次上传失败的概率接近100%。
![image](https://user-images.githubusercontent.com/64717639/80897514-12b2b300-8d2c-11ea-8fa7-ed6b67d3ba38.png)

**Comment by woshoxxx** [comment]
支不支持断点续传不是要看服务器和下载器的么。。。

**Comment by HFO4** [comment]
上传的端点续传前提是实现分片上传，有关分片上传的讨论：#307
