### ISSUE TITLE
上传文件BUG

### ISSUE THREAD

**Issue by qd201211** [cloudreve/Cloudreve#356]
我不知道这个问题是否存在于免费版。我设置了nginx `client_max_body_size 409600m;
        keepalive_timeout 10800;` 但是下午我上传了一个19G的压缩包，上传完之后一直卡在处理中，且在目标文件夹下找不到这个文件。上传大概用了1个多小时，上传速度5M/s。我重装系统三次，第三次尝试的时候我在目标文件夹下找到了我所上传的文件（压缩包可以正常打开，重新打开一个网盘网页也正常显示了这个文件），但web页面依旧是卡在处理中，大概30分钟左右，我发现我的上传流量又开始跑满（此时网盘界面依旧开着，没有进行任何操作。且这个压缩文件也没有被删除）。我不知道这是怎么造成的。我主系统是Unraid，网盘程序放在Centos虚拟机上，存储目录（目标文件夹）通过nfs连接在unraid硬盘上。希望可以解决~~感谢

**Comment by HFO4** [comment]
如果可以的话，麻烦尝试以下步骤并提供信息：
1. 尝试直接通过端口访问网站上传，不经过反代，是否正常。
2. 配置文件中开启debug模式，重启 Cloudreve，重现上传错误，贴出终端打印的日志
3. 重现上传错误，浏览器端F12打开开发者工具，给出全部日志

**Comment by qd201211** [comment]
好的

> 如果可以的话，麻烦尝试以下步骤并提供信息：
> 
> 1. 尝试直接通过端口访问网站上传，不经过反代，是否正常。
> 2. 配置文件中开启debug模式，重启 Cloudreve，重现上传错误，贴出终端打印的日志
> 3. 重现上传错误，浏览器端F12打开开发者工具，给出全部日志

好的，我重新试下

**Comment by qd201211** [comment]
> 如果可以的话，麻烦尝试以下步骤并提供信息：
> 
> 1. 尝试直接通过端口访问网站上传，不经过反代，是否正常。
> 2. 配置文件中开启debug模式，重启 Cloudreve，重现上传错误，贴出终端打印的日志
> 3. 重现上传错误，浏览器端F12打开开发者工具，给出全部日志

若不使用nginx问题没有出现，那应该还是nginx设置问题。我再找nginx的问题吧~感谢。顺便我想知道上传文件的时候，它会被上传到哪里。问这个问题是因为每次我出现处理中这个问题的时候，文件都是实实在在的占用了我磁盘的空间，但是我却不知道怎么才能把它清除。

**Comment by maywine** [comment]
参考 https://developer.aliyun.com/article/486083

**Comment by intbird** [comment]
server
{
        listen 127.0.0.1:443 proxy_protocol;
        server_name $name;
        index index.html index.htm index.php default.php default.htm default.html;
        add_header Strict-Transport-Security "max-age=63072000" always;

        client_body_buffer_size 16k;
        # chmod 777 ~/cloudreve/.temps
        client_body_temp_path ~/cloudreve/.temps
        client_max_body_size 512m;

        location / {
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header Host $http_host;
            proxy_redirect off;
            proxy_pass http://127.0.0.1:5212;
        }
}
