### ISSUE TITLE
OneDrive链接已经失效

### ISSUE THREAD

**Issue by BlueSkyXN** [cloudreve/Cloudreve#359]
https://cdn.jsdelivr.net/gh/BlueSkyXN/publicpicture/2020/05/05/2a1edd.png
程序给出的链接跳转后显示这样，如果手动去Azure里面添加的话，会因为不知道重定向地址而不能成功
https://cdn.jsdelivr.net/gh/BlueSkyXN/publicpicture/2020/05/05/8f47b9.png
https://cdn.jsdelivr.net/gh/BlueSkyXN/publicpicture/2020/05/05/ae23c6.png
https://cdn.jsdelivr.net/gh/BlueSkyXN/publicpicture/2020/05/05/38719e.png
https://cdn.jsdelivr.net/gh/BlueSkyXN/publicpicture/2020/05/05/a1d469.png

**Comment by HFO4** [comment]
请使用V3版本 Cloudreve
