### ISSUE TITLE
有没有类似软模拟raid0的功能吗?

### ISSUE THREAD

**Issue by Qs315490** [cloudreve/Cloudreve#361]
我这边主机Linux,12G存储空间,目前已经有用户了,新加入的从盘对接后,直接用还是需要改什么设置?

**Comment by cha0sCat** [comment]
从系统层实现就行
做LVM卷

**Comment by Qs315490** [comment]
> 从系统层实现就行
> 做LVM卷
设备是一台安卓和一个苹果，要合成一个空间，lvm貌似是对本地硬盘的吧。

**Comment by cha0sCat** [comment]
哦..那就得手动切换存储策略了

**Comment by HFO4** [comment]
目前没有
