### ISSUE TITLE
[建议]加入谷歌云CLOUD STORAGE

### ISSUE THREAD

**Issue by teemo0803** [cloudreve/Cloudreve#362]
谷歌云白嫖300美刀，CLOUD STORAGE怎么少的了呢~

**Comment by teemo0803** [comment]
备注：这里指的是谷歌云的对象储存，不是GOOGLE DRIVE

**Comment by HFO4** [comment]
暂时无法实现客户端直传，所以目前不会加入

**Comment by teemo0803** [comment]
这个跟阿里云和腾讯云对象储存是一样的呀
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AaronLiu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月8日(星期五) 晚上7:14
收件人:&nbsp;"cloudreve/Cloudreve"<Cloudreve@noreply.github.com&gt;;
抄送:&nbsp;"Teemo"<teemo0803@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cloudreve/Cloudreve] [建议]加入谷歌云CLOUD STORAGE (#362)





 
暂时无法实现客户端直传，所以目前不会加入

**Comment by HFO4** [comment]
OSS和COS都有办法实现上传事件的回调通知，GCP的对象存储据我所知还没办法。

**Comment by teemo0803** [comment]
好的，感谢回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AaronLiu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月8日(星期五) 晚上7:17
收件人:&nbsp;"cloudreve/Cloudreve"<Cloudreve@noreply.github.com&gt;;
抄送:&nbsp;"Teemo"<teemo0803@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cloudreve/Cloudreve] [建议]加入谷歌云CLOUD STORAGE (#362)





 
OSS和COS都有办法实现上传事件的回调通知，GCP的对象存储据我所知还没办法。

**Comment by zjsth92** [comment]
GCP 应该可以直传 https://cloud.google.com/storage/docs/xml-api/post-object
文档里提到 `Uploads objects by using HTML forms.`

回调可以通过监听 `google.storage.object.finalize` 实现
https://cloud.google.com/functions/docs/calling/storage

**Comment by zjsth92** [comment]
https://cloud.google.com/blog/products/storage-data-transfer/uploading-images-directly-to-cloud-storage-by-using-signed-url

谷歌官方例子里提到可以通过Signed URL+PUT请求上传
```
1. Once App Engine receives a request from the user, App Engine generates a Signed URL that allows PUT requests to be executed only for a specific Cloud Storage bucket and object for authenticated users, using application domain logic.
```
例子是App Engine 但是估计是通用的逻辑

**Comment by HFO4** [comment]
好像确实可以。不过目前增加存储策略可能要放到很后面了，前面排队的还有 S3、Azure Blob Storage

**Comment by zjsth92** [comment]
其他的对象存储是不是都有这个signed URL 的逻辑？如果是都有可以统一逻辑，然后做成类似插件的模式。如果部分没有是不是可以后台自己实现？之后添加存储就更简单了，而且可以方便其他人提交PR支持一些比较偏门的服务

**Comment by teemo0803** [comment]
太棒了，感谢


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"AaronLiu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月9日(星期六) 下午3:14
收件人:&nbsp;"cloudreve/Cloudreve"<Cloudreve@noreply.github.com&gt;;
抄送:&nbsp;"Teemo"<teemo0803@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cloudreve/Cloudreve] [建议]加入谷歌云CLOUD STORAGE (#362)





 
好像确实可以。不过目前增加存储策略可能要放到很后面了，前面排队的还有 S3、Azure Blob Storage

**Comment by teemo0803** [comment]
应该是这样的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"TS"<notifications@github.com&gt;;
发送时间:&nbsp;2020年5月9日(星期六) 下午3:23
收件人:&nbsp;"cloudreve/Cloudreve"<Cloudreve@noreply.github.com&gt;;
抄送:&nbsp;"Teemo"<teemo0803@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [cloudreve/Cloudreve] [建议]加入谷歌云CLOUD STORAGE (#362)





 
其他的对象存储是不是都有这个signed URL 的逻辑？如果是都有可以统一逻辑，然后做成类似插件的模式。如果部分没有是不是可以后台自己实现？之后添加存储就更简单了，而且可以方便其他人提交PR支持一些比较偏门的服务

**Comment by HFO4** [comment]
> 其他的对象存储是不是都有这个signed URL 的逻辑？如果是都有可以统一逻辑，然后做成类似插件的模式。如果部分没有是不是可以后台自己实现？之后添加存储就更简单了，而且可以方便其他人提交PR支持一些比较偏门的服务

统一实现的难点是Web端直传的实现，这个不同对象存储实现差别很大，包括回调方式也不同，目前需要引入对应的uploader适配js。如果上传使用服务端中转的话，这个要简单一点，只需要实现`FileSystem.Handler`接口就行了。

**Comment by zjsth92** [comment]
前端这个我把redux结构改完后可以试一下，我觉得应该可以做成类插件的模式
