### ISSUE TITLE
是否考虑添加同步存储

### ISSUE THREAD

**Issue by qd201211** [cloudreve/Cloudreve#363]
现可以通过选择存储策略将文件存到不同的存储器里。
未来是否考虑添加一个功能，可以在上传文件到本地存储的同时将它同时上传到多个存储策略里。
这样有助于备份和数据安全。

**Comment by HenMie** [comment]
附议+1，这个功能挺实用

**Comment by zjsth92** [comment]
这个好像是Pro的功能

**Comment by qd201211** [comment]
> 这个好像是Pro的功能

注意，我说的是同步存储。不是切换存储

**Comment by HFO4** [comment]
冗余存储衍生出的问题很多，而且需要大幅重构代码，短期内可能不会考虑。
