### ISSUE TITLE
onedrive（国内）策略下 解压缩的文件夹无法删除

### ISSUE THREAD

**Issue by Xiaohantx** [cloudreve/Cloudreve#368]
![image](https://user-images.githubusercontent.com/30380582/81498192-0c0cd880-92f6-11ea-950d-43419f5060bc.png)

右键删除时会报错如图

**Comment by HFO4** [comment]
文件数量太多，请分批删除2020年5月10日 下午7:40，小晗同学 <notifications@github.com>写道：



右键删除时会报错如图
