### ISSUE TITLE
重复上传同一批文件, 有些文件会无限反复上传

### ISSUE THREAD

**Issue by lujiaxing** [cloudreve/Cloudreve#369]
过程:
选择一批文件, 上传.
刷新网页
进入同一文件夹, 选择同一批文件, 上传.

现象:
有一部分文件 (大概率是第一个) 在第二次上传时候在 "正在上传" 和 "处理中..." 之间无限循环. 或者无限 "处理中..." 且之后的一个文件没有显示上传状态.

![image](https://user-images.githubusercontent.com/7188738/81506893-0b8f3480-932c-11ea-8dec-49df2ff565c0.png)
![image](https://user-images.githubusercontent.com/7188738/81507007-c91a2780-932c-11ea-8d00-44bdc5a865db.png)

期望:
能够正常显示上传结果.

环境:
Chromium  81.0.4044.138
Ubuntu 20.04 x86_64

**Comment by 2498981627** [comment]
我也遇到过，一直显示处理中，我还以为是我卡了
