### ISSUE TITLE
[Enhancement] 优化上传文件对话框

### ISSUE THREAD

**Issue by lujiaxing** [cloudreve/Cloudreve#370]
现有的文件上传对话框有如下问题:

1. 文件上传队列不清晰. 当有大量文件批量上传的时候, 对话框内的文件列表没有跟随上传进度滚动. 造成只能看到最前面几个文件上传进度的状况. 后面文件是否已上传完成不能清晰直观的看到. 必须手动滚滚动条.
2. 多批次上传文件的情况下, 没有清空前一批次文件上传清单且新一批上传的文件是跟在上一批次文件之后追加列在列表上的. 这造成了三个问题: 首先是看不到后面批次上传文件的上传进度. 还要拖滚动条. 其次文件上传列表过长导致页面卡顿. 你可以试试传输上百个文件, 页面会非常的卡. 最后难以分辨出哪些文件是哪一批上传的.
3. 批量文件上传结束后, 会卡一段时间. 目录中文件列表渲染成功后恢复.

根据以上问题提出以下建议:
1. 上传成功的文件直接从上传对话框文件队列中移除. 并显示在目标目录中. 如果目标目录未打开, 则不予显示. 或者学习 ACFun, 在屏幕左下角 / 右下角 以书签栈的方式顺序显示最近上传成功/失败的个文件. 哪怕上传文件对话框最小化了依然显示. 
![image](https://user-images.githubusercontent.com/7188738/81507631-3cbe3380-9331-11ea-9645-d6595f2657e1.png)
2. 上传文件列表以文件上传总体进度自动滚动. 确保上传对话框上默认显示的是正在上传的文件. 而如果用户滚动滚动条以至滚动位置列表项中未包含当前正在传输的文件, 则对话框滚动条不随上传进度而滚动. 用户滚动到某个未上传文件位置静止后文件上传总体进入到达当前停留位置后超越, 滚动条同样滚动. 参见 QQ.

**Comment by Steve-George** [comment]
很难不赞同
