### ISSUE TITLE
[Enhancement] 上传文件期间进行文件hash. 用来判断文件是否已经上传过了

### ISSUE THREAD

**Issue by lujiaxing** [cloudreve/Cloudreve#371]
建议在 files 表中增加 hash 字段. 在上传前对等待上传的文件按顺序作 MD5 / SHA1 并记录. 下次上传文件之前可以对文件进行 hash 并异步交给服务器由服务器程序判定此文件是否上传过. 现在是不管多大先把文件传完了再检测. 这样效率比较低.

**Comment by zjsth92** [comment]
dup https://github.com/cloudreve/Cloudreve/issues/285
