### ISSUE TITLE
希望能在openwrt上运行,

### ISSUE THREAD

**Issue by garypang13** [cloudreve/Cloudreve#372]
在openwrt X86_64上提示 -ash: ./cloudreve: not found
希望能兼容openwrt 毕竟一般家里很少有linux服务器, 家用搭建下载云盘主要就是软路由装openwrt或者NAS系统,那用的人肯定会多很多,我可以再简单整个配套的luci-app

**Comment by zjsth92** [comment]
`-ash: ./cloudreve: not found`
这个是路径不对吧，`ls` 看下有没有这个文件

**Comment by lujiaxing** [comment]
难度很大. 虽然都是 OpenWRT, 但是不同路由器的 CPU 不一样. 编译方法也就不一样.  MT7620 / MT7621A / BCM4709 / BCM4708 等等... 不同的 CPU 架构不一样, mips32 / mips64 / mipsel / mipshf / arm32 / armhf / aarch64... 需要不同的编译工具链. 想找齐实在太难了. 还是建议你根据自己设备的具体 CPU 型号和架构自行编译.

**Comment by garypang13** [comment]
> 难度很大. 虽然都是 OpenWRT, 但是不同路由器的 CPU 不一样. 编译方法也就不一样. MT7620 / MT7621A / BCM4709 / BCM4708 等等... 不同的 CPU 架构不一样, mips32 / mips64 / mipsel / mipshf / arm32 / armhf / aarch64... 需要不同的编译工具链. 想找齐实在太难了. 还是建议你根据自己设备的具体 CPU 型号和架构自行编译.

肯定不需要兼容所有openwrt设备,就只针对现在已有的amd64 arm64就行.
我的设备是openwrt X86_64, 但是无法运行 cloudreve_3.0.0_linux_amd64

**Comment by zjsth92** [comment]
> > 难度很大. 虽然都是 OpenWRT, 但是不同路由器的 CPU 不一样. 编译方法也就不一样. MT7620 / MT7621A / BCM4709 / BCM4708 等等... 不同的 CPU 架构不一样, mips32 / mips64 / mipsel / mipshf / arm32 / armhf / aarch64... 需要不同的编译工具链. 想找齐实在太难了. 还是建议你根据自己设备的具体 CPU 型号和架构自行编译.
> 
> 肯定不需要兼容所有openwrt设备,就只针对现有的amd64 arm64就行.
> 我的设备是openwrt X86_64, 但是无法运行 cloudreve_3.0.0_linux_amd64
> 
> 

所以你这个到底报啥错？那个not found是路径不对

**Comment by lujiaxing** [comment]
> > 难度很大. 虽然都是 OpenWRT, 但是不同路由器的 CPU 不一样. 编译方法也就不一样. MT7620 / MT7621A / BCM4709 / BCM4708 等等... 不同的 CPU 架构不一样, mips32 / mips64 / mipsel / mipshf / arm32 / armhf / aarch64... 需要不同的编译工具链. 想找齐实在太难了. 还是建议你根据自己设备的具体 CPU 型号和架构自行编译.
> 
> 肯定不需要兼容所有openwrt设备,就只针对现有的amd64 arm64就行.
> 我的设备是openwrt X86_64, 但是无法运行 cloudreve_3.0.0_linux_amd64

即便是同一架构的, 也存在底层库的差异. 比如说同样架构 glibc 和 ulibc 编译出来的东西就不通用. 你这种情况我估计就是 libc 库不一样所致.

**Comment by garypang13** [comment]
> 
> 所以你这个到底报啥错？那个not found是路径不对

![image](https://user-images.githubusercontent.com/48883331/81530432-745dc780-9393-11ea-9676-9eb24425645e.png)

**Comment by zjsth92** [comment]
上docker吧，如果docker也不兼容…

**Comment by zjsth92** [comment]
> > 
> > 所以你这个到底报啥错？那个not found是路径不对
> 
> ![image](https://user-images.githubusercontent.com/48883331/81530432-745dc780-9393-11ea-9676-9eb24425645e.png)
> 

试一下```
chmod a+x /root/cloudreve
/root/cloudreve
```

**Comment by garypang13** [comment]
> > > 所以你这个到底报啥错？那个not found是路径不对
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/48883331/81530432-745dc780-9393-11ea-9676-9eb24425645e.png)
> 
> 试一下```
> chmod a+x /root/cloudreve
> /root/cloudreve

不行哈,可能是还缺少什么库吧,要是有详细的报错信息就好了.

**Comment by zjsth92** [comment]
> > > > 所以你这个到底报啥错？那个not found是路径不对
> > > 
> > > 
> > > ![image](https://user-images.githubusercontent.com/48883331/81530432-745dc780-9393-11ea-9676-9eb24425645e.png)
> > 
> > 试一下```
> > chmod a+x /root/cloudreve
> > /root/cloudreve
> 
> 不行哈,可能是还缺少什么库吧,要是有详细的报错信息就好了.

还是用docker最简单了。按@lujiaxing 说的应该是底层有库不一样，要重新编译

**Comment by hmsjy2017** [comment]
openwrt直接运行cloudreve出现同样的错误，试了一下cloudreve-docker也不行
目前可行的方法是 docker Ubuntu里面运行 cloudreve

**Comment by wsndshx** [comment]
openwrt使用的是`musl-libc`, 运行由`glibc-libc`编译的程序会报错`not found`, 建议在alpine linux下重新编译出二进制文件.

**Comment by wsndshx** [comment]
> openwrt使用的是`musl-libc`, 运行由`glibc-libc`编译的程序会报错`not found`, 建议在alpine linux下重新编译出二进制文件.

然鹅`musl-libc`编译出来的文件在vps上通常跑不了, 也是报`not found`, 不过可以通过安装musl运行库解决.

**Comment by hmsjy2017** [comment]
> > openwrt使用的是`musl-libc`, 运行由`glibc-libc`编译的程序会报错`not found`, 建议在alpine linux下重新编译出二进制文件.
> 
> 然鹅`musl-libc`编译出来的文件在vps上通常跑不了, 也是报`not found`, 不过可以通过安装musl运行库解决.

那 openwrt 能安装 glibc-libc 运行库吗？

**Comment by wsndshx** [comment]
> > > openwrt使用的是`musl-libc`, 运行由`glibc-libc`编译的程序会报错`not found`, 建议在alpine linux下重新编译出二进制文件.
> > 
> > 
> > 然鹅`musl-libc`编译出来的文件在vps上通常跑不了, 也是报`not found`, 不过可以通过安装musl运行库解决.
> 
> 那 openwrt 能安装 glibc-libc 运行库吗？

emmmm我觉得不行, 可能需要用openwrt sdk编译一个带glibc-libc的openwrt吧
