### ISSUE TITLE
Onedrive的缩略图无法显示，似乎是API无法使用

### ISSUE THREAD

**Issue by p362** [cloudreve/Cloudreve#373]
国际版会使用这个方法
```
cropOption = fmt.Sprintf("c%dx%d_Crop", w, h)
requestURL = client.getRequestURL("me/drive/root:/"+dst+":/thumbnails") + "?select=" + cropOption
```
但是API好像不支持这个方法
调试
`https://graph.microsoft.com/v1.0/me/drive/root:/path/to/file:/thumbnails?select=c400x300_Crop`
提示
```
{
    "error": {
        "code": "invalidRequest",
        "message": "Unsupported options were provided in the thumbnail descriptor.",
        "innerError": {
            "request-id": "5b980f7e-eb88-4ccd-acfc-14c5abae032b",
            "date": "2020-05-09T11:32:29"
        }
    }
}
```
不过好像可以直接使用select=large，修改返回缩略图链接的width和height参数，并加上cropMode参数（cropMode可选：fit, fill, top, bottom；默认fit）实现裁剪缩略图
`https://eastasia1-mediap.svc.ms/transform/thumbnail?provider=spo&inputFormat=(@inputFormat)&cs=(@cs)&correlationId=(@correlationId)&docid=(@docid)&version=Published&width=(@width)&height=(@height)&cropMode=(@cropMode)`
但是部分文件即使无缩略图也能获取到链接，访问链接实际返回状态码406与错误
```
{
	"error": {
		"code": "generalException",
		"message": "Substitution Stream found in slot (Original Time: 2020-05-08 21:15:00Z. Original error code: -2146233088",
		"innererror": {
			"code": "SubStreamCached_GeneralFailure"
		}
	}
}
```

**Comment by 742481030** [comment]
当图片过多时候,会触发api限制 我曾经浏览目录2000+图片时候

**Comment by wsndshx** [comment]
> 当图片过多时候,会触发api限制 我曾经浏览目录2000+图片时候

emmm我的用OD作为储存在没有几张图片（5张）的时候也无法显示略缩图，不过可以正常查看文件

**Comment by HFO4** [comment]
经过反复测试，国际版是可以成功生成缩略图的，可能是相关 API 不太稳定。暂时先close了，如果有后续更新欢迎reopen.

**Comment by huang545** [comment]
我似乎也碰到了这个问题，国际版OD，世纪互联版本没有出现这个问题
即使使用某些方法，一样无法显示缩略图

**Comment by BlueWhale235** [comment]
一样无法生成mp4的缩略图，但似乎jpg\pdf那种的可以生成
`
{"error":{
  "code": "generalException",
  "message": "Substitution Stream for GeneralFailure found in slot (Original Time: 2025-10-18 09:21:00Z. Original error code: -2146233088",
  "innererror": {
    "code": "SubStreamCached_GeneralFailure"
  }
}}
`
@HFO4
