### ISSUE TITLE
i18n/l10n support

### ISSUE THREAD

**Issue by balcsida** [cloudreve/Cloudreve#374]
Hi everyone,

First of all, I would like to express my fascination with this software - for me, it seems a good alternative for Seafile/Nextcloud.

My only question is if there are any plans to have other languages supported or have internationalization/localization support and if yes, how can we help - I couldn't even buy the Pro version on you site.

Kind regards,
@balcsida

**Comment by zjsth92** [comment]
Hey @balcsida ,

I'm contributing to the [frontend](https://github.com/cloudreve/frontend). As so far, this project doesn't support i18n/l10n. But it will be great if you can help :). 

Best,
TS

**Comment by HFO4** [comment]
Glad you like the project. Currently, i18n/l10n mechanism was suppreted under the hood, but it's already being considered. It will probably be avaliable in next few milestones.

**Comment by balcsida** [comment]
Thank you guys for the answers.

@zjsth92: I agree, the UI is more important in this case then the log messages.
I forked the frontend repo and I'll start to work on it
