### ISSUE TITLE
safari 下下载会变成download.aspx

### ISSUE THREAD

**Issue by Xiaohantx** [cloudreve/Cloudreve#376]
https://file.markone.xyz/#/s/4rlS4

可以safari下尝试下

![image](https://user-images.githubusercontent.com/30380582/81641256-25776700-9453-11ea-9857-1f3a6367436c.png)

**Comment by HFO4** [comment]
OneDrive的下载是浏览器直接请求OneDrive那边的，Cloudreve暂时无法做出干涉。
