### ISSUE TITLE
[feature request]关于由服务器中转OneDrive下载的需求

### ISSUE THREAD

**Issue by Creling** [cloudreve/Cloudreve#377]
您好：
不知是否可以支持由服务器中转OneDrive的下载？
OneDrive国际版的网络质量每况愈下，如果可以支持由服务器中转下载，我们将有更大的空间去优化OneDrive下载，比如更换线路更好的服务器等。可能包括我在内的很多用户，只是喜爱OneDrive的5T空间，并不真正需要通过OneDrive直链下载来节省我们服务器的流量。
望作者酌情考虑。

此致

**Comment by HFO4** [comment]
直接下载还是最广泛的需求，暂不考虑增加中转下载。
