### ISSUE TITLE
V3.1是否添加Amazon S3的接口？

### ISSUE THREAD

**Issue by Dark-CC** [cloudreve/Cloudreve#378]
最新版V3.1会添加Amazon S3的接口吗？

**Comment by Dark-CC** [comment]
还有要不要增加一个前端的公告通知栏

**Comment by TheresaQWQ** [comment]
@Dark-CC 这个我都提过issue了...

**Comment by Dark-CC** [comment]
@TheresaQWQ 我就想知道，老大有没有这个计划做。

**Comment by HFO4** [comment]
3.1 版本的计划在 https://github.com/cloudreve/Cloudreve/projects/2，S3适配不会在3.1版本中出现。
