### ISSUE TITLE
建议离线下载功能增加文件大小限制和任务数量限制

### ISSUE THREAD

**Issue by XMD0718** [cloudreve/Cloudreve#380]
RT
我翻阅过Aria2c的参数文档，并未发现有可以限制文件大小的参数。
我的存储策略是对接云存储的，但离线下载功能需要将文件下载到本地再进行上传，因此，若无限制离线下载文件大小的功能，将很有可能导致服务器流量被偷跑，这种情况是很被动的，若未能及时发现，很可能会对服务器产生高额费用。
加入限制文件大小和限制任务数量的功能能够缓解这种问题，我非常希望此功能能够出现在未来的更新中。
非常感谢开发人员的付出。

**Comment by IITII** [comment]
aria2提供了获取下载文件信息的接口，感觉这个应该可以帮得上忙

**Comment by HFO4** [comment]
当下载过程中获取到任务文件大小信息时，Cloudreve会根据存储策略、用户组设定检查，如果超出容量限制，会随即停止任务。

**Comment by XMD0718** [comment]
> 当下载过程中获取到任务文件大小信息时，Cloudreve会根据存储策略、用户组设定检查，如果超出容量限制，会随即停止任务。

这与给用户组分配的容量并不冲突。我的存储策略对接的云存储，上传的文件不走服务器流量，因此我大可将分配给用户的容量大一点，但这并不意味着我能够接受用户使用离线下载功能将这个空间填满。离线下载相比直接对接云存储多了在本地中转这一环，而很多服务器的流量是有每月额度限制的，特别是那种香港G口按流量收费的服务器，这个问题在我看来是很严重的，我也希望开发者能够重视这个问题，否则网盘的管理者将要消耗大量的精力来管理和监视。当然，是否增加这个功能还取决于开发者的选择，我这里只是提个建议罢了。

**Comment by afxdxhy** [comment]
> 当下载过程中获取到任务文件大小信息时，Cloudreve会根据存储策略、用户组设定检查，如果超出容量限制，会随即停止任务。

我也希望增加这个功能
