### ISSUE TITLE
希望加入在线office编辑功能

### ISSUE THREAD

**Issue by aganlove** [cloudreve/Cloudreve#381]
目前的在线预览是国内通用的网盘的做法，希望能够支持在线office文档在线编辑，给网盘锦上添花

**Comment by topjohncian** [comment]
没有解决方案

**Comment by iyalue** [comment]
能不能直接对接onlyoffice?

**Comment by aganlove** [comment]
> 能不能直接对接onlyoffice?

希望加上，onlyoffice有接口，可惜react我不会

**Comment by lonelyor** [comment]
希望能在线预览 office
