### ISSUE TITLE
从机存储跨域访问问题

### ISSUE THREAD

**Issue by henrywu19359** [cloudreve/Cloudreve#382]
使用从机存储时，域名与主站点域名不同时由于没有 ‘Access-Control-Allow-Origin’ 这个响应头会被Chrome浏览器拦截（根据CORS政策），希望能够解决这个问题。
控制台截图可以见附件（域名已隐去）

![控制台截图](https://user-images.githubusercontent.com/49585566/82001944-036a2880-968f-11ea-8477-2fff7dddfeeb.jpg)

**Comment by HFO4** [comment]
参考添加存储策略时的指引，在从机配置文件中启用CORS。

**Comment by henrywu19359** [comment]
配置文件我是按照范例一摸一样复制过去的，站点也重新搭建过了，依然有这个问题...
用的是这个：
[CORS]
AllowOrigins = *
AllowMethods = OPTIONS,GET,POST
AllowHeaders = *

**Comment by HFO4** [comment]
从报错看，你从机服务器服务器地址填写有误。

**Comment by henrywu19359** [comment]
后台配置的时候测试通信是正常的，并且也能上传，只是在最后“处理中”的时候出现这个错误...

**Comment by Lehmaning** [comment]
我也有这个问题，不知道什么原因。

**Comment by HenryWu-OwO** [comment]
> 我也有这个问题，不知道什么原因。

需要在从机的服务器上加上CORS响应头，比如你是 Nginx 作反代的话需要在 Nginx 的配置文件中的 Server 段加上 
location /
　　{
　　add_header Access-Control-Allow-Origin *;
　　add_header Access-Control-Allow-Headers X-Requested-With;
　　add_header Access-Control-Allow-Methods GET,POST,OPTIONS;
　　include fastcgi.conf;
　　}
这样应该就可以了。
