### ISSUE TITLE
宝塔面板中反代后上传文件遇到HTTP错误

### ISSUE THREAD

**Issue by simon-yanghl** [cloudreve/Cloudreve#383]
运行环境：CENTOS7.8.2003 PY2.7.5 vultr的日本VPS，php版本5.6
通过反代127.0.0.1:5212的方式实现直接用网址打开网盘，拖拽文件上传时十几秒后提示
![image](https://user-images.githubusercontent.com/63163745/82027964-8effab80-96c7-11ea-8321-7602d17dfa62.png)
再十几秒后提示
![image](https://user-images.githubusercontent.com/63163745/82027979-96bf5000-96c7-11ea-910e-3c9181b9b48c.png)
 通过IP：5212的方式打开网页则没有任何问题
请问这种情况如何解决？

**Comment by HFO4** [comment]
参考 https://forum.cloudreve.org/d/871
