### ISSUE TITLE
小建议：希望能够更换上传速度计算方式

### ISSUE THREAD

**Issue by HenryWu-OwO** [cloudreve/Cloudreve#384]
当前的速度计算方式似乎是计算的平均上传速度，在上传大文件时，就不能很好的反映当前真实的上传速度（事实上传大文件时无论实时速度怎么变化，显示的速度几乎不变了）。
希望能将速度显示更改为实时速度，这应该不难。我想的方式是用当前已上传大小减去前一秒已上传大小即可显示当前速度。
谢谢。

**Comment by HFO4** [comment]
3.5.0后已支持切换速度计算方式
