### ISSUE TITLE
PWA 以及 OneDrive 上传问题

### ISSUE THREAD

**Issue by ceecx** [cloudreve/Cloudreve#386]
1. 默认打开首页会跳转到 /#/login, 即使已经登录的用户用 PWA 重新启动也是这个界面, 需要再登录一次或手动切换到其他页面, 应该加个登录判断? 已登录用户自动跳转主目录. 目前我的解决方法是先登录之后切换到 /#/home, 然后再创建 PWA 快捷方式...

2. 点击 "我的文件" 菜单默认是展开下面的分类, 如果我进行了搜索, 想回到主目录只能点击图中的小斜杠 (一开始真没看到,哈哈), 有点不好找, 希望可以加个主目录的菜单, 或把文件类型分类单独做个菜单, 或者左上角网站名称处变成可点击返回主目录也行.
![image](https://user-images.githubusercontent.com/18570103/82125144-919cf680-97d6-11ea-8c2d-036a66b97058.png)

~~3. 自己编译一直用不了, 编译期间也没有报错, 之前是 Redux Devtool 有问题, 但已经修复了, 现在的 [Issues](https://github.com/cloudreve/Cloudreve/issues/385), 如果能用的话前面两条还能自己解决一下.~~
可能是编译环境有问题, 更新了几个包之后现在好像又 OK 了.

4. 相同文件名上传问题
测试于 OneDrive 存储策略, 原来以为是根据本地储存的文件名来判断重名, 发现不对, 好像是根据储存在数据库文件名 (前端文件名称) 判断是否重名. 只要我上传相同文件名的文件就会提示错误, 我避免重名的存储策略就感觉没多大用了, 如果能判断储存的文件名就好了, 这样相同的文件名 (相同程序) 可以上传多份, 前端文件名字可以加上类似 {datetime} 的时间戳, 还能当历史版本用, 岂不快哉.
![image](https://user-images.githubusercontent.com/18570103/82125565-623bb900-97d9-11ea-8273-1ff694b44d81.png)

另外 OneDrive 存储策略如果 "不开启物理文件重命名", 再上传同名文件就会把之前上传的同名物理文件删除, 然后在前端还能看的到, 也删除不了.
![image](https://user-images.githubusercontent.com/18570103/82125917-b2b41600-97db-11ea-9494-0ddc1de916ab.png)

感谢几位贡献者, 刚刚已经买了捐赠版, 加油.

**Comment by HFO4** [comment]
> 默认打开首页会跳转到 /#/login, 即使已经登录的用户用 PWA 重新启动也是这个界面, 需要再登录一次或手动切换到其他页面, 应该加个登录判断? 已登录用户自动跳转主目录. 目前我的解决方法是先登录之后切换到 /#/home, 然后再创建 PWA 快捷方式...

无法复现，可能是上层CDN缓存了接口响应

> 点击 "我的文件" 菜单默认是展开下面的分类, 如果我进行了搜索, 想回到主目录只能点击图中的小斜杠 (一开始真没看到,哈哈), 有点不好找, 希望可以加个主目录的菜单, 或把文件类型分类单独做个菜单, 或者左上角网站名称处变成可点击返回主目录也行.

目前可以通过浏览器后退返回文件列表

> 另外 OneDrive 存储策略如果 "不开启物理文件重命名", 再上传同名文件就会把之前上传的同名物理文件删除, 然后在前端还能看的到, 也删除不了.

3.1 版本中增加了强制删除

**Comment by ceecx** [comment]
第一个问题回头我看看能不能复现，现在默认都是未缓存任何数据的，但偶尔会有个报错：
![image](https://user-images.githubusercontent.com/18570103/82194187-fcf6dd80-9928-11ea-8b83-996dc6fc552f.png)

不知道影响了什么东西，因为暂时没在生产环境使用。

题外：如果 IP:5212 形式直接套 CDN，不缓存任何文件只当前端，不经过 CDN  中转吧？偷懒暂未测试。
