### ISSUE TITLE
强烈建议让Cloudreve直接读取OneDrive文件列表！

### ISSUE THREAD

**Issue by Coolemao** [cloudreve/Cloudreve#389]
将OneDrive里的文件下载下来再上传到Cloudreve，最后再转入OneDrive中读取，是一件很蠢的事情

**Comment by henrywu19359** [comment]
如果您只是为了链接OneDrive，可以考虑一下使用Oneindex
Cloudreve本身是网盘，不会展示OneDrive中已有的内容。

**Comment by HFO4** [comment]
参见#304
