### ISSUE TITLE
求增加sharepoint的sites支持

### ISSUE THREAD

**Issue by vasexan** [cloudreve/Cloudreve#391]
onedrive子号，管理员可以直接看文件，sharepoint sites说只能指定成员看到，安全性高一点，而且空间限制25t比onedrive 5t高还不用申请
[http://blog.jialezi.net/?post=157](http://blog.jialezi.net/?post=157)

> 通过查阅微软的文档，SharePoint的API和OneDrive的主要是用到的id不一样，使用方法是通用的。

**Comment by HFO4** [comment]
与 #364 重复

**Comment by 742481030** [comment]
> onedrive子号，管理员可以直接看文件，sharepoint站点说只能指定成员看到，安全性高一点，而且空间限制25t比onedrive 5t高还不用申请
> [http://blog.jialezi.net/?post= 157](http://blog.jialezi.net/?post=157)
> 
> > 通过查阅微软的文档，SharePoint的API和OneDrive的主要是用到的id不一样，使用方法是通用的。

这个简单,我的less被关闭了我已经自己实现,修改me/drive/root/children  为 /drives/{drivesid}/root

**Comment by 742481030** [comment]
if ({driveid}=="")

**Comment by 742481030** [comment]
if driveisid== "" {
if dst == "" { 
	requestURL = client.getRequestURL("me/drive/root/children")
} else {
	requestURL = client.getRequestURL("me/drive/root:/" + dst + ":/children")
}
}else{

	if dst == "" {
		requestURL = client.getRequestURL("/drives/"+driveisid+"/root/children")
	} else {
		requestURL = client.getRequestURL("/drives/+driveisid+/root:/" + dst + ":/children")
	}


修改api

**Comment by 742481030** [comment]
if drivesid  ==“”{
if id != "" {
	requestURL = client.getRequestURL("/me/drive/items/" + id)
} else {
	dst := strings.TrimPrefix(path, "/")
	requestURL = client.getRequestURL("me/drive/root:/" + dst)
}}else{


	if id != "" {
		requestURL = client.getRequestURL("/dirves/"+drivesid+"/items/" + id)
	} else {
		dst := strings.TrimPrefix(path, "/")
		requestURL = client.getRequestURL("/drives/"+drivesid+"/root:/" + dst)
	}
