### ISSUE TITLE
systemctl 开机启动失败，手动启动正常

### ISSUE THREAD

**Issue by wnark** [cloudreve/Cloudreve#392]
![image.png](https://i.loli.net/2020/05/17/xMv8DdY9zlptjGC.png)
status错误代码也没显示什么东西
手动启动是正常的
![image.png](https://i.loli.net/2020/05/17/7gtOyDfEBqPoUTp.png)

**Comment by wnark** [comment]
知道原因了，服务器性能太弱，进程冲突
和nextcloud一个原因，解决办法是延时
Restart=on-failure
RestartSec=60s

**Comment by wnark** [comment]
systemctl没查到比较高大上的延时启动方法

**Comment by HFO4** [comment]
是否使用了MySQL？

**Comment by wnark** [comment]
> 是否使用了MySQL？

是的，使用了MySQL和redis

**Comment by HFO4** [comment]
试下 https://forum.cloudreve.org/d/863 能否解决

**Comment by wnark** [comment]
> 试下 https://forum.cloudreve.org/d/863 能否解决

有效，果然是mysql的问题，谢谢了
