### ISSUE TITLE
建议加入自定义分享外链下载地址的功能

### ISSUE THREAD

**Issue by shadowfish07** [cloudreve/Cloudreve#393]
我使用OneDrive作为存储，因为现在获取到的微软家的分享链接速度国内不稳定，我使用fast.io提供的服务来进行CDN加速，分享的时候只需要使用我自定义的cdn域名+文件名就可以了，望采纳

**Comment by HFO4** [comment]
部分存储策略支持使用同一提供商的CDN服务，OneDrive 不支持，目前也不计划支持。
