### ISSUE TITLE
[Feature Request] 可选上传文件加密功能

### ISSUE THREAD

**Issue by neteroster** [cloudreve/Cloudreve#394]
对于一些隐私相关的敏感资料，希望上传时可以增加一个「加密上传」选项，由用户设置或自动生成密码，对数据在服务端进行加密后再上传到存储策略，以确保数据的机密性和完整性。

**Comment by hiCasper** [comment]
此类功能会极大耗费服务端资源，支持的可能性不大。

如果需要此类功能，建议使用Seafile等同类产品。

**Comment by gzz2000** [comment]
挖坟（
seafile不支持外部存储，nextcloud也不支持onedrive之类，还是cloudreve好。
有时候我们加密安全性要求也不大，其实只要混淆一下就好了，比如在文档上传之前每个字符xor一个东西之类的，这样至少传到云上的东西被河蟹的概率低了好多。
看起来我得自行研究一下在代码哪里加这个东西好。或者如果开发者在可以给点提示嘛。我猜是pkg/filesystem一类地方

**Comment by HFO4** [comment]
加密后无法实现下载直传。

Justin Zhang ***@***.***>于2022年2月22日 周二22:30写道：

**Comment by danblaze13** [comment]
@HFO4 这个需求很怪，尤其是定位商业的来说，相当于用户传啥都是加密的，套娃行为。如果是自用备份，市面上有成熟加密上云的方案了，也可以自己搞定
