### ISSUE TITLE
前端套用 CDN 后 400 Bad Request

### ISSUE THREAD

**Issue by CeeIM** [cloudreve/Cloudreve#396]
测试了阿里云 CDN 所有文件默认不缓存也用不了，后来换到腾讯云 CDN，关闭所有缓存可用，但偶尔会报错，如图：
![image](https://user-images.githubusercontent.com/18570103/82194448-6c6ccd00-9929-11ea-9cce-52e63f4fbe41.png)

系统原生 WebDAV 连不上还以为 Windows 兼容性不好，换了 RaiDrive 报错 400 Bad Request，应该也是套了 CDN 的原因，使用 IP:5212 正常连接。现在无法让别人使用 WebDAV，因为习惯了不暴露源站，为了安全前面都会套一层。

**Comment by weipeilong123** [comment]
+1
