### ISSUE TITLE
离线下载的文件不走阿里云内网中转至OSS

### ISSUE THREAD

**Issue by Cettiidae** [cloudreve/Cloudreve#399]
存储后端：深圳 标准存储 OSS
服务器：深圳 ECS
Cloudreve版本：3.0.0

表现：文件转存时外网上传带宽占满。

能否让文件中转走阿里云内网上传至OSS呢？

**Comment by henrywu19359** [comment]
我觉得对接OSS的时候Endpoint地址填写为内网的就可以了。

**Comment by Cettiidae** [comment]
> 我觉得对接OSS的时候Endpoint地址填写为内网的就可以了。

这样配置是否会导致正常上传异常呢？
我去尝试一下，非常感谢您的建议。

**Comment by hiCasper** [comment]
> > 我觉得对接OSS的时候Endpoint地址填写为内网的就可以了。
> 
> 这样配置是否会导致正常上传异常呢？
> 我去尝试一下，非常感谢您的建议。

这样的话非阿里内网的客户端可能都无法正常下载了。
比较可靠的还是看看作者后续会不会加上相关的功能吧。

**Comment by henrywu19359** [comment]
确实会有这个问题，可以考虑一下将OSS挂载为本地磁盘，然后使用本地上传策略，例如使用Rclone（我不确定rclone是不是支持这个），你可以上网找一下有没有这方面的教程。

**Comment by Cettiidae** [comment]
@henrywu19359 很遗憾，这种修改方法会导致网页无法正常上传。
我尝试将存储后端的：
```
存储端 Endpoint ：oss-cn-shenzhen.aliyuncs.com
改为：
oss-cn-shenzhen-internal.aliyuncs.com
```
虽然离线下载的文件能通过内网传输了，但是在网页上直接上传文件时会无法处理上传任务。

**Comment by henrywu19359** [comment]
> @henrywu19359 很遗憾，这种修改方法会导致网页无法正常上传。
> 我尝试将存储后端的：
> 
> ```
> 存储端 Endpoint ：oss-cn-shenzhen.aliyuncs.com
> 改为：
> oss-cn-shenzhen-internal.aliyuncs.com
> ```
> 
> 虽然离线下载的文件能通过内网传输了，但是在网页上直接上传文件时会无法处理上传任务。

这样确实有问题，有尝试过挂载为本地磁盘曲线救国吗（例如使用rclone等）

**Comment by Cettiidae** [comment]
@henrywu19359 使用过ossfs将OSS挂载为本地磁盘虽然可行，但是ossfs的CPU开销极高。rclone没有使用过，不太清楚rclone的性能如何。还是直接内网地址上传的开销最小最方便，希望作者后期能加入吧！

**Comment by HFO4** [comment]
后续会增加 OSS 的 EndPoint 输入项，允许单独为中转传输指定内网 EndPoint。

**Comment by LUODIAN-233** [comment]
> @ henrywu19359使用过ossfs将OSS挂载为本地磁盘虽然可行，但是ossfs的CPU容量极高。rclone没有使用过，不太清楚rclone的性能如何。还是直接内网地址上传的体积最小最方便，希望作者后期能加入吧！

我的临时解决方案是先通过ping工具和hosts文件，将内网的Bucket 域名解析出来的ip定向为外网的Bucket 域名，这样离线下载的文件就能通过内网进行传输
