### ISSUE TITLE
建议新增m3u8与flv在线播放支持

### ISSUE THREAD

**Issue by wnark** [cloudreve/Cloudreve#401]
我观察到cloudreve貌似是用Dplayer做在线播放，dpalyer支持播放m3u8与flv格式的视频，因此可能可以增加m3u8与flv的在线播放支持吧。。。

**Comment by HFO4** [comment]
flv.js在 fetch 视频资源时无法携带cookie，所以暂时无法支持，m3u后续会尝试新增支持。

**Comment by canwushuang** [comment]
Try to change the filename extension to mp4.

**Comment by bnsave100** [comment]
> 
> 
> Try to change the filename extension to mp4.

nope it's not the same
