### ISSUE TITLE
文件名中带#号导致无法正常下载

### ISSUE THREAD

**Issue by hiCasper** [cloudreve/Cloudreve#405]
![](https://i.loli.net/2020/05/24/P5L7XCd8NkAmoFz.jpg)
![](https://i.loli.net/2020/05/24/tXRvOJpKMGFhHuT.jpg)

**Comment by yinrenxin** [comment]
特殊字符要特殊转义下

**Comment by HFO4** [comment]
这个是什么存储策略出现的问题？

**Comment by hiCasper** [comment]
> 这个是什么存储策略出现的问题？

应该是又拍云
