### ISSUE TITLE
service-worker.js 应禁止浏览器缓存

### ISSUE THREAD

**Issue by HFO4** [cloudreve/Cloudreve#406]
目前，版本更新后，浏览器仍然从缓存中读取静态资源文件。需要禁止与 ServiceWorker 相关静态资源文件的缓存。

**Comment by 742481030** [comment]
如果你不流量你可以删了这个文件,

**Comment by topjohncian** [comment]
先unregister再register疑似有效

**Comment by 742481030** [comment]
> 先unregister再register疑似有效

你的客户可不会这么操作,你是打电话通知还是发公告?手机浏览器通常要清除所有缓存,浏览器默认清除缓存也是不行的也就是,先unregister再register疑,不缺那点js css 流量,通常我编译前端时候直接删了service-worker.js,我之前的版本没有service-worker.js,跟新3.1后发现文件无法删除,所以我不得不删除service-worker.js

**Comment by topjohncian** [comment]
> > 先unregister再register疑似有效
> 
> 你的客户可不会这么操作,你是打电话通知还是发公告?手机浏览器通常要清除所有缓存,浏览器默认清除缓存也是不行的也就是,先unregister再register疑,不缺那点js css 流量,通常我编译前端时候直接删了service-worker.js,我之前的版本没有service-worker.js,跟新3.1后发现文件无法删除,所以我不得不删除service-worker.js

serviceworker的作用是PWA

**Comment by topjohncian** [comment]
> 先unregister再register疑似有效

此方案是给作者提出的建议

**Comment by 742481030** [comment]
> 先unregister再register疑似有效

只有作者跟新这玩意让跟新版本后service-worker.js 自动卸载重写装载.不然目前service-worker.js,改了前端后或者重写编译后,你的客户不会手动清除缓存基本上清一色的异常了

**Comment by topjohncian** [comment]
> > 先unregister再register疑似有效
> 
> 只有作者跟新这玩意让跟新版本后service-worker.js 自动卸载重写装载.不然目前service-worker.js,改了前端后或者重写编译后,你的客户不会手动清除缓存基本上清一色的异常了

是的 我的建议就是比对版本号后重新注册

**Comment by 742481030** [comment]
> > > 先unregister再register疑似有效
> > 
> > 
> > 只有作者跟新这玩意让跟新版本后service-worker.js 自动卸载重写装载.不然目前service-worker.js,改了前端后或者重写编译后,你的客户不会手动清除缓存基本上清一色的异常了
> 
> 是的 我的建议就是比对版本号后重新注册

我索性编译时候直接删了service-worker.js,因为我不知道怎么自动哈哈

**Comment by 742481030** [comment]
> > > > 先unregister再register疑似有效
> > > 
> > > 
> > > 只有作者跟新这玩意让跟新版本后service-worker.js 自动卸载重写装载.不然目前service-worker.js,改了前端后或者重写编译后,你的客户不会手动清除缓存基本上清一色的异常了
> > 
> > 
> > 是的 我的建议就是比对版本号后重新注册
> 
> 我索性编译时候直接删了service-worker.js,因为我不知道怎么自动哈哈

这个bug还是作者自己提的哈哈,我之前加了sharepoint后无法删除文件,原来就是service-worker.js,缓存了文件给我吓得我以为我又要改前端文件什么了
