### ISSUE TITLE
手动修改pkg/flies/drive/onedrive/api.go 已支持sharepoint

### ISSUE THREAD

**Issue by 742481030** [cloudreve/Cloudreve#407]
打开文件pkg/flies/drive/onedrive/api.go
搜索文件里到/me/drive/   和 me/drive/替换空   也就是只剩下root/
然后修存储策略高级配置 servers后面加上/me/drive/    
sharepin 文件演示 https://yun.mxin.ltd/#/s/znaO5UJ
编译完成后第一步先直接添加onedrive ,然后到存储策略高级配置 复制 token  clienid 等利用下面工具
sharepoint站点获取工具http://sharepoint.mxin.ltd  站点id获取工具(不保证可用php源代码如下)
会获取到 例如 https://microsoftgraph.chinacloudapi.cn/v1.0/sites/alphaone.sharepoint.cn,a0031d38-3ee4-4e22-87e3-c5ca1825419a,eda2d4bf-9dd2-4703-a606-5ff84bbd1c5b/drive/
添加到存储策略高级设置到servre里  如果使用onedrive 填写https://microsoftgraph.chinacloudapi.cn/v1.0/me/drive/
如果使用shartpoint站点填写获取到到完整url
本人不会reactjs  所以前端配置向导我就懒得改了;

`<?php

 if ($_REQUEST['site'] == '') {
     echo '站点id获取工具/sites/名称或者/teams/名称 yiyione 的可以用默认的
     
     ';
     echo '<form action="" method="post">api地址默认世纪互联
	 
     
      国际版填2，世纪互联填1<br>
      <input type="text" name="types" value ="1" /><br><br>
	  
	  <br>
      
      client_secret    <input type="text" name="client_secret" value ="v4[Nq:4=rmFS78BwYi[@x3sGk-iY.U:S" /><br>
        client_id  <input type="text" name="client_id" value ="3447f073-eef3-4c60-bb68-113a86f2c39a" /><br>
          redirect_uri<input type="text" name="redirect_uri" value ="https://coding.mxin.ltd/api/onedrive.html" /><br>
       refresh_token cloudreve存储策略-高级设置    <input type="text" name="refresh_token" value ="" /><br>
         
          
 　　<input type="text" name="site" value ="/sites/jane" />
 　　<input type="submit" value="站点id" />
 </form>';
     exit;
 }
 if($_REQUEST["types"]=="1"){
	 $apiurl="https://microsoftgraph.chinacloudapi.cn/v1.0";
	 $oauthurl="https://login.partner.microsoftonline.cn/common/oauth2/v2.0";
	 
 }else{
	 $apiurl="https://graph.microsoft.com/v1.0";
	 $oauthurl="https://login.microsoftonline.com/common/oauth2/v2.0";
	 
 }
  $client_secret = $_REQUEST['client_secret'];
   $client_id = $_REQUEST['client_id'];
  $redirect_uri = $_REQUEST['redirect_uri'];
   $refresh_token=$_REQUEST['refresh_token'];
 echo $gloable=$requests["gloable"];
  
  
  $requests['url'] =  $oauthurl.'/token';
            $requests['post_data'] = "client_id={$client_id}&redirect_uri={$redirect_uri}&client_secret={$client_secret}&refresh_token={$refresh_token}&grant_type=refresh_token";
            $requests['headers'] = 'Content-Type: application/x-www-form-urlencoded';
            $resp = fetch::post($requests);
$ss = json_decode($resp->content);
 $access_token = $ss->access_token;

     $request['headers'] = "Authorization: bearer {$access_token}".PHP_EOL.'Content-Type: application/json'.PHP_EOL;
     $request['url'] = 'https://microsoftgraph.chinacloudapi.cn/v1.0/sites/root';
     $resp = fetch::get($request);
     $data = json_decode($resp->content, true);
     $hostname = $data['siteCollection']['hostname'];

         $getsiteid = $apiurl.'/sites/'.$hostname.':'.$_REQUEST['site'];
         $request['url'] = $getsiteid;
         $respp = fetch::get($request);
     $datass = json_decode($respp->content, true);

  $siteidurl = ($datass['id']);
  
 
 $bb = "
 $apiurl.'/sites/'.$siteidurl."/drive/";
 
 
 
 echo "下面复制到cloudreve 存储策略 server";
 echo $bb;exit;

class fetch
{
    public static $headers = 'User-Agent:Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36';
    public static $cookies;
    public static $curl_opt;
    public static $proxy;

    public static $max_connect = 10;

    public static function init($opt = array())
    {
        self::$curl_opt = array(
            CURLOPT_RETURNTRANSFER => 1, //true, $head 有请求的返回值
            CURLOPT_BINARYTRANSFER => true, //返回原生的Raw输出
            CURLOPT_HEADER => true, //启用时会将头文件的信息作为数据流输出。
            CURLOPT_FAILONERROR => true, //显示HTTP状态码，默认行为是忽略编号小于等于400的HTTP信息。
            CURLOPT_AUTOREFERER => true, //当根据Location:重定向时，自动设置header中的Referer:信息。
            CURLOPT_FOLLOWLOCATION => false, //跳转
            CURLOPT_CONNECTTIMEOUT => 3, //在发起连接前等待的时间，如果设置为0，则无限等待。
            CURLOPT_TIMEOUT => 5, //设置cURL允许执行的最长秒数。
            CURLOPT_ENCODING => 'gzip,deflate',
            CURLOPT_SSL_VERIFYHOST => false,
            CURLOPT_SSL_VERIFYPEER => false,
        );
        foreach ($opt as $k => $v) {
            self::$curl_opt[$k] = $v;
        }
    }

    /**
     * fetch::get('http://www.google.com/');
     * fetch::post('http://www.google.com/', array('name'=>'foo'));.
     */
    public static function __callStatic($method, $args)
    {
        if (is_null(self::$curl_opt)) {
            self::init();
        }
        @list($request, $post_data, $callback) = $args;
        if (is_callable($post_data)) {
            $callback = $post_data;
            $post_data = null;
        }

        //single_curl
        if (is_string($request) || !empty($request['url'])) {
            $request = self::bulid_request($request, $method, $post_data, $callback);

            return self::single_curl($request);
        } elseif (is_array($request)) {
            //rolling_curl
            foreach ($request as $k => $r) {
                $requests[$k] = self::bulid_request($r, $method, $post_data, $callback);
            }

            return self::rolling_curl($requests);
        }
    }

    private static function bulid_request($request, $method = 'GET', $post_data = null, $callback = null)
    {
        //url
        if (is_string($request)) {
            $request = array('url' => $request);
        }
        empty($request['method']) && $request['method'] = $method;
        empty($request['post_data']) && $request['post_data'] = $post_data;
        empty($request['callback']) && $request['callback'] = $callback;

        return $request;
    }

    private static function bulid_ch(&$request)
    {
        // url
        $ch = curl_init($request['url']);
        // curl_opt
        $curl_opt = empty($request['curl_opt']) ? array() : $request['curl_opt'];
        $curl_opt = $curl_opt + (array) self::$curl_opt;
        // method
        $curl_opt[CURLOPT_CUSTOMREQUEST] = strtoupper($request['method']);
        // post_data
        if (!empty($request['post_data'])) {
            $curl_opt[CURLOPT_POST] = true;
            $curl_opt[CURLOPT_POSTFIELDS] = $request['post_data'];
        }
        // header
        $headers = @self::bulid_request_header($request['headers'], $cookies);
        $curl_opt[CURLOPT_HTTPHEADER] = $headers;

        // cookies
        $request['cookies'] = empty($request['cookies']) ? fetch::$cookies : $request['cookies'];
        $cookies = empty($request['cookies']) ? $cookies : self::cookies_arr2str($request['cookies']);
        if (!empty($cookies)) {
            $curl_opt[CURLOPT_COOKIE] = $cookies;
        }

        //proxy
        $proxy = empty($request['proxy']) ? self::$proxy : $request['proxy'];
        if (!empty($proxy)) {
            $curl_opt[CURLOPT_PROXY] = $proxy;
        }

        //setopt
        curl_setopt_array($ch, $curl_opt);

        $request['curl_opt'] = $curl_opt;
        $request['ch'] = $ch;

        return $ch;
    }

    private static function response($raw, $ch)
    {
        $response = (object) curl_getinfo($ch);
        $response->raw = $raw;
        //$raw = fetch::iconv($raw, $response->content_type);
        $response->headers = substr($raw, 0, $response->header_size);
        $response->cookies = fetch::get_respone_cookies($response->headers);
        fetch::$cookies = array_merge((array) fetch::$cookies, $response->cookies);
        $response->content = substr($raw, $response->header_size);

        return $response;
    }

    private static function single_curl($request)
    {
        $ch = self::bulid_ch($request);
        $raw = curl_exec($ch);
        $response = self::response($raw, $ch);
        curl_close($ch);
        if (is_callable($request['callback'])) {
            call_user_func($request['callback'], $response, $request);
        }

        return $response;
    }

    private static function rolling_curl($requests)
    {
        $master = curl_multi_init();
        $map = array();
        // start the first batch of requests
        do {
            $k = key($requests);
            $request = current($requests);
            next($requests);
            $ch = self::bulid_ch($request);
            curl_multi_add_handle($master, $ch);
            $key = (string) $ch;
            $map[$key] = array($k, $request['callback']);
        } while (count($map) < self::$max_connect && count($map) < count($requests));

        do {
            while (($execrun = curl_multi_exec($master, $running)) == CURLM_CALL_MULTI_PERFORM);
            if ($execrun != CURLM_OK) {
                break;
            }

            // a request was just completed -- find out which one
            while ($done = curl_multi_info_read($master)) {
                $key = (string) $done['handle'];

                list($k, $callback) = $map[$key];

                // get the info and content returned on the request
                $raw = curl_multi_getcontent($done['handle']);
                $response = self::response($raw, $done['handle']);
                $responses[$k] = $response;

                // send the return values to the callback function.
                if (is_callable($callback)) {
                    $key = (string) $done['handle'];
                    unset($map[$key]);
                    call_user_func($callback, $response, $requests[$k], $k);
                }

                // start a new request (it's important to do this before removing the old one)
                $k = key($requests);
                if (!empty($k)) {
                    $k = key($requests);
                    $request = current($requests);
                    next($requests);
                    $ch = self::bulid_ch($request);
                    curl_multi_add_handle($master, $ch);
                    $key = (string) $ch;
                    $map[$key] = array($k, $request['callback']);
                    curl_multi_exec($master, $running);
                }

                // remove the curl handle that just completed
                curl_multi_remove_handle($master, $done['handle']);
            }

            // Block for data in / output; error handling is done by curl_multi_exec
            if ($running) {
                curl_multi_select($master, 10);
            }
        } while ($running);

        return $responses;
    }

    private static function bulid_request_header($headers, &$cookies)
    {
        if (is_array($headers)) {
            $headers = join(PHP_EOL, $headers);
        }
        if (is_array(self::$headers)) {
            self::$headers = join(PHP_EOL, self::$headers);
        }
        $headers = self::$headers.PHP_EOL.$headers;

        foreach (explode(PHP_EOL, $headers) as $k => $v) {
            @list($k, $v) = explode(':', $v, 2);
            if (empty($k) || empty($v)) {
                continue;
            }
            $k = implode('-', array_map('ucfirst', explode('-', $k)));
            $tmp[$k] = $v;
        }

        foreach ((array) $tmp as $k => $v) {
            if ($k == 'Cookie') {
                $cookies = $v;
            } else {
                $return[] = $k.':'.$v;
            }
        }

        return (array) $return;
    }

    public static function iconv(&$raw, $content_type)
    {
        @list($tmp, $charset) = explode('CHARSET=', strtoupper($content_type));

        if (empty($charset) && stripos($content_type, 'html') > 0) {
            preg_match('@\<meta.+?charset=([\w]+)[\'|\"]@i', $raw, $matches);
            $charset = empty($matches[1]) ? null : $matches[1];
        }

        return empty($charset) ? $raw : iconv($charset, 'UTF-8//IGNORE', $raw);
    }

    public static function get_respone_cookies($raw)
    {
        $cookies = array();
        if (strpos($raw, PHP_EOL) != false) {
            $lines = explode(PHP_EOL, $raw);
        } elseif (strpos($raw, "\r\n") != false) {
            $lines = explode("\r\n", $raw);
        } elseif (strpos($raw, '\r\n') != false) {
            $lines = explode('\r\n', $raw);
        }

        foreach ((array) $lines as $line) {
            if (substr($line, 0, 11) == 'Set-Cookie:') {
                list($k, $v) = explode('=', substr($line, 11), 2);
                list($v, $tmp) = explode(';', $v);
                $cookies[trim($k)] = trim($v);
            }
        }

        return $cookies;
    }

    public static function cookies_arr2str($arr)
    {
        $str = '';
        foreach ((array) $arr as $k => $v) {
            $str .= $k.'='.$v.'; ';
        }

        return $str;
    }
}
`
会获取到 https://microsoftgraph.chinacloudapi.cn/v1.0/sites/alphaone.sharepoint.cn,a0031d38-3ee4-4e22-87e3-c5ca1825419a,eda2d4bf-9dd2-4703-a606-5ff84bbd1c5b/drive/
添加到存储策略高级设置到servre里  如果使用onedrive 填写https://microsoftgraph.chinacloudapi.cn/v1.0/me/drive/

本人不会reactjs  所以前端配置向导我就懒得改了;

**Comment by 742481030** [comment]
if dst == "" {
		requestURL = client.getRequestURL("**me/drive/**root/children")
	} else {
		requestURL = client.getRequestURL("**me/drive/**root:/" + dst + ":/children")

**Comment by 742481030** [comment]
// Meta 根据资源ID或文件路径获取文件元信息
func (client *Client) Meta(ctx context.Context, id string, path string) (*FileInfo, error) {
	var requestURL string
	if id != "" {
		requestURL = client.getRequestURL("**/me/drive/**items/" + id)
	} else {
		dst := strings.TrimPrefix(path, "/")
		requestURL = client.getRequestURL("**me/drive/**root:/" + dst)
	}

	res, err := client.requestWithStr(ctx, "GET", requestURL+"?expa

**Comment by toyay87935** [comment]
多个sites怎么加啊

**Comment by 742481030** [comment]
@toyay87935 重复添加onedrive 后 修改高级配置
