### ISSUE TITLE
文件未上传成功提示上传成功

### ISSUE THREAD

**Issue by CeeIM** [cloudreve/Cloudreve#408]
![image](https://user-images.githubusercontent.com/18570103/82754612-9843f300-9e00-11ea-819c-5cb37942fb45.png)

使用又拍云存储策略，为了避免物理文件重名加了 {datetime} 文件夹，按逻辑上传同名文件应该返回错误，但是上传读条结束后直接已完成了，储存库里除了第一个上传的文件之外后来上传的同名文件均未上传，但有创建 {datetime} 文件夹，目录下为空。

根据目前的规则，默认保留了第一个上传文件，如果上传同名文件应该被丢弃了，是否能根据这个逻辑更改为保留最新上传的同名文件？覆盖或是删除之前留下的同名文件达到更新的效果。因为有的文件改动了就直接整个文件夹上传了，如果要事先删除这些文件再上传有点不方便。

最完美的方式我觉得是像我之前的 [Issues](https://github.com/cloudreve/Cloudreve/issues/386) 里有提到，上传同名文件直接更名带编号的版本，来实现多版本共存？

**Comment by HFO4** [comment]
因为又拍云是异步回调，客户端上传时无法获知回调结果，只能展现为已完成。

**Comment by ceecx** [comment]
@HFO4 那上述功能有可能实现吗？

**Comment by HFO4** [comment]
> @HFO4 那上述功能有可能实现吗？

后续会在上传前检查重名、文件大小

**Comment by ceecx** [comment]
> > @HFO4 那上述功能有可能实现吗？
> 
> 后续会在上传前检查重名、文件大小

如果能选择是否保留目前版本（重名文件）并重新命名就更好了，希望能有更好的方案。
