### ISSUE TITLE
3.1版本上传文件后无法立即更新文件列表以及一点建议

### ISSUE THREAD

**Issue by jcx70100** [cloudreve/Cloudreve#409]
* Cloudreve版本
> v 3.1
* 问题描述

> 上传文件/新建文件夹后，无法立即看到上传或新建的文件，需要等待大约5min左右才能在文件列表看到上传的文件；

> 是否会和vps速度有关系？或者访问onedrive的速度有关呢。

* 遇到该问题时的其他操作
1. 本次是在全新的vps上全新安装的3.0版本，后来发现3.1版本已发布，就立即更新了，于是遇到了上述上传文件后不能立即看到文件的问题；
2. 配置过程中加了mysql和redius配置，并修改了端口，依然出现上出问题；
3. 最后在vps上删掉原先的文件，重新下载了3.1版本的进行安装，所有都是默认配置，只修改了端口，还是出现上传文件不能立即显示的问题。

* 其他信息
1. 系统` Centos x64`
2. 存储策略： `Onedrive for business`

* 一点点建议和其他问题
1. 上传文件列表可否添加“**清空已完成**”的按钮，很多情况下需要使用文件夹上传，文件很多，导致上传列表拉的很长，每次想看最新的上传进度都需要在上传列表内滚动鼠标跨国已经上传完成的部分；
2. 上传失败的时候可以增加**手动重新长传**的按钮，这个问题同样是针对文件夹上传，如果个别文件上传失败，还需要找到失败的文件，再将文件重新上传到相应的文件夹内，很不方便；
3. 在macOS系统里面，`shift`功能仅对文件\文件夹有效，如果想`shift`选中的文件段中同时存在文件夹和文件，那么`shift`功能将失效，只能通过`command`（功能同win下的`control`）进行一个一个选择；该问题在windows下测试也存在`shift`不能同时选中文件和文件夹区段；
4. 文件（夹）不能进行`拖拽移动`（windows和macOS下都不行）

**Comment by 742481030** [comment]
在macOS系统里面，shift功能仅对文件\文件夹有效，如果想shift选中的文件段中同时存在文件夹和文件，那么shift功能将失效，只能通过command（功能同win下的control）进行一个一个选择；该问题在windows下测试也存在shift不能同时选中文件和文件夹区段；

**Comment by 742481030** [comment]
我测试了 shift 是正常的

**Comment by jcx70100** [comment]
您好哈，昨晚重置了vps重新安装了一下，之前是用宝塔面板安装的，这次直接安装的lnmp进行配置，没有出现上述问题，看来是我这边配置有些问题，目前都解决了呢，十分感谢哈。
