### ISSUE TITLE
PDF无法预览

### ISSUE THREAD

**Issue by NorthCityChen** [cloudreve/Cloudreve#410]
使用七牛云存储的PDF无法预览

![image](https://user-images.githubusercontent.com/53619621/82810257-93467880-9ec0-11ea-8775-029a51f89149.png)

**Comment by HFO4** [comment]
能否提供开发者工具中更多错误信息？

**Comment by NorthCityChen** [comment]
![image](https://user-images.githubusercontent.com/53619621/82858475-9421ed80-9f46-11ea-83cc-7b1272e7defb.png)
这个bug只在电脑端复现（chrome），手机端无bug

**Comment by HFO4** [comment]
七牛那边的域名需要启用SSL
