### ISSUE TITLE
希望为Cloudreve添加子目录（二级目录）支持

### ISSUE THREAD

**Issue by fxzxmic** [cloudreve/Cloudreve#411]
我在使用Apache进行反代时发现，Cloudreve不支持子目录使用，我的反代配置为：
```
   <IfModule mod_proxy.c>
    ProxyRequests on
    SSLProxyEngine on
    AllowEncodedSlashes NoDecode
    ProxyPass /disk/ http://127.0.0.1:5212/ nocanon
    ProxyPassReverse /disk/ http://127.0.0.1:5212/ nocanon
    </IfModule>
```
我不知道我的配置是否存在问题，所有的静态资源文件包括前端向后端的API调用均会出现404错误，而我查看首页的script引用是这样的：

`<script src="/static/js/6.4b50c196.chunk.js"></script>`

是一个绝对地址，而我是在子目录使用的，所以这个文件当然不存在，而将其修改为：

`<script src="./static/js/6.4b50c196.chunk.js"></script>`

这样的相对地址后，是可以正常获取文件的，而这样的写法在某些时候可能存在问题，但是我想作者应该有办法解决。

**Comment by HFO4** [comment]
需要变更太多而且支持二级目录没有太大意义，暂时不考虑

**Comment by fxzxmic** [comment]
可以有一种最简单的实现方法就是在配置文件中加入程序的运行目录，使用户在安装时手动配置，让程序可以在 `http://127.0.0.1:5212/pan/`这样的目录中运行，而在程序中只用在路径前加入配置文件中的这一变量即可。我想一个功能做出来以后总会有人找到它的新用法。
现在考虑程序在二级目录的人越来越少了，结果导致每上线一个功能就得分配一个域名，功能多了，几十个域名就出去了，而且分散了权重，有的时候还得考虑跨域的问题。

**Comment by hiCasper** [comment]
> 可以有一种最简单的实现方法就是在配置文件中加入程序的运行目录，使用户在安装时手动配置，让程序可以在 `http://127.0.0.1:5212/pan/`这样的目录中运行，而在程序中只用在路径前加入配置文件中的这一变量即可。我想一个功能做出来以后总会有人找到它的新用法。
> 现在考虑程序在二级目录的人越来越少了，结果导致每上线一个功能就得分配一个域名，功能多了，几十个域名就出去了，而且分散了权重，有的时候还得考虑跨域的问题。

这个不是配置文件就能决定的，Cloudreve用到的react-router决定了路由模式，改成支持二级目录需要进行大量改动，还会出现各种未知bug，并且没有太大意义，所以不考虑。

当然，如果你有能力提供解决方案，PR Welcome.
