### ISSUE TITLE
建议增加原生 HTTP 跳转 HTTPS

### ISSUE THREAD

**Issue by ceecx** [cloudreve/Cloudreve#416]
目前新增了 HTTPS 原生支持应该是为了朝更便捷的方向发展，默认用户输入网址都不会带 https:// 前缀，配置了证书默认访问的还是 HTTP 就很尬，还需要进行反代跳转到 HTTPS，没法完全摆脱前端反代的痛点，如果能加个跳转就完美了。

不懂 Golang，查了一下好像有第三方包可以参考：
https://github.com/unrolled/secure

**Comment by HFO4** [comment]
内置Web服务器尽量从简，暂不考虑支持
