### ISSUE TITLE
cd无法上传大文件

### ISSUE THREAD

**Issue by liubangjain** [cloudreve/Cloudreve#426]
大佬你好
我用群晖运行https://hub.docker.com/r/xavierniu/cloudreve大佬的docker，运行的是OC模式，存储策略用的是世纪互联的onedrive；可以上传比较小的文件，例如txt文件或者几兆的exe文件，但是上传大概40-50m的rar文件，就提示上传失败，而我去到OneDrive的网页版看到该文件是上传成功的，但是在cloudreve上提示上传失败，而且不显示。conf.ini文件没有任何数据。请问是什么原因？请问怎么解决？期待你的回复。

**Comment by henrywu19359** [comment]
看上去你需要检查一下Nginx的MAX-BODY-SIZE的配置是否限制了上传大小。

**Comment by liubangjain** [comment]
问了镜像作者，这个镜像是完全纯净的，没有使用nginx。我也是使用192...局域网来访问，并未设置反代理。

**Comment by liubangjain** [comment]
我试了国际版和世纪互联版的OD情况都一样。

**Comment by henrywu19359** [comment]
貌似小文件走的是服务器中转，大文件是直传。这样的话我猜测内网IP会不会是回调出现了问题。OneDrive我记得是需要HTTPS才能正常收到回调信息的。

**Comment by liubangjain** [comment]
> 貌似小文件走的是服务器中转，大文件是直传。这样的话我猜测内网IP会不会是回调出现了问题。OneDrive我记得是需要HTTPS才能正常收到回调信息的。

解决了，谢谢。
