### ISSUE TITLE
建议创建下载链接的时候根据文件大小扣除对应积分

### ISSUE THREAD

**Issue by LUODIAN-233** [cloudreve/Cloudreve#430]
对于商业人群来说,若个别注册用户只为了快速分享自己的文件，购买了小型存储包，随后上传文件后进行账号共享，以10GB大小为例;若存储方式为阿里云OSS的话，账号每共享给一个人就要亏损大概3元，就算对用户进行限速，也不过是用户下载时长的问题

若此方法行不通也希望能够添加一个限制下载的功能

**Comment by cha0sCat** [comment]
对于商业人群来说，这些成本都应该均摊到套餐里，而不是用这种扣扣搜搜的方式计费

**Comment by LUODIAN-233** [comment]
> 对于商业人群来说，这些成本都应该均摊到套餐里，而不是用这种扣扣搜搜的方式收费

若以均摊的方式，会让正常用户的成本升高，谁都无法保证用户上传后只下载固定的次数或不下载

**Comment by 2498981627** [comment]
你这东西只有你自己用，怎么可能会给你单独造一个轮子？
这种属于商业版二开，又不属于作者的义务范围。你要这么做那你只能自己找人改。

**Comment by Yuelioi** [comment]
> 你这东西只有你自己用，怎么可能会给你单独造一个轮子？
> 这种属于商业版二开，又不属于作者的义务范围。你要这么做那你只能自己找人改。

可是买PRO不就是为了商用么，不然用社区版不就够了么。
本身打着旗号就是可以对接各大平台，但现实就是各大平台都是按流量计费的。
