### ISSUE TITLE
向网盘提几点建议

### ISSUE THREAD

**Issue by pmkol** [cloudreve/Cloudreve#431]
首先感谢作者的劳动，这个网盘go lang重构后，是我见过最好用的开源网盘之一，无论是性能、部署还是功能的简洁。希望这个网盘能有更多的人使用，给出几点建议：

1、文件夹共享功能
我在论坛提过这个功能，将一个文件夹同时共享给多个用户，为共享用户设置分组，只读/读写，并在用户自己的网盘中可以看见共享文件夹；

2、共享搜索
用户可以搜索文件，包含共享的文件，基于elasticseach或许是个不错的选择；

3、文件版本历史
管理员可以选择是否开启，有助多用户协作，同时也能防止用户个人误操作，可以挽回；

4、回收站
防止误删，可以设置最多保存天数；

以上四个功能，均可以放在付费版中，有了这4个功能，会有不少团队在内网环境下使用这个网盘，至少在我身边很多团队、小企业，因为购买不起价格高昂的企业网盘，对这里有需求，希望作者能在近几个版本考虑加入。

**Comment by 742481030** [comment]
onedriver 自带2级回收站和文件版本

**Comment by ceecx** [comment]
文件版本是很好的选项，我也提过，按目前的逻辑是可以实现的，但作者没意向，还是不太方便转正使用。

**Comment by hushisishao** [comment]
为了防止误删除，我把应用存文件的目录权限设置为了禁止删除😂。。。

**Comment by longzhang83** [comment]
> 首先感谢作者的劳动，这个网盘go lang重构后，是我见过最好用的开源网盘之一，无论是性能、部署还是功能的简洁。希望这个网盘能有更多的人使用，给出几点建议：
> 
> 1、文件夹共享功能 我在论坛提过这个功能，将一个文件夹同时共享给多个用户，为共享用户设置分组，只读/读写，并在用户自己的网盘中可以看见共享文件夹；
> 
> 2、共享搜索 用户可以搜索文件，包含共享的文件，基于elasticseach或许是个不错的选择；
> 
> 3、文件版本历史 管理员可以选择是否开启，有助多用户协作，同时也能防止用户个人误操作，可以挽回；
> 
> 4、回收站 防止误删，可以设置最多保存天数；
> 
> 以上四个功能，均可以放在付费版中，有了这4个功能，会有不少团队在内网环境下使用这个网盘，至少在我身边很多团队、小企业，因为购买不起价格高昂的企业网盘，对这里有需求，希望作者能在近几个版本考虑加入。

这个几个需求  加上， 基本达到商业网盘的效果了
