### ISSUE TITLE
建议在文件列表中新增上级目录

### ISSUE THREAD

**Issue by zzd** [cloudreve/Cloudreve#434]
在文件目录如果要返回上级，必须要点击面包屑导航，不是很方便，可以在文件目录中直接加入上级目录，以适应使用习惯。如图
![image](https://user-images.githubusercontent.com/45026982/83412884-7d4f2f80-a44d-11ea-8076-2859f84a749e.png)

**Comment by HFO4** [comment]
可以直接使用浏览器级别后退返回

**Comment by zzd** [comment]
OK，我只是觉得加上体验会更好，可以提供可选项。
