### ISSUE TITLE
【建议】文件和文件夹右键菜单添加属性功能

### ISSUE THREAD

**Issue by Beattheend** [cloudreve/Cloudreve#436]
![提议](https://user-images.githubusercontent.com/64207250/83417819-35cca180-a455-11ea-8822-cc00eddb2d5d.png)

发现面板右键菜单中没属性功能，无法查看文件或文件夹的属性（比如无法查看一个文件夹下包含了几个文件夹和几个文件，它们的修改时间，文件夹大小，等）

提议：
在文件或文件夹右键面板上添加【属性】菜单以方便查看类型（目录或xx文件？）丶大小（包括文件夹内全部文件）丶位置丶包含（几个文件夹，几个文件）丶修改时间（文件或文件夹）

已有功能可不加入。

**Comment by HFO4** [comment]
之前考虑过(#341)，目前可展示的属性信息极其有限，还不足以支撑单独的“属性”面板

**Comment by Mmxp** [comment]
事啊，其实属性的主要作用就是看一下大小。。别的数据又没多大用处
