### ISSUE TITLE
【建议】使用QQ登录或外部验证器登录时不要绕过二步验证

### ISSUE THREAD

**Issue by callng** [cloudreve/Cloudreve#437]
如标题所示。目前二步验证只局限于使用账号密码登录的方式而触发，但使用QQ或外部验证器登录时不触发（外部验证器也就算了）QQ登录为什么也绕过了二步验证？如开启了二步验证则任何登录方式也不要绕过二步验证。

**Comment by 742481030** [comment]
你想想就知道了

**Comment by cchins** [comment]
这是实话
