### ISSUE TITLE
纠正一个语文错误

### ISSUE THREAD

**Issue by XZB-1248** [cloudreve/Cloudreve#438]
![image](https://user-images.githubusercontent.com/28593573/83469824-46ac0000-a4b3-11ea-99b1-2223f5451248.png)
![image](https://user-images.githubusercontent.com/28593573/83469849-562b4900-a4b3-11ea-8045-e3c7dbca385d.png)
WebDav界面的"登陆"应改成"登录"。

**Comment by 2498981627** [comment]
虽然问题不大，但是还是建议严谨一点。

**Comment by ericdonthavebug** [comment]
看的懂就可以了啊.......

**Comment by XZB-1248** [comment]
> 看的懂就可以了啊.......

你觉得你的网站出现语文错误用户会怎么看？还是这样很基础的错误。再说了，就改两个字的事，要花多久？
