### ISSUE TITLE
目标名称非法

### ISSUE THREAD

**Issue by qqdaiyu55** [cloudreve/Cloudreve#441]
**System**: Windows 10 1909
**Version**: cloudreve_3.1.1_windows_amd64
**File name**: Everything you need to know about ng-template, ng-content, ng-container, and *ngTemplateOutlet in Angular.webloc
**File Extension**: .webloc
**Error Info**: 目标名称非法
**Screenshot**: ![](https://tva1.sinaimg.cn/large/007S8ZIlly1gfe4igz4u2j30x008s75d.jpg)

**Comment by hiCasper** [comment]
文件名不应含有*号，修改后即可。
