### ISSUE TITLE
webdav不能自定义登录密码

### ISSUE THREAD

**Issue by brianler** [cloudreve/Cloudreve#444]
webdav不能自定义登录密码

**Comment by brianler** [comment]
为什么？

**Comment by 742481030** [comment]
你可以数据库直接改

**Comment by brianler** [comment]
> 你可以数据库直接改

好办法

**Comment by brianler** [comment]
通过SQLite相关的GUI程序（如：https://github.com/sqlitebrowser/sqlitebrowser），可以打开cloudreve.db，查看和修改相关数据，包括WebDAV的密码。
