### ISSUE TITLE
使用word查看功能，涉及端口问题

### ISSUE THREAD

**Issue by 3772702** [cloudreve/Cloudreve#445]
使用word查看功能，涉及端口问题，云主机安全组，流入全端口全放开后功能可用，限制端口后功能就不可用了。word查看这功能用到了哪个端口？

**Comment by 742481030** [comment]
8080

**Comment by 3772702** [comment]
> 8080

不是8080  无效

**Comment by hiCasper** [comment]
应该和Cloudreve同端口

**Comment by 3772702** [comment]
> 应该和Cloudreve同端口

也不是 5212

**Comment by cha0sCat** [comment]
你自己F12看看不就知道了
