### ISSUE TITLE
请问Cloudreve如何反代onedrive?

### ISSUE THREAD

**Issue by long1215** [cloudreve/Cloudreve#447]
Cloudreve是用caddy反代，存储是onedrive直联太慢了。想让onedrive走服务器流量

**Comment by 742481030** [comment]
编译源代码 正则替换sharepont .com  然后nginx 反向代理

**Comment by long1215** [comment]
> 编译源代码 正则替换sharepont .com 然后nginx 反向代理

感谢指点，我试下

**Comment by henrywu19359** [comment]
也可以尝试直接Rclone挂载到本地然后用本地存储
