### ISSUE TITLE
Aliyun OSS Cloudflare SSL 回调失败

### ISSUE THREAD

**Issue by Anankke** [cloudreve/cloudreve#448]
在同时使用阿里云 OSS 和 Cloudflare 的时候，由于阿里云 OSS 莫名其妙的回调请求跟 Cloudflare 的 SSL 合不来导致回调失败，文件已上传但是未显示在 Cloudreve 的问题。

推荐添加设置项回调地址，这样就可以让 OSS 回调绕过 Cloudflare 的 SSL，同时能维持全站 https。

**Comment by 742481030** [comment]
这网盘前端就是静态文件编译后放cdn 就行了, Cloudflare  太慢了

**Comment by Anankke** [comment]
企业级用户笑而不语（

**Comment by henrywu19359** [comment]
可以考虑自己申请一张别的证书替换掉Cloudflare 的SSL？

**Comment by Anankke** [comment]
并不是因为证书的问题导致 SSL 握手失败的，Cloudflare 默认都是 ECDSA 和 RSA 的双证书。
![image](https://user-images.githubusercontent.com/40639066/83880866-d9e07200-a70d-11ea-8084-0374c96b5496.png)

**Comment by cjs520** [comment]
为啥不在阿里申请证书？？？

**Comment by Anankke** [comment]
> 为啥不在阿里申请证书？？？
为啥要在阿里申请证书？为啥要申请证书？

**Comment by cjs520** [comment]
和Cloudflare 的 SSL 合不来，用阿里的咯

**Comment by Anankke** [comment]
建议亲注册个账号再云。

**Comment by Hope-you** [comment]
> 在同时使用阿里云 OSS 和 Cloudflare 的时候，由于阿里云 OSS 莫名其妙的回调请求跟 Cloudflare 的 SSL 合不来导致回调失败，文件已上传但是未显示在 Cloudreve 的问题。
> 
> 推荐添加设置项回调地址，这样就可以让 OSS 回调绕过 Cloudflare 的 SSL，同时能维持全站 https。

跟你遇到了同样的问题，上传文件提示"上传失败(203：Error status : 502.)"请问大佬解决了吗？

**Comment by Anankke** [comment]
> > 在同时使用阿里云 OSS 和 Cloudflare 的时候，由于阿里云 OSS 莫名其妙的回调请求跟 Cloudflare 的 SSL 合不来导致回调失败，文件已上传但是未显示在 Cloudreve 的问题。
> > 推荐添加设置项回调地址，这样就可以让 OSS 回调绕过 Cloudflare 的 SSL，同时能维持全站 https。
> 
> 跟你遇到了同样的问题，上传文件提示"上传失败(203：Error status : 502.)"请问大佬解决了吗？

我的解决办法是同时开放 80/443，首先将域名加入 HSTS Preload List，然后服务端通过 UA/请求路径 判断是否为回调请求，如果是浏览器请求则会 301 至 https 并下发 HSTS 策略，如果是回调请求则 80 放行回调请求。

**Comment by Hope-you** [comment]
> > > 在同时使用阿里云 OSS 和 Cloudflare 的时候，由于阿里云 OSS 莫名其妙的回调请求跟 Cloudflare 的 SSL 合不来导致回调失败，文件已上传但是未显示在 Cloudreve 的问题。
> > > 推荐添加设置项回调地址，这样就可以让 OSS 回调绕过 Cloudflare 的 SSL，同时能维持全站 https。
> > 
> > 
> > 跟你遇到了同样的问题，上传文件提示"上传失败(203：Error status : 502.)"请问大佬解决了吗？
> 
> 我的解决办法是同时开放 80/443，首先将域名加入 HSTS Preload List，然后服务端通过 UA/请求路径 判断是否为回调请求，如果是浏览器请求则会 301 至 https 并下发 HSTS 策略，如果是回调请求则 80 放行回调请求。

大佬有时间贴份配置借我参考参考，非常感谢啦。

**Comment by tempurai** [comment]
这个问题依旧存在，解决方法误解，我给 oss 新开了个域名不走 cdn

**Comment by liqiujiong** [comment]
阿里云OSS这个回调问题依旧存在，我的使用Let's Encrypt证书，回调地址如果是https 的完全都收不到阿里云回调请求，直接报错502. 得改为http才可以了。

根本原因是：阿里云OSS回调请求客户端不支持SNI
https://lihuaio.com/tech/oss/
