### ISSUE TITLE
备案号功能超链接存在问题

### ISSUE THREAD

**Issue by syf2005** [cloudreve/Cloudreve#449]
http://www.beian.miit.gov.cn/是ICP备案链接，现在是错的
http://www.beian.gov.cn/portal/registerSystemInfo是公安网备链接
建议把这两个号都加上，分开设置

**Comment by Beattheend** [comment]
@

> [http://www.beian.miit.gov.cn/是ICP备案链接，现在是错的](http://www.beian.miit.gov.cn/%E6%98%AFICP%E5%A4%87%E6%A1%88%E9%93%BE%E6%8E%A5%EF%BC%8C%E7%8E%B0%E5%9C%A8%E6%98%AF%E9%94%99%E7%9A%84)
> [http://www.beian.gov.cn/portal/registerSystemInfo是公安网备链接](http://www.beian.gov.cn/portal/registerSystemInfo%E6%98%AF%E5%85%AC%E5%AE%89%E7%BD%91%E5%A4%87%E9%93%BE%E6%8E%A5)
> 建议把这两个号都加上，分开设置

这个问题已经知晓了，下个版本会改正，如果你急需，请知晓修改前端代码文件。
