### ISSUE TITLE
获取文件外链中链接好像有问题

### ISSUE THREAD

**Issue by TheresaQWQ** [cloudreve/Cloudreve#451]
![image](https://user-images.githubusercontent.com/22370654/83942735-e2799b00-a828-11ea-8e00-edda92f96cb9.png)
/也被Url编码了，这里直接访问这个链接会404

**Comment by HFO4** [comment]
请问这是什么存储策略？

**Comment by TheresaQWQ** [comment]
> 请问这是什么存储策略？

又拍云

**Comment by HFO4** [comment]
经测试，编码路径分隔符`/`后不影响正常访问，如果有后续 update 欢迎 Reopen 这个 issue
