### ISSUE TITLE
内网部署的office预览问题

### ISSUE THREAD

**Issue by cdszy2010** [cloudreve/Cloudreve#455]
在内网部署的cloundreve，由于不能访问互联网，无法预览office，提示“找不到view.officeapps.live.com”的服务器ip地址。不知道大家有没有在内网部署的，是否也有这个问题，作者后期是否有对office预览的离线支持？

**Comment by hiCasper** [comment]
在线预览使用的是由 Microsoft Office 提供的在线服务，不部署在公网则无法使用。

对于内网部署的情况下，可以参照 [官方指南](https://docs.microsoft.com/zh-cn/webappsserver/deploy-office-web-apps-server) 及 [相关教程](https://www.jianshu.com/p/d58c720b6990) 的指示，在内网部署 Office Web Apps Server 后，将 [此处](https://github.com/cloudreve/Cloudreve/blob/58856612e2c1e7ee3013dc7b89fe11ed08bca5d2/service/explorer/file.go#L222) 的地址修改为内网 Office Web Apps Server 的地址即可实现。

**Comment by cdszy2010** [comment]
非常感谢
