### ISSUE TITLE
[bug]webdev功能似乎有问题，使用potplayer连接后出现异常

### ISSUE THREAD

**Issue by shadowfish07** [cloudreve/Cloudreve#456]
![image](https://user-images.githubusercontent.com/38303418/84059091-9ecf8e80-a9ec-11ea-9119-4444d711bacc.png)
如图，连接成功后只显示出了文件，且文件也都显示异常，而如果我使用坚果云提供的webdev功能是可以正常列出文件列表的，因此应该不是potplayer的问题。
下面是我的根目录：
![image](https://user-images.githubusercontent.com/38303418/84059321-fe2d9e80-a9ec-11ea-9b78-924a617ab871.png)

**Comment by littlewhitelyw** [comment]
借楼，谢了
问题：win7系统的映射网络驱动器添加不了Cloudreve的webdav。
额外信息：
1、win7系统正常添加坚果云网盘的webdav
2、win10系统正常添加Cloudreve的webdav
不太懂webdav，不知道这里面是否存在兼容性问题

**Comment by xdeng** [comment]
> 借楼，谢了
> 问题：win7系统的映射网络驱动器添加不了Cloudreve的webdav。
> 额外信息：
> 1、win7系统正常添加坚果云网盘的webdav
> 2、win10系统正常添加Cloudreve的webdav
> 不太懂webdav，不知道这里面是否存在兼容性问题

我跟你的差不多的问题，我的win7曾经有成功过，之后就一直失败了，还会造成桌面重启，同样的账号密码地址在win10是成功的。 我怀疑的是不是https用的http2 win7支持比较差的原因。

**Comment by xdeng** [comment]
win7 用RaiDrive挂载好像就没事。

**Comment by HFO4** [comment]
Potplayer 的 WebDAV 设定似乎无法在连接前指定二级目录 `/dav`，所以导致连接不上，目前没有较好的解决办法。
