### ISSUE TITLE
加入 Vditor 作为 md 编辑器

### ISSUE THREAD

**Issue by JackalZhao** [cloudreve/Cloudreve#459]
[Vditor](https://vditor.b3log.org/) 是国人开发者 D 做的基于网页端的 md 编辑器，开源，可以考虑加入 cloudreve，作为 md 文件的编辑器和查看器。

基于 Vditor 的例子：

https://markdown.lovejade.cn/ 

https://hacpai.com/guide/markdown

**Comment by HFO4** [comment]
目前还没必要更换 Markdown 编辑器。
