### ISSUE TITLE
【bug】外部认证器认证有问题

### ISSUE THREAD

**Issue by XZB-1248** [cloudreve/Cloudreve#460]
![TIM截图20200610222229](https://user-images.githubusercontent.com/28593573/84279854-1b877780-ab69-11ea-9ad2-47b55d2e99a6.jpg)
![TIM截图20200610222242](https://user-images.githubusercontent.com/28593573/84279883-22ae8580-ab69-11ea-9b41-f04e58d0a127.jpg)
![TIM截图20200610222308](https://user-images.githubusercontent.com/28593573/84279894-27733980-ab69-11ea-8352-8a9216dd8145.jpg)
![TIM截图20200610222617](https://user-images.githubusercontent.com/28593573/84280105-6ef9c580-ab69-11ea-8257-dcbd95a8ab2a.jpg)

如图，添加认证器使用的是Windows Hello的指纹识别，但是登录的时候只能调起USB安全密钥。
也就是说，添加了指纹认证的验证方式之后，登录的时候却不能使用指纹。

**Comment by HFO4** [comment]
方便透露下使用的认证设备型号吗？

**Comment by imnpc** [comment]
> 方便透露下使用的认证设备型号吗？

我在使用PHP的webauthn库的时候看到过好像windows hello 认证支持的时候要单独设置参数？
[https://github.com/davidearl/webauthn/blob/master/WebAuthn/WebAuthn.php](https://github.com/davidearl/webauthn/blob/master/WebAuthn/WebAuthn.php)

**Comment by XZB-1248** [comment]
> 方便透露下使用的认证设备型号吗？

![TIM截图20200907210813](https://user-images.githubusercontent.com/28593573/92390883-4e341280-f14e-11ea-9e48-59a0e71e2c65.png)
制造商网站：http://shenai99.com/
