### ISSUE TITLE
数据库自动备份

### ISSUE THREAD

**Issue by JackalZhao** [cloudreve/Cloudreve#464]
注意到 cloudreve 在使用内置 SQLite 数据库时，为了数据安全性，需要进行备份。

备份有两种方式：

* 手动备份
* 定时脚本自动备份

都需要一定的动手能力，且需要访问外部空间，才能安全备份。

否则一旦误操作或因为意外，数据库丢了，虽然文件都在七牛云等空间存着，但文件目录等信息都没了，损失还是不小。

所以建议能够在控制面板添加自动备份设置，可以设置已添加的存储空间或者 Github 为备份目标，每天定时备份，使用简单的版本控制，例如最多30个版本的备份。

**Comment by henrywu19359** [comment]
可以考虑改成MYSQL，然后用宝塔面板就可以手动或定时备份
如果用Sqlite的话可以在宝塔面板搞一个定时任务，定时将文件复制到指定目录

**Comment by JackalZhao** [comment]
> 可以考虑改成MYSQL，然后用宝塔面板就可以手动或定时备份
> 如果用Sqlite的话可以在宝塔面板搞一个定时任务，定时将文件复制到指定目录

备份方法肯定多了去了，当跨设备备份时，更需要比较复杂的步骤，这不是该 issue 的重点。

该 issue 要表达的是：你是一个成熟的云盘系统了，该学会自己备份了，别让用户为了给你的数据库备份还要折腾其他东西。
