### ISSUE TITLE
【求助】为GOARM=5编译，遇到错误

### ISSUE THREAD

**Issue by bt-worm** [cloudreve/Cloudreve#467]
**### go env输出：**
_GO111MODULE=""
GOARCH="arm"
GOBIN="/opt/repo/goproj/bin"
GOCACHE="/home/tiger/.cache/go-build"
GOENV="/home/tiger/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/opt/repo/goproj"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOARM="5"
AR="arm-brcm-linux-uclibcgnueabi-ar"
CC="arm-brcm-linux-uclibcgnueabi-gcc"
CXX="arm-brcm-linux-uclibcgnueabi-g++"
CGO_ENABLED="0"
GOMOD="/opt/repo/goproj/Cloudreve/go.mod"
CGO_CFLAGS="-I/opt/brcm/hndtools-arm-linux-2.6.36-uclibc-4.5.3/usr/include -I/opt/brcm/hndtools-arm-linux-2.6.36-uclibc-4.5.3/include"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-L/opt/brcm/hndtools-arm-linux-2.6.36-uclibc-4.5.3/lib -L/opt/brcm/hndtools-arm-linux-2.6.36-uclibc-4.5.3/usr/lib"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build311980911=/tmp/go-build"_

**### 编译错误：**
$ ./build.sh -c
_github.com/HFO4/cloudreve/routers
routers/router.go:169:31: undefined: controllers.AnonymousGetContent
routers/router.go:171:41: undefined: controllers.DownloadArchive
routers/router.go:173:30: undefined: controllers.Download
routers/router.go:450:25: undefined: controllers.FileUploadStream
routers/router.go:452:35: undefined: controllers.GetUploadCredential
routers/router.go:454:28: undefined: controllers.PutContent
routers/router.go:456:25: undefined: controllers.CreateFile
routers/router.go:458:30: undefined: controllers.CreateDownloadSession
routers/router.go:460:29: undefined: controllers.Preview
routers/router.go:462:29: undefined: controllers.PreviewText
routers/router.go:462:29: too many errors_

另，为host native平台(amd_x64)编译无问题。

**Comment by topjohncian** [comment]
启动GOMODULE
```
export GO111MODULE="on"
```

**Comment by bt-worm** [comment]
同样错误

**Comment by topjohncian** [comment]
（玄学把
之前我用cmd编就出现这个
用pwsh就正常了

**Comment by bt-worm** [comment]
疏忽了，CGO_ENABLED="0" 应该设置为1
编译通过
