### ISSUE TITLE
（系统错误）显示初始密码界面后，登录后台网址显示系统错误

### ISSUE THREAD

**Issue by Hector-cqj** [cloudreve/Cloudreve#469]
[8192]  ErrorException在Query.php线400
不建议使用带有花括号的数组和字符串偏移量访问语法
                    // 按照md5的序列分表
                    $seq = (ord(substr(md5($value), 0, 1)) % $rule['num']) + 1;
                    break;
                default:
                    if (function_exists($type)) {
                        // 支持指定函数哈希
                        $seq = (ord(substr($type($value), 0, 1)) % $rule['num']) + 1;
                    } else {
                        // 按照字段的首字母的值分表
                        $seq = (ord($value{0}) % $rule['num']) + 1;
                    }
            }
            return $this->getTable() . '_' . $seq;
        } else {
            // 当设置的分表字段不在查询条件或者数据中
            // 进行联合查询，必须设定 partition['num']
            $tableName = [];
            for ($i = 0; $i < $rule['num']; $i++) {
                $tableName[] = 'SELECT * FROM ' . $this->getTable() . '_' . ($i + 1);

**Comment by hiCasper** [comment]
你当前使用的是v2版本（即php版）的Cloudreve，目前已经基本不再更新了，请使用新版Cloudreve.

**Comment by Hector-cqj** [comment]
> 您当前使用的是v2版本（即php版）的Cloudreve，目前已经基本不再更新了，请使用新版本Cloudreve。

谢谢
