### ISSUE TITLE
建议添加自动扫描 导入本地文件

### ISSUE THREAD

**Issue by sqyqyq** [cloudreve/Cloudreve#470]
偏向于个人使用， 建议添加自动扫描更新导入本地文件的功能，谢谢

**Comment by hiCasper** [comment]
已经支持从本地导入文件的功能（#304），但不建议作为日常使用，管理文件请尽量从网页/PWA端，或者WebDAV等进行操作。

**Comment by Jing-q** [comment]
强烈建议添加自动扫描更新导入本地文件的功能！！！

**Comment by hatsuyuki280** [comment]
@Jing-q 很显然，这个软件不是这么用的

这个软件有自己的文件系统抽象，监控磁盘上存在的文件变动本来就不是它该管理的事情

就像你直接对着磁盘在二进制层面上添加了一些内容却不在文件系统规定的元数据里添加指向那些修改的记录，你的文件系统也没办法识别到你有追加新文件一样

如果你需要这个功能，自己写个定期脚本直接写入数据库吧

**Comment by Jing-q** [comment]
> [@Jing-q](https://github.com/Jing-q)很明显，这个软件不是那么用的
> 
> 这个软件有自己的文件系统抽象，监控磁盘上存在的文件震动本来就不是该管理的事情
> 
> 就像你直接在磁盘片上添加了一些内容一样，在文件系统规定的元数据里添加指向那些的记录，你的文件系统修改也无法识别到你添加了新文件一样
> 
> 如果你需要这个功能，自己写一个脚本直接写入数据库吧

啊不好意思 没注意到信息，我之前就写了个小脚本用这了哈哈

**Comment by Meowilla** [comment]
> > [@Jing-q](https://github.com/Jing-q)很明显，这个软件不是那么用的
> > 这个软件有自己的文件系统抽象，监控磁盘上存在的文件震动本来就不是该管理的事情
> > 就像你直接在磁盘片上添加了一些内容一样，在文件系统规定的元数据里添加指向那些的记录，你的文件系统修改也无法识别到你添加了新文件一样
> > 如果你需要这个功能，自己写一个脚本直接写入数据库吧
> 
> 啊不好意思 没注意到信息，我之前就写了个小脚本用着了哈哈

什么脚本？来点 :)
