### ISSUE TITLE
【求助】自编译ARM5平台二进制，执行出错

### ISSUE THREAD

**Issue by bt-worm** [cloudreve/Cloudreve#471]
**交叉工具链**: gcc-linaro-4.9-2016.02-x86_64_arm-linux-gnueabi (glibc 2.19)
**go env 输出**:
_GO111MODULE=""
GOARCH="arm"
GOBIN="/opt/repo/goproj/bin"
GOCACHE="/home/xxx/.cache/go-build"
GOENV="/home/xxx/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/opt/repo/goproj"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org,direct"
GOROOT="/usr/local/go"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"
GCCGO="gccgo"
GOARM="5"
AR="arm-linux-gnueabi-ar"
CC="arm-linux-gnueabi-gcc"
CXX="arm-linux-gnueabi-g++"
CGO_ENABLED="1"
GOMOD=""
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -marm -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build038594369=/tmp/go-build -gno-record-gcc-switches"_

**目标平台**:ARM7l (BCM4709-无hardware floating); glibc 2.19

**编译无错, 目标平台运行输出**：

  / __\ | ___  _   _  __| |_ __ _____   _____ 
 / /  | |/ _ \| | | |/ _ | '__/ _ \ \ / / _ \	
/ /___| | (_) | |_| | (_| | | |  __/\ V /  __/
\____/|_|\___/ \__,_|\__,_|_|  \___| \_/ \___|

   __V3.1.1-1-gdd50ef1  Commit \#dd50ef1  Pro=false
================================================_

__Info]    2020-06-15 10:51:03 初始化数据库连接
SIGILL: illegal instruction
PC=0x933248 m=0 sigcode=1
signal arrived during cgo execution

goroutine 1 [syscall, locked to thread]:
runtime.cgocall(0x90c6d0, 0x1b7da4c, 0x188d598)
	/usr/local/go/src/runtime/cgocall.go:133 +0x5c fp=0x1b7da34 sp=0x1b7da1c pc=0x1f7f0
github.com/mattn/go-sqlite3.__Cfunc__sqlite3_open_v2(0x1709310, 0x188d598, 0x10006, 0x0, 0x0)_
	_cgo_gotypes.go:275 +0x38 fp=0x1b7da48 sp=0x1b7da34 pc=0x58bacc_
.
此处省略类似错误
.
goroutine 9 [select]:
database/sql.(*DB).connectionResetter(0x1896300, 0xfe4600, 0x19657e0)
	/usr/local/go/src/database/sql/sql.go:1065 +0xb4
created by database/sql.OpenDB
	/usr/local/go/src/database/sql/sql.go:723 +0x144

_trap    0x6
error   0x0
oldmask 0x0
r0      0xbec72830
r1      0x1030b2c
r2      0xbec7286c
r3      0xbec7286c
r4      0x0
r5      0x1709780
r6      0x1
r7      0x1030b2c
r8      0x0
r9      0x11
r10     0x1637308
fp      0xbec72888
ip      0x201
sp      0xbec7280c
lr      0x934cc8
pc      0x933248
cpsr    0x20000010
fault   0x0_

**Comment by pic2debug** [comment]
建议移步至clouddreve的论坛 https://forum.cloudreve.org 。也许其他论坛用户能帮到你

**Comment by bt-worm** [comment]
谢谢，已成功运行。目前在测试各项功能是否正常

**Comment by qian-jiahong** [comment]
@bt-worm 可以分享怎么解决此问题的吗？

**Comment by qian-jiahong** [comment]
> 谢谢，已成功运行。目前在测试各项功能是否正常

@bt-worm 可以分享怎么解决此问题的吗？
