### ISSUE TITLE
【BUG】无法删除文件等2个问题

### ISSUE THREAD

**Issue by callng** [cloudreve/Cloudreve#472]
### 问题1
如果要删除的文件过多（不能确定文件数（此次bug触发：＞300个文件）），会无法删除，报错如下图：
![bug](https://user-images.githubusercontent.com/64207250/84678923-3724c080-af63-11ea-93d7-4d4f8ee01d76.png)
存储策略：又拍云（应该不是又拍云问题），数据库：sqlite（性能问题？）
建议文件删除时，如果文件很多那么做批次删除处理不要集中在一个地址提交删除请求。
### 问题2
无法打开txt，php这类可以直接在cloudreve打开编辑的文件，但jpg这类图片文件可以正常访问，报错如下图：
![bug1](https://user-images.githubusercontent.com/64207250/84679398-d5b12180-af63-11ea-8c9c-147a76a9dc03.png)
存储方式：又拍云，数据库：sqlite

**Comment by Beattheend** [comment]
无法打开txt，php这类可以直接在cloudreve编辑的文件，但可以正常下载，下载的文件没有破坏。

**Comment by Beattheend** [comment]
在提个【建议】列表加载文件不建议一次性加载完毕，因为这样如果列表文件数过多（＞1000）会造成浏览器卡顿的现象。如果列表文件过多建议分批次加载文件，每次加载数量（<500？）防止浏览器卡顿（Google Chrome）

**Comment by hiCasper** [comment]
删除报错的问题应该是SQLite的问题，更换mysql应该可以解决，或者等作者修复。
文件无法打开的问题，可以F12打开Network选项卡，查看具体错误。
分页加载文件列表已经在计划了(https://github.com/cloudreve/frontend/issues/12)

**Comment by Beattheend** [comment]
@hiCasper 文件无法打开的问题，目前只有又拍云出现过，开启调试模式后就是如问题2 那截图一样

**Comment by HFO4** [comment]
> @hiCasper 文件无法打开的问题，目前只有又拍云出现过，开启调试模式后就是如问题2 那截图一样

是的，这个是又拍策略的bug
