### ISSUE TITLE
这种情况是否有可能内存泄露？

### ISSUE THREAD

**Issue by bt-worm** [cloudreve/Cloudreve#475]
硬件：Netgear R7000路由器 256M RAM, 
其他: 384M Swap
操作：上传300张照片（约2M/张）
现象：传到8~9张后，速度就非常慢了(有时完全停止），查看内存如下：

admin@R7000-20DA:/tmp/home/root# cat /proc/14206/status 
_Name:	cloudreve
State:	S (sleeping)
Tgid:	14206
Pid:	14206
PPid:	12661
TracerPid:	0
Uid:	1000	1000	1000	1000
Gid:	1000	1000	1000	1000
FDSize:	256
Groups:	27 1000 1001 
VmPeak:	  950852 kB
VmSize:	  948804 kB
VmLck:	       0 kB
VmHWM:	  172220 kB
VmRSS:	  118732 kB
VmData:	  923600 kB
VmStk:	     136 kB
VmExe:	   22588 kB
VmLib:	    1448 kB
VmPTE:	     392 kB
VmSwap:	  216492 kB
Threads:	16
SigQ:	1/1996
SigPnd:	0000000000000000
ShdPnd:	0000000000000000
SigBlk:	0000000000000000
SigIgn:	0000000000000000
SigCgt:	ffffffffffc1feff
CapInh:	0000000000000000
CapPrm:	0000000000000000
CapEff:	0000000000000000
CapBnd:	ffffffffffffffff
Cpus_allowed:	3
Cpus_allowed_list:	0-1
voluntary_ctxt_switches:	10722
nonvoluntary_ctxt_switches:	34168_

Cloudreve是否不适合在这样资源的硬件上运行？

**Comment by HFO4** [comment]
理论上是没问题的，可能是其他原因。
