### ISSUE TITLE
是否能够添加播放器时间轴缩略图功能？

### ISSUE THREAD

**Issue by spark135246** [cloudreve/Cloudreve#476]
我注意到视频播放器使用的是DPlayer，因此想问一下能否添加视频时间轴预览的功能？
![TIM截图20200618194437](https://user-images.githubusercontent.com/26293439/85016536-7ee25c80-b19c-11ea-8637-82e208100c5a.png)

**Comment by HFO4** [comment]
缩略图需要单独生成，暂时不考虑加入
