### ISSUE TITLE
添加sharepoint 支持后删除api错误帮忙修复下

### ISSUE THREAD

**Issue by 742481030** [cloudreve/Cloudreve#477]
body := client.makeBatchDeleteRequestsBody(dst)
	res, err := client.requestWithStr(ctx, "POST", client.getRequestURL("$batch"), body, 200)
	if err != nil {
		return dst, err
	}
client.getRequestURL("$batch") 里面多了me/drive/ 和sites/网站id/
请问正则怎么删掉 me/drive/ 和 sites/xxxxxxxxxxxxxx/
完全不懂go  不要见怪,
数据库api地址是 /v1.0/me/drive/和 /v1.0/sites/网站id/
所以这里函数多了  知道的麻烦告知下

**Comment by 742481030** [comment]
解决了
func (client *Client) Delete(ctx context.Context, dst []string) ([]string, error) {
	body := client.makeBatchDeleteRequestsBody(dst)
	
	
	
	
		if client.Endpoints.isInChina {
		res, err := client.requestWithStr(ctx, "POST", "https://microsoftgraph.chinacloudapi.cn/v1.0/$batch", body, 200)
	} else {
		res, err := client.requestWithStr(ctx, "POST", "https://graph.microsoft.com/v1.0/$batch", body, 200)
	}
	
	
	
	
	
	
	
//	res, err := client.requestWithStr(ctx, "POST", client.getRequestURL("$batch"), body, 200)
	if err != nil {
		return dst, err
	}

**Comment by 742481030** [comment]
报错了我日

**Comment by hiCasper** [comment]
使用Sharepoint会有不可预知的安全隐患，况且OneDrive自身也支持通过提交工单的方式扩容25T，所以没有任何支持Sharepoint的必要，还会带来不可预知的Bug。

> ”SharePoint的文件貌似同域内的用户可以搜索到（如果知道文件名或部分文件名的话）“

**Comment by 742481030** [comment]
我只是问如何让写 我并没让作者发行,知道就说不知道就拉到,

**Comment by 742481030** [comment]
发行版,偶尔都会无法获取上凭证和全选删除文件但是只删除一个的文件,这个也不知道是什么情况,

**Comment by 742481030** [comment]
解决了  参考pr
