### ISSUE TITLE
解压占用大量内存和cpu卡死服务器

### ISSUE THREAD

**Issue by Mmx233** [cloudreve/Cloudreve#479]
解压一个三百兆，136个文件的压缩包吃掉了五六百兆内存，cpu直接吃满。导服务器（1h1g）卡死一段时间然后cloudreve进程被kill
系统是centos7 64位，运行的是3.1.1 amd64
![image](https://user-images.githubusercontent.com/36563672/85222592-fb6c7980-b3ee-11ea-8833-a670f428daa1.png)
且再次启动cloudreve时会自动重新开始解压……但重新启动时压力会变小，能撑到完成任务。

**Comment by Beattheend** [comment]
解压缩这类肯定很吃内存的吧 @Mmxp

**Comment by Mmxp** [comment]
> 解压缩这类肯定很吃内存的吧 @Mmxp

鉿，那为啥用tar压力很小

**Comment by henrywu19359** [comment]
> > 解压缩这类肯定很吃内存的吧 @Mmxp
> 
> 鉿，那为啥用tar压力很小

tar确实压力小但是cloudreve用的是zip格式，所以吃性能。（主要是tar对中文支持太差了）
如果你想对比一下tar和zip的区别，可以将一个较大的文件分别压缩成tar格式和zip格式就能明显看到区别了。
zip对服务器压力大的问题好像无解，建议增加服务器配置或减少一次压缩的文件数量

**Comment by Mmxp** [comment]
> > > 解压缩这类肯定很吃内存的吧 @Mmxp
> > 
> > 
> > 铪，那为啥用tar压力很小
> 
> tar确实压力小但是cloudreve用的是zip格式，所以吃性能。（主要是tar对中文支持太差了）
> 如果你想对比一下tar和zip的区别，可以将一个较大的文件分别压缩成tar格式和zip格式就能明显看到区别了。
> zip对服务器压力大的问题好像无解，建议增加服务器配置或减少一次压缩的文件数量

可以用cgroups之类的限制一下占用吧，我觉得
