### ISSUE TITLE
储存策略失效时，难以移除。

### ISSUE THREAD

**Issue by Mmxp** [cloudreve/Cloudreve#480]
比如当连接的ondrive翻了车，这个时候存在那个策略里的文件以及该策略无法移除。从前台删除文件的话，在前台确实会消失，但是后台里那个文件还是在。而且这个时候从后台操作也删不掉，要能删一次还只能删100个文件，文件一多头皮都会麻掉。
不管吧，又占了数据库，后台数据也不真实了，很难过。

**Comment by HFO4** [comment]
可以在数据库中操作删除
