### ISSUE TITLE
【BUG】当用户的状态被更改后用户登录提示不是正确的封禁理由及其他问题

### ISSUE THREAD

**Issue by callng** [cloudreve/Cloudreve#481]
### 问题1
如果管理员在后台将某个用户封禁或者调整为其他状态（未激活丶超额使用被封禁）时，该用户登录时会提示用户邮箱或密码错误而不是正确的封禁理由。
### 问题2
如果开启了QQ互联并同时启用了未绑定时可直接登录时，被封禁的用户使用QQ登录后会重新创建一个新的账户！如果未启用 未绑定时可直接登录 那么会提示 此QQ号未绑定任何账号 的错误。

**Comment by SunshineboyZj** [comment]
查询了搜索引擎，发现这个“进入 cloudreve 数据库，修改 users 表里的 status 字段为 0”的办法能够解除封禁
![image](https://github.com/cloudreve/Cloudreve/assets/81549837/c1c6f1b7-f9cd-428a-bc02-059dbfff3926)
但还是希望能修复这个问题（让管理员无法封禁自己）
