### ISSUE TITLE
删除目录中的文件过多导致的删除超时

### ISSUE THREAD

**Issue by cha0sCat** [cloudreve/Cloudreve#484]
https://github.com/cloudreve/Cloudreve/blob/dd50ef1c25ce23061d6251a45665607ce9c87412/routers/controllers/objects.go#L10-L22

## 现象:
 + 目录没被删除
 + 前端报错504 Gateway timeout

## 原因:
  1. 删除任务所需时间过长导致请求超时
  2. 如果请求超时则上下文关闭, 任务被通知终止, 用户看到请求超时的错误, 最终文件夹删除失败.

## 解决方案:
如果单纯的把删除任务放到后台则表面上文件夹还在, 用户可能会重复调用删除.

因此:
 + 把删除任务作为一个Task, 提交任务时后端返回创建任务成功的通知, 随后前端使用Interval间隔请求删除进度.
 + 把删除任务放到后台, 优先删除目标目录, 让用户看到文件夹已经消失的"假象", 至于目录中的文件和子目录, 程序可以在后台慢慢删

***
<img src="https://i.ibb.co/NL6zVtk/68747470733a2f2f692e6962622e636f2f5a4b4a786758532f696d6167652e706e67.png" alt="image" border="0">
<br />
<img src="https://i.ibb.co/gDNwnMx/image.png" alt="image" border="0">

**Comment by qinfengge** [comment]
在docker的最新版本中，此问题依然存在
删除一个20000+文件的大文件夹先是CPU爆满，然后超时504，即使设置了nginx的最大超时时间，同样失败
同时在删除父文件夹中的任一文件同样错误，后端报{code: 203, msg: "Failed to delete 1 file(s)."}
此BUG严重影响体验
