### ISSUE TITLE
【BUG】管理员可以封禁自己及其他问题反馈

### ISSUE THREAD

**Issue by callng** [cloudreve/Cloudreve#486]
### 问题1
![反馈1](https://user-images.githubusercontent.com/64207250/85853085-79ac8f80-b7e4-11ea-992f-0dc473df8b21.png)
在后台管理用户页面查询管理组，查询后尝试封禁无法封禁，但进入编辑页面就可以进行属性修改，如果封禁丶超额封禁丶未激活等。
![反馈2](https://user-images.githubusercontent.com/64207250/85853219-b7111d00-b7e4-11ea-8841-3c6748c5f46c.png)
### 问题2
管理员购买非管理组的用户组后解绑后管理员的权限会被移除变成普通用户，拥有其他用户组会把管理员权限给弄没了。
### 问题3
请修复这个issues：[#481](https://github.com/cloudreve/Cloudreve/issues/481)

**Comment by cchins** [comment]
这个必须修复，我也手贱给自己玩没了过

**Comment by SunshineboyZj** [comment]
查询了搜索引擎，发现这个“进入 cloudreve 数据库，修改 users 表里的 status 字段为 0”的办法能够解除封禁
![image](https://github.com/cloudreve/Cloudreve/assets/81549837/c1c6f1b7-f9cd-428a-bc02-059dbfff3926)
但还是希望能修复这个问题（让管理员无法封禁自己）
