### ISSUE TITLE
【BUG】上传文件的过程中状态自动改变成【排队中】

### ISSUE THREAD

**Issue by shanhaishi** [cloudreve/Cloudreve#487]
发现在上传一个400M左右的文件的时候，刚开始能正常上传，但是忽然就会变成排队状态，无法完成上传

**Comment by HFO4** [comment]
@shanhaishi 可能是上传过程中发生异常

**Comment by remychew** [comment]
> @shanhaishi 可能是上传过程中发生异常

我也会经常这样，请问这种情况有解决方法吗？

**Comment by HFO4** [comment]
已在 https://github.com/cloudreve/frontend/commit/3a4ec698487ca88ba7a0d029335048c4c8274195 修复
