### ISSUE TITLE
上传完毕后的自动刷新页面会导致正在播放的音频消失

### ISSUE THREAD

**Issue by Mmx233** [cloudreve/Cloudreve#489]
![image](https://user-images.githubusercontent.com/36563672/86372980-7702dc00-bcb5-11ea-8112-a5cbbef9bbf8.png)
浏览器：谷歌桌面版，用手机谷歌浏览器测试时唤起文件管理器失败（没反应，oppo）
控制台无报错

**Comment by Mmxp** [comment]
啊，手机那个是他卡了，最终结果和pc一样。

**Comment by HFO4** [comment]
音频预览目前支持的较为简陋，不支持后台播放，后面可能会优化一下
