### ISSUE TITLE
积分下载分享文件可以绕过积分免费下载

### ISSUE THREAD

**Issue by h123hh** [cloudreve/Cloudreve#491]
在下载需要积分的文件时点击保存到我的文件就可以免费下载

**Comment by Beattheend** [comment]
@h123hh 在最新版本（3.1.1）中无法复现你的问题！
![no bug](https://user-images.githubusercontent.com/64207250/86741421-f1db4680-c069-11ea-94c1-efa16cc335ae.png)

**Comment by HFO4** [comment]
@Beattheend 如果已经预览/下载，积分就会扣除，且不会重复扣除

**Comment by h123hh** [comment]
> @Beattheend 如果已经预览/下载，积分就会扣除，且不会重复扣除
我是实验账号中本身已有足够的积分，然后主账号设置完分享再通过使用账号打开后点击保存到我的文件然后文件保存了，积分却没有扣除，刷新且切换设备登录了测试账号，积分数量依然没有变

**Comment by h123hh** [comment]
> @Beattheend 如果已经预览/下载，积分就会扣除，且不会重复扣除

哦，抱歉，问题已解决，我把服务器重启之后积分就扣除了
