### ISSUE TITLE
预览文件后点开其他页面标题不变

### ISSUE THREAD

**Issue by woshoxxx** [cloudreve/Cloudreve#492]
版本：3.1.1
策略：OneDrive
预览1.txt之后，点击左侧按钮，网页标题还是1.txt

**Comment by Beattheend** [comment]
@woshoxxx 左侧按钮指的是网易后退按钮？

**Comment by woshoxxx** [comment]
@Beattheend 左侧按钮指我的分享，离线下载、任务队列三个按钮

**Comment by Beattheend** [comment]
@woshoxxx 应该是前端，不是策略的问题
