### ISSUE TITLE
Windows环境下支付宝初始化实列失败解决方法

### ISSUE THREAD

**Issue by GuerraMorgan** [cloudreve/Cloudreve#496]
> 此电脑（计算机）-> 属性 -> 高级系统设置 -> 环境变量 -> 添加以下系统变量
> 变量名：ZONEINFO
> 变量值：C:\zoneinfo.zip
> 将以下文件放到C盘下（对照变量值）
> [zoneinfo.zip](https://github.com/cloudreve/Cloudreve/files/4900527/zoneinfo.zip)

**Comment by GuerraMorgan** [comment]
@HFO4

**Comment by 193305451** [comment]
谢谢 去试一下
