### ISSUE TITLE
离线下载报错Database is locked

### ISSUE THREAD

**Issue by Dustin-Jiang** [cloudreve/Cloudreve#497]
服务器部署在
```
Windows Server 2019 (1809) 64-Bit
Intel Core i3 4030U
Cloudreve v3.1.1 x86_64
Aria2c 1.35.0 via JSON RPC x86_64
```
在同时下载多个文件时报错`Error: Database is locked`
经查询得知此错误为SQLite并行数据处理时数据锁错误

可供参考资料: 
[解决SQLite database is locked](https://www.cnblogs.com/xienb/p/3455562.html)
[sqlite3 database is locked 问题解决方案](https://blog.csdn.net/u011011827/article/details/56486270)

望请修改解决

**Comment by HFO4** [comment]
解决起来较为复杂，大并发场景下还是推荐使用MySQL。

**Comment by Beattheend** [comment]
@HFO4 有什么方法可以从sqlite切换到mysql？

**Comment by hiCasper** [comment]
> @HFO4 有什么方法可以从sqlite切换到mysql？

- 手动dump sqlite数据库后导入到mysql中
- 初始化mysql数据库建立表结构以后将数据单独导入

以上方法不能保证不会出现未知bug，最稳妥的方式还是使用mysql重建数据库+导入数据。

**Comment by Beattheend** [comment]
@hiCasper 尝试过 但无法正常上传文件，上传后 Cloudreve刷新无文件 ，无法创建文件夹。等。

**Comment by Beattheend** [comment]
> 以上方法不能保证不会出现未知bug，最稳妥的方式还是使用mysql重建数据库+导入数据。

目前执行这套方案
