### ISSUE TITLE
目录下无法创建文件夹

### ISSUE THREAD

**Issue by Beattheend** [cloudreve/Cloudreve#499]
![无法创建文件夹](https://user-images.githubusercontent.com/64207250/87375330-c3a3bc80-c5bd-11ea-93f4-e4dccd55976b.png)

目录下没有要创建的文件夹却提示同名目录已存在？而且无论创建什么文件夹都会提示这错误。

无论是根目录还是其他目录都是这种问题。

在此之前我从sqlite数据库换成了mysql数据库，mysql数据库版本为：5.7。

难道是我更换数据库造成的问题？

而且目前又一已知问题是上传的文件无法在Cloudreve上显示。

完了，一定是更换数据库出的问题。

**Comment by Beattheend** [comment]
目前看来是Cloudreve无法往数据库插入数据或者查询才导致的问题。真是手欠啊！早知道就不换数据库了，因为官方都没有切换数据库的教程。。。

**Comment by Beattheend** [comment]
目前暂时恢复备份（sqlite数据库）解决问题，如果有什么方法可以无损切换到mysql数据库的，请告知。

**Comment by HFO4** [comment]
目前没有自动化的方法手动切换
