### ISSUE TITLE
无法加载验证码：Network Error

### ISSUE THREAD

**Issue by whuxxie** [cloudreve/Cloudreve#501]
![image](https://user-images.githubusercontent.com/5456079/87738003-fabcdc80-c80e-11ea-9ecf-d56c00be53c2.png)
![image](https://user-images.githubusercontent.com/5456079/87738026-0b6d5280-c80f-11ea-8686-0d23fa5c0483.png)
点击登陆，右上角红框显示    无法加载验证码：Network Error

**Comment by HFO4** [comment]
可以F12看下Console里的错误输出
