### ISSUE TITLE
从外部导入的图片似乎不会展示缩略图？

### ISSUE THREAD

**Issue by wodexiaobai322** [cloudreve/Cloudreve#502]
![_20200718_175100](https://user-images.githubusercontent.com/25130817/87849970-4068ca80-c91f-11ea-8d8d-424177267854.JPG)
如上图，直接上传的图片一切正常，可以展示缩略图
![_20200718_175141_Mosaic_17_51_49](https://user-images.githubusercontent.com/25130817/87850001-6db57880-c91f-11ea-93cc-985c10ac058b.JPG)
但是导入的图片不会展示缩略图。导入是用的rclone挂载在本地的Google drive。

**Comment by Macyrate** [comment]
同样的问题……`3.1.1`的更新日志里有`新增 缩略图不存在时重新创建`，但没有发现在哪😂

**Comment by 3772702** [comment]
同样导入的本地存储 缩略图不显示

**Comment by Towdium** [comment]
补充一点，webdav 上传的文件也缺少缩略图...

**Comment by gaoxianglyx** [comment]
> 补充一点，webdav 上传的文件也缺少缩略图...

我用webdav上传是有缩略图的

**Comment by spark135246** [comment]
我前几天看到源码缩略图里，local本地存储的存储策略里数据为空，也就是一种缩略图图片类型都不支持。然后看到上传图片的时候，因为本地存储不支持缩略图，所以不写入支持缩略图的字段，但是数据库插入操作结束后，又单独调用生成缩略图的代码，重新更新一遍数据数据。我还以为是故意这么设计，因为缩略图会生成在导入的目录，破坏导入目录的有序，但是我不在乎，还自己瞎改了呢。没想到是bug

**Comment by autodotua** [comment]
碰到同样的问题。而且，双击打开以后也没法显示。希望修复，谢谢。

**Comment by niubility000** [comment]
嗯嗯，同样问题。

**Comment by kangjinwen** [comment]
等待完善，功能是很不错的

**Comment by zero617** [comment]
这个功能还没做吗？求

**Comment by Whitedragon115** [comment]
v4.9.0 中可能會有相關功能

https://github.com/cloudreve/cloudreve/issues/2373

**Comment by YUDONGLING** [comment]
> 这个功能还没做吗？求

V4 导入还是不显示吗？

**Comment by zero617** [comment]
原来有新版了 😭 unraid上没注意，一直用的旧版
