### ISSUE TITLE
【BUG】3.1.1 Word docx 文档不能预览

### ISSUE THREAD

**Issue by mqlinme** [cloudreve/Cloudreve#505]
http://{ip}:{port}/api/v3/user/avatar/gzT2/s                  404
https://view.officeapps.live.com/op/zh-CN/strings.js      404

**Comment by mqlinme** [comment]
应该是本地没有外网

**Comment by topjohncian** [comment]
在线office预览必须得
** 外网可以访问 **
** 使用80 443端口 **

**Comment by Jonnyan404** [comment]
> 在线office预览必须得
> **外网可以访问**
> **使用80 443端口**

家宽只有非标准端口,80/443/8080被封禁.

**Comment by vailin** [comment]
内外访问可以在内网搭建OnlyOffice 然后修改Cloudreve代码将预览功能指向内外的OnlyOffice

**Comment by 157492196** [comment]
> 在线office预览必须得
> **外网可以访问**
> **使用80 443端口**

这两个条件都满足，在线预览依然提示An error occurred，点击Learn more会跳转到 https://www.office.com/redir.aspx?assetid=HA102724036 不过，这个网址依然不能打开。

**Comment by microcoder007** [comment]
遇到相同问题，已经用nginx进行端口转发
转发到80端口，外网可以访问，但还是无法预览office文档

**Comment by ninggee** [comment]
> 内外访问可以在内网搭建OnlyOffice 然后修改Cloudreve代码将预览功能指向内网的OnlyOffice

onlyoffice接受的参数一样吗，直接修改城内网的onlyoffice的地址就可以了吗
