### ISSUE TITLE
上传大小限制的问题

### ISSUE THREAD

**Issue by gy2331314** [cloudreve/Cloudreve#506]
大佬您好，我用CD（version3.1.1）连接了阿里云对象存储，但在上传大文件（超过5G）时出现post body size must be less than 5G
应该是阿里云对象存储上传限制了大小5G，能否在后台有设置选项设置上传的js的max_file_size：“0”，让前端上传不受限制。
![0073017d49ce752f63e65763c5549e0](https://user-images.githubusercontent.com/26855531/88513739-6f67f600-d01b-11ea-8992-d1bcba2e225d.jpg)

**Comment by gy2331314** [comment]
补充：我未使用代理

**Comment by HFO4** [comment]
@gy2331314 OSS策略暂不支持上传5GB以上文件

**Comment by gy2331314** [comment]
> @ gy2331314 OSS策略临时不支持上传5GB以上文件

有办法处理吗？

**Comment by HFO4** [comment]
暂时没有办法，后续会改用分片上传支持更大的文件。
