### ISSUE TITLE
希望可以支持自定义第三方接口

### ISSUE THREAD

**Issue by ALICEOFALICE** [cloudreve/Cloudreve#507]
希望可以支持下自定义第三方接口（国内有些oss厂家费用很低），这几家费用较高

**Comment by Beattheend** [comment]
你看上哪家了 自己按照SDK 打包就行

**Comment by ALICEOFALICE** [comment]
捐助版可以支持吗，想用捐赠版对接第三方接口

**Comment by topjohncian** [comment]
建议自己搞自己编译 
一般是不会支持小厂的
商家会不会跑路这回事说不清楚

**Comment by ALICEOFALICE** [comment]
还是得自己编译，行吧，尝试去适配下他们家的接口
