### ISSUE TITLE
映射本地盘符时可用容量显示错误

### ISSUE THREAD

**Issue by ZerowindSE** [cloudreve/Cloudreve#508]
触发条件/现象：
使用RaiDrive通过WebDAV映射目录为本地盘符时无法获取磁盘容量，手动填入总容量后依然无法得知可用容量。
相对根目录为 /

复现：
可复现，并在不同电脑测试过。

**Comment by cjs520** [comment]
RaiDrive的问题

**Comment by HFO4** [comment]
暂不支持通过WebDAV返回容量配额信息。RaiDrive会使用默认的容量展示。
