### ISSUE TITLE
是否可以考慮加入 github/gitlab 作為來源

### ISSUE THREAD

**Issue by changchichung** [cloudreve/Cloudreve#510]
用github 上的 reposiroty 作為儲存來源
當使用者透過 cloudreve 新增/刪除/異動 檔案時，就自動  commit & push

**Comment by 2834364635** [comment]
怎么加

**Comment by hiCasper** [comment]
Github对于repository的使用限制非常严格，一般只有1G空间，单文件限制100M，并且滥用会收到警告，所以不可能将Github作为储存策略提供。

**Comment by changchichung** [comment]
好吧，我只是想說這樣子，可以有個好用的平台編輯一些小的文字檔，也不用在那邊下指令去 commit push pull ..

**Comment by hiCasper** [comment]
> 好吧，我只是想說這樣子，可以有個好用的平台編輯一些小的文字檔，也不用在那邊下指令去 commit push pull ..
> 
> 

可以尝试使用一些GUI，比如Github Desktop或者其它（SourceTree，SmartGit，GitKraken等），都可以方便使用。
