### ISSUE TITLE
在线预览文件时 报错 无法读取文件数据

### ISSUE THREAD

**Issue by cr-zhichen** [cloudreve/Cloudreve#513]
在线预览文件时 在文本预览框中报错 无法读取文件，但是可以正常进行文件的下载  

![{"code":50004,"msg":"无法读取文件数据"}](https://tc.chengrui.xyz/2020/08/01/msedge_ZZvs0I8a1U.png)  

使用的版本为 3.1.1  
存储方式为阿里云OSS存储配合CDN加速  

![阿里云OSS](https://tc.chengrui.xyz/2020/08/01/msedge_tqhg7sttnF.png)  

存储设置中也正常填写了预览文件大小  

![预览文件大小  ](https://tc.chengrui.xyz/2020/08/01/msedge_y5mZproVVI.png)

**Comment by HFO4** [comment]
原因可能有很多，需要开启Debug模式查看详细报错。一般是服务器无法访问到远程文件导致。

**Comment by cr-zhichen** [comment]
> 原因可能有很多，需要开启Debug模式查看详细报错。一般是服务器无法访问到远程文件导致。

请问一下，如何开启Debug模式，或者有开启Debug模式的wike链接么，我刚翻官方文档，没有找到Debug模式的开启方式。  

另外保存的文件可以正常的生成下载链接和直链，只是不能正常在线预览。
