### ISSUE TITLE
下载文件时报404错误

### ISSUE THREAD

**Issue by jscblack** [cloudreve/Cloudreve#514]
例如下载overview.pdf
我们在线浏览是很正常的

但右击下载时，指向的url是

https://upoos.yilantingfeng.site/uploads%2F2020%2F08%2F03%2FOverview.pdf？_upd=Overview.pdf&_upt=6b6e9d781596458173

报404错误

如果删去_upd=Overview.pdf段

如

https://upoos.yilantingfeng.site/uploads%2F2020%2F08%2F03%2FOverview.pdf?_upt=6b6e9d781596458173

则一切正常

使用又拍云 版本为3.1.1 按推荐开启防盗链

**Comment by HFO4** [comment]
经测试，无法复现。如果有后续 update 欢迎 reopen 这个 issue
