### ISSUE TITLE
WebDAV设置根目录没用

### ISSUE THREAD

**Issue by DDOS-SU** [cloudreve/Cloudreve#515]
WebDAV设置根目录没用，上传的文件无法放在指定目录中。

**Comment by HFO4** [comment]
无法复现这种情况

**Comment by dzhl** [comment]
我这边也是这样情况，存储策略里设定的路径是updates，没有再使用魔法变量，连接的是世纪互联onedrive，在我的文件里创建了test目录，但是在onedrive里看不到test目录，在test目录里上传文件显示成功，但在onedrive里上传的文件直接位于update目录，使用webdav指定了根目录是updates下的test目录，同步后，同步文件也仍是位于updates目录
