### ISSUE TITLE
离线下载转存失败

### ISSUE THREAD

**Issue by gray0128** [cloudreve/Cloudreve#516]
感谢作者！
离线下载完成后，转存失败，请问如何处理？
提示：
文件转存失败：PUT https://yunpan-1256132207.cos.ap-shanghai.myqcloud.com/uploads%2F2020%2F08%2F06%2F9UVFC0DB_mysql-installer-community-8.0.19.0.msi: 400 UserNetworkTooSlow(Message: User network is too slow.

**Comment by HFO4** [comment]
服务器中转时网络状况不佳导致，尝试更换为网络更好的环境。
