### ISSUE TITLE
反代5212端口之后，一直出现502错误

### ISSUE THREAD

**Issue by KanVivii** [cloudreve/Cloudreve#517]
因为有ssl而且想直接80端口访问，所以配置反代。
但是只要设置反代之后几分钟就开始502错误
在宝塔面板直接配置的，反复检查也网上搜过配置方法确认没问题。
大佬求解

**Comment by LamGC** [comment]
检查一下反代的目标地址看看，可能是web服务器没连上Cloudreve？

**Comment by KanVivii** [comment]
> 检查一下反代的目标地址看看，可能是web服务器没连上Cloudreve？

链接了呀

因为刚开始的一会儿是可以用的 过了十来分钟就不行了

搜了一下都说是缓存的问题

**Comment by LamGC** [comment]
唔，如果是nginx服务器的话，我建议直接整个配置文件上去看看能不能解决问题（配置的话，可以直接到[NginxConfig](https://www.digitalocean.com/community/tools/nginx)上面配置一个，设置`Node.js`应用填目标地址就好）。

**Comment by KanVivii** [comment]
放弃了，我看大家说的最多的就是缓存问题，换成zfile了
