### ISSUE TITLE
上传速度限制

### ISSUE THREAD

**Issue by timgogochen** [cloudreve/Cloudreve#520]
服务器软件对上传速度有做限制吗，本机上传也仅仅维持了不到1MB的速度。
![image](https://user-images.githubusercontent.com/13269998/89869241-a971f400-dbe6-11ea-8af7-41703e04c0b3.png)

**Comment by pic2debug** [comment]
没限制。我那边上传4MB/s。防火墙可能回限制数据包传入的速度

**Comment by HFO4** [comment]
如果网络没问题的话，可能是硬盘IO限制了上传速度。

**Comment by obentnet** [comment]
我对接的upyun也是限速了
