### ISSUE TITLE
请问文件和文件夹不支持多选吗？尤其是手机操作相当不方便。

### ISSUE THREAD

**Issue by wuzhumeng** [cloudreve/Cloudreve#523]

**Comment by topjohncian** [comment]
PC可以使用 <kbd>Shift</kbd> 和 <kbd>Ctrl</kbd>

**Comment by wuzhumeng** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        手机端怎么弄？
        
    
        
        

        
    

    在2020年8月18日 16:28，topjohncian<notifications@github.com> 写道： 




PC可以使用 Shift 和 Ctrl

**Comment by fuckxiaoo** [comment]
> PC可以使用 Shift 和 Ctrl

怎么用我按着呢也不能多选啊

**Comment by HFO4** [comment]
移动端暂时不支持多选
