### ISSUE TITLE
站点报错 - 无法加载站点配置：Network Error

### ISSUE THREAD

**Issue by AdminHcat** [cloudreve/Cloudreve#528]
以https://+域名方式访问网站右上角提示：“**无法加载站点配置：Network Error**”
注册登录等操作右上角均提示“**无法加载验证码：Network Error**”

**Comment by fuckxiaoo** [comment]
![image](https://user-images.githubusercontent.com/62214878/90717898-41f12e00-e2e3-11ea-9312-1df08c302dbd.png)
你这改了吗

**Comment by AdminHcat** [comment]
> ![image](https://user-images.githubusercontent.com/62214878/90717898-41f12e00-e2e3-11ea-9312-1df08c302dbd.png)
> 你这改了吗

肯定该了阿

**Comment by topjohncian** [comment]
F12 Network 请

**Comment by AdminHcat** [comment]
> F12 Network 请

有两个文件连接已重置.-.

**Comment by topjohncian** [comment]
> > F12 Network 请
> 
> 有两个文件连接已重置.-.

截图 谢谢🍆

**Comment by AdminHcat** [comment]
> > > F12 Network 请
> > 
> > 
> > 有两个文件连接已重置.-.
> 
> 截图 谢谢🍆

![image](https://user-images.githubusercontent.com/50044729/90801230-38e67800-e348-11ea-92cd-71f513d80304.png)

**Comment by topjohncian** [comment]
> > > > F12 Network 请
> > > 
> > > 
> > > 有两个文件连接已重置.-.
> > 
> > 
> > 截图 谢谢🍆
> 
> ![image](https://user-images.githubusercontent.com/50044729/90801230-38e67800-e348-11ea-92cd-71f513d80304.png)

Connection reset 了是你服务器的问题 检查后端是否能被访问

**Comment by AdminHcat** [comment]
> > > > > F12 Network 请
> > > > 
> > > > 
> > > > 有两个文件连接已重置.-.
> > > 
> > > 
> > > 截图 谢谢🍆
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/50044729/90801230-38e67800-e348-11ea-92cd-71f513d80304.png)
> 
> Connection reset 了是你服务器的问题 检查后端是否能被访问

不用https就可以访问，就很奇怪

**Comment by hotwa** [comment]
同上遇到改问题出现，`无法加载站点配置：Network Error`以及`无法加载验证码：Network Error`
环境：

> cloudreve_3.2.1_linux_amd64.tar.gz
> ubuntu 20.04
> nginx 
> 配置好ssl

/etc/nginx/conf.d/cloudreve.conf
```
server {
        # listen 80;
        # rewrite ^(.*)$ https://${server_name}$1 permanent;
        # listen [::]:80 default_server;
        # SSL configuration
        listen 443 ssl default_server;
        listen [::]:443 ssl default_server;
        ssl_certificate /etc/nginx/conf.d/5124780_cloud.top.pem;
        ssl_certificate_key /etc/nginx/conf.d/5124780_cloud.top.key;
        server_name cloud.top;
                location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $http_host;
                proxy_redirect off;
                proxy_pass http://127.0.0.1:5212;

                # 如果您要使用本地存储策略，请将下一行注释符删除，并更改大小为理论最大文件尺寸
                #     # client_max_body_size 20000m;
        }
}
```
**解决办法**：关闭80端口重定向。可以正常访问http，登录不会出现上述报错。
我的解决办法，关闭80端口和重定向。只使用443端口。可以正常使用。
> 致开发者：对于同时开启80端口，443端口。登录80端口网页，443端口访问的网页，在退出登录，或者登录的时候，会出现不断重定向或者说刷新。也可能出现上述报错。
> 对于出现该问题，应该是有前端框架有不断读取cookie缓存等前端本地储存，对于同一域名，仅仅是80或者443端口不同，会导致，443直接读取到80网页中的缓存，出现不断刷新的情况。最好的解决方法就是只使用一个端口。推荐使用https。安全性和配置onedrive很有帮助。

**Comment by Yuelioi** [comment]
今天我也出现了这个问题, 发现是SSL 过期了, 重新申请一下就可以了
