### ISSUE TITLE
希望可以统计并显示文件夹下文件数目

### ISSUE THREAD

**Issue by ShaoPak** [cloudreve/Cloudreve#535]
遇到一次上传很多文件的时候，要想确定是否全部上传完毕需要一个一个文件的数，很麻烦，希望可以自动统计并列出文件夹下的文件夹总数和文件总数，类似windows里面的资源管理器（如图）
![image](https://user-images.githubusercontent.com/62377236/90946994-d8009200-e464-11ea-9162-878c4e6942ff.png)

**Comment by HFO4** [comment]
可以按下全选快捷键`Ctrl+A`，右上角会给出当前层级下的对象个数。
