### ISSUE TITLE
【bug】又拍云的下载问题

### ISSUE THREAD

**Issue by jscblack** [cloudreve/Cloudreve#538]
又拍云疑似更新了下载api，之前的下载是https://文件url?upd=文件名&upt=防盗链时间戳。
而现在更新为了https://文件url?upt=防盗链时间戳
也就是删去了_upd参数
现在使用下载就会出现404的错误，必须手动删去_upd字段才能正常下载，希望得到更新。
![](https://forum.cloudreve.org/assets/files/2020-08-24/1598254631-489297-81vu0t0pjt7k0n4-qe.png)
![](https://forum.cloudreve.org/assets/files/2020-08-24/1598254631-446116-7n8y0gf3cshm0at7sjs.png)

**Comment by Beattheend** [comment]
此问题无法复现，测试又拍云正常下载 _upd=0001.jpg&_upt=8a2653611598316870"

**Comment by jscblack** [comment]
问题已解决，出在又拍云的存储设置中需要选择？参数不跟随，感谢您的回复
