### ISSUE TITLE
【增强】不支持 GB2312 的中文 txt 文件在线预览，预览为乱码。

### ISSUE THREAD

**Issue by 157492196** [cloudreve/Cloudreve#540]
![image](https://user-images.githubusercontent.com/24198247/91046076-67b36580-e64a-11ea-9418-6213045d069d.png)
如图所示，该文件为 GB2312 的中文文本文件，直接打开为乱码。

有没有设置的地方修改，抑或是当前确实并不支持？

**Comment by HFO4** [comment]
不支持非UTF-8编码的文本编辑
