### ISSUE TITLE
离线下载世纪互联大文件转存失败

### ISSUE THREAD

**Issue by declan-haojin** [cloudreve/Cloudreve#541]
# 基本概况
一起下载的几MB的小文件都成功转存世纪互联了，但是1.4GB大小的视频显示转存失败

# 报错信息
> 文件转存失败：Put https://alphaone-my.sharepoint.cn/personal/darrell_mqk_me/_api/v2.0/drive/items/01DWNOZI4I3EHWQWMZLBDIGYUZ3MIFWHOB/uploadSession?guid='14c5baf0-e6ca-4a05-8285-feb3d6e2491c'&path='~tmp05_3xUoRUeM_Hard.Kill.2020.1080p.WEBRip.x265-RARBG.mp4'&overwrite=True&rename=False&dc=0&tempauth=eyJ0eXAiOiJKV1QiLCJhbGciOiJub25lIn0.eyJhdWQiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAvYWxwaGFvbmUtbXkuc2hhcmVwb2ludC5jbkAzYjFjODFiMS1kMTU2LTRhZjktYjE2OS1hZTA4MTI4YzAzOTYiLCJpc3MiOiIwMDAwMDAwMy0wMDAwLTBmZjEtY2UwMC0wMDAwMDAwMDAwMDAiLCJuYmYiOiIxNTk4NDU5Nzc5IiwiZXhwIjoiMTU5ODU0NjE3OSIsImVuZHBvaW50dXJsIjoiREU2VVp4OWNOYThVOE5vYVhGUEFJYnpFQ0U0bFpwYXp0bFJob1BCNGtvcz0iLCJlbmRwb2ludHVybExlbmd0aCI6IjI3MSIsImlzbG9vcGJhY2siOiJUcnVlIiwiY2lkIjoiT0dWaU5UZGxZVFl0T0dSbU5TMDBZekUyTFdKa1lUWXRaR0l5T1dWa1pHUXdNemRqIiwidmVyIjoiaGFzaGVkcHJvb2Z0b2tlbiIsInNpdGVpZCI6IlptTmlOREUxWldZdFpEUXhNaTAwWmpnMkxUa3lNMk10TVRGaVptUmlNRGswWTJabSIsImFwcF9kaXNwbGF5bmFtZSI6ImNsb3VkLmxpaGFvamluLmNuIiwic2lnbmluX3N0YXRlIjoiW1wia21zaVwiXSIsImFwcGlkIjoiMjU3MDJkYWEtYzc2OC00NTliLTljZDEtNDIyZWQwY2RlM2M4IiwidGlkIjoiM2IxYzgxYjEtZDE1Ni00YWY5LWIxNjktYWUwODEyOGMwMzk2IiwidXBuIjoiZGFycmVsbEBtcWsubWUiLCJwdWlkIjoiMTAwMzMyMzBDNTRDOEU4RCIsImNhY2hla2V5IjoiMGguZnxtZW1iZXJzaGlwfDEwMDMzMjMwYzU0YzhlOGRAbGl2ZS5jb20iLCJzY3AiOiJhbGxmaWxlcy53cml0ZSIsInR0IjoiMiIsInVzZVBlcnNpc3RlbnRDb29raWUiOm51bGx9.NjQzYlE4NnEyeXlMY1dJNGFDdk9IOHMxN3FMWGRiMFNlSTlWNnN5WmZCST0: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

# 谢谢！

**Comment by declan-haojin** [comment]
我有尝试了转存七牛云，也因为文件过大转存失败了
> 文件转存失败：{"error":"413 Request Entity Too Large"}

**Comment by cjs520** [comment]
你看看你的nginx设置的post_body大小

**Comment by declan-haojin** [comment]
你好，我尝试把`post_body`设为0无限制之后还是一样的报错信息。 另外请问Cloudreve的日志路径是哪里，谢谢！

**Comment by HFO4** [comment]
服务端传输到 OneDrive 服务器的速率太慢
