### ISSUE TITLE
【BUG】A用户保存B用户分享的文件无视用户存储容量的限制

### ISSUE THREAD

**Issue by Beattheend** [cloudreve/Cloudreve#544]
已知B用户空间容量限制在1B（经过测试），按照逻辑来说此时B用户根本无法上传和保存他人分享的文件，但A用户分享了一文件夹，文件夹里包含了24个文件，测试B用户任然可以保存A用户分享的文件，但进入B用户个人空间后会提示你的已用容量已超过容量配额，请尽快删除多余文件或购买容量。

请修复它。

![bug1](https://user-images.githubusercontent.com/64207250/91567060-18857180-e977-11ea-891e-dd8c61880de2.png)

![bug2](https://user-images.githubusercontent.com/64207250/91567082-23400680-e977-11ea-9187-43eab1af4689.png)

**Comment by HFO4** [comment]
与 #336 重复
