### ISSUE TITLE
使用Office365 的smtp发送邮件时出错

### ISSUE THREAD

**Issue by YuerSoCute** [cloudreve/Cloudreve#545]
log:
HIDDEN → IP ADDRESS
`[GIN] 2020/08/29 - 14:25:08 | 200 |    3.310349ms |   HIDDEN | POST     /api/v3/admin/setting`
`[GIN] 2020/08/29 - 14:25:22 | 200 |    2.626288ms |   HIDDEN | POST     /api/v3/admin/mailTest`
`[Error]   2020-08-29 14:25:22 邮件发送队列出现异常, tls: first record does not look like a TLS handshake ,10 秒后重置`
`[GIN] 2020/08/29 - 14:27:06 | 200 |     2.21915ms |   HIDDEN | POST     /api/v3/admin/mailTest`
`[Error]   2020-08-29 14:27:06 邮件发送队列出现异常, tls: first record does not look like a TLS handshake ,10 秒后重置`

`[GIN] 2020/08/29 - 14:29:28 | 200 |   39.606564ms |   HIDDEN | PATCH    /api/v3/admin/setting`
`[GIN] 2020/08/29 - 14:29:28 | 200 |    4.678092ms |   HIDDEN | GET      /api/v3/admin/reload/email`
`[GIN] 2020/08/29 - 14:29:29 | 200 |     1.97443ms |   HIDDEN | POST     /api/v3/admin/mailTest`
`[Error]   2020-08-29 14:29:29 邮件发送队列出现异常, tls: first record does not look like a TLS handshake ,10 秒后重置`

————————————————————
smtp服务器设置:

发件人邮箱
yu-@mail.-.vip
SMTP服务器
smtp.office365.com
SMTP端口
587
SMTP用户名
yu-@mail.-.vip
SMTP密码
X
回信邮箱
yu-@mail.-.vip
使用加密连接
True
SMTP连接有效期（秒）
30
————————————————————
office365的smtp服务器使用STARTTLS
[https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365#how-to-set-up-smtp-auth-client-submission](https://docs.microsoft.com/en-us/exchange/mail-flow-best-practices/how-to-set-up-a-multifunction-device-or-application-to-send-email-using-microsoft-365-or-office-365#how-to-set-up-smtp-auth-client-submission)

**Comment by GitUniversities** [comment]
应该是加密类型问题，好多SMTP不支持STARTTLS

**Comment by qcppl5** [comment]
我和你提示的一样，找到解决方法么😂😂😂

**Comment by wsndshx** [comment]
可以尝试使用25端口,因为587端口只允许TLS连接.

**Comment by qcppl5** [comment]
> 可以尝试使用25端口,因为587端口只允许TLS连接.



> 可以尝试使用25端口,因为587端口只允许TLS连接.

我用的是网易邮箱现在就是25端口一样没法发送邮件

**Comment by HFO4** [comment]
可尝试关闭`使用加密连接`，Cloudreve 会尝试使用 STARTTLS 连接 SMTP 服务器。相关表单的文字描述已经更新完善。
