### ISSUE TITLE
Something went wrong issue while uploading

### ISSUE THREAD

**Issue by shyim** [cloudreve/Cloudreve#546]
Hey,
when I upload an bigger Image (4mb). I get the error Something went wrong.

I guess the console errors triggers it
![image](https://user-images.githubusercontent.com/6224096/91646758-cca7fa80-ea52-11ea-880c-aee9f44bc7c4.png)

**Comment by HFO4** [comment]
Have you got any unsuccessful request in Network tab?

**Comment by shyim** [comment]
Can't reproduce it anymore 🙈 . Maybe Chrome update. Anyway thanks! 😊
