### ISSUE TITLE
文件压缩问题反馈

### ISSUE THREAD

**Issue by Beattheend** [cloudreve/Cloudreve#553]
两个7z压缩包用Cloudreve压缩成一个zip文件后大小变22b
![bug](https://user-images.githubusercontent.com/64207250/92225435-c7750080-eed5-11ea-9045-207678e19f01.png)

**Comment by HFO4** [comment]
可能是文件名包含非法字符。具体原因需要在压缩时打开Debug模式看日志输出才能分析出来。

**Comment by Beattheend** [comment]
我看看

> 可能是文件名包含非法字符。具体原因需要在压缩时打开Debug模式看日志输出才能分析出来。

**Comment by Beattheend** [comment]
感觉又是又拍云的锅呢

[2020-09-07 12:10:40]  [0.99ms]  SELECT * FROM "files"  WHERE "files"."deleted_at" IS NULL AND ((id in (15158,15261,15332,15342) AND user_id = 1))  
[4 rows affected or returned ] 
[Debug]   2020-09-07 12:10:40 Open笔趣阁小说插件源代码.zip，服务器返回非正常HTTP状态404
[Debug]   2020-09-07 12:10:40 Opencom.atssr.title.zip，服务器返回非正常HTTP状态404
[Debug]   2020-09-07 12:10:40 Open支付协议模块.e，服务器返回非正常HTTP状态404
[Debug]   2020-09-07 12:10:41 Opencom.atssr.X.zip，服务器返回非正常HTTP状态404
[Debug]   2020-09-07 12:10:41 压缩文件存放至/www/wwwroot/pan.***.com/temp/compress/archive_1599451840578256635.zip，开始上传

![test](https://user-images.githubusercontent.com/64207250/92347712-85310680-f103-11ea-9381-3f1d6f187678.png)

**Comment by Beattheend** [comment]
da ma da le ge ji mo

**Comment by Beattheend** [comment]
测试用腾讯云COS正常压缩。
