### ISSUE TITLE
能否在上传文件时覆盖已有同名文件

### ISSUE THREAD

**Issue by ChirmyRam** [cloudreve/Cloudreve#554]
经常在安卓端使用webdav功能来同步软件的相关配置，一些配置文件更新后同步上传会覆盖原来的文件，但cloudreve不支持上传已有同名文件，提示已存在而拒绝上传，这样就会造成同步失败，即使更改储存目录和重命名规则也会失败，必须删除原来的文件才能再次进行同步，请问上传时可否覆盖已有同名文件？
![同步失败](https://s1.ax1x.com/2020/09/05/wVfyC9.jpg)

**Comment by HFO4** [comment]
Cloudreve 的 WebDAV 实现本身是支持使用 PUT 覆盖更新文件内容的，409可能是锁操作异常。
