### ISSUE TITLE
请问如何加载磁盘原本的文件

### ISSUE THREAD

**Issue by gaoxianglyx** [cloudreve/Cloudreve#555]
请教一下：
我的存储路径原有的文件能否展示出来呢？是否有类似扫描目录的功能

另外，我手动在磁盘中移动了图片后，在系统中也无法删除，提示删除失败，是否有办法解决呢？

**Comment by topjohncian** [comment]
> 请教一下：
> 我的存储路径原有的文件能否展示出来呢？是否有类似扫描目录的功能
> 
> 另外，我手动在磁盘中移动了图片后，在系统中也无法删除，提示删除失败，是否有办法解决呢？

1.可以在后台进行手动导入
2.可以在后台里强制删除
 后台指 /#/admin
