### ISSUE TITLE
前端资源构建过慢

### ISSUE THREAD

**Issue by hzjoyous** [cloudreve/Cloudreve#559]
代码 clone 下来 第一次 yarn run build 花了 200s,
环境  matebook x pro 2019，win10 ,i7+16
![image](https://user-images.githubusercontent.com/28970107/92435159-37d09a00-f1d4-11ea-85e1-db82e7113759.png)

**Comment by mritd** [comment]
@hzjoyous 8c 16g vps docker 交叉 build 3 小时 🤣，不知道前端能不能用 esbuild

**Comment by topjohncian** [comment]
> 代码 clone 下来 第一次 yarn run build 花了 200s,
> 环境  matebook x pro 2019，win10 ,i7+16
> ![image](https://user-images.githubusercontent.com/28970107/92435159-37d09a00-f1d4-11ea-85e1-db82e7113759.png)
> 

这个速度算快了

**Comment by mritd** [comment]
@HFO4 项目兼容 [esbuild](https://github.com/evanw/esbuild) 么，如果能用 esbuild 的话应该会有很大提升。

**Comment by topjohncian** [comment]
> @HFO4 项目兼容 [esbuild](https://github.com/evanw/esbuild) 么，如果能用 esbuild 的话应该会有很大提升。

目前还是用create-react-app的
(webpack慢也没有办法啊

**Comment by mritd** [comment]
![image](https://user-images.githubusercontent.com/13043245/92677091-8d808000-f355-11ea-9c1d-900019089473.png)
人间不值得.....

**Comment by hzjoyous** [comment]
绳命在于等待
