### ISSUE TITLE
导入文件原路径设为 " . " 导致系统根目录被导入从而造成数据库爆满

### ISSUE THREAD

**Issue by CloverGit** [cloudreve/Cloudreve#561]
https://forum.cloudreve.org/d/1216

**Comment by mritd** [comment]
@CloverGit 描述不算太清晰，我的理解是你执行了两次导入，第一次导入路径设为 "/" 第二次为 "."，然后发现数据库满了？而且你说第一次导入并没有成功是有错误返回还是怎么回事？刚刚我看了下代码，按照我的理解你第一次就应该会导致数据库写满，导入动作我的理解是异步行为，你写了 "/" 就会从根开始递归导入。

**Comment by CloverGit** [comment]
> @CloverGit 描述不算太清晰，我的理解是你执行了两次导入，第一次导入路径设为 "/" 第二次为 "."，然后发现数据库满了？而且你说第一次导入并没有成功是有错误返回还是怎么回事？刚刚我看了下代码，按照我的理解你第一次就应该会导致数据库写满，导入动作我的理解是异步行为，你写了 "/" 就会从根开始递归导入。

事实上，我也不太清楚，我在问题决解后又按照原来的动作重现问题，在 【第一次导入路径设为 "/" 】之后刷新数据库，确实没有看到数据库写满的情况
