### ISSUE TITLE
全局状态码200真的好吗

### ISSUE THREAD

**Issue by zhangguanzhang** [cloudreve/Cloudreve#562]
项目结构不错，但是所有地方返回200真的好吗，我很期待作者能用gin写个生产后端的demo给我们小白参考下😁

**Comment by HFO4** [comment]
个人认为是否复用 HTTP 状态码语义也只是风格选择上的问题，没有明显的优劣之分。

**Comment by zhangguanzhang** [comment]
大佬有写那种纯后端的gin项目吗
