### ISSUE TITLE
希望能添加OneDrive反代链接

### ISSUE THREAD

**Issue by 56025192** [cloudreve/Cloudreve#568]
希望能添加OneDrive反代链接

**Comment by topjohncian** [comment]
#483

**Comment by 742481030** [comment]
https://github.com/cloudreve/Cloudreve/pull/572

**Comment by 742481030** [comment]
https://github.com/742481030/cloudreve-cdn-sharepoint

**Comment by 742481030** [comment]
> 希望能添加OneDrive反代链接
https://github.com/742481030/cloudreve-cdn-sharepoint
