### ISSUE TITLE
无法加载站点配置：Unexpected end of JSON input

### ISSUE THREAD

**Issue by ColorfulGhost** [cloudreve/Cloudreve#573]
配置文件使用mysql存储会出现此错误

**Comment by topjohncian** [comment]
是免费版升级pro嘛

**Comment by ColorfulGhost** [comment]
> 是免费版升级pro嘛

还有这种区分吗？......git clone 下来的啊

**Comment by zbx1425** [comment]
可能是MySQL版本的问题。Cloudreve要求MySQL 5.7及以上，但是从CentOS软件源或堡塔安装只有5.6。

**Comment by canghailan** [comment]
我也遇到了这个问题，是字符集的原因，不能使用utf8mb4编码，会导致索引超长，数据库表初始化失败，改成utf8编码就可以了。

**Comment by ColorfulGhost** [comment]
> 我也遇到了这个问题，是字符集的原因，不能使用utf8mb4编码，会导致索引超长，数据库表初始化失败，改成utf8编码就可以了。

了解了，但是看到着个项目的issue这么多....没人维护 不敢用了XD

**Comment by ColorfulGhost** [comment]
多谢告知 ，了解了。

Sent from Mail for Windows 10

**Comment by HFO4** [comment]
Link  #563

**Comment by YogeLiu** [comment]
这个bug应该解决了吧，但是我的Mysql字符集编码是utf8mb3的，还是出现了这个问题

**Comment by wangxiaoerYah** [comment]
> 这个bug应该解决了吧，但是我的Mysql字符集编码是utf8mb3的，还是出现了这个问题

你啥系统centos?

**Comment by YogeLiu** [comment]
> 

Mac 我昨天以为是配置mysql的问题。后来我重新编译了一个，没有配置数据库。但是还会出现这个问题。是我的静态资源没有嵌入成功吗
