### ISSUE TITLE
能否增加网易云NOS

### ISSUE THREAD

**Issue by zhyi526** [cloudreve/Cloudreve#580]
能否增加对接网易云NOS，我看官方也有go语言的sdk

**Comment by 742481030** [comment]
> 能否增加对接网易云NOS，我看官方也有go语言的sdk
有没有sdk不是重点, 有restapi接口都能加入,rclone挂载成本地可以支持好多国外的龟速网盘,google无限容量还是可以搞.
其实除了本地存储和onedrive,google,我有个朋友用cos,一夜流量被人刷了十几万,差点跳楼,这玩意还是内网用吧太恐怖
别的我们都用不起,分分钟房子给银行.注意这是私人型网盘,我不相信什么白熊小麦网盘能长久,早晚都是跑路,上市公司有钱玩的都是股民的钱.
