### ISSUE TITLE
WebDav 无法使用，401

### ISSUE THREAD

**Issue by dammu** [cloudreve/Cloudreve#581]
如题描述，armbian buster上`./cloudreve` 启动之后，WebDav 始终连不上（内网连http://192.168.xxx.xxx:5212/dav），终端显示 401。不管是用用户名+密码还是新建账号+密码，或者更换注册用户组，手机上换 Mix，ES，Win10 的资源管理器都连不上，都是 401。还尝试了在 Win 上再开了一个，连 http://127.0.0.1:5212/dav 也是不行。面板设置翻了又翻，实在是不知道怎么回事，google 半天也没找到解决办法，只有看到 HTTPS 反代出 401 的，不知道什么解决，求解。

[GIN] 2020/09/22 - 18:18:21 | 401 |      48.001µs |   192.168.50.46 | PROPFIND  /dav
[GIN] 2020/09/22 - 18:18:21 | 200 |    7.066136ms |   192.168.50.46 | OPTIONS  /
[GIN] 2020/09/22 - 18:18:21 | 401 |      44.001µs |   192.168.50.46 | PROPFIND  /dav
[GIN] 2020/09/22 - 18:18:22 | 401 |      46.001µs |   192.168.50.46 | PROPFIND  /dav
[GIN] 2020/09/22 - 18:18:22 | 401 |     4.12908ms |   192.168.50.46 | PROPFIND  /dav
[GIN] 2020/09/22 - 18:18:22 | 401 |    2.937057ms |   192.168.50.46 | PROPFIND  /dav
[GIN] 2020/09/22 - 18:18:22 | 401 |    3.279063ms |   192.168.50.46 | PROPFIND  /dav
[GIN] 2020/09/22 - 18:18:22 | 401 |    2.666052ms |   192.168.50.46 | PROPFIND  /dav
[GIN] 2020/09/22 - 18:18:22 | 401 |    2.656052ms |   192.168.50.46 | PROPFIND  /dav
[GIN] 2020/09/22 - 18:18:22 | 401 |    2.794053ms |   192.168.50.46 | PROPFIND  /dav
[GIN] 2020/09/22 - 18:18:22 | 401 |    2.881055ms |   192.168.50.46 | PROPFIND  /dav

连一次就这样的报错。

**Comment by mengfanding** [comment]
同问

**Comment by HFO4** [comment]
未启用ssl时，Windows资源管理器是无法挂载的。其他客户端是否有更具体的错误消息呢？

**Comment by dammu** [comment]
> 未启用ssl时，Windows资源管理器是无法挂载的。其他客户端是否有更具体的错误消息呢？

Windows Explorer 是改了注册表用 http 的，表现是输入帐号密码（应该是被拒绝了）又弹帐号密码输入框，重复就提示无法连接之类的（服务器端终端提示401）。手机上 Mix 连接填入地址用户名密码，连接就又弹出来这个输入界面（服务端提示401）。手机上 Total Commander 填好地址用户名密码，不勾选 https，连接就弹密码框，输入对应的密码重复弹，服务端刷出401，okhttpClient 跟 ApacheClient 都一样，然后就 Unauthorized 了。
客户端上就只有这种前端的表现可以看了，也没有报错提供（或者我不知道）。试着 Mix 连接的时候抓到个 TCP 包，有用的话我再贴一下。

**Comment by HFO4** [comment]
目前看来就是密码不正确导致的，或者是上层Web服务器把客户端发来的 `Authorization` 头。

**Comment by dammu** [comment]
> 目前看来就是密码不正确导致的，或者是上层Web服务器把客户端发来的 `Authorization` 头过滤掉了。

密码复制都不行应该是不会错的。使用环境是客户端到家用路由器到 armbian 吧，

**Comment by dammu** [comment]
> > 目前看来就是密码不正确导致的，或者是上层Web服务器把客户端发来的 `Authorization` 头过滤掉了。
> 
> 密码复制都不行应该是不会错的。使用环境是客户端到家用路由器到 armbian 吧，

手残点到关闭了。。
也没配置啥，那问题出在路由器上还是 armbian 上，怎么处理呢

**Comment by playcase** [comment]
楼主的问题后来解决了么？

**Comment by xmgi** [comment]
> 如题描述，armbian buster上`./cloudreve` 启动之后，WebDav 始终连不上（内网连[http://192.168.xxx.xxx:5212/dav），终端显示](http://192.168.xxx.xxx:5212/dav%EF%BC%89%EF%BC%8C%E7%BB%88%E7%AB%AF%E6%98%BE%E7%A4%BA) 401。不管是用用户名+密码还是新建账号+密码，或者更换注册用户组，手机上换 Mix，ES，Win10 的资源管理器都连不上，都是 401。还尝试了在 Win 上再开了一个，连 http://127.0.0.1:5212/dav 也是不行。面板设置翻了又翻，实在是不知道怎么回事，google 半天也没找到解决办法，只有看到 HTTPS 反代出 401 的，不知道什么解决，求解。
> 
> [GIN] 2020/09/22 - 18:18:21 | 401 | 48.001µs | 192.168.50.46 | PROPFIND /dav
> [GIN] 2020/09/22 - 18:18:21 | 200 | 7.066136ms | 192.168.50.46 | OPTIONS /
> [GIN] 2020/09/22 - 18:18:21 | 401 | 44.001µs | 192.168.50.46 | PROPFIND /dav
> [GIN] 2020/09/22 - 18:18:22 | 401 | 46.001µs | 192.168.50.46 | PROPFIND /dav
> [GIN] 2020/09/22 - 18:18:22 | 401 | 4.12908ms | 192.168.50.46 | PROPFIND /dav
> [GIN] 2020/09/22 - 18:18:22 | 401 | 2.937057ms | 192.168.50.46 | PROPFIND /dav
> [GIN] 2020/09/22 - 18:18:22 | 401 | 3.279063ms | 192.168.50.46 | PROPFIND /dav
> [GIN] 2020/09/22 - 18:18:22 | 401 | 2.666052ms | 192.168.50.46 | PROPFIND /dav
> [GIN] 2020/09/22 - 18:18:22 | 401 | 2.656052ms | 192.168.50.46 | PROPFIND /dav
> [GIN] 2020/09/22 - 18:18:22 | 401 | 2.794053ms | 192.168.50.46 | PROPFIND /dav
> [GIN] 2020/09/22 - 18:18:22 | 401 | 2.881055ms | 192.168.50.46 | PROPFIND /dav
> 
> 连一次就这样的报错。

我开始也用win10资源管理器连不上，加上ssl后好了

**Comment by chypay** [comment]
> 
> 
> > 如题描述，armbian buster上`./cloudreve` 启动之后，WebDav 始终连不上（内网连[http://192.168.xxx.xxx:5212/dav），终端显示](http://192.168.xxx.xxx:5212/dav%EF%BC%89%EF%BC%8C%E7%BB%88%E7%AB%AF%E6%98%BE%E7%A4%BA) 401。不管是用用户名+密码还是新建账号+密码，或者更换注册用户组，手机上换 Mix，ES，Win10 的资源管理器都连不上，都是 401。还尝试了在 Win 上再开了一个，连 http://127.0.0.1:5212/dav 也是不行。面板设置翻了又翻，实在是不知道怎么回事，google 半天也没找到解决办法，只有看到 HTTPS 反代出 401 的，不知道什么解决，求解。
> > [GIN] 2020/09/22 - 18:18:21 | 401 | 48.001µs | 192.168.50.46 | PROPFIND /dav
> > [GIN] 2020/09/22 - 18:18:21 | 200 | 7.066136ms | 192.168.50.46 | OPTIONS /
> > [GIN] 2020/09/22 - 18:18:21 | 401 | 44.001µs | 192.168.50.46 | PROPFIND /dav
> > [GIN] 2020/09/22 - 18:18:22 | 401 | 46.001µs | 192.168.50.46 | PROPFIND /dav
> > [GIN] 2020/09/22 - 18:18:22 | 401 | 4.12908ms | 192.168.50.46 | PROPFIND /dav
> > [GIN] 2020/09/22 - 18:18:22 | 401 | 2.937057ms | 192.168.50.46 | PROPFIND /dav
> > [GIN] 2020/09/22 - 18:18:22 | 401 | 3.279063ms | 192.168.50.46 | PROPFIND /dav
> > [GIN] 2020/09/22 - 18:18:22 | 401 | 2.666052ms | 192.168.50.46 | PROPFIND /dav
> > [GIN] 2020/09/22 - 18:18:22 | 401 | 2.656052ms | 192.168.50.46 | PROPFIND /dav
> > [GIN] 2020/09/22 - 18:18:22 | 401 | 2.794053ms | 192.168.50.46 | PROPFIND /dav
> > [GIN] 2020/09/22 - 18:18:22 | 401 | 2.881055ms | 192.168.50.46 | PROPFIND /dav
> > 连一次就这样的报错。
> 
> 我开始也用win10资源管理器连不上，加上ssl后好了

我加了SSL还是401错误

**Comment by ciigo** [comment]
同问，一样错误，防火墙都关闭了

**Comment by simplenjoy** [comment]
同问，2022年了，webdav问题怎么还没有修复？

**Comment by MingZhao2019** [comment]
在Cloudreve的配置文件conf.ini中加入下面一段配置：

`; 跨域配置
[CORS]
AllowOrigins = *
AllowMethods = *
AllowHeaders = *
AllowCredentials = true`

之后重启服务即可

**Comment by Ohlagrange** [comment]
> 在Cloudreve的配置文件conf.ini中加入下面一段配置：
> 
> `; 跨域配置 [CORS] AllowOrigins = * AllowMethods = * AllowHeaders = * AllowCredentials = true`
> 
> 之后重启服务即可

添加重启之后还是不行，用于zotero的同步。。提示“WebDAV 服务器不接受您输入的用户名及密码”

**Comment by dabuu** [comment]
![image](https://user-images.githubusercontent.com/3324824/188537953-7f4940d9-c127-43b5-a4b8-805ecf660629.png)

使用 "统一用户名" + "创建的密码"  可以登录成功。

**Comment by DingKuiqing** [comment]
> ![image](https://user-images.githubusercontent.com/3324824/188537953-7f4940d9-c127-43b5-a4b8-805ecf660629.png)
> 
> 使用 "统一用户名" + "创建的密码" 可以登录成功。

亲测可用 感谢

**Comment by WinMEMZqwq** [comment]
> ![image](https://user-images.githubusercontent.com/3324824/188537953-7f4940d9-c127-43b5-a4b8-805ecf660629.png)
> 
> 使用 "统一用户名" + "创建的密码" 可以登录成功。

正解 感谢

**Comment by PolarisYu** [comment]
> ![image](https://user-images.githubusercontent.com/3324824/188537953-7f4940d9-c127-43b5-a4b8-805ecf660629.png)
> 
> 使用 "统一用户名" + "创建的密码" 可以登录成功。

Via浏览器WebDav备份亲测可用

**Comment by rwenjie957** [comment]
今天也发现了401 农田authorized问题，搞了半天，发现把梯子关掉就好了😢
