### ISSUE TITLE
上传似乎并没有分片上传

### ISSUE THREAD

**Issue by huang545** [cloudreve/Cloudreve#587]
测试了两组网络磁盘挂载，发现一些问题，下列数据通过监控本地防火墙的方式
①使用腾讯cos上传
直接上传至腾讯cos（不经过cloudreve），上传进程数为4，单进程上传速度1M/S左右，速度为4M/S
经过cloudreve上传至腾讯cos，上传进程数为1，总体速度为1M/S
②使用世纪互联上传
直接上传，2M/S，进程数2
经过上传，1M/S，进程数1

更换浏览器上传，效果相同

**Comment by HFO4** [comment]
目前客户端直传时，只有OneDrive是支持分片上传的，但不是并行上传。

**Comment by huang545** [comment]
> 目前客户端直传时，只有OneDrive是支持分片上传的，但不是并行上传。

未来没有计划支持并行上传么？因为这样子上传速度很慢。

**Comment by 742481030** [comment]
> > 目前客户端直传时，只有OneDrive是支持分片上传的，但不是并行上传。
> 
> 未来没有计划支持并行上传么？因为这样子上传速度很慢。

onedrive不支持并行,
