### ISSUE TITLE
WebDav 无法使用，401

### ISSUE THREAD

**Issue by mengfanding** [cloudreve/Cloudreve#588]
见： https://github.com/cloudreve/Cloudreve/issues/581

Windows挂载webdav错误

**Comment by cchins** [comment]
要在webdav哪里创建一个新账号，用生成的那个密码

**Comment by mmtian** [comment]
> 要在webdav哪里创建一个新账号，用生成的那个密码

新建了账号也不行，401错误

**Comment by whuxxie** [comment]
同样的问题

**Comment by playcase** [comment]
我也是同样问题，401错误，以前是可以的正常连接webdav的 ，奇怪的问题。

**Comment by nymanyim** [comment]
一样一样，webdav用不了

**Comment by iotsys** [comment]
貌似连 demo.cloudreve.org/dav 也是不行，可能是我不是个案，为止还纠结一天多了，我是SB

**Comment by zsxeee** [comment]
通过Debug模式发现了问题，webdav的鉴权逻辑是，先去验证用户表有没有这个用户名，然后再拿用户名密码和webdav表中的比对。
也就是说要正常用的话，需要在webdav功能里添加一个已有用户的用户名，比如自己。登录的时候要使用webdav里密码，webdav页面上的提示误导了我，不过我猜测默认管理员注册时没有在webdav表中生成记录

**Comment by wyt990** [comment]
我的在输入完密码后，直接提示错误，添加了新的账号，用它生成的随机密码，也试过了注册的账号，都不行。我是win64的服务器，客户端是win10，开了http
