### ISSUE TITLE
社区版有限速么？

### ISSUE THREAD

**Issue by Shuazijun** [cloudreve/Cloudreve#601]
上传跟下载被限制在2MB/S，已使用测试脚本，磁盘IO虽然渣但也有50MB/S，网络为100M对等，已通过2个节点测试，都只有2MB/S，反代后跟不反代 速度一样.
系统版本：centos8 x64
已安装宝塔面板，防火墙已放行.
![image](https://user-images.githubusercontent.com/30001049/95695132-14f73280-0c25-11eb-883a-ad9832c1fa42.png)

**Comment by Shuazijun** [comment]
管理面板无限速规则

**Comment by 0x5c0f** [comment]
应该没有限速的，如果是云服务器，你可以看下你最大的宽带是多少。

**Comment by topjohncian** [comment]
所有版本均无限速
