### ISSUE TITLE
3.1.1版本似乎不支持CDN

### ISSUE THREAD

**Issue by huang545** [cloudreve/Cloudreve#602]
我为自己的网站加入了百度云加速，但是看CDN监控报表里面，似乎并没有缓存到任何内容，只要有访问就会回源，100%，是因为我的设置不到位么？还是因为目前程序不支持CDN缓存？

**Comment by 0x5c0f** [comment]
你可能需要尝试下动态加速。

**Comment by topjohncian** [comment]
/api/* 不可以被缓存
静态资源可以缓存
