### ISSUE TITLE
不支持百度云加速CC防护强力模式

### ISSUE THREAD

**Issue by huang545** [cloudreve/Cloudreve#603]
当网站接入百度云之后，将CC防护调整为强力模式（3秒验证模式），尽管可以正常进入网站，但是刷新该页面以后提示页面不存在。

**Comment by topjohncian** [comment]
不截图不发日志你在这说有什么用？

**Comment by huang545** [comment]
> 不截图不发日志你在这说有什么用？

你好。我录制了一段复现视频，请查看：https://pan.huang1111.top/#/s/0Qfa
非常抱歉，由于我首次反馈cloudreve的相关bug，不是很清楚流程，耽误您时间了。

**Comment by topjohncian** [comment]
@huang545 f12 network

**Comment by huang545** [comment]
> @huang545 f12 network

你好，日志和截图：https://pan.huang1111.top/#/s/lXiY

**Comment by HFO4** [comment]
CC防护验证后携带的 GET 参数会和 Cloudreve 的路由有冲突，不清楚百度云加速那边有没有别的解决方案。

**Comment by huang545** [comment]
> CC防护验证后携带的 GET 参数会和 Cloudreve 的路由有冲突，不清楚百度云加速那边有没有别的解决方案。

似乎没有，Get参数判断这个人有没有过验证，似乎并没有其他解决办法，除非关闭强力防护，不过关闭强力防护后，防护CC效果大打折扣
