### ISSUE TITLE
3.1.1版本，使用默认设置，阿里云centos7，office文档预览报错

### ISSUE THREAD

**Issue by microcoder007** [cloudreve/Cloudreve#604]
使用默认设置部署
网页端，上传文档，pdf文件可以正常预览，但是office系都不能预览
已经测试 .doc，.docx，.pptx
请问是不是需要其他插件？

![微信截图_20201015180620](https://user-images.githubusercontent.com/25121682/96109484-41ef6200-0f11-11eb-93ad-a046697220ed.png)

**Comment by HFO4** [comment]
duplicate #505

**Comment by microcoder007** [comment]
大佬，我已经使用nginx进行端口转发到80
服务器可以使用外网，但还是无法使用office预览。
