### ISSUE TITLE
普通版或者捐赠版有开放接口的计划吗？

### ISSUE THREAD

**Issue by 1925473403** [cloudreve/Cloudreve#605]
普通版似乎并没有为第三方客户端调用开放的接口，目前还没有入手捐赠版，因为我不太确定捐赠版是否有我最需要的功能：为开发者开发第三方客户端提供的接口
我想问下，有为扩展开发提供的接口，或者为开放接口准备的开发计划吗？
：P

**Comment by topjohncian** [comment]
前端和后端是使用API接口进行通信的
只是没有写 APIDOC
