### ISSUE TITLE
上传异常导致无法登陆

### ISSUE THREAD

**Issue by Gumplefik** [cloudreve/Cloudreve#606]
在大量上传场景下，某些异常会导致user.storage计算异常，存储数据如图
![QQ图片20201018220718](https://user-images.githubusercontent.com/19474332/96369765-5a1fe500-118e-11eb-96a3-8ce446ab3e0c.png)
该异常数据会导致sql异常，从而导致无法登陆，非debug状态下报密码错误

**Comment by HFO4** [comment]
已修复
