### ISSUE TITLE
[BUG]：PC微信客户端内置浏览器打开空白

### ISSUE THREAD

**Issue by qqyule** [cloudreve/Cloudreve#608]
这是内置浏览器（3.0.0.47）的内核信息

CEF | 4.0.1301.400
Chromium | 53.0.2785.116
OS | Windows
WebKit | 537.36
JavaScript | 5.3.332.45

系统所有页面打开都显示空白，应该是未加载js导致，官方demo测试情况一样
修改过前端browserslist支持浏览器配置，还是不能解决

**Comment by HFO4** [comment]
微信私有 X5 内核暂未进行适配
