### ISSUE TITLE
IOS系统 ，预览PDF文件报错

### ISSUE THREAD

**Issue by Shuazijun** [cloudreve/Cloudreve#616]
IOS系统 ，预览PDF文件报错，苹果手机预览PDF ，载入后拖动页面，就会提示 Something went wrong. 
cloudreve v3.1.1 windows 2008系统x64

**Comment by Shuazijun** [comment]
![f6b302f9-75fa-4f71-8814-dba5f1ba1007](https://user-images.githubusercontent.com/30001049/97542655-189aff80-1a02-11eb-95e6-bbf383dd2f72.png)

**Comment by Shuazijun** [comment]
![Snipaste_2020-10-29_16-17-30](https://user-images.githubusercontent.com/30001049/97542773-4718da80-1a02-11eb-9917-5c77540429a4.png)
预览PDF 拖动一下页面就这样了

**Comment by Shuazijun** [comment]
测试了苹果，PDF文件较大时(5MB+)，预览就会报错。小文件PDF没问题（<1MB）

**Comment by HFO4** [comment]
经测试，无法复现
