### ISSUE TITLE
WebDav不能用，401

### ISSUE THREAD

**Issue by mmtian** [cloudreve/Cloudreve#618]
如题，WebDav不能用，总是出现401错误

**Comment by mmtian** [comment]
![image](https://user-images.githubusercontent.com/32121698/97881136-fa643500-1d5c-11eb-8657-860b9fe182e2.png)

**Comment by FikaCode** [comment]
webdav 页面的说明没说清楚，账号是 你登陆cloudreve的的账号，带邮箱的那个账号，密码是你在webdav页面创建账号时候自动生成的密码。webdav页面创建的账号好像没什么用，只有密码有作用。

**Comment by mmtian** [comment]
> webdav 页面的说明没说清楚，账号是 你登陆cloudreve的的账号，带邮箱的那个账号，密码是你在webdav页面创建账号时候自动生成的密码。webdav页面创建的账号好像没什么用，只有密码有作用。

谢谢，按照你说的，问题解决了，之前没理解那个说明啥意思

**Comment by CoderPwp** [comment]
> webdav 页面的说明没说清楚，账号是 你登陆cloudreve的的账号，带邮箱的那个账号，密码是你在webdav页面创建账号时候自动生成的密码。webdav页面创建的账号好像没什么用，只有密码有作用。

亲测有效！！！谢谢

**Comment by kangjinwen** [comment]
> webdav 页面的说明没说清楚，账号是 你登陆cloudreve的的账号，带邮箱的那个账号，密码是你在webdav页面创建账号时候自动生成的密码。webdav页面创建的账号好像没什么用，只有密码有作用。

谢谢谢谢谢谢谢谢！！！！！！！！！！！
