### ISSUE TITLE
关于CDN回源的问题

### ISSUE THREAD

**Issue by pmkol** [cloudreve/Cloudreve#621]
由于把网盘放在了海外服务器上，使用CDN，发现是回源的，下载大文件速度很慢。

但使用CDN，访问同一个主机下，纯NGINX目录列表，下载大文件速度很快，说明CDN对大文件是生效的。

所以想知道原因是什么，有什么办法可以让CDN不回源网盘的大文件。

**Comment by baiguke2019** [comment]
外部存储端因该不可以

**Comment by HFO4** [comment]
本地存储不支持 CDN 缓存

**Comment by chunfengyao** [comment]
> 本地存储不支持 CDN 缓存

按照这个配置也无法缓存本地存储吗？

https://forum.cloudreve.org/d/2475
