### ISSUE TITLE
当你删除的文件夹包含上千个文件时，报错！

### ISSUE THREAD

**Issue by spark135246** [cloudreve/Cloudreve#622]
## 操作

前端删除本地存储的文件夹，且文件夹包含上千个文件

## 现象

web端报错“无法列取对象记录“”

## 具体错误原因

大概就是上千个文件需要删除的时候，最终执行SQL删除或查找语句中就会包含上千个参数，而SQLite参数数量最大默认值为999，太多参数会消耗大量内存，因此超出999的参数数量会报错。

[参考链接](https://stackoverflow.com/questions/7106016/too-many-sql-variables-error-in-django-with-sqlite3)

![image](https://user-images.githubusercontent.com/26293439/98568845-81c91f80-22ec-11eb-999a-b14972ff6fb8.png)

![image](https://user-images.githubusercontent.com/26293439/98569399-382d0480-22ed-11eb-87fc-b056e125d320.png)

![image](https://user-images.githubusercontent.com/26293439/98568899-91486880-22ec-11eb-9f90-147935a49e42.png)

**Comment by HFO4** [comment]
Link #472

**Comment by canwushuang** [comment]
不上千也会报错。

**Comment by spark135246** [comment]
> 不上千也会报错。

准确来说，333是删除上限
