### ISSUE TITLE
怎么不是php版本的了

### ISSUE THREAD

**Issue by qqtx** [cloudreve/Cloudreve#625]
怎么不是php版本的了

**Comment by qqtx** [comment]
> 怎么不是php版本的了，亚马逊的oss根本下载不下来 主程序

**Comment by KawaiiZapic** [comment]
@qqtx 你这也能开issues你当issues是许愿池么?
建议给GitHub打电话问为啥没有中国境内的存储桶

**Comment by qqtx** [comment]
> @qqtx 你这也能开issues你当issues是许愿池么?
> 建议给GitHub打电话问为啥没有中国境内的存储桶
哦 你是知道的啊 ！！

**Comment by amtoaer** [comment]
@qqtx 1. 关于版本，cloudreve使用go进行了重构，你可以选择使用过去的php版本。
2. 关于下载，请检查本机网络并恰当使用代理工具。
