### ISSUE TITLE
自定义前端的问题

### ISSUE THREAD

**Issue by qqtx** [cloudreve/Cloudreve#631]
./cloudreve -eject  提取静态资源，把statics文件夹放Cloudreve 同级目录下，重启 Cloudreve ，修改的img图片文件会生效，修改后的html和js文件不会生效（网站前端显示的还是初始的内容），这是哪里的问题 centos7系统

**Comment by qqtx** [comment]
已经找到原因：有缓存，ctrl+f5都刷新不掉，如果正式推广后，前端有要修改的地方，怎么解决缓存问题？

**Comment by mritd** [comment]
这个问题理论上不属于开发者这边吧，缓存行为是浏览器/CDN 等中间层问题，如果软件将缓存强制设置为永不缓存，那么会影响全部用户，我觉得这有点得不偿失了。
