### ISSUE TITLE
上传提示无法完成文件上传

### ISSUE THREAD

**Issue by tinyhugh** [cloudreve/Cloudreve#632]
腾云cos存储策略
cloudreve版本：3.1.1

上传文件先提示完成，然后提示无法完成文件上传，在cos后台可以看到文件确实上传成功了，但是在cloudreve  web端不显示上传成功的文件。
![QQ截图20201121111923](https://user-images.githubusercontent.com/14050033/99866335-6fec5400-2beb-11eb-88f7-f67cfc48f898.png)

**Comment by HFO4** [comment]
检查设置中的 站点 URL 是否填写正确。
