### ISSUE TITLE
前端文件如何修改

### ISSUE THREAD

**Issue by Concept09** [cloudreve/Cloudreve#633]
吧前端静态资源提取出来 里面只有一个index。html页面，其他都是js文件 ， 比如<div class="jss767">这些div标签和class类 在哪里修改？  我想改分享页的文字，着实没找到下手的地方！！！

**Comment by seefs001** [comment]
朋友你要不了解一下react？

**Comment by Concept09** [comment]
吧前端静态资源提取出来 里面只有一个index。html页面，其他都是js文件 ， 比如  `<div class="jss676">`

这些div标签和class类 在哪里修改？ 我想改分享页的文字，着实没找到下手的地方！！！
![QQ浏览器截图20201121165644](https://user-images.githubusercontent.com/50699280/99872153-b73e0900-2c1a-11eb-9a55-4107062007e2.png)

**Comment by topjohncian** [comment]
前端源码
https://github.com/Cloudreve/frontend
