### ISSUE TITLE
安装时无法执行二进制文件

### ISSUE THREAD

**Issue by weimanMK** [cloudreve/Cloudreve#634]
![Snipaste_2020-11-21_20-45-04](https://user-images.githubusercontent.com/62314027/99877638-88d02600-2c3a-11eb-8930-cdc97d67be72.png)
请问如何解决，谢谢

**Comment by wsndshx** [comment]
执行`chmod +x cloudreve`

**Comment by topjohncian** [comment]
下错版本了
注意 `arm64` 和 `amd64` 的区别
