### ISSUE TITLE
从机存储策略BUG

### ISSUE THREAD

**Issue by philipsc** [cloudreve/Cloudreve#635]
为Cloudreve的从机存储策略添加的物理存储路径（uploads/{uid}/{path}）不能生效，在本机模式下才能生效，当用户uid为1的时候根据设置的存储路径会上传到uploads/1，但测试文件被上传到uploads/0，而且{path}目录还无法成功被创建。所有上传的文件都被保存在了uploads/0目录下，希望尽快修复。

**Comment by philipsc** [comment]
[论坛帖子](https://forum.cloudreve.org/d/1357)

**Comment by HFO4** [comment]
Fixed now.
