### ISSUE TITLE
无法发送邮件

### ISSUE THREAD

**Issue by luckywords** [cloudreve/Cloudreve#636]
看到有人说是PHP版本的问题，试了好几版本的PHP，还是一样的问题,又是出现的是tcp连接的问题，连接超时
还有的是一个邮件排队发送啥的什么问题，不知道是我的环境问题还是什么，求解决

**Comment by luckywords** [comment]
还有就是在我的wordpress上就可以发送邮件，都是一样的邮箱账号，之前我以为是我的阿里云的企业邮箱的解析问题，然后去发了工单但是没有问题，之后我用自己的个人邮箱去试了，还是一样的不能发送，接着我就去用个人的邮箱账号去试了我的wordpress，可以发送的，无论是25还是465，都是可以发送的，PHP的版本也切换了好几个7.3 7.4  56 都已经试过了，难道是真的是我的环境问题吗，我都是按照教程来安装的，我觉得最奇怪的就是今天下午我用的手机来配置的时候完全没有问题，但是后来我重新安装的时候就出现了问题，后来就不行了，一直都是发送不了的问题，麻烦帮忙看看。，谢谢

**Comment by luckywords** [comment]
![image](https://user-images.githubusercontent.com/73739680/99986276-eeaee000-2de9-11eb-9a49-488717b46b8a.png)

**Comment by luckywords** [comment]
![(ZI@VS10I $YXFHOJ@_JE2Y](https://user-images.githubusercontent.com/73739680/99986482-303f8b00-2dea-11eb-8325-6aab643bddb1.png)

**Comment by HFO4** [comment]
原因是无法连接到 SMTP 服务器，跟 PHP 无关。
