### ISSUE TITLE
一台服务器能不能同时运行两个程序

### ISSUE THREAD

**Issue by Concept09** [cloudreve/Cloudreve#639]
用不同得文件位置和端口 开启第二程序得时候提示 permission denied 但是权限已经是777了也是root用户 ， 在当前的命令行里测试启动第一个程序 可以成功

**Comment by philipsc** [comment]
放在另一个目录使用从机模式（Mode = slave）运行

**Comment by HFO4** [comment]
理论上是支持两个程序同时运行的，请检查自身的权限问题。
