### ISSUE TITLE
cloudreve里建立的文件夹删除后，实际磁盘里依然存在这个文件夹，这是BUG吗？

### ISSUE THREAD

**Issue by xiao-si-qi** [cloudreve/Cloudreve#641]
cloudreve里建立文件夹上传内容然后再删除整个文件夹，但是删除后，实际磁盘里依然存在空的文件夹啊，是就这样设计的，还是BUG啊

**Comment by HFO4** [comment]
Cloudreve 目前不会主动删除空目录，后续版本会进行优化
