### ISSUE TITLE
access token获取失败

### ISSUE THREAD

**Issue by huang545** [cloudreve/Cloudreve#647]
添加世纪互联存储策略，一直到授权页面状态正常，点击转到授权页面，提示access token获取失败

**Comment by HFO4** [comment]
服务端请求世纪互联相关API失败，具体错误信息可开启Debug模式查看。

**Comment by huang545** [comment]
> 服务端请求世纪互联相关API失败，具体错误信息可开启Debug模式查看。

世纪互联不再支持未注册的api调用，是否之后不再能够使用世纪互联存储策略？
