### ISSUE TITLE
:( 请求时出现错误 Request failed with status code 404

### ISSUE THREAD

**Issue by YuenSzeHong** [cloudreve/Cloudreve#648]
系统 win server 2012 r2 宝塔系统 apache 
错误信息
`2020/11/15 21:24:35 [error] 3792#1276: *15 FastCGI sent in stderr: "PHP Parse error:  syntax error, unexpected '$req' (T_VARIABLE) in C:\wwwroot\pan.yysub.top\includes\Upyun\Uploader.php on line 164" while reading response header from upstream, client: 182.35.65.203, server: pan.yysub.top, request: "POST /ajax.php?act=upload HTTP/1.1", upstream: "fastcgi://127.0.0.1:20054", host: "pan.yysub.top", referrer: "http://pan.yysub.top/upload.php"
`

**Comment by CoiaPrant** [comment]
@YuenSzeHong PHP 54实锤

**Comment by CoiaPrant** [comment]
@YuenSzeHong 请尝试使用新版php

**Comment by HFO4** [comment]
V2版本不再维护和支持，请升级至V3
