### ISSUE TITLE
iphone 连接webDAV 后，内容不可用

### ISSUE THREAD

**Issue by soarding** [cloudreve/Cloudreve#652]
1、iphone通过文件，连接服务器；
2、进入dav文件夹后，出现内容不可用，如下图：
![IMG_CDE043C5E1B1-1](https://user-images.githubusercontent.com/13713096/101131481-5104ad80-3640-11eb-97fd-8993691da5cf.jpeg)

**Comment by dingdingfujian** [comment]
macbook可以正常访问

**Comment by 835300592** [comment]
遇到同样问题 害

**Comment by cay080801** [comment]
我谢谢你们了文件只能链接smb协议
