### ISSUE TITLE
希望加入（pro）

### ISSUE THREAD

**Issue by AH-dark** [cloudreve/Cloudreve#656]
可以更改付费套餐的说明内容（这个很恶心）
转存自动识别不多占空间
可以禁止用户缓存
顶部菜单（1～2个即可）
侧栏菜单
兑换码独立页面
任务列表，防止多次上传
ftp存储策略（账号、密码、链接地址、下载地址）
可以自定义头部内容、css/js内容、底部内容，像lightsns一样那种
可以禁用搜索
可以设置仅限某储存策略的空间，就比如某空间只能用于这个储存策略，某空间可以用于全局
————
能实现三个我就谢天谢地了，作者加油！

**Comment by 1362032536** [comment]
附议
