### ISSUE TITLE
磁盘空间不足，导致离线下载失败。

### ISSUE THREAD

**Issue by hhrensheng** [cloudreve/Cloudreve#658]
版本：3.1.1
问题：当磁盘空间不足时，aria2下载完文件无法复制到Cloudreve的指定目录。
例如：当服务器空间有10G时，离线一个6G的文件。此时aria2的离线任务是正常生成的。当离线完毕后，猜测是由于程序是把文件复制而不是移动到正式目录。所以会导致磁盘空间不足。
这个问题我在论坛上已经提了，不知道是不是bug。[https://forum.cloudreve.org/d/1381](url)

**Comment by HFO4** [comment]
离线下载完成处理使用的统一是 复制 而非 移动，属于设计特性而非 Bug。

**Comment by hhrensheng** [comment]
我想问下为什么不用移动而是用复制呢，防止移动过程中意外中断导致数据丢失吗？
