### ISSUE TITLE
出现上传组件未加载完成的提示，无法上传文件

### ISSUE THREAD

**Issue by PaPerseller** [cloudreve/Cloudreve#660]
之前已上传的文件不受影响，刷新和重启服务无法解决。systemctl status cloudreve 报错部分如下:
2020/12/09 09:31:07 [sessions] ERROR! securecookie: the value is not valid
2020/12/09 09:31:07 [sessions] ERROR! securecookie: the value is not valid
[GIN] 2020/12/09 - 09:31:07 | 200 |     376.165µs | 2605:52c0:2:318:: | GET      /api/v3/user/avatar/0yUD/s
[GIN] 2020/12/09 - 09:31:07 | 200 |     174.496µs | 2605:52c0:2:318:: | GET      /api/v3/directory/
2020/12/09 09:31:07 [sessions] ERROR! securecookie: the value is not valid
[GIN] 2020/12/09 - 09:31:07 | 200 |      109.18µs | 2605:52c0:2:318:: | GET      /api/v3/user/storage
2020/12/09 09:31:07 [sessions] ERROR! securecookie: the value is not valid
[GIN] 2020/12/09 - 09:31:07 | 200 |    2.228546ms | 2605:52c0:2:318:: | GET      /api/v3/site/config
2020/12/09 09:31:07 [sessions] ERROR! securecookie: the value is not valid

**Comment by HFO4** [comment]
@PaPerseller 尝试清空 Redis 下的所有缓存

**Comment by PaPerseller** [comment]
> @PaPerseller 尝试清空 Redis 下的所有缓存

此前并未在系统中安装过 Redis, 也未用 find 找到带 Redis 名的文件。尝试删除 cloudreve 文件夹后重新部署，同样还是不行，可能并非 cloudreve 问题。
