### ISSUE TITLE
Cloudreve邮件发送问题

### ISSUE THREAD

**Issue by Beattheend** [cloudreve/Cloudreve#661]
![图1](https://user-images.githubusercontent.com/64207250/101821095-745cba80-3b62-11eb-88b0-a39e3d1ca4a3.png)

如图1所示，填写正确的邮箱参数后（已测试手机第三方APP授权码登录发送成功），Cloudreve无法发送测试邮件，开启调试模式提示“邮件发送列队出现异常，10秒后重置”

![图2](https://user-images.githubusercontent.com/64207250/101821406-df0df600-3b62-11eb-9b1a-0b6ec3a8cd3a.png)

Cloudreve提示邮件已成功发送，但我Gmail邮箱并未收到（已测试手机第三方APP授权码登录发送成功），开启调试模式后显示图1内容。

系统版本：CentOS 8.2.2004
Cloudreve版本：3.2.0 Pro 已启用SSL访问
测试时间：2020-12-11 03:44:58

请问是服务器问题还是什么原因。

**Comment by huang545** [comment]
在我这里，发信测试已被QQ邮箱自动识别为垃圾邮件退信，看一下是不是因为退信的原因导致无法发送.

**Comment by HFO4** [comment]
服务器无法连接到发信SMTP服务器导致

huang545 <notifications@github.com> 于 2020年12月12日周六 01:01写道：

**Comment by Beattheend** [comment]
只有去腾讯云反馈了

**Comment by Beattheend** [comment]
> 只有去腾讯云反馈了

问题已解决，原因：安全组未放行端口。
