### ISSUE TITLE
onedrive授权页面无法跳转回网盘

### ISSUE THREAD

**Issue by huang545** [cloudreve/Cloudreve#663]
可能是callback出现了问题，允许权限使用后跳转到了一个adminxxx网址，如图
![40E076CF-9F4D-40C1-88F5-4A423011112D](https://user-images.githubusercontent.com/18374415/101929262-93feec00-3c11-11eb-8dd0-d12d91e054ea.png)

**Comment by huang545** [comment]
补充：问题是发生在更新3.2版本后

**Comment by kroyoo** [comment]
一样，能正常授权，回调错误

**Comment by huang545** [comment]
> 一样，能正常授权，回调错误

我在“文件”栏丢失了一个存储桶，没办法看到存储桶新增的文件，但是主页面可以看到，不清楚是不是和这个问题有关，先等待其他人的修复吧，pro版本好像要等作者来修复了

**Comment by cjs520** [comment]
https://tb.861652.xyz/s/248a80bd-df5a-4f2c-ad63-853b941a61bd

已修复

**Comment by huang7dede** [comment]
> https://tb.861652.xyz/s/248a80bd-df5a-4f2c-ad63-853b941a61bd
> 
> 已修复

链接里的文件无法下载,我也是同样的错误..

**Comment by cyouakari** [comment]
> https://tb.861652.xyz/s/248a80bd-df5a-4f2c-ad63-853b941a61bd
> 
> 已修复

能否编译一下支持sharepoint的版本

**Comment by cjs520** [comment]
> > https://tb.861652.xyz/s/248a80bd-df5a-4f2c-ad63-853b941a61bd
> > 已修复
> 
> 下载了,,但是版本号貌似是3.0.0

版本号我忘记改了

**Comment by cjs520** [comment]
> > https://tb.861652.xyz/s/248a80bd-df5a-4f2c-ad63-853b941a61bd
> > 已修复
> 
> 能否编译一下支持sharepoint的win版本

有这个需求？？？

**Comment by kroyoo** [comment]
> 
> 
> > https://tb.861652.xyz/s/248a80bd-df5a-4f2c-ad63-853b941a61bd
> > 已修复
> 
> 能否编译一下支持sharepoint的win版本

https://github.com/kroyoo/Cloudreve/actions/runs/453865763

刚编译，win自测。
