### ISSUE TITLE
wget外链获取文件的问题和分享的文件夹支持上传权限

### ISSUE THREAD

**Issue by mycode233** [cloudreve/Cloudreve#669]
我注意到外链链接带有?sign=相关的信息（可能是鉴权信息？），正常下载后文件名显示正常，

但是在linux上使用wget，获取的文件，名字会带上?sign=里面包含的信息，有没有办法避免这种情况？

还有就是分享出去的文件夹是否可以添加上传权限，这项功能确实挺好的用。

最后谢谢作者能做出这么全面的好程序，目前市面的上的网盘，这个网盘功能涵盖算是最全面了

**Comment by CoiaPrant** [comment]
@mycode233 wget -O 文件名称

**Comment by expoli** [comment]
@mycode233 添加上传权限确实挺有用的

**Comment by Hubray** [comment]
可选分享目录的上传权限就好，确实是挺实用的功能

**Comment by topjohncian** [comment]
可能会在 3.3 的 Pro 版本出现
