### ISSUE TITLE
增加docker的支持？

### ISSUE THREAD

**Issue by esrrhs** [cloudreve/Cloudreve#670]

**Comment by hulb** [comment]
有别人自己做的可以用用试试：[cloudreve-docker](https://github.com/xavier-niu/cloudreve-docker)
我参照这个修改了下自己在用：[2d605a78](https://github.com/hulb/Cloudreve/commit/2d605a78f38eeaead1f4b0845287e654455cae51)

**Comment by esrrhs** [comment]
666
