### ISSUE TITLE
onedrive使用cloudflare反向代理后，文档预览失效

### ISSUE THREAD

**Issue by guomaimang** [cloudreve/Cloudreve#674]
onedrive存储策略一旦加上 cloudflare反向代理 就不能对文档预览。

能不能让 下载的链接需要单独以域名+文件路径导出外链，让文档的预览不走反代域名
这确实是一个已知的问题

**Comment by kroyoo** [comment]
没用过文档功能。这个思路参考下，cloudflare 可以添加规则，让一些不通过cloudflare直接走服务器，子域名和请求目录都可以。

**Comment by guomaimang** [comment]
> 没用过文档功能。这个思路参考下，cloudflare 可以添加规则，让一些不通过cloudflare直接走服务器，子域名和请求目录都可以。

我说的文档是指docx、pptx等。另外我说的使用cloudflare不是给网站添加CDN，而是在存储策略中 给onedrive的文件下载 实现反向代理。那个下载链接一般不暴露格式，真的不能用cloudflare添加规则。

我觉得可以让 下载的链接需要单 独以域名 +文件路径导出外链。这里的独立域名就是反向代理的链接。

**Comment by huang545** [comment]
确认这个问题，但是图片可以正常预览。

**Comment by cxw620** [comment]
我用cloudflare workers加自选ip的方法，反代后视频可以预览，但等待很久
