### ISSUE TITLE
3.2.0版本webDAV，404

### ISSUE THREAD

**Issue by wraptor** [cloudreve/Cloudreve#675]
1. 如图，已配置好
![](https://gitee.com/seepine/oss/raw/master/picgo/20201217094808.png)

2. 初次访问需要输入账号密码
![](https://gitee.com/seepine/oss/raw/master/picgo/20201217094846.png)

3. 输入后404，刷新，多次测试，多机访问，都是404
![](https://gitee.com/seepine/oss/raw/master/picgo/20201217094957.png)

**Comment by FikaCode** [comment]
浏览器怕是不行，用windows 自带的文件浏览器映射网络磁盘试试。
