### ISSUE TITLE
建议-希望可以增加一些登录方式

### ISSUE THREAD

**Issue by 18367451686** [cloudreve/Cloudreve#683]
希望可以增加一键登录的方式，比如Microsoft账户登录，短信验证码登录，github账户登录……
我知道开发新登录渠道很复杂，但我实在很难进行二次开发（我对go语言一窍不通），作者加油!

**Comment by RoundCloud-Tech** [comment]
同意，希望加入阿里云短信、腾讯云短信、微信登录、微博登录、Github登录等，如果作者还有余力的话可以尝试同步Wordpress、Discuz等的用户数据
