### ISSUE TITLE
前端怎么实现该项目的流式上传

### ISSUE THREAD

**Issue by PipiHua** [cloudreve/Cloudreve#688]
我想实现像您一样的文件流式上传，后端已经实现了，前端的流式上传是怎么实现的呢，可以简单描述一下吗？

**Comment by PipiHua** [comment]
我看到了您点击了class为uploadFileForm的input元素，但是没有找到上传函数

**Comment by topjohncian** [comment]
frontend:
public/static/js/uploader/uploader_[policy].js
