### ISSUE TITLE
离线下载本地磁盘跑满

### ISSUE THREAD

**Issue by nymanyim** [cloudreve/Cloudreve#693]
使用aria2进行离线下载，中途如果暂停并清除此任务，系统还是会在后台进行下载，一直到跑满磁盘。请问应怎样解决这个问题呢，设置任务超时时间还是？主要是取消任务无效

**Comment by FikaCode** [comment]
应该只能手动删除了，我就是这么干的。
清空 `./aria2.session` 里面的内容，再启动就不会继续任务了。

**Comment by nymanyim** [comment]
对的，必须手动删除这些。

**Comment by HFO4** [comment]
取消任务生效时间大约需要一分钟。大量文件的BT任务可能需要更多时间。
