### ISSUE TITLE
功能优化建议

### ISSUE THREAD

**Issue by lyglay1991** [cloudreve/Cloudreve#695]
1.下载功能：
希望未来版本支持文件批量下载以及文件夹下载功能

2.网盘功能：
希望增加对googledrive的支持，另外就是网盘内容同步这一块，希望能网盘那边有更新内容了，程序端这边也能及时同步显示出来，而不是每次需要手动同步才行

3.离线下载功能：
除了aria2外，是否可以考虑增加其他一些下载工具啊，如：qBittorrent；或者说机器安装了其他下载工具，离线下载界面可以选择调用其程序

**Comment by HFO4** [comment]
> 1.下载功能：
希望未来版本支持文件批量下载以及文件夹下载功能

已经支持打包下载

> 希望增加对googledrive的支持

Duplicate of #23

> 希望能网盘那边有更新内容了，程序端这边也能及时同步显示出来，而不是每次需要手动同步才行

实现起来复杂度较高，暂无打算，或者优先级低。

> 除了aria2外，是否可以考虑增加其他一些下载工具啊，如：qBittorrent；或者说机器安装了其他下载工具，离线下载界面可以选择调用其程序

暂不考虑
