### ISSUE TITLE
站点url设置。

### ISSUE THREAD

**Issue by Hope-you** [cloudreve/Cloudreve#697]
环境：宝塔面板安装的Nginx和docker，程序放在**docker中运行**，用**Nginx反向代理**，**cloudflaer加速**，用**阿里云OSS**存储策略。
问题：站点url如果设置为 **源ip+端口**，可以用域名访问并且**正常上传文件**，但是前段**不显示文件**。用源ip访问可以正常显示文件
站点url如果设置为**反向代理后的域名**，上传文件**提示错误**，但是阿里云OSS控制台**可以看到**文件正常上传。

这是什么问题呢？

**Comment by HFO4** [comment]
> 站点url如果设置为反向代理后的域名，上传文件提示错误，但是阿里云OSS控制台可以看到文件正常上传。

阿里云OSS无法请求回调URL导致。检查站点URL能否被公网访问、SSL证书有效性等。
