### ISSUE TITLE
多编译一些成品好吗？

### ISSUE THREAD

**Issue by niubility000** [cloudreve/Cloudreve#702]
居然没有我能用的版本。能提供官方编译好的linux arm v5，linux arm v7，linux mips等版本吗？看可道云每次都提供20多个版本，filebrowser也很多。

**Comment by KawaiiZapic** [comment]
@niubility000 特殊需求请自己编译,或者换设备.
鸭子不必去麻烦别人为自己的懒惰付出, 毕竟开发者也没吃你家大米.
鸭子也不必去跟别人比较,正因为与别人不同所以才存在.

Go的交叉编译十分简单,如果确实有这种需求也不算太麻烦.

**Comment by niubility000** [comment]
你说话太冲了😎。而且，我不会啊，会者不难，难者不会啊。啥叫交叉编译我都不懂。就算我折腾明白了，也放不到这上面，别人有需求还得折腾，不利于软件传播啊。作者肯定希望更多人用的。

**Comment by KawaiiZapic** [comment]
@niubility000 更多人能用≠满足少部分人的特殊需求
使用特殊平台自然有他的代价,如果折腾不出来还是建议换.

**Comment by niubility000** [comment]
很多人用啊，我是用在路由器上，华硕梅林固件，看看koolshare，恩山上有多少帖子就知道了。还有玩客云，群晖都能用啊。

**Comment by KawaiiZapic** [comment]
@niubility000 现在几乎没有人用Arm v5平台,怎么的也是个Arm64.
不知道"很多人"在哪里

即便如此,100人可能很多,但是有1w人在用amd64,3000人在用Arm64,这样看来100人不算多了.所以我说是迎合大部分人的需求.

你都提到论坛了,说明你也逛过里面,自行折腾的人也肯定不少.
何尝不自己试试呢?
交叉编译的方法在官方文档里有,可以自行查询.
我觉得比起无端的抱怨"为什么没有xxx",自行折腾遇到困难时肯定更多人愿意帮助你.

**Comment by niubility000** [comment]
哪止100人，至少几十万人有斐讯的东西，不然那老板怎么能骗走100亿。玩客云翻车的也很多。
你是觉得我第一贴不礼貌哈？sorry。

**Comment by mritd** [comment]
我觉得标题就很不礼貌

**Comment by niubility000** [comment]
这么神经过敏啊？

**Comment by niubility000** [comment]
那个还鸭子鸭子的？有病得治！

**Comment by niubility000** [comment]
> @niubility000 特殊需求请自己编译,或者换设备.
> 鸭子不必去麻烦别人为自己的懒惰付出, 毕竟开发者也没吃你家大米.
> 鸭子也不必去跟别人比较,正因为与别人不同所以才存在.
> 
> Go的交叉编译十分简单,如果确实有这种需求也不算太麻烦.

你是不是有精神病？

**Comment by niubility000** [comment]
> 我觉得标题就很不礼貌

还有你，精神不正常吗？那标题怎么没礼貌了？你平时说话都跪着吗？

**Comment by KawaiiZapic** [comment]
@niubility000 ?

**Comment by YamazakuraH** [comment]
@niubility000 怎么乱咬人，想要armv5v7自己去编译。

**Comment by niubility000** [comment]
> @niubility000 怎么乱咬人，想要armv5v7自己去编译。

早编完了。这软件还有bug，比如导入的图片没有缩略图，单击有穿透现象（go的毛病，能修复）。得多等几版更新再用。

**Comment by bt-worm** [comment]
> > @niubility000 怎么乱咬人，想要armv5v7自己去编译。
> 
>  早编完了。这软件还有bug，比如导入的图片没有缩略图，单击有穿透现象（go的毛病，能修复）。得多等几版更新再试。

能否分享一下您编译的armv5版本。谢谢！

我编译出的armv5版本，放在梅林上，总是说TLS错误(Thread Local Storage)，应该是交叉编译环境或者参数配置有问题。

**Comment by topjohncian** [comment]
> Thread Local Storage

Try to provide more information (such as logs and pictures).

**Comment by qian-jiahong** [comment]
有人编译出ARMv5版本了吗？能否分享一下编译办法？
我编译出来的，运行时会出错： -sh: ./cloudreve: not found
CGO_ENABLED=0 编译，可以运行，还是出错。提示：go-sqlite3 需要 CGO 才能工作。

**Comment by AH-dark** [comment]
> 居然没有我能用的版本。能提供官方编译好的linux arm v5，linux arm v7，linux mips等版本吗？看可道云每次都提供20多个版本，filebrowser也很多。

Developers of open source software are not obligated to provide you with multi-version compiled products. Ask for help if you need it, but don't make rude demands.

Since most people use amd64, arm64, this makes sense. And most software only provides amd64, the special case you mentioned cannot be the standard of ethics in the opensource community.

**Comment by qian-jiahong** [comment]
> @niubility000 特殊需求请自己编译,或者换设备. 鸭子不必去麻烦别人为自己的懒惰付出, 毕竟开发者也没吃你家大米. 鸭子也不必去跟别人比较,正因为与别人不同所以才存在.
> 
> Go的交叉编译十分简单,如果确实有这种需求也不算太麻烦.

十分简单的话，你编译一个试试能不能正常运行？
