### ISSUE TITLE
编译后的版本不能在alpine3.12.3上运行

### ISSUE THREAD

**Issue by xdsnet** [cloudreve/Cloudreve#703]
下载的编译后cloudreve_3.2.0_linux_amd64.tar.gz版本，解压后默认不能在alpine3.12.3上运行
估计是因为编译不是纯静态编译，可能有一些依赖在alpine默认环境中并没有合适的共享库来实现，建议提供全静态编译的版本。

**Comment by mritd** [comment]
alpine 是 musl c，默认应该是在 glibc 下编译的，如果全静态编译可能会有点问题，因为采用了 sqlite3，sqlite3 的驱动是 cgo 的；如果有可能作者应该还是提供更多的交叉编译版本 😁
