### ISSUE TITLE
Webdav Windows10自带dav客户端401错误

### ISSUE THREAD

**Issue by SakurabaKiyoka** [cloudreve/Cloudreve#706]
通过TCP抓包得知Windows的Dav客户端的认证 base64似乎会多传一个\t进去（明文表现多出了一段CQ==的base64），进而导致密码出错。反代软件Nginx，域名是带SSL的，WinSCP没问题可以正常打开。不知道这个是Windows的bug还是nginx反代问题。
![0](https://user-images.githubusercontent.com/16064020/103451162-f07e9400-4d03-11eb-8666-88829ecfc3d8.png)
![1](https://user-images.githubusercontent.com/16064020/103451163-f2485780-4d03-11eb-88a9-dca9be68ea99.png)

**Comment by rabbitgg75** [comment]
我也遇到了，应该是产生密码的问题，复制出来就会多一个\t，你可以先粘贴到一个文本文件中，删除后面的\t，再使用这个密码

**Comment by HFO4** [comment]
@rabbitgg75 感谢反馈，稍候会调查一下这个问题

**Comment by SakurabaKiyoka** [comment]
尝试复制了一下，确实在webdav界面上复制后面会多一个\t，应该是前端的问题了。感觉加一个复制按钮比较好。

**Comment by HFO4** [comment]
已在 https://github.com/cloudreve/frontend/commit/68dc674577f1a78089d6168948a81b362c173edb 后增加复制按钮
