### ISSUE TITLE
无法被 Systemd 启动

### ISSUE THREAD

**Issue by SunsetYe66** [cloudreve/Cloudreve#708]
如题，在重启主机之后发现 cloudreve 没有启动起来。执行 systemctl status cloudreve 显示：
Jan 03 16:42:39 VM-0-2-ubuntu cloudreve[838]: github.com/cloudreve/Cloudreve/v3/pkg/util.(*Logger).Panic(0xc0001b25a0, 0x12357c1, 0x1c, 0xc00040be30, 0x1, 0x1)
Jan 03 16:42:39 VM-0-2-ubuntu cloudreve[838]:         /home/runner/work/Cloudreve/Cloudreve/pkg/util/logger.go:74 +0xe2
Jan 03 16:42:39 VM-0-2-ubuntu cloudreve[838]: github.com/cloudreve/Cloudreve/v3/models.Init()
Jan 03 16:42:39 VM-0-2-ubuntu cloudreve[838]:         /home/runner/work/Cloudreve/Cloudreve/models/init.go:53 +0x1e7
Jan 03 16:42:39 VM-0-2-ubuntu cloudreve[838]: github.com/cloudreve/Cloudreve/v3/bootstrap.Init(0xc0000382a0, 0x17)
Jan 03 16:42:39 VM-0-2-ubuntu cloudreve[838]:         /home/runner/work/Cloudreve/Cloudreve/bootstrap/init.go:25 +0x85
Jan 03 16:42:39 VM-0-2-ubuntu cloudreve[838]: main.init.0()
Jan 03 16:42:39 VM-0-2-ubuntu cloudreve[838]:         /home/runner/work/Cloudreve/Cloudreve/main.go:23 +0x1f4
Jan 03 16:42:39 VM-0-2-ubuntu systemd[1]: cloudreve.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
Jan 03 16:42:39 VM-0-2-ubuntu systemd[1]: cloudreve.service: Failed with result 'exit-code'.

系统：Ubuntu 20.04 LTS；Cloudreve 主文件权限：755，拥有者：root，系统登陆所使用的用户名：Ubuntu

**Comment by HFO4** [comment]
参考 https://forum.cloudreve.org/d/863
