### ISSUE TITLE
移动端无法播放在线播放视频

### ISSUE THREAD

**Issue by Lewin671** [cloudreve/Cloudreve#709]
版本: 3.2.0
经过使用，无法在移动端（手机、iPad）在线播放视频，而在pc端就没问题。

**Comment by HFO4** [comment]
无法复现，需要更多信息。

**Comment by Lewin671** [comment]
> 无法复现，需要更多信息。
这是我在iPhone上播放视频的结果，显示无法播放视频。而在PC端就没有这个问题。
![WechatIMG217](https://user-images.githubusercontent.com/37481138/103747749-14144800-503e-11eb-963f-3490dd665e6a.jpeg)

**Comment by haikouwang** [comment]
我也是一样的，安卓和windows都可以，就是iOS不行
