### ISSUE TITLE
windows server 2019 V3.2捐赠版闪退

### ISSUE THREAD

**Issue by waitsaber** [cloudreve/Cloudreve#710]
在Winserver 2019中直接双击cloudreve.exe弹窗后直接秒退，文件夹中无生成任何文件，用V3.2免费版就不会出现这个问题可以正常运行。

**Comment by KawaiiZapic** [comment]
@waitsaber 你不会让他不闪退么

**Comment by HFO4** [comment]
检查 `key.bin` 是否放在了同级目录下
