### ISSUE TITLE
后台提示错误——forEach

### ISSUE THREAD

**Issue by Concept09** [cloudreve/Cloudreve#711]
进入后台-点击首页面板提示红框 写着：Cannot read property 'forEach' of undefined

我在后台添加了一个用户，然后用刚添加的用户邮箱找回密码 然后就出错了 （邮件激活已经配置）

**Comment by wsndshx** [comment]
`Cannot read property 'forEach' of undefined` 大概是因为官网的ssl证书过期了, 导致后台无法去官网拉取更新公告.

**Comment by HFO4** [comment]
公告加载出错，现在已经修复
