### ISSUE TITLE
关于Backblaze B2云储存挂载的问题

### ISSUE THREAD

**Issue by 212-mei** [cloudreve/Cloudreve#713]
昨天我尝试用aws s3协议挂载Backblaze B2存储桶，发现上传的时候总是出现http错误，经过我的多次填写信息，确认信息并没有填错，错误仍然无法解决。我尝试用chevereto的s3协议挂载Backblaze B2存储桶，也出现同样的错误，不过报错更详细，说是某个位置缺少了ssl证书。而尝试使用zfile挂载下载成功。经过我查询Backblaze B2官方文档，发现他们仅支持aws s3的最新版本v4协议，百度查到说每个版本的协议的SSL证书位置不一样。目前尚不清楚所指的证书是哪个域名的证书以及需要放到哪个位置才能实现挂载上传，也不知道cloudreve目前支持的aws s3协议的版本是多少。如果有解决办法麻烦告知一下？

**Comment by czk1997** [comment]
走S3的话应该不用证书才对。我用的是WASABI的S3兼容存储原理是一致的。
这软件使用的是aws4的签名。有错误我建议你贴上来。官方文档有很多东西没说，有的得自己研究才行。
