### ISSUE TITLE
【建议】捐赠版用户组绑定两个存储策略后分开显示内容

### ISSUE THREAD

**Issue by waitsaber** [cloudreve/Cloudreve#715]
现在捐赠版的用户组绑定了两个存储策略后上传的文件跟导入的文件在前端显示是全部混到一块去的，
建议一、是两个存储策略切换的时候只显示当前所在存储策略内的文件，如：一个用户组绑定了本地存储策略跟OneDrive存储，当我切换成本地存储的时候只显示上传到本地存储的文件，当我切换成OneDrive存储策略的时候只显示OneDrive内的文件。
建议二、导入文件的时候，当用户组绑定两个策略的时候导入文件时可以选择导入到哪个存储策略里。
建议三、当用户组绑定两个存储策略的时候可以对两个存储策略分别进行空间容量的分配，而不是用户组指定一个公共容量数值，这样会导致失去两个存储策略的意义，因为不管是传到哪个存储里容量只有固定的那点，会导致用户感觉不到两个存储策略跟一个存储策略的区别。

**Comment by RoundCloud-Tech** [comment]
附议
