### ISSUE TITLE
下载完成后提示  data to long for column porps  at row 1

### ISSUE THREAD

**Issue by Simoneshen** [cloudreve/Cloudreve#716]
离线下载文件后提示 error 1406： data to long for column porps  at row 1，
下载的原始文件存在，数据库是mysql 5.7，存储策略：默认存储策略，没有自动重命名；
请问是什么原因》谢谢！

**Comment by HFO4** [comment]
请问是 3.2.0 版本还是？

**Comment by Simoneshen** [comment]
> 请问是 3.2.0 版本还是？

是3.2.0版本

**Comment by wangxiaoerYah** [comment]
我也是提示这个

**Comment by wangxiaoerYah** [comment]
下载的bt种子，有158GB，然后全部下载完成了，就提示这个问题，查看Aria2c是下载成功的

**Comment by wangxiaoerYah** [comment]
现在3.3.2版本，任然有这个问题。
种子文件: magnet:?xt=urn:btih:879377bdc35ec3e4c1cc5c1f0c14476b3e67384b&tr=http://tracker.36dm.com:2710/announce
大小:158G
错误:1406 data too long
@HFO4 这个问题可以看看，如果捐赠版解决了，可以通知下，可以入正。

**Comment by HFO4** [comment]
新安装的版本已经修复。从老版本升级需要删除`downloads`表后升级才可生效，或者可通过手动执行SQL Query 更新`attr`字段为 `long_text`

**Comment by wangxiaoerYah** [comment]
🤪🤪🤪
