### ISSUE TITLE
离线下载出现http timeout awaiting response headers错误提示

### ISSUE THREAD

**Issue by Simoneshen** [cloudreve/Cloudreve#719]
离线下载出现http timeout awaiting response headers错误，前台显示不下载，但aria2后台还在下载，请问是vps机器设备问题还是下载的文件问题还是程序问题？

**Comment by HFO4** [comment]
> 离线下载出现http timeout awaiting response headers错误

具体是哪个过程出现？创建任务时？离线下载进行时？

> 前台显示下载，但aria2后台还在下载

这是预期中的现象吧

**Comment by Simoneshen** [comment]
> > 离线下载出现http timeout awaiting response headers错误
> 
> 具体是哪个过程出现？创建任务时？离线下载进行时？
> 
> > 前台显示下载，但aria2后台还在下载
> 
> 这是预期中的现象吧

离线下载出现http timeout awaiting response headers错误
> 
> 具体是哪个过程出现？创建任务时？离线下载进行时？

> **是离线下载进行时，进行一段时间后出现这个错误。**


> > 前台显示下载，但aria2后台还在下载
> 
> 这是预期中的现象吧

**说错了，出现这个错误后，发现 前台显示不下载，但aria2后台还在下载。**
