### ISSUE TITLE
账号出错

### ISSUE THREAD

**Issue by Yofo-me** [cloudreve/Cloudreve#721]
下载安装后，手动创建配置文件（MYSQL），直接配置守护进程并设置直射以手动创建的文件启动，发现进不去，没有账号且同级目录下没有db文件

systemctl stop cloudreve && ./cloudreve
执行后会输出管理员账户 admin@cloudreve.org 和密码，但是输入后提示 账户或密码错误

**Comment by HFO4** [comment]
指定使用 MySQL 后不会创建db文件；

> systemctl stop cloudreve && ./cloudreve
执行后会输出管理员账户 admin@cloudreve.org 和密码，但是输入后提示 账户或密码错误

原因不明且无法复现，无法给出更多帮助。
