### ISSUE TITLE
建议增加发送邮件服务器加密验证协议

### ISSUE THREAD

**Issue by waitsaber** [cloudreve/Cloudreve#723]
经过测试cloudreve只支持非加密的邮件服务器跟使用SSL加密的服务器进行发送验证邮件，像office365的服务器只能使用 STARTTLS加密，因为cloudreve不支持 STARTTLS加密会导致发送验证邮件失败。错误如下图。
![图片](https://user-images.githubusercontent.com/67093172/104131556-f2a2bb80-53b1-11eb-8480-2dcab7a5dabd.png)

**Comment by KawaiiZapic** [comment]
@waitsaber office365直接往587发,不开加密.
虽然 加密协议只有开和关的区别 这点确实非常迷惑,不过勉强能用.

**Comment by waitsaber** [comment]
试过了是没有用的会被直接提示身份验证失败

**Comment by waitsaber** [comment]
试过了是没有用的会被直接提示身份验证失败![图片](https://user-images.githubusercontent.com/67093172/104213141-f5b0b100-5470-11eb-9a88-f3a13e5ed70a.png)
![图片](https://user-images.githubusercontent.com/67093172/104213181-fe08ec00-5470-11eb-95c9-8fb96bfdb2f3.png)

**Comment by kddxnb** [comment]
这种直接建一个不带身份验证的专门用来发邮件的小号就是了，邮箱还能取类似no-reply@xxxx的格式，看起来更正规。现在我遇到的问题就是，这种方法和ipv6不兼容，不知道为什么我的服务器默认从ipv6解析smtp.office365.com,导致一直连不上邮件服务器
