### ISSUE TITLE
请问下怎么设置本地存储目录的路径

### ISSUE THREAD

**Issue by mikolaje** [cloudreve/Cloudreve#724]
在文档上没找到。

**Comment by HFO4** [comment]
在对应的存储策略中更改。

**Comment by AuroraTea** [comment]
> > 在对应的存储策略中更改。
> 
> 请问如何修改存储策略？官方文档为空

大概率你已经知道了, 但是为了后面搜到这的人我还是说一下:
是点右上角头像然后点管理面板里菜有存储策略的修改
其实感觉这个还挺反直觉的

**Comment by lixuanbin** [comment]
在可执行文件同一路径下的uploads文件夹，按用户隔离。
