### ISSUE TITLE
是否支持h2c？

### ISSUE THREAD

**Issue by kirin10000** [cloudreve/Cloudreve#728]
请问是否支持http2？如何配置。

**Comment by huang545** [comment]
支持

**Comment by kirin10000** [comment]
> 支持

请问如何配置呢？我的tls是在前端解密的(haproxy)，后端直接监听。打开网站显示http2协议错误

**Comment by kirin10000** [comment]
标题已改。应该是 `HTTP2 Cleartext`或者`H2C`

**Comment by topjohncian** [comment]
建议把 Nginx 进行反代

**Comment by HFO4** [comment]
可通过上层 Web 服务器反代实现支持，内置 Web 服务器暂不支持。
