### ISSUE TITLE
能否支持b2储存

### ISSUE THREAD

**Issue by znc15** [cloudreve/Cloudreve#730]
我曾经在2018的issue里看到过当时的回答，但是我现在在github上找到了也是由Go语言编译的B2储存端，能否看看cloudreve能不能用
相关链接https://github.com/kothar/go-backblaze

**Comment by AH-dark** [comment]
附议

**Comment by HFO4** [comment]
不是SDK的问题，主要是客户端直传的安全性问题。19年的时候只能实现不可信的直传，类似现在的S3策略，未来会继续调查是否可以引入 B2 存储。

**Comment by znc15** [comment]
> 不是SDK的问题，主要是客户端直传的安全性问题。19年的时候只能实现不可信的直传，类似现在的S3策略，未来会继续调查是否可以引入 B2 存储。

但是为什么那个可以用呢

**Comment by wangxiaoerYah** [comment]
附议，B2的存储真的是便宜，而且速度也还行，求支持

**Comment by ecareyu** [comment]
跪求支持呢，这家真的还算蛮便宜的，挺良心的

**Comment by wangxiaoerYah** [comment]
> 不是SDK的问题，主要是客户端直传的安全性问题。19年的时候只能实现不可信的直传，类似现在的S3策略，未来会继续调查是否可以引入 B2 存储。

没猜错大大应该姓刘，那就叫刘大好了😂😂😂

刘大，我今天尝试用Amazon S3挂载了b2储存。结果还是有些惊喜的。

在cloudreve设置中

Endpoint 填写，b2的地址
然后正常填写桶名
密匙

然后密匙需要注意的是，不能填写b2的主密匙
要新建一个应用密匙，注意勾选兼容s3协议的选项，然后访问控制定位到目标储存桶，其它默认。
b2的储存桶cors规则选择允许所有来源共享储存桶(在官方没有明确兼容前，先这样设置，测试)

然后，一切完成过后，测试上传文件，正常的http错误❌无法上传的。

然后，我到离线下载中测试下，直接下载https://baidu.com,居然直接上传成功。

那就是说b2储存其实可以曲线救国使用的。
刘大，可以再看看b2文档吗？您之前那个Head 问题解决没有。
如果没有，可以先用中转上传的方式把这个接口先接出来用吗？

主要是b2太便宜了，阿里云，腾讯云的储存，太贵了啊，不用他们的传输加速，速度起不来。用了的话1.25元/GB真心不划算。😂😂😂昨个一晚上下几部片子就是将近100大洋。

@HFO4 @HFO4 给刘大发奖金发奖金，加鸡腿

**Comment by HFO4** [comment]
@wangxiaoerYah 感谢你的实验。3.4版本估计会尝试引入B2存储。

**Comment by wangxiaoerYah** [comment]
> @wangxiaoerYah 感谢你的实验。3.4版本估计会尝试引入B2存储。

已经入正，支持刘大。

**Comment by znc15** [comment]
pan的意思是直接下载百度网盘的文件？

**Comment by HFO4** [comment]
最新版本重构了S3，使用了分片上传，经测试是可以完美适配B2的。

**Comment by wangxiaoerYah** [comment]
😘
