### ISSUE TITLE
請問是否有指令批次新增使用者帳號或者支援 LDAP ?

### ISSUE THREAD

**Issue by changchichung** [cloudreve/Cloudreve#732]
第一次建立系統之後，想要幫部門同事也弄個帳號來幫忙測試
大概有十來個帳號，除了手工一個一個建立之外，是否有指令可以新增？
或者是可以匯入檔案來新增？
又或者是有沒有支援 LDAP 認證？

**Comment by HFO4** [comment]
批量导入账户暂不支持；
LDAP 目前仍不支持，不排除会在未来加入 #619
