### ISSUE TITLE
English Translation?

### ISSUE THREAD

**Issue by Darthagnon** [cloudreve/Cloudreve#734]
I was wondering if I could help do an English translation. It looks like a good project. I don't speak Chinese, but I'm computer-literate, and can pick out correct translations from Google Translate.

Not too sure which files contain most of the user-readable text, though - if anyone could point me in the right direction, I'd sure appreciate it.

**Comment by Darthagnon** [comment]
I'm starting [here](https://github.com/Darthagnon/CloudreveEnglish/)

**Comment by HFO4** [comment]
Thanks for your translation!
We are still working on the i18n/l10n support, it might come into being in the next major update.

**Comment by imtomjorge** [comment]
Hello @HFO4,
Any update? :)

**Comment by HFO4** [comment]
The i18n is finally finished. English support will be shipped with coming version 3.6.0.
