### ISSUE TITLE
windows端的potplayer连接webdav后只显示文件夹不显示文件

### ISSUE THREAD

**Issue by smartutu** [cloudreve/Cloudreve#736]
windows端的potplayer连接webdav后只显示文件夹不显示文件（域名为http开头），而且https开头的webdav地址连接不上  软件为win10下的potplayer播放器   ios端的nplyaer 和 notability 一切正常

**Comment by JackieDark** [comment]
我也遇到了

**Comment by shenuadm** [comment]
我也有这个问题，只显示文件夹不显示文件是什么情况，顶上去让作者解决一下

**Comment by beyondth** [comment]
同样有这个问题

**Comment by aljxtop** [comment]
什么原因啊，我也是

**Comment by beyondth** [comment]
换官网的PotPlayer版本就好了
