### ISSUE TITLE
有考虑开发移动端的APP吗？

### ISSUE THREAD

**Issue by vperson** [cloudreve/Cloudreve#737]
目前把cloudreve作为nas在使用，备份东西还是比较麻烦需要手动备份，希望APP在同一个局域网中就自动备份的功能

**Comment by 1362032536** [comment]
https://cr.z2z.cc  这里

**Comment by ZhiboWong** [comment]
> https://cr.z2z.cc 
请问CR+Cloudreve可以拿来当作我都毕业设计吗？我的题目是私有云

**Comment by HFO4** [comment]
> > https://cr.z2z.cc
> > 请问CR+Cloudreve可以拿来当作我都毕业设计吗？我的题目是私有云

不行

**Comment by ZhiboWong** [comment]
> > > https://cr.z2z.cc
> > > 请问CR+Cloudreve可以拿来当作我都毕业设计吗？我的题目是私有云
> 
> 不行

请问是为啥不行呢？恳请赐教，我觉得CR+Cloudreve挺合适私有云的呀

**Comment by HFO4** [comment]
@ZhiboWong 你是不是对毕业设计有什么误解？？？
毕业设计请自己去做。

**Comment by StandWithYOU** [comment]
> > > > https://cr.z2z.cc
> > > > 请问CR + Cloudreve可以拿来当作我都毕业设计吗？我的译文是私有云
> > 
> > 
> > 不行
> 
> 请问是为啥不行呢？恳请赐教，我觉得CR + Cloudreve挺合适私有云的呀
这是人家的项目为啥要给你做毕设

**Comment by 1362032536** [comment]
> > https://cr.z2z.cc
> > 请问CR + Cloudreve可以拿来当作我都毕业设计吗？我的译文是私有云

我们有开放对应的lua的api，您可以对照那个api来做您的毕业设计
[https://github.com/1362032536/Cloudreve-API](url)

**Comment by 0x01x0** [comment]
我尼玛人都要笑抽筋了 2333333333333333333333333

**Comment by sakura-yuina** [comment]
当场过来嘲笑

**Comment by Henry14all** [comment]
> > https://cr.z2z.cc
> > 请问CR+Cloudreve可以拿来当作我都毕业设计吗？我的题目是私有云

We think there may be a problem with your idea.
1. CR+ is a semi-open source product, and there are open source and non-open source versions of it. But the author also replied "We have an open api for lua, you can compare your graduation design with that api
https://github.com/1362032536/Cloudreve-API"

2. I hope you don't misunderstand the graduation project, it's not a direct submission of someone else's work, and according to the Cloudreve developers themselves, it's not allowed to be used.

3. Even though Cloudreve is suitable for public cloud, it doesn't mean it can be your graduation work, please write it yourself and use your own discretion.

Please understand if my language is too crude.Please also think for yourself and do not cause jokes.
(You are still quite cute, I laughed on the spot)
