### ISSUE TITLE
将宿主机文件导入进Cloudreve后，在宿主机删除文件，Cloudreve无法删除

### ISSUE THREAD

**Issue by 3061732350** [cloudreve/Cloudreve#739]
如题
将宿主机文件导入进Cloudreve后，在宿主机手动删除文件，Cloudreve的还显示在文件列表里，且无法删除，后台强制删除也无法删除。
![QQ截图20210126201116](https://user-images.githubusercontent.com/24598890/105843433-aba00180-6012-11eb-990b-bf45ff22a4ae.jpg)
![QQ截图20210126200944](https://user-images.githubusercontent.com/24598890/105843300-7b586300-6012-11eb-935c-ca2462d7ffad.jpg)
系统：Windows Server 2012

**Comment by jerryliang122** [comment]
进数据库手动删除

**Comment by lonelykid** [comment]
可以有个脚本校核文件，数据库存在，实际已不存在的，删除数据库条目。数据不存在，实际还存在的，删除文件或添加数据库条目。当然实际删除前，可以询问确认。这样保持数据库和实际文件始终同步。

**Comment by HFO4** [comment]
已在 e699287ffdc49bf0c5df4c65d2b464103e79e2bc 优化，删除不存在的文件直接被视为删除成功。
