### ISSUE TITLE
关于SMTP无法关闭问题

### ISSUE THREAD

**Issue by Jungle-Leesin** [cloudreve/Cloudreve#743]
![image](https://user-images.githubusercontent.com/62128074/106349680-d4721080-630a-11eb-86e1-f98df863eece.png)
我开启了SMTP邮件发送，能够成功发送邮件，但是日志里有这个警告，我想知道这个可以解决嘛，谢谢！非常感谢能开发出这么好的软件，再次衷心的感谢您的辛勤付出！

**Comment by HFO4** [comment]
警告输出暂时没法单独关闭

**Comment by Jungle-Leesin** [comment]
> 警告输出暂时没法单独关闭
好的，十分感谢您的回复！祝您生活愉快！
