### ISSUE TITLE
遇到包含空格的文件名时处理出错

### ISSUE THREAD

**Issue by user1121114685** [cloudreve/Cloudreve#747]
`[Warning] 2021-02-02 20:10:39 钩子执行失败：目标名称非法
[Warning] 2021-02-02 20:10:39 导入任务无法创插入文件[ShaoXia/全网最适合中国人的免费音标课(纯干货, 超详细!)/[P1]01 到底应该怎么学音标?.mp4], 目标名称非法`
**[P1]01 到底** 这中间有个空格，就无法处理了！

**Comment by xvzhenduo** [comment]
为什么我就可以上传包含空格的文件？

**Comment by wsndshx** [comment]
不是因为空格, 是因为名称太长了. 你把空格前面的文件名删掉一些就能上传了

**Comment by wsndshx** [comment]
不对, 你这前面是超长的目录名称emmmm. 你试试上传文件名为 `[ p1].mp4` 的看看
