### ISSUE TITLE
离线下载功能性建议

### ISSUE THREAD

**Issue by huang545** [cloudreve/Cloudreve#751]
你好，cloudreve中的离线下载部分依赖于本机进行数据中转，但是国内大多数服务器都是小水管以及国外部分大带宽服务器性能配置较低问题，可能在上传文件时出现无法访问的情况，我建议可以将主机与离线下载服务器进行分离，这样可以有更多的可操作性。
例如：
A服务器作为访问网站，B服务器作为离线下载服务器，A网站的用户存储桶是OneDrive，B服务器完全镜像了A网站的用户数据以及存储桶信息，当A站用户提交离线下载地址后，A站向B站下达离线下载命令，B网站在对资源进行下载上传中转操作后，将成功的信息发送给A站（我不清楚A站是否可以直接去读取到新文件，如果不可以，可以让B服务器向A站发送完整信息）

这样子可以避免如果自己的服务器是小水管服务器无法使用离线下载而去再新开一个服务器，相信这个功能可以有更多人可以使用到。

**Comment by wsndshx** [comment]
为啥不直接把cloudreve部署在服务器B上?

**Comment by huang545** [comment]
> 为啥不直接把cloudreve部署在服务器B上?

一般选用离线服务器会选用国外G口服务器，到国内的访问会大打折扣
这里举例的A服务器是国内的服务器，一般都是小水管，根本没办法进行离线下载的任务

作者在群里交流过了，如果将数据库让A、B服务器共同使用的话，是可以实现的

**Comment by wsndshx** [comment]
> > 为啥不直接把cloudreve部署在服务器B上?
> 
> 一般选用离线服务器会选用国外G口服务器，到国内的访问会大打折扣
> 这里举例的A服务器是国内的服务器，一般都是小水管，根本没办法进行离线下载的任务
> 
> 作者在群里交流过了，如果将数据库让A、B服务器共同使用的话，是可以实现的

emmm个人感觉不如用A反代B操作性好一些, 毕竟最后取文件回来的时候走的是od的cdn. (另外从实际成本上考虑的话, A用国内大厂的CDN可能会更好一些? )

**Comment by huang545** [comment]
> > > 为啥不直接把cloudreve部署在服务器B上?
> > 
> > 
> > 一般选用离线服务器会选用国外G口服务器，到国内的访问会大打折扣
> > 这里举例的A服务器是国内的服务器，一般都是小水管，根本没办法进行离线下载的任务
> > 作者在群里交流过了，如果将数据库让A、B服务器共同使用的话，是可以实现的
> 
> emmm个人感觉不如用A反代B操作性好一些, 毕竟最后取文件回来的时候走的是od的cdn. (另外从实际成本上考虑的话, A用国内大厂的CDN可能会更好一些? )

延迟太高，，，A服务器如果在国内，B服务器在国外，就算是G口海外服务器，到晚高峰的情况下没有精品线路一样会缓慢
而且即使是精品线路，受到物理距离的影响，延迟至少在50ms+左右（这还是香港的服务器，但是香港服务器很贵，一般都是美国机房，这时候延迟100ms+）体验完全不一样
