### ISSUE TITLE
如果删除一个正在进行中的传输任务，那么后面排队中的传输任务会一直处于等待状态不会触发上传

### ISSUE THREAD

**Issue by yubanmeiqin9048** [cloudreve/Cloudreve#752]
试了几次都是这样

**Comment by haodedong** [comment]
我也遇到了，并且 左下角显示占用了空间，但是/目录下却没有显示这个文件！！！！
上传的文件仅仅100多MB，名称是dmg的文件

**Comment by haodedong** [comment]
http://haodedong.cn:5000/s/B4fG

**Comment by haodedong** [comment]
http://haodedong.cn:5000/s/B4fG

**Comment by yubanmeiqin9048** [comment]
> 单个文件上传，和小容量文件夹上传时没这个问题，但在这个情况下如果我在上传过程中离开主页面(不是关闭浏览器)，比如进入个人中心，上传任务会被删除



> 我也遇到了，并且 左下角显示占用了空间，但是/目录下却没有显示这个文件！！！！
> 上传的文件仅仅100多MB，名称是dmg的文件

我俩的应该不是一个情况

**Comment by yubanmeiqin9048** [comment]
> 我也遇到了，并且 左下角显示占用了空间，但是/目录下却没有显示这个文件！！！！
> 上传的文件仅仅100多MB，名称是dmg的文件

你和我说的应该不是一个情况

**Comment by HFO4** [comment]
这边没法 100% 复现，目前还不清楚什么情况下会出现这种现象，欢迎大家补充
