### ISSUE TITLE
给Cloudreve  pro几点建议

### ISSUE THREAD

**Issue by a87750530** [cloudreve/Cloudreve#756]
1、建议增加[backblaze](https://www.backblaze.com/) 的B2储存
2、建议增加热门数据的本地缓存功能，为类似backblaze  的B2或者是亚马逊S3，或者是阿里云，腾讯云的本地硬盘缓存，以便于减少从各种oss储存调取的费用
3、文件夹共享后，文件夹里面的文件在共享搜索里面无法搜索到文件，建议文件夹共享后，里面的文件也一并能在共享里面搜索到！

**Comment by naicfeng** [comment]
B2可以直接用s3协议访问啊
