### ISSUE TITLE
Some suggest about develop

### ISSUE THREAD

**Issue by AH-dark** [cloudreve/Cloudreve#759]
We may need a location to **put more filing information**, and we also need to **add more navigation**. In order to better business operation, we also need **email domain blacklist** service and **SMS service**, which is to prevent spam users.

It's said that the author is disgusted with SMS. I also think SMS is annoying, but it's still a good way to verify identity and prevent malicious registration.Both _Aliyun SMS_ and _Tencent Cloud SMS_ are very good. It is recommended to use them.

It is very difficult for us to add products. We ask you to add the function of editing products.

Thanks to the efforts of the author, with the increase of functions, you can also _increase the pricing of Cloudreve Pro_ or increase _the intermediate version_, which is beneficial to incerase your income.

Write by AHdark in RoundCloud Tech. Co,Ltd.

PS: If you need enterprise qualification for your development, please contact [qq:2254666380](http://sighttp.qq.com/authd?IDKEY=04b0b0e749b72212bed9a81d75bcfd3de162cdc0dc01abaa), we can provide you with relevant enterprise qualification and authority.

With all due respect, you need to speed up the development. The progress is a little slow now.

Best wishes to you.

**Comment by AH-dark** [comment]
@HFO4 I don't know why you use English. But if you use English, I'll also speak English to talk.

**Comment by HFO4** [comment]
Email domain blacklist is under developing. SMS service and other feature requests is not adopted for now.
