### ISSUE TITLE
对cloudreve功能的一些建议

### ISSUE THREAD

**Issue by xvzhenduo** [cloudreve/Cloudreve#760]
建议增加
1.office在线编辑（可以用only office）
2.如果可以的话（虽然不太可能）可以将迅雷作为离线下载的核心，并且支持批量添加任务
3.希望不要限制每次删除的文件个数（比如说我每次删我的漫画时都得删掉数据库因为有2000+的图片）
4.希望加快导入文件的速度我算了导入2000个文件大概需要一个多小时，而cloudever只使用了磁盘读写0.5~1MB/s，CPU0.1%~3%，内存约40MB可以加快同时并行的任务数，但不知为什么在导入时打开页面时加载的特别慢而且卡。
5.还希望增加7Z，rar，XZ其他等常见格式的解压缩
6.希望文件多的时候可以每次加载出一部分，不然就会卡死
（本人小白一枚，如果说的有问题的地方见谅）

**Comment by XZB-1248** [comment]
迅雷？算了吧，吸血鬼一个。

**Comment by xvzhenduo** [comment]
虽然是吸血鬼但不得不承认有时候BT和磁力只有迅雷有速度

**Comment by KyonCN** [comment]
抛开吸血不谈 迅雷不开源 没有Linux版本 怎么添加
以前为了推硬件出的xware早没了

**Comment by HFO4** [comment]
> 3.希望不要限制每次删除的文件个数（比如说我每次删我的漫画时都得删掉数据库因为有2000+的图片）

切换到 MySQL 可以临时解决此问题。

> 希望文件多的时候可以每次加载出一部分，不然就会卡死

使用 LazyLoad 后，如果用户在未加载完全时使用了全选快捷键，这样就没法选择当前目录下的所有文件了。目前还没想到别的解决办法

**Comment by xvzhenduo** [comment]
> > 3.希望不要限制每次删除的文件个数（比如说我每次删我的漫画时都得删掉数据库因为有2000+的图片）
> 
> 切换到 MySQL 可以临时解决此问题。
> 
> > 希望文件多的时候可以每次加载出一部分，不然就会卡死
> 
> 使用 LazyLoad 后，如果用户在未加载完全时使用了全选快捷键，这样就没法选择当前目录下的所有文件了。目前还没想到别的解决办法

可以在用户使用快捷键时再加载
