### ISSUE TITLE
编辑图标位置问题

### ISSUE THREAD

**Issue by ntgeralt** [cloudreve/Cloudreve#763]
![image](https://user-images.githubusercontent.com/8230651/107800699-1171e480-6d9a-11eb-972e-b65f77dd44d6.png)
编辑放前面，删除放最后
可能这样更符合人体工程学 :)

**Comment by HFO4** [comment]
已在 https://github.com/cloudreve/frontend/commit/01f6ae048f8cf31712125b6b9a401303d425b72e 后优化
