### ISSUE TITLE
sqlite如何转换成mysql？

### ISSUE THREAD

**Issue by qitayun** [cloudreve/Cloudreve#770]
sqlite报错database is locked
用的是默认的sqlite，现在数据库已经150多MB了

**Comment by Beattheend** [comment]
太麻烦了，建议重开

**Comment by qitayun** [comment]
> 太麻烦了，建议重开

我数据库都那么大了。

**Comment by Beattheend** [comment]
> 我数据库都那么大了。
https://zhidao.baidu.com/question/746041566207947372.html 我以前转过 忘记怎么弄了

**Comment by ThreeGold127** [comment]
迁移的主要问题在于时间字段的类型：sqlite 里的所有的时间字段的类型都是 datetime，mysql 里是 timestamp

初始化 mysql 表，用 navicat 把 mysql 的表结构导出成 .sql 文件。
用 navicat 把 sqlite 的表数据导出成 .sql 文件，删除其中非 insert 开头的语句；用正则把时间字段的格式改成新格式（不改也行，就是各种时间都会变成1900年）。

依次执行下2个sql文件就行了
