### ISSUE TITLE
Sharepoint支持

### ISSUE THREAD

**Issue by KusakabeSi** [cloudreve/Cloudreve#771]
支持SharePoint应该是许多人的需求

不像OD，SP不用工单扩容，就有25T

工单扩容是人工处理，教育全局有一定风险
而且微软政策改变，[E5 Developer也不再允许工单扩容25T了](https://www.hostloc.com/forum.php?mod=viewthread&tid=803363)
![image](https://user-images.githubusercontent.com/73118488/108668745-b2893980-7516-11eb-9c81-c881979b2fe3.png)

隐私问题的话，许多人全局就只有一个人用，应该不会造成严重问题
或是加个警语，比直接不支持来的好些

**前面也有issue提到SP，但是都关闭了**。
没见到作者明确拒绝，所以我再开一次

使用魔改版总是会有更新上的麻烦，望大佬重新考虑，十分感谢

**Comment by KyonCN** [comment]
已经加到3.3版本的 todo了
