### ISSUE TITLE
oneDrive上传:无法获取上传凭证

### ISSUE THREAD

**Issue by lsCoding666** [cloudreve/Cloudreve#772]
本来用的好好的 突然就这样了。oneDrive web上传和客户端上传正常
日志里面看不出异常，上传请求的response就是
{"code":50002,"msg":"无法获取上传凭证"}

我怀疑是文件冲突引起的。重启一下换一个文件试试又行了，但是原来出问题的文件还是不行

**Comment by lsCoding666** [comment]
也有可能是对同一个文件上传多次引起的？

**Comment by HFO4** [comment]
可能的原因
1. 服务器无法连接到 OneDrive 的 Graph API 服务；
2. OneDrive 授权过期，请在存储策略中重复授权操作。
