### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by as564335sa** [cloudreve/Cloudreve#773]
Hi,
    现在本地文件导入有了，但是并不灵活，本地删除文件之后web上的文件就删不掉了，只能去删数据库，文件一旦多了简直惨不忍睹，能不能加一个自动扫描路径的功能？这个加上那就完美了。
    还有个小BUG，手机端看图片的时候，图片的关闭按钮图层下面刚好是删除按钮，每次关闭图片都会弹出删除确认。

**Comment by wen2006953** [comment]
我再补充几点
1、注册功能如果禁用后，登陆页面注册按钮应该消失，而不是填了资料后提交时再报未开启
2、文件列表鼠标放上去没有高亮，放到文件名上面也没有变成手型，体验不太好
3、视频播放也做成和图片查看一样的显示方式，一点弹出层全页显示。现在局部内嵌的方式播放视频会导致宽高比例失调。竖屏视频如抖音视频显示不全，只有上半部分。
4、另外希望增加挂载指定目录作为各用户的公共目录，可配置为哪些用户可查看或读写

**Comment by HFO4** [comment]
> 现在本地文件导入有了，但是并不灵活，本地删除文件之后web上的文件就删不掉了，只能去删数据库，文件一旦多了简直惨不忍睹，能不能加一个自动扫描路径的功能？这个加上那就完美了。

下个版本会优化，如果删除文件时文件已不存在，则认定为删除成功

> 还有个小BUG，手机端看图片的时候，图片的关闭按钮图层下面刚好是删除按钮，每次关闭图片都会弹出删除确认。

会在未来修复。

**Comment by as564335sa** [comment]
> > 现在本地文件导入有了，但是并不灵活，本地删除文件之后web上的文件就删不掉了，只能去删数据库，文件一旦多了简直惨不忍睹，能不能加一个自动扫描路径的功能？这个加上那就完美了。
> 
> 下个版本会优化，如果删除文件时文件已不存在，则认定为删除成功
> 
> > 还有个小BUG，手机端看图片的时候，图片的关闭按钮图层下面刚好是删除按钮，每次关闭图片都会弹出删除确认。
> 
> 会在未来修复。
光删除成功不实用，文件扫描很有必要，或者有手动扫描工具什么的，文件多了在后台增删文件是常有的事，没有扫描基本就瞎了；
还有就是，一个文件夹下文件很多的话，web一个页面显示的文件列表太长了，导致浏览起来很卡顿
