### ISSUE TITLE
建议: "帐户救援"的方法

### ISSUE THREAD

**Issue by KusakabeShi** [cloudreve/Cloudreve#777]
最初是一位tg群的用户提的issue，忘记密码后TOTP没有被重置，装置遗失一样无法登入

我一开始以为是bug，直接加入PR #765了

于是有了这些对话:

@HFO4 in https://github.com/cloudreve/Cloudreve/pull/765#discussion_r584218604
> 我个人认为重设密码不应该重设二步验证代码。二步验证应该跟其他验证方式完全隔离开来，这样才能起到增加安全性的作用。

@KusakabeSi in https://github.com/cloudreve/Cloudreve/pull/765#discussion_r584318184
> 恩...那遗失TOTP装置的话，怎么救援比较好呢?一样用email?
可是忘记密码，忘记TOTP都用email的话，还不如两个一起重设
或是用不同的email?这样要大幅改code，而且要改前端，我大概不行了<br>
我刚刚去试了下google和microsoft的作法。他们没有忘记密码，而是统一叫做帐户救援
帐户救援成功的话，密码和TOTP都会被重置。不过帐户救援的流程相当复杂，有问你安全问题的，问你帐号在哪边注册的，上次登入多久以前，大概什么时间注册的等等<br>
上次tg群有人提这个issue，具体作法可能要讨论一下，或是参考下别人的作法。但我觉得TOTP装置丢失就没救有点瞎

@HFO4 in https://github.com/cloudreve/Cloudreve/pull/765#discussion_r584407676
> 因为没有提供忘记密码后复杂的验证流程，所以目前设想重设二步验证的工作交给了站点管理员：如果用户丢失验证密钥，则联系管理员提供所需材料，最终由管理员重设。

@KusakabeSi in https://github.com/cloudreve/Cloudreve/pull/765#discussion_r584456888
> 我也认同，TOTP的重置问题，确实不是这个PR该解决的问题
我先revert，然后开一个新的issue，大家一起讨论这个问题比较好

**Comment by KusakabeSi** [comment]
我觉得，```重设密码```改成和其他主流做法一样的```帐户救援```比较好。救援成功的话密码和TOTP都被重置。
而且能顺便对接未来可能会增加的```短信验证```功能

但是```帐户救援```要怎么实作，就比较值得讨论了。
其他平台基本上对SMS短信验证是最信任的，其次是邮箱和验证问答，再来是TOTP

像是微软，如果你绑定TOTP和邮箱，帐户救援的当下会就会要求输入TOTP和邮箱，都通过才能功过。
如果又绑定短信，就不需要TOTP了

我想到一个方法
短信验证4分
邮箱验证2分
验证问答1分
TOTP 1分

帐户救援时，会验证一次所有的救援手段
如果用户能达到他满分的70%，即通过```帐户救援```，否则只能找管理员了

例如:
用户A，绑定了邮箱，有设置TOTP，没有短信和问答
那么它的满分是3分。救援当下必须通过短信和TOTP

用户B，绑定了邮箱，短信，验证问答和TOTP
那么它的满分是8分，只要到达6分(75%)即可通过```帐户救援```。例如短信+邮箱

用户C: 绑定了邮箱，TOTP和验证问答
那么它的满分是4分。只要验证问答+邮箱都通过，拿到3分(75%)即可
或是邮箱+TOTP
