### ISSUE TITLE
Pro版本支付系统建议

### ISSUE THREAD

**Issue by AH-dark** [cloudreve/Cloudreve#780]
### 建议增加接口

- 微信官方支付接口（公众号、jsapi、h5）
- 支付宝即时支付接口（电脑网站、手机网站、自动续订）
- 易支付接口（自定义站点）
- 码支付接口（自定义站点）
（圆云科技可提供以上接口用于测试，详细请联系[ahdark@roundcloud.cn](mailto:ahdark@roundcloud.cn)）

### 建议优化后台

- 增加商品信息修改页面
- 增加兑换码批量删除页面
- 允许使用商品列表
- 允许使用外链商城（跳转）

**Comment by MoeCinnamo** [comment]
是的，应该增加一些支付接口。后台也可以搞‘一个兑换码每个用户只能使用一次，兑换码可以多次使用’的功能。

外链商城有些勉强，不过搞个侧边栏自由编辑确实可以
