### ISSUE TITLE
BUG：webdav容量显示不准

### ISSUE THREAD

**Issue by as564335sa** [cloudreve/Cloudreve#786]
今天试了下win10的webdav，我是映射的网络驱动器，但是映射完之后显示可用只有33G，但是web上已用是0，我也没有上传过文件。
![QQ截图20210306160716](https://user-images.githubusercontent.com/35949162/110200029-a7c79080-7e96-11eb-9ac5-88968005a4a4.png)
![QQ截图20210306160737](https://user-images.githubusercontent.com/35949162/110200030-a8f8bd80-7e96-11eb-8cd7-4f5a9e413cac.png)

**Comment by snailwind** [comment]
这个显示的是本地缓存的盘(一般是C盘)的容量，表示你可以在同步(上传)完成前，存入的文件大小。基本都会这样
