### ISSUE TITLE
可以增加任务计划功能吗？

### ISSUE THREAD

**Issue by dzhl** [cloudreve/Cloudreve#788]
请问可以增加个任务计划功能吗？比如我设定了特定时间，从onedrive特定目录导入文件到cloudreve中指定的路径下，这样的话，我通过其他方式上传到onedrive中的文件都能同步到cloudreve中，而不是每次都需要我手工导入

**Comment by dzhl** [comment]
大家觉得有必要这样的功能吗？

**Comment by yinqf** [comment]
非常有必要哦

**Comment by hfdem** [comment]
希望实现计划任务，我想每天自动导入外部目录到存储策略

**Comment by tysonair** [comment]
附议
