### ISSUE TITLE
外部导入文件的数据库删除

### ISSUE THREAD

**Issue by lijieamd** [cloudreve/Cloudreve#789]
关于管理员账号的管理页面下的外部导入功能：
是否能增加一个功能，可以在不删除源文件的情况下，删除外部导入功能所导入的文件（仅删除数据库）

**Comment by huiges** [comment]
我也期待这个功能

**Comment by sunnynctu** [comment]
有些文件导入后就后悔了，但是删除会删除源文件，同样期待可以撤回导入

**Comment by huiges** [comment]
> 有些文件导入后就后悔了，但是删除会删除源文件，同样期待可以撤回导入

应该可以让用户选择删除本地文件时不删除源文件，和外部导入后再次导入可以重新获取远程的目录结构然后再导入进去，不然的话远程目录里面删了内容，本地还是存在内容，这样无限循环很麻烦

**Comment by TomLiu-GitHub** [comment]
我也期待这个功能
我已经丢失了好多数据
我以为只会删除数据库不会删源文件

**Comment by TomLiu-GitHub** [comment]
我是导入失败,空间不足,但是目录已经被导入了.我删除了重新导入,没想到5T的文件全被删了
