### ISSUE TITLE
离线下载大文件转存失败导致云盘可用空间显示不正确

### ISSUE THREAD

**Issue by shuguang101** [cloudreve/Cloudreve#790]
假设本机有10g存储, 分给Cloudreve 9g, 现在使用离线下载功能下载了一个8g的文件，之后进行转存时会因为系统空间不足而导致转存失败(并且会自动删除该离线下载文件)，但Cloudreve界面却会显示用户已使用了8g的存储空间, 且在界面上找不到该文件(无法进行删除)

Cloudreve 3.2.1

**Comment by HFO4** [comment]
本地策略离线下载需要有两倍于文件大小的可用物理空间。否则转存时会写满硬盘导致无法写入数据库，进而引发奇怪的问题。
