### ISSUE TITLE
希望添加数据库重建的选项或功能

### ISSUE THREAD

**Issue by ShevonKuan** [cloudreve/Cloudreve#794]
- 需求:
服务器上的一些功能或服务可以对cloudreve下的储存目录进行修改,同时cloudreve能够重新扫描变动并修改cdfiles表,使得网盘能够显示文件的即时更新.
- 目前我的解决方法:
目前每一次文件操作完成后都会直接对cdfiles表进行修改,这步工作现在由php完成,但是这极其不方便,希望网盘服务能够完全独立于其他服务,

**Comment by as564335sa** [comment]
这个功能呼声很高啊

**Comment by AH-dark** [comment]
支持

**Comment by topjohncian** [comment]
我认为这样大可不必使用cloudreve了

Get Outlook for Android<https://aka.ms/AAb9ysg>

________________________________

**Comment by zhang-anzhi** [comment]
如果有功能和服务有读取和修改网盘文件的需要，这个需求应该是 **增加文件修改和删除的API**，而不是要求云盘主动扫描变动，存储区域是这个功能创建并持续使用的，只应该由这个服务来读取和修改

**Comment by ShevonKuan** [comment]
增加api是可以的,但是我更希望添加一个选项或一个按钮,可以扫描文件变动并重建cdfiles表,当然这个功能我目前使用删除表记录和导入外部文件这个功能实现.
