### ISSUE TITLE
[Bug report] 存储路径=uploads/{uid}/{path} ，自动重命名=否 檔案覆蓋bug

### ISSUE THREAD

**Issue by KusakabeSi** [cloudreve/Cloudreve#795]
**Describe the bug**
因为想要前后端一致，储存路径这样设定: ```uploads/{uid}/{path} ```
存储路径=```uploads/{uid}/{path}```
自动重命名=否
此情况有档案覆盖bug

**To Reproduce**
1. 储存策略: onedrive
2. 存储路径=uploads/{uid}/{path}
3. 自动重命名=否
4. 上传资料夹 a/1.png
5. 重新命名资料夹 a 变成 b
6. 此时在od里面，仍然是 a/1.png
7. 上传资料夹 a/1.png
8. 打开 b/1.png，档案被覆盖

**Expected behavior**
重新命名资料夹 a 变成 b 时，后端应该一起重新命名
或是上传档案时，后端已有相同档案名称，自动重新命名
再不然强制档案名称加乱数。但是这样就造成档案载下来档名改变，体验不好
或是资料夹名称强制加乱数

**Screenshots**
先上传大雄光之旅，重新命名成大雄光之旅2，再上传修改过的
![image](https://user-images.githubusercontent.com/73118488/110921522-97615b00-8359-11eb-86e3-44f45583fdd7.png)
![image](https://user-images.githubusercontent.com/73118488/110921480-8add0280-8359-11eb-8bc3-20bb45067978.png)
一开始的已被修改
![image](https://user-images.githubusercontent.com/73118488/110921809-eeffc680-8359-11eb-973b-799bde839c07.png)

**Desktop (please complete the following information):**
 - Version 3.2.1

**Additional context**
None

**Comment by HFO4** [comment]
这一问题已经在开发版中修复，现在如果遇到了物理重名，会被标记为上传失败。
关联：#764
