### ISSUE TITLE
Webdav 405错误 提示物理同名文件已存在或不可用

### ISSUE THREAD

**Issue by SakurabaKiyoka** [cloudreve/Cloudreve#803]
升级到3.3.0之后出现的webdav问题，通过任何客户端上传到webdav Cloudreve后台均会提示物理同名文件已存在或不可用。文件夹权限正常，文件也没被锁定或者占用。
![err](https://user-images.githubusercontent.com/16064020/111890168-4f61c880-8a2a-11eb-8dee-a33056b26125.png)

**Comment by HFO4** [comment]
请问您使用的WebDAV客户端是？

**Comment by SakurabaKiyoka** [comment]
> 请问您使用的WebDAV客户端是？
WIN10自带，winscp，还有joplin这个笔记软件（支持同步到webdav），安卓es/cx/soild浏览器，均报同样错误。环境是nginx https反代，如果采用http直连则干脆文件列表都看不见了，之前用3.2.1的时候一切正常的

**Comment by SakurabaKiyoka** [comment]
手动再次确认了一下，服务端重启后第一次使用winscp的话上传文件就正常，但是一旦在winscp删掉这个文件，又在win10的webdav上传了同样的文件，则直接错误423；服务端重启后直接使用win10的webdav有概率成功，也有一定概率后端直接405，原因仍然不明，其他客户端的话首次上传也是概率成功或者405和423随机出现。一旦服务端返回423之后，所有客户端上传文件均返回405，推测是什么锁机制导致的。

**Comment by HFO4** [comment]
请问您所使用的存储策略：
* 是否是本机存储策略？
* 是否开启了自动重名规则？

**Comment by SakurabaKiyoka** [comment]
> 请问您所使用的存储策略：
> 
> * 是否是本机存储策略？
> * 是否开启了自动重名规则？

本机，自动重命名开启了

**Comment by SakurabaKiyoka** [comment]
不过关掉自动重命名，重启服务端后使用win10客户端传什么文件都是依旧405，winscp可以任意操作，但是一旦win10上传了文件a.jpg（假设文件名是a.jpg，其实任意文件均可触发)，导致服务端405之后，winscp再去上传a.jpg就会返回423了

**Comment by HFO4** [comment]
已经修复，感谢反馈！
