### ISSUE TITLE
世纪互联OD几率出现某个文件无法获取上传凭证

### ISSUE THREAD

**Issue by dngronglong** [cloudreve/Cloudreve#804]
od里面看了没有存在同名文件，同一目录夏其它文件都能上传，就某一个或几个文件无法获取上传凭证。

**Comment by HFO4** [comment]
需要开启debug模式提供下更多日志信息

**Comment by HFO4** [comment]
3.3 版本后由于冲突策略的变更，可能会出现某些特定文件“无法获取上传凭证”。

**原因：**
存储策略未开启“自动重命名”，且之前上传某个特定文件时中途取消了上传，Cloudreve 为了防止恶意上传，会插入占位符文件，导致后续无法重复上传此文件。

**解决方法：**
可选择下列任何一种:

* 开启存储策略的“自动重命名功能”
* 对待上传的文件重命名
* 到 OneDrive 里手动删除大小为 0 的占位符文件

**Comment by dngronglong** [comment]
解决
