### ISSUE TITLE
请问3.3.0下载文件时,域名指向了localhost这个要怎么搞一下?

### ISSUE THREAD

**Issue by iCod1ng** [cloudreve/Cloudreve#805]
点击下载调用了如下接口 -> http://localhost/api/v3/file/download

**Comment by Beattheend** [comment]
后台 站点信息 站点URL 设置正确吗？

**Comment by iCod1ng** [comment]
> 后台 站点信息 站点URL 设置正确吗？
我下载后，启起来直接用的。没配置过,请问这个在哪里看呢？

**Comment by Beattheend** [comment]
> > 后台 站点信息 站点URL 设置正确吗？
> > 我下载后，启起来直接用的。没配置过,请问这个在哪里看呢？

域名/admin/basic 检查站点URL设置

**Comment by zhang-anzhi** [comment]
管理员账号登录后设置面板有
