### ISSUE TITLE
COS储存 上传10G左右文件时提示上传失败（400：Your proposed upload is smaller than the minimum all owed boject size.）

### ISSUE THREAD

**Issue by SHDocter** [cloudreve/Cloudreve#806]
COS储存 上传10G左右文件时提示 上传失败（400：Your proposed upload is smaller than the minimum all owed boject size.）
![P)P @PNYANHINP`P1I94182](https://user-images.githubusercontent.com/72510879/111957364-e1e79200-8b26-11eb-988d-4c5f1b7ff8df.png)

**Comment by HFO4** [comment]
COS 客户端直传目前只支持最大 5GB，参考：https://docs.cloudreve.org/use/policy/compare
未来会实现分片上传以突破此限制。
