### ISSUE TITLE
3.3.0 Method Not Allowed

### ISSUE THREAD

**Issue by 1549469775** [cloudreve/Cloudreve#808]
**Describe the bug**
我想问下什么情况会导致这个，用3.3.0会这样，3.1.1可以上传，我该怎么修改呢？

**Screenshots**
![image](https://user-images.githubusercontent.com/20150696/112088794-64c22880-8bcb-11eb-9316-5529af7e087d.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - OS: window10
 - Browser edge

**Comment by HFO4** [comment]
是 3.3.0 版本的 bug，现在已经修复。参见 #803
