### ISSUE TITLE
[minor] Frontend and some API returns datetime string ignoring server/client timezone

### ISSUE THREAD

**Issue by noahzark** [cloudreve/Cloudreve#811]
**Describe the bug**
As a user at 🇨🇳  visiting a server deployed at 🇺🇸
I expect front end timestamp shows in my local time
So I could know the accurate time info

Currently the API simply returns a time string ignoring the time stamp.

**To Reproduce**
1. Start service in another country
2. Perform a new task
3. Visit tasks page
4. /api/v3/user/setting/tasks returns create date without TZ info

**Expected behavior**
Datetime strings with TZ info and shows local time in front end.

**Screenshots**
In database
![db](https://disk.fz-l.com/api/v3/file/source/4115/db.png?sign=8BZWDy85i___luhmpMTUejXjVl_USlgb83vy5rJtNTE%3D%3A0)

API response ignores timezone
![tasks](https://disk.fz-l.com/api/v3/file/source/4116/tasks.png?sign=2Zvrx9mqyroNMJHwOJJPpLWQkCuglNJ1E2iL4GMaJgg%3D%3A0)

File detail ignores timezone
![file](https://disk.fz-l.com/api/v3/file/source/4117/file.png?sign=dkgs5ni8m8INUI-5oUccm-mV8hb0aplcMRAdyI6YXQk%3D%3A0)

**Additional context**
As a temporary fix for servers deployed in other countries(or you want test such case), we could start the server with additional TZ env
```bash
TZ=Asia/Shanghai ./cloudreve 
```

**Comment by HFO4** [comment]
Thanks for the feedback, now we can set custom timezone value in setting page:
![image](https://user-images.githubusercontent.com/16058869/113473719-dfc5f180-949d-11eb-9e1f-7006906d253b.png)
