### ISSUE TITLE
【重要】通过搜索栏能够直接获取文件

### ISSUE THREAD

**Issue by Leonhzz** [cloudreve/Cloudreve#812]
不知道是设置问题还是什么。
游客可以直接在前段通过文件名搜索出你分享中的文件。
![image](https://user-images.githubusercontent.com/53173411/112473413-4dd92d00-8da9-11eb-8eca-7bc60ecd45b6.png)
只要任何通过你分享的任何一个链接就可以进入到这个页面，然后通过这个搜索栏，输入文件名获取搜索结果。
![image](https://user-images.githubusercontent.com/53173411/112473510-6ba69200-8da9-11eb-8599-6f5ccacb0717.png)

经反馈，即使文件设置有分享密码也一样可以通过搜索结果直接下载！

还请尽快修复。

**Comment by HFO4** [comment]
> 游客可以直接在前段通过文件名搜索出你分享中的文件。

这个是预期之内的表现，公开分享可以直接搜索。

> 经反馈，即使文件设置有分享密码也一样可以通过搜索结果直接下载！

经测试，无法复现

**Comment by Leonhzz** [comment]
这个预期表现，很尴尬。
前端不应该出现搜素选项，公开分享，应该是分享一个链接，任何人都仅能查看这个链接才是。= . =，而不是，你给人分享个链接，后面，家底都被人扒了。
我希望能够改善这个预期内的表现，作者大大是否能考虑下呢？

至少，所有网盘文件的搜索框不应该出现在前端，必须登录。

**Comment by Beattheend** [comment]
> 这个预期表现，很尴尬。
> 前端不应该出现搜素选项，公开分享，应该是分享一个链接，任何人都仅能查看这个链接才是。= . =，而不是，你给人分享个链接，后面，家底都被人扒了。
> 我希望能够改善这个预期内的表现，作者大大是否能考虑下呢？
> 
> 至少，所有网盘文件的搜索框不应该出现在前端，必须登录。

这种情况下，在官方改动前，你可以自己下载源代码修改。

**Comment by Leonhzz** [comment]
> > 这个预期表现，很尴尬。
> > 前端不应该出现搜素选项，公开分享，应该是分享一个链接，任何人都仅能查看这个链接才是。= . =，而不是，你给人分享个链接，后面，家底都被人扒了。
> > 我希望能够改善这个预期内的表现，作者大大是否能考虑下呢？
> > 至少，所有网盘文件的搜索框不应该出现在前端，必须登录。
> 
> 这种情况下，在官方改动前，你可以自己下载源代码修改。

不了解go，

**Comment by Leonhzz** [comment]
> > 游客可以直接在前段通过文件名搜索出你分享中的文件。
> 
> 这个是预期之内的表现，公开分享可以直接搜索。
> 
> > 经反馈，即使文件设置有分享密码也一样可以通过搜索结果直接下载！
> 
> 经测试，无法复现

我能问下，作者大大是否有考虑修复优化这个呢？ > . <
查看了cloudreve很多文档和社区提问，都有不少需求，有要求能够全部搜索公开的也有不需要的。
所以，后台增加一个设置项可以选择是否允许游客搜索？

我是对Go一窍不通，而且更改之后，需要重新打包之后太繁琐了。

**Comment by Leonhzz** [comment]
也许有人也会需要这个，目前有大佬@Band Sky（= . =）给了个解决办法。如下：
帮你看了一下，未登录用户前端去掉搜索框。
找到：\cloudreve-frontend\src\component\Navbar\Navbar.js（前端文件，通过github cloudreve的assets文件夹进入即可看到）
大约647行的，<SezrchBar /> 改成 Auth.Check(this.props.isLogin) && <SezrchBar />

就是只在登录用户下显示搜索了。

</感谢大佬的帮助，但是对我来讲依然是个可怕的工程。本地电脑未安装开发环境，而且打包封装都属于一脸懵逼的状态。仅会使用发行包来安装cloudreve，故而我只能将其搁置。>

感谢大佬们的帮助！！
