### ISSUE TITLE
使用腾讯cdn无法上传大文件

### ISSUE THREAD

**Issue by 52lemon6** [cloudreve/Cloudreve#813]
使用腾讯cdn无法上传大文件，缓存规则均已改为不过滤不缓存，但是上传大文件时仍报错HTTP错误
 谷歌和edge都报次错误
控制台报错截图
![image](https://cdn.drive.oniya.cn/api/v3/file/get/3376/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202021-03-26%20090808.png?sign=skfZQW8dM0vHioUtBSWiOR0cOLU9Cxeh7RZ4hVOJ9K8%3D%3A0)
![image](https://user-images.githubusercontent.com/40059643/112563130-bc52d500-8e13-11eb-9947-44d7a8904b5d.png)

腾讯cnd控制台截图
![image](https://cdn.drive.oniya.cn/api/v3/file/get/3377/%E5%B1%8F%E5%B9%95%E6%88%AA%E5%9B%BE%202021-03-26%20091028.png?sign=KqGppTe1FByvYzkqUA788bcUD2uejcNL3MROapebFLY%3D%3A0)
![image](https://user-images.githubusercontent.com/40059643/112563161-c70d6a00-8e13-11eb-93df-e467e3a98ba2.png)

不走cdn可正常上传，

**Comment by 52lemon6** [comment]
破案了，腾讯云cdn  POST请求最大只支持200MB，

**Comment by crazy6995** [comment]
我用cloudflare也是一样，413 Entity is too large...
目前还是流式上传，希望支持分片。。。

**Comment by YumeGod** [comment]
> 我用cloudflare也是一样，413 Entity is too large...
> 目前还是流式上传，希望支持分片。。。
现在有办法解决吗，我也用的cloudflare报错也一样，有解决方法吗，或者添加一个自定义上传接口应该也可以，前端用IP上传
