### ISSUE TITLE
[Bug]在线编辑文本行号错误

### ISSUE THREAD

**Issue by AnzhiZhang** [cloudreve/Cloudreve#814]
**Describe the bug**
使用在线编辑txt，当文本因为单行过长，挤出一行多行显示的时候，行号在挤出的行继续标出，
![image](https://user-images.githubusercontent.com/37402126/112622904-a4587100-8e66-11eb-8a2f-d3efc604c11e.png)

**To Reproduce**
1. 新建一个txt文件
2. 把一行敲的特别长
3. 然后就看到挤出去的“第二行”多了个行号，但是其实并没有换行符

**Expected behavior**
正常情况应该跳到下一个换行之后再显示
![image](https://user-images.githubusercontent.com/37402126/112623010-c4883000-8e66-11eb-826c-aeef132e4174.png)

**Desktop (please complete the following information):**
 - Cloudreve running on Ubuntu server 20.04
 - OS: Windows 10
 - Browser: Chrome
 - Version: v3.3.1 Commit #a1252c8

**Comment by zhang-anzhi** [comment]
改Bug影响比较严重，建议开发者增加 `BUG` 标签并及时修复

**Comment by zhang-anzhi** [comment]
该Bug影响比较严重，建议开发者增加 `BUG` 标签并及时修复
