### ISSUE TITLE
新增拖拽选择文件

### ISSUE THREAD

**Issue by AnzhiZhang** [cloudreve/Cloudreve#818]
现在选择多个文件只能选中一个后使用shift或ctrl来选择多个文件，希望添加一下拖拽光标选择文件

**Comment by Beattheend** [comment]
这些都是需求，而且哥们你能不能多问题一次性在一个issues里提完..

**Comment by zhang-anzhi** [comment]
Issue: **An** important topic that people are discussing or arguing about
不好意思一开始只是反馈bug，后来顺便提了个需求，然后就多提了一点。不过分开其实更加规范，提在一块不一定会同时resolve，分开也方便commit的时候标记

**Comment by topjohncian** [comment]
我建议还是一次提完比较好把
不然 watchers 的邮箱要爆炸了~

**Comment by zhang-anzhi** [comment]
一次性提完确实对watchers感觉更舒服，但是作为contributors来思考。一个标题是《一些功能改进建议》的issue，并不一定每条都会采纳，而且不可能同时做完，这时对于项目管理就很不方便。多思考一些项目层面的东西，对做东西有好处
