### ISSUE TITLE
[Feature request]存储空间同时显示总容量

### ISSUE THREAD

**Issue by zhang-anzhi** [cloudreve/Cloudreve#820]
在左下角显示存储空间的位置，增加空间总容量。如 `已使用xxMB / 共xxMB`
![image](https://user-images.githubusercontent.com/37402126/112708023-66049580-8eea-11eb-9a84-aecbcc6f0866.png)

**Comment by naicfeng** [comment]
鼠标能移上去看下嘛？

**Comment by zhang-anzhi** [comment]
鼠标移上去能看。这个issue的需求是直接显示。

**Comment by naicfeng** [comment]
v2就是这样显示的，宽度不够才改为浮动显示。

**Comment by zhang-anzhi** [comment]
改成这样就够了，语义上也没用问题，上面有 `存储空间` 几个字
![image](https://user-images.githubusercontent.com/37402126/112712496-fce14a00-8f0a-11eb-8e69-f22172d2bb3d.png)

**Comment by Beattheend** [comment]
才更新，你又倒回去了...

**Comment by zhang-anzhi** [comment]
> 才更新，你又倒回去了...

请问更新前是什么样的呢？

**Comment by Beattheend** [comment]
> > v2就是这样显示的，宽度不够才改为浮动显示。
> 
> 请问更新前是什么样的呢？
3.3.0之前的版本就是这样的，由于显示宽度问题，3.3.0优化了 见 [https://forum.cloudreve.org/d/1568](https://forum.cloudreve.org/d/1568) @zhang-anzhi

**Comment by zhang-anzhi** [comment]
没找到更新前的样子，以上的截图已经证明是放得下的

**Comment by otakisa** [comment]
自己改前端不会吗？群里看着发这种无聊的issue跳过来吐个槽

**Comment by zhang-anzhi** [comment]
> 自己改前端不会吗？群里看着发这种无聊的issue跳过来吐个槽

不会。这是无聊的issue吗，你是作者吗，还是维护者？

**Comment by wsndshx** [comment]
我想说的前面已经有人说了, 我这里给你一个切入点: 在移动端下当前的显示方式会让用户不知道总空间大小.

**Comment by zhang-anzhi** [comment]
> 我想说的前面已经有人说了, 我这里给你一个切入点: 在移动端下当前的显示方式会让用户不知道总空间大小.

Your opinion is ONLY your opinion, you are not the member of this project. The display mode can do a different disign on the different diveces.

**Comment by wsndshx** [comment]
> 我想说的前面已经有人说了, 我这里给你一个切入点: 在移动端下当前的显示方式会让用户不知道总空间大小.

emmm好像不大对, PC上模拟出来不显示总大小, 但手机上显示的又超出宽度了

![photo_2021-03-27_23-28-45](https://user-images.githubusercontent.com/7829265/112725639-3ab69080-8f54-11eb-896b-ac1a63653855.jpg)

在移动端上用你说的方式去显示可能会更加友好?

**Comment by zhang-anzhi** [comment]
> > 我想说的前面已经有人说了, 我这里给你一个切入点: 在移动端下当前的显示方式会让用户不知道总空间大小.
> 
> emmm好像不大对, PC上模拟出来不显示总大小, 但手机上显示的又超出宽度了
> 
> ![photo_2021-03-27_23-28-45](https://user-images.githubusercontent.com/7829265/112725639-3ab69080-8f54-11eb-896b-ac1a63653855.jpg)
> 
> 在移动端上用你说的方式去显示可能会更加友好?

Lookup my image, I removed `已使用` words.
