### ISSUE TITLE
捐赠版 推广加积分

### ISSUE THREAD

**Issue by AH-dark** [cloudreve/Cloudreve#821]
**Is your feature request related to a problem? Please describe.**
无关，仅为建议&需求

**Describe the solution you'd like**
用户（某特定用户组）可生成推广链接，其他用户点击此链接后可获得一定积分奖励，使用此链接注册账号后可获得一定积分奖励。

**Comment by anzhiyu-c** [comment]
这个我觉得可以有哎，有这个的话我觉得捐赠版可以冲
