### ISSUE TITLE
手机登录相关（MIIT通知）

### ISSUE THREAD

**Issue by AH-dark** [cloudreve/Cloudreve#822]
**根据相关通知：https://mp.weixin.qq.com/s/EmZQPJkhPaAitnpNLD62uw**

>25、邮箱云盘类
>
>基本功能服务为“邮箱、云盘等”，必要个人信息为：注册用户移动电话号码。

### 为遵从政府相关部门规定，建议新增以下功能：

1. 手机登录：使用手机号与密码或手机号与短信验证码登录云盘
2. 已有用户强制要求绑定手机号（对话框不可关闭）
3. 允许开关邮箱登录、手机登录
4. 可选择是否允许邮箱注册、手机号注册
5. 更改密码时需手机短信（邮箱）验证

建议新增以下短信接口：

1. 阿里云短信接口
2. 短信宝短信接口

**Comment by zhang-anzhi** [comment]
看了一下这个文件原文 [关于印发《常见类型移动互联网应用程序必要个人信息范围规定》的通知](http://www.cac.gov.cn/2021-03/22/c_1617990997054277.htm)，相关原文如下 `（二十五）邮箱云盘类，基本功能服务为“邮箱、云盘等”，必要个人信息为：注册用户移动电话号码。`
按照这个规定的解释，应该移除邮箱接口，添加短信接口。或将注册使用的邮箱改为用户名。
强制要求绑定手机号在这个规定里并没有要求。

PS: 实际责任是将该项目用于生产的主体而不是项目开发者。

**Comment by AH-dark** [comment]
> 看了一下这个文件原文 [关于印发《常见类型移动互联网应用程序必要个人信息范围规定》的通知](http://www.cac.gov.cn/2021-03/22/c_1617990997054277.htm)，相关原文如下 `（二十五）邮箱云盘类，基本功能服务为“邮箱、云盘等”，必要个人信息为：注册用户移动电话号码。`
> 按照这个规定的解释，应该移除邮箱接口，添加短信接口。或将注册使用的邮箱改为用户名。
> 强制要求绑定手机号在这个规定里并没有要求。
> 
> PS: 实际责任是将该项目用于生产的主体而不是项目开发者。

是的，但这一Issue是为了保护运营主体不受国家法律法规制裁。

且我的意思是，“强制要求绑定手机号”作为一个可开关选项作用于用户，这是为了避免已有用户可以不去绑定手机。

**Comment by zhang-anzhi** [comment]
目前的Cloudreve并不违法相关法律法规，运营主体可以关闭强制邮箱验证。
你的建议1345都很合理而且适应了该规定，但是2应该由运营主体来决定是否强制要求绑定手机号。
建议修改一下需求，重新整理一下语言，方便开发者了解更加清晰的需求

**Comment by AH-dark** [comment]
> 目前的Cloudreve并不违法相关法律法规，运营主体可以关闭强制邮箱验证。
> 你的建议1345都很合理而且适应了该规定，但是2应该由运营主体来决定是否强制要求绑定手机号。
> 建议修改一下需求，重新整理一下语言，方便开发者了解更加清晰的需求

感谢您的建议，希望 @HFO4 能看到吧

**Comment by AH-dark** [comment]
Aaron还没消息？
