### ISSUE TITLE
上传.mp3文件卡在处理中

### ISSUE THREAD

**Issue by ipangbo** [cloudreve/Cloudreve#823]
**Describe the bug**
上传.mp3文件卡在处理中

**To Reproduce**
1. 上传.mp3文件
2. 等待上传结束

**Expected behavior**
希望能够尽快处理完成并且结束上传
**Screenshots**
![image](https://user-images.githubusercontent.com/36611837/112990526-c0c31900-9198-11eb-876d-552e4f06e631.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 2009
 - Browser Edge 
 - Version 89.0.774.63

**Comment by hatsuyuki280** [comment]
建议检查下目录读写权限的正确性/允许上传的文件大小是否符合部分运营商的要求
