### ISSUE TITLE
家里宽带有公网IP，通过路由器的DMZ功能转发端口到nas来访问webdav的时候，webdav无法连接

### ISSUE THREAD

**Issue by cimyong** [cloudreve/Cloudreve#826]
路由器开启DMZ
![image](https://user-images.githubusercontent.com/33285042/1131408
webdav
![image](https://user-images.githubusercontent.com/33285042/113141032-c46ba400-925b-11eb-9a01-008a8ae64dd2.png)
56-8d958e00-925b-11eb-80cd-d3b23bf16f9c.png)

**Comment by HFO4** [comment]
Windows 资源管理器中使用 WebDAV 需要服务端启用 HTTPS，或者手动更改注册表解除这个安全限制。
注册表管理器定位至：`HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\WebClient\Parameters`
将`BasicAuthLevel` 更改为 `2` (decimal), 然后重启 Windows
