### ISSUE TITLE
请问该系统是否支持外部账号系统呢？我有一个网站想做一个附属的网盘功能，账号系统已经有了

### ISSUE THREAD

**Issue by Firesuiry** [cloudreve/Cloudreve#827]
**Is your feature request related to a problem? Please describe.**
请问该系统是否支持外部账号系统呢？我有一个网站想做一个附属的网盘功能，账号系统已经有了
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by hatsuyuki280** [comment]
@Firesuiry 比如…记得好像支持Redis来着quq？

**Comment by Firesuiry** [comment]
> @Firesuiry 比如…记得好像支持Redis来着quq？

比如Auth2.0啥的~ Redis不是数据库吗，不是账号系统把

**Comment by HFO4** [comment]
目前暂不支持外部账号系统
