### ISSUE TITLE
是否考虑公布API文档

### ISSUE THREAD

**Issue by hahaha28** [cloudreve/Cloudreve#830]
能否考虑整理一份API文档，我（或者别人）可以为其写手机App

**Comment by 2926295173** [comment]
有软件可以直接把网页生成app，不过好像不好用

**Comment by YamazakuraH** [comment]
@hahaha28 AMP了解一下

**Comment by HFO4** [comment]
详细路由可参考 https://github.com/cloudreve/Cloudreve/blob/master/routers/router.go
具体请求可通过抓包获取。目前没计划编写 API 文档，工作重心仍然是系统本身的完善。

**Comment by zhang-anzhi** [comment]
建议作者考虑一下API文档，从经验上来看小团队甚至个人开发，写一些文档有助于自己理解自己设计的系统。在编写文档的过程中也会自己对系统进行整理，可以在这个过程中找到很多优化的思路

**Comment by xiaowumin-mark** [comment]
对go的语法不熟悉，如果不公布api文档很不方便

**Comment by Muska-Ami** [comment]
+1希望能做一份API文档

**Comment by yxzlwz** [comment]
个人有意愿社区维护一个文档，期待有类似想法或社区项目管理经验的Cloudreve用户前来一起实现想法

TG群聊：https://t.me/+XW2ok10N8DExMDU1

GitHub Organization：https://github.com/Cloudreve-Document
