### ISSUE TITLE
OneDrive离线下载后转存断断续续

### ISSUE THREAD

**Issue by q601904795** [cloudreve/Cloudreve#832]
系统环境:ubuntu18.04
程序版本:3.3.1
机器:azure香港
OneDrive地区:香港
问题描述:
本机正常上传速度没问题.
离线下载后转存很慢,后面nload观察,应该说是转存断断续续,每次速度都会很快跑上去,但是一下子又停止了,然后需要比较大的间隔才会有速度,如此循环. 本机网络环境应该没有问题,速度最高时可去到300M带宽,但只是1秒闪现,马上就没速度了

尝试:
 1)一开始以为是OneDrive订阅问题,但是已经切换过几种订阅 A1 A1P A3 E3 E5 世纪互联,但是现象一样.
 2)尝试过重新搭建程序,现象一样.
 3)怀疑是机器配置不够?  最高升配到4C8G,现象相同.

希望能得到帮助.
以下是nload截图  速度能跑上去,但是马上断开

![{K(C))QCVI`)0(%9RO DIE](https://user-images.githubusercontent.com/24204266/113654394-4b8ca200-96ca-11eb-8618-c8620b44422b.png)

**Comment by HFO4** [comment]
@q601904795 OmeDrivr的上传是需要分片的，所以上行流量呈波动趋势

**Comment by q601904795** [comment]
明白了,不过我这个地方明显间隔时间比较长.分片完好像一瞬间就传完了.这个是需要修改什么参数?还是说机器的CPU或者IO不足?

**Comment by q601904795** [comment]
![image](https://user-images.githubusercontent.com/24204266/113848537-2c296e00-97cb-11eb-9d70-cc5bc17a53e3.png)

你好,这是我刚刚测试的截图,就是在离线下载完成后转存阶段,无上传应该是分片阶段,明显负载没有什么波动,CPU和内存占用都很低,如果我想提高这个分片的速度或者是减少上行流量波动,应该要怎么做呢?

**Comment by Amberler** [comment]
同样的问题，之前的3.2.1没问题，现在升级到最新，转存特别慢

**Comment by sunnynctu** [comment]
同样的问题。Ubuntu镜像这类热种离线下载速度有80MB/s，但是转存平均速度只有2MB/s

**Comment by HFO4** [comment]
3.5 以后可以自定义分片大小解决此问题。
