### ISSUE TITLE
关于云盘下载和一些其他零碎的小bug

### ISSUE THREAD

**Issue by LEEkabe** [cloudreve/Cloudreve#833]
第一次部署网站用到您的代码，这是我的荣幸。以下问题是我在部署过程中遇到的一些零碎的bug：
1. 一旦刷新就会退出登录，不能保留在已登账户的界面上（也有可能这是你出于安全方面的考虑？）
2. 上传文件的加号在我点进视频、文件等副选项之后被隐藏，再点回我的文件就无法再次弹出。需要点击其他大选项（如我的分享和离线下载等）才可以恢复
3. （最重要的一点！！！）文件上传大小被限制了，文件一旦比较大（例如50-100M不等），就会上传失败或者卡在上传列表中

希望你生活开心快乐~

**Comment by topjohncian** [comment]
1. 检查是否使用CDN/开启缓存

**Comment by LEEkabe** [comment]
已经检查了，所用的网址并不是CDN的所在网址，浏览器缓存已经清除，网站备份没开的情况下依旧出现这种情况呜呜呜呜

**Comment by Yuelioi** [comment]
> 已经检查了，所用的网址并不是CDN的所在网址，浏览器缓存已经清除，网站备份没开的情况下依旧出现这种情况呜呜呜呜

是不是开了https，但是使用http登陆的

**Comment by seeleclover** [comment]
这种情况其实很有可能是 Nginx 的问题，比如 proxy-body-size 的值不够大，就会导致文件上传大小被限制。
