### ISSUE TITLE
是否可以支持多语言版本？

### ISSUE THREAD

**Issue by CreekCai** [cloudreve/Cloudreve#835]
目前的版本只能显示中文，是否考虑增加多语言版本以涵盖更多市场？

**Comment by simplove** [comment]
也正好有这个需求，老外看不懂中文呀

**Comment by Henry14all** [comment]
有的，目前已有外国友人将Cloudreve翻译为英语，但似乎不能切换。
要用英语版可以自己搜一下，后期也等待群主添加多语言切换功能。

**Comment by topjohncian** [comment]
下版本（3.6）会增加对多语言的支持 😃
