### ISSUE TITLE
是否可以支持下图床功能

### ISSUE THREAD

**Issue by fuzhengwei** [cloudreve/Cloudreve#838]
1. 希望上传的图片可以支持 url 地址访问
2. 这样就可以放到 md 里了，也不用在另外安装图床的程序了

**Comment by cxplay** [comment]
获取外链功能可以得到文件的直链, 使用 Markdown 语法可以直接引用.
![image](https://user-images.githubusercontent.com/62034099/114292752-680e4d00-9ac3-11eb-96ea-adc4ac5aed9f.png)
当然前提是你的储存策略支持.

**Comment by fuzhengwei** [comment]
> 获取外链功能可以得到文件的直链, 使用 Markdown 语法可以直接引用.
> ![image](https://user-images.githubusercontent.com/62034099/114292752-680e4d00-9ac3-11eb-96ea-adc4ac5aed9f.png)
> 当然前提是你的储存策略支持.

我使用了本地存储没有分享外链的功能，你这个是用的什么存储策略？感谢🙏

**Comment by cxplay** [comment]
> > 获取外链功能可以得到文件的直链, 使用 Markdown 语法可以直接引用.
> > ![image](https://user-images.githubusercontent.com/62034099/114292752-680e4d00-9ac3-11eb-96ea-adc4ac5aed9f.png)
> > 当然前提是你的储存策略支持.
> 
> 我使用了本地存储没有分享外链的功能，你这个是用的什么存储策略？感谢🙏

![image](https://user-images.githubusercontent.com/62034099/114293910-ce4b9d80-9acc-11eb-816f-2c038a941253.png)
修改本机策略的 "直链设置"

**Comment by fuzhengwei** [comment]
> 设置"

赞，搞定

**Comment by zhang-anzhi** [comment]
建议解决了之后主动关issue呢
