### ISSUE TITLE
[Bug]Windows amd64版本WebDav不可用

### ISSUE THREAD

**Issue by hongwen000** [cloudreve/Cloudreve#839]
使用Windows amd64版本cloudreve搭建服务端，注册账号，开启WebDav，使用浏览器访问对应的WebDav网址会反复不断跳出身份认证窗口，使用资源管理器（开启了http WebDav支持）或其他WebDav客户端，提示无法访问。

使用相同配置文件和数据库文件，运行Linux版本的cloudreve，则可以正常访问WebDav

**Comment by wyt990** [comment]
我的也是这样，不知道有没有解决的办法。
