### ISSUE TITLE
[Feature Request]支持对离线下载时aria2服务端返回的文件地址进行转换

### ISSUE THREAD

**Issue by hongwen000** [cloudreve/Cloudreve#840]
aira2是通过rpc调用，客户端（cloudreve）和aria2服务端之间可能存在异构性，aria2返回的文件地址不一定能直接为cloudreve所用。
由于 issue #839 的存在，我在我的Windows设备下不得不使用WSL2下运行cloudreve。由于WSL2不支持ipv6，且访问NTFS磁盘速度很慢，所以我又不得不调用Windows原生的aria2。Windows原生的aria2通过rpc返回的文件地址是类似 "F:/Downloads/file"的格式，而对应的WSL2下的地址是"/mnt/f/Downloads/file"，只有修改monitor.go和tranfer.go的逻辑，添加地址转换功能，才能够正确完成下载。

**Comment by HFO4** [comment]
目前 Cloudreve 必须与 aria2 在同一逻辑环境下运行，地址转换加起来比较复杂，而且用的比较少。
