### ISSUE TITLE
[Feature Request]支持区分BT下载的seeding和active状态

### ISSUE THREAD

**Issue by hongwen000** [cloudreve/Cloudreve#841]
aria2 rpc会将seeding状态的种子返回为active状态，可能需要在cloudreve中通过判断文件的进度比，区分这两个状态。否则做种状态的torrent永远不会被转存。

**Comment by HFO4** [comment]
seeding 状态下文件仍然在被 aria2 使用，在 Windows 下进行转存会导致转存完毕后无法删除临时下载文件。所以还是需要等待做种完成后再进行转存操作。
