### ISSUE TITLE
关于项目的部署，可以直接部署到PHP服务器吗

### ISSUE THREAD

**Issue by fuzhengwei** [cloudreve/Cloudreve#842]
官网介绍：[使用PHP + MySQL架构，简单5分钟即可成功部署您的专属云盘。](https://cloudreve.org/)

如果我只是希望把代码部署到一个类似百度云BCH，这种服务类似于可以直接上传好php工程代码，就可以运行的云服务。

目前的部署方式是一个可执行文件，所以对这块有点疑惑，希望解答

**Comment by Waitung** [comment]
V3开始已经用Go重构，不再是PHP，官网介绍那里是忘了改了。V2版本的才是PHP，不过已经不再维护更新。
