### ISSUE TITLE
添加外部验证器时出现错误, 界面提示 "The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client."

### ISSUE THREAD

**Issue by cxplay** [cloudreve/Cloudreve#845]
- 站点已通过反向代理并开启强制 SSL.
- 已允许使用 Web Authn

## 表现与调试信息

当进入账户设置界面点击 "添加新验证器" 时出现 `The operation either timed out or was not allowed. See: https://www.w3.org/TR/webauthn-2/#sctn-privacy-considerations-client.`

![image](https://user-images.githubusercontent.com/62034099/114524670-ff1c0600-9c77-11eb-86e5-1fba40cff4bc.png)

某一次的响应为   
```
{"code":0,"data":{"publicKey":{"challenge":"xHUPFSeCvsATv+QI72Xz3iLMOi4NaaNe/52cKifzhxI=","rp":{"name":"FileLink","id":"filel.ink"},"user":{"name":"cxplaygo@outlook.com","icon":"https://filel.ink/api/v3/user/avatar/Mnie/l","displayName":"cxplay","id":"AQAAAAAAAAA="},"pubKeyCredParams":[{"type":"public-key","alg":-7},{"type":"public-key","alg":-35},{"type":"public-key","alg":-36},{"type":"public-key","alg":-257},{"type":"public-key","alg":-258},{"type":"public-key","alg":-259},{"type":"public-key","alg":-37},{"type":"public-key","alg":-38},{"type":"public-key","alg":-39},{"type":"public-key","alg":-8}],"authenticatorSelection":{"requireResidentKey":false,"userVerification":"preferred"},"timeout":60000,"attestation":"direct"}},"msg":""}
```

点击时"添加新验证器" Debug 输出信息:
![image](https://user-images.githubusercontent.com/62034099/114524980-486c5580-9c78-11eb-9d88-94b881a6333c.png)

**Comment by cxplay** [comment]
![image](https://user-images.githubusercontent.com/62034099/115153355-16a82400-a0a8-11eb-9a20-bb2e18fb4357.png)
在 Demo 站也发现了这个问题.
Microsoft Edge 版本 90.0.818.41 (官方内部版本) (64 位)

**Comment by HFO4** [comment]
硬件设备、浏览器不支持导致。
