### ISSUE TITLE
代码编辑器报错，提示页面渲染出现错误，请尝试刷新此页面

### ISSUE THREAD

**Issue by Houmura** [cloudreve/Cloudreve#846]
**Describe the bug**

使用代码编辑器预览代码时，会提示“ 页面渲染出现错误，请尝试刷新此页面”，且刷新后依旧如此。

展开错误详情之后提示：

TypeError: window.matchMedia("(forced-colors: active)").addEventListener is not a function. (In 'window.matchMedia("(forced-colors: active)").addEventListener("change",(function(){e._updateActualTheme()}))', 'window.matchMedia("(forced-colors: active)").addEventListener' is undefined)

**Version**
 - OS: Linux amd64
 - Browser: Chrome, Safari
 - Cloudreve Version: 3.3.1  

**Additional Text**
- iOS 系统下的浏览器(Chrome, Safari)会报错
- Windows系统下的浏览器(Chrome, Edge)没有出现问题

**Comment by qeqeq1** [comment]
我是分享页面报错，没有保留信息 就看见了什么group，刷新后正常，在edge和QQ自带浏览器（t5）均复现
