### ISSUE TITLE
希望增加onedrive个人版的功能

### ISSUE THREAD

**Issue by fjhechuan** [cloudreve/Cloudreve#847]
现在只能对接商业版的账户
希望增加onedrive个人版账户的功能

**Comment by AH-dark** [comment]
个人版无法使用Azure，咋调用API？

**Comment by HFO4** [comment]
目前是可以使用个人 OneDrive 账户的

**Comment by Microbai** [comment]
获取refrash token的时候提示账号不是 工作账号，不能是个人账号登陆

**Comment by kncxstudio** [comment]
现在获取授权会提示 "无法使用个人帐户在此登录，请改用工作或学校帐户"
