### ISSUE TITLE
Azure应用密码无法永久

### ISSUE THREAD

**Issue by BA7JCM** [cloudreve/Cloudreve#850]
现在Azure那边创建应用的密码的时候已经没有“永久”这一选项了，最长时间只有两年，我想问下，这种情况下要怎么添加OneDrive

**Comment by huang545** [comment]
如果作者在后期可以考虑添加以账号登陆形式调用API则不需要在考虑密钥过期问题

**Comment by cxplay** [comment]
这不属于 Cloudreve 的问题.
微软修改了政策, 在密码过期之后需要手动更新密码并再次授权

**Comment by BA7JCM** [comment]
> 这不属于 Cloudreve 的问题.
> 微软修改了政策, 在密码过期之后需要手动更新密码并再次授权

那能否像别的同类产品比如“onemanager”和“oneindex”那样自动创建Azure应用或者使用别的已有的Azure应用来解决或者说是绕过这一问题呢？或者能否考虑加个自动续期密钥的功能？或者是像huang545说的那样“以账号登陆形式调用API”？

**Comment by BA7JCM** [comment]
> 如果作者在后期可以考虑添加以账号登陆形式调用API则不需要在考虑密钥过期问题

oneindex的作者是真的牛叉，我帐号换了域了都不需要重新配置，而onemanager就需要重新设置，这点吹爆（滑稽）

**Comment by BA7JCM** [comment]
> 这不属于 Cloudreve 的问题.
> 微软修改了政策, 在密码过期之后需要手动更新密码并再次授权

与cloudreve是同类软件的oneindex可以做到在我更换了我帐号的域之后不需要设置，仍然可以正常运转，我觉得也许您可以参考一下

**Comment by HFO4** [comment]
> > 这不属于 Cloudreve 的问题.
> > 微软修改了政策, 在密码过期之后需要手动更新密码并再次授权
> 
> 与cloudreve是同类软件的oneindex可以做到在我更换了我帐号的域之后不需要设置，仍然可以正常运转，我觉得也许您可以参考一下

Oneindex 这种是通过开发者创建的公用 AAD 应用来实现的，但也会有潜在的问题，比如开发者可以看到所有 OneDrive 使用者的信息；应用因意外不可用时会导致整个使用此系统的用户不再可用。

Cloudreve 选择把创建 AAD 应用这一工作交给用户，而非采用中心化的管理方式，最大可能减少潜在的不确定风险。

**Comment by BA7JCM** [comment]
> > > 这不属于 Cloudreve 的问题.
> > > 微软修改了政策, 在密码过期之后需要手动更新密码并再次授权
> > 
> > 
> > 与cloudreve是同类软件的oneindex可以做到在我更换了我帐号的域之后不需要设置，仍然可以正常运转，我觉得也许您可以参考一下
> 
> Oneindex 这种是通过开发者创建的公用 AAD 应用来实现的，但也会有潜在的问题，比如开发者可以看到所有 OneDrive 使用者的信息；应用因意外不可用时会导致整个使用此系统的用户不再可用。
> 
> Cloudreve 选择把创建 AAD 应用这一工作交给用户，而非采用中心化的管理方式，最大可能减少潜在的不确定风险。

可我当初配置oneindex的时候我看它好像是跳转到一个页面登录自己的帐号，然后才给出ID和密码，那个也是又oneindex开发者创建的吗

**Comment by HFO4** [comment]
> > > > 这不属于 Cloudreve 的问题.
> > > > 微软修改了政策, 在密码过期之后需要手动更新密码并再次授权
> > > 
> > > 
> > > 与cloudreve是同类软件的oneindex可以做到在我更换了我帐号的域之后不需要设置，仍然可以正常运转，我觉得也许您可以参考一下
> > 
> > 
> > Oneindex 这种是通过开发者创建的公用 AAD 应用来实现的，但也会有潜在的问题，比如开发者可以看到所有 OneDrive 使用者的信息；应用因意外不可用时会导致整个使用此系统的用户不再可用。
> > Cloudreve 选择把创建 AAD 应用这一工作交给用户，而非采用中心化的管理方式，最大可能减少潜在的不确定风险。
> 
> 可我当初配置oneindex的时候我看它好像是跳转到一个页面登录自己的帐号，然后才给出ID和密码，那个也是又oneindex开发者创建的吗

那是微软早期给出的自动创建应用的通道，现在已不可用。

**Comment by BA7JCM** [comment]
> > > > > 这不属于 Cloudreve 的问题.
> > > > > 微软修改了政策, 在密码过期之后需要手动更新密码并再次授权
> > > > 
> > > > 
> > > > 与cloudreve是同类软件的oneindex可以做到在我更换了我帐号的域之后不需要设置，仍然可以正常运转，我觉得也许您可以参考一下
> > > 
> > > 
> > > Oneindex 这种是通过开发者创建的公用 AAD 应用来实现的，但也会有潜在的问题，比如开发者可以看到所有 OneDrive 使用者的信息；应用因意外不可用时会导致整个使用此系统的用户不再可用。
> > > Cloudreve 选择把创建 AAD 应用这一工作交给用户，而非采用中心化的管理方式，最大可能减少潜在的不确定风险。
> > 
> > 
> > 可我当初配置oneindex的时候我看它好像是跳转到一个页面登录自己的帐号，然后才给出ID和密码，那个也是又oneindex开发者创建的吗
> 
> 那是微软早期给出的自动创建应用的通道，现在已不可用。

但是前几天我配置tg机器人搞e5的时候好像也是这样的
