### ISSUE TITLE
单独设定分享链接过期条件

### ISSUE THREAD

**Issue by cxplay** [cloudreve/Cloudreve#862]
现有的设置过期方式在调整之后就无法取消其中过期条件, 建议把按时间和按下载次数过期的两种条件分别独立开关;  
或者可设置为数值为 "0" 时定为不启用或不使用这种限制.

为什么必须要同时设置两种过期条件呢？希望能够单独设定过期条件。

**Comment by cxplay** [comment]
今天又遇到了这种问题, 极其容易混淆这两种条件, 建议考虑一下...

**Comment by cxplay** [comment]
很显然并没被解决.

**Comment by HFO4** [comment]
Implemented in 3.8.0-beta1
