### ISSUE TITLE
自定义广告位

### ISSUE THREAD

**Issue by cxplay** [cloudreve/Cloudreve#863]
[运营扩充] 作为重要的一种盈利手段, 广告位可在分享页 / 用户主页 / 登录页 的各种位置, 主要于页脚 / 弹窗 / 贴片等各种方式展示.

**Comment by ggz0638** [comment]
虽不能直接后台添加，可以自己修改前端页面，变相的增加广告或自定义内容

教程：https://fuwa365.com/showinfo-6-8-0.html
