### ISSUE TITLE
在线编辑Office文档会报错

### ISSUE THREAD

**Issue by CJYKK** [cloudreve/Cloudreve#867]
在线编辑Office文档时，会加载很长时间后报错……
![image](https://user-images.githubusercontent.com/59359590/115144864-848d2500-a081-11eb-8e6a-13a4c6897d5c.png)
![image](https://user-images.githubusercontent.com/59359590/115144903-b30b0000-a081-11eb-890b-4b47e01669a2.png)
使用版本：Cloudreve 3.3.1
服务器系统：Debian 10

**Comment by bruceforlearn** [comment]
[GIN] 2020/12/22 - 18:31:14 | 404 |    3.454079ms |     192.168.2.1 | GET      /api/v3/user/avatar/xPTo/s
跨域配置也做了还是不行

**Comment by HFO4** [comment]
Duplicate of #505

**Comment by t826** [comment]
我也在配置文件里设置了跨域允许，但是就是没有设置跨域的响应头出来，期间也更新了配置文件，重启了网盘。
