### ISSUE TITLE
离线下载有多个任务时容易出现这个提示：datebase is locked和其他异常情况

### ISSUE THREAD

**Issue by applesense** [cloudreve/Cloudreve#874]
在使用中发现离线下载到世纪互联SP时容易出现这个提示：datebase is locked,然后aria2依然在下载，cloudreve里只能删除这个任务，第二个问题是离线下载时，cloudreve离线下载页面的某一个任务会像卡死一样，一直不动，然后aria2查到都下载完了，离线下载页面那里还是卡住，等一天还是不动，然后删除任务也删不了，会有错误提示：操作失败。只能把aria2里所有的文件和任务全部删除，过一会才能恢复。。。

**Comment by q601904795** [comment]
黄片哥,你要用MYSQL才行.
自带的litesql抗不了压.

**Comment by applesense** [comment]
卧槽。。 你怎么知道我是黄片哥？



发送自我的盖乐世



-------- 原始信息 --------
发件人： q601904795 ***@***.***>
日期: 2021/4/28 15:56 (GMT+08:00)
收件人： cloudreve/Cloudreve ***@***.***>
抄送： applesense ***@***.***>, Author ***@***.***>
主题： Re: [cloudreve/Cloudreve] 离线下载有多个任务时容易出现这个提示：datebase is locked和其他异常情况 (#874)


黄片哥,你要用MYSQL才行.
自带的litesql抗不了压.

―

**Comment by HFO4** [comment]
3.5后已修复
