### ISSUE TITLE
离线下载完成后文件还在服务器上

### ISSUE THREAD

**Issue by BA7JCM** [cloudreve/Cloudreve#885]
我登录自己的管理员账户去离线下载，它显示离线下载完成，但是我看了我OneDrive里面我选择的那个目录，里面并没有我离线下载的文件，然后我登录服务器的宝塔面板看了，发现文件仍然在我当初给aria2设置的临时目录里，并没有上传到我OneDrive里，可是在cloudreve里面看的话文件的确是在我选择的那个地方

**Comment by HFO4** [comment]
可能是离线下载中途切换了存储策略，或者用户使用的还是本地存储策略。
