### ISSUE TITLE
在线浏览office文件报错

### ISSUE THREAD

**Issue by CupOfBread** [cloudreve/Cloudreve#886]
在线浏览docx文件，报错如下：
An error occurred
We're sorry, but for some reason we can't open this for you.
[Learn more](https://r.office.microsoft.com/r/rlidowaviewhelp)

**Comment by TomLiu-GitHub** [comment]
我也是同样的问题

**Comment by XJain01** [comment]
同样

**Comment by siguofeng** [comment]
我也是同样的问题，解决了吗

**Comment by XJain01** [comment]
换了 蓝眼云盘+KKFILE



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月24日(星期四) 下午4:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cloudreve/Cloudreve] 在线浏览office文件报错 (#886)





 
我也是同样的问题，解决了吗

**Comment by siguofeng** [comment]
是不是因为内网的原因，无法预览，改用了kkFileView，Cloudreve大佬有计划加上kkFileView吗

**Comment by XJain01** [comment]
出现问题应该是调用的微软的在线预览不给力 至于计划 不清楚



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月24日(星期四) 下午5:15
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [cloudreve/Cloudreve] 在线浏览office文件报错 (#886)





 
是不是因为内网的原因，无法预览，改用了kkFileView，Cloudreve大佬有计划加上kkFileView吗

**Comment by gnu-xiaosong** [comment]
要用域名，不能用ip

**Comment by xudong198600** [comment]
> 换了 蓝眼云盘+KKFILE
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: ***@***.***&gt;; 发送时间: 2021年6月24日(星期四) 下午4:56 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [cloudreve/Cloudreve] 在线浏览office文件报错 (#886) 我也是同样的问题，解决了吗 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

蓝眼云盘你是怎么设置预览接口的，我设置的总是说请求被拒绝。

**Comment by alone-86** [comment]
office online 提供的预览服务，要求文件的url中必须是域名，并且需要使用80或者443端口。
https://www.example.com:1234/my/file.doc 这种Url是不行的，https://1.2.3.4/my/file.doc  也是不行的

**Comment by xiaoran4663** [comment]
> 要用域名，不能用ip

怎么配置域名呢，我的是安装的
