### ISSUE TITLE
使用systemd进程守护时运行失败，但是前台运行良好

### ISSUE THREAD

**Issue by gylove1994** [cloudreve/Cloudreve#889]
**问题描述**
我在对cloudreve pro的linux版进行部署时，前台运行良好，但是只要涉及到sysytemd进程守护运行时，就会出现一些令人匪夷所思的BUG。从输出的问题来看很可能是数据库方面的问题，但是无论使用litedb数据库，还是换用mysql数据库，都会存在一些非常致命的问题。最后，希望各位可以协助我解决这一问题，谢谢。
**如何复原这一情况**
请遵循一下步骤:
1. 安装CentOS 8.2.2004 x64 版
2. 使用yum源安装MySQL-server
3. 创建名为cloudreve的空数据库
4. 创建名为cloudreve的用户，并给予cloudreve库的全部操作权限
5. 下载并安装cloudreve pro，赋予该程序777权限，编辑conf.ini，写入相关数据库相关内容
6. 前台启动测试，一切正常
7. ctrl + c 关闭cloudreve pro前台进程
8. 按照手册编辑cloudreve.service
9. 使用systemctl daremon-reload更新配置
10. 尝试启动，启动失败

**可能的情况**
在查看报错提示时，我发现在进程守护下运行时，mysql数据库连接失败，但是在前台运行时却无报错警告。
很有可能是与权限相关的问题，但是由于我对于linux系统以及mysql数据库不太了解，无法解决这一问题。

**相关配置及日志**
程序所在目录：
`/etc/cloudreve`
配置conf.ini：
![image](https://user-images.githubusercontent.com/47300853/117442314-2d37f180-af69-11eb-8959-fee6f8a3518c.png)
配置cloudreve.service：
![image](https://user-images.githubusercontent.com/47300853/117442425-52c4fb00-af69-11eb-95a9-2bed32ab76c1.png)
systemctl status:
![image](https://user-images.githubusercontent.com/47300853/117442796-d383f700-af69-11eb-9c1f-84795eb282f7.png)
journalctl -u cloudreve:
![image](https://user-images.githubusercontent.com/47300853/117442933-fd3d1e00-af69-11eb-9118-c8ae302a1913.png)
前台运行：
![image](https://user-images.githubusercontent.com/47300853/117443088-38d7e800-af6a-11eb-8c71-69d25480062d.png)

**Comment by JohyC** [comment]
我在这边回答有写示例，你可以参考一下。
https://github.com/cloudreve/Cloudreve/issues/749#issuecomment-1200378568
