### ISSUE TITLE
封禁异常流量

### ISSUE THREAD

**Issue by LittleDeng1** [cloudreve/Cloudreve#891]
**Is your feature request related to a problem? Please describe.**
如下图 一秒内有大量不同ip请求同一文件

**Describe the solution you'd like**
如一秒内有大量不同ip请求相同链接时 做出封禁

**Describe alternatives you've considered**

**Additional context**
这堆异常流量请求了数小时 仅取了部分输出信息并关服
![image](https://user-images.githubusercontent.com/62782358/117530333-26fc5080-b00f-11eb-9c94-d6b6e764188d.png)

**Comment by AH-dark** [comment]
这个应该放Nginx和CDN层面上

**Comment by LittleDeng1** [comment]
@AH-dark 用的release编译好的windows版 直接就在自己机子用 nginx和cdn都用不上
