### ISSUE TITLE
希望添加小功能

### ISSUE THREAD

**Issue by kyzypm** [cloudreve/Cloudreve#892]
1、pc端存在搜索，wap却没有，希望作者捎带加这个。
2、打包下载的时候如果是单一的文件（或文件夹）如果是文件的名字或文件夹名称比较好，现在下载都叫active.zip。
3、文件夹中存在文件时候无法删除，希望可以删除，大不了文件夹中存在文件的时候给个确认提示。
4、媒体在线播放支持的格式太少了。
5、文件下载后文件名如果不加前缀更好一些，或可以设置。

**Comment by Yuelioi** [comment]
> 1、pc端存在搜索，wap却没有，希望作者捎带加这个。
> 2、打包下载的时候如果是单一的文件（或文件夹）如果是文件的名字或文件夹名称比较好，现在下载都叫active.zip。
> 3、文件夹中存在文件时候无法删除，希望可以删除，大不了文件夹中存在文件的时候给个确认提示。
> 4、媒体在线播放支持的格式太少了。
> 5、文件下载后文件名如果不加前缀更好一些，或可以设置。

5可以自己设置的，在储存策略那
