### ISSUE TITLE
Pro付费下载的问题

### ISSUE THREAD

**Issue by Yuelioi** [cloudreve/Cloudreve#894]
目前的问题
下载付费资源，需要先登录，再去购买积分，再下载。。流程太长了，作为游客来说太复杂

解决方案：
付费资源直接扫码付款，然后就可以下载了（省去买积分的问题）

希望加的内容
1.付费资源免登陆下载。。有点讨厌登录下载的模式，比如百度云
2.目前几个大平台都是储存+下载流量分开计算，所以可不可以加个下载流量包。。比如下载10G/1元

**Comment by Yuelioi** [comment]
1. 打开付费资源链接
![1](https://user-images.githubusercontent.com/46314093/117632537-d112de80-b1af-11eb-9fa6-659097fb7b37.png)
2. 点击下载，提示要登录
![2](https://user-images.githubusercontent.com/46314093/117632573-d839ec80-b1af-11eb-9080-5a58b727c9aa.png)
3. 注册、登录完成
![3](https://user-images.githubusercontent.com/46314093/117632590-da03b000-b1af-11eb-89a1-ee266bdf341b.png)
4. 找到容量配额（游客估计都不知道在哪）
![4](https://user-images.githubusercontent.com/46314093/117632601-dbcd7380-b1af-11eb-8b11-4a81976092c0.png)
5. 购买积分
![5](https://user-images.githubusercontent.com/46314093/117632610-dcfea080-b1af-11eb-9ed1-e5d1e14e43fe.png)
6. 再找到原来的资源链接，才能下载
![6](https://user-images.githubusercontent.com/46314093/117632630-e12abe00-b1af-11eb-9e90-72079ceaf515.png)

这个流程 感觉跟恶心的百度云没区别了。屠龙勇者终成龙么

**Comment by AH-dark** [comment]
确实应该做一下这个直接付款的

**Comment by miniers** [comment]
确实流程有些繁琐，希望支持直接付费

**Comment by snowdream** [comment]
繁琐的流程会消耗用户的耐心，确实可以考虑优化。
