### ISSUE TITLE
能否添加对存储策略的某一目录结构的自动导入功能

### ISSUE THREAD

**Issue by cnbright** [cloudreve/Cloudreve#896]
例如，有一cloudreve账户的一存储策略的存储路径在/root文件夹下，当我通过smb向服务器的smb存入一文件后，cloudreve需要进行一次"从外部目录导入"，才能让这个文件出现在该账户的文件列表中，能否添加一个开关，使从cloudreve之外对存储目录中所做的修改自动同步到cloudreve中。

简单点说，就是像可道云那种，从外部对存储目录做的修改，在可道云里也能同步过去

或者单独添加一个这种类型的存储策略？

**Comment by ITCJ** [comment]
同问

**Comment by zfs156** [comment]
这个功能要是有可就太棒了，以后可以直接向某个目录里写东西或者删除东西，云盘里就能同步这个文件的删除或者添加状态，那可就太好了。我直接就把onedrive卸载掉
