### ISSUE TITLE
[Feature Request] 分享页面移动端优化

### ISSUE THREAD

**Issue by ShellWen** [cloudreve/Cloudreve#898]
Cloudreve V3.3.0 版本进行了一次大规模的 移动端优化，在移动端界面右上角增加了显示模式切换以及排序方式切换，但是在分享页面似乎并没有进行相关优化，导致在移动端打开分享页面无法调整显示模式切换和排序方式
不知道是 bug 还是没做，尚且就当做 feat 吧

**Comment by cxplay** [comment]
#868 相同的建议

**Comment by Herts** [comment]
我看了一下，是分享页面调整显示模式的按钮没放上去。

**Comment by GoFly233** [comment]
主要是不会写 React，哪个大佬写一下 PR（笑2021年5月18日 上午9:11，Herts Li ***@***.***>写道：

我看了一下，是分享页面调整显示模式的按钮没放上去。

**Comment by HFO4** [comment]
在3.5.3中修复。
