### ISSUE TITLE
🚨 Potential Security Vulnerability

### ISSUE THREAD

**Issue by ranjit-git** [cloudreve/Cloudreve#907]
Hello, @HFO4 , @hiCasper , @mritd  - Three potential high severity security vulnerability in your repository has been disclosed to huntr.

Visit report url and validate them 
[https://www.huntr.dev/bounties/4-other-cloudreve/Cloudreve/](https://www.huntr.dev/bounties/4-other-cloudreve/Cloudreve/)
[https://www.huntr.dev/bounties/3-other-cloudreve/Cloudreve/](https://www.huntr.dev/bounties/3-other-cloudreve/Cloudreve/)
[https://www.huntr.dev/bounties/2-other-cloudreve/Cloudreve/](https://www.huntr.dev/bounties/2-other-cloudreve/Cloudreve/)

**Comment by HFO4** [comment]
Thanks! We'll look into these later.
