### ISSUE TITLE
预览PDF文件提示加载pdf.js失败

### ISSUE THREAD

**Issue by qq77522980** [cloudreve/Cloudreve#908]
![image](https://user-images.githubusercontent.com/74188271/119350017-68f4ea00-bcd1-11eb-9870-9c349ed6150c.png)
如图，双击预览PDF文件提示加载插件失败，不知道是否是cloudflare的CDN故障，能否将PDF.JS改为本地加载？

**Comment by cyhcyh** [comment]
我也遇到了相同的问题，在有些网络环境下加载失败，同建议将pdf.work.js本地加载，或添加相关自定义的设置。

**Comment by wangwuxuan2011** [comment]
+1，遇到了相同的问题

**Comment by GXU3KG** [comment]
同，求添加
