### ISSUE TITLE
构建过程中/环境准备/4，go get github.com/rakyll/statik报错。

### ISSUE THREAD

**Issue by ZhiboWong** [cloudreve/Cloudreve#912]
报错咋办？
`C:\Users\81239>go get github.com/rakyll/statik
go: github.com/rakyll/statik upgrade => v0.1.7
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\statik.go:20:2: package archive/zip is not in GOROOT (D:\APPs\_Programming\Go\bin\src\archive\zip)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\statik.go:21:2: package bytes is not in GOROOT (D:\APPs\_Programming\Go\bin\src\bytes)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\fs\fs.go:21:2: package errors is not in GOROOT (D:\APPs\_Programming\Go\bin\src\errors)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\statik.go:22:2: package flag is not in GOROOT (D:\APPs\_Programming\Go\bin\src\flag)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\statik.go:23:2: package fmt is not in GOROOT (D:\APPs\_Programming\Go\bin\src\fmt)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\fs\fs.go:23:2: package io is not in GOROOT (D:\APPs\_Programming\Go\bin\src\io)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\fs\fs.go:24:2: package io/ioutil is not in GOROOT (D:\APPs\_Programming\Go\bin\src\io\ioutil)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\fs\fs.go:25:2: package net/http is not in GOROOT (D:\APPs\_Programming\Go\bin\src\net\http)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\fs\fs.go:26:2: package os is not in GOROOT (D:\APPs\_Programming\Go\bin\src\os)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\fs\fs.go:27:2: package path is not in GOROOT (D:\APPs\_Programming\Go\bin\src\path)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\fs\fs.go:28:2: package path/filepath is not in GOROOT (D:\APPs\_Programming\Go\bin\src\path\filepath)
package github.com/rakyll/statik: cannot find package
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\fs\fs.go:29:2: package sort is not in GOROOT (D:\APPs\_Programming\Go\bin\src\sort)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\fs\fs.go:30:2: package strings is not in GOROOT (D:\APPs\_Programming\Go\bin\src\strings)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\fs\fs.go:31:2: package time is not in GOROOT (D:\APPs\_Programming\Go\bin\src\time)
D:\Study makes me happy\go\pkg\mod\github.com\rakyll\statik@v0.1.7\statik.go:32:2: package unicode is not in GOROOT (D:\APPs\_Programming\Go\bin\src\unicode)`

**Comment by TheresaQWQ** [comment]
需要手动安装一下 statik，然后执行嵌入前端资源的命令，然后就可以正常编译了
