### ISSUE TITLE
根据MINE的text类型来启用编辑

### ISSUE THREAD

**Issue by hilaolu** [cloudreve/Cloudreve#917]
如题，我参阅了#748，个人认为通过追加后缀名列表不是优雅的办法。而且某些文本文件甚至连后缀都没有。可不可以根据MINE类型来启用编辑？

**Comment by HFO4** [comment]
不太好改，主要原因是：
1. 因为历史遗留问题，之前的文件并未记录MIME信息；
2. 部分第三方存储无法方便的获取MIME信息；
3. 采用后缀名判断更加灵活，用户可以通过更改后缀名切换预览方式。

**Comment by AH-dark** [comment]
为何不考虑，优先取mime，取不了就判断后缀？
