### ISSUE TITLE
下载文件时报错“无法获取外链”

### ISSUE THREAD

**Issue by fangaso** [cloudreve/Cloudreve#919]
首先在提问之前看了有关的一个issue，但是发现原因不同。
一些信息：使用onedrive，未曾移动文件
之前上传的文件昨天(2021.6.5)还可以正常下载，但是今天就不行了，提示“无法获取外链”，之后我又重新上传了一个新文件，发现可以正常下载。
希望可以解决这个问题！谢谢！

**Comment by HFO4** [comment]
可能是文件被删除、移动，或者是被OneDrive屏蔽。
