### ISSUE TITLE
希望支持DigitalOcean Spaces

### ISSUE THREAD

**Issue by huanjue** [cloudreve/Cloudreve#92]
https://developers.digitalocean.com/documentation/spaces/
https://blog.csdn.net/www359956085/article/details/79235823
这是他们的API和一个API实例

digitalocean spaces是一个云存储空间。可以用户自己上传文件，也可以用API上传
我有一个space账户，但是现在不知道该干啥，免费两个月不发挥点作用有点亏了。。

**Comment by AceKevinMark** [comment]
+1
