### ISSUE TITLE
启动 cloudreve之后，使用es文件浏览器配置webdav连接，操作无法操作文件与文件夹，也看不到在web创建的文件夹

### ISSUE THREAD

**Issue by 471417811** [cloudreve/Cloudreve#920]
启动 cloudreve之后，使用es文件浏览器配置webdav连接，操作无法操作文件与文件夹，也看不到在web创建的文件夹
实现步骤：
1、启动cloudreve服务
2、创建一个“测试文件夹”
3、手机es文件浏览器连接webdav
4、连接成功后，新建——文件夹，提示：正在创建文件夹，创建失败，文件夹已存在。 实际是不存在的，之前在web创建的"测试文件夹"也看不到
5、已经配置sll证书，跟证书应该是无关的（尝试过http,https，都不行）

**Comment by yindaheng98** [comment]
我直接输入IP地址`xxx.xxx.xxx.xxx`连接的时候和你是一样的情况，
但是cloudreve写了用webdav要加上`/dav`路径，我输入`xxx.xxx.xxx.xxx/dav`连接直接就报“找不到服务器”，
用PC上其他软件连webdav都能正常用，感觉是ES的问题

**Comment by 471417811** [comment]
嗯，我已经换了，直接浏览器访问，把快捷方式发送到桌面一个图标，用起来也还好。就是他的地址是要自己面板里面配置的绝对路径，本地访问与公网访问切换很不友好
