### ISSUE TITLE
分享链接中的网址修改

### ISSUE THREAD

**Issue by somedisappoint** [cloudreve/Cloudreve#922]
现在分享链接中的域名地址还是localhost，对于远程访问服务器非常不方便，是不是在配置文件中或者是浏览器也面中支持修改。
![image](https://user-images.githubusercontent.com/49521223/121983428-e6d57e00-cdc3-11eb-9592-f389b8b601cb.png)

**Comment by Beattheend** [comment]
我对你这个问题表示怀疑。

**Comment by jiangwenfan** [comment]
遇到同样的问题，如何修改啊？

**Comment by xvzhenduo** [comment]
看一下管理面板-站点信息里的域名，是不是填成localhost了

**Comment by shylock-wu** [comment]
> 遇到同样的问题，如何修改啊？

具体在哪儿修改啊，Setting设置里面没有呀

**Comment by xvzhenduo** [comment]
> > 遇到同样的问题，如何修改啊？
> 
> 具体在哪儿修改啊，Setting设置里面没有呀

![image](https://github.com/user-attachments/assets/6384ce0b-3d98-419e-87b3-82f07da88b42)

**Comment by xvzhenduo** [comment]
> > > > 遇到同样的问题，如何修改啊？
> > > 
> > > 
> > > 具体在哪儿修改啊，Setting设置里面没有呀
> > 
> > 
> > <img alt="image" width="1280" src="https://private-user-images.githubusercontent.com/74353173/356184936-3dc62609-a8fe-4a5d-9054-454d0e917d43.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMxMjAxMzIsIm5iZiI6MTcyMzExOTgzMiwicGF0aCI6Ii83NDM1MzE3My8zNTYxODQ5MzYtM2RjNjI2MDktYThmZS00YTVkLTkwNTQtNDU0ZDBlOTE3ZDQzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA4VDEyMjM1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThlNWQ5MzY1MTk0ZWRiMzE1OWVhMjM1N2RlY2RmYTJiMTEwNTJhNzdkZTQzMDY3MTY1NzU5MDk2MDUyYjhmOTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qmrR28yAQU3xsiu9v-QIgpzQereXSGvh2clj4F9x5m8">
> 
> 你的和我的怎么不一样啊 @xvzhenduo
> 
> ![CleanShot 2024-08-08 at 20 22 30@2x](https://private-user-images.githubusercontent.com/73875874/356220034-39a0d11d-cf36-4015-b202-8a37a36d3b20.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyMDg1NzcsIm5iZiI6MTcyMzIwODI3NywicGF0aCI6Ii83Mzg3NTg3NC8zNTYyMjAwMzQtMzlhMGQxMWQtY2YzNi00MDE1LWIyMDItOGEzN2EzNmQzYjIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODA5VDEyNTc1N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYwYmEwZmM5NTRjZDIyZGE0NmFjOGEyYWFiNmM4N2E5MTY5ZTk1MDEzMmZlMzIwZjRiOThkODQ3YTI2MjNlMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5Lz6WfPjMN-NKosWfQ-cPBRuVqiABlxRHsKL-ESOtKE)

只能在管理面板上改啊，点击头像，如果你是管理员的话会出现一个管理面板选项
