### ISSUE TITLE
站点url能否使用相对路径？

### ISSUE THREAD

**Issue by 471417811** [cloudreve/Cloudreve#925]
当用作家庭云盘的时候，经常需要本地局域网与公网frp之间进行切换下载网盘资源。
1、本来局域网可以通过：局域网ip:端口，进行访问，下载速度非常快
2、之后只要再用  域名：端口访问了一下公网，就需要修改站点url，才可以下载
3、每次公网局域网之间都需要手动去切换一下，一旦在公网模式切回局域网url的时候，忘记换站点url了，下载文件的时候速度就是公网绕一圈回来的速度，跟局域网的速度完全没办法相比
4、希望能够有个模式，能够直接使用相对路径来加载下载地址，这样，我如果用  局域网ip:端口访问，那么就使用局域网去加载请求了，我观察了一下，他们之间的不同无非下载地址 局域网使用 http://192.168.1.3:5212  与 公网使用 http://pan.xxxx.cn:5212 的区别而已

**Comment by qq77522980** [comment]
你可以将你的域名加入本地hosts，无论在哪里都用域名访问，可以无缝实现局域网和公网访问。配置里填入域名即可。

**Comment by topjohncian** [comment]
可以更改本地策略专家设置中的 文件资源根URL
![image](https://user-images.githubusercontent.com/45138629/125194872-c3e49f80-e285-11eb-91fb-2316d1ca3624.png)
