### ISSUE TITLE
下载时需要将localhost替换为域名

### ISSUE THREAD

**Issue by jiangwenfan** [cloudreve/Cloudreve#927]
无法直接下载，需要替换连接中的域名才能下载。
![image](https://user-images.githubusercontent.com/35188849/123187816-73232780-d4cd-11eb-8276-856bc9772d6a.png)

**Comment by fuheiliu** [comment]
面板里有没有把网站域名更改好？

**Comment by xvzhenduo** [comment]
你看一下你的储存策略里的cnd域名是不是填成localhost了
