### ISSUE TITLE
github.com/cloudreve/Cloudreve/v3/statik not found

### ISSUE THREAD

**Issue by mxue12138** [cloudreve/Cloudreve#928]
`
github.com/cloudreve/Cloudreve/v3 imports
	github.com/cloudreve/Cloudreve/v3/bootstrap imports
	github.com/cloudreve/Cloudreve/v3/statik: cannot find module providing package github.com/cloudreve/Cloudreve/v3/statik
`

**Comment by mxue12138** [comment]
![image](https://user-images.githubusercontent.com/35069089/123215440-03c42c80-d4fb-11eb-9442-1767f4e2bf1f.png)

**Comment by HFO4** [comment]
参考文档，需要嵌入静态资源。
