### ISSUE TITLE
關於文件夾的改名效率問題

### ISSUE THREAD

**Issue by yeungc** [cloudreve/Cloudreve#93]
剛開始試用了一下Cloudreve 發現文件夾的絕對路徑是直接儲存在數據庫裡 然後每次用戶給文件夾改名的時候 都會用LIKE %的方式尋找底下所有文件夾跟檔案 每個檔案各自用一句SQL改名

如果檔案的數量少 那這樣應該沒有問題 但是如果要改名的文件夾底下有1萬個檔案呢? 首先要將這1萬個檔案用LIKE %找出來 然後再運行1萬次更新檔案名字的SQL 效率似乎會變得非常差

如果有考慮支援這種情況 建議用樹形結構

**Comment by HFO4** [comment]
v3版本中已解决此问题
