### ISSUE TITLE
使用宝塔的nginx进行反向代理之后，上传文件“处理中”需要很长时间

### ISSUE THREAD

**Issue by ipangbo** [cloudreve/Cloudreve#932]
**Describe the bug**
我已经设置了nginx允许最大上传文件为4g，但是设置后我发现上传文件会卡在处理中很长时间，但是最后可以上传成功。
控制台没有报错，文件也没有损坏，只是单纯的处理时间长

**Expected behavior**
能解决卡在处理的问题

**Desktop (please complete the following information):**
 - OS: Ubuntu20.04
 - Browser: Chrome. Edge
 - Version 91

**Comment by ipangbo** [comment]
补充一下，用端口访问的话处理的过程会很快，加了反向代理才出问题，但是不知道具体是怎么导致的，所以请教

**Comment by heartnn** [comment]
我只知道小文件是直接通过本地中转到远程的，大文件是直接长传到远程，我的存储是用的onedrive

**Comment by HFO4** [comment]
关闭宝塔的缓存或者其他可能阻碍流式传输的功能。
