### ISSUE TITLE
panic: 无法创建初始存储策略, Error 1366: Incorrect string value: '\xE9\xBB\x98\xE8\xAE\xA4...' for column 'name' at row 1

### ISSUE THREAD

**Issue by zhengfenwei** [cloudreve/Cloudreve#934]
![image](https://user-images.githubusercontent.com/7141804/123911250-20a2a900-d9ae-11eb-8c1d-10f8b4891279.png)

**Comment by zhengfenwei** [comment]
数据库版本：mysql> select version();
+------------+
| version()  |
+------------+
| 5.7.34-log |
+------------+
1 row in set (0.00 sec)

**Comment by zhengfenwei** [comment]
切换为sqlite数据库，则正常

**Comment by wangxiaoerYah** [comment]
解决办法 #1096 

@HFO4 close issue
