### ISSUE TITLE
关于二步验证的一个问题

### ISSUE THREAD

**Issue by yoyosscn** [cloudreve/Cloudreve#937]
自己管理员的账号配置了二步验证 绑定的是谷歌原版 无备份 前几天不小心删除了 现在管理员账号登陆不进去 请问能怎么重新指定一个管理员账号或者关闭这个账号的二步验证的方法吗

[GIN] 2021/07/04 - 14:38:07 | 200 |    2.105014ms |   | POST     /api/v3/user/session
[GIN] 2021/07/04 - 14:38:12 | 200 |     741.462µs |   | POST     /api/v3/user/2fa
试试了一下查看了下日志
没啥可用信息 找了好久服务器上和数据库 由于不怎么懂数据库就只是看了看 没看到关闭二步验证的关联项..

**Comment by HFO4** [comment]
在数据库中将`users`表的`two_factor`字段改为空值

**Comment by yoyosscn** [comment]
查找了 一番数据库 还是没找到users表里有这个字段...
USER | CURRENT_CONNECTIONS | TOTAL_CONNECTIONS |  
        -- | -- | -- | --
    NULL | 19 | 22
      root | 2 | 823
 xxxxx.xxxxxx.xx| 0 | 430
唯一匹配的就是这个数据库performance_schema里才找到的这users的表...

**Comment by yoyosscn** [comment]
> 在数据库中将`users`表的`two_factor`字段改为空值

查找了一番数据库还是没找到用户表里有这个字段...
USER | CURRENT_CONNECTIONS | TOTAL_CONNECTIONS |  
-- | -- | -- | --
空 | 19 | 22
根| 2 | 第823
话 0 | 430
唯一匹配的就是这个数据库性能_模式里才找到的用户表...

**Comment by JaneYork** [comment]
> > 在数据库中将`users`表的`two_factor`字段改为空值
> 
> 查找了一番数据库还是没找到用户表里有这个字段... USER | CURRENT_CONNECTIONS | TOTAL_CONNECTIONS | -- | -- | -- | --
> 
> 唯一匹配的就是这个数据库性能_模式里才找到的用户表...
> 
> 我想请问一下还有没有其它的解决方法 ？

https://github.com/cloudreve/Cloudreve/issues/1495#issuecomment-1272478418
