### ISSUE TITLE
【功能增强建议】在网盘内以及分享时优化md文件链接

### ISSUE THREAD

**Issue by WangWenBin2017** [cloudreve/Cloudreve#938]
比如我在文件夹/MD/创建了一个文件README.md，里面链接到了另一个md文件：./md1.md ，点击预览之后渲染出来的文件连接是/md1.md而不是/MD/md1.md，分享的时候也是，比如我将这个文件夹分享，分享链接是https://host/s/67hM，里面的README.md同样有个到./md1的链接，会发现预览创建出来的链接是https://host/s/md1.md而不是https://host/s/67hM/md1.md，用起来比较不友好。希望修复一下。(我举例的情况比较简单，实际处理起来可能会复杂一些)

**Comment by topjohncian** [comment]
@HFO4 我觉得可以在前端渲染MD时增加一些魔法变量
比如说 分享链接
