### ISSUE TITLE
如何加入TLS证书呢

### ISSUE THREAD

**Issue by wangyifan349** [cloudreve/Cloudreve#939]
这个
tar -zxvf cloudreve_VERSION_OS_ARCH.tar.gz

# 赋予执行权限
chmod +x ./cloudreve

# 启动 Cloudreve
./cloudreve
不是https的网站如何让他支持https

**Comment by HFO4** [comment]
参考 https://docs.cloudreve.org/getting-started/config#qi-yong-https
