### ISSUE TITLE
数据库下载表的字段范围

### ISSUE THREAD

**Issue by li-guohao** [cloudreve/Cloudreve#941]
当使用aria2下载时，如果下载的文件数量非常多，
downloads表的attrs字段会超出text类型的最大范围，导致下载任务失败，(之前下一个50G的磁力链接时出现的问题)
建议将attrs字段类型改为longtext类型

还有
每次重启机器之后，会报Gid找不到
GID xxx is not found
然而磁力链接无法重新添加，会报infoHash已经被注册了
InfoHash xxx  is already registered.

这个问题我翻了翻数据库表，找不到啥好的解决办法

**Comment by Tymon42** [comment]
同 InfoHash xxx is already registered. 目前也没有手动处理的方法吗？

**Comment by li-guohao** [comment]
> 同 InfoHash xxx is already registered. 目前也没有手动处理的方法吗？

暂时我没找到什么合适的解决方法，我目前是尽量避免有任务在下载的时间重启机器。

**Comment by li-guohao** [comment]
@HFO4 大哥，这个issue 是暂时挂着还是我这边关掉？

**Comment by Yummy-Cookie-S** [comment]
在 Cloudreve 无法下载提示 InfoHash xxx is already registered. 的问题原因是 Cloudreve 和 aria2 数据不同步
Cloudreve 已经没有这个任务了，但 aria2还有持有这个任务

解决方法:
首先删除缓存目录，比如对我来说是
/usr/local/caddy/www/aria2/Download/aria2/*
可以很容易的通过 ` find / -name *.aria2 2>/dev/null ` 命令来找到他
**我不知道这是否是必要的，或许是不必的 :D**

然后删除 aria2.session ，对我来说它位于  /root/.aria2/aria2.session
同样可以通过 ` find / -name aria2.session 2>/dev/null ` 命令来定位
在删除后重新创建一个空文件 `touch aria2.session`
这个是重要的，**这将清理所有任务，失去现有的断点续传，如果有希望保留特定的任务可以手动编辑该文件**

注意，这些是在 aria2 关闭的情况下做的
作为这些后再重新启动 aria2 ，问题解决√

注：
当` find `没有返回值时尝试` sudo find `，这些文件的位置可能没有读取权限
