### ISSUE TITLE
对于 离线下载 功能提出的两点建议

### ISSUE THREAD

**Issue by MisaLiu** [cloudreve/Cloudreve#943]
**Is your feature request related to a problem? Please describe.**
用户可能会使用 离线下载 功能创建大文件下载任务或是大量下载任务，可能会拖慢服务器速度并加剧占用服务器存储空间

**Describe the solution you'd like**
给用户组增加 限制离线下载文件最大大小 和 限制离线下载同时在线任务数 的参数，限制用户下载的文件大小和同时在线的任务数量

**Describe alternatives you've considered**
或者也可以限制用户一段时间内可以创建的任务数量

**Additional context**
应该不需要

**Comment by xvzhenduo** [comment]
后台配置中可以给指定用户组加离线下载的参数

**Comment by HFO4** [comment]
会在 3.5.3 中增加。

**Comment by afxdxhy** [comment]
> Referenc

请尽快添加限制离线下载文件大小的功能 一旦用户上传了很大的文件 如果服务器存储不够，那么就会炸服务器
