### ISSUE TITLE
打包下载功能建议

### ISSUE THREAD

**Issue by huang545** [cloudreve/Cloudreve#947]
建议可以批量下载，而不是服务器打包下载，这样可以方便下载且不会占用太多服务器资源

**Comment by xvzhenduo** [comment]
但是文件夹怎么处理？浏览器下载没法指定下载的位置，而且有的时候几千张图片你确定浏览器不会卡死？

**Comment by huang545** [comment]
> 但是文件夹怎么处理？浏览器下载没法指定下载的位置，而且有的时候几千张图片你确定浏览器不会卡死？

你有考虑过几千张图片下载的时候服务器会卡死么？
文件夹只能让用户先行创建修改系统的默认下载目录，至少这样子还能够下载少量的文件，不然这个功能本身就不怎么可以使用。

**Comment by xvzhenduo** [comment]
但是我下几千张图片时我的服务器一点事也没有

**Comment by huang545** [comment]
> 但是我下几千张图片时我的服务器一点事也没有（我的服务器是普通的i5芯的家用电脑）

这种方法只适合你小范围使用啊
我现在是785的注册数，日IP是300-350，服务器是8255C的2H
如果开放这个功能的话服务器直接炸票了

**Comment by xvzhenduo** [comment]
但是批量下载，你的服务器也受不了啊，一下几千个请求，而且用户体验十分不好，如果不知道关闭在每次下载时询问保存位置，那就得点几千下

**Comment by xvzhenduo** [comment]
你可以试着给他们限速

**Comment by huang545** [comment]
> 你可以试着给他们限速

你要确定一件事，这种批量下载的方式不能作为生产环境使用
就算你是家用电脑，你的ISP给你的上行也是有限制的，不是无止境的
我的建议是还是提前做一个提示，提醒他们更换对应的下载目录，点确认之后再开始批量请求下载
服务器请求倒是没问题，nginx的并发没这么低

**Comment by hatsuyuki280** [comment]
@huang545 有一说一。。。
还有那种包含大文件的情况。。。
如果选择打包下载。。。
（一堆大文件的情况下）打包过程中后端可能还会原地爆炸。。。。

然后前端会收到无法连接到后端的提示。。。过一会等待后端自动重启啥的。。。能不打包直接按文件夹下载是最好的

至于下载的时候目录怎么办的问题，有一种叫做浏览器插件的东西。。。。。
或者可以生成一个wget下载脚本/aria下载脚本之类的也行

ps：文件比较多的话咱个人也很偏向多文件同时下载而不是选择打包下载

**Comment by hatsuyuki280** [comment]
能在用户这边用脚本或者插件解决的问题，
浪费后端的资源去跑一大堆文件的压缩感觉并不会比想象的划算多少

**Comment by huang545** [comment]
> @huang545 有一说一。。。
> 还有那种包含大文件的情况。。。
> 如果选择打包下载。。。
> （一堆大文件的情况下）打包过程中后端可能还会原地爆炸。。。。
> 
> 然后前端会收到无法连接到后端的提示。。。过一会等待后端自动重启啥的。。。能不打包直接按文件夹下载是最好的
> 
> 至于下载的时候目录怎么办的问题，有一种叫做浏览器插件的东西。。。。。
> 或者可以生成一个wget下载脚本/aria下载脚本之类的也行
> 
> ps：文件比较多的话咱个人也很偏向多文件同时下载而不是选择打包下载

对的，这个解决办法也是可行的，如果直接让后端来做，根本没办法做

**Comment by hatsuyuki280** [comment]
实在不行，还可以考虑先按照目录格式下载去浏览器blob里，再想办法引导用户自己从blob里把文件弄出来/额外准备个浏览器脚本之类的大概也是个办法

**Comment by xvzhenduo** [comment]
> 实在不行，还可以考虑先按照目录格式下载去浏览器blob里，再想办法引导用户自己从blob里把文件弄出来/额外准备个浏览器脚本之类的大概也是个办法

最好的办法是做一个客户端

**Comment by xvzhenduo** [comment]
> 能在用户这边用脚本或者插件解决的问题，
> 浪费后端的资源去跑一大堆文件的压缩感觉并不会比想象的划算多少

可以试着在后端只打包，不进行压缩，这样可以节省很多资源

**Comment by huang545** [comment]
> > 能在用户这边用脚本或者插件解决的问题，
> > 浪费后端的资源去跑一大堆文件的压缩感觉并不会比想象的划算多少
> 
> 可以试着在后端只打包，不进行压缩，这样可以节省很多资源

你可能玩的不是服务器，服务器的上行是非常小的，10M的上行就已经要很多钱了，，，这一部分如果是生产环境下就不应该交给后端来做，因为服务器的上行太小，下载这一个都有可能造成阻塞

**Comment by xvzhenduo** [comment]
> > > 能在用户这边用脚本或者插件解决的问题，
> > > 浪费后端的资源去跑一大堆文件的压缩感觉并不会比想象的划算多少
> > 
> > 
> > 可以试着在后端只打包，不进行压缩，这样可以节省很多资源
> 
> 你可能玩的不是服务器，服务器的上行是非常小的，10M的上行就已经要很多钱了，，，这一部分如果是生产环境下就不应该交给后端来做，因为服务器的上行太小，下载这一个都有可能造成阻塞

我用的是自己的电脑+钉钉开发者的免费内网穿透(不限速)

**Comment by hatsuyuki280** [comment]
@xvzhenduo 咱的服务器上传感觉还挺大的呀
主要提供文件服务的主服务器上行1G
几个主要提供各种api的从属服务器
以前还有一个上行10G的主要放备份之类的冷文件(后来觉得没什么用了就取消了)

现阶段来说姑且带宽还是够用的…至少不是只有10M

**Comment by qins** [comment]
1. 服务器上进行压缩很大可能爆盘
比如

> 我是50G硬盘/2G内存的云盘+2T的对象存储
> 上传了100个4G大小的文件
> 压缩的话, 会把400G的文件放到50G硬盘上去

2. 小文件也有便捷性问题
> 假如20张图片的文件夹下载
> 本来只需要选中点击下载查看
> 现在只能先压缩, 下载后再解压查看

只要有个类似客户端的东西, 可以在本地新建文件夹, 按理说下载文件夹没问题才对

**Comment by cyhcyh** [comment]
> 1. 服务器上进行压缩很大可能爆盘
> 
> > 我是50G硬盘/2G内存的云服务器+2T的对象存储(COS)
> > 上传了100个4G大小的文件
> > 压缩的话, 会把400G的文件放到50G硬盘上去
> 
> 2. 小文件也有便捷性问题
> 
> > 假如20张图片的文件夹下载
> > 本来只需要选中点击下载查看
> > 现在只能先压缩, 下载后再解压查看
> 
> 只要有个类似客户端的东西, 可以在本地新建文件夹, 按理说下载文件夹没问题才对; 可以限制下载线程

用WebDAV可以实现。电脑上用AirExplorer，手机用Solid explorer，WebDAV连上以后选择想要的文件夹拷贝下来就行。

**Comment by HFO4** [comment]
3.5.0后已支持客户端打包下载和服务端流式中转
