### ISSUE TITLE
OneDrive分片上传和重试次数能否放宽?

### ISSUE THREAD

**Issue by q601904795** [cloudreve/Cloudreve#948]
`const (
	// SmallFileSize 单文件上传接口最大尺寸
	SmallFileSize uint64 = 4 * 1024 * 1024
	// ChunkSize 服务端中转分片上传分片大小
	ChunkSize uint64 = 10 * 1024 * 1024
	// ListRetry 列取请求重试次数
	ListRetry = 1
)
`

有个疑问.作者为何把分片上传尺寸设置为10m,并且重试次数设置为1?
是OneDrive限制?

**Comment by topjohncian** [comment]
网页端上传为 100M 一个分片

**Comment by q601904795** [comment]
明了

**Comment by lsCoding666** [comment]
我试了下 把这里改为100* 1024 *1024
https://github.com/cloudreve/Cloudreve/blob/c84d0114ae53f67800cca8b702254b9f6e69b604/pkg/filesystem/driver/onedrive/api.go#L30
上传速度如下 提升很多
![image](https://user-images.githubusercontent.com/73888354/153318649-982b469e-ee48-45e2-99a0-cab593506bae.png)
![image](https://user-images.githubusercontent.com/73888354/153318660-1474b34a-c2d2-426a-8ccc-66c82005e1de.png)

不过貌似分片之间间隔的时间也长了 或许50 * 1024 *1024比较合适 反正是比10 *1024 *1024快

**Comment by lsCoding666** [comment]
改之前上传的速度情况 同一文件 时间差不多是改之后的2倍
![image](https://user-images.githubusercontent.com/73888354/153319946-60eb2dca-9b58-4fab-aae2-82df4f7d2540.png)

**Comment by HFO4** [comment]
> 改之前上传的速度情况 同一文件 时间差不多是改之后的2倍
> 
> ![image](https://user-images.githubusercontent.com/73888354/153319946-60eb2dca-9b58-4fab-aae2-82df4f7d2540.png)
> 
> 

感谢测试，下个版本会优化这一参数。

**Comment by lsCoding666** [comment]
50m一片
![image](https://user-images.githubusercontent.com/73888354/153321713-7bd881f4-b1bd-4a65-8f1a-8b05e83243c9.png)
200m一片 时间上比100m一片的还快 就是知道文件会不会损坏
![image](https://user-images.githubusercontent.com/73888354/153322657-0b69aed2-098c-43f3-b2ca-b9d6601b2543.png)
上传到onedrive后取回 文件大小看起来正常
![image](https://user-images.githubusercontent.com/73888354/153322995-e7133e3b-d659-4db2-ac8e-2ae907824acd.png)
取回本地后文件播放正常 在线也正常
试试不分片（1000m一片 大于文件大小 相当于不分片）
woc上传速度贼快 
![image](https://user-images.githubusercontent.com/73888354/153323736-2d9569d9-8579-4c03-8f2c-05d0dc02a618.png)
结论 没必要分片

**Comment by lsCoding666** [comment]
但是不分片有概率失败 因为服务器负载太重了
![image](https://user-images.githubusercontent.com/73888354/153324028-e1acb5d6-387a-430c-914e-dd65a145b250.png)

**Comment by lsCoding666** [comment]
https://github.com/cloudreve/Cloudreve/blob/c84d0114ae53f67800cca8b702254b9f6e69b604/pkg/filesystem/driver/onedrive/api.go#L300-L302
上传代码写的是 先取出文件前10m的数据，在内存开辟10m空间，然后把这10m放到内存开辟的空间里，然后上传，成功后再把下一个10m放到内存里，然后上传...直到整个文件上传完毕为止。
有没有什么办法避免把文件写入内存这种耗时又占资源的操作？
比如说 先用linux spllit命令将文件分割，然后再统一上传，这样会快很多。
我测试了下 分割一个441m的文件在我的垃圾服务器（1h1g io55m/s）的服务器上也只需要不到5s
然后再统一上传 应该会快很多，不用把文件写入内存

**Comment by HFO4** [comment]
写入内存是为了能在分片上传失败时重新上传当前分片。

**Comment by lsCoding666** [comment]
> 写入内存是为了能在分片上传失败时重新上传当前分片。

但是如果分割成子文件的话 如果失败了 重新传那一片的文件不就行了
![image](https://user-images.githubusercontent.com/73888354/153785046-3fece39e-b07d-482a-a606-3dc560a85503.png)

**Comment by HFO4** [comment]
> > 写入内存是为了能在分片上传失败时重新上传当前分片。
> 
> 
> 
> 但是如果分割成子文件的话 如果失败了 重新传那一片的文件不就行了
> 
> ![image](https://user-images.githubusercontent.com/73888354/153785046-3fece39e-b07d-482a-a606-3dc560a85503.png)
> 
> 

因为传入 OneDrive Client 这块代码的文件流是 Reader+Closer，没法直接操作对应的文件。目前正在计划重构这部分代码，可通过seek来重试分片，这样转存到OneDrive的文件完全不需要写入内存中了。

**Comment by lsCoding666** [comment]
主要是split命令不占用内存，在分割过程中我发现服务器内存占用率没有变化。其实这个分割操作如果能不均分的话就更好了，这样或许能不用占用过多的磁盘空间

**Comment by lsCoding666** [comment]
> > > 写入内存是为了能在分片上传失败时重新上传当前分片。
> > 
> > 
> > 但是如果分割成子文件的话 如果失败了 重新传那一片的文件不就行了
> > ![image](https://user-images.githubusercontent.com/73888354/153785046-3fece39e-b07d-482a-a606-3dc560a85503.png)
> 
> 因为传入 OneDrive Client 这块代码的文件流是 Reader+Closer，没法直接操作对应的文件。目前正在计划重构这部分代码，可通过seek来重试分片，这样转存到OneDrive的文件完全不需要写入内存中了。

好的 谢谢了

**Comment by HFO4** [comment]
分片上传及重试策略已经在新版本中优化。

**Comment by xjc19960724** [comment]
> 分片上传及重试策略已经在新版本中优化。

能优化下onedrive的离线下载嘛？设置的分片错误重试9999好像一点用都没有，上传大一点的文件就经常上传失败，能不能分片上传失败后等待几分钟再重试上传呢
