### ISSUE TITLE
更新V3.3.2后，个人主页分享展示列表的时间出现了格式问题

### ISSUE THREAD

**Issue by LegendRW** [cloudreve/Cloudreve#949]
![20210721163648](https://user-images.githubusercontent.com/19301575/126459467-0239dc04-5998-430a-88c6-7a9def23b0e5.png)
RT

**Comment by topjohncian** [comment]
@HFO4 这里漏了一行
https://github.com/cloudreve/frontend/blob/master/src/component/Setting/Profile.js#L374
