### ISSUE TITLE
Cloudreve 删除文件后，磁盘文件还是存在！

### ISSUE THREAD

**Issue by ycllwl** [cloudreve/Cloudreve#952]
希望能增加回收站功能，回收站文件的保留时间！增加设置永久删除选项

**Comment by nillin** [comment]
提出了心声

**Comment by AndoKaguya** [comment]
附议
本地存储策略，我也是遇到这个问题，其他策略没试过。
cloudreve上删除文件，本地依旧存在
![image](https://user-images.githubusercontent.com/53990829/135450629-cb061ae5-092b-4d6d-8635-53fd2f05835c.png)
![image](https://user-images.githubusercontent.com/53990829/135450716-47aa847e-24ba-4fa5-97d6-03796cd756da.png)

**Comment by yayashanzei** [comment]
附议：使用s3存储策略，删不掉，点击删除后一直转圈圈

**Comment by anzhiyu-c** [comment]
附议
