### ISSUE TITLE
七牛云华东-浙江2存储区域暂无法上传超4m文件

### ISSUE THREAD

**Issue by gangongkong** [cloudreve/Cloudreve#954]

**Comment by ertuil** [comment]
发现同样的问题，CORS检测的 OPTIONS 会返回501错误。经查，原因大致是七牛云华东-浙江2区域不支持分块上传1.0的API，而是2.0的API： [https://developer.qiniu.com/kodo/1671/region-endpoint-fq](https://developer.qiniu.com/kodo/1671/region-endpoint-fq)。
