### ISSUE TITLE
宝塔部署进程启动失败

### ISSUE THREAD

**Issue by aomsir** [cloudreve/Cloudreve#958]
不知道问题出在哪儿，宝塔部署的时候守护进程无法启动，官网的下载也无法打开

**Comment by wsndshx** [comment]
我掐指一算, 这边建议你买捐赠版.

**Comment by aomsir** [comment]
> 我掐指一算, 这边建议你买捐赠版.

 我也觉得哈哈哈，没用守护进程，直接./cloudreve，然后反代一下就好了，不过对接云存储有点问题，老是路径为空，也不知道是不是因为cdn+ssl上出问题了
