### ISSUE TITLE
WebDav 无法使用，日志报401

### ISSUE THREAD

**Issue by sys1em** [cloudreve/Cloudreve#963]
1.环境/服务
宝塔面板7.6.0
Nginx 1.20.1（最开始使用1.21版本，发现401，后降为1.20.1也是一样结果)
MySQL 5.7.34
Redis 6.2.4
阿里云全站加速
以及给全站加速配置了SSl

2.日志：
  ___ _                 _                    
  / __\ | ___  _   _  __| |_ __ _____   _____ 
 / /  | |/ _ \| | | |/ _ | '__/ _ \ \ / / _ \	
/ /___| | (_) | |_| | (_| | | |  __/\ V /  __/
\____/|_|\___/ \__,_|\__,_|_|  \___| \_/ \___|

   V3.3.1  Commit #21b1b53  Pro=true
================================================

[Info]    2021-07-31 23:23:20 初始化数据库连接
[Info]    2021-07-31 23:23:20 数据库版本匹配，跳过数据库迁移
[Info]    2021-07-31 23:23:20 初始化任务队列，WorkerNum = 10
[Info]    2021-07-31 23:23:20 初始化定时任务...
[Info]    2021-07-31 23:23:20 检测到 statics 目录存在，将使用此目录下的静态资源文件
[Info]    2021-07-31 23:23:20 当前运行模式：Master
[Info]    2021-07-31 23:23:20 已连接到 Redis 服务器：127.0.0.1:XXX
[Info]    2021-07-31 23:23:20 开始监听 :5212
[Info]    2021-07-31 23:23:20 开始监听 :5213
[GIN] 2021/07/31 - 23:09:33 | 401 |      65.979µs |  222.240.xx.xx | PROPFIND  "/dav/"
[GIN] 2021/07/31 - 23:09:58 | 401 |      22.676µs |  222.240.xx.xx | PROPFIND  "/dav/"
[GIN] 2021/07/31 - 23:10:09 | 401 |      37.183µs |  222.240.xx.xx | PROPFIND  "/dav/"
[GIN] 2021/07/31 - 23:10:34 | 401 |      28.362µs |  222.240.xx.xx | PROPFIND  "/dav/"

3.使用账户：
系统初始化时自动创建的（将初始化邮箱改为自己的），创建了多个WebDav密码，都是提示401

4.测试连接的系统：
手机上使用三个app都是401，win客户端也是401

谷歌浏览器直接访问会提示【页面不存在】而不是登录账号密码界面

5.排除原因：
不是密码错误，我无论从网页上复制还是从数据库里直接复制都是一样的问题
复制密码的界面截图↓，我是在这个界面复制的密码，所以不可能搞错WebDav密码！！！
http://www.wuhuwuhu.com/20210731234841.png
![密码界面截图](http://www.wuhuwuhu.com/20210731234841.png)

**Comment by sys1em** [comment]
问题已解决，是CDN把Authorization头给过滤掉了导致鉴权失败

**Comment by iJayscn** [comment]
> 问题已解决，是CDN把Authorization头给过滤掉了导致鉴权失败

请问如何解决呢？
