### ISSUE TITLE
离线下载点击选择要下载的文件没反应，下载完成后不能结束

### ISSUE THREAD

**Issue by dfmjndm** [cloudreve/Cloudreve#965]
![image](https://user-images.githubusercontent.com/57401901/127802697-7932ebfa-b7e6-4211-8bcd-03c67d8d5f99.png)
一直卡在进行中没办法结束，我去后台看了一下文件早就已经下载好了。

然后点击选择要下载的文件也没有反应

**Comment by dfmjndm** [comment]
![image](https://user-images.githubusercontent.com/57401901/127803007-acf1448c-0f11-4344-a702-629159db0d7a.png)

**Comment by dfmjndm** [comment]
![image](https://user-images.githubusercontent.com/57401901/127803040-724a5ae2-96a3-460a-9cd2-e137d8be7969.png)

**Comment by q601904795** [comment]
aria2没有设置做种时间吧?  这应该是下载好后还在等待做种,需要做种到一定条件后才算任务完成
