### ISSUE TITLE
Aria2任务更新时间间隔

### ISSUE THREAD

**Issue by LFMcxixif** [cloudreve/Cloudreve#967]
后台设置为10s更新，而前端默认还是60s更新

![QQ截图20210803005823](https://user-images.githubusercontent.com/69949204/127897687-92373d41-a239-400e-8749-db09ca861740.png)
![QQ截图20210803005834](https://user-images.githubusercontent.com/69949204/127897692-be6eaf39-f757-43a0-923f-451b023293d6.png)

**Comment by xvzhenduo** [comment]
后台改完设置点保存了吗？

**Comment by LFMcxixif** [comment]
> 后台改完设置点保存了吗？

肯定的啦，但是他前端就是这样，比如
60->50 然后刷新 又继续重复

**Comment by xvzhenduo** [comment]
这个我就不知道了，但是我的没有问题~
