### ISSUE TITLE
离线下载完成,在持续上传文件到OneDrive一段时间后,上传出错,接着后续文件上传全部失败.

### ISSUE THREAD

**Issue by q601904795** [cloudreve/Cloudreve#969]
版本:3.3.2
报错提示如下:
文件转存失败：Put https://microsoftgraph.chinacloudapi.cn/v1.0/sites/xxx.sharepoint.cn,7e9c45f4-741a-4e8b-960c-865a63f807ac,37af86cc-1481-4b38-a185-0ad9a57d2b69/drive/root:/uploads/2021/08/03/0p7mru94_%E9%B2%8D%E9%B1%BC%E7%9B%B4%E6%92%AD%E7%9B%92%E5%AD%90%EF%BC%8C%E5%85%8D%E8%B4%B9%E6%8E%A2%E8%8A%B1%E7%9B%B4%E6%92%AD%E5%92%8C%E9%AB%98%E6%B8%85%E8%A7%86%E9%A2%91.html:/content?@microsoft.graph.conflictBehavior=fail: read /root/aria/aria2/1627870207716317245/xxx/xxx.html: file already closed

**Comment by q601904795** [comment]
搜索了一圈源码,源码内没有包含这个错误信息

**Comment by Zynismus16** [comment]
我也遇到了，同样的错误信息，一般出现在下载的内容是文件夹且里面有很多文件时，在线解压压缩包时还会出现缺失文件的情况，虽然没有错误信息，但我估计也是这个问题

**Comment by Zynismus16** [comment]
@HFO4

**Comment by wangxiaoerYah** [comment]
@q601904795 @Zynismus16 

这个问题应该是这个问题 #716

**Comment by wangxiaoerYah** [comment]
需要升级到最新版本，然后修改数据库。如果闲麻烦，可以直接删除表，重装下。如果解决了问题，请关闭issue。

@HFO4 捐赠版的验证老是自动跳转到cloudreve.org好烦啊，我在论坛里面问了问题。https://forum.cloudreve.org/d/1842，好难啊。

**Comment by q601904795** [comment]
> 需要升级到最新版本，然后修改数据库。如果闲麻烦，可以直接删除表，重装下。如果解决了问题，请关闭issue。

我的版本已经在issue中提到,是最新版3.3.2.  目前并没有跟高的版本号.

而我提到的错误信息是file already closed
而不是#716中提到的data to long for column porps at row 1

**Comment by wangxiaoerYah** [comment]
> > 需要升级到最新版本，然后修改数据库。如果闲麻烦，可以直接删除表，重装下。如果解决了问题，请关闭issue。
> 
> 我的版本已经在issue中提到,是最新版3.3.2.  目前并没有跟高的版本号.
> 
> 而我提到的错误信息是file already closed
> 而不是#716中提到的data to long for column porps at row 1

 看看aria2下载的文件权限，如果是root权限或是不是cloudreve用户的权限，就会读取失败。

**Comment by Zynismus16** [comment]
> > > 需要升级到最新版本，然后修改数据库。如果闲麻烦，可以直接删除表，重装下。如果解决了问题，请关闭issue。
> > 
> > 
> > 我的版本已经在issue中提到,是最新版3.3.2.  目前并没有跟高的版本号.
> > 而我提到的错误信息是file already closed
> > 而不是#716中提到的data to long for column porps at row 1
> 
> 看看aria2下载的文件权限，如果是root权限或是不是cloudreve用户的权限，就会读取失败。

我的aria2是root权限运行，cloudreve也是root权限运行的。
另外可能是我没找到问题所在或者这是一个概率性问题，又或者是路径太长或包含特殊字符。
（我在下载文件时有遇到日文提示文件名非法的情况)
我这边一般出现在文件比较多的情况下，诸如800个文件及以上，极容易出现这个问题

**Comment by Zynismus16** [comment]
另外，文件转存失败后，我删除相应文件及任务，再次重新下载，发现报错的文件还是同样的

**Comment by wangxiaoerYah** [comment]
@q601904795 仔细看了下，报错里面有个字段 '''microsoft.graph.conflictBehavior=fail''' 
这个问题在onedrive的issue下有提出。https://github.com/OneDrive/onedrive-api-docs/issues/1148  

这个应该是微软的api有问题。

参考: https://techcommunity.microsoft.com/t5/microsoft-graph/cannot-get-conflict-behaviour-to-work-with-upload-to-sharepoint/td-p/1995331

**Comment by wangxiaoerYah** [comment]
你试试存到对象储存或者本地试试，如果不报错那就是onedrive的问题。

**Comment by q601904795** [comment]
关闭.
原因找到了,因为SharePoint容量不够,上传过程中容量不够时文件先被close了.
然后程序在另外一个地方close该文件,因为文件已经被close,所以报错file already closed

**Comment by Zynismus16** [comment]
我这边只针对部分文件，举个例子，我离线下载文件夹，部分内容保存，但我单独上传却没有问题。另外，我再上传其他比失败更大的文件也没有问题，我估计确实是微软api问题，只能说是个硬伤了
