### ISSUE TITLE
OneDrive上删除文件,网站的目录不会更新

### ISSUE THREAD

**Issue by solitudealma** [cloudreve/Cloudreve#971]
从OneDrive上删除文件时,发现网站上的目录并没有更新,文件还在,但是打开什么都没(图片),然后看了一下数据库发现是数据没有删除,导致目录下的文件还在.

**Comment by Beattheend** [comment]
> 从OneDrive上删除文件时,发现网站上的目录并没有更新,文件还在,但是打开什么都没(图片),然后看了一下数据库发现是数据没有删除,导致目录下的文件还在.

OneDrive上删除文件并不能管控Cloudreve的数据库它们不是“相互联动的”，除非你在Cloudreve上删除文件。
