### ISSUE TITLE
大文件上传卡在1%

### ISSUE THREAD

**Issue by lovelycatv** [cloudreve/Cloudreve#974]
超过100M无法上传，已改nginx php上传限制
小文件可正常使用

**Comment by hatsuyuki280** [comment]
@lovelycatv 也许你还可以检查下你有没有使用某种形式的CDN？

部分CDN提供商会限制请求大小
作为例子：cloudflare免费计划的单个请求的大小上限就是100M

作为解决方案：
* 不套用这类服务，让用户直连
* 想办法让程序支持上传分片

**Comment by HFO4** [comment]
3.5.0后已支持分片上传
