### ISSUE TITLE
”钩子执行失败：容量空间不足“，上传文件卡住直接关掉退出登录，就出现问题了

### ISSUE THREAD

**Issue by LanSilence** [cloudreve/Cloudreve#977]
[GIN] 2021/08/11 - 18:14:24 | 200 |   49.562904ms |       127.0.0.1 | GET      /api/v3/admin/summary
[GIN] 2021/08/11 - 18:14:25 | 200 |  483.782967ms |       127.0.0.1 | GET      /api/v3/admin/news
[GIN] 2021/08/11 - 18:14:29 | 200 |    5.237671ms |       127.0.0.1 | POST     /api/v3/admin/setting
[GIN] 2021/08/11 - 18:35:47 | 404 |   11.476276ms |       127.0.0.1 | GET      /api/v3/user/avatar/kRfO/l
[GIN] 2021/08/11 - 18:35:49 | 200 |    5.385538ms |       127.0.0.1 | DELETE   /api/v3/user/session
[GIN] 2021/08/11 - 18:35:49 | 200 |    3.603288ms |       127.0.0.1 | GET      /admin/aria2
[GIN] 2021/08/11 - 18:35:49 | 200 |    1.586847ms |       127.0.0.1 | GET      /api/v3/user/avatar/0/s
[GIN] 2021/08/11 - 18:35:49 | 200 |    1.374528ms |       127.0.0.1 | GET      /api/v3/user/avatar/0/l
[GIN] 2021/08/11 - 18:35:49 | 200 |    4.498934ms |       127.0.0.1 | GET      /api/v3/site/config
[GIN] 2021/08/11 - 18:35:49 | 200 |     1.73442ms |       127.0.0.1 | GET      /api/v3/user/avatar/0/s
[GIN] 2021/08/11 - 18:35:49 | 200 |    1.062759ms |       127.0.0.1 | POST     /api/v3/admin/setting
[GIN] 2021/08/11 - 18:35:49 | 200 |    3.918849ms |       127.0.0.1 | GET      /login
[GIN] 2021/08/11 - 18:35:49 | 200 |   15.686188ms |       127.0.0.1 | GET      /static/img/favicon.ico
[GIN] 2021/08/11 - 18:35:49 | 200 |    4.572137ms |       127.0.0.1 | GET      /api/v3/site/config
[GIN] 2021/08/11 - 18:35:49 | 200 |    15.54649ms |       127.0.0.1 | GET      /static/img/favicon.ico
[GIN] 2021/08/11 - 18:35:52 | 200 |    6.869142ms |       127.0.0.1 | POST     /api/v3/user/session
[GIN] 2021/08/11 - 18:35:52 | 404 |    8.332331ms |       127.0.0.1 | GET      /api/v3/user/avatar/lOh2/s
[GIN] 2021/08/11 - 18:35:52 | 200 |    4.644465ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:35:52 | 200 |    8.078307ms |       127.0.0.1 | GET      /api/v3/directory/
[GIN] 2021/08/11 - 18:35:52 | 200 |    4.586136ms |       127.0.0.1 | GET      /api/v3/user/storage
[Warning] 2021-08-11 18:36:03 钩子执行失败：容量空间不足
[Warning] 2021-08-11 18:36:24 钩子执行失败：容量空间不足
[Warning] 2021-08-11 18:36:51 钩子执行失败：容量空间不足
[GIN] 2021/08/11 - 18:36:52 | 200 |  1.303021714s |       127.0.0.1 | POST     /api/v3/file/upload
[Warning] 2021-08-11 18:36:52 钩子执行失败：容量空间不足
[GIN] 2021/08/11 - 18:36:52 | 200 |    5.293086ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:36:52 | 200 |   11.741092ms |       127.0.0.1 | GET      /api/v3/directory/
[GIN] 2021/08/11 - 18:36:53 | 200 |    4.518766ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:36:54 | 200 |  1.264210026s |       127.0.0.1 | POST     /api/v3/file/upload
[GIN] 2021/08/11 - 18:36:54 | 200 | 29.283591842s |       127.0.0.1 | POST     /api/v3/file/upload
[GIN] 2021/08/11 - 18:37:00 | 200 | 57.157970828s |       127.0.0.1 | POST     /api/v3/file/upload
[GIN] 2021/08/11 - 18:37:03 | 404 |    8.607353ms |       127.0.0.1 | GET      /api/v3/user/avatar/lOh2/l
[GIN] 2021/08/11 - 18:37:04 | 200 |    5.213176ms |       127.0.0.1 | DELETE   /api/v3/user/session
[GIN] 2021/08/11 - 18:37:04 | 200 |     2.98704ms |       127.0.0.1 | GET      /home?path=%2F
[GIN] 2021/08/11 - 18:37:04 | 200 |    1.035927ms |       127.0.0.1 | GET      /api/v3/user/avatar/0/s
[GIN] 2021/08/11 - 18:37:04 | 200 |     1.03272ms |       127.0.0.1 | GET      /api/v3/user/avatar/0/l
[GIN] 2021/08/11 - 18:37:05 | 200 |     854.232µs |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:37:05 | 200 |     1.25437ms |       127.0.0.1 | GET      /api/v3/user/avatar/0/s
[GIN] 2021/08/11 - 18:37:05 | 200 |    5.118682ms |       127.0.0.1 | GET      /api/v3/site/config
[GIN] 2021/08/11 - 18:37:05 | 200 |    1.111755ms |       127.0.0.1 | GET      /api/v3/directory/
[GIN] 2021/08/11 - 18:37:05 | 200 |     842.858µs |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:37:05 | 200 |    2.988206ms |       127.0.0.1 | GET      /login
[GIN] 2021/08/11 - 18:37:05 | 200 |    3.100199ms |       127.0.0.1 | GET      /login
[GIN] 2021/08/11 - 18:37:05 | 200 |    3.016788ms |       127.0.0.1 | GET      /login
[GIN] 2021/08/11 - 18:37:05 | 200 |    4.339695ms |       127.0.0.1 | GET      /api/v3/site/config
[GIN] 2021/08/11 - 18:37:08 | 200 |    7.310403ms |       127.0.0.1 | POST     /api/v3/user/session
[GIN] 2021/08/11 - 18:37:08 | 200 |     4.52314ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:37:08 | 404 |   11.942328ms |       127.0.0.1 | GET      /api/v3/user/avatar/lOh2/s
[GIN] 2021/08/11 - 18:37:08 | 200 |    8.081807ms |       127.0.0.1 | GET      /api/v3/directory/
[GIN] 2021/08/11 - 18:37:08 | 200 |    4.571554ms |       127.0.0.1 | GET      /api/v3/user/storage
[Warning] 2021-08-11 18:37:25 钩子执行失败：容量空间不足
[GIN] 2021/08/11 - 18:37:27 | 200 |  1.293383992s |       127.0.0.1 | POST     /api/v3/file/upload
[Warning] 2021-08-11 18:37:27 钩子执行失败：容量空间不足
[GIN] 2021/08/11 - 18:37:27 | 200 |    4.596927ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:37:27 | 200 |   11.079638ms |       127.0.0.1 | GET      /api/v3/directory/
[GIN] 2021/08/11 - 18:37:27 | 200 |    4.727584ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:37:28 | 200 |  1.189820727s |       127.0.0.1 | POST     /api/v3/file/upload
[Warning] 2021-08-11 18:40:13 钩子执行失败：容量空间不足
[GIN] 2021/08/11 - 18:40:14 | 200 |  1.152430298s |       127.0.0.1 | POST     /api/v3/file/upload
[Warning] 2021-08-11 18:40:14 钩子执行失败：容量空间不足
[GIN] 2021/08/11 - 18:40:14 | 200 |    5.211135ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:40:14 | 200 |   12.721315ms |       127.0.0.1 | GET      /api/v3/directory/
[GIN] 2021/08/11 - 18:40:14 | 200 |    5.592024ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:40:15 | 200 |  870.092579ms |       127.0.0.1 | POST     /api/v3/file/upload
[Warning] 2021-08-11 18:40:34 钩子执行失败：容量空间不足
[GIN] 2021/08/11 - 18:40:34 | 200 |  332.874466ms |       127.0.0.1 | POST     /api/v3/file/upload
[Warning] 2021-08-11 18:40:34 钩子执行失败：容量空间不足
[GIN] 2021/08/11 - 18:40:34 | 200 |    4.771623ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:40:34 | 200 |    8.768051ms |       127.0.0.1 | GET      /api/v3/directory/
[GIN] 2021/08/11 - 18:40:34 | 200 |  100.081891ms |       127.0.0.1 | POST     /api/v3/file/upload
[GIN] 2021/08/11 - 18:40:34 | 200 |    4.485518ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:40:42 | 200 |    6.308599ms |       127.0.0.1 | GET      /api/v3/file/search/video/internal
[GIN] 2021/08/11 - 18:40:43 | 200 |    6.333681ms |       127.0.0.1 | GET      /api/v3/file/search/image/internal
[GIN] 2021/08/11 - 18:40:43 | 200 |    6.237729ms |       127.0.0.1 | GET      /api/v3/file/search/audio/internal
[GIN] 2021/08/11 - 18:40:44 | 200 |    6.369845ms |       127.0.0.1 | GET      /api/v3/file/search/doc/internal
[GIN] 2021/08/11 - 18:40:58 | 404 |   11.866792ms |       127.0.0.1 | GET      /api/v3/user/avatar/lOh2/l
[GIN] 2021/08/11 - 18:40:59 | 200 |    5.235049ms |       127.0.0.1 | DELETE   /api/v3/user/session
[GIN] 2021/08/11 - 18:40:59 | 200 |    3.681742ms |       127.0.0.1 | GET      /home?path=%2F
[GIN] 2021/08/11 - 18:40:59 | 200 |     939.976µs |       127.0.0.1 | GET      /api/v3/user/avatar/0/s
[GIN] 2021/08/11 - 18:40:59 | 200 |     922.768µs |       127.0.0.1 | GET      /api/v3/user/avatar/0/l
[GIN] 2021/08/11 - 18:41:00 | 200 |     971.182µs |       127.0.0.1 | GET      /api/v3/user/avatar/0/s
[GIN] 2021/08/11 - 18:41:00 | 200 |    1.429358ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:41:00 | 200 |     996.264µs |       127.0.0.1 | GET      /api/v3/directory/
[GIN] 2021/08/11 - 18:41:00 | 200 |    4.876907ms |       127.0.0.1 | GET      /api/v3/site/config
[GIN] 2021/08/11 - 18:41:00 | 200 |   15.186893ms |       127.0.0.1 | GET      /static/img/favicon.ico
[GIN] 2021/08/11 - 18:41:00 | 200 |     813.109µs |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:41:00 | 200 |    3.863146ms |       127.0.0.1 | GET      /login
[GIN] 2021/08/11 - 18:41:00 | 200 |    3.269937ms |       127.0.0.1 | GET      /login
[GIN] 2021/08/11 - 18:41:00 | 200 |    3.695741ms |       127.0.0.1 | GET      /login
[GIN] 2021/08/11 - 18:41:00 | 200 |    4.382859ms |       127.0.0.1 | GET      /api/v3/site/config
[GIN] 2021/08/11 - 18:41:03 | 200 |    6.958678ms |       127.0.0.1 | POST     /api/v3/user/session
[GIN] 2021/08/11 - 18:41:03 | 200 |    8.799257ms |       127.0.0.1 | GET      /api/v3/directory/
[GIN] 2021/08/11 - 18:41:03 | 200 |    9.781522ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:41:03 | 404 |   14.076012ms |       127.0.0.1 | GET      /api/v3/user/avatar/kRfO/s
[GIN] 2021/08/11 - 18:41:03 | 200 |    4.503892ms |       127.0.0.1 | GET      /api/v3/user/storage
[GIN] 2021/08/11 - 18:41:09 | 404 |    8.297626ms |       127.0.0.1 | GET      /api/v3/user/avatar/kRfO/l
[GIN] 2021/08/11 - 18:41:10 | 404 |    8.485737ms |       127.0.0.1 | GET      /api/v3/user/avatar/kRfO/s
[GIN] 2021/08/11 - 18:41:10 | 200 |   49.792171ms |       127.0.0.1 | GET      /api/v3/admin/summary
[GIN] 2021/08/11 - 18:41:11 | 200 |   10.386396ms |       127.0.0.1 | POST     /api/v3/admin/policy/list
[GIN] 2021/08/11 - 18:41:11 | 200 |   10.508013ms |       127.0.0.1 | POST     /api/v3/admin/file/list

**Comment by HFO4** [comment]
3.5.0后已修复
