### ISSUE TITLE
Cloudreve如何加新的本地硬盘

### ISSUE THREAD

**Issue by 654we** [cloudreve/Cloudreve#978]
原来服务器是用的256G的一个硬盘当备份，后面满啦，又买了个2TB的硬盘，但是不知道如何挂载到Cloudreve。求大佬教一下！

**Comment by hatsuyuki280** [comment]
@654we 你可以先想办法把它挂载到你的服务器上，然后你大概就知道怎么把它挂载在Cloudreve里了

**Comment by 654we** [comment]
> 已经挂载到服务器上去了，但是原本那个硬盘是挂载在home这个目录里面，Cloudreve程序也在这个目录里面，我想到是如何把新硬盘挂载在home目录里面的一个分目录，但是不知道如何操作也不知道能不能这样做，不是很懂，我小白！对Linux命令啥的都不是很懂。非常感谢您的指点！

**Comment by 654we** [comment]
@hatsuyuki280 已经载到服务器上去了，这个原来的目录是挂载在家里的目录目录里面，Cloudreve程序目录这个目录里面，我想是如何把新的目录挂载在家里目录里面的一个分，但是不知道怎么操作也不知道能不能破坏，不是很懂，我小白！对Linux命令啥的都不是很懂。非常感谢你的指点！

**Comment by hatsuyuki280** [comment]
@654we 如果你已经完成了在系统上的挂载，你可以直接：
1. 用浏览器访问你的cloudreve
1. 打开控制面板
1. 选择存储策略
1. 添加存储策略
1. 本地

然后按照向导输入路径就可以

**Comment by 654we** [comment]
@hatsuyuki280 好的，非常感谢！

**Comment by lcpbule** [comment]
可以使用磁盘融合，添加存储策略只能某个账户可以使用。
