### ISSUE TITLE
one drive文件大于10M以后出现文件信息不一致

### ISSUE THREAD

**Issue by mgz0227** [cloudreve/Cloudreve#980]
挂载了3个onedrive，其中一个大于10M以后就出现文件信息不一致，并且挂载新的onedrive也是一样的情况。

**Comment by hofaeair** [comment]
相同问题

**Comment by hofaeair** [comment]
我在OneDrive的垃圾桶里找了一下，发现117mb的文件，在垃圾桶里显示的是115mb，确实不一致。

**Comment by hofaeair** [comment]
406mb的，垃圾桶里是397mb。好像是上传丢失。

**Comment by hofaeair** [comment]
旧的没事，新挂载的都这样

**Comment by hofaeair** [comment]
https://forum.cloudreve.org/d/1854

**Comment by hofaeair** [comment]
@HFO4
购买捐助版就可以解决问题吗？

**Comment by hofaeair** [comment]
如果作者不回复，真的很绝望啊。

**Comment by Jieoz** [comment]
我这里也是相同问题，有一个测试文件，是一个29MB的pptx文件，实测将pptx改为其他非pptx后缀则正常
https://wwi.lanzoui.com/iEM7ytskv0d
