### ISSUE TITLE
无法播放视频

### ISSUE THREAD

**Issue by wrnxr233** [cloudreve/Cloudreve#981]
**Describe the bug**

**To Reproduce**
播放视频显示如图所示，大小为718M,手机测试一样，随便录个屏后上传有声音无画面
采用的是最新版的cloudreve

**Expected behavior**

**Screenshots**
![QQ截图20210816184450](https://user-images.githubusercontent.com/53810658/129551942-a641a2fc-ee47-4379-845e-8de005671921.png)

**Desktop (please complete the following information):**
 - OS: [Windows11,22000.132]
 - Browser [edge]
 - Version [92.0.902.73]

**Smartphone (please complete the following information):**
 - Device: [iPhone6s]
 - OS: [iOS15beta5]
 - Browser [safari]
 - Version [unknow]

**Additional context**

**Comment by spellbook96** [comment]
我也是同样的问题，测试用pc chrome浏览器正常播放。其他浏览器Firefox，Safari均不能正常播放
