### ISSUE TITLE
播放视频有声音，没有画面，视频格式为mkv，播放过程不卡顿

### ISSUE THREAD

**Issue by hongyonghan** [cloudreve/Cloudreve#982]
播放视频有声音，没有画面，视频格式为mkv，播放过程不卡顿。
浏览器为chrome浏览器。部署的系统为centos7.
![image](https://user-images.githubusercontent.com/53131561/129906999-e085268b-112b-49c7-a7e8-494f79dc3229.png)

**Comment by MagmaBlock** [comment]
cloudreve 内置的是 Dplayer
在一些浏览器里可能对mkv兼容不太好
而且有些mkv内封的字幕还无法识别😭
我目前的方法是获取直链后用本地播放器播

**Comment by HFO4** [comment]
只支持浏览器能够原生解码的视频播放。

**Comment by jacksunhack** [comment]
这个问题貌似还没解决

**Comment by Oliyrs** [comment]
我也是，edge播放只有声音没有画面，但chorme播放没问题。求解决
