### ISSUE TITLE
OneDrive 导入文件后文件大小有概率为0

### ISSUE THREAD

**Issue by MagmaBlock** [cloudreve/Cloudreve#983]
**故障简介**
从OneDrive世纪互联版 使用管理后台的【从外部导入】，导入的文件有概率会为大小“0 B”
文件能够正常使用和下载，但是就是大小无法刷新
**重点是 这种0 B大小的文件无法让一些WebDav客户端理解**
**重点是 这种0 B大小的文件无法让一些WebDav客户端理解**

**复现步骤**
使用管理后台的【从外部导入】，导入OneDrive世纪互联版已有的文件
导入成功，但是文件有概率出现0 B大小的情况

**建议**
将 从外部导入 这个功能增加一个验证机制，导入时遇到数据异常的文件尝试重新导入
或者用别的办法刷新 数据库中已有文件 的大小等数据。

**截图**
![image](https://user-images.githubusercontent.com/61128045/130007343-234e1af8-12cb-4dfa-bed9-a17fbee92a65.png)
![image](https://user-images.githubusercontent.com/61128045/130007346-7ff16f7f-775b-46b8-ade0-5185e034238a.png)

**平台:**
服务器为Ubuntu 20.04.2 LTS，位于上海。
（之前使用美国的VPS此情况出现概率更大，应该是网络故障导致的）
存储策略为OneDrive 世纪互联版，不知道别的策略会不会有这种情况
使用数据库MySQL5.7，已经确定SQLite也会有此故障

**Comment by huiges** [comment]
我的也是有时候导入可能为0
