### ISSUE TITLE
Onedrive存储，外链无法打开，跳转域名错误

### ISSUE THREAD

**Issue by ljm12914** [cloudreve/Cloudreve#988]
使用onedrive国际商业版存储，获取外链显示`https://domain.com/api/v3/file/source/...`，打开后**跳转至相同域名而不是sharepoint域名**，进而导致外链404。

例如：
`https://domain.com/api/v3/file/source/6/demo.jpg?sign=i-am-a-sign` --> `https://domain.com/personal/my_onedrive_account/_layouts/15/download.aspx?......`由于没有合适的处理程序，这个直接404

而预期现象是直接跳转至sharepoint域名下载：
`https://domain.com/api/v3/file/source/6/demo.jpg?sign=i-am-a-sign` --> `https://thisisorgname-my.sharepoint.com/personal/my_onedrive_account/_layouts/15/download.aspx?......`

额外信息：
1.网盘内下载设置了反代服务器（域名为dl.domain.com）。
2.使用iis8.0反代（ARR），Windows Server 2012 R2。

可能的暂时解决方案：
设置条件反代，将符合`domain.com/api/v3/file/source`的单独重定向至sharepoint域名。但已经过一次跳转，目前尚未找到捕获方案。

版本3.3.2

**Comment by xb2016** [comment]
@ljm12914 ARR 设置不对，参考https://moedog.org/1281.html

**Comment by ljm12914** [comment]
已解决，谢谢
