### ISSUE TITLE
对接其他机器离线下载

### ISSUE THREAD

**Issue by GreenTeodoro839** [cloudreve/Cloudreve#989]
网盘搭建在低延迟的国内服务器上，但是带宽很低。能不能做一个从机客户端？国外大带宽机器做从机，通过密钥连接主服务器，调用从机的aria2下载然后上传。另外，这个方法应该也可以用来中转webdav，(解)压缩等

**Comment by cr-zhichen** [comment]
同样需要这样的功能来加快aria2下载
