### ISSUE TITLE
在进行邮件测试时，邮箱无法发送信息。提示邮件发送队列出现异常

### ISSUE THREAD

**Issue by ShiinaRinne** [cloudreve/Cloudreve#993]
在进行邮件测试时，使用的邮箱无法发送信息。
![image](https://user-images.githubusercontent.com/45081750/131322887-a112a5e6-9c59-48d6-84d8-8bc0e2b9b4d4.png)

![image](https://user-images.githubusercontent.com/45081750/131323028-2047dfeb-20af-4a90-9471-18184b9dde4b.png)
当使用foxmail发送时，可以正常发送

**Comment by cxplay** [comment]
那就不要用加密连接
