### ISSUE TITLE
分享链接，能否增加一个直接下载呢？

### ISSUE THREAD

**Issue by zhangzhanqiu** [cloudreve/Cloudreve#995]
分享链接，能否增加一个直接下载呢？目前下载总有一个提示：xx向你分享了一个文件…下载。我想链接直接就是下载怎么设置一下呢？谢谢

**Comment by sepmoecat** [comment]
请获取直链

**Comment by zhangzhanqiu** [comment]
> 
> 
> 请获取直链

怎样获取直链呢？直接点击下载，获取的链接带有sign签名，过期了链接就失效了。怎么获取不带签名的直链呢？

**Comment by sepmoecat** [comment]
> > 请获取直链
> 
> 怎样获取直链呢？直接点击下载，获取的链接带有sign签名，过期了链接就失效了。怎么获取不带签名的直链呢？

有个功能叫获取直链，右键文件。

**Comment by zhangzhanqiu** [comment]
> 
> 
> > > 请获取直链
> > 
> > 
> > 怎样获取直链呢？直接点击下载，获取的链接带有sign签名，过期了链接就失效了。怎么获取不带签名的直链呢？
> 
> 有个功能叫获取直链，右键文件。

我的右键没有那一项，我明白了，我的版本可能不是最新的，我重装一下试试，谢谢

**Comment by sepmoecat** [comment]
> > > > 请获取直链
> > > 
> > > 
> > > 怎样获取直链呢？直接点击下载，获取的链接带有sign签名，过期了链接就失效了。怎么获取不带签名的直链呢？
> > 
> > 
> > 有个功能叫获取直链，右键文件。
> 
> 我的右键没有那一项，我明白了，我的版本可能不是最新的，我重装一下试试，谢谢

![image](https://user-images.githubusercontent.com/60971296/131955624-ae29f7f6-f0e2-4308-bfa9-39ddd89a9618.png)

**Comment by zhangzhanqiu** [comment]
> 
> 
> > > > > 请获取直链
> > > > 
> > > > 
> > > > 怎样获取直链呢？直接点击下载，获取的链接带有sign签名，过期了链接就失效了。怎么获取不带签名的直链呢？
> > > 
> > > 
> > > 有个功能叫获取直链，右键文件。
> > 
> > 
> > 我的右键没有那一项，我明白了，我的版本可能不是最新的，我重装一下试试，谢谢
> 
> ![image](https://user-images.githubusercontent.com/60971296/131955624-ae29f7f6-f0e2-4308-bfa9-39ddd89a9618.png)

我安装的是最新版本3.3.2，和你的怎么不一样呢？我的没有获取外链那一项
![QQ截图20210903141033](https://user-images.githubusercontent.com/36806886/131959003-4c600187-e27b-4e93-9626-4476077426c9.jpg)

**Comment by hatsuyuki280** [comment]
@zhangzhanqiu 你现在使用的存储策略有没有启用允许直链…？
你现在使用的用户有没有允许直链的权限？

**Comment by hatsuyuki280** [comment]
@hatsuyuki280

**Comment by hatsuyuki280** [comment]
> @zhangzhanqiu 你现在使用的存储策略有没有启用允许直链…？
> 你现在使用的用户有没有允许直链的权限？

![Screenshot_20210903-152007](https://user-images.githubusercontent.com/34149082/131959797-36b4ff52-5ec1-4444-a9be-dc90d3681dc2.png)
存储策略的允许直链在这里

用户那边好像没有设置，咱记错了

**Comment by zhangzhanqiu** [comment]
> 
> 
> > @zhangzhanqiu 你现在使用的存储策略有没有启用允许直链…？
> > 你现在使用的用户有没有允许直链的权限？
> 
> ![Screenshot_20210903-152007](https://user-images.githubusercontent.com/34149082/131959797-36b4ff52-5ec1-4444-a9be-dc90d3681dc2.png)
> 存储策略的允许直链在这里
> 
> 用户那边好像没有设置，咱记错了

嗯，显示外链了。就是浏览器直接打开文件，不是下载文件。但这样我就够用了。谢谢

**Comment by Chandler-Lu** [comment]
> > > @zhangzhanqiu 你现在使用的存储策略有没有启用允许直链…？
> > > 你现在使用的用户有没有允许直链的权限？
> > 
> > 
> > ![Screenshot_20210903-152007](https://user-images.githubusercontent.com/34149082/131959797-36b4ff52-5ec1-4444-a9be-dc90d3681dc2.png)
> > 存储策略的允许直链在这里
> > 用户那边好像没有设置，咱记错了
> 
> 嗯，显示外链了。就是浏览器直接打开文件，不是下载文件。但这样我就够用了。谢谢

加响应头
`Content-Disposition: attachment`

**Comment by ppfirework** [comment]
为什么我还是不行
已经允许获取直链了
![](https://img.pprocket.cn/20211003131722.png)
