### ISSUE TITLE
请问，能否在一个存储策略中使用多个目录呢？

### ISSUE THREAD

**Issue by gaohychina** [cloudreve/Cloudreve#996]
请问，能否在一个存储策略中使用多个目录呢？这样通过一个存储策略可以向多个磁盘中写文件了，能够避免单一磁盘容量过小的问题。

**Comment by danblaze13** [comment]
@gaohychina 这个问题不需要cloudreve处理,本地用MergerFS把多硬盘合并单目录

**Comment by hatsuyuki280** [comment]
@gaohychina 现在的状态可能还比较困难，不过linux的话记得有一个命令可以创建一个多个目录合并起来的大目录，往里面写入也会平摊到两个目录里，也许你可以试试看那个quq

**Comment by hanqingwu** [comment]
mdadm  软件RAID
