### ISSUE TITLE
希望支持对接更多云存储

### ISSUE THREAD

**Issue by GreenTeodoro839** [cloudreve/Cloudreve#999]
参考github开源的sharelist，可以对接百度网盘，天翼云，和彩云，阿里云之类的。百度云应该不难，和od一样可以自建api，官方有文档

**Comment by cxplay** [comment]
任何非官方承认的 API 或接口都不能用于生产环境, 这些接口无法保持稳定性和可用性添加支持只会无限增加对接口的维护成本.

Sharelist 这类目录程序基本无需考虑数据库主动不主动的, 只要定时从接口拉取文件列表更新缓存就行了.

另外 Cloudreve 不是目录程序.

**Comment by GreenTeodoro839** [comment]
> 任何非官方承认的 API 或接口都不能用于生产环境, 这些接口无法保持稳定性和可用性添加支持只会无限增加对接口的维护成本.
> 
> Sharelist 这类目录程序基本无需考虑数据库主动不主动的, 只要定时从接口拉取文件列表更新缓存就行了.
> 
> 另外 Cloudreve 不是目录程序.

不过百度网盘官方提供api，不知道可否尝试

**Comment by cxplay** [comment]
那你最好单独提 issue, 把 API 文档贴上

**Comment by GreenTeodoro839** [comment]
这是百度网盘api文档，希望作者能尝试一下
https://pan.baidu.com/union/doc/
